opendatahub-io/odh-dashboard

frontend/src/__mocks__/mlmd/mockGetArtifactsByContext.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/compareRuns.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/compareRuns.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/executions.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/mlmdUtils.ts
frontend/src/concepts/pipelines/content/compareRuns/CompareRunsNoMetrics.tsx
frontend/src/concepts/pipelines/content/compareRuns/metricsSection/confusionMatrix/ConfusionMatrixCompare.tsx
frontend/src/concepts/pipelines/content/compareRuns/metricsSection/markdown/MarkdownCompare.tsx
frontend/src/concepts/pipelines/content/compareRuns/metricsSection/roc/RocCurveCompare.tsx
frontend/src/concepts/pipelines/content/compareRuns/metricsSection/scalar/ScalarMetricTable.tsx
frontend/src/pages/pipelines/global/experiments/compareRuns/CompareRunsMetricsSection.tsx

JIRA: [RHOAIENG-8406](https://issues.redhat.com/browse/RHOAIENG-8406)
Add an empty state when there are runs selected but no metrics to compare for all the tabs in compare run metrics section.
1. Create some runs with a pipeline that will not generate metrics
2. Go to compare runs page
3. See the metrics section, check and uncheck the runs
4. Make sure the empty state is shown as described
Added some cypress tests to verify the empty state

Add no metrics state for compare runs metrics section

---

backend/src/routes/api/operator-subscription-status/index.ts
backend/src/types.ts
backend/src/utils/resourceUtils.ts
frontend/src/__tests__/cypress/cypress/pages/aboutDialog.ts
frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/application.cy.ts
frontend/src/app/AboutDialog.scss
frontend/src/app/AboutDialog.tsx
frontend/src/app/App.tsx
frontend/src/app/AppContext.ts
frontend/src/app/HeaderTools.tsx
frontend/src/app/__tests__/AboutDialog.spec.tsx
frontend/src/k8sTypes.ts
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ManageInferenceServiceModal.spec.tsx
frontend/src/redux/selectors/index.ts
frontend/src/services/operatorSubscriptionStatusService.ts
frontend/src/types.ts
frontend/src/utilities/useWatchOperatorSubscriptionStatus.tsx

Closes: [RHOAIENG-4220](https://issues.redhat.com/browse/RHOAIENG-4220)
Add an About dialog to the Dashboard UI using existing PatternFLy component.
https://www.patternfly.org/components/about-modal
This provides a place for UI users to see the current product version they are using, which can be useful for support and analytics use cases. 
Tested locally
Added e2e mock tests
Added jest test

[RHOAIENG-6982] About Modal in the Dashboard

---

frontend/src/__tests__/cypress/test-variables.yml.example

Closes: [RHOAIENG-7791](https://issues.redhat.com/browse/RHOAIENG-7791)
This  is the template file which holds the structure of the configuration file and the default values for test.
The values are being generated dynamically during runtime and populate fields of template file data and generates the final content for the actual configuration file.
Need to run the jenkins pipeline job for cypress tests

RHOAIENG-7791:Add test configuration template file for cypress tests

---

backend/src/routes/api/service/modelregistry/index.ts
backend/src/utils/proxy.ts

https://issues.redhat.com/browse/RHOAIENG-8891
Model registry had a slight variation in requires for their backend proxy than the other proxy services and therefore the common proxy util was not usable without being refactored.
Find a cluster with model-registry setup or perform the setup on your cluster.
Login to the cluster on the terminal.
- run a local backend: `npm run start:dev`
- run a local frontend: `npm run start:dev`
- from the root dir, `NAMESPACE=default make port-forward`
- make sure the env var `MODEL_REGISTRY_NAME` in the `.env.development` is correct for your cluster
- visit `http://localhost:4010/modelRegistry`
Make sure the page loads and functions as expected
None, unfortunately backend doesn't have tests at this time.
If you …

refactor model registry proxy onto proxy util

---

frontend/src/pages/home/projects/ProjectsLoading.tsx

https://issues.redhat.com/browse/RHOAIENG-8788
Update loading state for project section in home page. 
Before
After
Tested manually. Reload home screen to test Projects loading state. 
N/A - no changes to functionality 

[RHOAIENG-8788]: Update loading state for project section in home page

---

frontend/src/__tests__/cypress/cypress/pages/modelRegistrySettings.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistrySettings/modelRegistrySettings.cy.ts
frontend/src/k8sTypes.ts
frontend/src/pages/modelRegistrySettings/CreateModal.tsx
frontend/src/pages/modelRegistrySettings/ModelRegistriesTableRow.tsx

Closes: 8454
- add display name, resource name, description fields to MR.
- use the namedescriptionfield component for creation form.
- use resourcenametooltip for table name, add description underneath
ran tests, updated where necessary, tested manually by creating MRs and viewing on the table.
minor updates

feat(MR): 8454 add namedesc fields

---

frontend/src/__tests__/cypress/cypress/pages/userManagement.ts
frontend/src/components/MultiSelection.tsx
frontend/src/pages/groupSettings/GroupSettings.tsx
frontend/src/pages/groupSettings/groupTypes.ts

Closes: [RHOAIENG-421](https://issues.redhat.com/browse/RHOAIENG-421)
This PR updates the deprecated Patternfly 4 select component with the PF5 [multi select component](https://www.patternfly.org/components/menus/select/#multiple-typeahead-with-chips)
This is tested with `npm run test` as well as on localhost, and using the Cypress tests in `userManagement.cy.ts`
No new tests were added as there are no functionality changes 

Update depricated PF multiselect component 

---

frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTable.tsx
frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTableRow.tsx

Closes: [RHOAIENG-6851](https://issues.redhat.com/browse/RHOAIENG-6851)
The edit and delete buttons did not perform their actions if the serving runtime was not found. Both the edit and delete modals handle the action when the serving runtime is not passed so the modals can still be launched.
None

[RHOAIENG-6851] Fix for Edit and Delete actions in Model tab

---

frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectList.cy.ts
frontend/src/api/useAccessReview.ts
frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx
frontend/src/pages/projects/screens/projects/useProjectTableRowItems.ts

Closes [RHOAIENG-1163](https://issues.redhat.com/browse/RHOAIENG-1163) and https://github.com/opendatahub-io/odh-dashboard/issues/1932
When a user doesn't have permission to Edit Project, Delete Project, or Edit Permissions, the actions will be grayed out and disabled. This prevents a user from trying to do the action and later getting an insufficient permissions error. (We decided to not hide them, because then we would have to hide the entire kebab menu if there were no permissions, which requires a check on display of the table.)
This also defers the project permission checks until the menu will be opened. This saves us from having to make 1 (or more) api calls per project being displayed on the table on page load. 
Tested locally with varying user permissions. Checked that projects …

Defer project kebab check and disable

---

frontend/src/__mocks__/mockInferenceServiceK8sResource.ts
frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts
frontend/src/api/k8s/__tests__/inferenceServices.spec.ts
frontend/src/api/k8s/inferenceServices.ts
frontend/src/k8sTypes.ts
frontend/src/pages/modelServing/screens/global/InferenceServiceEndpoint.tsx
frontend/src/pages/modelServing/screens/global/InternalServicePopoverContent.tsx
frontend/src/pages/modelServing/screens/projects/__tests__/utils.spec.ts
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
frontend/src/pages/modelServing/screens/projects/utils.ts

Closes https://issues.redhat.com/browse/RHOAIENG-6651
Add support for public/private routes in kserve
1. Install ODH Operator 2.14 (needed for the changes in kserve controller)
2. Create a new project
3. Deploy a single model server without a public route
4. Check that the internal route points to the right service
5. Now edit the deployment and make it public
6. Check that you end up getting a url
Added integration tests and unit test.

Add support for public routes in kserve

---

backend/src/routes/api/namespaces/namespaceUtils.ts
backend/src/routes/api/nb-events/eventUtils.ts
backend/src/routes/api/nb-events/index.ts

Closes: [RHOAIENG-536](https://issues.redhat.com/browse/RHOAIENG-536)
Previously, a user without 'get' permissions for notebooks could access the API url for notebook events. Now, they are unable to, and they would be greeted with a `403` status code.
Steps to test:
1. Create a new notebook server (`Applications` -> `Enabled` ->  `Jupyter`)
2. That itself should be an event. If time has elapsed since then, just open up the notebook server, make a file, and type in `print("hello world")` or anything else that would constitute an event.
3. Create a user with no permissions
4. Change the URL in `dev_impersonate` to:
```
const url = `https://oauth.${namedHost}/oauth/authorize?response_type=token&client_id=openshift-challenging-client`; 
```
We are changing the URL because currently it doesn't …

disable access to notebook from other users

---

backend/src/routes/api/nb-events/index.ts

Closes: [RHOAIENG-536](https://issues.redhat.com/browse/RHOAIENG-536)
SSAR failure should show 403 not 404 (followup pr)
SSAR failure should show 403 not 404
reproduction steps: https://github.com/opendatahub-io/odh-dashboard/pull/3010

fixed nb-events SSAR failure status code

---

frontend/src/components/table/TableBase.tsx

JIRA: https://issues.redhat.com/browse/RHOAIENG-9675
One-liner fix. Added `aria-label` to checkbox table header.
Go to the pipelines table (or any table with checkboxes), and make sure there are no a11y warnings in the browser console.
N/A

Fix a11y warning on checkbox table header

---

frontend/src/pages/modelRegistry/ModelRegistryRoutes.tsx
frontend/src/pages/modelRegistry/screens/RegisterModel/RegisterModel.tsx
frontend/src/pages/modelRegistry/screens/RegisterModel/useRegisterModelData.ts
frontend/src/pages/modelRegistry/screens/RegisteredModels/RegisteredModelListView.tsx
frontend/src/pages/modelRegistry/screens/RegisteredModels/RegisteredModelsTableToolbar.tsx
frontend/src/pages/modelRegistry/screens/routeUtils.ts

Closes: https://issues.redhat.com/browse/RHOAIENG-9913
Skeleton for the register model page/form
ran through and made sure validation works for submit button, radio buttons work for displaying different location inputs
none yet - skeleton
go to a MR, add `/registerModel` to the URL, see validation and radio buttons work properly.

feat(MR): register model page skeleton

---

frontend/src/__mocks__/mockPipelinePodK8sResource.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/topology.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelinesTopology.cy.ts
frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetailsActions.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRecurringRun/PipelineRecurringRunDetailsActions.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetailsActions.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx

closes: https://issues.redhat.com/browse/RHOAIENG-4705
1. removes tooltip on logs search icon
2. fixed logs tab overflowing action dropdown
3. Now when you pause a running a pipeline log, if the task completes while still paused, it will remain paused. When you unpause the logs, it will fetch the rest of the logs and the pause icon will be hidden due to the task completing.
1. run a pipeline
2. go to one of the nodes pods tab
4. verify tooltip doesn't exist on pod search icon
5. pause the logs before the finish
6. wait for the node to complete
7. verify pod is still paused
8. unpause
9. verify it fetches the rest and the pause icon disappears
added test for pausing logs
not really any ux changes, just removing a tooltip and …

Fix LogViewerSearch styling issue and improve functionality

---

frontend/src/concepts/k8s/utils.ts
frontend/src/pages/modelRegistry/screens/ModelRegistrySelector.tsx

closes: https://issues.redhat.com/browse/RHOAIENG-8453
closes: https://issues.redhat.com/browse/RHOAIENG-10025
add display name and description (truncated with tooltip) in the selector, add a "view description" button link off to the side with a popver containing the name/description.
tested with MRs that have display name different from resource name. tested with MR that contains a long description, short description, no description.
just adding some info, tests all still pass
test selector looks correct with various display name, resource name, and description.

feat(mr): add display name and description for mr selector

---

frontend/src/concepts/pipelines/kfTypes.ts
frontend/src/concepts/pipelines/topology/__tests__/parseUtils.spec.ts
frontend/src/concepts/pipelines/topology/parseUtils.ts

JIRA: https://issues.redhat.com/browse/RHOAIENG-9327
Add detection for edge cases where `pvcMount` is another format that includes `constant` field as the PVC name.
1. Upload the pipeline in the ticket and create a run with it
2. Check the `Volumes` tab, make sure the volume name is correctly shown as `your-pvc-name` instead of `No value`.
Updated unit test to verify the change.

Display pipeline run volume name correctly

---

frontend/src/__tests__/cypress/cypress/pages/pipelines/createRunPage.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/experiments.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/experiments.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineCreateRuns.cy.ts
frontend/src/concepts/pipelines/content/createRun/RunPage.tsx
frontend/src/pages/pipelines/global/experiments/useDefaultExperiment.ts

JIRA: [RHOAIENG-9429](https://issues.redhat.com/browse/RHOAIENG-9429)
When creating a run/schedule from the pipelines page, it will auto-fill the experiment field as `Default` if the `Default` experiment is in the selector (not archived on the create run page).
1. Create a run from the pipeline version row or details page
2. See if the `Default` experiment is auto-filled
3. Archive the `Default` experiment
4. When creating a run, the experiment field should be empty
5. When creating a schedule, the experiment field should still be set to `Default`
6. Try to duplicate a run/schedule, make sure this change doesn't have an impact on the field
7. Try to create a run/schedule from the experiment runs page, make sure this change doesn't have an impact on the field
8. Try to switch between …

Set experiment as Default on create run/schedule page

---

frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeDetailsTab.tsx

JIRA: https://issues.redhat.com/browse/RHOAIENG-8903
We should not translate the state in the side panel because it's only used to show the PF topology node status. Instead, we should show whatever state is returned by the KFP server.
Follow the instructions in the JIRA ticket, check the node status, and make sure the text is correct and the same as the KFP UI.
N/A

Show correct state text on pipeline run node side drawer

---

frontend/src/__mocks__/mockDashboardConfig.ts
frontend/src/__tests__/cypress/cypress/pages/workbench.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/workbench.cy.ts
frontend/src/pages/projects/screens/detail/notebooks/NotebookList.tsx
frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx
frontend/src/pages/projects/screens/detail/notebooks/useNotebookDeploymentSize.ts
frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
frontend/src/pages/projects/screens/spawner/useNotebookSizeState.ts
frontend/src/pages/projects/utils.ts

Closes: https://issues.redhat.com/browse/RHOAIENG-578
When an administrator updates the notebook sizes, the container size now changes to `Custom` instead of `Unknown`.
<details>
<summary>Workbenches table(not expanded):</summary>
</details>
<details>
<summary>Workbenches table(expanded):</summary>
</details>
</details>
<details>
<summary>Edit workbenches for deleted notebook sizes(expanded):</summary>
</details>
1. Create a workbench with any container size
2. Go to console and update the `notebookSizes` in `OdhDashboardConfig`([for example](https://github.com/opendatahub-io/odh-dashboard/issues/1513#issue-1803778644))
3. Go to your Workbenches table on your dashboard and see `Custom` in the `Container size`. Expand the table row and see `limits` and `requests`.
4. Edit this workbench > …

Add custom container size to workbenches table

---

frontend/src/__tests__/cypress/cypress/pages/pipelines/createRunPage.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesTable.ts
frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineCreateRuns.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelinesList.cy.ts
frontend/src/concepts/k8s/NameDescriptionField.tsx
frontend/src/concepts/pipelines/apiHooks/useAllPipelineVersions.ts
frontend/src/concepts/pipelines/apiHooks/usePipelines.ts
frontend/src/concepts/pipelines/content/DuplicateNameHelperText.tsx
frontend/src/concepts/pipelines/content/createRun/RunForm.tsx
frontend/src/concepts/pipelines/content/import/PipelineImportModal.tsx
frontend/src/concepts/pipelines/content/import/PipelineVersionImportModal.tsx
frontend/src/concepts/pipelines/utils.ts

Closes: [RHOAIENG-4702](https://issues.redhat.com/browse/RHOAIENG-4702)
- Added duplicate name info helper text when uploading a pipeline, version or creating a run or schedule.
- Fixed issue where if > 20 versions existed within a particular pipeline, only the latest 20 were being used in the list of versions used on every runs table - this would result in pipeline versions not rendered in the table - instead just a hyphen, and consequently effected the list of pipeline versions available for the table filter toolbar dropdown.
- Fixed duplicate running of ~30 tests that was leading to an unnecessary additional ~2.5 minutes of CI cypress test runtime.
Manual testing, and updated existing tests to verify the existence of the duplicate name helper text.
Creation of runs, schedules, and …

[RHOAIENG-4702] Improve unique naming for runs and versions in pipelines

---

frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx

Closes: [RHOAIENG-1210](https://issues.redhat.com/browse/RHOAIENG-1210)
This PR will add `notebooks.opendatahub.io/notebook-restart=true` to notebook CR to restart the pod after updating config map.
1. Create a workbench with adding the Environment variables (ConfigMap Environment variables type).
2.  after creation, update the config map. You can see that the pods will restart.
NA, added an annotation. 

Restart the pods after updating configMap in workbench

---

frontend/src/__mocks__/index.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelinesList.cy.ts
frontend/src/concepts/pipelines/content/import/PipelineImportModal.tsx

https://issues.redhat.com/browse/RHOAIENG-7943
Redirect to the pipeline details page after a pipeline is created via URL or uploaded using a yaml file.
Manually tested & updated pipeline creation cypress tests to verify the user is redirected to the appropriate URL.
Import a pipeline using a yaml file and a URL, verify both methods lead to being redirected to the pipeline version details page.

[RHOAIENG-7943] Navigate to pipeline details on import

---

backend/src/utils/constants.ts
docs/dashboard-config.md
manifests/rhoai/shared/odhdashboardconfig/odhdashboardconfig.yaml

Closes: https://issues.redhat.com/browse/RHOAIENG-8575
Sets `disableKServeMetrics` feature flag to false.
Deploy on server, verify `disableKServeMetrics` flag is set to false by default. 
N/A

Enable KServeMetrics by default (RHOAIENG-8575)

---

CONTRIBUTING.md
docs/definition-of-done.md
docs/definition-of-ready.md

Closes https://issues.redhat.com/browse/RHOAIENG-10271 
We need our [Definition of Done](https://docs.google.com/document/d/1A3Y4P04MVlovOK1XvUZL8SpQ0wY94LwQsxe8DwEGoGE/edit) and [Definition of Ready](https://docs.google.com/document/d/1JP8FlysPrsEH5mfx4Jq6t-jr1XBIORS5PoRpeSMkNt8/edit) docs moved into markdown files in the docs folder and our contribution markdown file updated to point at those
N/A (Non-code change)
N/A

Add definition of ready and done

---

frontend/src/concepts/pipelines/content/import/PipelineImportModal.tsx
frontend/src/concepts/pipelines/content/import/PipelineVersionImportModal.tsx

https://issues.redhat.com/browse/RHOAIENG-10489
Reset the duplicate name warning flag on modal close for the pipeline upload and pipeline version upload modals
Manually tested by triggering the info text using duplicate names in both modals, then closing and re-opening those modals verifying the info text is reset.

[RHOAIENG-10489] reset duplicate name warning for pipeline and version upload modals

---

frontend/src/__tests__/cypress/cypress/pages/pipelines/topology.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts

[RHOAIENG-10454](https://issues.redhat.com/browse/RHOAIENG-10454)
The reloading of pipelines after uploading a new pipeline in the 2 tests updated here was causing the page to reload and in some cases that reload would impede on the redirect to the pipeline details page.
2 cypress tests were updated to address the issue

[RHOAIENG-10454] mock cypress test flake: pipelines.cy.ts 'imports a new pipeline'

---

backend/src/types.ts
backend/src/utils/constants.ts
docs/dashboard-config.md
frontend/src/__mocks__/mockDashboardConfig.ts
frontend/src/concepts/areas/const.ts
frontend/src/concepts/areas/types.ts
frontend/src/concepts/connectionTypes/useConnectionTypesEnabled.ts
frontend/src/k8sTypes.ts
manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
manifests/rhoai/shared/odhdashboardconfig/odhdashboardconfig.yaml

https://issues.redhat.com/browse/RHOAIENG-10564
Adds a new feature flag to the odhDashboardConfig for the upcoming work on the custom data connection types feature.
- Pushed the updated CRD to my personal cluster with the new flags and verified the flag being received in network requests.
- Running the frontend and backend locally, got the new flag saw it in the browser console.
- turned the flag to true and false to verify it switches
- no tests added, not really much to test yet? other feature flags don't have tests either

Add disableConnectionTypes feature flag

---

frontend/src/__mocks__/mockConnectionType.ts
frontend/src/concepts/connectionTypes/__tests__/utils.spec.ts
frontend/src/concepts/connectionTypes/types.ts
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/k8sTypes.ts

https://issues.redhat.com/browse/RHOAIENG-10310
Defines the typescript types used to describe connection types. 
A connection type is stored in a config map. 
A connection type is an ordered collection of field descriptors. Each descriptor typed by a unique string identifier which identifies the corresponding field type. The field type is used to associate a rendered which knows how to consume their specific properties.
Note. The current field types are based on a non-finalized version of the UX. Therefore the fields and field properties are subject to change. However the general structure will remain the same.
Added mock util to be used for early development and testing.
Added serialization/deserialization utils to convert a configmap with `string` data into a json object and back. These …

define the connection type config map typescript types

---

frontend/src/pages/modelRegistrySettings/ModelRegistriesTableRow.tsx
frontend/src/pages/modelRegistrySettings/ModelRegistryTableRowStatus.tsx
frontend/src/pages/modelRegistrySettings/__tests__/ModelRegistryTableRowStatus.spec.tsx
frontend/src/pages/modelRegistrySettings/columns.ts

https://issues.redhat.com/browse/RHOAIENG-7485
Show various statuses depending on model registry conditions within a new column labeled "Status" for the model registry list table page.
**Degrading popover**
**Unavailable with multiple messages**
(cc @yih-wang)
Manually tested with sample data, created unit tests with possible status scenarios

[RHOAIENG-7485] Admin - Database status in Model Registry Table

---

backend/src/routes/api/connection-types/connectionTypeUtils.ts
backend/src/routes/api/connection-types/index.ts
backend/src/types.ts
frontend/src/concepts/connectionTypes/__tests__/utils.spec.ts
frontend/src/concepts/connectionTypes/types.ts
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/services/connectionTypesService.ts

[RHOAIENG-10311](https://issues.redhat.com/browse/RHOAIENG-10311)
Adds backend endpoints for ConnectionType objects.
Includes GET, POST, PUSH, PATH, DELETE.
Adds a frontend service to access these endpoints.
This has been tested locally by adding temporary calls in the UI
Tests will need to be added when the UI accesses these new functions.

[RHOAIENG-10311] Backend service endpoints for connection types

---

frontend/package-lock.json
frontend/package.json
frontend/src/concepts/analyticsTracking/initSegment.tsx

Closes https://issues.redhat.com/browse/RHOAIENG-9754
Use the npm-version of the Segment client (Analytics(-next).js) and don't load it on the fly 
on the first load of the UI. 
This change has no impact of the visible appearance and functionality of the UI.
Manual testing by looking at network tab of the browser tools in non-dev mode
See previous item
cc @christianvogt @andrewballantyne 
Superseeds #3012

[RHOAIENG-9754] Use the npm-Version of the Segment libraries.

---

frontend/src/concepts/pipelines/content/pipelineSelector/useCreateSelectors.ts

https://issues.redhat.com/browse/RHOAIENG-10208
Fixes issue using the Experiment dropdown with 10+ experiments within a project, clicking "View more" led to an API error which is displayed to the user in the form of an Alert, and the user was unable to view more than the latest 10 experiments on the Create Run page.
Manually tested by opening the Experiment dropdown on the Create Run page within a project that has 10+ experiments and clicking the "View more" link.

[RHOAIENG-10208] Pipeline Run creation - Experiment dropdown - 'View more' causes API error

---

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineCreateRuns.cy.ts
frontend/src/concepts/pipelines/content/createRun/contentSections/TriggerTypeField.tsx

https://issues.redhat.com/browse/RHOAIENG-9537
the user can end up with an error while submitting a scheduled run because of white space to avoid this I have trim white spaces from cron string
1. Create a scheduled run
2. Change the Trigger type to cron
3. at @every 5m with a space at the end
4. check if the scheduled run is created successfully without any error

trim cron string

---

frontend/src/concepts/topology/PipelineTaskEdge.tsx
frontend/src/concepts/topology/factories.ts

https://issues.redhat.com/browse/RHOAIENG-7066
Allowing  users to select pipeline edges to highlight the dependency route
1. Import a pipeline
2. Click on the edge of the pipeline topology and check whether it highlight the dependency route
N/A

Allow users to select pipeline edges to highlight the dependency route

---

frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts
frontend/src/__tests__/cypress/cypress/pages/modelRegistry/registerModelPage.ts
frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelRegistry.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/registerModel.cy.ts
frontend/src/api/modelRegistry/__tests__/custom.spec.ts
frontend/src/api/modelRegistry/custom.ts
frontend/src/concepts/modelRegistry/__tests__/utils.spec.ts
frontend/src/concepts/modelRegistry/context/useModelRegistryAPIState.tsx
frontend/src/concepts/modelRegistry/types.ts
frontend/src/concepts/modelRegistry/utils.ts
frontend/src/pages/modelRegistry/screens/RegisterModel/RegisterModel.tsx
frontend/src/pages/modelRegistry/screens/RegisterModel/useRegisterModelData.ts
frontend/src/pages/modelRegistry/screens/RegisterModel/utils.ts

Closes https://issues.redhat.com/browse/RHOAIENG-2240
Unblocks and partially addresses https://issues.redhat.com/browse/RHOAIENG-7571
Implements API calls on submitting the Register Model form, and adjusts some presentation details of the page to match the latest mockups.
* Adds new API client functions to `useModelRegistryAPIState`: `createModelVersionForRegisteredModel` and `createModelArtifactForModelVersion`. The existing `createModelVersion` and `createModelArtifact` functions use the base endpoint for those resources, but (1) in the case of creating artifacts we need to use the sub-route under the model version URL to associate the artifact with that version, and (2) it made sense to be consistent and do the same for creating versions under the associated model's URL.
* Adds the …

API integration for Register Model form

---

.github/pull_request_template.md

We auto-squash now with the merge bot. Removing the review checklist item that says squash commits from the template.

Remove squash commits checklist item

---

frontend/src/pages/projects/screens/projects/NotebookStateStatus.tsx

closes: [RHOAIENG-5084](https://issues.redhat.com/browse/RHOAIENG-5084)
In the big "UI Refresh", it seems that the `doListen` got set to false where it shouldn't have. Previously here: https://github.com/opendatahub-io/odh-dashboard/commit/d5124d28feb555770aa2c8b7f00e36783a4ebdc7#diff-2c0ccfc2c2e7347604445b4d648b808d62e96fe6fd36c05cec54ea14bcd3d10dL46
Setting it to true for the project list view fixes the issue.
It's interesting that the status is used in the projects page and the notebook page, but is updated differently. The notebook tab has `doListen={false}` and updates fine (must update at a different level instead of from the statusToggle component itself).
Tested that the status updates properly and doesn't continue to make network calls for the status after getting the update. …

fix(ProjectList): notebook status listen and update

---

frontend/src/__mocks__/mockRoleBindingK8sResource.ts
frontend/src/__tests__/cypress/cypress/pages/modelRegistryPermissions.ts
frontend/src/__tests__/cypress/cypress/pages/permissions.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistrySettings/modelRegistryPermissions.cy.ts
frontend/src/concepts/projects/utils.ts
frontend/src/concepts/roleBinding/RoleBindingPermissionsNameInput.tsx
frontend/src/concepts/roleBinding/RoleBindingPermissionsTable.tsx
frontend/src/concepts/roleBinding/RoleBindingPermissionsTableRow.tsx
frontend/src/concepts/roleBinding/RoleBindingPermissionsTableRowAdd.tsx
frontend/src/concepts/roleBinding/RoleBindingPermissionsTableSection.tsx
frontend/src/concepts/roleBinding/utils.ts
frontend/src/k8sTypes.ts
frontend/src/pages/modelRegistrySettings/ModelRegistriesPermissions.tsx
frontend/src/pages/modelRegistrySettings/ProjectsTab/ProjectsSettingsTab.tsx

Closes: [RHOAIENG-8632](https://issues.redhat.com/browse/RHOAIENG-8632)
This PR aims to add projects tab under MR Permissions.
In MR permission, click on Projects tab
create/ edit/ delete rolebindings for projects.
Added cypress tests.

Admin - Model Registry RBAC Management Projects

---

frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetailsActions.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRecurringRun/PipelineRecurringRunDetailsActions.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetailsActions.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/DownloadDropdown.tsx
frontend/src/concepts/pipelines/content/tables/PipelineFilterBar.tsx
frontend/src/concepts/projects/ProjectSelector.tsx

Towards [RHOAIENG-2404](https://issues.redhat.com/browse/RHOAIENG-2404)
Replaces the usages of Dropdown from the `@patternfly/react-core/deprecated` package with the Dropdown in `@patternfly/react-core` package
Tested manually
The following components are effected:
- Data Science Pipelines -> Project select
- Data Science Pipelines -> click a pipeline: Actions select.
- Data Science Pipelines -> Actions -> View schedules -> click a schedule -> Actions select
- Data Science Pipelines -> expand a pipeline -> kebab from a pipeline version -> view runs -> click a run -> Action select
- Data Science Pipelines -> expand a pipeline -> kebab from a pipeline version -> view runs -> click a run -> select a node -> side panel logs tab -> download button

[RHOAIENG-2404] Replace PF deprecated Dropdown components with PF core Dropdowns

---

frontend/src/pages/projects/screens/detail/notebooks/__tests__/useNotebookImageData.spec.ts
frontend/src/pages/projects/screens/detail/notebooks/useNotebookImageData.ts

Closes: [RHOAIENG-8553](https://issues.redhat.com/browse/RHOAIENG-8553)
Fixes a bug where a workbench created with a custom images shows a "! Deleted" flag when not true
Steps to reproduce this bug is in the JIRA ticket linked. Note the cluster type. I'm unable to reproduce this bug on a ROSA cluster currently. 
Please reach out to me on slack if you need help testing this.
`npm run test`. Locally on an OCP cluster
A jest test was added that checks if the fix fails when the image doesn't match
Before:
After:

Fix for untrue !Deleted flag

---

frontend/src/concepts/analyticsTracking/segmentIOUtils.tsx
frontend/src/concepts/analyticsTracking/trackingProperties.ts
frontend/src/concepts/analyticsTracking/useSegmentTracking.ts
frontend/src/concepts/analyticsTracking/useTrackUser.ts

Closes https://issues.redhat.com/browse/RHOAIENG-9232
Put obtaining user properties into its own hook. This is meant to be extended in the future.
Manual testing by developer by inspecting browser console and (for non-dev mode) network tab.
cc @andrewballantyne

RHOAIENG-9232 Create useTrackUser

---

frontend/src/__mocks__/mockModelArtifact.ts
frontend/src/__mocks__/mockSecretK8sResource.ts
frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDeployModal.ts
frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionDeploy.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionDetails.cy.ts
frontend/src/concepts/modelRegistry/context/ModelRegistryContext.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsHeaderActions.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsTableRow.tsx
frontend/src/pages/modelRegistry/screens/RegisteredModels/RegisteredModelTableRow.tsx
frontend/src/pages/modelRegistry/screens/RegisteredModels/useLabeledDataConnections.ts
frontend/src/pages/modelRegistry/screens/RegisteredModels/usePrefillDeployModalFromModelRegistry.ts
frontend/src/pages/modelRegistry/screens/RegisteredModels/useProjectErrorForRegisteredModel.ts
frontend/src/pages/modelRegistry/screens/RegisteredModels/useRegisteredModelDeployInfo.ts
frontend/src/pages/modelRegistry/screens/__tests__/useProjectErrorForRegisteredModel.spec.ts
frontend/src/pages/modelRegistry/screens/components/DeployRegisteredModelModal.tsx
frontend/src/pages/modelServing/customServingRuntimes/utils.ts
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionExistingField.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionSection.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceFrameworkSection.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ProjectSelector.tsx
frontend/src/pages/modelServing/screens/projects/__tests__/utils.spec.ts
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
frontend/src/pages/modelServing/screens/projects/utils.ts
frontend/src/pages/modelServing/screens/types.ts

JIRA: [RHOAIENG-8396](https://issues.redhat.com/browse/RHOAIENG-8396)
When you deploy a model based on a model registry, the following modal will show:
If anything wrong with the project, the corresponding error message will pop up:
Otherwise, the current KServe modal or InferenceService modal will pop up depending on the project's serving platform. The name will be pre-filled as `{modelName} - {versionName}`:
There is a helper text if the model registry version contains a prompt model format:
The data connections part will be decided by the model artifact URI.
If there are more than 1 matches, we don't pre-select the data connection:
If there is only one match, we pre-select the recommended data connection:
If there is no match, we pre-select the new data connection field:
The path will …

Add deployment modal for model registry

---

backend/src/utils/resourceUtils.ts

https://issues.redhat.com/browse/RHOAIENG-8816
Only create accelerator when nvidia type nodes are detected from the server's list of nodes.
Manually tested. This doesn't seem to be re-creatable in dev without some hard-coded intervention. The condition to create the accelerator has been adjusted to make sure nvidia nodes exist, however I was not able to simulate the "configured" state being true, which is the other part of the condition.
Testing this is not straight forward and requires deleting resources in the openshift console and restarting the backend afterwards + manually editing the condition to bypass the "configured" state. I believe this change is one we can have the reporter of the issue test once released to be sure this resolves his issue.
1. Update …

[RHOAIENG-8816] Automatic discovery of Accelerator profile handles AMD GPUs like they were NVIDIA

---

frontend/src/__mocks__/mockArtifactStorage.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/compareRuns.ts
frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/compareRuns.cy.ts
frontend/src/concepts/pipelines/apiHooks/__tests__/useArtifactStorage.spec.ts
frontend/src/concepts/pipelines/apiHooks/useArtifactStorage.ts
frontend/src/concepts/pipelines/content/compareRuns/metricsSection/markdown/MarkdownCompare.tsx
frontend/src/concepts/pipelines/content/compareRuns/metricsSection/markdown/useFetchMarkdownMaps.ts
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/ArtifactVisualization.tsx
manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml

https://issues.redhat.com/browse/RHOAIENG-9738
Updated the `useArtifactStorage` function to make it more stable
Updated the `manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml`
Updated the compare run section to use the new hook `useArtifactStorage`
Updated the artifact nodes virtualization side drawer panel to use new hook `useArtifactStorage`
Update the crd ,check if disableArtifactsAPI is false the fetch is from the DSP server
when disableArtifactsAPI is true and disableS3Endpoint is false check the fetching occurs from backend 
while running locally 
`open -n -a /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --args --user-data-dir="/tmp/chrome_dev_test" --disable-web-security` to avoid cors error
1. Upload a pipeline with metrics 
2. Create a run with …

 Use artifact downloader hook in fetching markdown html

---

frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersions.cy.ts
frontend/src/pages/modelRegistry/ModelRegistryCoreLoader.tsx

Closes: [RHOAIENG-10503](https://issues.redhat.com/browse/RHOAIENG-10503)
This PR aims to update the links to Registered Models to use the right registry name.
- Create a model registry that starts with an earlier alphabetical letter than `modelregistry-sample` so it will show up above that in the selector. (currently on the modelregistry-ui cluster the "dallas-mr" registry is in this position.
- Navigate to the Model Registry page / registered models table and select the `modelregistry-sample` registry.
- Reload the page.
- Click on a registered model and observe that the right registry is in the URL.
Updated cypress test.

Update links to Registered models

---

frontend/src/__mocks__/mockArtifactStorage.ts
frontend/src/__mocks__/mockPipelineVersionsProxy.ts
frontend/src/__mocks__/mockRunKF.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/topology.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/artifacts.cy.ts
frontend/src/concepts/pipelines/content/artifacts/ArtifactUriLink.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/__tests__/PipelineRunDrawerRightContent.spec.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/ArtifactNodeDetails.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/__tests__/ArtifactNodeDrawerContent.spec.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsInputOutput.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsPrintKeyValues.tsx
frontend/src/concepts/pipelines/kfTypes.ts
frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/ArtifactDetails.tsx
frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/ArtifactOverviewDetails.tsx
frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactsTable.tsx
frontend/src/pages/pipelines/global/experiments/artifacts/__tests__/ArtifactDetails.spec.tsx
frontend/src/pages/pipelines/global/experiments/artifacts/__tests__/ArtifactsTable.spec.tsx
frontend/src/pages/pipelines/global/experiments/artifacts/constants.ts
frontend/src/pages/pipelines/global/experiments/artifacts/utils.ts
frontend/src/utilities/__tests__/string.spec.ts
frontend/src/utilities/string.ts

Closes: [RHOAIENG-9699](https://issues.redhat.com/browse/RHOAIENG-9699)
Refractored the Artifact URI to use `useArtifactStorage` to get the artifact uri.
It opens new tab 
https://github.com/user-attachments/assets/a711430c-5581-4aac-bab4-db5ffa74506b
If both artifactURI and s3Endpoint is disabled it only shows a text url
Try changing feature flags, disableArtifactsAPI and disableS3Endpoint.
* disableArtifactsAPI: false disableS3Endpoint: true => new tab (for models it downloads)
* disableArtifactsAPI: false disableS3Endpoint: false => new tab (for models it downloads)
* disableArtifactsAPI: true disableS3Endpoint: false => new tab
* disableArtifactsAPI: true disableS3Endpoint: true => just text url
Added cypress test to check the artifact uri in pipeline run details page. Modified the …

Use artifact downloader hook to get the artifact URI

---

frontend/src/concepts/connectionTypes/fields/ConnectionTypeFormFields.tsx
frontend/src/concepts/dashboard/DashboardModalFooter.tsx
frontend/src/pages/connectionTypes/create/ConnectionTypeFieldModal.tsx
frontend/src/pages/connectionTypes/create/ConnectionTypeSectionModal.tsx
frontend/src/pages/connectionTypes/create/CreateConnectionTypeFieldsTable.tsx
frontend/src/pages/connectionTypes/create/CreateConnectionTypeFieldsTableRow.tsx
frontend/src/pages/connectionTypes/create/CreateConnectionTypePage.tsx
frontend/src/pages/connectionTypes/create/__tests__/ConnectionTypeSectionModal.spec.tsx

https://issues.redhat.com/browse/RHOAIENG-10317
Adds the ability to create, edit and delete field sections.
Tests will be added. This PR provides some plumbing for integrating the add field modal as well.
Creation modal:
Editing modal:
Popovers:
Empty field state:
Section row with actions:
Buttons beneath fields table:
Construct a connection type:
<details>
<summary>ConfigMap</summary>
```
kind: ConfigMap
apiVersion: v1
metadata:
name: test-ct
namespace: opendatahub
labels:
opendatahub.io/connection-type: 'true'
annotations:
opendatahub.io/enabled: 'true'
opendatahub.io/username: test
openshift.io/description: this is the description
openshift.io/display-name: test connection type
```
</details>
Go to `/connectionTypes/duplicate/test-ct`. …

add actions to create and edit section fields

---

frontend/src/concepts/connectionTypes/types.ts
frontend/src/pages/connectionTypes/fields/ConnectionTypeDataFieldModal.tsx
frontend/src/pages/connectionTypes/fields/TextForm.tsx
frontend/src/pages/connectionTypes/fields/__tests__/AddConnectionTypeFieldModal.spec.tsx
frontend/src/pages/connectionTypes/manage/ConnectionTypeFieldModal.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTable.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTableRow.tsx

Closes [RHOAIENG-10318](https://issues.redhat.com/browse/RHOAIENG-10318)
Adds a modal to allow adding of a field to a connection type
Add tests for adding/editing/duplicating fields in a connection type.

[RHOAIENG-10318] Add connection type field modal

---

frontend/src/__tests__/cypress/cypress/pages/modelRegistry/registerModelPage.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/registerModel.cy.ts
frontend/src/concepts/projects/ProjectSelector.tsx
frontend/src/pages/modelRegistry/screens/RegisterModel/ConnectionDropdown.tsx
frontend/src/pages/modelRegistry/screens/RegisterModel/ConnectionModal.tsx
frontend/src/pages/modelRegistry/screens/RegisterModel/RegisterModel.scss
frontend/src/pages/modelRegistry/screens/RegisterModel/RegisterModel.tsx

closes: https://issues.redhat.com/browse/RHOAIENG-9914
On the register modal page, there will be a new button to the right of Model Location / Object Storage (when selected) that says "Autofill from data connection".
Clicking that should bring up a modal with a project selector and a data connection selector. Selecting a project will populate the data connection selector with it's available data connections that contain a bucket.
Selecting a data connection and hitting the submit button will populate the Object Storage region/endpoint/bucket in the register model form.
Made sure that projects appear in project selector, and data connection is disabled with a note about selecting a project.
Upon selecting a project, data connection will either be populated or remain disabled with a note …

feat(RegisterModel): 9914 autofill connection

---

frontend/src/pages/connectionTypes/EmptyConnectionTypes.tsx

Super simple change to route the user to the `connectionTypes/create` url. (same as the non empty create button)
<details>
<summary> screenshots </summary>
Before:
After:
</details
Locally.
No tests added since it's very simple
To test, go to `/connectionTypes` route and make sure all are delete so you see the empty table.
none 

Fix disabled create button for connection types empty table

---

Dockerfile

Closes: [RHOAIENG-8824](https://issues.redhat.com/browse/RHOAIENG-8824)
This PR aims to update the dockerfile to use numeric user id.
-  `make build ` to build the image using podman
-  `make push` to push the image to the `IMAGE_REPOSITORY` specified in `.env.local` file
-  deploy the image and check the dashboard container image to have `UID` as 1001
NA

Update dockerfile to use numeric user id

---

frontend/src/k8sTypes.ts

https://issues.redhat.com/browse/RHOAIENG-1104
Adding a type for the storage class config object to be a part of the existing annotations type.

[RHOAIENG-1104] Design custom annotation type to track storage class metadata

---

frontend/src/__mocks__/mockStartNotebookData.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/applications/notebookServer.cy.ts
frontend/src/api/k8s/__tests__/inferenceServices.spec.ts
frontend/src/api/k8s/__tests__/servingRuntimes.spec.ts
frontend/src/api/k8s/__tests__/utils.spec.ts
frontend/src/api/k8s/inferenceServices.ts
frontend/src/api/k8s/notebooks.ts
frontend/src/api/k8s/servingRuntimes.ts
frontend/src/api/k8s/utils.ts
frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeDetails.tsx
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
frontend/src/pages/modelServing/screens/projects/useServingAcceleratorProfile.ts
frontend/src/pages/modelServing/screens/projects/utils.ts
frontend/src/pages/modelServing/utils.ts
frontend/src/pages/notebookController/screens/server/AcceleratorProfileSelectField.tsx
frontend/src/pages/notebookController/screens/server/NotebookServerDetails.tsx
frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx
frontend/src/pages/projects/screens/detail/notebooks/useNotebookAcceleratorProfile.ts
frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
frontend/src/pages/projects/types.ts
frontend/src/utilities/tolerations.ts
frontend/src/utilities/useAcceleratorProfileState.ts

https://issues.redhat.com/browse/RHOAIENG-9368
refactors accelerator hook to now only show the current state of the resource's accelerator
moved all selected accelerator to the accelerator dropdown component
existing tests pass
and
1. create a accelerator from the admin panel
2. create workbench and make sure that the option shows up in the workbench under accelerators
3. check that save works
4. do this for model serving modal too
5. disable the accelerator from he admin page
6. edit the workbench and verify that the disabled option is still selectable
7. delete the accelerator
8. edit the workbench
9. verify that a use existing settings option is available
there is existing test coverage …

Refactor accelerator profile state hooks to no longer manage its own selected

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionArchive.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/registeredModelArchive.cy.ts
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsHeaderActions.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelDetailsView.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsHeaderActions.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsTableRow.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionArchiveDetails.tsx
frontend/src/pages/modelRegistry/screens/RegisteredModels/RegisteredModelTableRow.tsx
frontend/src/pages/modelRegistry/screens/RegisteredModelsArchive/RegisteredModelArchiveDetails.tsx
frontend/src/pages/modelRegistry/screens/__tests__/utils.spec.ts
frontend/src/pages/modelRegistry/screens/utils.ts

https://issues.redhat.com/browse/RHOAIENG-10997)
Removed the workaround for Patching the fields from API. As described in the issue, the description, labels, and Properties should remain when I archive the model. See attached Screenshots 
Tested on the UI see above sreenshots
I've deleted some tests that were related to the Patching functions, Also updated some fields in the tests now to match the behavior as the remaining fields in those tests are not needed anymore, because they are coming from a different place now.

 removed the use of Patch Body

---

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineCreateRuns.cy.ts
frontend/src/concepts/pipelines/content/createRun/RunForm.tsx
frontend/src/concepts/pipelines/content/createRun/contentSections/ProjectAndExperimentSection.tsx
frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts

JIRA: [RHOAIENG-10401](https://issues.redhat.com/browse/RHOAIENG-10401)
When user creates/duplicates a schedule, prevent user from selecting the archived experiments from the selector and only show active experiments.
1. Create `ExperimentA`
2. Create a schedule `ScheduleA` with `ExperimentA`
3. Archive `ExperimentA`
4. Create a schedule, make sure you cannot select `ExperimentA` in the experiment selector
5. Duplicate the `ScheduleA`, make sure `ExperimentA` is not pre-filled
Added/changed some cypress tests to better test selecting archived experiments on a create schedules page.

Show only active experiments on create/duplicate schedules page

---

frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionArchive.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersions.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/registeredModelArchive.cy.ts
frontend/src/pages/modelRegistry/ModelRegistryRoutes.tsx

Closes: [RHOAIENG-10812](https://issues.redhat.com/browse/RHOAIENG-10812)
When you reach these routes by clicking a model or a version (on both the main models/versions tables and the archived models/versions tables):
- /modelRegistry/:name/registeredModels/:registeredModelId
- /modelRegistry/:name/registeredModels/archive/:registeredModelId
- /modelRegistry/:name/registeredModels/:registeredModelId/versions/:modelVersionId
- /modelRegistry/:name/registeredModels/:registeredModelId/versions/archive/:modelVersionId
You are redirected to the first tab of the page for that version/model, respectively:
- /modelRegistry/:name/registeredModels/:registeredModelId/versions
- /modelRegistry/:name/registeredModels/archive/:registeredModelId/versions
- …

Enable browser back button after clicking on Registered model/version

---

frontend/.slignore.generated
frontend/package-lock.json
frontend/package.json

https://issues.redhat.com/browse/RHOAIENG-11838
To test the sea-light poc on odh-nightly
1. added slnodejs devdependency
2. Added slignore.generated file : To ignore files from being scanned

added sealight configuration

---

frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDeployModal.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/executions.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/experiments.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunTable.ts
frontend/src/__tests__/cypress/cypress/support/commands/application.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionArchive.cy.ts
frontend/src/pages/modelRegistry/screens/components/DeployRegisteredModelModal.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ProjectSelector.tsx

https://issues.redhat.com/browse/RHOAIENG-11791
The `DeployRegistrationModelModal` renders 3 separate modals depending on the project selected. When the cypress tests switches modals, it acts too fast to interact again with the dropdown only to have the UI unmount the current modal and mount a new one. Since our custom commands store the selector dom node in order to perform multiple actions, this node becomes stale and no longer applicable to the current DOM. Thus the command fails.
Changed the selector for clicking on them project selector menu item to be two separate commands.
Had to update the code to move the project selector open state management to the parent so that all modal instances share the same state, otherwise the dropdown could close when rendering a new modal.
Run cypress …

fix cypress flake in modelVersionDeployModal.cy.ts

---

frontend/src/__mocks__/mockConnectionType.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/connectionTypes/createConnectionType.cy.ts
frontend/src/concepts/connectionTypes/CategoryLabel.tsx
frontend/src/concepts/connectionTypes/ConnectionTypePreview.tsx
frontend/src/concepts/connectionTypes/ConnectionTypePreviewDrawer.tsx
frontend/src/concepts/connectionTypes/__tests__/utils.spec.ts
frontend/src/concepts/connectionTypes/createConnectionTypeUtils.ts
frontend/src/concepts/connectionTypes/fields/BooleanFormField.tsx
frontend/src/concepts/connectionTypes/fields/ConnectionTypeFormFields.tsx
frontend/src/concepts/connectionTypes/fields/DataFormFieldGroup.tsx
frontend/src/concepts/connectionTypes/fields/DefaultValueTextRenderer.tsx
frontend/src/concepts/connectionTypes/fields/DropdownFormField.tsx
frontend/src/concepts/connectionTypes/fields/HiddenFormField.tsx
frontend/src/concepts/connectionTypes/fields/TextFormField.tsx
frontend/src/concepts/connectionTypes/fields/__tests__/ConnectionTypeFormFields.spec.tsx
frontend/src/concepts/connectionTypes/fields/__tests__/DropdownFormField.spec.tsx
frontend/src/concepts/connectionTypes/fields/__tests__/HiddenFormField.spec.tsx
frontend/src/concepts/connectionTypes/types.ts
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/pages/connectionTypes/ConnectionTypesTableRow.tsx
frontend/src/pages/connectionTypes/manage/ConnectionTypeDataFieldModal.tsx
frontend/src/pages/connectionTypes/manage/DataFieldPropertiesForm.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTable.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTableRow.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypePage.tsx

https://issues.redhat.com/browse/RHOAIENG-11539
Updated the preview header to use a white background and made it sticky to the top so that the scrollable area is the drawer body.
No connection type name or description:
Has connection type name, description and category:
Popovers for field descriptions:
Updated dropdown review to include values:
Preview hidden default read only values. Use popover to see real value.
Additional changes:
- update the config map types to include category
- updated serialization utils to handle category
- added reusable `CategoryLabel` component
- adjusted field table column widths
- used `React.memo` for performance improvements
Existing tests. Manually. For the most part this is just look and feel changes.
- Enable the connection types …

update preview panel to align with latest ux

---

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineCreateRuns.cy.ts
frontend/src/concepts/k8s/NameDescriptionField.tsx
frontend/src/concepts/pipelines/content/createRun/RunForm.tsx
frontend/src/concepts/pipelines/content/createRun/const.ts

JIRA: https://issues.redhat.com/browse/RHOAIENG-11058
Added a helper text and a length limit to the text area of the description field on the create run/schedule page.
1. Go to the create run/schedule page
2. Check if the helper text "Cannot exceed 255 characters" is under the description field
3. Try to type in a long string, and you cannot type more when you reach the limit of 255 characters
Added some cypress checks in the current test cases to make sure the input field character length is limited.

Add character length limit to the description field on create run form

---

frontend/src/pages/connectionTypes/manage/ConnectionTypeDataFieldModal.tsx

Fixes a lint error that got merged.
Ran the lint command
None

Fix for lint error

---

backend/src/routes/api/storage-class/index.ts
backend/src/routes/api/storage-class/utils.ts
backend/src/types.ts
frontend/src/services/StorageClassService.ts
manifests/core-bases/base/role.yaml

closes: https://issues.redhat.com/browse/RHOAIENG-11855
adds backend route `/api/storage-class/{name}/metadata` and a frontend service function to call it
backend -- no tests
none

add backend route for storage class metadata

---

frontend/src/__tests__/cypress/cypress/pages/connectionTypes.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/connectionTypes/createConnectionType.cy.ts
frontend/src/pages/connectionTypes/manage/ConnectionTypeFieldMoveModal.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTable.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTableRow.tsx

Closes https://issues.redhat.com/browse/RHOAIENG-11540
- Renames the "Delete" to "Remove" in the page for modifying the fields on the connection type.
- Adds a kebab action to data field types, to move to it to a new section
- action doesn't show up if there are 0 section rows
- if there is only 1 section, it will be greyed out in the modal
Tested locally, changes are isolated to the affected area.
Added test to click the modal and make sure the rows are moved correctly

Update connection type field action "Move to section heading"

---

frontend/src/concepts/connectionTypes/types.ts
frontend/src/pages/connectionTypes/manage/ConnectionTypeDataFieldModal.tsx
frontend/src/pages/connectionTypes/manage/ConnectionTypeFieldModal.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTable.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTableRow.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypePage.tsx
frontend/src/pages/connectionTypes/manage/__tests__/ConnectionTypeDataFieldModal.spec.tsx
frontend/src/pages/connectionTypes/manage/__tests__/ManageConnectionTypeFieldsTableRow.spec.tsx
frontend/src/pages/connectionTypes/manage/fieldTableColumns.ts

https://issues.redhat.com/browse/RHOAIENG-11538
Provides user with feedback when creating fields which have conflicting env var values.
Note that microcopy is not finalized.
- Go to `Settings` -> `Connection types` as an admin with the connection type feature flag enabled.
- Create a new connection type.
- Add two fields with the same env var name.
- Observe the error in the table and fields modal and that the form save button is disabled
- Edit a conflicting field to have a unique env var
- Observe the form save button is no longer disabled (providing the rest of the form is valid)
Added unit tests.

surface conflicting env var names as warnings and errors

---

backend/src/types.ts
backend/src/utils/constants.ts
docs/dashboard-config.md
frontend/src/__mocks__/index.ts
frontend/src/__mocks__/mockDashboardConfig.ts
frontend/src/__mocks__/mockStorageClasses.ts
frontend/src/__tests__/cypress/cypress/pages/storageClasses.ts
frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/storageClasses/storageClasses.cy.ts
frontend/src/app/AppRoutes.tsx
frontend/src/concepts/areas/const.ts
frontend/src/concepts/areas/types.ts
frontend/src/concepts/design/utils.ts
frontend/src/images/empty-state-storage-classes.svg
frontend/src/k8sTypes.ts
frontend/src/pages/projects/screens/spawner/storage/usePreferredStorageClass.ts
frontend/src/pages/storageClasses/StorageClassesPage.tsx
frontend/src/pages/storageClasses/index.ts
frontend/src/pages/storageClasses/utils.ts
frontend/src/utilities/NavData.tsx
manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
manifests/rhoai/shared/odhdashboardconfig/odhdashboardconfig.yaml

https://issues.redhat.com/browse/RHOAIENG-1105
- Added feature flag for storage classes
- Showing empty state when no storage classes are found
- Showing blank page in anticipation for a table to be rendered as a part of [RHOAIENG-1106](https://issues.redhat.com/browse/RHOAIENG-1106) coming soon
- Added logic on render to add annotations to storage class metadata if those storage classes are absent of the `sc-config` annotation.
**Empty state**
**With feature turned off or as a non-admin user**
(cc @xianli123)
Manual testing with creation of annotations, although that data can be inspected in the network tab. This will be visualized in [RHOAIENG-1106](https://issues.redhat.com//browse/RHOAIENG-1106), so the expectation is to test this logic more thoroughly there. Otherwise, cypress tests …

[RHOAIENG-1105] Add Storage Class section in Admin Panel and Feature Flag

---

frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/ArtifactNodeDrawerContent.tsx

JIRA: [RHOAIENG-11567](https://issues.redhat.com/browse/RHOAIENG-11567)
Add a style to prevent tabs from shrinking.
1. Create a run using the metrics pipeline
2. Click on the artifact nodes
3. Make sure the tabs are not hidden anymore when you click on the `Visualization` tab
N/A, a small UX fix.

Fix Tab layout issue on Artifact node side panel

---

frontend/package-lock.json
frontend/package.json
frontend/src/concepts/connectionTypes/fields/FileFormField.tsx
frontend/src/concepts/connectionTypes/fields/__tests__/FileFormField.spec.tsx
frontend/src/concepts/connectionTypes/fields/fieldUtils.ts
frontend/src/concepts/connectionTypes/types.ts
frontend/src/pages/connectionTypes/manage/ConnectionTypeDataFieldModal.tsx
frontend/src/pages/connectionTypes/manage/advanced/DataFieldAdvancedPropertiesForm.tsx
frontend/src/pages/connectionTypes/manage/advanced/FileUploadAdvancedPropertiesForm.tsx
frontend/src/pages/connectionTypes/manage/advanced/FileUploadExtensionRow.tsx
frontend/src/pages/connectionTypes/manage/advanced/__tests__/FileUploadAdvancedPropertiesForm.spec.tsx
frontend/src/pages/connectionTypes/manage/manageFieldUtils.ts

Closes [RHOAIENG-11530](https://issues.redhat.com/browse/RHOAIENG-11530)
Adds the field field advanced settings for connection type fields
Tested manually. Added RTL tests.

[RHOAIENG-11530] Add file field advanced settings for connection type fields

---

frontend/src/__tests__/cypress/cypress/pages/connectionTypes.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/connectionTypes/createConnectionType.cy.ts
frontend/src/components/MultiSelection.tsx
frontend/src/pages/connectionTypes/ConnectionTypesTableRow.tsx
frontend/src/pages/connectionTypes/columns.ts
frontend/src/pages/connectionTypes/const.ts
frontend/src/pages/connectionTypes/manage/ManageConnectionTypePage.tsx

Closes: [RHOAIENG-11536](https://issues.redhat.com/browse/RHOAIENG-11536)
Create a new category option on the create connection type page. This allows users to pick from predetermined categories, or create their own.
Tested locally
Cypress tests are being created. Still in progress.

Add category option to create connection type

---

frontend/src/concepts/connectionTypes/fields/DropdownFormField.tsx
frontend/src/pages/connectionTypes/manage/advanced/DataFieldAdvancedPropertiesForm.tsx
frontend/src/pages/connectionTypes/manage/advanced/DropdownAdvancedPropertiesForm.tsx
frontend/src/pages/connectionTypes/manage/advanced/__tests__/DropdownAdvancedPropertiesForm.spec.tsx
frontend/src/pages/connectionTypes/manage/manageFieldUtils.ts

Completes https://issues.redhat.com/browse/RHOAIENG-10322
- This adds the "Advanced settings" dropdown / expandable form to the dropdown creation modal. It is defaulted to open when you select the dropdown variant (because there are required options).
- The single select variant is automatically selected.
- The table has draggable rows, and they can be deleted and added. A minimum of 1 row will always exist. 
- The "Dropdown item values" is the required field, so an option can exist without a label. In this scenario, I default the label to be the value. 
- The default values will be updated with the list of options from the table row. Blank options will not be added. If an option has a blank value, it will still be added, but the option will be disabled until a value is added. 
- If there …

Add connection type dropdown advanced properties

---

frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx
frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTable.tsx
frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTable.tsx
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx

https://issues.redhat.com/browse/RHOAIENG-11049
Add Segment tracking for Model serving Deploy/Edit/Delete  operations
Manual testing by clicking in the UI and watching the events fired in the browser console
* Deploy a Model in Kserve (submit / cancel cases)  
* Deploy a Model server, (submit / cancel )
* Edit a Model server (submit /cancel)
* Deploy a model on a model server
Those should all yield lines like the following in the browser console, when in dev-mode. The `outcome` property should match the action submit/cancel of the dialog.
> Telemetry event triggered: Model Deployed - {"outcome":"cancel","type":"multi"} for version v2.25.0 
> Telemetry event triggered: Model Server Modified - {"outcome":"submit","type":"OpenVINO Model Server","size":"Small","success":true} for version …

RHOAIENG-11049 Add tracking for model serving

---

frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetails.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersions.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionArchiveDetails.tsx
frontend/src/pages/modelRegistry/screens/RegisteredModelsArchive/RegisteredModelArchiveDetails.tsx

closes: https://issues.redhat.com/browse/RHOAIENG-12026
truncates long descriptions in the header for mr details 
ran locally
no logical change, no test impact
description is truncated if it would extend multiple lines, on hover a tooltip will show up

feat(MR detail): truncate description in header

---

frontend/src/concepts/modelRegistrySettings/useModelRegistriesBackend.ts

Closes: [RHOAIENG-11278](https://issues.redhat.com/browse/RHOAIENG-11278)
This PR aims to update the status of the model registry by adding refresh interval.
1. create a model registry.
2. check that the status of the model registry will update when it is available.
NA

Update model registry status

---

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineRuns.cy.ts
frontend/src/concepts/pipelines/content/compareRuns/CompareRunTableToolbar.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableToolbar.tsx

JIRA: https://issues.redhat.com/browse/RHOAIENG-11239
Removed "Paused" and "Cancelled" from the status filter on the pipeline runs table
1. Go to pipeline runs table (either under pipeline version or experiment context)
2. Choose the filter by `Status`
3. Check the filters, and make sure there is no `Cancelled` and `Paused` in the selection
Added a cypress test to verify that Cancelled and Paused are not in the filter dropdown.

Remove Cancelled and Paused from pipeline runs status filter

---

frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/__tests__/PipelineRunDrawerRightContent.spec.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/ArtifactNodeDrawerContent.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/__tests__/ArtifactNodeDrawerContent.spec.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/utils.ts
frontend/src/concepts/topology/customNodes/ArtifactTaskNode.tsx

JIRA: https://issues.redhat.com/browse/RHOAIENG-11570
Change the icon of all the artifact nodes with a visualization metrics (system.Metrics, system.ClassificationMetrics, system.HTML, system.Markdown, system.SlicedClassificationMetrics) to the monitoring icon. And hide the `Visualization` side panel tab for those non-metrics type artifact nodes (system.Model, system.Dataset, system.Artifact)
Monitoring icon:
No "visualization" tab:
1. Create a run with the metrics visualization pipeline
2. Make sure all the artifact nodes are using the Monitoring icon
3. Create a run with the iris training pipeline
4. Make sure the artifacts nodes with the type of `system.Model` or `system.Dataset` don't have the Visualization tab in the side panel when clicking the node
Add unit tests to verify the …

Change metrics artifact node icon and hide non-metrics artifact visualization tab

---

frontend/src/concepts/pipelines/context/useManageElyraSecret.ts

JIRA: https://issues.redhat.com/browse/RHOAIENG-10719
Add a ref to prevent simultaneously creating/replacing the elyra secret, and rewrite the hook a little bit to make it more readable.
2. Configure a pipeline server
3. Make sure there is no 409 conflict error message in the console when creating `ds-pipeline-config` secret
N/A, needs e2e live test for that which https://github.com/opendatahub-io/odh-dashboard/pull/3028 will cover.

Prevent duplicity post of creating/replacing elyra secret

---

frontend/src/__mocks__/mockModelVersion.ts
frontend/src/__tests__/cypress/cypress/pages/modelRegistry/registeredModelArchive.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelRegistry.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersions.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/registeredModelArchive.cy.ts
frontend/src/concepts/modelRegistry/types.ts
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionListView.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsTable.tsx
frontend/src/pages/modelRegistry/screens/RegisteredModels/RegisteredModelTable.tsx
frontend/src/pages/modelRegistry/screens/RegisteredModels/RegisteredModelsTableColumns.ts
frontend/src/pages/modelRegistry/screens/RegisteredModelsArchive/RegisteredModelsArchiveTable.tsx
frontend/src/pages/modelRegistry/screens/__tests__/utils.spec.ts
frontend/src/pages/modelRegistry/screens/components/ModelTimestamp.tsx
frontend/src/pages/modelRegistry/screens/utils.ts

Closes: [RHOAIENG-11505](https://issues.redhat.com/browse/RHOAIENG-11505)
This PR aims to update the default sort state of registered models list, model versions list, archived models list. 
- Verify that the default sort state set to `Last modified` for registered models list, archived models list. 
- No default sort state for model versions list and versions are sorted by create time.
Added unit test.
Added and updated Cypress tests.

Update MR tables default sort state

---

frontend/src/pages/connectionTypes/manage/advanced/DropdownAdvancedPropertiesForm.tsx
frontend/src/pages/connectionTypes/manage/advanced/__tests__/DropdownAdvancedPropertiesForm.spec.tsx

Closes https://issues.redhat.com/browse/RHOAIENG-10322
Adds error text if there are duplicate entries for the labels and columns row.
The first entry will not have the error text, only the subsequent entries, which is similar to the file upload.  
Has been tested locally and jest unit tests have been added 

Add error text for duplicate label and value

---

docs/dev-setup.md

Due to issues with various optional dependencies (who don't report errors until you made the dev dependencies), we need to be on v18.18 of Node. Our previous recommended versions did not match this, updating them.
I matched the NPM version that was auto upgraded when I switched my Node.

Upversion Node & NPM to match other dependency needs

---

frontend/src/__mocks__/mlmd/mockGetExecutionsByContext.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/topology.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelinesTopology.cy.ts
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightTabs.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTabStatus.tsx

closes: https://issues.redhat.com/browse/RHOAIENG-10000
adds a condition to show a cache message in pipeline logs when the task is cached
create a pipeline run that will cache a task
check that the log tab is visible with the cache alert
added a test for the alert
cc @yannnz This is the UX I went with. @kaedward for wording

add cache message in logs

---

frontend/src/__tests__/cypress/cypress/tests/mocked/connectionTypes/createConnectionType.cy.ts
frontend/src/concepts/connectionTypes/ConnectionTypePreviewDrawer.tsx
frontend/src/pages/connectionTypes/ConnectionTypesTable.tsx
frontend/src/pages/connectionTypes/ConnectionTypesTableToolbar.tsx
frontend/src/pages/connectionTypes/const.ts
frontend/src/pages/connectionTypes/manage/ConnectionTypeDataFieldModal.tsx
frontend/src/pages/connectionTypes/manage/ConnectionTypeFieldRemoveModal.tsx
frontend/src/pages/connectionTypes/manage/DuplicateConnectionTypePage.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTableRow.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypePage.tsx

Closes [RHOAIENG-11528](https://issues.redhat.com/browse/RHOAIENG-11528)
Updates the connection type admin screens with the latest micro copy found in [Figma mocks](https://www.figma.com/proto/97akqulXiGIGtvxkdPLjMm/Data-connections-enhancement?node-id=1168-156206&t=QAO1jyYn2P3dP1yX-0&scaling=scale-down&content-scaling=fixed&page-id=24%3A74&starting-point-node-id=1168%3A156206)
Updated e2e tests where necessary

[RHOAIENG-11528] Update connection types admin screens with final microcopy

---

backend/src/utils/componentUtils.ts

Closes: https://issues.redhat.com/browse/RHOAIENG-1135
Added a catch block to `fastify.kube.customObjectsApi.getNamespacedCustomObject`
1. Install an ISV operator(e.g. Elastic(ECK) operator/NVIDIA GPU(Certified) operator).
2. If the corresponding `OdhApplication` isn't present, create the corresponding `OdhApplication` using https://github.com/opendatahub-io/odh-dashboard/blob/main/manifests/rhoai/addon/apps/starburst/starburst-app.yaml with `enabled: true` inside `spec`
3. Go to Dashboard > Enabled and wait for the card to appear.
4. Uninstall the operator and head back to the Enabled page
5. You should not see an `HTTP request failed` page.
6. For the Elastic tile.. when you have the operator installed you shouldn't see `Disabled` in the tile and vice-versa. 
Self checklist (all need to …

Fix error in loading Enabled applications after uninstalling an ISV

---

frontend/src/components/table/TableRowTitleDescription.tsx
frontend/src/concepts/connectionTypes/ConnectionTypePreview.tsx
frontend/src/pages/connectionTypes/ConnectionTypesTable.tsx
frontend/src/pages/connectionTypes/ConnectionTypesTableRow.tsx
frontend/src/pages/connectionTypes/columns.ts

Closes https://issues.redhat.com/browse/RHOAIENG-12443
This is a visual styling change to fix long descriptions. You can still enter really long descripitons, but it won't overflow outside the container the text is in.
I also saw this is a similar issue in the preview page, no idea why. But I fixed that as well.
Before:
After: 
Preview before:
After:
Tested locally
A shared component has been updated, but the new prop is default unsued

Truncate long connection type description

---

frontend/src/__tests__/cypress/cypress/pages/connectionTypes.ts
frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/connectionTypes/createConnectionType.cy.ts
frontend/src/pages/connectionTypes/manage/CreateConnectionTypePage.tsx
frontend/src/pages/connectionTypes/manage/EditConnectionTypePage.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFooter.tsx

Closes [RHOAIENG-12439](https://issues.redhat.com/browse/RHOAIENG-12439)
Fix handling of the error response when creating a connection type.
Tested manually
Added e2e test to verify response error text is shown on the page after an error.

Show connection type creation error message on failure

---

backend/src/routes/api/storage-class/utils.ts
frontend/src/__mocks__/mockStorageClasses.ts
frontend/src/__tests__/cypress/cypress/pages/storageClasses.ts
frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/storageClasses/storageClasses.cy.ts
frontend/src/pages/storageClasses/StorageClassDefaultRadio.tsx
frontend/src/pages/storageClasses/StorageClassEnableSwitch.tsx
frontend/src/pages/storageClasses/StorageClassesPage.tsx
frontend/src/pages/storageClasses/StorageClassesTable.tsx
frontend/src/pages/storageClasses/StorageClassesTableRow.tsx
frontend/src/pages/storageClasses/constants.ts
frontend/src/pages/storageClasses/utils.ts
frontend/src/services/StorageClassService.ts

https://issues.redhat.com/browse/RHOAIENG-1106
Added storage classes table which includes column sorting, labels, popovers, tooltips, requests to update the default or the enabled state of storage classes (the underlying metadata for each row), placeholders for future table related stories.
https://github.com/user-attachments/assets/1b7b71b8-39d0-4f4c-8a04-25be2517630d
(cc @xianli123)
Manual and cypress tests. Running the dev environment via the root directory of the project (npm run dev) and navigating to `/storageClasses?devFeatureFlags=disableStorageClasses` should lead to the storage classes table so long as storage classes exist to be rendered. Here you can compare to the design and interact with the default radio buttons and enable switches to verify that behavior.
Added cypress …

[RHOAIENG-1106] Storage classes table

---

frontend/src/concepts/connectionTypes/fields/UriFormField.tsx
frontend/src/concepts/connectionTypes/fields/__tests__/UriFormField.spec.tsx

Closes [RHOAIENG-12292](https://issues.redhat.com/browse/RHOAIENG-12292)
Fixes the regular expression test for the connection type URI field input
Added additional RTL tests to validate/invalidate different URI entries

Fix for URI form field regex validation

---

frontend/src/utilities/useDraggableTableControlled.ts

https://issues.redhat.com/browse/RHOAIENG-12561
`useDraggableTableControlled` was using `useEffect` to keep track of draggable items internally. While this was functional it would also lead to a double render whenever the incoming items array changed. The negative side effect of this is that the first render would supply data to the consumer that was stale until the next render. As a result, components which rely on object identity of the table items would be rendering against stale data until the new state was applied in the `useEffect`.
As noted in the linked issue, the connection type field would "blip" render an error icon indicating that the field's env var was a duplicate. The cause of this is because the check for duplicates would filter the given row data from the full set of …

remove useEffect from state management in useDraggableTableControlled

---

backend/src/__tests__/imageUtils.spec.ts

We have an issue with where our backend test files are for development -- moving to where the others are. We will follow up with an investigation of our tsconfig to figure out how to fix this more generically.

Move test file -- weird backend setup

---

frontend/src/api/useRulesReview.ts
frontend/src/concepts/modelRegistry/apiHooks/__tests__/useModelRegistryServices.spec.ts
frontend/src/concepts/modelRegistry/apiHooks/useModelRegistryServices.ts
frontend/src/concepts/modelRegistry/context/ModelRegistrySelectorContext.tsx
frontend/src/pages/modelRegistrySettings/ModelRegistrySettings.tsx

https://issues.redhat.com/browse/RHOAIENG-10026
Please verify that the MR selector shows a new registered model, without the need of refreshing a page
on the UI
I had to rewrite a couple of tests to match the new logic

MR selector doesn't update without page reload

---

frontend/src/pages/connectionTypes/manage/ConnectionTypeDataFieldModal.tsx
frontend/src/pages/connectionTypes/manage/ConnectionTypeFieldModal.tsx
frontend/src/pages/connectionTypes/manage/ConnectionTypeSectionModal.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTable.tsx
frontend/src/pages/connectionTypes/manage/__tests__/ConnectionTypeDataFieldModal.spec.tsx
frontend/src/pages/connectionTypes/manage/__tests__/ConnectionTypeSectionModal.spec.tsx

- Auto selects the name field
- update labels that no longer have "field"
- "Text - Short" is auto selected
- field type dropdown no longer has focused styling
- button is now "Save" and not "Edit"
Initial load render screenshot:
Locally, mainly visual changes
The field labels have been changed so the test-id's could also be updated, but I haven't (they still have "field")

Fixes to connection type field modal

---

frontend/src/components/TruncatedText.tsx
frontend/src/concepts/connectionTypes/ConnectionTypePreview.tsx
frontend/src/pages/connectionTypes/ConnectionTypesTableToolbar.tsx
frontend/src/pages/connectionTypes/EmptyConnectionTypes.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTableRow.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypePage.tsx

https://issues.redhat.com/browse/RHOAIENG-12573
Removed the enable checkbox from the type details section which allows it more room to display without text wrapping.
Removed the col span from the section title cell in order to constrain the text to its column.
Added missing icon to search inputs:
Manually.
Visual only changes.
N/A

fix alignment of text for connection type form elements

---

frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ProjectSelector.tsx

Closes: [RHOAIENG-11864](https://issues.redhat.com/browse/RHOAIENG-11864)
Project selector is scrollable in Deploy Model modal in Model Registry
1. Go to Model registry> Select any registered model with versions> Try to Deploy that model version by clicking on `Deploy` by clicking on that kebab menu in that specific row
2. You should see a scroll bar(in case you have many projects) when you click on `Select target project` in `Deploy model`.
Manually and Cypress tests added

Project selector is scrollable in Deploy model modal

---

frontend/src/pages/notebookController/screens/server/AcceleratorProfileSelectField.tsx

JIRA: https://issues.redhat.com/browse/RHOAIENG-12694
Revert the changes made in https://github.com/opendatahub-io/odh-dashboard/pull/3102/files#diff-47693ad1cdd3bf50cbf06a60b941d5af0c9b0478f43311f7eca3e4f7d7972df8 to make the accelerator field non-required as discussed in https://redhat-internal.slack.com/archives/C07CQ4R4HMY/p1725973980856419?thread_ts=1725972888.178819&cid=C07CQ4R4HMY
Verify both the workbench spawner page and model deployment modals, the accelerator field should not be required now.
N/A, one-liner fix on UX, not sure if it is worth the effort to detect the `*` symbol exists...

Make accelorators field not required on workbench spawner page and model deployment modals

---

frontend/src/utilities/NavData.tsx

Closes: [RHOAIENG-12253](https://issues.redhat.com/browse/RHOAIENG-12253)
This PR aims to show the Model Registry above the Model Serving in left navigation.
1. Run `npm run start:dev:ext` in the frontend and see that the Model Registry is above the Model Serving.
NA

Swap the order of Model Registry and Model Serving in left navigation

---

frontend/src/__mocks__/mockConnectionType.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/connectionTypes/createConnectionType.cy.ts
frontend/src/concepts/connectionTypes/__tests__/utils.spec.ts
frontend/src/concepts/connectionTypes/fields/__tests__/BooleanFormField.spec.tsx
frontend/src/concepts/connectionTypes/fields/__tests__/ConnectionTypeDataFormField.spec.tsx
frontend/src/concepts/connectionTypes/fields/__tests__/ConnectionTypeFormFields.spec.tsx
frontend/src/concepts/connectionTypes/fields/__tests__/DefaultValueTextRenderer.spec.tsx
frontend/src/concepts/connectionTypes/fields/__tests__/DropdownFormField.spec.tsx
frontend/src/concepts/connectionTypes/fields/__tests__/FileFormField.spec.tsx
frontend/src/concepts/connectionTypes/fields/__tests__/HiddenFormField.spec.tsx
frontend/src/concepts/connectionTypes/fields/__tests__/NumericFormField.spec.tsx
frontend/src/concepts/connectionTypes/fields/__tests__/ShortTextFormField.spec.tsx
frontend/src/concepts/connectionTypes/fields/__tests__/TextFormField.spec.tsx
frontend/src/concepts/connectionTypes/fields/__tests__/UriFormField.spec.tsx
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/pages/connectionTypes/manage/ConnectionTypeDataFieldModal.tsx
frontend/src/pages/connectionTypes/manage/__tests__/ConnectionTypeDataFieldModal.spec.tsx
frontend/src/pages/connectionTypes/manage/__tests__/ManageConnectionTypeFieldsTableRow.spec.tsx

https://issues.redhat.com/browse/RHOAIENG-12440
Restrict env var names to valid C identifiers as denoted by pattern: `^[_a-zA-Z][_a-zA-Z0-9]*$`
Updated all mocks and tests to conform to the new pattern.
Updated error message
Login as an admin
Go to Settings -> Connection types
Create a new connection type
Add a field
enter valid and invalid values for the env var
Observe the error is displayed and `Add` button disabled when an invalid env var value is entered.
update unit tests

update valid env var pattern

---

backend/src/server.ts

https://issues.redhat.com/browse/RHOAIENG-12443
fastify default `maxParamLength` is 100.
Some of our URLs contain k8s resource names and since a k8s resource name can be up to 253 characters, we get invalid routes:
Create a connection type with a name longer than 100 characters
Attempt to edit the connection type.
Same thing can be tested with accelerator profiles.
N/A

update fastify maxParamLength to 253 for support max k8s names

---

frontend/package-lock.json
frontend/package.json

JIRA: [RHOAIENG-11990](https://issues.redhat.com/browse/RHOAIENG-11990)
Cherry-pick the commit https://github.com/opendatahub-io/odh-dashboard/commit/8f7c866ae0fe192f1d2a405187d8b61e3857de36 to fix the CVE in RHOAI 2.10, which is the v2.23.0 here.

[V2.23.0/RHOAI 2.10]: CVE-2024-43788 odh-dashboard-container: DOM Clobbering vulnerability in AutoPublicPathRuntimeModule

---

frontend/src/__tests__/cypress/cypress/pages/projects.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectList.cy.ts
frontend/src/pages/projects/screens/projects/ProjectLink.tsx
frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx

Closes [RHOAIENG-10493](https://issues.redhat.com/browse/RHOAIENG-10493)
Adds the project description to the name column in the projects list view
Manually, added e2e test check
None
/cc @tobiastal

Add projects' descriptions to projects list view

---

frontend/src/__tests__/cypress/cypress/pages/pipelines/experiments.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/experiments.cy.ts
frontend/src/concepts/pipelines/content/tables/columns.ts
frontend/src/concepts/pipelines/content/tables/experiment/ExperimentTableRow.tsx

https://issues.redhat.com/browse/RHOAIENG-11499
Removed the separate description column and  have the description underneath the resource name for the experiments table. and archive experiment table
1. Go to the experiment Page 
2. Check whether the description column is not present
3. check whether the description is present underneath the resource name and gets truncated when > 2 lines

change description format within tables

---

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineRuns.cy.ts
frontend/src/concepts/pipelines/content/compareRuns/metricsSection/roc/RocCurveTable.tsx
frontend/src/concepts/pipelines/content/tables/experiment/ExperimentTableBase.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTable.tsx

JIRA: https://issues.redhat.com/browse/RHOAIENG-11428
(This should also fixes https://issues.redhat.com/browse/RHOAIENG-11383)
Change pagination to compact style at 3 tables.
Experiments table:
Pipeline schedules table:
Compare run ROC curve table:
This should cover all the tables in the pipeline area
Check all the pages in the pipelines and experiments area and make sure all the paginations are in the compact style.
Modify the cypress tests because some paginations don't have the page number input anymore.

Change pagination to compact style for all pipeline tables

---

frontend/src/__tests__/cypress/cypress/pages/connectionTypes.ts
frontend/src/components/TruncatedText.tsx
frontend/src/components/table/TableRowTitleDescription.tsx

Closes [RHOAIENG-12566](https://issues.redhat.com/browse/RHOAIENG-12566)
Determine if the text to be displayed will be truncated and if so wrap it with the tooltip otherwise just show the text.
Also fixes an issue causing a `validateDomNesting` issue for the Connection Types list page.
Tested Home page project cards, documentation cards, and connection type descriptions (in table and in preview pane).
None, visual change only.

Don't show tooltip on truncated text that isn't truncated

---

frontend/src/__tests__/cypress/cypress/pages/projects.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectList.cy.ts
frontend/src/components/PopoverListContent.tsx
frontend/src/pages/projects/screens/projects/EmptyProjects.tsx
frontend/src/pages/projects/screens/projects/ProjectListView.tsx
frontend/src/pages/projects/screens/projects/ProjectsToolbar.tsx
frontend/src/pages/projects/screens/projects/const.ts

Closes [RHOAIENG-10496](https://issues.redhat.com/browse/RHOAIENG-10496)
Update the Project table Filter design pattern:
- Use the attribute value filter and chip component
- Allow filtering on both Name and User at same time, maximum of one of each
- Allow clearing of all filters
- Allow clearing of a single filter in the chip
- Switching between filter type will retain the input in each field. For example, if I choose "Name" and type "admin", then switch to "User" and type "David," and then go back to "Name," I’ll still see "admin" in the search bar under the "Name" filter.
- Adjust the old “No results” to the PatternFly updated no results.
- ## How Has This Been Tested?
Tested Manually, updated e2e tests
Updated e2e tests …

Update Projects view filter bar

---

frontend/src/app/App.scss
frontend/src/concepts/connectionTypes/fields/DropdownFormField.tsx
frontend/src/pages/connectionTypes/ConnectionTypesTable.tsx
frontend/src/pages/connectionTypes/ConnectionTypesTableToolbar.tsx
frontend/src/pages/connectionTypes/const.ts
frontend/src/pages/connectionTypes/manage/ConnectionTypeFieldMoveModal.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTableRow.tsx
frontend/src/pages/connectionTypes/manage/__tests__/ManageConnectionTypeFieldsTableRow.spec.tsx
frontend/src/pages/connectionTypes/manage/fieldTableColumns.ts

https://issues.redhat.com/browse/RHOAIENG-12827
Addresses the following UX items for connection types:
Connection type filter changed from `Created By` to `Creator`:
Microcopy of fields name header updated with spacing around the `/`:
Long env var names get truncated in table. Include screenshots for when env var names are in conflict.
When duplicating a section or data field, the name starts with `Copy of`:
Dropdown field updates.
When no items are defined:
When items are defined but no field name:
When field name is defined (eg. `testing`):
Added spacing between modal description and form by moving the text inside the form which applies the default spacing between form elements:
Manual verification
- Enable the connection types feature flag and navigate to Settings => Connection types …

address UX items with connection types

---

frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx

This section will be looked at again by UX for style post MVP according to this comment by Haley: https://github.com/opendatahub-io/odh-dashboard/pull/3139#issuecomment-2327882720
For now, fixing an issue that was introduced in https://github.com/opendatahub-io/odh-dashboard/pull/3139 which results in an a11y warning. The a11y issue was due to a non datalist element as a child of a datalist. To fix this, I split up the datalist into two and put the heading in between. Had to add some space that was lost after pulling the heading out of the datalist, but this should be temporary with some refresh post-MVP.
no difference, just a small DOM change.
make sure everything looks good and AXE doesn't complain about header being in DL …

fix(5463): fix axe issue in model version detail

---

frontend/src/__tests__/cypress/cypress/pages/connections.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/connections.cy.ts
frontend/src/pages/projects/ProjectDetailsContext.tsx
frontend/src/pages/projects/screens/detail/connections/ConnectionsDeleteModal.tsx
frontend/src/pages/projects/screens/detail/connections/ConnectionsList.tsx
frontend/src/pages/projects/screens/detail/connections/ConnectionsTable.tsx
frontend/src/pages/projects/screens/detail/connections/__tests__/ConnectionsTable.spec.tsx

Closes https://issues.redhat.com/browse/RHOAIENG-11557
Fairly straightforward implementation of the delete modal for the new connections page inside a project. 
To test: if there are existing data connections on a project, you can delete those. otherwise you have to add new secrets from openshift console for that project
Has been tested locally
Cypress test added

Add delete modal for project connections

---

frontend/src/components/ResourceNameTooltip.tsx
frontend/src/components/table/TableRowTitleDescription.tsx
frontend/src/pages/connectionTypes/ConnectionTypesTable.tsx
frontend/src/pages/connectionTypes/ConnectionTypesTableRow.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTableRow.tsx
frontend/src/pages/projects/screens/detail/connections/ConnectionsTableRow.tsx

https://issues.redhat.com/browse/RHOAIENG-12827
Changed table variant to not be compact and truncates long names:
Added name truncation to fields table:
Added name and description truncation to connections table:
For reference. The serving runtimes admin table uses the `ResourceNameTooltip` component and it still looks the same as before vs after
Manually tested by creating resources with long names in the various UI areas.
N/A. Visual only changes.

address truncation of names in connection type tables

---

frontend/src/__tests__/cypress/cypress/pages/storageClasses.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/storageClasses/storageClasses.cy.ts
frontend/src/pages/storageClasses/OpenshiftDefaultLabel.tsx
frontend/src/pages/storageClasses/StorageClassEditModal.tsx
frontend/src/pages/storageClasses/StorageClassesTableRow.tsx

https://issues.redhat.com/browse/RHOAIENG-1108
Edit modal accessed from row actions for the storage class table
**Demo**
https://github.com/user-attachments/assets/5da9dc1f-c141-4bce-9f65-d938c154b435
(cc @xianli123)
1. Run the dev environment via the root directory of the project (npm run dev) and navigating to `/storageClasses?devFeatureFlags=disableStorageClasses` should lead to the storage classes table
2. For 1 or many rows, access row actions from the last column value menu, select "Edit", verify the modal matches the design, verify you cannot submit the modal without a display name
3. Edit the display name & description and submit. Verify the table data is updated with the new name and description …

[RHOAIENG-1108] Edit for Storage Class Table Row

---

frontend/src/api/modelRegistry/__tests__/custom.spec.ts
frontend/src/api/modelRegistry/custom.ts

fixes: https://issues.redhat.com/browse/RHOAIENG-12787
showing with 26 total.
live
archived
changed model registry list limit (via API call) to 99999 as the default was 20 and when we reached 20 we would not see any new model registries. there is a spike to followup by implementing server side filter/sort/pagination https://issues.redhat.com/browse/RHOAIENG-12800
tested locally by adding more than 20 (combo of live and archived) model registries and making sure they are still visible and behavior properly in the table.
updated a test to make sure that the pageSize is included in the call. can't really test beyond that as we mock the data that comes as a response.
see more than 20 registered models in the table
After the PR …

fix(12787): fix 20 qty limit on registered models

---

docs/dev-setup.md

Adds a small blurb to our documents about dev feature flags and how to enable them in the browser using `?devFeatureFlags` query string.

add doc for dev feature flags

---

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/manageRuns.cy.ts
frontend/src/app/App.scss
frontend/src/components/FilterToolbar.tsx
frontend/src/components/table/TableBase.tsx
frontend/src/concepts/connectionTypes/fields/DropdownFormField.tsx
frontend/src/concepts/pipelines/content/compareRuns/CompareRunTableToolbar.tsx
frontend/src/concepts/pipelines/content/tables/experiment/ExperimentTableBase.tsx
frontend/src/concepts/pipelines/content/tables/experiment/ExperimentTableToolbar.tsx
frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTable.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTable.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTableToolbar.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableToolbar.tsx
frontend/src/concepts/pipelines/content/tables/usePipelineFilter.ts
frontend/src/pages/connectionTypes/ConnectionTypesTable.tsx
frontend/src/pages/connectionTypes/ConnectionTypesTableToolbar.tsx
frontend/src/pages/connectionTypes/const.ts
frontend/src/pages/connectionTypes/manage/ConnectionTypeFieldMoveModal.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTableRow.tsx
frontend/src/pages/connectionTypes/manage/__tests__/ManageConnectionTypeFieldsTableRow.spec.tsx
frontend/src/pages/connectionTypes/manage/fieldTableColumns.ts
frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactsTable.tsx
frontend/src/pages/pipelines/global/experiments/compareRuns/ManageRunsPage.tsx
frontend/src/pages/pipelines/global/experiments/compareRuns/ManageRunsTable.tsx
frontend/src/pages/pipelines/global/experiments/executions/ExecutionsTable.tsx
frontend/src/pages/pipelines/global/experiments/executions/ExecutionsTableToolbar.tsx
frontend/src/pages/pipelines/global/pipelines/GlobalPipelinesTableToolbar.tsx
frontend/src/pages/pipelines/global/pipelines/PipelinesView.tsx
frontend/src/pages/projects/screens/projects/ProjectListView.tsx
frontend/src/pages/projects/screens/projects/ProjectsToolbar.tsx

https://issues.redhat.com/browse/RHOAIENG-12827
Manually hitting the different areas of the UI.
Connection type before and after:
Pipelines before and after:
All affected areas:
- `/connectionTypes`
- `/pipelines/<namespace>`
- `/experiments/<namespace>`
- `/experiments/<namespace>/archived`
- `/executions/<namespace>`
- `/artifacts/<namespace>`
- `/projects`
Existing cypress tests.

update table filters into separate chip groups

---

backend/src/routes/api/service/mlmd/index.ts
backend/src/routes/api/service/pipelines/index.ts
backend/src/types.ts
backend/src/utils/proxy.ts

https://issues.redhat.com/browse/RHOAIENG-12000
adds a constructUrl option that can be used instead of manually entering service info for backend proxy helper
uses this for mlmd and pipelines
make sure a pipelines server and mlmd server can fetch data
create a new pipeline server and verify backend is not crashing
none backend 

Update mlmd and pipelines service to use constructUrl for URL generation

---

frontend/src/concepts/modelRegistry/apiHooks/__tests__/usePrefillDeployModalFromModelRegistry.spec.ts
frontend/src/pages/modelRegistry/screens/RegisteredModels/usePrefillDeployModalFromModelRegistry.ts
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx

(https://issues.redhat.com/browse/RHOAIENG-12116)
Updated the UI to enable the Deploy button once all the required fields are filled, without the need to update the pre-filled fields/ 
On the UI in - try to deploy a version of a model with pre-existing connection fields
Added a unit test that makes sure the awsData array never has more than one element per key, as this was the issues that was causing the buggy behavior. ## Request review criteria:

Model registry deploy modal has faulty submit button disable detection

---

frontend/src/__mocks__/mockStorageClasses.ts
frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/clusterStorage.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/workbench.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/storageClasses/storageClasses.cy.ts
frontend/src/api/k8s/pvcs.ts
frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx
frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
frontend/src/pages/projects/screens/spawner/service.ts
frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx
frontend/src/pages/projects/screens/spawner/storage/StorageClassSelect.tsx
frontend/src/pages/projects/screens/spawner/storage/useDefaultStorageClass.ts
frontend/src/pages/projects/screens/spawner/storage/usePreferredStorageClass.ts
frontend/src/pages/projects/screens/spawner/storage/utils.ts
frontend/src/pages/projects/types.ts
frontend/src/pages/storageClasses/utils.ts

Closes: [RHOAIENG-1109](https://issues.redhat.com/browse/RHOAIENG-1109)
This is a continuation of @dpanshug PR
- added default selection
- added default label
- corrected autofill for default
- added alerts for select
> Added new field to select storage class to create pvc.
Create a new cluster storage and you check list of storage classes in the field.
Create new workbench and select storage class in cluster storage.
added test for default being set
@xianli123

Storage class dropdown select

---

frontend/src/concepts/pipelines/content/ViewPipelineServerModal.tsx

https://issues.redhat.com/browse/RHOAIENG-9819
View pipeline server dialog displays Access key and Secret key when the values are from a secret
1. Create a dspa using the following yaml mentioned in the jira issue
2. Check whether the view pipeline server dialog displays the access key and secret key
3. Check whether othetr dspa created from dashboard works same
The cypress test are already present

View pipeline server dialog shows access key and secret key

---

frontend/src/__mocks__/mockStorageClasses.ts
frontend/src/__tests__/cypress/cypress/pages/storageClasses.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/storageClasses/storageClasses.cy.ts
frontend/src/pages/storageClasses/CorruptedMetadataAlert.tsx
frontend/src/pages/storageClasses/ResetCorruptConfigValueAlert.tsx
frontend/src/pages/storageClasses/StorageClassDefaultRadio.tsx
frontend/src/pages/storageClasses/StorageClassEditModal.tsx
frontend/src/pages/storageClasses/StorageClassEnableSwitch.tsx
frontend/src/pages/storageClasses/StorageClassesTableRow.tsx
frontend/src/pages/storageClasses/utils.ts

https://issues.redhat.com/browse/RHOAIENG-12310
Show error/warning alerts for scenarios where individual storage class config values or the entire config are malformed in some way. Introduce abilities to correct those mistakes possibly made via the Openshift UI within the ODH dashboard's storage class table.
**Unreadable config demo:**
https://github.com/user-attachments/assets/86b3cda6-f5c4-41cf-bcdc-92f8787f9b61
**Invalid data, default, enable config values:**
https://github.com/user-attachments/assets/35a9d29c-f889-4101-a2f2-690fe4a8afbb
**Invalid Display name demo:**
https://github.com/user-attachments/assets/af5d969f-450c-4303-a1e5-3057554d114d
**Invalid Description demo:**
https://github.com/user-attachments/assets/8f4b14a3-b97f-4035-b24c-0f8d28a885b7
**Invalid Display name and …

[RHOAIENG-12310] Error cases for storage class admin table

---

backend/src/routes/api/service/mlmd/index.ts
backend/src/routes/api/service/modelregistry/index.ts
backend/src/routes/api/service/pipelines/index.ts
backend/src/routes/api/service/trustyai/index.ts
backend/src/types.ts
backend/src/utils/proxy.ts
frontend/src/__mocks__/mockModelRegistry.ts
frontend/src/k8sTypes.ts
frontend/src/pages/modelRegistrySettings/CreateModal.tsx

Closes https://issues.redhat.com/browse/RHOAIENG-10133 and https://issues.redhat.com/browse/RHOAIENG-9037
Updates `proxyService` to support configuring services with an optional `addressAnnotation`. If the `addressAnnotation` is omitted, the existing behavior will apply, so this PR should not affect the behavior of proxied services other than model registry. If the `addressAnnotation` is `EXTERNAL_REST` or `EXTERNAL_GRPC`, the proxy will fetch the k8s Service named in the request URL and look for a corresponding annotation. If present, the proxy will use that annotation's value as the upstream URL. If it's missing, the proxy will fall back to the existing behavior (constructing an internal `.svc.cluster.local` URL), which will provide compatibility with non-Istio model registry services …

Add support for external routes to proxyService, use for model registry

---

frontend/src/__tests__/cypress/cypress/pages/connectionTypes.ts
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeBreadcrumbs.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypePage.tsx

https://issues.redhat.com/browse/RHOAIENG-12827
Fixes the breadcrumb of the edit connection type page which use to say `Create connection type`.
Updated screenshot:
Manually by editing a connection type.
N/A copy change

update breadcrumb title for edit connection type page

---

frontend/package-lock.json
frontend/package.json

Closes [RHOAIENG-11967](https://issues.redhat.com/browse/RHOAIENG-11967)
Closes [RHOAIENG-11118](https://issues.redhat.com/browse/RHOAIENG-11118)
Update version of @patternfly/react-core to pickup fixes for dropdown and select to prevent inadvertent scrolling when the menu is opened.
Tested locally
Enable connection types
Edit a connection type with enough fields to make the list scroll so that some items are not seen at the top of the page.
Scroll down to the initially non-visible fields.
Open the kebab menu for the fields, verify the menu opens and is visible.
Add a drop down field as one of the fields that are not visible initially.
Open the connection type preview pane.
Scroll down and open the dropdown from the dropdown field.
Verify the menu opens and is visible
None, this is a …

Update @patternfly/react-core for menu fixes

---

frontend/src/__mocks__/mockConnectionType.ts
frontend/src/__tests__/cypress/cypress/pages/connectionTypes.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/connectionTypes/connectionTypes.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/connections.cy.ts
frontend/src/concepts/connectionTypes/CompatibilityLabel.tsx
frontend/src/concepts/connectionTypes/__tests__/utils.spec.ts
frontend/src/concepts/connectionTypes/types.ts
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/pages/connectionTypes/ConnectionTypesTableRow.tsx
frontend/src/pages/connectionTypes/columns.ts
frontend/src/pages/projects/screens/detail/connections/ConnectionsTableRow.tsx
frontend/src/pages/projects/screens/detail/connections/connectionsTableColumns.ts

https://issues.redhat.com/browse/RHOAIENG-13111
Compatibility is assumed based on inspection of the environment variables stored in the connection type and secret by name. A model serving compatible connection requires the following env vars: 'AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_S3_ENDPOINT', 'AWS_S3_BUCKET'
If all of these env vars are present, then we assume it is model serving compatible.
Connection instances:
Connection types:
Enable the connection types feature flag.
Connection types:
- Create a connection type in the admin section. 
- Add fields with at least the following required env vars: 'AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY', 'AWS_S3_ENDPOINT', 'AWS_S3_BUCKET'
- Observe the connection type displays `Model serving` in the compatibility column
Connection …

connection type compatibility column

---

frontend/src/pages/modelRegistry/screens/RegisterModel/RegisteredModelSelector.tsx

https://issues.redhat.com/browse/RHOAIENG-12777
The selection from the drop down is now preserved and displayed
on the UI
No test impact

Model name dropdown not retaining user selection for 'Register new version'

---

frontend/src/__mocks__/mockPVCK8sResource.ts
frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/clusterStorage.cy.ts
frontend/src/pages/projects/screens/detail/storage/StorageTable.tsx
frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx
frontend/src/pages/projects/screens/detail/storage/data.ts
frontend/src/pages/projects/screens/detail/storage/types.ts

https://issues.redhat.com/browse/RHOAIENG-1110
1. Added a new column for the storage class in the cluster storage table when the feature flag is enabled
2. shows class display name and description and sortable
3. shows the deprecated storage class alert when atleast one of the storage class is disabled and attached to cluster storage and added a label 
Cluster storage page
when storage class is deprecated/disabled
[
](url)
when storage class is deleted
When feature flag is off
1. Check the functionality remains same 
When feature flag is on
1. Go to the cluster storage tab from the Data science project Page
2. Check for the new storage column
3. Check whether its sortable
4. Check when the storage class is disabled for the attached cluster storage the deprecated label along with the alert …

Display storage class selected in workbenches

---

frontend/src/api/k8s/__tests__/templates.spec.ts
frontend/src/api/k8s/templates.ts

JIRA: https://issues.redhat.com/browse/RHOAIENG-12799
Added back the label selector for `'opendatahub.io/dashboard': 'true'` when fetching the templates.
1. Go to the serving runtimes page in the settings
2. Duplicate a serving runtime template
3. Go to the OpenShift console and find that template
4. Remove the label `'opendatahub.io/dashboard': 'true'` from the template
5. Refresh the serving runtimes page in the dashboard
6. Make sure the template without the label is not listed
There is no way to test the WebSocket watch API, the only way is to make sure the hook has been called with the selector option, so I updated that.

Only fetch serving runtime templates with dashboard label

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelMetrics.cy.ts
frontend/src/pages/modelServing/screens/metrics/MetricsChart.tsx

JIRA: https://issues.redhat.com/browse/RHOAIENG-11048
This is a known issue in Victory chart, and I am taking the workaround as suggested by the PF team here https://github.com/patternfly/patternfly-react/issues/10978#issuecomment-2346917642. If there is no data, we render it as `[null]` instead of `[]`, which fixes the issue.
I met some problems with generating the real data points, but you can go to the cypress test server and check the test case `Serving Chart Shows Data`
Way to compare:
1. Run `cypress:server` and `cypress:open:mock` in 2 terminals
2. Add `it.only` to the `Serving Chart Shows Data` test so we can check the screenshot
3. Go to `modelMetrics` test to check if it renders incorrectly
4. Run `cypress:server:build` and re-run step 1-3
5. You can see the data renders …

Fix stack chart issue when there is no data for one area

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistrySettings/modelRegistryPermissions.cy.ts
frontend/src/components/TypeaheadSelect.tsx
frontend/src/concepts/roleBinding/RoleBindingPermissionsNameInput.tsx
frontend/src/concepts/roleBinding/RoleBindingPermissionsTableRow.tsx

[RHOAIENG-12025](https://issues.redhat.com/browse/RHOAIENG-12025)
1.  Verify that once you've selected an item in the dropdown, if you then open the dropdown, you can NOW focus the typeahead text field without the need to close the dropdown( it was blocking the user from doing it) - try typing something in the typeahead in addition to the selected option 
2. The Option in the bottom of the dropdown list is now Select and not Create 
3. After you choose an option in the drop down, try deleting it in the typeahead and verify that it's not creating duplicate entries of that field in the dropdown(see screenshot in the issue) 
Tested on the UI 
One test change to update the Create to Select . Also When changing the label to select I didn't change all the variable names of that label so they …

MR Permissions - Group and Project dropdown issues 

---

manifests/rhoai/shared/base/anaconda-ce-validator-cron.yaml
manifests/rhoai/shared/base/deployment.yaml
manifests/rhoai/shared/base/nvidia-nim-validator-cron.yaml

JIRA: [RHOAIENG-10782](https://issues.redhat.com/browse/RHOAIENG-10782)
This field was probably an old value and could be removed not to avoid the warnings.
1. Get a 4.15+ OpenShift cluster
2. Install RHOAI operator on it and create the DSC
3. Check the warning events on the cluster, you should be able to see `Unable to retrieve some image pull secrets (addon-managed-odh-pullsecret);`
4. Go to DSC, edit dashboard entry to
```
dashboard:
devFlags:
manifests:
- contextDir: manifests
sourcePath: ''
uri: 'https://github.com/DaoDaoNoCode/odh-dashboard/tarball/jira-rhoaieng-10782'
```
5. The deployment will start to rollout
6. Make sure there is no warning event above
7. Make sure the dashboard can still running normally
N/A, manifest change.
If you have …

Get rid of imagePullSecrets field in RHOAI deployment

---

frontend/src/__tests__/cypress/cypress/pages/connections.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/connections.cy.ts
frontend/src/concepts/connectionTypes/ConnectionTypeDetailsHelperText.tsx
frontend/src/concepts/connectionTypes/ConnectionTypeForm.tsx
frontend/src/concepts/connectionTypes/ConnectionTypePreview.tsx
frontend/src/concepts/connectionTypes/ConnectionTypePreviewDrawer.tsx
frontend/src/concepts/connectionTypes/fields/ConnectionTypeFormFields.tsx
frontend/src/concepts/connectionTypes/types.ts
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/pages/projects/screens/detail/connections/ConnectionsList.tsx
frontend/src/pages/projects/screens/detail/connections/ManageConnectionsModal.tsx
frontend/src/pages/projects/screens/detail/connections/__tests__/ManageConnectionsModal.spec.tsx

https://issues.redhat.com/browse/RHOAIENG-11555
Creates a new connection in the form of a secret on the project.
<details>
<summary> SCREENSHOTS </summary>
result:
</details>
If you have a connection type named s3, then you can view the results in data connections. otherwise check the secrets to verify the creation
cypress and jest tests added
@simrandhaliw 

Add connection modal

---

frontend/src/concepts/k8s/K8sNameDescriptionField/K8sNameDescriptionField.tsx
frontend/src/concepts/k8s/K8sNameDescriptionField/ResourceNameField.tsx
frontend/src/concepts/k8s/ResourceNameDefinitionTooltip.tsx

It was observed while reviewing the new [create connection modal](https://github.com/opendatahub-io/odh-dashboard/pull/3217) that the k8s name / description component didn't fit exactly the UX for connection types.
Two differences observed:
- The spacing between form elements is 16px as oppose to 24px. PF `Form` and PF `FormSection` provide specific spacing between elements of the form. This component was using a stack layout with a different gap.
- The help icon and tooltip vs popover differed from those in the connection type form for form field descriptions.
The change here replaces the stack layout with a `FormSection`. Since there is no title to this section, the margin is eliminated to allow for these form elements to fit into existing forms.
The 2nd change is to use a popover and …

adjust resource name form spacing and help icon

---

frontend/src/__tests__/cypress/cypress/tests/mocked/projects/clusterStorage.cy.ts
frontend/src/pages/projects/notebook/ConnectedNotebookNames.tsx
frontend/src/pages/projects/notebook/StorageNotebookConnections.tsx
frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx
frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
frontend/src/pages/projects/screens/spawner/storage/AddExistingStorageField.tsx
frontend/src/pages/projects/screens/spawner/storage/StorageClassSelect.tsx
frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx
frontend/src/pages/projects/screens/spawner/storage/utils.ts
manifests/core-bases/base/cluster-role.yaml
manifests/core-bases/base/role.yaml

https://issues.redhat.com/browse/RHOAIENG-12803
This PR implements the functionality to allow a PVC to be added to multiple workbenches. The changes include:
- Updating the UI to allow selection of multiple workbenches when adding or editing a PVC.
- Modifying the logic to handle attaching a PVC to multiple workbenches.
I also updated some storage class logic and manifests
https://github.com/user-attachments/assets/a25b7f9a-7bef-4eb4-b5e2-b1531aba3805
1. create two workbenches
- one with its own new pvc
- the second one should be able to use the previous pvc
2. go to cluster storage tab
3. create a new pvc and connect one workbench
4. save and re edit pvc and add another workbench 
- Cypress tests for adding a new PVC and attaching it to multiple workbenches …

allow for pvc to be added to multiple workbenches

---

frontend/src/__tests__/cypress/cypress/pages/storageClasses.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/clusterStorage.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/storageClasses/storageClasses.cy.ts
frontend/src/__tests__/cypress/cypress/utils/oc_commands/project.ts
frontend/src/concepts/dashboard/DashboardEmptyTableView.tsx
frontend/src/k8sTypes.ts
frontend/src/pages/acceleratorProfiles/screens/list/AcceleratorProfiles.tsx
frontend/src/pages/storageClasses/ResetCorruptConfigValueAlert.tsx
frontend/src/pages/storageClasses/StorageClassFilterToolbar.tsx
frontend/src/pages/storageClasses/StorageClassesPage.tsx
frontend/src/pages/storageClasses/StorageClassesTable.tsx
frontend/src/pages/storageClasses/StorageClassesTableRow.tsx
frontend/src/pages/storageClasses/constants.ts

https://issues.redhat.com/browse/RHOAIENG-1107
Added filter toolbar and pagination to the storage classes table page. Users can filter by display name and/or Openshift class name.
**Demo:** 
https://github.com/user-attachments/assets/6d86fe29-a3c8-46f1-badc-e459dce17123
(cc @xianli123)
1. With the feature flag enabled, visit the storage class table's page; `/storageClasses?devFeatureFlags=disableStorageClasses`
2. Verify pagination exists
3. Verify the toolbar filter exists and matches the design
4. Verify you can filter by both display name and openshift class name
5. Verify empty state when filter yields no results and can reset filters via the action in that empty state ("Clear filters")
Added catch-all filter cypress test for storage classes
If …

[RHOAIENG-1107] Storage Class Filter

---

backend/src/utils/resourceUtils.ts

https://issues.redhat.com/browse/RHOAIENG-13107
(soft) Disable trusty bias metrics feature flag as the cache loads in the OdhDashboardConfig
Get dashboard config... `GET /api/config`
```json
{
"apiVersion": "opendatahub.io/v1alpha",
"kind": "OdhDashboardConfig",
"metadata": "...",
"spec": {
"dashboardConfig": {
"disableBiasMetrics": true,
"other-properties": "...",
},
"other-properties": "...",
},
"status": {
"conditions": [
{
"message": "This feature flag state is being ignored",
"reason": "IgnoredFeatureFlag",
"status": "False",
"type": "disableBiasMetricsAvailable"
}
]
}
```
For RHOAI installations, biasMetrics will always be disable when fetching the status to the client.
[Arch docs are being added in support to explain this design](https://github.com/opendatahub-io/architecture-decisi …

Soft disable the biasMetrics feature flag

---

frontend/src/__tests__/cypress/cypress/pages/components/Modal.ts

https://issues.redhat.com/browse/RHOAIENG-11946
A bug in PF `Modal` is causing the modal DOM node container to have `aria-hidden="true"` when running in our dev server which uses `React.StrictMode`. As a result, the cypress selector fails to find the modal.
The workaround here is to supply `hidden: true` to the selector. As per the documentation, this will include the hidden element in the result:
```
/**
* If true includes elements in the query set that are usually excluded from
* the accessibility tree. `role="none"` or `role="presentation"` are included
* in either case.
*/
hidden?: boolean
```
`npm run cypress:server:dev`
`npm run cypress:open:mock`
Run the `connectionTypes.cy.ts` test suite. Specifically the delete test.
N/A
If you have UI …

workaround PF bug with modals causing cypress selectors to fail

---

frontend/src/components/CharLimitHelperText.tsx
frontend/src/concepts/k8s/NameDescriptionField.tsx
frontend/src/concepts/pipelines/content/const.ts
frontend/src/concepts/pipelines/content/createRun/RunForm.tsx
frontend/src/concepts/pipelines/content/createRun/const.ts
frontend/src/concepts/pipelines/content/experiment/CreateExperimentModal.tsx

https://issues.redhat.com/browse/RHOAIENG-11751
Add name/description limit of 255 characters for the Create Experiment modal. If the user tries to type/paste in a character amount beyond 255, the input value is truncated accordingly. This prevents the user from possibly experiencing an error alert on submission for either of these fields.
1. Open the Create Experiment modal
2. Type in or paste a value greater than 255 characters for both name and description fields
3. Verify you can create the experiment successfully by submitting the modal and that no error alerts are visible

[RHOAIENG-11751] [RFE] Name & Description field character limit validation for 'create experiment' form

---

backend/src/routes/api/k8s/index.ts
backend/src/routes/api/k8s/pass-through.ts
backend/src/server.ts
frontend/src/__mocks__/mockStartNotebookData.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/workbench.cy.ts
frontend/src/api/k8s/__tests__/notebooks.spec.ts
frontend/src/api/k8s/notebooks.ts
frontend/src/api/k8sUtils.ts
frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx

JIRA: https://issues.redhat.com/browse/RHOAIENG-1157
After discussions within the eng team, we decided not to go with the UX design and simply create some actions in the alert to allow the user to override the value and force update the workbench or abandon the value and refresh the page.
The PR does the following things:
1. Added a merge patch method to the k8s API so we can merge patch a resource
2. Create a new method called `mergePatchUpdateNotebook` to override the values in the workbench using merge-patch
3. Dry-run the current method `updateNotebook` (which will use `PUT` method instead of `PATCH`), if it generates a 409 conflict because the workbench is updated on the cluster, then prompt 2 actions to allow users to force update the workbench or refresh the page
1. Create a …

Improve update call in editing workbench

---

manifests/rhoai/shared/apps/pachyderm/pachyderm-app.yaml

Closes: [RHOAIENG-10901](https://issues.redhat.com/browse/RHOAIENG-10901)
Fixes broken links for the dashboard application Pachyderm
Tested locally on cluster
no new tests

Fix broken links for pachyderm application

---

backend/src/routes/api/modelRegistries/modelRegistryUtils.ts
backend/src/types.ts
frontend/src/concepts/modelRegistry/context/ModelRegistrySelectorContext.tsx
frontend/src/k8sTypes.ts
frontend/src/pages/modelRegistrySettings/CreateModal.tsx
frontend/src/pages/modelRegistrySettings/ModelRegistriesPermissions.tsx
frontend/src/pages/modelRegistrySettings/useModelRegistryRoleBindings.ts

Followup to https://github.com/opendatahub-io/odh-dashboard/pull/3239
Needed for https://issues.redhat.com/browse/RHOAIENG-12311
[See slack thread here](https://redhat-internal.slack.com/archives/C07C0447EAV/p1727200812929609). The above PR creates a situation where if model registry is not enabled on a cluster, the dashboard will crash on server start. This PR is an immediate fix for the crash, and I'll follow up with a second PR to switch us to using a ResourceWatcher so we make sure the namespace value is current in case it is not available yet when the dashboard starts.
This PR also fixes the same type in the frontend to make sure we are always being defensive when we try to read this value.
Tested on https://console-openshift-console.apps.ods-qe-psi-01.osp.rh-ods.com/ which is old …

Don't crash if modelregistries namespace is not present in the DSC

---

frontend/src/api/k8s/__tests__/notebooks.spec.ts
frontend/src/api/k8s/notebooks.ts
frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx

JIRA: [RHOAIENG-147](https://issues.redhat.com/browse/RHOAIENG-147)
Find all the connected notebooks to the PVC, and when detects the PVC size changes, add the `notebooks.opendatahub.io/notebook-restart=true` annotation to the workbench to trigger a restart.
1. Create a workbench
2. Make sure it's running
3. Find the attached PVC to that workbench
4. Update that PVC, increase the size by 1 GB
5. Make sure the workbench restarts
6. You can try to attach the PVC to more workbenches and make sure the size increase could trigger the restart of all the attached workbenches
Added a unit test to verify the restart notebook function triggers the correct patch method.

Restart all connected notebooks when the pvc size changes

---

backend/src/routes/api/dsc/index.ts
backend/src/routes/api/modelRegistries/index.ts
backend/src/routes/api/modelRegistries/modelRegistryUtils.ts
backend/src/utils/dsc.ts
backend/src/utils/proxy.ts
backend/src/utils/resourceUtils.ts
backend/src/utils/route-security.ts

Followup to #3248 and #3239.
Closes https://issues.redhat.com/browse/RHOAIENG-12311
A potential problem with the implementation in #3239 is that it depends on the registriesNamespace being present in the DSC status immediately when the dashboard pod starts. In theory on a fresh install it is possible for the dashboard to start before the operator has reconciled the DSC and put the registriesNamespace into its status, in which case we would never refetch it and all model registry API calls would fail until the dashboard pods were restarted.
To fix this, we can use a ResourceWatcher so that the server is regularly refetching the DSC and any usage of `getModelRegistryNamespace` will use its latest value. This means that function is no longer async, and also should now be called during each …

Use a ResourceWatcher for DSC status in the backend instead of fetching it once at app startup to resolve model registries namespace

---

frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetails.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRecurringRun/PipelineRecurringRunDetails.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx
frontend/src/concepts/topology/PipelineVisualizationSurface.tsx

Fixes [RHOAIENG-13164](https://issues.redhat.com/browse/RHOAIENG-13164)
When spacer nodes are created for edges due to multiple sources going to the same multiple targets, only the edge between the spacer node and source (or target) was being highlighted.
Added code to include the edge between the spacer node and targets (or sources) in the selection list.
Can reproduce using:
https://redhat.enterprise.slack.com/files/UQN4S2YQJ/F07P71R7NSU/fraud_detection.yaml

Fix to show complete edge highlight on selection in topology views

---

backend/package.json
backend/src/app.ts

Updated lint script to target the `backend/src` folder because not all files were being assessed by eslint.
Fixed any errors.
`npm run test:lint
N/A

run eslint on backend src folder

---

frontend/src/__mocks__/mockNotebookK8sResource.ts
frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/clusterStorage.cy.ts
frontend/src/pages/projects/pvc/MountPathField.tsx

JIRA: https://issues.redhat.com/browse/RHOAIENG-7680
There is something wrong with the logic in the helper text and what error text we should show. I made some changes to that to correct the logic. Also, change the regex to allow a trailing `/` in the path.
Initial state:
Trailing slash:
Duplicate path:
Empty input:
Invalid value (contains number):
Invalid value (slash is not the trailing slash):
1. Create a cluster storage
2. Attach it to a workbench
3. Input in the mouth path field, check if it's allowing a trailing slash
4. Check all the error states as listed above
Updated the cypress test to check the error cases.

Fix validation in the storage modal mount path

---

frontend/src/__tests__/cypress/cypress/tests/mocked/projects/connections.cy.ts
frontend/src/concepts/connectionTypes/ConnectionTypeForm.tsx
frontend/src/concepts/connectionTypes/fields/ConnectionTypeFormFields.tsx
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/concepts/k8s/K8sNameDescriptionField/K8sNameDescriptionField.tsx
frontend/src/concepts/k8s/K8sNameDescriptionField/ResourceNameField.tsx
frontend/src/pages/projects/screens/detail/connections/ConnectionsList.tsx
frontend/src/pages/projects/screens/detail/connections/ConnectionsTable.tsx
frontend/src/pages/projects/screens/detail/connections/ManageConnectionsModal.tsx
frontend/src/pages/projects/screens/detail/connections/__tests__/ConnectionsTable.spec.tsx
frontend/src/pages/projects/screens/detail/connections/__tests__/ManageConnectionsModal.spec.tsx
frontend/src/pages/projects/screens/detail/data-connections/utils.ts

https://issues.redhat.com/browse/RHOAIENG-11556
Hooks up the edit kebab action to the manageConnectionModal. it will pass in the connection of that row, and pass `isEdit`. It will then prefill connection data. 
The secret stores data in base64, so `atob()` is used to decode, this is done in the modal itself (which is similar to the data connections). This makes it easier to reference a corresponding connection type, to determine how to decode the value. 
If a connection has env var names that do not match up to a connection type field, they will be appended to the bottom as short text fields. 
The multi dropdown is stored as a JSON array, and decoded as such. 
The "Save" button isn't enabled until the field values have been updated. 
Additionally the k8sNameDesc is now intractable in the …

Edit for existing project connection instances

---

backend/src/routes/api/modelRegistryRoleBindings/index.ts
backend/src/routes/api/modelRegistryRoleBindings/modelRegistryRolebindingsUtils.ts
backend/src/types.ts
frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistrySettings/modelRegistryPermissions.cy.ts
frontend/src/concepts/roleBinding/RoleBindingPermissions.tsx
frontend/src/concepts/roleBinding/RoleBindingPermissionsTable.tsx
frontend/src/concepts/roleBinding/RoleBindingPermissionsTableSection.tsx
frontend/src/pages/modelRegistrySettings/ModelRegistriesPermissions.tsx
frontend/src/pages/modelRegistrySettings/ProjectsTab/ProjectsSettingsTab.tsx
frontend/src/pages/modelRegistrySettings/useModelRegistryRoleBindings.ts
frontend/src/pages/projects/projectSharing/ProjectSharing.tsx
frontend/src/services/modelRegistrySettingsService.ts

use a separate endpoint for MR based rolebinding calls which will automatically use the MR namespace and labels
tested locally, things still work as expected
mocks changed in tests to match new urls
make sure rolebinding still works as expected for given role. this would include listing, adding, and deleting

feat(13045): mr permissions and rolebindings

---

backend/src/plugins/kube.ts
backend/src/utils/resourceUtils.ts
frontend/src/__mocks__/mockRoleK8sResource.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts
frontend/src/api/index.ts
frontend/src/api/k8s/__tests__/roleBindings.spec.ts
frontend/src/api/k8s/__tests__/roles.spec.ts
frontend/src/api/k8s/roleBindings.ts
frontend/src/api/k8s/roles.ts
frontend/src/api/models/k8s.ts
frontend/src/k8sTypes.ts
frontend/src/pages/modelServing/__tests__/utils.spec.ts
frontend/src/pages/modelServing/screens/projects/utils.ts
frontend/src/pages/modelServing/utils.ts
manifests/core-bases/base/cluster-role.yaml

Resolves https://issues.redhat.com/browse/RHOAIENG-11010
See comments on Jira issue for implementation details. When setting up token auth for KServe models, instead of giving their ServiceAccounts a binding to the ClusterRole "view", we create a new role for them to get only InferenceServices in their own namespace. This PR also adds logic to replace the old rolebindings on users' clusters with the replaced more secure ones.
Tested by @lucferbux, [steps outlined in this doc](https://docs.google.com/document/d/1N1UvwESTHo6fTsNSkjojuExakUzKKU0fxB4LXY_Kty4/edit#heading=h.cv9nyz82zwzi)
* New unit tests for new frontend utils for managing roles
* Updated tests for `setUpTokenAuth` to account for creating / not creating the new role
* Backend code unfortunately has no unit testing currently, …

[RHOAIENG-11010] Use a more secure role for KServe InferenceService access

---

frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts
frontend/src/components/table/TableRowTitleDescription.tsx
frontend/src/pages/projects/screens/detail/storage/StorageTable.tsx
frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx
frontend/src/pages/projects/screens/spawner/storage/StorageClassSelect.tsx
frontend/src/pages/storageClasses/ResetCorruptConfigValueAlert.tsx
frontend/src/pages/storageClasses/StorageClassConfigValue.tsx
frontend/src/pages/storageClasses/StorageClassDefaultRadio.tsx
frontend/src/pages/storageClasses/StorageClassEnableSwitch.tsx
frontend/src/pages/storageClasses/StorageClassesContext.tsx
frontend/src/pages/storageClasses/StorageClassesPage.tsx
frontend/src/pages/storageClasses/StorageClassesTable.tsx
frontend/src/pages/storageClasses/StorageClassesTableRow.tsx
frontend/src/pages/storageClasses/utils.ts

https://issues.redhat.com/browse/RHOAIENG-13320
https://issues.redhat.com/browse/RHOAIENG-13401
Added new logic to account for edge cases where users manually update storage classes from the OpenShift dashboard. The situations accounted for include:
**Storage class table:**
1. If isEnabled is false & isDefault is true (set from OpenShift dashboard), then set isEnabled to true.
2. When all configs exist but no ODH default is defined, update to set the OpenShift default or the first found storage class as the ODH default and show the same alert as when configs are initialized.
3. Disable corresponding IsDefault while Enabling is ongoing.
**Storage class dropdown:**
1. Disable storage class dropdown when only 1 value exists.
2. Hide the dropdown when no storage class configs are defined.
By …

[RHOAIENG-13320] Storage class duplication isDefault edge cases

---

frontend/src/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTable.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTableRow.tsx
frontend/src/pages/pipelines/global/runs/ScheduledRuns.tsx

https://issues.redhat.com/browse/RHOAIENG-11858
ggle one of the schedules to enable or disable it, and that should only trigger and re-render of that particular schedule
1. Use a pipeline version to create some schedules
2. View schedules for that pipeline version
3. Try to toggle the "Status" column for any row
Check if  It will only trigger re-render of the current row and re-fetch the current schedule
N/A

rerender only the schedule which got toggled

---

frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
frontend/src/pages/projects/notebook/StartNotebookModal.tsx

https://issues.redhat.com/browse/RHOAIENG-11107
sort the events by their timestamp in the StartServerModal and startNotebookModal
1. Create a workbench
2. and check for the event log whether its sorted, compare the event to workbench pod events in openshift console 
3. also Verify the event logs for notebook server 
Workench:
Notebook server

Events are in correct order in workbench status progress

---

frontend/src/pages/notebookController/screens/admin/NotebookAdminControl.tsx
frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx

JIRA: [RHOAIENG-1202](https://issues.redhat.com/browse/RHOAIENG-1202)
Remove the div on the administration page to make it use the full width:
Fix the loading state by adding the `loadingContent` to the applications page to remove the background.
Go to the notebook controller page and switch between the Notebook Server and Administration tab. See how the loading state renders, Make sure there is no layout issue.
N/A, layout fix.

Fix layout issues on notebook controller

---

frontend/src/__tests__/cypress/cypress/support/commands/odh.ts

Fixes type check errors in the cypress dir.
`npm run test:type-check` in the frontend dir
N/A

update interceptOdh DELETE modelRegistryRoleBindings return type

---

frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
frontend/src/app/App.scss

https://issues.redhat.com/browse/RHOAIENG-12443
This works around an issue with PF: https://github.com/patternfly/patternfly/issues/7104
`Label` components within a `LabelGroup` do not truncate when placed within a confined container.
- Create a connection type with a very long named category.
- Observe the category truncation on the connection type table.
Before:
After:
N/A
Visual change only.

label group truncation

---

frontend/src/concepts/k8s/K8sNameDescriptionField/__tests__/utils.spec.ts
frontend/src/concepts/k8s/K8sNameDescriptionField/utils.ts
frontend/src/concepts/k8s/utils.ts
frontend/src/pages/connectionTypes/manage/ManageConnectionTypePage.tsx

Closes https://issues.redhat.com/browse/RHOAIENG-13400
Use the new `K8sNameDescriptionField` component. This prevents the user from entering a too long of a name which causes a resource name error when saving. 
Tested locally by running through the different connection type operations. 
For the bug referenced in the jira issue, paste a lot of text https://www.lipsum.com/feed/html and click save. It will now truncate the resource name
No updates, existing tests cover the previous functionality. (and the long name is a server side error)

Use K8sNameDescriptionField in connection type page

---

frontend/src/k8sTypes.ts
frontend/src/pages/modelServing/screens/global/DeleteInferenceServiceModal.tsx
frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx
frontend/src/pages/modelServing/screens/projects/NIMServiceModal/DeployNIMServiceModal.tsx
frontend/src/pages/modelServing/screens/projects/NIMServiceModal/NIMModelListSection.tsx
frontend/src/pages/modelServing/screens/projects/nimUtils.ts
frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelsSection.tsx

https://issues.redhat.com/browse/APPENG-2712
Added secret deletion and deploy button links fixed in empty state to point to NIM modal.
Verified resource creation and deletion during model deployment and removal.

NIM deployment

---

backend/src/routes/api/modelRegistries/index.ts
backend/src/routes/api/modelRegistryRoleBindings/modelRegistryRolebindingsUtils.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistrySettings/modelRegistryPermissions.cy.ts
frontend/src/api/modelRegistry/errorUtils.ts
frontend/src/services/modelRegistrySettingsService.ts

Followup to https://github.com/opendatahub-io/odh-dashboard/pull/3252 and https://github.com/opendatahub-io/odh-dashboard/pull/3249 as well as some misc discussion points from arch review (https://issues.redhat.com/browse/RHOAIENG-13439).
* After #3249 was rebased on the changes from #3252, testing it revealed that because we removed the model registry namespace from the checks in `backend/src/utils/route-security.ts` and rolebindings we create in MR settings include that namespace in the request body, creation of rolebindings failed due to the namespace checking in `requestSecurityGuard`. We do not want to modify route-security because it is a fragile workaround and modifying it involves high risk. The fix instead is to simply not include a namespace in the rolebinding object when we …

MR fixes identified during architecture review

---

frontend/src/__mocks__/mockKserveMetricsConfigMap.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelMetrics.cy.ts
frontend/src/api/prometheus/kservePerformanceMetrics.ts
frontend/src/concepts/metrics/kserve/content/KserveMeanLatencyGraph.tsx

closes: https://issues.redhat.com/browse/RHOAIENG-11522
this is a situation that would result in the error stack and ui crash without this change:
prevent ui from crashing. let the query be undefined if it doesn't exist, which will result in an empty data and no errors. vince said he did not want an error message at all as it might convey to the user that it might resolve with a refresh or something.
tested code on a previous deploy that would crash the ui on metrics page, it no longer crashes. used MR cluster to test. existing tests still pass.
added a new test using mock data that only contains 1 query and made sure that the 4 charts show up (instead of an error stack page). i also updated the test mock for `prometheus/serving` to return empty results if the request body includes …

fix(vllm metrics): error stack trace

---

backend/src/types.ts
backend/src/utils/constants.ts
backend/src/utils/notebookUtils.ts
docs/dashboard-config.md
frontend/src/__mocks__/mockStorageClasses.ts
frontend/src/__tests__/cypress/cypress/pages/storageClasses.ts
frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/applications/notebookServer.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/clusterStorage.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/workbench.cy.ts
frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
frontend/src/types.ts
manifests/rhoai/shared/odhdashboardconfig/odhdashboardconfig.yaml

https://issues.redhat.com/browse/RHOAIENG-13395
This PR adds support for setting the default storage class for the jupyter tile. 
Key changes:
* Added storageClassName field to NotebookData type in both frontend and backend.
* fix test mocks that where creating a new type
1. enable storage class feature flag
2. set storage class in dashboard config
3. spawn a notebook in jupyter tile
4. check that notebook created is using the storage class in the dashboard config
5. remove the storage class from the dashboard config
6. spawn it again and check that it uses the default set in the storage class admin page
7. turn off the feature flag
8. spawn it again, check that it uses the default openshift storage class
updated test mocks and added test to make sure default storage class was passed to …

Add storage class support for notebook PVCs

---

frontend/src/concepts/pipelines/content/createRun/contentSections/PipelineSection.tsx
frontend/src/concepts/pipelines/content/import/ImportPipelineButton.tsx
frontend/src/concepts/pipelines/content/import/PipelineImportModal.tsx

https://issues.redhat.com/browse/RHOAIENG-11326
Add condition to pipeline import modal to only redirect when not located in the `/create` path associated with runs/schedules
**Demo:**
https://github.com/user-attachments/assets/28f10956-9b84-465e-8db6-bf9fda2d5f6d
1. Import a pipeline from the Pipelines list page and verify you're redirected to the pipeline version details page after creation
2. Import a pipeline from the Create run page and verify you are not redirected to the pipeline version details page
3. Repeat step 2 for the Create schedule page

[RHOAIENG-11326] Creating new pipeline from Create Run Page redirects to the pipeline detail page

---

frontend/src/pages/modelServing/screens/global/EmptyModelServing.tsx
frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx

Resolved double window and NIM modal showing for KServe. Added a link to EmptyModelServing for NIM project. 

Nim double window

---

frontend/src/pages/storageClasses/constants.ts

https://issues.redhat.com/browse/RHOAIENG-13781
Fixing sort that was previously using the storage class name instead of the storage class config display name.
https://github.com/user-attachments/assets/19dee695-3b6d-4c25-b893-fd5e767732db
Verify using storage class names that differ from their config display names that the Display name column sort is based on those displayName values versus the storage class name.

[RHOAIENG-13781] Storage classes grid not sorting by Display Name

---

frontend/src/__tests__/cypress/cypress/pages/projects.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/pipelines/pipelines.cy.ts

https://issues.redhat.com/browse/RHOAIENG-13384
After some changes in the DSProjects view search toolbar, the Pipelines  e2e test was failing.
Also I've updated the URL used to import the pipeline.
cypress/job/dashboard-tests/18

Fix: Cypress Pipeline e2e test

---

frontend/src/pages/projects/notebook/utils.ts
frontend/src/utilities/notebookControllerUtils.ts

Closes: [RHOAIENG-1132](https://issues.redhat.com/browse/RHOAIENG-1132)
Added case to handle notebook failure when reason === "BackOff"
1. Create a custom image from Settings > Notebook images (e.g., quay.io/myfakeimages/myimage:1234)
2. create a workbench and select the custom image as notebook image
3. compare the pod and workbench status
N/A
@xianli123

ImagePullBackOff is not handled as error during workbench start

---

frontend/src/pages/projects/__tests__/useInferenceServicesForConnection.spec.ts
frontend/src/pages/projects/screens/detail/connections/ConnectedResources.tsx
frontend/src/pages/projects/screens/detail/connections/ConnectionsDeleteModal.tsx
frontend/src/pages/projects/screens/detail/connections/__tests__/ConnectionsDeleteModal.spec.tsx
frontend/src/pages/projects/screens/detail/connections/__tests__/ConnectionsTable.spec.tsx
frontend/src/pages/projects/useInferenceServicesForConnection.ts

Closes [RHOAIENG-11558](https://issues.redhat.com/browse/RHOAIENG-11558)
Adds connected deployed models to the connection table rows.
Lists connected deployed models when deleting a connection.
Tested manually.
Added test scenarios
Test the connection table to verify the related models show up in each row
Test the delete connection modal to verify the related models are listed.

List connected deployed models for each connection table row

---

backend/src/routes/api/nim-serving/index.ts
frontend/src/api/k8s/servingRuntimes.ts
frontend/src/pages/modelServing/screens/projects/NIMServiceModal/DeployNIMServiceModal.tsx
frontend/src/pages/modelServing/screens/projects/NIMServiceModal/NIMModelListSection.tsx
frontend/src/pages/modelServing/screens/projects/__tests__/utils.spec.ts
frontend/src/pages/modelServing/screens/projects/nimUtils.ts
frontend/src/pages/modelServing/screens/projects/utils.ts

Retrieving ConfigMap using service account and added ${uid} to PVC name to avoid waiting for resource termination after deletion
Deployed a NIM model, deleted it, and deployed another model while the PVC was still in the 'Terminating' state. 

Config map nim model name fetch

---

frontend/src/pages/projects/screens/spawner/storage/StorageClassSelect.tsx
frontend/src/pages/projects/screens/spawner/storage/useDefaultStorageClass.ts
frontend/src/pages/storageClasses/StorageClassesContext.tsx
frontend/src/pages/storageClasses/StorageClassesTableRow.tsx

Closes: [RHOAIENG-13608](https://issues.redhat.com/browse/RHOAIENG-13608)
This PR resolves inconsistencies when handling corrupted or multiple storage classes marked as default (isDefault: true).
a) If a corrupted class is detected and no valid default is found, the first storage class in the list is automatically selected.
b) Improved the logic in `StorageClassSelect` to properly manage scenarios with multiple default storage classes.
Before
After
c) Enhanced error handling for corrupted default values within `StorageClassesContext`.
https://github.com/user-attachments/assets/61b8d37a-ffa9-43cb-8ad6-7f00f93097d6
To test default inconsistency on Storage class select.
1. Add isDefault: 1 in annotations of any one storage class.
2. On the cluster storage page create new storage, the default …

RHOAIENG-13608 Inconsistent Default Storage Class when corrupting isDefault value

---

frontend/src/__tests__/cypress/cypress/pages/projects.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectDetails.cy.ts
frontend/src/components/ResourceNameTooltip.tsx
frontend/src/pages/projects/screens/detail/ProjectActions.tsx
frontend/src/pages/projects/screens/detail/ProjectDetails.tsx

Closes [RHOAIENG-8571](https://issues.redhat.com/browse/RHOAIENG-8571)
In the project details page, add a popover to show users the project's resource name and kind.
Also, add actions to allow a provisioned user to edit or delete the project.
As a provisioned user, navigate to a project page.
Verify there is a popover indicator next to the project name.
Clicking the indicator shows a popover that shows the project's resource name and show `Project` for the resource type.
Click on the actions menu to the far right, verify both `Edit project` and `Delete project` actions are shown.
Verify that `Edit project` bring up the `Edit project` modal.
Verify that `Delete project` brings up the `Delete project` modal.
As a non-provisioning user, navigate to a project page.
Verify there is a popover …

Project Details Page - Allow Edit and View Details

---

frontend/src/pages/projects/screens/detail/connections/ConnectionsDeleteModal.tsx
frontend/src/pages/projects/screens/detail/connections/__tests__/ConnectionsDeleteModal.spec.tsx

Fixes [RHOAIENG-11558](https://issues.redhat.com/browse/RHOAIENG-11558)
When deleting a connection, do not show the related models section if there are no related models
Delete a Connection that has no related deployed models.
Verify the `Model deployments` section is not shown.
Added RTL test for empty workbenches and model deployments

Don't show empty connected models when deleting a connection

---

frontend/src/concepts/pipelines/content/ArchiveModal.tsx
frontend/src/concepts/pipelines/content/PipelineServerActions.tsx
frontend/src/concepts/pipelines/content/RestoreModal.tsx
frontend/src/concepts/pipelines/content/ViewPipelineServerModal.tsx
frontend/src/concepts/pipelines/content/configurePipelinesServer/ConfigurePipelinesServerModal.tsx
frontend/src/concepts/pipelines/content/experiment/CreateExperimentButton.tsx
frontend/src/concepts/pipelines/content/experiment/CreateExperimentModal.tsx
frontend/src/concepts/pipelines/content/import/ImportPipelineButton.tsx
frontend/src/concepts/pipelines/content/import/ImportPipelineSplitButton.tsx
frontend/src/concepts/pipelines/content/import/PipelineImportModal.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx
frontend/src/concepts/pipelines/content/tables/experiment/ActiveExperimentTable.tsx
frontend/src/concepts/pipelines/content/tables/experiment/ArchivedExperimentTable.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx
frontend/src/concepts/pipelines/context/PipelinesContext.tsx
frontend/src/pages/pipelines/global/experiments/ArchiveExperimentModal.tsx
frontend/src/pages/pipelines/global/experiments/RestoreExperimentModal.tsx
frontend/src/pages/pipelines/global/runs/ArchiveRunModal.tsx
frontend/src/pages/pipelines/global/runs/RestoreRunModal.tsx

Towards [RHOAIENG-12117](https://issues.redhat.com/browse/RHOAIENG-12117)
Update usage of pipeline Archive, Restore, and View server modals to render them only when they would be shown rather than having them be rendered but hidden.
Run thru the UI and check that then modals are shown only when they should be shown.
- From a project details page
- select the `Pipelines` tab
- expand a pipeline that has pipeline versions
- select a pipeline version
- from the pipelines page, select the `Pipeline server actions` menu and choose `View pipeline server configuration`
- verify the `View pipeline server` modal is shown
- From a project details page
- select the `Pipelines` tab
- expand a pipeline that has pipeline versions
- from a pipeline version, use the kebab and select `View runs`
- from …

Conditionally render pipeline modals

---

frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsHeaderActions.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsHeaderActions.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsTableRow.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionArchiveDetails.tsx
frontend/src/pages/modelRegistry/screens/RegisterModel/ConnectionModal.tsx
frontend/src/pages/modelRegistry/screens/RegisterModel/RegistrationCommonFormSections.tsx
frontend/src/pages/modelRegistry/screens/RegisteredModels/RegisteredModelTableRow.tsx
frontend/src/pages/modelRegistry/screens/RegisteredModelsArchive/RegisteredModelArchiveDetails.tsx
frontend/src/pages/modelRegistry/screens/components/ArchiveModelVersionModal.tsx
frontend/src/pages/modelRegistry/screens/components/ArchiveRegisteredModelModal.tsx
frontend/src/pages/modelRegistry/screens/components/DeployRegisteredModelModal.tsx
frontend/src/pages/modelRegistry/screens/components/ModelLabels.tsx
frontend/src/pages/modelRegistry/screens/components/RestoreModelVersionModal.tsx
frontend/src/pages/modelRegistry/screens/components/RestoreRegisteredModel.tsx

Towards [RHOAIENG-12117](https://issues.redhat.com/browse/RHOAIENG-12117)
Update usage of modals in the model registry section to render them only when they would be shown rather than having them be rendered but hidden.
Run thru the UI and check that then modals are shown only when they should be shown.
- From the `Model Registry` page
- from a model, use the kebab and select `Archive model`
- verify the `Archive model?` modal is shown
- From the `Model Registry` page
- Click on a model
- from the model details page, open a kebab menu for a version and select `Deploy`
- verify the `Deploy model` modal is shown
- From the `Model Registry` page
- Click on a model
- from the model details page, open a kebab menu for a version and select `Archive model version`
- verify the `Archive version?` …

Conditionally render model registry modals

---

frontend/src/pages/projects/screens/projects/LaunchJupyterButton.tsx

* https://github.com/red-hat-data-services/ods-ci/pull/1880#issuecomment-2387950341
PR checks
After the PR is posted & before it merges: quay.io/opendatahub/odh-dashboard:pr-3294

NO-JIRA: chore(quality): add `data-testid` for the Launch standalone notebook server button

---

frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts
frontend/src/pages/modelRegistry/screens/RegisterModel/RegisterModel.tsx
frontend/src/pages/modelRegistry/screens/RegisterModel/RegisterVersion.tsx
frontend/src/pages/modelRegistry/screens/RegisterModel/RegistrationCommonFormSections.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceServingRuntimeSection.tsx
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/AuthServingRuntimeSection.tsx
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeExpandedField.tsx
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenInput.tsx
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenSection.tsx
frontend/src/pages/modelServing/screens/types.ts
frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx
frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx
frontend/src/pages/projects/types.ts
frontend/src/utilities/useGenericObjectState.ts

https://issues.redhat.com/browse/RHOAIENG-9748
Improves the typing of `useGenericObjectState` such that the value is properly typed depending on the supplied property key. As a result, any unmatched value will result in a typescript error.
Extracted common types for model serving into a separate type definition to be used by common form components.
Additionally, updated `useGenericObjectState` to accept a function to coincide with the API of `useState`. This function argument can be used when the computation of default data is expensive.
`npm run test:type-check`
Ran existing tests.
N/A

update useGenericObjectState types

---

frontend/.env
frontend/src/__tests__/cypress/cypress/fixtures/resources/yaml/storage_class.yaml
frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts
frontend/src/__tests__/cypress/cypress/pages/projects.ts
frontend/src/__tests__/cypress/cypress/pages/storageClasses.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/storageClasses/clusterStorage.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/storageClasses/storageClasses.cy.ts
frontend/src/__tests__/cypress/cypress/types.ts
frontend/src/__tests__/cypress/cypress/utils/clusterStorage.ts
frontend/src/__tests__/cypress/cypress/utils/oc_commands/baseCommands.ts
frontend/src/__tests__/cypress/cypress/utils/oc_commands/project.ts
frontend/src/__tests__/cypress/cypress/utils/oc_commands/storageClass.ts
frontend/src/__tests__/cypress/cypress/utils/storageClass.ts
frontend/src/pages/projects/components/GenericHorizontalBar.tsx
frontend/src/pages/projects/screens/detail/storage/StorageList.tsx
frontend/src/pages/projects/screens/spawner/storage/StorageClassSelect.tsx

https://issues.redhat.com/browse/RHOAIENG-11613
e2e Cypress test cases for Storage Class Feature
Settings->Storage class view:
- A non admin user can not acccess to Settings -> Storage classes view
- The Default label is shown in the grid
- An admin user can enable a disabled Storage Class
- An admin user can disable an enabled Storage Class
- An admin user can set an enabled Storage Class as the default one
- An admin user can edit an Storage Class
Cluster Storage view from the Cluster Storage DSP tab:
- Regular user can create a cluster storage using a new storage class
- A Cluster Storage with a disabled SC shows the deprecated warning
- If all SC are disabled except one, the SC dropdown should be disabled
As there were some UI changes, the tests ran against the local UI and a 2.14 …

test: Storage Classes e2e cypress tests

---

frontend/src/concepts/pipelines/EnsureCompatiblePipelineServer.tsx
frontend/src/pages/pipelines/global/PipelineCoreApplicationPage.tsx

JIRA: https://issues.redhat.com/browse/RHOAIENG-9209
Updated the configure server button variant on pipelines page to make it primary.
Go to the project that doesn't have a pipeline server configured, make sure the configure server button is the primary style on both the projects page and the pipelines global page.
N/A, minor UX update.

Update empty pipeline server page button variant

---

frontend/src/pages/modelRegistry/screens/components/DeployRegisteredModelModal.tsx
frontend/src/pages/modelRegistrySettings/CreateModal.tsx
frontend/src/pages/modelRegistrySettings/DeleteModelRegistryModal.tsx
frontend/src/pages/modelRegistrySettings/ModelRegistriesTableRow.tsx
frontend/src/pages/modelRegistrySettings/ModelRegistrySettings.tsx
frontend/src/pages/modelRegistrySettings/ViewDatabaseConfigModal.tsx
frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx
frontend/src/pages/modelServing/screens/global/ServeModelButton.tsx
frontend/src/pages/modelServing/screens/metrics/bias/BiasConfigurationPage/BiasConfigurationModal/ManageBiasConfigurationModal.tsx
frontend/src/pages/modelServing/screens/metrics/bias/BiasConfigurationPage/BiasConfigurationPage.tsx
frontend/src/pages/modelServing/screens/metrics/bias/BiasConfigurationPage/BiasConfigurationTable.tsx
frontend/src/pages/modelServing/screens/projects/EmptyMultiModelServingCard.tsx
frontend/src/pages/modelServing/screens/projects/EmptyNIMModelServingCard.tsx
frontend/src/pages/modelServing/screens/projects/EmptySingleModelServingCard.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ManageInferenceServiceModal.spec.tsx
frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTable.tsx
frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTable.tsx
frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx
frontend/src/pages/modelServing/screens/projects/NIMServiceModal/DeployNIMServiceModal.tsx
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
frontend/src/pages/projects/screens/detail/overview/serverModels/AddModelFooter.tsx

Towards [RHOAIENG-12117](https://issues.redhat.com/browse/RHOAIENG-12117)
Update usage of modals in the model serving section to render them only when they would be shown rather than having them be rendered but hidden.
Run thru the UI and check that then modals are shown only when they should be shown.
- From the `Model Serving` page
- For a project with KServe enabled, select the `Deploy model` button
- verify the `Deploy model` modal is shown
- From the `Model Serving` page
- For a project with ModelMesh enabled, select the `Deploy model` button
- verify the `Deploy model` modal is shown
- From the `Model Serving` page
- For a project with ModelMesh enabled, select the kebab for an existing model and select `Delete`
- verify the `Delete deployed model?` modal is shown
- From the `Model …

Conditionally render model serving modals

---

frontend/src/pages/modelRegistry/screens/ModelRegistry.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionListView.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersions.tsx
frontend/src/pages/modelRegistry/screens/RegisteredModels/RegisteredModelListView.tsx

Closes: [RHOAIENG-12863](https://issues.redhat.com/browse/RHOAIENG-12863)
This PR aims to update the empty state of versions list and models list to show the secondary action only when there are archived versions /  archived models.
Check for empty state of versions list with no archived versions.
Check for empty state of models list with no archived models.
NA, just rendering the empty state actions conditionally. 

Update empty state of versions list and models lists

---

frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsHeaderActions.tsx

Closes: [RHOAIENG-13063](https://issues.redhat.com/browse/RHOAIENG-13063)
This PR aims to update the workflow of archiving version from version details page. Now if we archive a version from version details page it will redirect to versions list page
Archive a version from the version details page and see that navigates to versions list page after archiving a version.
NA, updated the navigation after archive.

Update the workflow of archiving version from version details page

---

frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx
frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
frontend/src/pages/projects/screens/spawner/storage/StorageClassSelect.tsx
frontend/src/pages/projects/screens/spawner/storage/useDefaultStorageClass.ts

https://issues.redhat.com/browse/RHOAIENG-14219
This PR refactors the `useDefaultStorageClass` hook to use the `useFetchState` utility, improving error handling and loading state management. The changes affect several components that use this hook, updating their implementations to handle the new return value format.
Key changes:
- Rewrote `useDefaultStorageClass` to use `useFetchState`
- Updated components using `useDefaultStorageClass` to destructure the new return value
- Added error handling and improved loading state management in `SpawnerPage`
Navigate to the Spawner page and verify that the storage class selection works as expected.
1. Verify that the ManageStorageModal in the project details page still functions correctly.
2. Check the StorageClassSelect component to ensure it …

Refactor useDefaultStorageClass hook to use FetchState

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersions.cy.ts
frontend/src/concepts/modelRegistry/types.ts
frontend/src/pages/modelRegistry/screens/__tests__/utils.spec.ts
frontend/src/pages/modelRegistry/screens/utils.ts

https://issues.redhat.com/browse/RHOAIENG-12589
When using the Keyword filtering option, it will now query the labels as well. This should be in both models and versions
on The UI  

Provide the functionality to search models and model version by "labels"

---

frontend/src/pages/home/aiFlows/ProjectsGallery.tsx
frontend/src/pages/projects/screens/detail/overview/configuration/ConfigurationSection.tsx

Closes: [RHOAIENG-13140](https://issues.redhat.com/browse/RHOAIENG-13140)
Updates the data connections card with new contents on both the home page and the data science projects page. The Connections card on the data science projects page now links to the connections tab.
Tested locally
No tests added
_----------------------_

Connection card update

---

frontend/.eslintrc
frontend/src/app/DevFeatureFlagsBanner.tsx
frontend/src/components/EditableLabelsDescriptionListGroup.tsx
frontend/src/pages/BYONImages/BYONImageModal/ManageBYONImageModal.tsx
frontend/src/pages/BYONImages/BYONImagesTable.tsx
frontend/src/pages/BYONImages/ImportBYONImageButton.tsx
frontend/src/pages/acceleratorProfiles/screens/list/AcceleratorProfileEnableToggle.tsx
frontend/src/pages/acceleratorProfiles/screens/list/DisableAcceleratorProfileModal.tsx
frontend/src/pages/acceleratorProfiles/screens/manage/ManageAcceleratorProfileTolerationsSection.tsx
frontend/src/pages/acceleratorProfiles/screens/manage/tolerations/ManageTolerationModal.tsx
frontend/src/pages/acceleratorProfiles/screens/manage/tolerations/TolerationsTable.tsx
frontend/src/pages/notebookController/screens/admin/NotebookAdminControl.tsx
frontend/src/pages/notebookController/screens/server/NotebookServer.tsx
frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
frontend/src/pages/notebookController/screens/server/StopServerModal.tsx
frontend/src/pages/projects/notebook/NotebookActionsColumn.tsx
frontend/src/pages/projects/notebook/NotebookStateStatus.tsx
frontend/src/pages/projects/notebook/StartNotebookModal.tsx
frontend/src/pages/projects/notebook/StopNotebookConfirmModal.tsx
frontend/src/pages/projects/pvc/AddNotebookStorage.tsx
frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx
frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTable.tsx
frontend/src/pages/projects/screens/detail/data-connections/ManageDataConnectionModal.tsx
frontend/src/pages/projects/screens/detail/notebooks/NotebookTable.tsx
frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx
frontend/src/pages/projects/screens/detail/storage/StorageList.tsx
frontend/src/pages/projects/screens/detail/storage/StorageTable.tsx
frontend/src/utilities/notebookControllerUtils.ts

Closes [RHOAIENG-12117](https://issues.redhat.com/browse/RHOAIENG-12117)
Adds an eslint rule to not allow rendering modals that are not visible. Updates remaining modal usages to only render modals that are open.
Run thru the UI and check that then modals are shown only when they should be shown.
- In the UI, add `?devFeatureFlags` to the URL
- in the top banner, click the `overridden` link
- verify the `Feature flags` modal is shown 
- From the `Model Registry` page
- Select a model with versions
- From the mode versions page, select a model version
- Select `Edit` labels
- Click the `Add label` label
- Verify the `Add label` modal is shown
- From the Setting -> `Accelerator profiles` page
- Click the `Enable` switch for an enabled profile
- verify the `Disable accelerator profile` modal …

Conditionally render modals

---

frontend/src/concepts/dashboard/DashboardLogViewer.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTabStatus.tsx

JIRA: https://issues.redhat.com/browse/RHOAIENG-6582
Follow the mockup to do the following updates:
1. Update the alert text, add 2 links to allow users to view raw logs or download the current step in the alert
2. Add a mousedown event to capture the highlight and click the event in the log window and pause the logs as needed
3. Updated the tooltip and icon for pause/resume logs
4. Remove the log viewer footer
1. Check the JIRA comment, use the log-forever-pipeline and create a run
2. Check the node logs, and verify all the changes based on the [mockup](https://www.figma.com/proto/etbN0ccCcZR1qKCpJXQNAg/Pipeline-phase-2?page-id=12031%3A86470&node-id=12534-92933&node-type=frame&viewport=714%2C-1503%2C0.35&t=214XjsqaSYtM6ngc-1&scaling=scale-down-width&content-scaling=fixed&starting-point-no …

UX updates for pipeline logs

---

frontend/src/__mocks__/mockModelRegistry.ts
frontend/src/__tests__/cypress/cypress/pages/modelRegistrySettings.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistrySettings/modelRegistrySettings.cy.ts
frontend/src/pages/modelRegistrySettings/ModelRegistriesTable.tsx
frontend/src/pages/modelRegistrySettings/ModelRegistriesTableRow.tsx
frontend/src/pages/modelRegistrySettings/ModelRegistrySettings.tsx

Closes: [RHOAIENG-13091](https://issues.redhat.com/browse/RHOAIENG-13091)
This PR aims to disable the Manage Permissions when model registry is in not ready state.
Create a model registry
when Model registry is in progressing state, Manage permissions on the model registry table will be disabled.
Updated cypress test.

Disable manage permissions when no rolebinding present for the default group

---

frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelRegistry.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersions.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/registeredModelArchive.cy.ts
frontend/src/concepts/modelRegistry/apiHooks/__tests__/useModelVersions.spec.ts
frontend/src/concepts/modelRegistry/apiHooks/useModelVersions.ts
frontend/src/pages/modelRegistry/screens/ModelRegistry.tsx
frontend/src/pages/modelRegistry/screens/RegisteredModels/RegisteredModelListView.tsx
frontend/src/pages/modelRegistry/screens/RegisteredModelsArchive/RegisteredModelsArchive.tsx
frontend/src/pages/modelRegistry/screens/RegisteredModelsArchive/RegisteredModelsArchiveListView.tsx
frontend/src/pages/modelRegistry/screens/__tests__/utils.spec.ts
frontend/src/pages/modelRegistry/screens/utils.ts

https://issues.redhat.com/browse/RHOAIENG-14022 
https://issues.redhat.com/browse/RHOAIENG-13056
[RHOAIENG-14022](https://issues.redhat.com//browse/RHOAIENG-14022)  : See screenshot showing that the filer is now working in Archived Models by Owner - Results when there is a match vs no results when not match
[RHOAIENG-13056](https://issues.redhat.com//browse/RHOAIENG-13056) See screenshot showing that a model that has a version coming back by that keyword and is showing up by that version label even on the model level search by Keyword 
On the UI
Added tests for the hook and fixed other tests 

Search by Owner on Archived + Search Version Level by keyword

---

frontend/src/pages/clusterSettings/ModelServingPlatformSettings.tsx

JIRA: https://issues.redhat.com/browse/RHOAIENG-4147
Follow the description and change the text.
Go to the settings page, deselect single-serving platform or multi-serving platform. Check the alert text.
N/A, minor text change.

Update alert text when disabling multi-serving platform or single-serving platform

---

frontend/src/pages/modelServing/screens/projects/NIMServiceModal/NIMPVCSizeSection.tsx
frontend/src/pages/projects/components/PVSizeField.tsx

https://issues.redhat.com/browse/RHOAIENG-14037
Added another line of helper text and removed 'Mi' option.
Tested to make sure 'Mi' does not show up as an option for NIM.

NIM storage size field update

---

frontend/src/concepts/trustyai/content/TrustyDBExistingSecretField.tsx

https://issues.redhat.com/browse/RHOAIENG-14314
Couple PR followups to the previous effort to add DB field to trusty startup
See https://github.com/opendatahub-io/odh-dashboard/pull/3305 for setup. Basically this is all frontend so you just need trusty enabled and to interact with the UI modal for configuring it.
None, UI quirks.

Cleanup the existing secret field functionality

---

frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineVersionImportModal.ts
frontend/src/concepts/pipelines/content/compareRuns/CompareRunTableToolbar.tsx
frontend/src/concepts/pipelines/content/experiments/ExperimentLoadingError.tsx
frontend/src/concepts/pipelines/content/import/PipelineImportBase.tsx
frontend/src/concepts/pipelines/content/import/PipelineImportModal.tsx
frontend/src/concepts/pipelines/content/import/PipelineVersionImportModal.tsx
frontend/src/concepts/pipelines/content/import/useImportModalData.ts
frontend/src/concepts/pipelines/content/tables/pipelineRun/EmptyRunsState.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableToolbar.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableToolbarBase.tsx
frontend/src/pages/pipelines/global/experiments/ActiveExperimentsList.tsx
frontend/src/pages/pipelines/global/experiments/ArchivedExperimentsList.tsx
frontend/src/pages/pipelines/global/experiments/compareRuns/ManageRunsPage.tsx
frontend/src/pages/pipelines/global/experiments/compareRuns/ManageRunsTable.tsx
frontend/src/pages/pipelines/global/pipelines/PipelineVersionCreateRunPage.tsx
frontend/src/pages/pipelines/global/pipelines/PipelineVersionDetailsBreadcrumb.tsx
frontend/src/pages/pipelines/global/pipelines/PipelineVersionDuplicateRecurringRunPage.tsx
frontend/src/pages/pipelines/global/pipelines/PipelineVersionRecurringRunDetails.tsx
frontend/src/pages/pipelines/global/pipelines/PipelineVersionRecurringRunsBreadcrumb.tsx
frontend/src/pages/pipelines/global/pipelines/PipelineVersionRunDetails.tsx
frontend/src/pages/pipelines/global/pipelines/PipelineVersionRuns.tsx
frontend/src/pages/pipelines/global/runs/ActiveRuns.tsx

https://issues.redhat.com/browse/RHOAIENG-12667
Fixes duplicate code in pipelines based on the output of
```bash
npx jscpd . --ignore "**/*.spec.*,**/__tests__/**" -r html --ignore-pattern "import.*from\s*'.*'" -l 20 --pattern "**/pipelines/**"
```
I choose 20 because anything smaller was not worth creating shared components. There are some still in the 20 line range but those could not be created into shared components or it was unnatural to make them into a shared component. At 30 lines, all duplication was removed.
Test each area of duplication. they are separated by commit.
1. Import pipeline and import pipeline version modal
2. pipeline run table toolbar (search dropdown)
- can be seen in compare runs, compare runs manage runs, and run list page
3. pipeline active runs table empty …

Task/rhoaieng 12667  tech debt cleanup duplicate code in pipelines co

---

frontend/src/__tests__/cypress/cypress/tests/mocked/projects/connections.cy.ts

Adjusted cypress tests for connections to assert intercept payloads
Tested locally 
Changed tests from `cy.wait('@createConnection');` and `cy.wait('@editConnection');` to be a proper cypress intercept 

Connections interception

---

frontend/src/components/OdhCard.scss
frontend/src/components/OdhExploreCard.tsx

Fixes [RHOAIENG-7709](https://issues.redhat.com/browse/RHOAIENG-7709)
Adds z-index to the partner badge for selectable cards so that it shows above the card overlay and displays the tooltip on hover. Adds the pointer cursor and handles the click event when the card is not disabled (so that click on the badge still selects the card).
- On the `Explore` page, for an enabled card:
-  hover over the badge, verify the tooltip for the badge is shown and the cursor remains the pointer cursor
- click on the badge, verify the card becomes selected and the side panel shows its details
- On the `Explore` page, for disabled card  (I tested by forcing cards to be disabled):
- hover over the badge, verify the tooltip for the badge is shown
- click on the badge, verify nothing happens
Automated testing …

Fix to show tooltip on explore card badges

---

frontend/package-lock.json

CVE fix for JIRA: https://issues.redhat.com/browse/RHOAIENG-13432
Refer to the changes in https://github.com/opendatahub-io/odh-dashboard/pull/3188
Override packages:
express: 4.19.2 -> 4.20.0
body-parser: 1.20.2 -> 1.20.3

CVE-2024-45590 odh-dashboard-container: Denial of Service Vulnerability in body-parser [rhoai-2.13]

---

frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightContent.tsx

Closes: [RHOAIENG-12089](https://issues.redhat.com/browse/RHOAIENG-12089)
Added copy clipboard and copy button in the Pipeline run graph execution node drawer.
Open a pipeline run execution and click on the node to open right drawer. Check the clipboard copy and popover text.
N/A
@yannnz

Add explanation and copy action for the Pod name in the Pipeline run graph execution node drawer

---

frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts
frontend/src/pages/modelServing/screens/global/InferenceServiceEndpoint.tsx
frontend/src/pages/modelServing/screens/global/InternalServicePopoverContent.tsx

Closes: [RHOAIENG-7579](https://issues.redhat.com/browse/RHOAIENG-7579)
This PR aims to display internal addresses even when models are external.
check the inference endpoint:
when external route is enabled: 
- it should display both internal and external address
when external route is not enabled
- it should only show internal address
Added cypress tests.

Display internal addresses even when models are external

---

frontend/src/pages/modelRegistrySettings/ModelRegistryTableRowStatus.tsx

https://issues.redhat.com/browse/RHOAIENG-13047
Made the labels indicate they are hoverable in Settings page
https://github.com/user-attachments/assets/31648c76-ee87-4b39-80b8-316f4e594ced
On the UI

Make Label Cursor Hoverable 

---

backend/src/types.ts
backend/src/utils/constants.ts
backend/src/utils/resourceUtils.ts
docs/dashboard-config.md
frontend/src/__mocks__/mockDashboardConfig.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelMetrics.cy.ts
frontend/src/concepts/areas/const.ts
frontend/src/k8sTypes.ts
manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
manifests/rhoai/shared/odhdashboardconfig/odhdashboardconfig.yaml

https://issues.redhat.com/browse/RHOAIENG-14126
renames trusty flag to disableTrustyBiasMetrics and removed logic in the resourceUtils that prevents RHOAI from using the feature flag
Make sure enable trusty is visible in the permissions tab
no test impact

rename trusty flag to disableTrustyBiasMetrics

---

frontend/src/__tests__/cypress/cypress/pages/projects.ts
frontend/src/__tests__/cypress/cypress/pages/workbench.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectList.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/workbench.cy.ts
frontend/src/pages/projects/notebook/NotebookActionsColumn.tsx
frontend/src/pages/projects/notebook/NotebookStateAction.tsx
frontend/src/pages/projects/notebook/NotebookStateStatus.tsx
frontend/src/pages/projects/notebook/utils.ts
frontend/src/pages/projects/screens/detail/notebooks/NotebookList.tsx
frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx
frontend/src/pages/projects/screens/detail/notebooks/data.ts
frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx
frontend/src/pages/projects/screens/projects/ProjectTableRowNotebookTable.tsx
frontend/src/pages/projects/screens/projects/ProjectTableRowNotebookTableRow.tsx
frontend/src/pages/projects/screens/projects/notebookTableData.tsx
frontend/src/pages/projects/screens/projects/tableData.tsx
frontend/src/utilities/useRefreshInterval.ts

Closes [RHOAIENG-14674](https://issues.redhat.com/browse/RHOAIENG-14674)
PM review revealed the inability to quickly find active workbenches and the need for too many click to shutdown active workbenches. Updated the Project list view to show active workbenches in the workbenches column. Added start/stop actions to each work bench row rather than have them in the kebab menu.
Navigate to the Data Science Project page.
Verify the workbench counts for stopped or active workbenches are accurate (workbenches in the `starting` phase are counted as active).
Expand the workbenches column for projects with active and stopped workbenches.
Verify the correct action is shown (start or stop) based on the workbench status.
Updated the e2e tests to check for the correct counts and actions
Self checklist …

Update project list view to readily show active notebooks

---

frontend/src/concepts/pipelines/content/__tests__/utils.spec.tsx
frontend/src/concepts/pipelines/content/compareRuns/CompareRunTableRow.tsx
frontend/src/concepts/pipelines/content/tables/experiment/renderUtils.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx
frontend/src/concepts/pipelines/content/tables/renderUtils.tsx
frontend/src/concepts/pipelines/content/utils.tsx
frontend/src/concepts/pipelines/kfTypes.ts
frontend/src/concepts/topology/NodeStatusIcon.tsx
frontend/src/concepts/topology/PipelineDefaultTaskGroup.tsx
frontend/src/concepts/topology/customNodes/ArtifactTaskNode.tsx
frontend/src/concepts/topology/customNodes/StandardTaskNode.tsx
frontend/src/pages/pipelines/global/experiments/executions/ExecutionStatus.tsx
frontend/src/pages/pipelines/global/experiments/executions/ExecutionsTableRow.tsx
frontend/src/pages/pipelines/global/experiments/executions/details/ExecutionDetails.tsx

https://issues.redhat.com/browse/RHOAIENG-11333
Updated icons/labels for statuses based on this figma referenced in the JIRA issue: https://www.figma.com/design/Beh8E4dQQ5hq0Kzd9qLaCZ/Pipelines-v2-enhancements?node-id=582-15436
Verify all pages referenced in the [figma](https://www.figma.com/design/Beh8E4dQQ5hq0Kzd9qLaCZ/Pipelines-v2-enhancements?node-id=582-15436) (or [this doc](https://docs.google.com/document/d/1psldOcTvZskdnuedg7CI05UiA-l7mQWfSPMCdRI6vAA/edit#heading=h.l5i04lmgilak), which is just another way of consuming the same information) match.
Had to update some tests to account for icon changes. Otherwise, these are non-functional changes so shouldn't effect cypress tests. …

[RHOAIENG-11333] Modify status labels for runs and executions

---

backend/src/types.ts
backend/src/utils/constants.ts
docs/dashboard-config.md
frontend/src/__mocks__/mockDashboardConfig.ts
frontend/src/concepts/areas/const.ts
frontend/src/concepts/areas/types.ts
frontend/src/k8sTypes.ts
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
manifests/rhoai/shared/odhdashboardconfig/odhdashboardconfig.yaml

Part of [RHOAIENG-14688](https://issues.redhat.com/browse/RHOAIENG-14688)
Adding feature flag `disableServingRuntimeParams` to add "Configuration parameters" below "Source model location" `FormSection` to `ManageKserveModal` to unblock a part of the above ticket as well as [RHOAIENG-14689](https://issues.redhat.com/browse/RHOAIENG-14689) 
1. Scale down `odh-dashboard` deployment pod.
2. Add the feature flag to `OdhDashboardConfig` CRD and to `odh-dashboard-config` in `opendatahub` namespace. You can switch the feature flag to false for testing this PR.
3. Switch `disableServingRuntimeParams` `true` and `false` and check whether you see "Configuration parameters" in the Kserve modal. You should see it when the feature flag is `false` and vice-versa
Will add tests in a follow-up PR that …

Add feature flag for configuration parameters in Kserve modal

---

frontend/package-lock.json
frontend/package.json
frontend/src/__tests__/unit/testUtils/hooks.ts
frontend/src/concepts/connectionTypes/__tests__/validationUtils.spec.ts
frontend/src/concepts/connectionTypes/fields/ConnectionTypeFormFields.tsx
frontend/src/concepts/connectionTypes/fields/fieldUtils.ts
frontend/src/concepts/connectionTypes/types.ts
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/concepts/connectionTypes/validationUtils.ts
frontend/src/pages/connectionTypes/ConnectionTypesTableRow.tsx
frontend/src/pages/connectionTypes/manage/ConnectionTypeDataFieldModal.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTableRow.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypePage.tsx
frontend/src/pages/connectionTypes/manage/__tests__/ManageConnectionTypeFieldsTableRow.spec.tsx
frontend/src/pages/connectionTypes/manage/advanced/DataFieldAdvancedPropertiesForm.tsx
frontend/src/pages/connectionTypes/manage/advanced/DropdownAdvancedPropertiesForm.tsx
frontend/src/pages/connectionTypes/manage/advanced/FileUploadAdvancedPropertiesForm.tsx
frontend/src/pages/projects/screens/detail/connections/ManageConnectionsModal.tsx
frontend/src/pages/projects/screens/detail/connections/useConnections.ts
frontend/src/pages/projects/screens/spawner/environmentVariables/useNotebookEnvVariables.tsx
frontend/src/utilities/__tests__/useValidation.spec.ts
frontend/src/utilities/useValidation.ts

https://issues.redhat.com/browse/RHOAIENG-13664
Introduces `zod` for form validation. Added basic support to work with zod schemas and validation errors until future integration with a form library.
Added hook `useValidation(<data>, <object schema>)` as a means to integrate `zod` with form which utilize `useGenericObjectState`.
Added schema for connection types and updated the connection types admin form to make use of the schema for validation. This update is only for the main form and not any sub form in modals.
- Enable the `disableConnectionTypes` feature flag
- As a dashboard admin, go to `Settings -> Connection types`
- Test creating, editing, and duplicating a connection type.
- Ensure that the submit button is only enabled when the form is valid.
- Ensure that the fields table …

use zod for form validation of connection types validation

---

frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts
frontend/src/pages/modelServing/screens/global/InferenceServiceStatus.tsx

Closes: [RHOAIENG-10992](https://issues.redhat.com/browse/RHOAIENG-10992)
Updates the data science projects models page to use a popover instead of a tooltip for the status. The message will no longer disappear when trying to select the text, and removes the issue of the screen shaking if the message is too long.
Tested locally
Adjusted cypress tests to check for popover instead of tooltip
Before (hover for tooltip):
After (click for popover)"

Change models tooltip to popover

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionDetails.cy.ts
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionSelector.tsx

Closes: [RHOAIENG-14705](https://issues.redhat.com/browse/RHOAIENG-14705)
This PR aims to update Model registry version selector on the details page title to show only active versions.
1. Go to the model registry
2. Create 2 versions - v1 and v2
3. Archive v2
4. Click on v1 to get into the details page
5. On the top right corner, you will only see v1 (active version)

Update Model registry version selector on the details page title to show only active versions

---

frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTable.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTableRow.tsx
frontend/src/pages/connectionTypes/manage/__tests__/ManageConnectionTypeFieldsTableRow.spec.tsx

https://issues.redhat.com/browse/RHOAIENG-13664
If multiple connection type fields have the same env var name, then an error will appear in the field row adjacent to the env var name. During DnD of the fields, the error marker incorrectly jumps to another row because while dragging the index of the field is changing however the index of the validation error is not. Therefore the two get out of sync.
The fix is to compute the index of the row from the original field set so that the index aligns with the indicies of the validation error.
- enable connection types feature using the `disableConnectionTypes` feature flag
- navigate to `Settings -> Connection types`
- create a connection type
- add multiple fields and sections
- add two fields with the same env var name
- observe the two fields …

fix validation error markers when dnd field row

---

frontend/src/concepts/pipelines/content/tables/experiment/ArchivedExperimentTable.tsx
frontend/src/concepts/roleBinding/RoleBindingPermissionsTableRow.tsx
frontend/src/pages/acceleratorProfiles/screens/list/AcceleratorProfilesTableRow.tsx
frontend/src/pages/acceleratorProfiles/screens/manage/tolerations/TolerationRow.tsx
frontend/src/pages/connectionTypes/ConnectionTypesTableRow.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTableRow.tsx
frontend/src/pages/modelRegistry/screens/ModelPropertiesTableRow.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsHeaderActions.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsTableRow.tsx
frontend/src/pages/modelRegistry/screens/RegisteredModels/RegisteredModelTableRow.tsx
frontend/src/pages/modelRegistrySettings/ModelRegistriesTableRow.tsx
frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
frontend/src/pages/modelServing/screens/metrics/bias/BiasConfigurationPage/BiasConfigurationTableRow.tsx
frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTableRow.tsx
frontend/src/pages/projects/notebook/NotebookActionsColumn.tsx
frontend/src/pages/projects/screens/detail/ProjectActions.tsx
frontend/src/pages/projects/screens/detail/connections/ConnectionsTable.tsx
frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTableRow.tsx
frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx
frontend/src/pages/projects/screens/spawner/connections/ConnectionsFormSection.tsx

Closes [RHOAIENG-13971](https://issues.redhat.com/browse/RHOAIENG-13971)
Adds a menu separator before destructive actions in menus.
Menus with destructive actions:
- Experiments
- Role bindings
- Accelerator profiles
- Tolerations
- Connection types
- Connection type fields
- Connection type sections
- Models
- Model versions (header in details page)
- Model versions (in table)
- Registered models
- Model registries
- Inference services
- Bias configurations
- Serving runtimes
- Notebooks
- Projects
- Connections
- Data connections
- Cluster storage
- Notebook spawner - Detach a connection
No test impact

Update menus to include a divider for separating delete actions

---

frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts
frontend/src/pages/projects/screens/detail/storage/StorageTable.tsx

https://issues.redhat.com/browse/RHOAIENG-13457
Minor text change in deprecated storage alert message
1. Create a DSP and assign multiple storage classes.
2. Disable at least 2 of the storage classes
updated the existing cypress test

Change the deprecated storage alert message

---

frontend/src/__mocks__/mockConnectionType.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/connectionTypes/createConnectionType.cy.ts
frontend/src/pages/connectionTypes/manage/ConnectionTypeDataFieldModal.tsx
frontend/src/pages/connectionTypes/manage/ConnectionTypeSectionModal.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypePage.tsx
frontend/src/pages/connectionTypes/manage/__tests__/ConnectionTypeDataFieldModal.spec.tsx
frontend/src/pages/connectionTypes/manage/__tests__/ConnectionTypeSectionModal.spec.tsx

https://issues.redhat.com/browse/RHOAIENG-14750
Updates the connection type form, along with section and data field modals. When entering these forms through an edit scenario, the form submit button will remain disabled until the form becomes dirty. Dirty is a simple computation in that as soon as any value changes, the form is considered dirty. However returning back to the original value will still be considered dirty.
- enable connection types feature flag 'disableConnectionTypes'
- navigate to `Settings -> Connection types'
Connection type:
- create a connection type
- observe the submit button is disabled until the form is valid
- complete the connection type and save
- edit the connection type
- observe the submit button is disabled
- modify any value or add a section or field
- …

enable edit form submit button only when form is dirty

---

frontend/src/__mocks__/mockConnectionType.ts
frontend/src/concepts/connectionTypes/createConnectionTypeUtils.ts
frontend/src/concepts/connectionTypes/types.ts
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/pages/connectionTypes/ConnectionTypesTableRow.tsx
frontend/src/pages/connectionTypes/columns.ts
frontend/src/services/connectionTypesService.ts

https://issues.redhat.com/browse/RHOAIENG-14749
Replaces annotation `opendatahub.io/enabled` with the inverse `opendatahub.io/disabled`.
- Enable the connection type feature flag: `disableConnectionType`
- Navigate to `Settings -> Connection types`
- Create and edit various connection types. Set the enabled checkbox to checked and unchecked.
- Use the toggle button in the connection types list to toggle the enabled state.
- Navigate to a project via the project list page.
- Go to the `Connections` tab.
- Create a new connection. Observe that only the enabled connections are present.
Existing tests.

change connection types annotation from enabled to disabled

---

frontend/src/__tests__/cypress/cypress/pages/workbench.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/workbench.cy.ts
frontend/src/pages/projects/notebook/NotebookStateAction.tsx

JIRA: [RHOAIENG-14134](https://issues.redhat.com/browse/RHOAIENG-14134)
Simply remove the detection of image availability to unblock users from starting with a deleted notebook image.
1. Import a custom image in the settings page
2. Create a workbench with that image
3. Stop the workbench
4. Delete the custom image you created at step 1
5. Go back to the workbench list, and make sure you can still click the start button. (You will definitely get an error when starting, though)
Added a cypress test case to verify the button is enabled even when the notebook image is deleted.

Allow users to start/stop notebooks when related image is deleted

---

frontend/src/concepts/connectionTypes/utils.ts
frontend/src/concepts/dashboard/DashboardModalFooter.tsx
frontend/src/pages/connectionTypes/manage/ConnectionTypeDataFieldRemoveModal.tsx
frontend/src/pages/connectionTypes/manage/ConnectionTypeFieldMoveModal.tsx
frontend/src/pages/connectionTypes/manage/ConnectionTypeSectionModal.tsx
frontend/src/pages/connectionTypes/manage/ConnectionTypeSectionRemoveModal.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTable.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTableRow.tsx
frontend/src/pages/connectionTypes/manage/__tests__/ConnectionTypeSectionRemoveModal.spec.tsx

https://issues.redhat.com/browse/RHOAIENG-14752
When removing a section, the modal now includes an option to also remove all fields associated to the section; if there are any. Selecting the checkbox will remove the listed fields, otherwise only the section itself is removed.
Also fixed an issue where duplicating a field would add it to the end of the list instead of immediately adjacent to the field you duplicated. This also makes it easier to quickly create fields for testing this issue.
_Note that the spacing between the list and the expandable title is the PF default behavior._
- enable the connection types feature flag `disableConnectionTypes`
- Navigate to `Settings -> Connection types` as an admin
- create a connection type
- Add various sections and fields
- Delete sections …

add option to remove all fields within a connection type section

---

frontend/src/__tests__/cypress/cypress/pages/connectionTypes.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/connectionTypes/connectionTypes.cy.ts
frontend/src/concepts/connectionTypes/ConnectionTypeForm.tsx
frontend/src/concepts/connectionTypes/ConnectionTypePreviewDrawer.tsx
frontend/src/concepts/connectionTypes/ConnectionTypePreviewModal.tsx
frontend/src/pages/connectionTypes/ConnectionTypesTableRow.tsx
frontend/src/pages/projects/screens/detail/connections/ManageConnectionsModal.tsx

https://issues.redhat.com/browse/RHOAIENG-14754
Adds a preview action to connection types which opens a preview modal with the connection form in read only mode.
- enable the connection types feature flag `disableConnectionTypes`
- navigate to `Settings -> Connection types` as an admin
- Create a connection type
- From the connection type list, open the kebab menu for the connection type and select `Preview`
- Observe the preview modal is read only and can be closed

create preview modal for connection types

---

frontend/src/pages/modelServing/screens/projects/kServeModal/EnvironmentVariablesSection.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ServingRuntimeArgsSection.tsx

closes: [14688](https://issues.redhat.com/browse/RHOAIENG-14688)
closes: [14689](https://issues.redhat.com/browse/RHOAIENG-14689)
the UI components only of Additional Serving Runtime Args and Env Vars for the Manage KServe Modal. Leaving the "View Predefined __" buttons for later story as they require working around the PF components a bit.
1. You should see both the "Additional serving runtime arguments" and "Additional environment variables" fields when the `disableServingRuntimeParams` feature flag is turned on
tests will need to be added along with connecting the data to the UI components.
check that these two sections work for KServe deploy modal. No data connections, but the help info, placeholder, adding/removing/editing env vars, etc shoudl work. Will need …

14688-14689: add ui component of runtime args and env vars

---

frontend/src/concepts/connectionTypes/ConnectionDetailsHelperText.tsx
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ConnectionSection.spec.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
frontend/src/pages/modelServing/screens/projects/utils.ts
frontend/src/pages/projects/screens/detail/connections/ManageConnectionsModal.tsx
frontend/src/pages/projects/screens/detail/connections/useConnections.ts
frontend/src/utilities/useWatchConnectionTypes.tsx

https://issues.redhat.com/browse/RHOAIENG-13139
Replaces the data connections section in the model serving modals with connection types. The existing connection has fairly similar behavior. The new connection options has the ability to create a new connection inline, 
Updated the single kserving modal and the modelmesh multi model modals.
1. Set disableConnectionTypes dev flag to false
2. either navigate to a project and open the "Models" details section OR go to `/modelServing` which is the "Model Serving" on the left nav bar
3. Make sure you have a runtime setup 
-  (either single serving or multi. you can have 2 projects with each having one of them)
4. Edit or deploy a new model
- Try various combinations of connections types and connection instances on the project
Jest tests added …

Add connection type to model serving create modal

---

frontend/src/__mocks__/mockNotebookK8sResource.ts
frontend/src/__tests__/cypress/cypress/pages/workbench.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/dataConnection.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/workbench.cy.ts
frontend/src/api/k8s/__tests__/notebooks.spec.ts
frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
frontend/src/pages/projects/screens/spawner/environmentVariables/AlertWarningText.tsx
frontend/src/pages/projects/screens/spawner/environmentVariables/useNotebookEnvVariables.tsx
frontend/src/pages/projects/screens/spawner/environmentVariables/utils.ts
frontend/src/pages/projects/screens/spawner/service.ts

https://issues.redhat.com/browse/RHOAIENG-1891
- If a cluster admin deletes secrets or config maps that a Notebook resource (workbench) uses, then editing notebook will display a alert warning stating which secret or configmap is deleted 
- if you click on the update workbench, the notebook will be updated successfully without any error and the secrets/ configmaps will be removed from envFrom
- You can even delete the notebook which has secrets/configMaps deletd by clusteradmin successfully without any error
1. Create a workbench with secret or configMap env variables and 
2. Delete one of the env variables from console
3. Stop the workbench and edit the workbench
4. check the workbench with alert warning
5. check whether the workbench updates successfully
6. delete the workbench which …

Deleting workbench resource makes workbench editable

---

frontend/src/concepts/areas/utils.ts
frontend/src/k8sTypes.ts

JIRA: https://issues.redhat.com/browse/RHOAIENG-14095
This is because the `installedComponents` is possibly `undefined` in the first few minutes after the operator is deployed. It will be called `Array.reduce` later, which causes the error because you cannot call `Array.reduce` on `undefined`. Change the type to optional could help with this issue.
You can change the backend to mockup the DSC return value to see the result on the frontend. At https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/utils/dsc.ts#L14, change it to
```
.then((res) => {
const body = (res.body as DataScienceClusterList).items[0];
delete body.status.installedComponents;
return body;
})
```
And see the change of the frontend. Before the change in this PR, you should get a crashed dashboard with the …

Fix type error in DSC to prevent crashing when operator first deployed

---

frontend/src/concepts/connectionTypes/ConnectionDetailsHelperText.tsx
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ConnectionSection.spec.tsx

Follow up to https://issues.redhat.com/browse/RHOAIENG-13139 
Clarification detailed that we will show the connection type name instead of the categories. 
1. Go to model serving
2. Create or edit an existing model serving deployment.
3. The "Existing connection" radio option will show the connection type in the option description and click the "View connection details" to see it in the popover.
I did actually update a test and the option selection will include the "type: s3"  in the description, so the test confirms it works.
@simrandhaliw 

Show conn type name in options and details

---

frontend/src/__tests__/cypress/cypress/pages/connectionTypes.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/connectionTypes/createConnectionType.cy.ts
frontend/src/pages/connectionTypes/manage/DuplicateConnectionTypePage.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypePage.tsx

https://issues.redhat.com/browse/RHOAIENG-14751
Updates the edit connection type page banner to include a `Duplicate` action which changes the form from edit to create and copies over all changes in the form to the new form.
- enable connection types feature flag `disableConnectionTypes`
- Navigate to `Settings -> Connection types` as an admin
- Create a new connection type
- Edit that connection type
- make some changes in the form
- Click the `Duplicate` action link in the alert at the top of the page
- Observe the page changes to a create form, the url includes `/duplicate` and the form contains all the changes previously made.
- Note that if the display name was changed, the new name in the create form is unchanged. If however the name was unchanged, we prefix the name with `Copy of` …

add action to duplicate connection type when editing

---

frontend/src/__mocks__/mockStatus.ts
frontend/src/app/__tests__/AboutDialog.spec.tsx
frontend/src/concepts/analyticsTracking/useSegmentTracking.ts
frontend/src/concepts/analyticsTracking/useTrackUser.ts
frontend/src/pages/projects/screens/projects/__tests__/EmptyProjects.spec.tsx
frontend/src/pages/projects/screens/spawner/__tests__/SpawnerFooter.spec.tsx
frontend/src/redux/actions/actions.ts
frontend/src/redux/reducers/appReducer.ts
frontend/src/redux/selectors/types.ts
frontend/src/redux/selectors/user.ts
frontend/src/redux/types.ts
frontend/src/utilities/__tests__/useDetectUser.spec.ts

Closes https://issues.redhat.com/browse/RHOAIENG-14811
We now get the userID from the status api endpoint if set. 
This builds on RHOAIENG-9480/PR #3107.
This closes the first try in #3362
The previous code did not correctly pass the userID from the backend around in the frontend.
The backend already has it correctly on a 2.14 cluster and provides it via /api/status call.
Manual test in dev-mode running `npm run start:dev:ext` against an instance on Dev-Sandbox and a non-Sandbox one.
Then looking at the console output for the the Identify event
```
Identify event triggered: {... "userID":"b09067a69...99"}
```
If the userID looks like this (whith chars) it is an anonymous one. If it is numeric (may be negative) and short (probably < 8 digits), then it is a web-user-id. 
Self checklist (all …

RHOAIENG-14811 The userdID was not correctly transferred to the frontend

---

frontend/src/pages/connectionTypes/ConnectionTypesTableRow.tsx
frontend/src/pages/connectionTypes/manage/EditConnectionTypePage.tsx
manifests/common/connection-types/kustomization.yaml
manifests/common/connection-types/oci-compliant-registry-v1.yaml
manifests/common/connection-types/s3.yaml
manifests/common/connection-types/uri-v1.yaml

[RHOAIENG-13105](https://issues.redhat.com/browse/RHOAIENG-13105)
Adds yaml files for OOTB connection types. Updates the connection type page to not allow editing of the OOTB connection types. Fixes an issue where the connection types table does not update when new connections are added or modified.
- Run the UI and navigate to Settings -> Connection types
- Install the connection types:
- Set the project to opendatahub: `oc project opendatahub`
- oc apply -f manifests/common/connection-types/s3.yaml
- oc apply -f manifests/common/connection-types/oci-compliant-registry-v1.yaml
- oc apply -f manifests/common/connection-types/uri-v1.yaml
- Verify the connection types are shown in the UI without needing to refresh the page within 30 seconds
- From the OpenShift Console, go to Administrator …

Add P0 OOTB connection types

---

backend/src/routes/api/service/mlmd/index.ts
backend/src/routes/api/service/pipelines/index.ts
frontend/src/__mocks__/mockDataSciencePipelinesApplicationK8sResource.ts
frontend/src/__tests__/cypress/cypress/fixtures/resources/yaml/dspa.yaml
frontend/src/api/models/pipelines.ts

https://issues.redhat.com/browse/RHOAIENG-13935
DataSciencePipelineApplicationModels to be bumped to v1
- Adjust the pipeline devFlags to point to main 
- check whether pipeline server created successfully
Updated the mock function to use v1

bump v1alpha1 to v1

---

backend/src/routes/api/service/mlmd/index.ts
backend/src/routes/api/service/pipelines/index.ts
frontend/src/__mocks__/mockDataSciencePipelinesApplicationK8sResource.ts
frontend/src/__tests__/cypress/cypress/fixtures/resources/yaml/dspa.yaml
frontend/src/api/models/pipelines.ts

This reverts commit 4842b35c35c639c7fe448a7fa708261b19e2788a.
revert commit that might put us in a bad state on upgrade
make sure you can access DS projects and pipelines
none just a revert

Revert "bump v1alpha1 to v1 (#3391)"

---

frontend/src/pages/modelServing/screens/projects/kServeModal/ServingRuntimeArgsSection.tsx

Followup to https://issues.redhat.com/browse/RHOAIENG-14688 (#3384)
A line of microcopy in the mockups changed since #3384 was opened, this just updates it to the correct text.
cc @yih-wang 
Tested locally, saw that the text renders correctly
N/A, microcopy change

Quick update to help text (followup to #3384)

---

backend/src/routes/api/connection-types/index.ts

https://issues.redhat.com/browse/RHOAIENG-15217
Connection type `GET` endpoint was secured behind admin protection. This PR makes it so that a regular user can use this endpoint.
- enable the connection types feature flag `disableConnectionTypes`
- As an admin:
- navigate to `Settings -> Connection types`
- observe OOBT connection types listed
- As a regular user:
- navigate to project details -> connections tab
- page loads without error and can create a connection 
N/A backend change

remove admin requirement to fetch connection types

---

frontend/src/__tests__/cypress/cypress/pages/connectionTypes.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/connectionTypes/createConnectionType.cy.ts
frontend/src/components/SimpleMenuActions.tsx
frontend/src/concepts/connectionTypes/__tests__/utils.spec.ts
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/pages/connectionTypes/manage/ManageConnectionTypePage.tsx
frontend/src/utilities/__tests__/string.spec.ts
frontend/src/utilities/string.ts

https://issues.redhat.com/browse/RHOAIENG-14813
Adds a dropdown to the connection type creation page to add model serving compatible fields.
All OOTB types are present in the dropdown.
Selecting one of the types inserts a new section field along with all other fields found in the connection type.
When the connection type is found to be compatible (ie it has the same env vars), then we show an alert. Currently this is based strictly on the env var name and not of the field type or other properties such as required, name or description.
Ensure your cluster has the OOTB connection types applied. https://github.com/opendatahub-io/odh-dashboard/pull/3335
You can manually add them to your cluster with `oc apply -f ...`. They are found in the `manifests/common/connection-types` …

add model serving compatible select to connection type form

---

frontend/src/concepts/design/TypeBorderCard.scss
frontend/src/concepts/design/utils.ts
frontend/src/concepts/design/vars.scss
frontend/src/pages/projects/screens/detail/ProjectDetails.tsx

Closes [RHOAIENG-14753](https://issues.redhat.com/browse/RHOAIENG-14753)
The color palette used for resources has been updated in the new [guidelines](https://docs.google.com/document/d/1OdaE6LjTikTMTIOHvgGQzRDJpm9Bn-kPxsfoqRh5tsU/edit#heading=h.v94u92bpa671)
Navigate thru the UI and check the colors for each resource type.
No automated test impact as this is only a change in colors.
/cc @simrandhaliw @tobiastal

Update UI to use new resource color palette

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionDetails.cy.ts
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx

[HOAIENG-14812](https://issues.redhat.com/browse/RHOAIENG-14812)
A follow up fix for the saving wasn't working because of an API changed made. Added the needed value the API was needing. 
on MR UI- PLEASE use only modelregistry-sample-2 or a new model registry you create, as there is a bug on the API side that doesn't patch the old registries.
Test were written in the original feature PR

MR API patch error fix

---

frontend/src/pages/projects/screens/detail/connections/ConnectionsList.tsx

When the empty state is shown on the connection tab, the `Create connection` button would not open the modal. This is because the modal was rendered within the children of the details page. 
The fix is simply to move the modal rendering to a fragment sibling of the details component.
- Enable the connection types feature flag `disableConnectionTypes`
- Create a project
- Go to the project details -> Connections tab
- Click the `Create connection` button in th empty state
- Observe the modal to create a connect opens
- Complete the modal
- Observe the new connection in the table
N/A

unable to create a connection from the empty state

---

frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ServingRuntimeArgsSection.tsx

closes: https://issues.redhat.com/browse/RHOAIENG-14691
no change until serving runtime is selected, at which point a helptext with link shows up:
clicking that link will scroll (if necessary) and focus on the additional args textarea
locally
added tests that it doesn't show up initially, until selecting serving runtime
should only show up in kserve, with servingRunTimeParamsEnabled, and after selecting a serving runtime

feat(14691): serving runtime link to args

---

frontend/src/__tests__/cypress/cypress/tests/mocked/application.cy.ts
frontend/src/app/AppLauncher.tsx

https://issues.redhat.com/browse/RHOAIENG-10502
Changed the header value of the "Applications" section to be "Red Hat Applications" instead of referencing the product name.
The ODH console link no longer appears in the ODH Dashboard application menu therefore no changes were required in this regard cc @manosnoam.
Before:
After:
Click on app launcher icon in page masthead. 
Updated `application.cy.ts`.

[RHOAIENG-10502]: Update App Launcher Title

---

frontend/src/__mocks__/mockConnection.ts
frontend/src/__tests__/cypress/cypress/pages/connectionTypes.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/connectionTypes/connectionTypes.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/connections.cy.ts
frontend/src/concepts/connectionTypes/CompatibilityLabel.tsx
frontend/src/concepts/connectionTypes/__tests__/utils.spec.ts
frontend/src/concepts/connectionTypes/types.ts
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/pages/connectionTypes/ConnectionTypesTableRow.tsx
frontend/src/pages/connectionTypes/columns.ts
frontend/src/pages/connectionTypes/manage/ManageConnectionTypePage.tsx
frontend/src/pages/projects/screens/detail/connections/ConnectionsTableRow.tsx
frontend/src/pages/projects/screens/detail/connections/connectionsTableColumns.ts
frontend/src/pages/projects/screens/detail/connections/useConnections.ts
frontend/src/utilities/useWatchConnectionTypes.tsx

https://issues.redhat.com/browse/RHOAIENG-14813
Connections:
Connection types:
- Enable the connection types feature flag `disableConnectionTypes`
- As an admin, navigate to `Settings -> Connection types`
- Observe the preinstalled types show the correct model serving compatibility labels.
- Duplicate a preinstalled type or hand craft a new type with appropriate model serving fields with appropriate env var names (can use the dropdown to auto add matching types).
- Observe the alert indicates the compatible model serving types.
- Create a new project
- Go to the project details -> Data Connections tab (testing data connection compatibility
- Create a new data connection (include a value for the Bucket field)
- Go to the Connections tab
- Observe the new connection is compatible with s3 …

update model serving compatibility for connection types

---

frontend/src/pages/projects/screens/detail/ProjectDetails.tsx

https://issues.redhat.com/browse/RHOAIENG-14748
While we figure out whether the connection types feature flag will persist or not, we should ensure all data connection related UIs are turned off when connection types is turned on. 
This change simply conditionally renders the project details data connections tab.
- enable the connection types feature flag `disableConnectionTypes`
- create a project
- go to the project details
- observe the Connections tab is present while the data connections tab is not
N/A

remove data connections tab when connection types is enabled

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/registerModel.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/registerVersion.cy.ts
frontend/src/pages/modelRegistry/screens/RegisterModel/RegisterModel.tsx
frontend/src/pages/modelRegistry/screens/RegisterModel/RegistrationCommonFormSections.tsx
frontend/src/pages/modelRegistry/screens/RegisterModel/const.ts
frontend/src/pages/modelRegistry/screens/RegisterModel/utils.ts

Closes: [RHOAIENG-12844](https://issues.redhat.com/browse/RHOAIENG-12844)
This PR aims to add character length limit to both model name and version name in Register model and Register version forms. Also to use the given model name for the RegisteredModel and the given version name for both the ModelVersion and the ModelArtifact.
1. In model registry, click on Register model.
2. check the helper text "Cannot exceed 128 characters" is under model name and version name field.
3. Try to type in a long string, length greater than 128, you will see an error and it will disable the Register model button.
4.  Same goes for Register version form, try to Register a version with lang name and you will see the error in helper text and Register version button will be disabled. 
5. For Register …

Add character length limit to both model name and version name

---

frontend/src/__tests__/cypress/cypress/tests/mocked/connectionTypes/connectionTypes.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/connections.cy.ts
frontend/src/concepts/connectionTypes/types.ts
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
frontend/src/pages/projects/screens/detail/connections/ConnectionsTable.tsx
frontend/src/pages/projects/screens/detail/connections/ConnectionsTableRow.tsx
frontend/src/pages/projects/screens/detail/connections/ManageConnectionsModal.tsx
frontend/src/pages/projects/screens/detail/connections/connectionsTableColumns.ts
frontend/src/pages/projects/screens/spawner/connections/ConnectionsFormSection.tsx
frontend/src/pages/projects/screens/spawner/connections/SelectConnectionsModal.tsx

Depends on https://github.com/opendatahub-io/odh-dashboard/pull/3417
Problem
- Can’t use `opendatahub.io/connection-type` label arbitrarily because a controller reads this value to populate `storage-config` `Secret` with `s3` properties used by `InferenceService`
- Doesn’t seem to be a way to change the type of the referenced secret in the `InferenceService` outside of our connection `Secret`.
- The `opendatahub.io/managed=true` annotation is used by a controller to identify secrets which will be used to populate the `storage-config` `InferenceService` will fail unless the type related to the reference `Secret` is of type `s3`	
Solution
- At connection creation / edit time, set `opendatahub.io/managed=true` and `opendatahub.io/connection-type=s3` if the connection is an s3 model serving …

update to use connection-type-ref annotation

---

frontend/src/__tests__/cypress/cypress/pages/workbench.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/workbench.cy.ts
frontend/src/pages/projects/notebook/NotebookStateStatus.tsx
frontend/src/pages/projects/notebook/StartNotebookModal.tsx
frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx
frontend/src/pages/projects/screens/projects/ProjectTableRowNotebookTableRow.tsx

JIRA: https://issues.redhat.com/browse/RHOAIENG-14737
Update several places:
1. Update the waiting message from "Waiting for notebook to start..." to "Waiting for workbench to start..." and the popover title from "Notebook status" to "Workbench status"
2. Update the event modal title from "Starting server" to "Starting workbench" and Update the cancel button text from "Cancel" to "Stop workbench"
3. When stop workbench from the event modal, it will also prompt a confirmation modal now
1. Create a workbench
2. Start and stop it, check the event modal
3. Make sure all the content and behavior are as described
Updated some cypress tests to adapt to the change

UX updates for content and behavior in event log modal for a starting workbench

---

frontend/src/__tests__/cypress/cypress/pages/projects.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectDetails.cy.ts
frontend/src/concepts/pipelines/context/PipelinesContext.tsx
frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCard.tsx
frontend/src/pages/projects/screens/detail/pipelines/PipelinesSection.tsx

JIRA: https://issues.redhat.com/browse/RHOAIENG-14133
Updated the project pipelines card and tab, showing the same error message and actions to align it with the global pipelines page when there is an error.
Also, when click on the delete button, it will bump the same deleting model to confirm whether you want to delete it or not.
1. Configure a pipeline server using an invalid data connection
2. Wait for a few minutes
3. Check the error states in the project details page, and check whether the error message is shown on both the pipelines card and pipelines tab section in that project
4. Try to delete the server using the action in the alert, make sure it opens a confirmation modal before deleting
Added a Cypress test to verify the error state on the project details page
Self checklist …

Show pipeline server error on project pipelines card and tab section

---

frontend/src/pages/projects/screens/detail/connections/ConnectedResources.tsx
frontend/src/pages/projects/screens/detail/connections/ConnectionsDeleteModal.tsx
frontend/src/pages/projects/screens/detail/connections/ConnectionsTable.tsx
frontend/src/pages/projects/screens/detail/connections/__tests__/ConnectionsDeleteModal.spec.tsx

Closes [RHOAIENG-14208](https://issues.redhat.com/browse/RHOAIENG-14208)
When removing a connection, delete the env var from the env var list of any connected notebooks
Delete a connection that has connected notebooks
Go to the workbenches tab and edit the notebooks that were connected.
Verify the connection is no longer listed in the Connections section

Delete connection ref from notebooks when connection is deleted

---

frontend/src/concepts/connectionTypes/validationUtils.ts
frontend/src/pages/connectionTypes/manage/ConnectionTypeDataFieldModal.tsx
frontend/src/pages/projects/screens/detail/connections/ConnectionsList.tsx
frontend/src/pages/projects/screens/spawner/connections/ConnectionsFormSection.tsx

https://issues.redhat.com/browse/RHOAIENG-14745
<details><summary>Before</summary>
Environment Variable: Default Help Text
Environment Variable: Error Text
Environment Variable: Warning Text
"Attach existing connection" button tooltip in workbench creation form:
"Create connection" button in Connections tab of project view (tooltip does not exist here):
</details>
<details><summary>After</summary>
Environment Variable: Default Help Text
Environment Variable: Error Text
Environment Variable: Warning Text
"Attach existing connections" button tooltip in "Create workbench" form: 
"Create connection" button tooltip in Connections tab of project view:
</details>
Add field modal:
Connection Types -> "Edit" in kebab dropdown for connection type -> "Add field"
In workbench creation form:
Disable …

[RHOAI-14745]: Apply Final Microcopy Changes

---

frontend/src/__mocks__/mockServingRuntimeTemplateK8sResource.ts
frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ServingRuntimeArgsSection.tsx
frontend/src/pages/modelServing/utils.ts

closes: https://issues.redhat.com/browse/RHOAIENG-14690
the label help button and popover to view default serving runtime args for the selected serving runtime
with no selected serving runtime:
after selecting a serving runtime with no predefined args:
after selecting a serving runtime with predefined args:
tested locally with no runtime selected and with various runtimes
added a test that the popover shows up with default serving runtime arg of the selected runtime
check the popover looks correct with various runtimes selected

feat(14690): default serving runtime args popover

---

frontend/src/__mocks__/mockServingRuntimeTemplateK8sResource.ts
frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
frontend/src/pages/modelServing/screens/projects/kServeModal/EnvironmentVariablesSection.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ServingRuntimeArgsSection.tsx
frontend/src/pages/modelServing/utils.ts

Closes: https://issues.redhat.com/browse/RHOAIENG-14692
No serving runtime selected:
Serving runtime with predefined env vars:
Serving runtime with no predefined env vars:
@yih-wang 
Tested locally with various selections for serving runtime
added tests for the tooltip and popover displaying serving runtime env var
tooltip exists before selecting serving runtime, popover exists after selecting serving runtime and contains env vars (if they exist on serving runtime)

feat(14692): predefined vars popover

---

frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersions.cy.ts
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsTable.tsx

closes https://issues.redhat.com/browse/RHOAIENG-15448
fixed issue where searching on the model details page caused the ui to crash. now correctly shows the no results view:
locally tested with search that has results and search that doesn't
added a test for searching with no matches
searching on the model registry versions page will correctly show results if they exist, and show a "no results found" screen if not.

fix(15448): no match version search crashes ui

---

frontend/src/concepts/pipelines/EnsureCompatiblePipelineServer.tsx
frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCard.tsx

Follow up for [RHOAIENG-14133](https://issues.redhat.com/browse/RHOAIENG-14133)
Per requested here: https://github.com/opendatahub-io/odh-dashboard/pull/3404#discussion_r1827284829, I added an extra check for the pipelines server condition for the pipelines card on the project overview page to make sure it can correctly render the incompatible v1 servers.
1. Change dspVersion from v2 to v1
2. Check the error state on the project overview page pipelines card
N/A

Follow-up fix for RHOAIENG-14133 about pipeline server condition check

---

frontend/src/__tests__/cypress/cypress/pages/storageClasses.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/storageClasses/storageClasses.cy.ts
frontend/src/pages/storageClasses/StorageClassesContext.tsx
frontend/src/pages/storageClasses/StorageClassesPage.tsx

JIRA: https://issues.redhat.com/browse/RHOAIENG-15219
A one-liner change to update the condition to show the alert correctly.
1. Go to OpenShift console and find all the storage classes
2. Find the default storage class, change the annotation `storageclass.kubernetes.io/is-default-class: 'true'` to `storageclass.kubernetes.io/is-default-class: 'false'`
3. Remove the annotation `opendatahub.io/sc-config` from all the storage classes
4. Go back to the Dashboard storage classes settings page and refresh
5. You should be able to see the alert
6. Change the storage class in step 2 back to default
7. Remove the annotation `opendatahub.io/sc-config` from all the storage classes again
8. Go back to the Dashboard storage classes settings page and refresh
9. You shouldn't see the alert even if the …

Show no-default alert correctly when first loading storage classes settings page

---

frontend/src/__tests__/cypress/cypress/pages/connectionTypes.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/connectionTypes/connectionTypes.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/connectionTypes/createConnectionType.cy.ts
frontend/src/concepts/connectionTypes/ConnectionTypeForm.tsx
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/pages/connectionTypes/ConnectionTypesPage.tsx
frontend/src/pages/connectionTypes/manage/DuplicateConnectionTypePage.tsx
frontend/src/pages/connectionTypes/manage/EditConnectionTypePage.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypePage.tsx
frontend/src/services/connectionTypesService.ts

Address review comments from https://issues.redhat.com/browse/RHOAIENG-14740
When creating a new connection type, previously used categories will be shown as options in the categories dropdown along with pre-defined set:
When data in a connection type fails to parse, it was causing the app to error out. Now whenever fetch a list of connection types, the corrupt ones are omitted from the list and no error is thrown which will error out the app.
When using a direct link to edit or duplicate a corrupt connection type, the following error is shown:
- enable the connection type feature flag `disableConnectionTypes`
Categories:
- Navigate to Settings -> Connection types
- Create a new connection type
- add custom categories and save
- create a 2nd connection type
- Observe all previously added …

guard against corrupt connection types and support previous categories

---

frontend/src/__tests__/cypress/cypress/pages/workbench.ts
frontend/src/pages/projects/screens/detail/storage/BaseStorageModal.tsx
frontend/src/pages/projects/screens/detail/storage/ClusterStorageModal.tsx
frontend/src/pages/projects/screens/detail/storage/StorageList.tsx
frontend/src/pages/projects/screens/detail/storage/StorageTable.tsx
frontend/src/pages/projects/screens/spawner/storage/AddExistingStorageField.tsx
frontend/src/pages/projects/screens/spawner/storage/AttachExistingStorageModal.tsx
frontend/src/pages/projects/screens/spawner/storage/SpawnerMountPathField.tsx
frontend/src/pages/projects/screens/spawner/storage/WorkbenchStorageModal.tsx
frontend/src/pages/projects/screens/spawner/storage/__tests__/utils.spec.ts
frontend/src/pages/projects/screens/spawner/storage/const.ts
frontend/src/pages/projects/screens/spawner/storage/types.ts
frontend/src/pages/projects/screens/spawner/storage/utils.ts

[RHOAIENG-7681](https://issues.redhat.com/browse/RHOAIENG-7681)
Added `BaseStorageModal` which defines the structure and functionality of the Create/Edit storage modal.
Two sub-models are created taking `BaseStorageModal` as base.
* `WorkbenchStorageModal` to create/edit cluster storage in Spawner.
* `ClusterStorageModal` to create/edit cluster storage in Storage section under projects page.
Create storage modal: Updated the ManageStorageModal:
Attach storage modal: 
Working of cluster storage modal (will be same as the old one):
https://github.com/user-attachments/assets/8fe94c26-f872-4724-b37d-1970e661b280
Workbench modal:
1. Uncomment the code in SpawnerPage.tsx from lines 244 to 275.
2. Open the spawner page in the dashboard. You will find two new buttons added in the Cluster Storage …

Cluster storage modal

---

frontend/src/pages/modelRegistry/screens/ModelRegistrySelectorNavigator.tsx

Resolves https://issues.redhat.com/browse/RHOAIENG-15471
Prevents infinite loop on mounting the ModelRegistrySelectorNavigator when there is only one registry, caused by  https://github.com/opendatahub-io/odh-dashboard/pull/3345. The `onSelection` callback will be called on first render, which was triggering a navigation that would call it again, triggering an infinite loop. Now it will only navigate if we are not already on the registry we want to navigate to.
I attempted to write a cypress test for this, but the infinite loop was not happening in the Cypress environment so I couldn't get the test to fail without the fix. I gave up 🤷 

Model Registry Selector: don't navigate on selection unless necessary

---

backend/src/routes/api/accelerator-profiles/acceleratorProfilesUtils.ts
frontend/src/__tests__/cypress/cypress/pages/acceleratorProfile.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/acceleratorProfiles/manageAcceleratorProfiles.cy.ts
frontend/src/concepts/k8s/K8sNameDescriptionField/ResourceNameField.tsx
frontend/src/concepts/k8s/K8sNameDescriptionField/types.ts
frontend/src/concepts/k8s/K8sNameDescriptionField/utils.ts
frontend/src/pages/acceleratorProfiles/screens/manage/ManageAcceleratorProfile.tsx
frontend/src/pages/acceleratorProfiles/screens/manage/ManageAcceleratorProfileDetailsSection.tsx
frontend/src/pages/acceleratorProfiles/screens/manage/ManageAcceleratorProfileFooter.tsx
frontend/src/pages/acceleratorProfiles/screens/manage/types.ts
frontend/src/services/acceleratorProfileService.ts

Towards [RHOAIENG-14746](https://issues.redhat.com/browse/RHOAIENG-14746)
Updates the create/edit dialog for Accelerator Profiles to use the common `K8sNameDescriptionField` component in order to meet current UX guidelines.
- Navigate to Settings -> Accelerator profiles
- Select `Create accelerator profile`
- Enter the name for the new profile.
- View the resource name via the `Edit resource name` link.
- Change the resource name
- Save the profile.
- Verify the profile is created with the correct Display name, Resource Name, and Description.
- Navigate to Settings -> Accelerator profiles
- Select the kebab for an existing profile and choose `Edit`
- Update the Name field
- Update the Description field
- Notice the resource name is not editable
- Save the profile.
- Verify the profile is …

Update 'Resource name' fields to meet UX guidelines: Accelerator Profiles

---

backend/src/types.ts
backend/src/utils/notebookUtils.ts
frontend/src/__tests__/cypress/cypress/pages/notebookServer.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/applications/notebookServer.cy.ts
frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
frontend/src/types.ts

https://issues.redhat.com/browse/RHOAIENG-15330
update logic for submitting of a juypyter notebook
try to submit a jupyter notebook with accelerator profile and make sure resulting notebook resource gets the accelerator details added 
added test

Fix types in accelerator spawner submit

---

frontend/src/api/trustyai/rawTypes.ts
frontend/src/concepts/trustyai/utils.ts

https://issues.redhat.com/browse/RHOAIENG-15008
Fixes an incorrect type of required `requestName` and defaults to a generated one if it's missing.
* Create a Trusty Service against a DB (using the Mariadb steps)
* Create a Trusty metric via the CLI with the specific fail points (see [RHOAIENG-15008](https://issues.redhat.com//browse/RHOAIENG-15008) ticket for details)
* UI now renders it with a generated name
None, bad type -- everything should be working as intended.

Fix some trusty issues

---

frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTable.tsx
frontend/src/pages/connectionTypes/manage/advanced/DropdownAdvancedPropertiesForm.tsx
frontend/src/pages/connectionTypes/manage/advanced/__tests__/DropdownAdvancedPropertiesForm.spec.tsx

Fixes validation with connection type dropdown items. Labels are not required and therefore empty labels should not cause the form to become invalid.
Fixes adding fields to sections.
-  enable the connection type feature flag
- create a new connection type
- add a section
- click the add field button for the section
- select the field type as drop down
- add a name and env var
- add an item and supply value `v1`
- add another item and supply value `v2`
- Ensure the modal can be saved
- save the modal
- observe the item is correctly added to the section
- try adding another field to the same or another section
added test case

fix adding dropdown fields to section

---

frontend/src/pages/connectionTypes/manage/DataFieldPropertiesForm.tsx

Add helper text to default values to guide the user to not store sensitive information in default values.
- enable the connection types feature flag
- create a connection type
- add a field
- observe the helper text below the default value
N/A

add helper text for default value sensitive information

---

frontend/src/__mocks__/mockPVCK8sResource.ts
frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/clusterStorage.cy.ts
frontend/src/components/ValueUnitField.tsx
frontend/src/pages/projects/components/PVSizeField.tsx
frontend/src/pages/projects/screens/detail/storage/BaseStorageModal.tsx
frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx
frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx

JIRA: [RHOAIENG-526](https://issues.redhat.com/browse/RHOAIENG-526)
When editing storage, if it's not "Bound", we disable the size field and show a helper text to explain why.
1. Create a new cluster storage, and don't connect it to any workbench
2. Try to edit the storage, check whether the size field is disabled and the helper text is shown
3. Try to connect it to a workbench, and start/restart that workbench
4. Wait for a few second (it may take a few second to make the PVC on the cluster bound with a PV), and try to edit the cluster storage again
5. Now you can see it's enabled and you can increase the size now
Added a cypress test to verify you cannot edit the storage size field when it's not bound. …

Disable size field and show helper text when editing an unbound storage

---

frontend/src/concepts/connectionTypes/fields/DataFormFieldGroup.tsx

As part of the UX review we identified a missing update to the field details popover.
Added environment variable details to popover:
- enable connection types feature flag
- go to Settings -> Connection types
- preview the s3 connection type
- click the `?` for a field
- observe the popover details includes env var
N/A

add env var to field details popover

---

frontend/src/components/DashboardDescriptionListGroup.tsx
frontend/src/concepts/roleBinding/RoleBindingPermissionsTableRow.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelDetailsView.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsTableColumns.ts
frontend/src/pages/modelRegistry/screens/RegisteredModels/RegisteredModelsTableColumns.ts

Closes: [RHOAIENG-13049](https://issues.redhat.com/browse/RHOAIENG-13049)
Tooltip to popover updates Updates from tooltip to popover made in various areas. Also added popovers to a few areas
Tested locally on these pages:
- Model registry settings - default group tooltip changed to popover
- Model list page - owner tooltip changed to popover
- Model details and archived model details - owner popover added
- Version list and archived version list - author popover added
Tooltip - popover
Before:
After:
Before:
After:
Popover additions:

Popover fixes/additions

---

backend/src/routes/api/modelRegistries/index.ts

closes: https://issues.redhat.com/browse/RHOAIENG-12782
give the real error message from k8s, this includes "[name] already exists"
locally, kserve cluster, creating an MR (in MR settings) that has the same name as an existing MR. Run backend and frontend separately to see the changes in this PR.
none

fix(12782): display actual error msg for failed mr creation

---

frontend/src/__tests__/cypress/cypress/tests/mocked/projects/dataConnection.cy.ts
frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTableExpandedSection.tsx
frontend/src/pages/projects/ProjectDetailsContext.tsx
frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx
frontend/src/pages/projects/screens/detail/notebooks/NotebookList.tsx
frontend/src/pages/projects/screens/detail/storage/StorageList.tsx
frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx

https://issues.redhat.com/browse/RHOAIENG-12866
Updated usages of project details context to not refresh all resources after certain actions like the one mentioned in this ticket take place (e.g. deletion of data connections).
Inspected browser network - After deleting data connections, additional API requests for other resources (e.g. fetching of notebooks) no longer occur. This can be done to manually test, or the deletion of cluster storage from the project details page.
Since there was no change in functionality, no additional tests were added for this change.

[RHOAIENG-12866] entire project context refreshed when individual resources are deleted

---

frontend/src/pages/modelRegistrySettings/ModelRegistryTableRowStatus.tsx

Closes: [RHOAIENG-15587](https://issues.redhat.com/browse/RHOAIENG-15587)
https://github.com/user-attachments/assets/8be8c8c3-89f0-48b1-8441-2589b4e3f304
https://github.com/user-attachments/assets/bf497fbe-54f2-4cd1-9f29-c775b323b272
Model registry admin settings page now shows the following:
1. Progressing status should have animated `InProgressIcon`
2. Degrading status is grey in color and has animated `InProgressIcon` 
3. Unavailable status has`ExclamationTriangleIcon` and is yellow in color.
Only icon updates(no text/status updates) - so no tests

Model registry settings table icon updates

---

backend/src/utils/constants.ts
docs/dashboard-config.md
manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
manifests/rhoai/shared/odhdashboardconfig/odhdashboardconfig.yaml

https://issues.redhat.com/browse/RHOAIENG-14748
- apply the CRD changes to your test cluster, thus removing the `disableConnectionTypes` feature flag
- if testing locally, run a local backend server with the changes
- observe the UI shows connection types enabled by default
N/A
cc @andrewballantyne @dgutride @emilys314

enable connection types by default

---

frontend/src/pages/projects/screens/spawner/connections/ConnectionsFormSection.tsx

Closes https://issues.redhat.com/browse/RHOAIENG-15584
When creating a new connection is created, it uses the connection made from `assembleConnection` which has its data inside `stringData` not `data` so check those. 
So this fixes 3 different issues oddly:
1. When creating a new connection to attach, it would not warn of duplicate env variables in the table anymore. This was because the `assembleConnection()` put the data into `stringData` not `data`
2. When saving a (new) connection, it would always add the new connection to the table, even if there was a failure. There was no success gate for adding it.
3. If you tried editing a connection you just created, it would not load the existing data you just entered, because it was in `stringData`
All of these are fixed by using the response …

Fix workbench new connection env warning / editing new connection / and save failure handling

---

frontend/src/components/DashboardDescriptionListGroup.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsHeaderActions.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionListView.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsHeaderActions.tsx

closes: https://issues.redhat.com/browse/RHOAIENG-15588
mr style updates
- the edit icon should be at the start of button for editableTextDescriptionListGroup (which is used in MR details and MR version details). this component is not used anywhere else.
- register new version on the model versions list page should be primary:
- actions button should be secondary on the model detail and versions list page:
- version detail page should have a separate button with primary styling for deploy (removed from actions menu), and the actions button should be secondary styling
none - styling changes

feat(15588): mr style updates

---

frontend/config/webpack.common.js
frontend/config/webpack.dev.js

`ForkTsCheckerWebpackPlugin` was type checking all files including cypress files. Since we omit optional dependencies, errors were found type checking cypress files. 
The fix here is to only run `ForkTsCheckerWebpackPlugin` in dev environment as previous done before the change that introduced it.
- delete your `node_modules` folders
- `npm ci --omit=optional` from the root
- build the frontend dir: `npm run build`
- should succeed without error
N/A

run ForkTsCheckerWebpackPlugin only in dev env

---

frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelCard.tsx

Closes: [RHOAIENG-13078](https://issues.redhat.com/browse/RHOAIENG-13078)
Fixes a bug where model names over 55+ characters overflow off of the deployed model card. It will now truncate at the end. It will also show a tooltip for names that are truncated.
Tested locally
2. Deploy a model via model serving with a name of 55+ characters
3. Navigate to Data Science Projects > Project
4. Scroll down to 'Serve Models' element
5. Name should be truncated now
Before:
After:

Fix name overflow on deployed model card

---

backend/src/routes/api/images/imageUtils.ts
frontend/src/__tests__/cypress/cypress/pages/notebookImageSettings.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/notebookImageSettings/notebookImageSettings.cy.ts
frontend/src/concepts/k8s/K8sNameDescriptionField/HelperTextItemVariants.tsx
frontend/src/concepts/k8s/K8sNameDescriptionField/types.ts
frontend/src/concepts/k8s/K8sNameDescriptionField/utils.ts
frontend/src/concepts/k8s/utils.ts
frontend/src/pages/BYONImages/BYONImageModal/ManageBYONImageModal.tsx

Towards [RHOAIENG-14746](https://issues.redhat.com/browse/RHOAIENG-14746)
Updates the create/edit dialog for Notebook Images to use the common `K8sNameDescriptionField` component in order to meet current UX guidelines.
- Navigate to a `Settings` -> `Notebook images`
- Select `Import new image
- Enter an image location
- Enter the name for the new notebook image
- Enter a description for the new notebook image
- View the resource name via the `Edit resource name` link.
- Change the resource name to something invalid (ie. contains a space)
- Verify the `Import` button is disabled
- Change the resource name to something valid
- Verify the `Import` button is enabled
- Save the notebook image.
- Verify the notebook is created with the correct Display name, Description, and Resource Name.
- …

Update 'Resource name' fields to meet UX guidelines: Image streams

---

backend/src/routes/api/service/mlmd/index.ts
backend/src/routes/api/service/pipelines/index.ts
frontend/src/__mocks__/mockDataSciencePipelinesApplicationK8sResource.ts
frontend/src/__tests__/cypress/cypress/fixtures/resources/yaml/dspa.yaml
frontend/src/api/models/pipelines.ts

https://issues.redhat.com/browse/RHOAIENG-15234
Reopening this PR
DataSciencePipelineApplicationModels to be bumped to v1
- Adjust the pipeline devFlags to point to main
- check whether pipeline server created successfully
-  Updated the mocks to use v1

bump DSPA version from v1alpha to v1

---

backend/src/utils/prometheusUtils.ts
docs/dev-setup.md
frontend/src/utilities/clusterUtils.ts
frontend/src/utilities/const.ts

[RHOAIENG-6352](https://issues.redhat.com/browse/RHOAIENG-6352)
Added new env variable `CONSOLE_LINK_DOMAIN` to get access to internal services for ROSA or IBM clusters.
1. Get ROSA cluster
2. add CONSOLE_LINK_DOMAIN in .env.local
3. Run the cluster
N/A

Create consoleLinkDomain ENV Var

---

frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/clusterStorage.cy.ts
frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx
frontend/src/pages/projects/screens/spawner/storage/StorageClassSelect.tsx

[RHOAIENG-13984](https://issues.redhat.com/browse/RHOAIENG-13984)
Added resource tooltip to storage class name in the table.
Description and resource name added in select dropdown
Create a storage class, and check the name, resourcename and description in storage table and create storage modal.
Added cypress test to check resource name in storage table.
@xianli123

Display the storage class metadata name in the end user UI

---

frontend/src/concepts/areas/const.ts
frontend/src/pages/modelServing/screens/global/EmptyModelServing.tsx
frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx
frontend/src/pages/modelServing/screens/projects/__tests__/utils.spec.ts
frontend/src/pages/modelServing/screens/projects/useIsNIMAvailable.ts
frontend/src/pages/modelServing/screens/projects/utils.ts
frontend/src/pages/modelServing/screens/types.ts
frontend/src/pages/modelServing/useServingPlatformStatuses.ts
frontend/src/pages/projects/screens/detail/overview/serverModels/PlatformSelectSection.tsx
frontend/src/pages/projects/screens/detail/overview/serverModels/ServeModelsSection.tsx
frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelsSection.tsx

(I'll have to create an issue -- don't think we have it yet)
Fixes the issue where if KServe is the only thing installed, NIM doesn't appear as an option and it auto-selects KServe.
Not having MM installed then installing the NIM tile & then creating a new project
Test fixes -- no new tests

Fix NIM selection issue

---

frontend/src/__mocks__/mockModelRegistryService.ts
frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelRegistry.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersions.cy.ts
frontend/src/components/PopoverListContent.tsx
frontend/src/components/WhosMyAdministrator.tsx
frontend/src/k8sTypes.ts
frontend/src/pages/modelRegistry/screens/ModelRegistrySelector.tsx
frontend/src/pages/modelRegistry/screens/utils.ts

Closes: [RHOAIENG-15171](https://issues.redhat.com/browse/RHOAIENG-15171)
This PR aims to update the context bar selector to include help content and show the API endpoint URL of the selected model registry.
1. Go to Model registry
2. Click on `View details` button to see the API endpoint URL 
3. Click on `Need another registry` button to see help content.

Update context selector bar and show API endpoint URL

---

frontend/src/components/SimpleSelect.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceFrameworkSection.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx

JIRA: https://issues.redhat.com/browse/RHOAIENG-15526
Update the `SimpleSelect` component, make it not depend on the whole options array (which is not stable). Instead, make it only depend on the first option key. Added a prop to the option named `optionKey` to adapt to some special cases. Here is the reason why we need the `optionKey`:
Normally, `key` in the `SelectOption` is used to differentiate the options and will be triggered an auto-update if there is only one option in the Select component, but there is a special use case in the Model Serving area. When deploying a KServe model, user needs to choose a template, and the options for the `Model format` will be changed by the choice of the template. However, 2 different templates could have the same one option (For example, template A …

Make SimpleSelect one-option hook triggered on key instead of the options

---

frontend/src/pages/distributedWorkloads/global/projectMetrics/GlobalDistributedWorkloadsProjectMetricsTab.tsx
frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/DWSectionCard.tsx

Closes: [RHOAIENG-12280](https://issues.redhat.com/browse/RHOAIENG-12280)
Changes the tooltip for requested resources to a popover
Tested locally using Cypress
Navigate to Distributed workload metrics, and click the icon next to Requested resources
No new tests added 
Before:
After:

Distributed workloads popover fix

---

frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/TopResourceConsumingWorkloads.tsx

Closes: [RHOAIENG-14197](https://issues.redhat.com/browse/RHOAIENG-14197)
This fixes the clipping that's happening on the donut graphs on distributed workload metrics. The tooltips are now constrained to the graph area, and moved over a bit to make space for text. 
Tested locally using the cypress file `globalDistributedWorkloads.cy.ts` 
Instructions for creating a workload on your cluster can be found [here](https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/2.13/html/working_with_distributed_workloads/configuring-distributed-workloads_distributed-workloads#configuring-the-distributed-workloads-components_distributed-workloads).
Testing: Navigate to Distribute Workload Metrics. Hover over the donut graph under top resource-consuming distributed workloads. Tooltip …

Fix tooltip clipping on distributed workloads

---

frontend/src/__tests__/cypress/cypress/tests/mocked/projects/connections.cy.ts
frontend/src/concepts/connectionTypes/fields/ConnectionTypeFormFields.tsx
frontend/src/concepts/connectionTypes/fields/DataFormFieldGroup.tsx
frontend/src/concepts/connectionTypes/fields/SectionFormField.tsx
frontend/src/concepts/connectionTypes/fields/TextFormField.tsx
frontend/src/concepts/connectionTypes/fields/__tests__/ConnectionTypeFormFields.spec.tsx

Adds `field <env var>` `data-testid` to field control elements.
Replaces generated field IDs with `field-<env var>` values to ensure predicable IDs can be used with bitwarden.
Add `data-testid` to sections.
Web inspector
Updated unit tests.

add data-testid to connection form fields

---

frontend/src/__mocks__/mlmd/mockGetContextType.ts
frontend/src/__mocks__/mlmd/mockGetContextsByExecution.ts
frontend/src/__mocks__/mlmd/mockGetEventsByArtifactIDs.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/artifacts.ts
frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/artifacts.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/mlmdUtils.ts
frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetEventByArtifactId.spec.ts
frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetMlmdContextByExecution.spec.ts
frontend/src/concepts/pipelines/apiHooks/mlmd/useGetEventByArtifactId.ts
frontend/src/concepts/pipelines/apiHooks/mlmd/useGetMlmdContextByExecution.ts
frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/ArtifactOverviewDetails.tsx
frontend/src/pages/pipelines/global/experiments/executions/details/ExecutionDetailsReferenceSection.tsx
frontend/src/pages/pipelines/global/experiments/executions/utils.ts

https://issues.redhat.com/browse/RHOAIENG-14415
added the execution reference in the artifact detail page that it came from and if it was cached then show the root execution
1. Run a pipeline which contains artifacts
2. Go to Artifact Page-> click on the artifactName
3. check if the Reference section is present 
4. Check if the execution link redirects to execution page
5. Check execution link is a root execution link if its cached
Added cypress test cases
cc @yannnz

Execution reference on the artifact view what execution produced the artifacts

---

frontend/package-lock.json
frontend/package.json
frontend/src/concepts/topology/PipelineDefaultTaskGroup.tsx

https://issues.redhat.com/browse/RHOAIENG-14822
Updated the DefaultTaskGroup to use BanIcon
- Run a pipeline with cancelled task
- Check whether the ExclamationTriangleIcon is changed to BanIcon for cancelled task
N/A

Update DefaultTaskGroup custom icon to use BanIcon

---

frontend/src/pages/connectionTypes/manage/ManageConnectionTypeFieldsTable.tsx

https://issues.redhat.com/browse/RHOAIENG-14757
Before:
After:
1. Go to Connection Types -> "Create connection type"
2. Add rows to fields table by adding section heading(s) or field(s).
3. Resize window to smaller viewport and verify that table headers wrap instead of truncate. 
N/A, no changes to functionality. 

[RHOAIENG-14757]: Implement wrapped column header styling in ConnectionTypes field table

---

frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunTable.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineDeleteRuns.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineRuns.cy.ts
frontend/src/concepts/pipelines/content/tables/__tests__/usePipelineFilter.spec.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTable.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTableToolbar.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx
frontend/src/concepts/pipelines/content/tables/usePipelineFilter.ts
frontend/src/pages/pipelines/global/experiments/compareRuns/ManageRunsPage.tsx
frontend/src/pages/pipelines/global/experiments/compareRuns/ManageRunsTable.tsx
frontend/src/pages/pipelines/global/runs/GlobalPipelineRunsTabs.tsx

JIRA: [RHOAIENG-16026](https://issues.redhat.com/browse/RHOAIENG-16026)
Fix issues as described in the JIRA.
Added a hook named `usePipelineFilterSearchParams` to use the search params as the only source of truth for the pipeline filters on the pipeline runs table.
1. When loading with search params in the URL, it will automatically find the valid filters and apply it
2. When switching between the tabs, it will unmount and mount the tabs in case the search params change on one tab affects another
3. The tab will remember it's last search params when switching between tabs, so users won't lose track of the filters when they change tabs in the pipeline runs table. If you navigate to another page and click back to the page, all the filters will be reset. (However, if you use the `Back` …

Fix search param issues on pipeline runs table

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionDetails.cy.ts
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx

https://issues.redhat.com/browse/RHOAIENG-15562
Reverting the changes that were made last sprint to accomadate a backend change for patching those 2 fields. It was taking care of by the backend team now and this workaround is not necessary anymore. 
Run the K-serve cluster and verify in modelregistry-sample that you can edit those fields, and save and no error appears. 
No test impact

Reverted the workaround for patching MR artifacts

---

frontend/src/pages/modelServing/screens/projects/ModelServingPlatformSelectButton.tsx

Closes: [RHOAIENG-15592](https://issues.redhat.com/browse/RHOAIENG-15592)
This PR aims to Improve loading state while selecting/deselecting a model serving platform.
Before:
https://github.com/user-attachments/assets/550d4c70-91b2-4040-b5fc-144897fcf9b9
After:
https://github.com/user-attachments/assets/5d2819f8-64e6-4d04-9d18-dff5b1f91ba7
- Go to Model Serving inside a Project
- Select a type / Deselect a type  
- Observe that loading state does not stop until the view changes to show the new platform.
- Also check this behaviour in project details page Overview tab as well.
NA, just updated the loading state

Improve loading state while selecting/deselecting a model serving platform

---

frontend/src/components/InlineTruncatedClipboardCopy.tsx
frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTokenDisplay.tsx

Closes: [RHOAIENG-11861](https://issues.redhat.com/browse/RHOAIENG-11861)
Updated token secrets to have middle truncation.
Due to PatternFly not having a true fix for this yet, I’m using our InlineTruncatedClipoardCopy.tsx work around for this fix. A few modifications added to that file to allow for middle truncation. 
Tested locally. 
- Create a model mesh server with a model that requires a token
- View the Token secret in the Models and model servers table 
No new tests added 
Before:
After:

Change token secret to have middle truncation

---

frontend/src/app/__tests__/useDevFeatureFlags.spec.ts
frontend/src/app/useDevFeatureFlags.ts

https://issues.redhat.com/browse/RHOAIENG-16107
cc @manosnoam @andrewballantyne 
Adds the ability to enable and disable all feature flags using `?devFeatureFlags=true|false`.
The enabled state of a feature flag is still managed as individual flags. This change only adds a new interpretation of the query param.
A value of `true` will enable all features => set all `disableFeatureName=false`
A value of `false` will disable all features => set all `disableFeatureName=true`
- Modify the app url to include `?devFeatureFlags=true` and observe that all features are enabled.
- Modify the app url to include `?devFeatureFlags=false` and observe that all features are disabled.
Added unit tests. …

support devFeatureFlags=true/false to quickly toggle all feature flags

---

frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesTable.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelinesTopology.cy.ts
frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetailsActions.tsx
frontend/src/concepts/pipelines/content/tables/columns.ts
frontend/src/concepts/pipelines/content/tables/pipelineVersion/PipelineVersionTableRow.tsx
frontend/src/routes/pipelines/runs.ts

[RHOAIENG-15520](https://issues.redhat.com/browse/RHOAIENG-15520)
https://github.com/user-attachments/assets/f741ae80-454b-4ce1-87bb-835f24834c2e
Added View runs in Pipeline version table and removed from kebab action. Also clicking on View schedule will redirect to runs page with pipeline version filtered.
1. Navigate to pipeline page.
2. Expand pipeline and click on View runs to navigate on Runs page, with filtered pipeline version.
3. Also check the View schedule from Kebab action.
Added cypress tests to validate the navigation working with correct routes.
@yannnz

Update global pipelines page and link it to the global pipeline runs page

---

frontend/src/__tests__/cypress/cypress/support/commands/application.ts

https://issues.redhat.com/browse/RHOAIENG-16164
- Pass query parameters (e.g devFeatureFlags) if the relative url is '/'.
- Login should override the user/password values (instead of append).
All Cypress E2E tests were run using Jenkins on a real cluster (dashboard-e2e):
This PR enables us to run E2E on ODH Dashboard URL that includes `devFeatureFlags` in the query parameters.
To use, update your ODH_DASHBOARD_URL with the desired devFeatureFlags, in the Cypress variables file (`frontend/src/__tests__/cypress/test-variables.yml`), for example:
`ODH_DASHBOARD_URL: https://odh-dashboard-opendatahub.apps.your-server.domain.com?devFeatureFlags=true`
- [ x] The developer has manually tested the changes and verified that the changes work
- [ x] Testing …

Enable Cypress E2E tests login to Dashboard URL with devFeatureFlags

---

frontend/src/concepts/k8s/NameDescriptionField.tsx
frontend/src/concepts/pipelines/content/import/PipelineImportBase.tsx

https://issues.redhat.com/browse/RHOAIENG-14617
The name and description for the `import pipeline/ pipeline version modal` now has a max limit of 255
the submit button is disbaled if the name is duplicated
1. Create a pipeline using `import pipeline modal` with name larger character set
2. Verify for the helperText 
3. Verify that the name gets trim after 255 character is achieved
4. Verify that when duplicated name is typed the `submit button` is disabled with error helperText
N/A

support better handling of name and description in import pipeline modal

---

frontend/src/pages/modelRegistrySettings/ModelRegistryTableRowStatus.tsx

Part of [RHOAIENG-15587](https://issues.redhat.com/browse/RHOAIENG-15587)
The Degrading status wasn't visible at first, found during QA verification of [RHOAIENG-15587](https://issues.redhat.com/browse/RHOAIENG-15587)
The `Degrading` state usually appears for a very short period while deleting resources related to a specific MR. There is high possibility of not seeing this state unless you have issues during deletion. To simulate this state, add finalizers to any MR resource using OpenShift Console and try deleting the same MR via Dashboard, you should see the Degrading status. 
Tests already covered.

Make MR Degrading status more prominent

---

frontend/src/pages/notebookController/screens/server/NotebookServerDetails.tsx

Per latest comment in https://issues.redhat.com/browse/RHOAIENG-291 cc @antowaddle 
Before:
After:
1. Applications -> Enabled
2. Click "Launch Application".
3. Start a notebook server.
4. When notebook server is created, go to Notebook server control panel -> Notebook server details.
5. Verify units are correct.
N/A, tests covered in #3338 

[RHOAIENG-291]: Update Mi/Gi Instance in NotebookServerDetails

---

frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeDetails.tsx
frontend/src/pages/modelServing/screens/projects/utils.ts

Closes https://issues.redhat.com/browse/RHOAIENG-384
The initial data retrieve on the modal would skip 0 and default to 1 because it was a falsey check and not a nullish check.
I also saw on the model row details it would show "Unknown" for 0, so i did the same fix there.
1. Edit an already deployed model (kserve and/or modelmesh)
2. Set the replicas to 0 ("Number of model server replicas to deploy" field)
3. Save
4. The model row details should show "Model server replicas 0" instead of "Model server replicas Unknown"
5. Edit the model again
6. The "Number of model server replicas to deploy" field should display 0 instead of 1
Very minor change so no tests updated

Fix 0 model replicas display text

---

frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectDetails.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectList.cy.ts
frontend/src/components/OdhAppCard.tsx
frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
frontend/src/pages/projects/screens/detail/overview/trainModels/TrainModelsSection.tsx
frontend/src/pages/projects/screens/detail/storage/ClusterStorageModal.tsx
frontend/src/pages/projects/screens/detail/storage/StorageTable.tsx
frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx
frontend/src/pages/projects/screens/projects/LaunchJupyterButton.tsx
frontend/src/pages/projects/screens/projects/ProjectListView.tsx
frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx

https://issues.redhat.com/browse/RHOAIENG-15252
hides workbench related things when the area is not enabled
disable workbenches and check that everything from jira is hidden
added tests to areas project list and project details

handle workbench not enabled

---

frontend/src/__mocks__/mockInferenceServiceK8sResource.ts
frontend/src/pages/modelServing/screens/global/InferenceServiceStatus.tsx
frontend/src/pages/modelServing/screens/global/__tests__/utils.spec.ts
frontend/src/pages/modelServing/screens/global/useRouteForInferenceService.ts
frontend/src/pages/modelServing/screens/global/utils.ts
frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelsGallery.tsx

Closes https://issues.redhat.com/browse/RHOAIENG-3409
Makes the status a spinner after editing a model, popover message says "Redeploying".
Basically the status functions will prioritize looking at the target state, since that is more indicative of what is going on. 
I'm not 100% on what the correct message is to display. But the special return case could be removed and then it would default to the state of the target i.e. "Loading". 
1. Deploy a model
2. Edit the model and change something (most things will reload it)
3. The status should change to loading (the polling may be slow to update it)
Jest unit tests could be added to the utils functions, but there aren't any so i didn't add any.
@vconzola  …

Add model redeploying status

---

frontend/src/api/k8s/pvcs.ts
frontend/src/concepts/k8s/K8sNameDescriptionField/K8sNameDescriptionField.tsx
frontend/src/concepts/k8s/K8sNameDescriptionField/types.ts
frontend/src/concepts/k8s/K8sNameDescriptionField/utils.ts
frontend/src/pages/projects/screens/detail/storage/BaseStorageModal.tsx
frontend/src/pages/projects/screens/detail/storage/ClusterStorageModal.tsx
frontend/src/pages/projects/screens/detail/storage/utils.ts
frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx
frontend/src/pages/projects/screens/spawner/storage/WorkbenchStorageModal.tsx
frontend/src/pages/projects/screens/spawner/storage/__tests__/utils.spec.ts
frontend/src/pages/projects/screens/spawner/storage/utils.ts
frontend/src/pages/projects/types.ts
frontend/src/utilities/useGenericObjectState.ts

Closes [RHOAIENG-14746](https://issues.redhat.com/browse/RHOAIENG-14746)
Updates create/edit cluster storage modals to use `K8sNameDescriptionField` component in order to meet current UX guidelines.
- Navigate to a project and go to the Cluster storage tab
- Select `Add cluster storage`
- Enter a name
- Verify the `Add storage` button is enabled
- View the resource name via the `Edit resource name` link.
- Change the resource name to something invalid (ie. contains a space)
- Verify the `Add storage` button is disabled
- Change the resource name to something valid
- Enter a description
- Verify the `Add storage` button is enabled
- Save the storage.
- Verify the cluster storage is created with the correct Display name and Resource Name and Description.
- Navigate to a project and go to …

Update 'Resource name' fields to meet UX guidelines: Cluster storage

---

frontend/src/__tests__/cypress/cypress.config.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/application.cy.ts

https://issues.redhat.com/browse/RHOAIENG-16485 
Add a retry  mechanism to the e2e Cypress tests.
I've forced the failure of the application.cy.ts test here 9a1c6762723ce4564cdf81746b2589a35dfe43af 
Then I've ran the cypress job (cypress/job/cypress-tests/59)
In the report, 3 attempts are shown:
Then I've fixed the test here  8e55ff23222efa539c2d43f8df9b2eed57b091d6 
And ran the cypress job (cypress/job/cypress-tests/60)
And the test was up and running fine again
It's an "enhancement" 

Cypress: Retry mechanism for e2e tests

---

frontend/src/pages/modelServing/__tests__/utils.spec.ts
frontend/src/pages/modelServing/screens/projects/utils.ts
frontend/src/pages/modelServing/utils.ts

Closes https://issues.redhat.com/browse/RHOAIENG-15479
Fix an issue in which users without cluster admin roles would dry run rolebindings referencing a role that's not there.
Also, avoiding calling setUpTokenAuth twice in kserve.
1. Impersonate a regular user
2. Create a new project
3. Go to model serving section
4. Deploy a new kserve model
5. Select auth tokens
6. See there's an issue
These changes will fix that scenario

Fix dryRun issue with permissionless user

---

backend/src/types.ts
backend/src/utils/constants.ts
docs/dashboard-config.md
frontend/src/__mocks__/mockDashboardConfig.ts
frontend/src/concepts/areas/const.ts
frontend/src/concepts/areas/types.ts
frontend/src/k8sTypes.ts

https://issues.redhat.com/browse/RHOAIENG-16488
Adds `disableKServeRaw` feature flag. defaulted to true for now

Add kserve raw feature flag

---

frontend/src/__tests__/cypress/cypress/tests/mocked/projects/workbench.cy.ts
frontend/src/api/k8s/configMaps.ts
frontend/src/api/k8s/secrets.ts
frontend/src/pages/projects/notebook/DeleteNotebookModal.tsx

https://issues.redhat.com/browse/RHOAIENG-16192
fixes https://github.com/opendatahub-io/odh-dashboard/issues/3521 (we will follow up with more flexibility in the future)
This PR addresses an issue where deleting a notebook would unintentionally delete ConfigMaps and Secrets that might be shared between multiple workbenches. The fix introduces prefix-based filtering to ensure only dashboard-generated resources are deleted.
- Modified deletion logic to only delete resources that start with these prefixes
- Updated tests to verify that custom resources are preserved
updated delete test
1. create test resources
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
name: shared-test-configmap
labels:
data:
STAGE: test
kind: Secret
apiVersion: v1
metadata:
name: …
```

fix(frontend): prevent unintended deletion of shared ConfigMaps and Secrets during notebook deletion

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx

https://issues.redhat.com/browse/RHOAIENG-16540
Go to Data Science projects and find a project that is configure with model mesh
Create a new model server (for example openvino) e.i. named "newserver"
in a modelmesh server Create a new model deployment under it e.i. name "newmodel" and save
Notice that "newmodel" is now appearing under "newserver" See screenshots below on the before and after
on MR cluster 
BEFORE 
AFTER with same name
AFTER with different names 
Fixed the tests 

Model mesh deployment doesn't appear under server after creation

---

.github/workflows/authorized-tag-creators.txt
.github/workflows/create-tag-release.yml

Github action to create Quay tags for ODH release

Add GitHub action to create Quay tags for release

---

frontend/src/app/ThemeContext.tsx

Closes [RHOAIENG-16682](https://issues.redhat.com/browse/RHOAIENG-16682)
Use local storage to remember users' theme preference
Set the theme to dark
Refresh the UI
Verify the theme remains dark
Uses simple utility no additional tests necessary

Use local storage to remember user's theme preference

---

frontend/src/concepts/pipelines/content/createRun/contentSections/TriggerTypeField.tsx
frontend/src/concepts/pipelines/content/createRun/contentSections/__tests__/utils.spec.ts
frontend/src/concepts/pipelines/content/createRun/contentSections/utils.ts
frontend/src/concepts/pipelines/content/createRun/submitUtils.ts
frontend/src/utilities/__tests__/string.spec.ts
frontend/src/utilities/__tests__/time.spec.ts
frontend/src/utilities/string.ts
frontend/src/utilities/time.ts

[RHOAIENG-14431](https://issues.redhat.com/browse/RHOAIENG-14431)
Refactored the logic of Run every numeric and text part. Also removed dead code previously used. 
https://github.com/user-attachments/assets/4b7c5aea-0e80-4c1c-9c01-ac17a86612c3
1. Open create schedule pipeline page.
2. Try to enter very long input in Run every numeric field. It should work without breaking.
Added unit tests for utility function.

'Run every' - 'Select' dropdown greys out and cannot be selected

---

manifests/core-bases/base/cluster-role.yaml

Resolves critical bug [RHOAIENG-15773](https://issues.redhat.com/browse/RHOAIENG-15773).
Due to a change in the Model Registry operator ([PR here](https://github.com/opendatahub-io/model-registry-operator/pull/160/files#diff-ef231245a2fe05b23d3b1a452ddfacc56a03cd441b5bd2b7af46061466043eed), [issue here](https://issues.redhat.com/browse/RHOAIENG-15574)), the `registry-user-${registryname}` role that is generated for each model registry now has an additional permission: get endpoints.
The service account used by the dashboard to create rolebindings for managing model registry permissions does not have permission to get endpoints today. Because of this change, the Manage Permissions page's requests to create new rolebindings using this role are failing in the dashboard. This is due to a …

[RHOAIENG-15773] Fix MR permissions management error (give dashboard ServiceAccount permission to get endpoints)

---

backend/src/types.ts
backend/src/utils/constants.ts
docs/dashboard-config.md
frontend/src/__mocks__/mockDashboardConfig.ts
frontend/src/__mocks__/mockHardwareProfile.ts
frontend/src/api/index.ts
frontend/src/api/k8s/__tests__/hardwareProfiles.spec.ts
frontend/src/api/k8s/hardwareProfiles.ts
frontend/src/api/models/odh.ts
frontend/src/app/AppRoutes.tsx
frontend/src/concepts/areas/const.ts
frontend/src/concepts/areas/types.ts
frontend/src/k8sTypes.ts
frontend/src/pages/hardwareProfiles/HardwareProfiles.tsx
frontend/src/pages/hardwareProfiles/HardwareProfilesRoutes.tsx
frontend/src/pages/hardwareProfiles/__tests__/useHardwareProfile.spec.ts
frontend/src/pages/hardwareProfiles/__tests__/useHardwareProfiles.spec.ts
frontend/src/pages/hardwareProfiles/useHardwareProfile.ts
frontend/src/pages/hardwareProfiles/useHardwareProfiles.ts
frontend/src/types.ts
frontend/src/utilities/NavData.tsx
manifests/common/crd/hardwareprofiles.opendatahub.io.crd.yaml
manifests/common/crd/kustomization.yaml
manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
manifests/core-bases/base/fetch-hardwares.rbac.yaml
manifests/core-bases/base/kustomization.yaml

https://issues.redhat.com/browse/RHOAIENG-16253
- created disableHardwareProfiles feature flag
- created side navigation settings called "Hardware profiles"
- Hide navigation behind new feature flag
- created new HardwareProfile CRD (spec)
- created useHardwareProfile hook
- will need to fetch new crd
- create empty state for side navigation
- Update RBAC for authenticated users
- oc apply the manifest file
- check for the hardware profile when you are a clusteradmin
- check in the openshift console , whether hardware profile is created in custom resource definition
- console log the `createHardwareProfile` , `deleteHardwareProfile`, `updateHardwareProfile` to check whether hardware profile instance is created, updated or deleted
- check if the `useHardwareProfile`  and …

Hardware profile empty state

---

backend/src/routes/api/status/adminAllowedUsers.ts
backend/src/types.ts
backend/src/utils/adminUtils.ts

JIRA: https://issues.redhat.com/browse/RHOAIENG-16434
Use `ResourceAccessReview` API as described [here](https://docs.openshift.com/container-platform/4.17/rest_api/authorization_apis/resourceaccessreview-authorization-openshift-io-v1.html) to fetch the cluster admin users and groups instead of arbitrarily push `cluster-admins` group to the list and fetch it. This could also avoid the error mentioned in the JIRA where we are fetching a non-exist user group.
1. Create some user groups
2. Bind them to the `cluster-admin` role
3. Add some users to those groups separately
4. Go to the Jupyter notebook controller admin panel, make sure those users are there and shown as `Admin`
N/A

Fetch correct cluster admin list for the notebook controller admin panel

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionDetails.cy.ts
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx

closes: https://issues.redhat.com/browse/RHOAIENG-15128
add loading spinner and error for the loading of modelArtifacts on mr version details page.
show spinner on full page as the loading doesn't take long and determines some of the page format
show error in the model location area
you can see the spinner briefly if you refresh the page. otherwise i was hard coding an error value to see that.
had to add an intercept to make sure the right side of mr version detail loads after selecting a different version #

feat(15128): load and error state for modelArtifact on mr version detail

---

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineRuns.cy.ts

https://issues.redhat.com/browse/RHOAIENG-16871
a flaky test has been occurring in pipeline recurring runs table
```
Pipeline runs - Schedules - with data - can disable a recurring run: timed out waiting `5000ms` for the 1st request to the route: `disableRecurringRun`. No request ever occurred.
```
There is nothing wrong with the test but on occasion it will timeout waiting for the post call. I have increased that timeout.
tests pass
updates test timeout

Increase timeout for disabling recurring run in Cypress test

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts
frontend/src/api/k8s/__tests__/inferenceServices.spec.ts
frontend/src/api/k8s/inferenceServices.ts
frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
frontend/src/pages/modelServing/screens/projects/NIMServiceModal/NIMModelDeploymentNameSection.tsx

Closing issue 2 from https://issues.redhat.com/browse/RHOAIENG-16540
When selecting multiple models on a multi model server it was throwing and error when trying to deploy a second model.  Found on kserve cluster.
Before 
After 
2 Scenarios
1. Any cluster - In Data Science projects go to models, choose Multi-model serving platform. Add a model server.Deploy a model. Try to deploy a 2nd mode. Make sure that no error appears. 
2. Cluster that has NIM enabled- we need to make sure that the InferenceService gets the right name when deploying a kserve model or a NIM model.
Fixed the failing test

Fixing multiple models deploy 

---

backend/src/types.ts
backend/src/utils/constants.ts
docs/dashboard-config.md
frontend/src/__mocks__/mockDashboardConfig.ts
frontend/src/concepts/areas/const.ts
frontend/src/concepts/areas/types.ts
frontend/src/k8sTypes.ts
frontend/src/pages/modelRegistrySettings/CreateMRSecureDBSection.tsx
frontend/src/pages/modelRegistrySettings/CreateModal.tsx
frontend/src/pages/modelRegistrySettings/PemFileUpload.tsx
manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
manifests/rhoai/shared/odhdashboardconfig/odhdashboardconfig.yaml

closes https://issues.redhat.com/browse/RHOAIENG-15898
implement feature flag for securedb, which when enabled will show newly implemented "Add CA certificate to secure database connection" at the bottom of the create mr modal. checking that will give 4 ways that a certificate can be added.
this looks different than the mocks as "Note" was added to the file upload alert and we've since upgraded to pf6. @yih-wang 
before checking
after check
clicking existing
the searchable drop menu
the file upload
tested locally by triggering the new flag and checking the box at the bottom of the create mr form. check that form can be submitted if one of the first two radios are selected. if one of the last two are selected, you'll need to supply info before you can submit the form.
no real data yet, so …

feat(15898): create MR secure db feature flag, skeleton for form elements

---

frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDeployModal.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionDeploy.cy.ts

fixes issue with a flakey deploy model test
When switching projects in the deploy version modal of the UI, I notice there are new network calls and some changes on the UI. This may have caused the test to fail if the option to select didn't exist yet.
I added a `wait` on the network call for getting projects before attempting to select.
I also changed increased the `timeout` of finding the project name to select to 5 seconds.
ran tests locally several times, passed
hopefully won't intermittently fail anymore

fix(test): add wait in deploy model test

---

frontend/src/pages/modelRegistrySettings/CreateModal.tsx

accidentally left a boolean flipped after debugging, undoing that.
secureDB section in create MR modal should not exist without the feature flag.
none

fix(secureDb): undo debugging boolean flip

---

frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionRegisteredDeploymentsView.tsx
frontend/src/pages/modelServing/screens/global/data.ts

https://issues.redhat.com/browse/RHOAIENG-16078
I added the edit/Delete Kebab to the list of Version deployments
https://github.com/user-attachments/assets/bf5ca36d-c999-4b00-ae57-2acf9dfbc4f7
On K serve cluster, go to a model version Deployments tab and verify that we have the edit/Delete Kebab on each deployment
No test Impact

Support 'undeploy' in model registry (don't hide the Edit/Delete kebab when rendering deployments table in MR)

---

frontend/src/__tests__/cypress/cypress/tests/mocked/home/homeAIFlows.cy.ts
frontend/src/pages/home/aiFlows/DeployAndMonitorGallery.tsx
frontend/src/pages/home/aiFlows/useAIFlows.tsx

[RHOAIENG-16021](https://issues.redhat.com/browse/RHOAIENG-16021)
In the home page under "Work with AI/ML models"(based on comments below) ( previously "Train, serve, monitor, and manage AI/ML models") "Manage Models"( Previously Deploy and monitor models) will be displayed based on the 4 cases below:
Case 1 : customer has model registry and model serving both enabled - display all 3 cards . 
Case 2 : customer only has model registry enabled - display only Model registry card. 
Case 3 : customer only has model serving enabled - display Model servers and Deploying models cards only. 
Case 4 : Customer not enabled both model registry or model serving - don't display Manage Models all together. 
NOTE: The icons in the screenshot are not up to date, and don't reflect the "Work with AI/ML …

Home Page MR card in the "Manage models" section

---

backend/src/utils/resourceUtils.ts
manifests/core-bases/base/cluster-role.yaml

https://issues.redhat.com/browse/RHOAIENG-16822
Reduces permissions for the SA around Namespaces. Removed deprecated/unused code to assist with the permissions reduction.
We only PATCH namespaces for model serving today.
On a cluster, should be fine to just deploy it with the DSC DevFlag as the code that is removed was never called.
None

Reduce Namespace Permissions

---

backend/src/routes/api/validate-isv/index.ts
frontend/src/pages/exploreApplication/GetStartedPanel.tsx

Closes: [RHOAIENG-16251](https://issues.redhat.com/browse/RHOAIENG-16251)
Quick update for the ValidateISV Endpoint. Also add logic to hide the enable button if the user isn't an admin.
npm run test and locally
No changes
Admin:
Non admin:

ValidateISV Endpoint Update

---

backend/src/routes/api/integrations/nim/index.ts
backend/src/routes/api/integrations/nim/nimUtils.ts

https://issues.redhat.com/browse/NVPE-77
Added the ability to update the existing secret with the new API key.
- Tested by updating the secret. 
- Tested by removing the account and trying to update the secret.

fix: add capability to update existing secret

---

frontend/src/concepts/pipelines/content/InvalidArgoDeploymentAlert.tsx

https://issues.redhat.com/browse/RHOAIENG-16973 , fix version is 2.17.0
We want to rename the "Enabling data science pipelines 2.0" section in the RHOAI docs to "Migrating to data science pipelines 2.0" to more accurately reflect the content/procedure. 
As a workaround for the 2.16 docs, I updated the title to "Migrating to data science pipelines 2.0" but I did not change the filename or id so that these links would not break. 
When the links are updated here, I can rename the file and update the id in the doc repo.
The links will be broken until the updated docs are published, but the preview links will be available when I know which release this change is implemented in.

Update doc link

---

backend/src/routes/api/modelRegistryCertificates/index.ts
backend/src/routes/api/modelRegistryCertificates/modelRegistryCertificatesUtils.ts
backend/src/types.ts
frontend/src/concepts/modelRegistrySettings/useModelRegistryCertificateNames.ts
frontend/src/k8sTypes.ts
frontend/src/pages/modelRegistrySettings/CreateMRSecureDBSection.tsx
frontend/src/pages/modelRegistrySettings/CreateModal.tsx
frontend/src/services/modelRegistrySettingsService.ts

Closes: [RHOAIENG-15899](https://issues.redhat.com/browse/RHOAIENG-15899)
- Fetch config maps and secrets in model registry namespace and added hook for the same
- Lazy loading(Skeleton) when one clicks on the checkbox
- Added logic to disable/enable the first two options 
- If the data from the new hook has no ConfigMap with the name `odh-trusted-ca-bundle` or that ConfigMap does not include the key `ca-bundle.crt`, disable the "Use cluster-wide CA bundle" radio button and add a tooltip "No certificate is available in the cluster-wide CA bundle". 
- If the data from the new hook has no ConfigMap with the name `odh-trusted-ca-bundle` or that ConfigMap does not include the key `odh-ca-bundle.crt`, disable the "Use ${ODH_PRODUCT_NAME} CA bundle" radio button and add a tooltip "No …

Add backend route for Configmaps and secrets for MR namespace

---

frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDeployModal.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionDeploy.cy.ts

thinking a possible reason for the failure (which i've never been able to reproduce locally) is that the dropdown menu gets clicked before it closes from the first selection.
originally tried a fix is to check for it to be closed before attempting to open it - but it was getting some "dom changed" error
this PR is now separating the two "unsupported platform" tests into their own so it doesn't have to deal with whatever issue is happening when flicking between two

hopeful fix for flakey mr test

---

frontend/src/pages/storageClasses/StorageClassesTable.tsx

Closes [RHOAIENG-16679](https://issues.redhat.com/browse/RHOAIENG-16679)
Removes the extra line below the header in the Storage Classes table
- Navigate to `Settings -> Storage Classes`
- Verify there is no line between the table header and the first row
No impact, purely a visual change

Fix for extra line in storage classes table

---

frontend/src/__mocks__/mockInferenceServiceModalData.ts
frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts
frontend/src/api/k8s/__tests__/inferenceServices.spec.ts
frontend/src/api/k8s/inferenceServices.ts
frontend/src/k8sTypes.ts
frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/KServeDeploymentModeDropdown.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
frontend/src/pages/modelServing/screens/projects/utils.ts
frontend/src/pages/modelServing/screens/types.ts

Closes https://issues.redhat.com/browse/RHOAIENG-16487
Figma https://www.figma.com/design/hKimcyeu6pgAoqKH1XrqmY/Support-KServe-RawDeployment-mode?node-id=231-2365&node-type=canvas&t=KepUcCxzaanRkMU8-0
First part of adding kserve raw model deployments. This adds the deployment mode dropdown to single serving (kserve) modals. What is done is basically adding `...DeploymentMode: RawDeployment` and the corresponding labels for auth / routing. The backend model controller takes care of the rest.
- Advanced -> Serverless / old behaviour
- Standard -> KServe raw / new
Changing the deployment mode on an existing deployment is not supported so it will be disabled on edit. However the `assembleInferenceService()` does properly replace the labels and annotations. 
The deployment mode dropdown will …

Add deployment mode select for kserve raw

---

frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/clusterStorage.cy.ts
frontend/src/concepts/dashboard/DashboardPopupIconButton.tsx
frontend/src/k8sTypes.ts
frontend/src/pages/projects/components/PVSizeField.tsx
frontend/src/pages/projects/components/StorageSizeBars.tsx
frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx
frontend/src/pages/projects/screens/spawner/storage/utils.ts
frontend/src/pages/projects/utils.ts

[RHOAIENG-527](https://issues.redhat.com/browse/RHOAIENG-527)
When the storage size is updated but no pod connected, the size doesn't get updated on UI. So added a condition which will display the updated size with warning.
If the storage is connected to workbenches
If the storage is not connected to any workbench
1. Create a cluster storage with workbench connected. (size: 12Gi)
2. Disconnect the workbench from it.
3. Edit the size. (size: 13Gi)
4. You can see the updated size with warning popover.
Added cypress test to check the warning when cluster storage size is updated but no workbench is connected.
@xianli123 @kaedward

Cluster storage that was disconnected from the workbench doesn't update it's size info

---

frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts
frontend/src/__tests__/cypress/cypress/pages/workbench.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/clusterStorage.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/workbench.cy.ts
frontend/src/components/TypeaheadSelect.tsx
frontend/src/concepts/connectionTypes/ConnectionTypeForm.tsx
frontend/src/pages/modelRegistry/screens/RegisterModel/RegisteredModelSelector.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
frontend/src/pages/projects/notebook/ConnectedNotebookField.tsx
frontend/src/pages/projects/screens/detail/storage/ClusterStorageModal.tsx
frontend/src/pages/projects/screens/detail/storage/ClusterStorageTableRow.tsx
frontend/src/pages/projects/screens/detail/storage/utils.ts
frontend/src/pages/projects/screens/spawner/dataConnection/ExistingDataConnectionField.tsx
frontend/src/pages/projects/screens/spawner/storage/AddExistingStorageField.tsx
frontend/src/pages/projects/screens/spawner/storage/StorageClassSelect.tsx

JIRA: [RHOAIENG-16038](https://issues.redhat.com/browse/RHOAIENG-16038)
Add a hook in TypeaheadSelect to auto-select the only option and disable the field. This only happens when:
1. The field is required (e.g. When adding a cluster storage, the connected notebook field is not required, we cannot force to select the only workbench)
2. The field is not creatable
Verify all the components that use `TypeaheadSelect` is working as expected.
- If it's creatable, it should not be changed by this PR
- If it's not required, it should not be changed by this PR
- Otherwise, if there is only one option in the select menu list, it should be disabled and auto-select the only option
Update the cypress test in workbench …

Update typeahead select to make it auto select the only option as needed

---

frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/AuthServingRuntimeSection.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx

Closes: [RHOAIENG-10060](https://issues.redhat.com/browse/RHOAIENG-10060)
This PR aims to allow private/public route selection in KServe, when authorino is not enabled.
https://github.com/user-attachments/assets/6e39d1bd-d36b-4779-8bf5-9714fc938ea7
In KServe, now we allow private/public route selection even when the authorino is not enabled.
when the model route checkbox is checked, we will show warning alert.

Allow private/public route selection in KServe, when authorino is not enabled

---

frontend/src/pages/projects/screens/spawner/storage/StorageClassSelect.tsx

https://issues.redhat.com/browse/RHOAIENG-16609
show only the storageClass which are enabled  ( already addressed in  in this PR https://github.com/opendatahub-io/odh-dashboard/pull/3547 )
hide the storageClass dropdown when no storageClass is enabled or all of them dont have the openshift storage config annotations
1. Remove the openshift config annotations from  all storageClass in the console
2. Check if the  storageClass dropdown is hidden
N/A

fix cluster storage class dropdown

---

frontend/src/__tests__/cypress/cypress/tests/mocked/home/homeAIFlows.cy.ts
frontend/src/pages/home/aiFlows/useAIFlows.tsx

[RHOAIENG-16483](https://issues.redhat.com/browse/RHOAIENG-16483) 
This has to be tested on a cluster that has the backend components for model registry and serving disabled 

Fixed the 4 edge case for main page

---

frontend/src/__tests__/cypress/cypress/tests/mocked/projects/workbench.cy.ts
frontend/src/pages/projects/screens/spawner/storage/ClusterStorageTable.tsx

https://issues.redhat.com/browse/RHOAIENG-16797
Before
After
1. Go to Data Science Projects.
2. Select a project -> Workbenches.
3. Create workbench.
4. Scroll down to "Cluster storage" table.
5. Verify the correct units are applied.
Updated `workbench.cy.ts`. 

Apply formatMemory on Storage Size Units in Cluster Storage Table

---

frontend/src/__mocks__/mockNotebookK8sResource.ts
frontend/src/__tests__/cypress/cypress/pages/notebookServer.ts
frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/applications/notebookServer.cy.ts
frontend/src/pages/notebookController/screens/server/EnvironmentVariablesField.tsx
frontend/src/pages/notebookController/screens/server/EnvironmentVariablesRow.tsx

https://issues.redhat.com/browse/RHOAIENG-17122
When we did a change for the selects in our app to select the first item and disable itself it had a side-effect to Jupyter tile where it triggered a re-selection and emptying of the secret/configmap details. This occurred in all env var groups but it seems due to poor reference mapping, we updated the values with in-memory old data and thus only ended up applying the last set state. 
Fix was to just not allow the selecting of the same dropdown item to reset the data. But I'm fairly certain this dropdown is obsolete in the code and maybe never did anything in the first place (unimplemented logic?). We'll have to swing back and clean this up later or more likely do a refactor of this page to a new design (like Workbenches).
Fire up Jupyter …

Fix Jupyter Tile env var readback

---

CONTRIBUTING.md
README.md
docs/dev-setup.md

Onboarding doc considerations, https://issues.redhat.com/browse/RHOAIENG-17027 
This is to help new team members get an ext cluster configured with the `frontend`, to align the UI efforts with the broader infrastructure and RBAC changes that are planned for Q1. 
Local environment, validated the frontend against multiple backend clusters. 
testing methodology and [cluster list](https://spaces.redhat.com/display/RHODS/Dashboard+Shared+Clusters)
1. `oc login {uri from clusters sheet}`
2. `cd frontend && npm start:dev:ext` 
3. Validate that the get projects, create projects, and view workbenches works
No tests added due to this being primarily `markdown` and documentation updates for local development. 
Reviewing the docs for clarity, as well as potential backend/or other test-cases for local …

Adding links, and breaking down onboarding steps

---

frontend/src/app/App.scss
frontend/src/pages/notebookController/NotebookController.scss
frontend/src/pages/notebookController/screens/server/ImageTagPopover.tsx

Closes [RHOAIENG-16677](https://issues.redhat.com/browse/RHOAIENG-16677)
Removes underlines from text in resource category filter options. 
Fixes alignment of radio buttons in the Spawner page
- Navigate to `Resources` page
- Verify the category links are not underlined
- Navigate to `Data Science Projects`
- Select a project
- Select the `Workbenches` tab
- Select `Create workbench`
- Verify the alignment of the image selector radio buttons
Not impact on tests as this is purely visual

Fixes for visual issues with Resources vertical tabs and Spawner page image selectors

---

backend/src/utils/resourceUtils.ts

https://issues.redhat.com/browse/RHOAIENG-15388
Fixes error `Cannot read properties of undefined (reading 'notebookController')`
The `resourceUtils.ts#createDashboardCR` function returned an array instead of the dashboard config itself, therefore when attempting to read `spec.notebookController` from the config, it would fail since `spec` is `undefined` on the array. At the same time, also returned the `blankDashboardCR` in case creation were to fail.
This points to a bigger issue where our tsconfig needs to be made strict.
- Spin down the dashboard deployment or stop your local backend server. 
- Delete the OdhDashboardConfig
- Start the dashboard backend
- Immediately hit the frontend URL.
- Page should load without error. …

fix return type when creating dashboard config

---

frontend/src/__mocks__/mockHardwareProfile.ts
frontend/src/api/k8s/__tests__/hardwareProfiles.spec.ts
frontend/src/pages/hardwareProfiles/ManageNodeResourceSection.tsx
frontend/src/pages/hardwareProfiles/nodeResource/CountFormField.tsx
frontend/src/pages/hardwareProfiles/nodeResource/ManageNodeResourceModal.tsx
frontend/src/pages/hardwareProfiles/nodeResource/NodeResourceForm.tsx
frontend/src/pages/hardwareProfiles/nodeResource/NodeResourceTable.tsx
frontend/src/pages/hardwareProfiles/nodeResource/NodeResourceTableRow.tsx
frontend/src/pages/hardwareProfiles/nodeResource/__tests__/utils.spec.ts
frontend/src/pages/hardwareProfiles/nodeResource/const.ts
frontend/src/pages/hardwareProfiles/nodeResource/utils.ts

[RHOAIENG-16256](https://issues.redhat.com/browse/RHOAIENG-16256)
Added table and modal for Node resource for Hardware profile
Currently this table and modal are standalone components and are not used anywhere, to tests you can import `<ManageNodeResourceSection />` to any form page, like i have tested this in `ManageAcceleratorProfile` 
Add unit tests for validation utility functions
@vconzola

Node resource table and modals

---

frontend/src/__tests__/cypress/cypress/pages/acceleratorProfile.ts
frontend/src/pages/acceleratorProfiles/screens/list/AcceleratorProfiles.tsx
frontend/src/pages/acceleratorProfiles/screens/list/AcceleratorProfilesTableRow.tsx
frontend/src/pages/acceleratorProfiles/screens/manage/tolerations/TolerationsTable.tsx

Closes [RHOAIENG-16464](https://issues.redhat.com/browse/RHOAIENG-16464)
Fix for warnings in the console cause by PF v6 upgrade. 
- Navigate to `Applications -> Explore`
- Open the dev console, verify there are no warnings generated
- Navigate to `Settings -> Accelerator profiles`
- Open the dev console, verify there are no warnings generated
Test Id was updated from `description` to `table-row-title-description`
No additional tests required since there is merely a structural change.

Fix for warnings from PF upgrade

---

frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
frontend/src/pages/projects/screens/spawner/const.ts
frontend/src/pages/projects/screens/spawner/types.ts

Closes: [RHOAIENG-16189](https://issues.redhat.com/browse/RHOAIENG-16189)
Removes invalid jump link to Data connections in the create workbench page. In doing so, also cleaned up some unused data connections code.
Tested locally on cluster.
- Navigate to your data science project
- Workbench tab, create workbench.
- The Data connections jump link should no longer exist.
Before:
After:

Remove invalid jump link

---

frontend/src/pages/projects/screens/detail/storage/ClusterStorageModal.tsx
frontend/src/pages/projects/screens/detail/storage/ClusterStorageTableRow.tsx
frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
frontend/src/pages/projects/screens/spawner/storage/AddExistingStorageField.tsx
frontend/src/pages/projects/types.ts

https://issues.redhat.com/browse/RHOAIENG-16239
Cluster storage is now showing the displayname before  and after creation of a workbench  
1. Create a PVC with displayName ( you can find the example in the jira issue)
2. Create a workbench 
3. Attach the created PVC, check if the displayed name of attached PVC is attached to workbench
4. Once created, go to cluster storage and check if the display name is still showing instead of metadata name
N/A

show display name instead of pvc metadata name

---

frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsTabs.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionRegisteredDeploymentsView.tsx

closes https://issues.redhat.com/browse/RHOAIENG-17775
this is a fix for an issue conor found while testing https://issues.redhat.com/browse/RHOAIENG-16078
the deployment list in the /modelRegistry registeredModels versions deployments table wasn't updating properly when a deployment was edited or deleted. this pr fixes that.
i updated and deleted deploys and made sure that the changes were reflected right away without having to refresh the page.
no impacted tests

fix(mr deploys): update list with edits/deletes

---

frontend/src/concepts/modelRegistry/apiHooks/__tests__/updateTimestamps.test.ts
frontend/src/concepts/modelRegistry/utils/updateTimestamps.ts

https://issues.redhat.com/browse/RHOAIENG-16481
related to [RHOAIENG-16077](https://issues.redhat.com/browse/RHOAIENG-16077) 
Fixed all the scenarios for point 3
Deploy a version and verify that the deploy updates the Lat modified field in both versions and models list 
Updated the test

Version Deploy not updating timestamp

---

frontend/src/pages/projects/screens/detail/overview/serverModels/PlatformSelectSection.tsx

Closes [RHOAIENG-17776](https://issues.redhat.com/browse/RHOAIENG-17776)
Change the layout of the Platform selection section in the project overview page to be `flex` rather than `stack`. `stack` sets the height to be 100% which causes it to utilize extra space.
- From the Projects page, select a project that has no deployed models or model server selections.
- Scroll to the bottom of the Overview section
- Verify the `Project configuration` section is shown correctly.
No impact to tests, visual change only
/cc @jgiardino

Fix project overview layout when no deployed models

---

frontend/src/api/k8s/servingRuntimes.ts

Jira: https://issues.redhat.com/browse/NVPE-82
Added support for creating a second model with the same NVIDIA NIM.
Deployed a model and successfully deployed the same model again within the same project.

fix: add support for creating a second model with the same NVIDIA NIM

---

frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTableRow.tsx

Closes: [RHOAIENG-5256](https://issues.redhat.com/browse/RHOAIENG-5256)
Fixes the layout for the token disabled warning. It will now be on the right, inline with the token authentication, instead of below. 
Tested locally on cluster.
- Navigate to the models tab in your data science project. 
- Deploy a model with tokens disabled
- Inspect the model to see the change in layout
Before:
After:

Fix layout for token disabled warning

---

frontend/src/__mocks__/index.ts
frontend/src/__mocks__/mockConfigMapSecrets.ts
frontend/src/__tests__/cypress/cypress/pages/modelRegistrySettings.ts
frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistrySettings/modelRegistrySettings.cy.ts
frontend/src/concepts/modelRegistrySettings/__tests__/useModelRegistryCertificateNames.spec.ts
frontend/src/pages/modelRegistrySettings/CreateMRSecureDBSection.tsx
frontend/src/pages/modelRegistrySettings/CreateModal.tsx

Tests for [RHOAIENG-15899](https://issues.redhat.com/browse/RHOAIENG-15899)
Added unit test for `useModelRegistryCertificateNames` hook and Cypress tests for MR secure DB section
Run the unit test file and Cypress tests using the commands from README

Tests for mr secure db section

---

frontend/src/pages/modelRegistrySettings/CreateModal.tsx

Two commits were recently merged that added the same `data-testid` prop causing a lint error.
Since we do not use prow ci jobs, the checks previously passed and no rebase was required by git to merge.
`npm run test:lint`
Check CI test job.
N/A

remove duplicate prop to fix lint error

---

frontend/package-lock.json

[RHOAIENG-17793](https://issues.redhat.com/browse/RHOAIENG-17793)
[RHOAIENG-17794](https://issues.redhat.com/browse/RHOAIENG-17794)
* CVE-2024-55565 odh-dashboard-container: nanoid mishandles non-integer values
* CVE-2024-52798 odh-dashboard-container: path-to-regexp Unpatched  ReDoS in 0.1.x
`npm audit` in frontend folder and check for 0 vulnerabilities. 
None

Frontend Vulnerabilities fixed

---

frontend/src/api/k8s/inferenceServices.ts
frontend/src/api/k8s/utils.ts

https://issues.redhat.com/browse/RHOAIENG-16900
This adds a rudimentary parser that should handle most cases for inferenceservice argument parsing.
Note, I'm not a JS expert, and wrote it with the help of my internal AI, so it's possible there's some degerenate edge case with this, but in testing it worked fine
Code used to test: 
[parseCommandLine.ts.txt](https://github.com/user-attachments/files/18186726/parseCommandLine.ts.txt)
(Note it misbehaves a bit on some of the negative tests, but the normal test cases it works fine on)
Tested with the above tests, caveats noted

Add in proper handling of spaces and quotes in ISVC parsing

---

frontend/src/api/k8s/__tests__/utils.spec.ts

Follow up for #3592 
Add unit tests for parseCommandline util function
Ran the unit test for parseCommandline added in this PR.
This PR only adds unit tests 

Unit tests parsecommandline util

---

frontend/src/api/k8s/__tests__/utils.spec.ts
frontend/src/pages/modelServing/screens/projects/kServeModal/ServingRuntimeArgsSection.tsx

Followup to https://github.com/opendatahub-io/odh-dashboard/pull/3592 and https://github.com/opendatahub-io/odh-dashboard/pull/3633.
Resolves https://issues.redhat.com/browse/RHOAIENG-16900.
Adds one more test based on comments on #3633, and removes the now-incorrect help text directing users to only have one argument per line now that we support single-line arg lists.
Help text before:
Help text after:
No manual testing, this is just a unit test and a microcopy change.
See new unit test - just making sure the util still handles multi-line args properly.

parseCommandLine: Add unit test for multi-line input, remove incorrect help text

---

frontend/src/__tests__/cypress/cypress/pages/components/Modal.ts
frontend/src/__tests__/cypress/cypress/pages/loginDialog.ts
frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/application.cy.ts
frontend/src/app/App.tsx
frontend/src/app/SessionExpiredModal.tsx
frontend/src/app/useApplicationSettings.tsx
frontend/src/services/dashboardConfigService.ts

Towards https://issues.redhat.com/browse/RHOAIENG-1154.
Before:
After:
Run `application.cy.ts` to simulate 403 status code and verify the modal is rendered. 
Added new test to `application.cy.ts`. 

[RHOAIENG-1154]: Apply modal to alert user error

---

manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml

https://issues.redhat.com/browse/RHOAIENG-15160
Prevent group changes in the OdhDashboardConfig so all changes are properly in the Auth resource created by the Platform. See https://github.com/opendatahub-io/opendatahub-operator/pull/1452 for those changes.
There is a UI change to support not writing to this resource anymore, see https://github.com/opendatahub-io/odh-dashboard/pull/3577. 
When saving in OdhDashboardConfig, you should see an error like this:
It has a minor set of wording to point them to another resource. 
Apply the change to a cluster -- it'll mutate the CRD and the CR will no longer be modifiable. 
N/A

Limit the ability to change the group configs

---

frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/workbenches.cy.ts

https://issues.redhat.com/browse/RHOAIENG-18051
As the issue with the PVC showing it's name instead of the Display Name in the UI (https://issues.redhat.com/browse/RHOAIENG-16239) has been fixed, we need to update the Workbenches test.
It's been failing in the lasts nightlies
`$ npx cypress run --spec "**/workbenches.cy.ts" --browser chrome`
Fix for workbenches.ct.ts test

Fix: workbenches e2e test. Use PVC Display Name

---

frontend/src/__mocks__/mockInferenceServiceK8sResource.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts
frontend/src/api/k8s/__tests__/inferenceServices.spec.ts
frontend/src/api/k8s/inferenceServices.ts
frontend/src/k8sTypes.ts
frontend/src/pages/modelServing/screens/projects/utils.ts
frontend/src/pages/modelServing/utils.ts

Fix: https://issues.redhat.com/browse/RHOAIENG-17640
Add annotation for kserve serverless per requested.
Added unit testing and deployed a model:
1. Deploy a new kserve model
2. Check that the inferenceservice contains the annotation

Add annotation for kserve servereless

---

frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/clusterStorage.cy.ts
frontend/src/pages/projects/components/StorageSizeBars.tsx
frontend/src/pages/projects/screens/detail/storage/StorageTable.tsx
frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx
frontend/src/pages/projects/screens/detail/storage/data.ts

[RHOAIENG-16283](https://issues.redhat.com/browse/RHOAIENG-16283)
Removed expandable row content from the cluster storage table and added new column for size.
Check the cluster storage table page.
Changed the reference of expandable row to table column in cypress test
@xianli123

Show 'Storage size' column directly in the storage table

---

frontend/src/pages/connectionTypes/ConnectionTypesTableRow.tsx

Closes: [RHOAIENG-17142](https://issues.redhat.com/browse/RHOAIENG-17142)
Hides the edit and delete options for connections owned by DSC. Since the admin will never be able to enable these actions, there's no need for them to be visible. 
Tested locally 
Before, with edit and delete disabled:
After, edit and delete hidden:

Hide disabled kebab for connections owned by DSC

---

backend/src/routes/api/dev-impersonate/index.ts
backend/src/utils/constants.ts

Fixes the URL path to `oath` when the dev server is running agains an RHOAI dashboard
- For a cluster whose oath route is not `oauth-openshift`, Edit `.env.local` and set `DEV_IMPERSONATE_USER` and `DEV_IMPERSONATE_PASSWORD` to a valid combo and set `DEV_OAUTH_PREFIX` to the correct route.
- Run the dev server
- In the dev dashboard, select the user menu and `Start impersonate`
- Verify there are no errors and you now see only projects that `DEV_IMPERSONATE_USER` should see.
None, dev mode only

Allow override of the path to oauth for impersonate user

---

frontend/src/concepts/nimServing/NIMAvailabilityContext.tsx
frontend/src/pages/modelServing/screens/projects/__tests__/nimUtils.spec.ts
frontend/src/pages/modelServing/screens/projects/__tests__/utils.spec.ts

https://issues.redhat.com/browse/NVPE-39
Added a unit test for the getNIMResourcesToDelete function and relocated the fetchNIMAccountTemplateName unit test to a new file alongside the newly created test for better organization.
Ran all the unit tests to make sure nothing was broken.

fix: add unit test for getNIMResourcesToDelete function

---

frontend/src/__tests__/cypress/cypress/tests/e2e/settings/clusterSettings/testDataCollection.cy.ts
frontend/src/__tests__/cypress/cypress/utils/oc_commands/customResources.ts

https://issues.redhat.com/browse/RHOAIENG-17801
Migrate ODS-1218 to Cypress
- Tested against ODH-Nightly & RHOAI nightly
After exporting the test-variables.yml we have 2 different ways:
Using the UI
Go to odh-dashboard/frontend/src/tests/cypress and run the command npx cypress open . This will open the Cypress UI where testDataCollection.cy.ts can be run.
Headless
Go to odh-dashboard/frontend/src/tests/cypress and run the command npx cypress run --spec "cypress/tests/e2e/settings/clusterSettings/testDataCollection.cy.ts" --browser chrome
- This is already a test
Self …

Cypress e2e Test - Verify That "Usage Data Collection" Can Be Set In "Cluster Settings"

---

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelinesTopology.cy.ts
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/utils.tsx
frontend/src/utilities/__tests__/time.spec.ts
frontend/src/utilities/time.ts

https://issues.redhat.com/browse/RHOAIENG-13774
The pipeline runs detail pages are changed to UTC time zones and duration time is more consistent
`npm run test:unit **/time.spec.ts`
Edited the `time.spec.ts` file

changed fields to be UTC and duration to be more descriptive

---

frontend/src/pages/exploreApplication/EnableModal.tsx

JIRA: https://issues.redhat.com/browse/RHOAIENG-425
In `OdhApplication` CRD, the field `spec.enable` may not contain `title` and `actionLabel` fields. Give them default value to show the enable modal correctly. Default fallback title is `spec.displayName` and default fallback actionLabel is `Enable`
Import the following YAML to your cluster using OpenShift console `opendatahub` namespace (or the namespace where you deployed the ODH dashboard)
```
apiVersion: dashboard.opendatahub.io/v1
kind: OdhApplication
metadata:
annotations:
opendatahub.io/categories: 'Data management,Data preprocessing,Model training'
name: mlflow-server
labels:
app: odh-dashboard
spec:
enable:
validationConfigMap: mlflow-enable
img: '<svg width="24" height="25" viewBox="0 0 24 25" fill="none" …
```

Give default title and action label to the application enable modal

---

frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionDetails.cy.ts
frontend/src/k8sTypes.ts
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetails.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersions.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsTable.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionsArchive/ArchiveModelVersionDetails.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionArchiveDetails.tsx
frontend/src/pages/modelRegistry/screens/RegisteredModels/RegisteredModelTable.tsx
frontend/src/pages/modelRegistry/screens/RegisteredModels/useRegisteredModelDeployInfo.ts
frontend/src/pages/modelRegistry/screens/components/DeployRegisteredModelModal.tsx
frontend/src/pages/modelServing/__tests__/useInferenceServices.spec.ts
frontend/src/pages/modelServing/screens/projects/utils.ts
frontend/src/pages/modelServing/useInferenceServices.ts

Closes: [RHOAIENG-16989](https://issues.redhat.com/browse/RHOAIENG-16989)
This PR aims to add model registry name label when creating an inference service
1. deploy a model from the model registry UI.
2. test that the deployed model won't show up in other model registry deployments.
3. Also, make sure that the model deployments which does not have label (modelregistry.opendatahub.io/name) will show up in deployments. As we are returning all ISVCs that either have modelregistry.opendatahub.io/name === registryName or do not have the modelregistry.opendatahub.io/name label.
Added unit test and cypress test.

Add model registry name label when creating an inferenceservice

---

docs/external-redirects.md
frontend/src/__tests__/cypress/cypress/pages/externalRedirect.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/externalRedirects.cy.ts
frontend/src/app/AppRoutes.tsx
frontend/src/pages/ApplicationsPage.tsx
frontend/src/pages/external/ExternalRoutes.tsx
frontend/src/pages/external/RedirectErrorState.tsx
frontend/src/pages/external/redirectComponents/ExternalRedirectNotFound.tsx
frontend/src/pages/external/redirectComponents/PipelinesSdkRedirects.tsx
frontend/src/utilities/__tests__/useRedirect.spec.ts
frontend/src/utilities/useRedirect.ts

https://issues.redhat.com/browse/RHOAIENG-8476
This PR adds a system to handle external URL redirects in a centralized way, with the first implementation handling Pipeline SDK URLs.
WIP bc waiting for backend to confirm some things but could probably merge before them
- External routes system under `/external/*`
- Redirect handling with loading and error states
- Pipeline SDK URL support for experiments and runs
1. Create a new redirect component in `frontend/src/pages/external/redirectComponents/`
2. Add your route to `ExternalRoutes.tsx`
3. Use `useRedirect` hook to handle the redirect logic
Example:
```tsx
const [redirect, state] = useRedirect(() => '/foo');
// With async path creation
const [redirect, state] = useRedirect(async () => {
const data = await fetchData();
return …
```

Add external routes to AppRoutes component

---

frontend/src/k8sTypes.ts
frontend/src/pages/modelServing/screens/projects/kServeModal/KServeDeploymentModeDropdown.tsx
frontend/src/pages/modelServing/screens/projects/utils.ts
frontend/src/pages/modelServing/useDefaultDeploymentMode.ts

https://issues.redhat.com/browse/RHOAIENG-16489
Read the kserve `defaultDeploymentMode` value on the DSC status. Then use this value for preselecting the default mode and also show which one is the default.
This requires a nightly odh operator or the likes to have a default deployment mode other than serverless
1. Uncheck the devFlag `disableKServeRaw`
2. deploy a model
3. check the "... (default)" and the preselected value in the modal
No tests added. the pulling of the DSC status value is pretty simple. and creating a cypress test for a different preselection seemed like overkill, but lmk.
@yih-wang 

Read and show default deployment mode in deploy modal

---

frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineImportModal.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineVersionImportModal.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/v1-pipeline.yaml
frontend/src/concepts/dashboard/DashboardModalFooter.tsx
frontend/src/concepts/pipelines/content/InvalidArgoDeploymentAlert.tsx
frontend/src/concepts/pipelines/content/PipelineMigrationNoteLinks.tsx
frontend/src/concepts/pipelines/content/const.ts
frontend/src/concepts/pipelines/content/import/PipelineImportBase.tsx
frontend/src/concepts/pipelines/content/import/utils.ts

JIRA: https://issues.redhat.com/browse/RHOAIENG-6754
When importing a pipeline, do the following check:
- Whether there is an `InvalidInputError` in the error message
- Whether there is `parsedYaml.kind === 'PipelineRun' && parsedYaml.apiVersion === 'tekton.dev/v1beta1'` in the YAML file uploaded
If true, then we change the error message to prompt user to the docs, and migrate their v1 pipelines to v2.
NOTE: The docs are not available yet, it's for 2.17. So you will see 404 pages by clicking those links. But they are verified by the doc team.
1. Import a v1 pipeline (I added the example into the cypress test, you can find it in the code changes)
2. Make sure you got the error message with links to the docs
Added cypress tests to verify this change …

Change error when importing v1 pipeline

---

frontend/src/pages/projects/screens/spawner/storage/SpawnerMountPathField.tsx
frontend/src/pages/projects/screens/spawner/storage/__tests__/utils.spec.ts
frontend/src/pages/projects/screens/spawner/storage/utils.ts

[RHOAIENG-17252](https://issues.redhat.com/browse/RHOAIENG-17252)
I changed mentions of "folder(s)" to "mount path(s)"
@Gkrumbach07 mentioned that the other 2 criteria don't need to be met at this moment, but please correct me if I'm wrong.
visually. It is also included in unit tests. The reproduction instructions are in the jira ticket.
edited a test in `utils.spec.ts`

made wording more consistent in storage dialog

---

manifests/rhoai/addon/apps/nvidia/nvidia-app.yaml

https://issues.redhat.com/browse/RHOAIENG-1141
See the comments in the Jira story for how we uncovered that this is deprecated and safe to remove. 
Support link re: [this operator](https://docs.redhat.com/en/documentation/red_hat_openshift_ai_cloud_service/1/html/managing_openshift_ai/enabling_accelerators#enabling-nvidia-gpus_managing-rhoai) is no longer supported. 
`wget https://raw.githubusercontent.com/opendatahub-io/odh-dashboard/81fc54e3d4a3068289c0dc7f54b1d56070418e37/manifests/rhoai/addon/apps/nvidia/nvidia-app.yaml` 
Create a new `OdhApplication` in the cluster with the modified payload. Validated that the `enabled` button no longer appear
-- The `enable` button for the `NVIDIA GPU addon`  in RHOAI should no longer be displayed. 
If you …

[RHOAIENG-1141] remove the deprecated nvidia GPU Addon manifest from rhoai

---

frontend/src/pages/projects/screens/spawner/environmentVariables/EnvTypeSelectField.tsx

Closes: [RHOAIENG-1201](https://issues.redhat.com/browse/RHOAIENG-1201)
Previously, when creating a workbench, if a user wanted to add an environment variable, a selection is required to complete the creation. There was no indication that this field was required. This PR adds a required star to the drop down if the user chooses to add the variable. 
Tested locally 
- Navigate to your data science projects, and choose one to create a workbench for. 
- In the create workbench page, scroll down to environment variables. It should be an optional field. But when you click to add variables, a title of "Variable type * " will now show. 
Environment Variables field:
Before:
After:

Adds required to environment variables

---

frontend/src/pages/projects/notebook/NotebookRouteLink.tsx
frontend/src/pages/projects/notebook/StopNotebookConfirmModal.tsx
frontend/src/pages/projects/screens/detail/overview/trainModels/NotebooksCardItems.tsx

Closes [RHOAIENG-18073](https://issues.redhat.com/browse/RHOAIENG-18073)
Remove style overrides for the `NotebookRouteLink` component. Font size should be standard in all cases.
Navigate to the Data Science Projects page, expand the workbenches for a project. Verify the link font size is correct.
Navigate to a project's overview page, verify the workbench links in the Workbenches card have the correct font size.
Navigate to a project's Workbenches page, verify the `Open` links in the table have the correct font size.
Click `Stop` on a workbench row, verify the workbench link in the confirmation dialog has the correct font size
No test impact, visual change only
/cc @jgiardino

Fix for notebook route link font size

---

frontend/src/__tests__/cypress/cypress/tests/mocked/distributedWorkloads/globalDistributedWorkloads.cy.ts
frontend/src/pages/distributedWorkloads/global/useDistributedWorkloadsTabs.tsx

Closes: [RHOAIENG-7711](https://issues.redhat.com/browse/RHOAIENG-7711)
This PR aims to update the positions of DW tabs. Distributed workload status as the first tab and metrics next.
Test that, Distributed workload status is the first tab and metrics next.
Updated cypress tests.

Update the positions of DW tabs

---

frontend/src/__mocks__/mockDscStatus.ts
frontend/src/__tests__/cypress/cypress/pages/clusterSettings.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/clusterSettings/clusterSettings.cy.ts
frontend/src/pages/clusterSettings/ClusterSettings.tsx
frontend/src/pages/clusterSettings/ModelServingPlatformSettings.tsx

https://issues.redhat.com/browse/RHOAIENG-16491
This adds the admin page default deployment mode dropdown. It's set to read only as setting the mode requires new dashboard functionality that was a WIP. It will be updated in a future story before release.
This requires a nightly odh operator or the likes to have a default deployment mode other than serverless
Uncheck the devFlag disableKServeRaw
Go to the cluster settings page
Verify the button is selected with the correct deployment mode
A cypress test has been added
@yih-wang 

Add default deployment mode selector as read only

---

frontend/src/pages/ApplicationsPage.tsx

Closes [RHOAIENG-18227](https://issues.redhat.com/browse/RHOAIENG-18227)
Prevents the actions button from wrapping in a page header when the description is very long.
- Navigate to `Data Science Projects` and select a project
- Use the `Actions` button and `Edit project` 
- Set the project's description to a something very long
- Save
- Verify the project details page continues to show the `Actions` button aligned with the title and not wrapped below the description.
None, visual change only

Fix for page header layout when page has long description

---

frontend/src/__mocks__/mockConnectionType.ts
frontend/src/concepts/k8s/utils.ts

https://issues.redhat.com/browse/RHOAIENG-18622
Simply changing to check for the existence of the `platform.opendatahub.io/part-of` label. Also updating mocks to reflect this change. Personally wouldn't mind changing the name of the function since we aren't using the ownership to determine if something is created by the DSC. 
Manually tested. Should see the changes from [this PR](https://github.com/opendatahub-io/odh-dashboard/pull/3642) once it's working (correct label for pre-installed and no kebab actions for edit and delete if preinstalled). User created connection types should show the username as the creator and still allow editing and deleting in the kebab. 
Updated mocks for data connection config maps. Wouldn't be a bad idea to add a line to the mock test to ensure there's no …

Update ownedByDSC to use correct label for checking what is created by the operator

---

frontend/src/components/ProgressBarWithLabels.scss
frontend/src/components/ProgressBarWithLabels.tsx
frontend/src/pages/distributedWorkloads/components/WorkloadResourceUsageBar.tsx
frontend/src/pages/projects/components/StorageSizeBars.tsx

https://issues.redhat.com/browse/RHOAIENG-5147
Refractor the cluster storage progress bar and distributed workload progress bar to share component
- Check the storage cluster progress bar
- Check the distributed workload progress bar from distributed workload metrics table
No UI changes just the refractor

refractor UsageBar and StorageSizeBar

---

frontend/src/pages/hardwareProfiles/manage/ManageHardwareProfile.tsx

[RHOAIENG-18106](https://issues.redhat.com/browse/RHOAIENG-18106)
Display name was not trimmed, which caused the issue of improper sorting.
Create a hardware profile with leading and trailing spaces in the name and check the sorting in the list.
None, just added trim to display name.

Hardware Profile Display Name is not trimmed

---

frontend/src/pages/hardwareProfiles/HardwareProfilesTableRow.tsx
frontend/src/pages/hardwareProfiles/nodeResource/NodeResourceTableRow.tsx
frontend/src/pages/hardwareProfiles/nodeSelector/NodeSelectorTableRow.tsx
frontend/src/pages/hardwareProfiles/toleration/TolerationTableRow.tsx

[RHOAIENG-18090](https://issues.redhat.com/browse/RHOAIENG-18090)
Added truncate to form table fields
When creating hardware profile enter large entry for those field, they should be truncated.
None, just added truncate

Name, resource label, tolerations and Node selector fields - Unlimited size string

---

frontend/src/__mocks__/mockServingRuntimeTemplateK8sResource.ts
frontend/src/__tests__/cypress/cypress/pages/servingRuntimes.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/customServingRuntimes/customServingRuntimes.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/customServingRuntimes/customServingRuntimesUtils.ts
frontend/src/api/k8s/__tests__/templates.spec.ts
frontend/src/concepts/k8s/utils.ts
frontend/src/pages/connectionTypes/ConnectionTypesTableRow.tsx
frontend/src/pages/connectionTypes/manage/EditConnectionTypePage.tsx
frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeTableRow.tsx
frontend/src/pages/modelServing/customServingRuntimes/utils.ts

Closes: [RHOAIENG-10686](https://issues.redhat.com/browse/RHOAIENG-10686)
This PR aims to Update the Serving runtime templates to use `platform.opendatahub.io/part-of` label to identify preinstalled resources.
Make sure that the pre-installed label will display on serving runtime templates with `platform.opendatahub.io/part-of` label. 
Updated cypress and unit tests.

Update the Serving runtime templates to use correct label to identify preinstalled resources

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionDeploy.cy.ts
frontend/src/pages/modelRegistry/screens/RegisteredModels/useRegisteredModelDeployInfo.ts

Closes: [RHOAIENG-15827](https://issues.redhat.com/browse/RHOAIENG-15827)
This PR aims to update the pre-fill behavior of "Deploy from model registry" form (KServe modal). The generated model name no longer includes a timestamp and is trimmed to a max of 63 characters. 
The character limit validation piece of this has been moved to a backend issue [RHOAIENG-18603](https://issues.redhat.com/browse/RHOAIENG-18603).
1. Click on Deploy from Model Registry (with long version name or registered model name).
2. Select project with single model serving platform enabled.
3. Check that the model name is pre-filled and the characters limit is 63.
added cypress test.

Update Deploy from model registry form pre-fill behavior

---

frontend/src/__tests__/cypress/cypress/pages/resources.ts
frontend/src/__tests__/cypress/cypress/support/commands/application.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/learningResources/testResourcesfilters.cy.ts
frontend/src/__tests__/cypress/cypress/utils/resourceUtils.ts

Closes: [RHOAIENG-17797](https://issues.redhat.com/browse/RHOAIENG-17797)
Migrate ODS-489 to Cypress
Created a Cypress command to get card numbers checkbox labels In Resources page and compare the numbers of cards on that filter with the same.
- Locally against a PSI cluster and ODH-Nightly
After exporting the test-variables.yml we have 2 different ways:
Using the UI
Go to odh-dashboard/frontend/src/tests/cypress and run the command npx cypress open . This will open the Cypress UI where testResourcesFilters.cy.ts can be run.
Headless
Go to …

[Cypress e2e] Verify Filters Are Working On Resources Page

---

frontend/src/components/ResourceNameTooltip.tsx
frontend/src/pages/hardwareProfiles/HardwareProfilesTableRow.tsx

[RHOAIENG-18874](https://issues.redhat.com/browse/RHOAIENG-18874)
hardware profiles name no longer overlaps with tooltip
visually
n/a, simple change

fix overlap in hardware profiles table

---

.github/workflows/authorized-tag-creators.txt
.github/workflows/create-tag-release.yml

Replace `QUAY_ODH_DASHBOARD_IMAGE_REPO` with `quay.io/repository/opendatahub/odh-dashboard` coz the GitHub action is [failing](https://github.com/opendatahub-io/odh-dashboard/actions/runs/12709365163/job/35428222022) and DevOps advised to use the image URL instead. This change is made to the `create-tag` action only.
Followed [this doc](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/store-information-in-variables) to make the changes. GitHub action whisperers welcome to correct me.
Can test it once this PR is merged and I run the action.
Tested on my fork with one of my own Quay repos: https://github.com/manaswinidas/odh-dashboard/actions/runs/13057310033
After the PR is posted & …

[GitHub action] Replace Quay image URL

---

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelinesTopology.cy.ts
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx

[RHOAIENG-18916](https://issues.redhat.com/browse/RHOAIENG-18916)
Pipeline logs were not appearing due to height and position issues. Added a height of 100vh for visibility.
Run a pipeline and check its logs.
Improved existing test to verify pipeline logs actually is visible to the user.

Pipeline logs are not appearing on run details page

---

frontend/src/app/AppRoutes.tsx
frontend/src/pages/BYONImages/BYONImageAccelerators.tsx
frontend/src/pages/BYONImages/BYONImageHardwareProfiles.tsx
frontend/src/pages/BYONImages/BYONImageRoutes.tsx
frontend/src/pages/acceleratorProfiles/screens/manage/ManageAcceleratorProfile.tsx
frontend/src/pages/acceleratorProfiles/screens/manage/ManageAcceleratorProfileDetailsSection.tsx
frontend/src/pages/acceleratorProfiles/screens/manage/ManageAcceleratorProfileFooter.tsx
frontend/src/pages/acceleratorProfiles/screens/manage/types.ts
frontend/src/pages/hardwareProfiles/manage/ManageHardwareProfile.tsx
frontend/src/pages/hardwareProfiles/manage/ManageHardwareProfileFooter.tsx

JIRA: [RHOAIENG-1458](https://issues.redhat.com/browse/RHOAIENG-1458)
Create separate routes for creating accelerator profile and hardware profile on the notebook image table. In that case, when creating it, the navigation could be more reasonable and clear.
Take hardware profile as an example, click on "Create profile" on any row
Now the creation page still sits under the notebook image settings context - You can check the breadcrumb and the side nav highlight
Click on "Cancel", it will take you back to the notebook settings table
When successfully creating, it will take you back to the notebook image table and show a notification with a link
Clicking on the link, it will take you to the edit page of that hardware profile
It's the same flow for accelerator profile if the hardware profile …

Update routing flow for creating accelerator/hardware profile on custom notebook image table

---

frontend/src/concepts/k8s/K8sNameDescriptionField/__tests__/utils.spec.ts
frontend/src/concepts/k8s/K8sNameDescriptionField/utils.ts
frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx

[RHOAIENG-13679](https://issues.redhat.com/browse/RHOAIENG-13679)
Workbench storage resource names are now capped at 63 characters. Project and workbench resource names are now capped at 30 characters.
Visually, you can see the resource name enforcement if you make a new PVC in workbench, make a new workbench, and make a new Project. If you put in absurd values for names, it should be converted with the max length.

added form limits for workbench, PVC, and project resource names

---

backend/src/routes/api/integrations/nim/index.ts
frontend/src/pages/exploreApplication/GetStartedPanel.tsx

JIRA - https://issues.redhat.com/browse/NVPE-103
This PR addresses implementing updates to the Enable Page and Explore Page Drawer behavior for user:
- For **users with NIM enabled**, the NIM card is now correctly displayed on the Enable page.
- For **users without NIM enabled**, a **disabled Enable button with a tooltip** is displayed on the Explore page drawer.
**When NIM in not enabled:**
Before fixing the problem - non-admin user does not see the Enable button or any indication of why it is missing:
After-non-admin user sees a disabled Enable button with a tooltip explaining why the button is not clickable:
**When NIM in enabled:**
Before fixing the problem - non-admin user doesn't see the NIM card, even though NIM is enabled:
After - NIM card is now visible to the non-admin user …

 Fix: NIM Enable/Disable Behavior for Users in Enable & Explore Pages

---

frontend/src/concepts/__tests__/StartNotebookModal.spec.tsx
frontend/src/concepts/notebooks/StartNotebookModal.tsx
frontend/src/types.ts
frontend/src/utilities/notebookControllerUtils.ts

Fixes [RHOAIENG-17784](https://issues.redhat.com/browse/RHOAIENG-17784)
Fixes events for notebooks that are starting and stopping.
Adds a final event `Server started` that doesn't get marked complete until the server is running.
Adds text to indicate the server is stopping and does not automatically mark the initial event complete
- Stop a running workbench and click on the status label
- Verify the status shows Stopping
- Verify the status text shows `Shutting down the server...`
- Verify all steps show incomplete
- Start a workbench
- Verify the label show starting
- For the starting workbench, click the label or message text
- Verify the workbench status dialog is shown
- Verify the current status is shown and Progress steps show the current completed steps
- Verify the steps update …

Fixes for workbench startup modal stopping and starting states

---

backend/src/types.ts
backend/src/utils/constants.ts
docs/dashboard-config.md
frontend/src/__mocks__/mockDashboardConfig.ts
frontend/src/concepts/areas/const.ts
frontend/src/concepts/areas/types.ts
frontend/src/k8sTypes.ts
manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml

https://issues.redhat.com/browse/RHOAIENG-18657
Adding a new feature flag for the KServe OCI Models feature.
Ran the dashboard and seems to be fine.
Added a mock for the flag so we can use it once we start writing mock tests.

Add feature flag for deploying KServe OCI Models

---

backend/src/types.ts
backend/src/utils/constants.ts
docs/dashboard-config.md
frontend/src/__mocks__/mockDashboardConfig.ts
frontend/src/__tests__/cypress/cypress/pages/modelCatalog.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalog.cy.ts
frontend/src/app/AppRoutes.tsx
frontend/src/concepts/areas/const.ts
frontend/src/concepts/areas/types.ts
frontend/src/k8sTypes.ts
frontend/src/pages/modelCatalog/EmptyModelCatalogState.tsx
frontend/src/pages/modelCatalog/ModelCatalogCoreLoader.tsx
frontend/src/pages/modelCatalog/ModelCatalogRoutes.tsx
frontend/src/pages/modelCatalog/ModelDetailsPage.tsx
frontend/src/utilities/NavData.tsx
manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml

Closes: [RHOAIENG-18953](https://issues.redhat.com/browse/RHOAIENG-18953)
- Adds feature flag `disableModelCatalog` and routes with placeholder content 
- When the feature flag is enabled, check for the below screen when you navigate to `/modelCatalog`
- When the feature flag is enabled, check for the below screen when you navigate to `/modelCatalog/tempDetails`
- Check for the "not found" screen when the feature flag is disabled.
1. Add the feature flag `disableModelCatalog` to the CRD(You may have to scale down the `odh-dashboard` Deployment)
2. Enable the feature flag in `OdhDashboardConfig` and wait till the Navigation item `Model Catalog` appears - it will appear above `Model Registry`
3. Check for the above screens and routes - both when the feature flag is enabled and when it is …

Model Catalog page skeletons and new feature flag `disableModelCatalog`

---

frontend/src/concepts/notebooks/NotebookStatusLabel.tsx
frontend/src/pages/projects/notebook/NotebookStateStatus.tsx

Fixes [RHOAIENG-17784](https://issues.redhat.com/browse/RHOAIENG-17784)
Updates the status labels in the workbench rows to show the hover treatment.
Removes the tooltip for failed status as the text is already shown.
Navigate to the `Data science projects` page
Expand one of the rows workbenches column
Hover over the status labels for the workbenches
Verify the background color changes on hover
No test impact, purely visual
/cc @tobiastal

Fix for hover state on workbench status labels

---

frontend/src/components/OdhAppCard.tsx

JIRA - [https://issues.redhat.com/browse/NVPE-136](https://issues.redhat.com/browse/NVPE-136)
This PR ensures that the "Disabled" NIM link is no longer clickable for non-admin users and provides a tooltip to inform them of the restriction.
**Before:**
Non-admin users could click on the "Disabled" NIM link, leading to confusion.
**After:**
The link is now disabled for non-admin users and a tooltip provides context on why the action is unavailable.
Tested locally by logging in as an admin and non-admin user.
Verified that:
- Admin users still have access to the link.
- Non-admin users see the disabled link with a tooltip.
- Log in as a non-admin user.
- Navigate to the Enable page.
- Ensure that the "Disabled" NIM link is disabled and shows the tooltip when hovered over.
Self checklist (all …

disable "Disabled" NIM Link for Non-Admins with Tooltip

---

frontend/src/concepts/__tests__/StartNotebookModal.spec.tsx
frontend/src/concepts/notebooks/StartNotebookModal.tsx
frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
frontend/src/pages/projects/notebook/NotebookStateStatus.tsx

Closes [RHOAIENG-19280](https://issues.redhat.com/browse/RHOAIENG-19280)
Fixes an issue where standalone notebook startup shows the server status modal as stuck on starting
Launch a standalone notebook
Monitor the startup status modal
Verify it updates to running once the notebook is running
Added a test for the startup modal given the parameters passed by the standalone notebook

Fix for standalone notebook startup dialog looking stuck

---

frontend/src/__tests__/cypress/cypress/fixtures/e2e/connectionTypes/testOOTBConnectionType.yaml
frontend/src/__tests__/cypress/cypress/tests/e2e/settings/connectionTypes/connectionTypes.cy.ts
frontend/src/__tests__/cypress/cypress/types.ts
frontend/src/__tests__/cypress/cypress/utils/dataLoader.ts

https://issues.redhat.com/browse/RHOAIENG-18736
Quick e2e test to verify our OOTB data connections are present. This will cover our common utils that we use to determine if something is installed by the operator. See https://github.com/opendatahub-io/odh-dashboard/pull/3682 for details on how that's done.
Ran the test against my cluster. Please note you will need ODH operator >= 1.22 and ODH dashboard latest.
None

Add e2e test for OOTB connection types

---

frontend/src/__mocks__/mockNimResource.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/modelServingNim.cy.ts
frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx

https://issues.redhat.com/browse/NVPE-101
Set default Model Server size to 'Custom' and update helper text.
Verified that the default Model Server size for NIM deployment is set to 'Custom', while for KServe, it defaults to 'Small'. Also confirmed that the helper text is correctly updated.

fix: set default Model Server size to 'Custom' and update helper text

---

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelinesTopology.cy.ts
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx

[RHOAIENG-18916](https://issues.redhat.com/browse/RHOAIENG-18916)
backport of https://github.com/opendatahub-io/odh-dashboard/pull/3697

[Backport] Pipeline logs are not appearing on run details page

---

frontend/src/pages/clusterSettings/utils.ts
frontend/src/utilities/__tests__/utils.spec.ts
frontend/src/utilities/utils.ts

https://issues.redhat.com/browse/RHOAIENG-19803
adds a safe execute around a new early development feature.
also adds a safe execute helper function to be used
without the latest DSC schema, open cluster settings page and see no error
should fix e2e tests

Add safeExecute utility for error handling in InstructLab feature check

---

backend/src/types.ts
backend/src/utils/constants.ts
frontend/src/__mocks__/mockDashboardConfig.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/connectionTypes/connectionTypes.cy.ts
frontend/src/concepts/areas/const.ts
frontend/src/concepts/areas/types.ts
frontend/src/k8sTypes.ts
frontend/src/utilities/NavData.tsx
manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml

Closes: [RHOAIENG-19606](https://issues.redhat.com/browse/RHOAIENG-19606)
Re-add the connection type feature flag for admin view
tested locally
Cypress test checking feature flag added back in

Connection type admin view feature flag

---

frontend/src/pages/clusterSettings/const.ts

Closes: [RHOAIENG-381](https://issues.redhat.com/browse/RHOAIENG-381)
Small fix to allow ‘ / ‘ characters in the toleration box for notebooks. The error message was also modified to reflect this change. 
- Navigate to settings -> cluster settings
- Scroll to the bottom and check "Add a toleration to notebook pods .... "
- The toleration key box should now allow for ' / ' characters to be used
Tested locally
Before:
After:

Notebook tolerations box update

---

backend/src/utils/constants.ts
docs/dashboard-config.md
frontend/src/__mocks__/mockDashboardConfig.ts
frontend/src/concepts/areas/const.ts
manifests/rhoai/shared/odhdashboardconfig/odhdashboardconfig.yaml

https://issues.redhat.com/browse/NVPE-157
Set disableNIMModelServing to false as required for GA to enable the NIM feature. 
Tested by making sure NIM is available with the setting set to false. 

fix: set disableNIMModelServing to false as required for GA

---

frontend/src/__tests__/cypress/cypress/pages/components/NIMDeployModal.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/modelServingNim.cy.ts
frontend/src/pages/modelServing/screens/projects/NIMServiceModal/NIMModelListSection.tsx

JIRA - https://issues.redhat.com/browse/NVPE-93
In this PR I replaced the current PF dropdown component with the [Select component with Typeahead variant](https://v5-archive.patternfly.org/components/menus/select#typeahead) in order to allow the user to start typing in the name of the model to reduce the size of the list.
Before there was no option to type and search in the model's dropdown (NVIDIA NIM):
This improves the user experience and will help in searching through the list as you start typing.
When trying to deploy a model using NIM, you should be able to search through the NVIDIA NIM dropdown as you start typing.

Alternative for models' info and the drop down list

---

frontend/src/pages/modelRegistry/screens/ModelRegistrySelector.tsx

Closes: [RHOAIENG-16089](https://issues.redhat.com/browse/RHOAIENG-16089)
When creating a model registry with one long string for a name, the name will exceed past the popover box. Currently this is a bug in PatternFly (https://github.com/patternfly/patternfly/issues/7340). For now, I've implemented a workaround by truncating the name.
Tested locally
- In settings under Model Registry, create a model with a very long name, specifically just one long string.
- Go back to the Model Registry tab and in the top, click 'View details' by your model registry. 
- The name should now truncate, and you should be able to hover to see the full name. 
Before:
After:

Model registry name truncation

---

frontend/src/concepts/connectionTypes/__tests__/utils.spec.ts
frontend/src/concepts/connectionTypes/fields/UriFormField.tsx
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/concepts/connectionTypes/validationUtils.ts
frontend/src/pages/connectionTypes/manage/ConnectionTypeDataFieldModal.tsx

https://issues.redhat.com/browse/RHOAIENG-19860
This allows setting the env var of connection type fields to match this https://kubernetes.io/docs/concepts/configuration/secret/#restriction-names-data so this will allow us to use `.dockerconfigjson` as an env var in connections
1. Create / edit connection type
2. add a new field named `.dockerconfigjson` and save
3. go to project and create a connection with that field
Update jest validation tests
@simrandhaliw 

Less strict connection field env variable names

---

frontend/src/__tests__/cypress/cypress/tests/mocked/projects/connections.cy.ts
frontend/src/concepts/connectionTypes/utils.ts

https://issues.redhat.com/browse/RHOAIENG-19053
When creating a connection, checks if there is stuff in the .dockerconfigfile, and instead of an "Opaque" secret it will be "kubeneties.io/dockerconfigjson"
-  Create / edit connection type
-  add a new field named .dockerconfigjson and save
-  go to project and create a connection
-  upload a file for the .dockerconfigjson field and submit
-  check the created secret in openshift console has type "kubeneties.io/dockerconfigjson"
Cypress test added for flow

Create a connection with secret type 'kubernetes.io/dockerconfigjson'

---

frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts
frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts
frontend/src/api/pipelines/callTypes.ts
frontend/src/api/pipelines/custom.ts
frontend/src/components/EmptyStateErrorMessage.tsx
frontend/src/concepts/pipelines/apiHooks/usePipelineByName.ts
frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/types.ts
frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/validationUtils.ts
frontend/src/concepts/pipelines/content/modelCustomizationForm/useIlabPipeline.ts
frontend/src/concepts/pipelines/context/usePipelineAPIState.ts
frontend/src/concepts/pipelines/types.ts
frontend/src/pages/pipelines/GlobalModelCustomizationRoutes.tsx
frontend/src/pages/pipelines/global/GlobalPipelineCoreLoader.tsx
frontend/src/pages/pipelines/global/PipelineCoreNoProjects.tsx
frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx
frontend/src/pages/pipelines/global/modelCustomization/FineTunePageFooter.tsx
frontend/src/pages/pipelines/global/modelCustomization/ModelCustomizationForm.tsx
frontend/src/pages/pipelines/global/modelCustomization/const.ts
frontend/src/routes/pipelines/modelCustomizationForm.ts

[RHOAIENG-19020](https://issues.redhat.com/browse/RHOAIENG-19020)
Added the instruct lab form with some zod methods.
The base URL is `/modelCustomization/instructlab/<project-name>`
Added test files. You can also test visually.
Added tests.
- [ x Included any necessary screenshots or gifs if it was a UI change.

created ilab form

---

frontend/src/__mocks__/mockDsc.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/clusterSettings/clusterSettings.cy.ts
frontend/src/api/k8s/dsc.ts
frontend/src/k8sTypes.ts
frontend/src/pages/clusterSettings/ClusterSettings.tsx
frontend/src/pages/clusterSettings/ModelServingPlatformSettings.tsx

https://issues.redhat.com/browse/RHOAIENG-16492
Adds the ability for odh admins and cluster admins to edit the cluster settings dropdown for KServe raw which changes the default deployment mode between RawDeployment (Standard) and Serverless (Advanced).
Logging in as both privileged and unprivileged users to ensure cluster settings are unavailable.
Updating the setting and saving
Make sure DSC gets updated properly
Updating should work if `defaultDeploymentMode` is present or not present
After save, the button should be disabled
Reload after a few minutes should reflect proper change
There's already a test `View KServe defaultDeploymentMode` for default deployment mode. Not sure if we want to expand the testing here. @emilys314 thoughts?
If you …

Patch DSC when Admin changes Default Deployment Mode

---

frontend/src/__mocks__/mockHardwareProfile.ts
frontend/src/__tests__/cypress/cypress/pages/hardwareProfile.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/hardwareProfiles.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/manageHardwareProfiles.cy.ts
frontend/src/api/k8s/__tests__/hardwareProfiles.spec.ts
frontend/src/app/NavSidebar.tsx
frontend/src/concepts/hardwareProfiles/const.ts
frontend/src/concepts/hardwareProfiles/types.ts
frontend/src/concepts/hardwareProfiles/validationUtils.ts
frontend/src/pages/hardwareProfiles/HardwareProfileEnableToggle.tsx
frontend/src/pages/hardwareProfiles/HardwareProfiles.tsx
frontend/src/pages/hardwareProfiles/HardwareProfilesTable.tsx
frontend/src/pages/hardwareProfiles/HardwareProfilesTableRow.tsx
frontend/src/pages/hardwareProfiles/__tests__/hardwareProfileWarning.spec.ts
frontend/src/pages/hardwareProfiles/__tests__/isHardwareProfileIdentifierValid.spec.ts
frontend/src/pages/hardwareProfiles/manage/ManageNodeResourceSection.tsx
frontend/src/pages/hardwareProfiles/nodeResource/NodeResourceTable.tsx
frontend/src/pages/hardwareProfiles/nodeResource/NodeResourceTableRow.tsx
frontend/src/pages/hardwareProfiles/nodeResource/const.ts
frontend/src/pages/hardwareProfiles/utils.ts
frontend/src/utilities/NavData.tsx
frontend/src/utilities/NavWithIcon.tsx
frontend/src/utilities/__tests__/valueUnits.spec.ts
frontend/src/utilities/useWatchHardwareProfiles.ts
frontend/src/utilities/valueUnits.ts

[RHOAIENG-17841](https://issues.redhat.com/browse/RHOAIENG-17841)
Invalid inputs will now show warnings in the UI
You can directly insert hardware profiles in the cluster dashboard. Input invalid values as specified in the jira issue and mockups.
I added unit tests and cypress tests

added warnings and tests for hardware profiles

---

frontend/src/__tests__/cypress/cypress/tests/e2e/settings/clusterSettings/testDataCollection.cy.ts

Enhancement for test ODS-1218 to improve the scenario for when a cluster is not torn down
- Tested against ODH-Nightly & RHOAI nightly
After exporting the test-variables.yml we have 2 different ways:
Using the UI
Go to odh-dashboard/frontend/src/tests/cypress and run the command npx cypress open . This will open the Cypress UI where testDataCollection.cy.ts can be run.
Headless
Go to odh-dashboard/frontend/src/tests/cypress and run the command npx cypress run --spec "cypress/tests/e2e/settings/clusterSettings/testDataCollection.cy.ts --browser chrome
- This is already a …

Enhancement to ODS-1218 'Verify That Usage Data Collection Can Be Set In Cluster Settings'

---

.github/pull_request_template.md

Found a typo while reading the PR template the first time.
No need
None

chore: Fix typo in PR template

---

frontend/src/pages/notebookController/screens/server/AcceleratorProfileSelectField.tsx
frontend/src/pages/notebookController/screens/server/__tests__/useAcceleratorCountWarning.spec.ts
frontend/src/pages/notebookController/screens/server/useAcceleratorCountWarning.tsx
frontend/src/pages/projects/screens/detail/notebooks/NotebookSizeDetails.tsx
frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx
frontend/src/pages/projects/screens/detail/notebooks/__tests__/utils.spec.ts
frontend/src/pages/projects/screens/detail/notebooks/utils.ts

[RHOAIENG-16749](https://issues.redhat.com/browse/RHOAIENG-16749)
Create a workbench and connect it to accelerators.
@xianli123

Show the GPU requests and limits in workbench table

---

frontend/src/pages/pipelines/global/modelCustomization/ModelCustomization.tsx

JIRA: [RHOAIENG-20338](https://issues.redhat.com/browse/RHOAIENG-20338)
Easy one-liner. Make the Drawer inline so the drawer content can push the page content to the side when it's open instead of covering the content.
Go to the model customization page, expand the taxonomy section, and click on "Learn more", see how the drawer pushes the content to the side.
N/A

Make model customization side drawer inline

---

frontend/src/__tests__/cypress/cypress/fixtures/e2e/dataScienceProjects/testWorkbenchNegativeTests.yaml
frontend/src/__tests__/cypress/cypress/pages/workbench.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dashboardNavigation/testManifestLinks.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchControlSuite.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchEditing.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchNegativeTests.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchStatus.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchTolerations.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchVariables.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/learningResources/testCustomResourceCreation.cy.ts
frontend/src/__tests__/cypress/cypress/types.ts
frontend/src/__tests__/cypress/cypress/utils/dataLoader.ts
frontend/src/__tests__/cypress/cypress/utils/retryableHooks.ts

https://issues.redhat.com/browse/RHOAIENG-20128
https://issues.redhat.com/browse/RHOAIENG-17421
- Migrate ODS-1973 to Cypress
- Created a new test also that validates that Workbenches cannot be created using invalid resources 
- Removes a number of tests from quarantine and corrected some titles
- Locally against a PSI cluster and ODH-Nightly also on Jenkins cypress/job/dashboard-tests/619/ 
- None - this is a test
Go to odh-dashboard/frontend/src/tests/cypress and run the command npx cypress open . This will open the Cypress UI where the various workbenches tests can be …

Cypress e2e - Workbenches (new e2e tests) and unquarantine existing tests 

---

frontend/src/concepts/roleBinding/RoleBindingPermissionsTableRow.tsx

Closes: [RHOAIENG-13745](https://issues.redhat.com/browse/RHOAIENG-13745)
Small truncation update to the users section
Tested locally. Under your Data science projects, navigate to the permissions tab. Add a user with an extremely long name. Name will now be truncated. 
Before:
After:

Small truncation fix

---

frontend/src/__tests__/cypress/cypress.config.ts

During test execution with the Firefox browser, Cypress was failing with the following error:
```
> npm run cypress:run:mock -- --browser=firefox 
Warning: We failed capturing this video.
This error will not affect or change the exit code.
Error: Insufficient frames captured to create video.
at ChildProcess.<anonymous> (<embedded>:778:16306)
at ChildProcess.emit (node:events:514:28)
at Process.onexit (node:internal/child_process:291:12)
An error was thrown in your plugins file while executing the handler for the after:spec event.
The error we received was:
Error: ENOENT: no such file or directory, unlink '<path-to-workdir>/odh-dashboard/frontend/src/__tests__/cypress/results/mocked/videos/application.cy.ts.mp4'
at Object.unlinkSync (node:fs:1954:11)
at Object.handler …
```

Fix: Remove Non-Existent Video File in after:spec Handler

---

frontend/src/api/k8s/__tests__/notebooks.spec.ts
frontend/src/concepts/pipelines/elyra/utils.ts
frontend/src/types.ts

https://issues.redhat.com/browse/RHOAIENG-19973
adds optional to volume for elrya secret in notebooks
1. create pipeline server
2. make sure elrya secret is created: `ds-pipeline-config`
3. create a workbench in same project
4. ensure elrya secret volume is added to notebook
5. delete pipeline server and make sure elrya secret is removed
6. make sure that workbench can still be started
non, k8s notebook spec change

Add optional flag to Elyra volume secret configuration

---

frontend/src/utilities/useQuickStart.ts

https://issues.redhat.com/browse/RHOAIENG-20532
This PR adds a `useQuickStart` hook that extracts the quickstart launch functionality from cards into a reusable hook. This allows any component to trigger quickstarts without being tied to card components.
Key changes:
- Adds new `useQuickStart` hook that provides:
- `launchQuickStart` method to trigger quickstarts
- Access to quickstart context values
- Uses existing `launchQuickStartUtil` under the hood
- Small, focused change to improve reusability
- No changes to existing quickstart behavior
1. Go to any component that needs quickstart functionality
2. Add the hook:
```typescript
const { launchQuickStart } = useQuickStart();
```
3. Add a trigger (e.g. button):
```typescript
<Button onClick={() => …
```

Make quickstart functionality available outside cards

---

frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts
frontend/src/api/k8s/secrets.ts
frontend/src/concepts/pipelines/content/createRun/submitUtils.ts
frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/__tests__/validationUtils.spec.ts
frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/validationUtils.ts
frontend/src/concepts/pipelines/content/modelCustomizationForm/useIlabPipeline.ts
frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx
frontend/src/pages/pipelines/global/modelCustomization/FineTunePageFooter.tsx
frontend/src/pages/pipelines/global/modelCustomization/ModelCustomizationForm.tsx
frontend/src/pages/pipelines/global/modelCustomization/const.ts
frontend/src/pages/pipelines/global/modelCustomization/teacherJudgeSection/JudgeModelSection.tsx
frontend/src/pages/pipelines/global/modelCustomization/teacherJudgeSection/TeacherJudgeInputComponents.tsx
frontend/src/pages/pipelines/global/modelCustomization/teacherJudgeSection/TeacherModelSection.tsx
frontend/src/pages/pipelines/global/modelCustomization/utils.ts

JIRA: [RHOAIENG-19108](https://issues.redhat.com/browse/RHOAIENG-19108)
Added 2 similar sections to the form: Teacher model and Judge model. Here are the descriptions.
1. Added validation to these 2 sections. When the public endpoint is chosen, it doesn't require a token to be input. When the private endpoint is selected, it requires the token field not to be empty. Also, the endpoint field needs to follow the URI format.
2. I leave the links to the docs in the description as empty for now
3. When submitting, it will create 2 separate secrets for both teacher and judge. There are 3 fields in the secrets: `api_token`, 'endpoint' and `model_name`. When it's public, the `api_token` field will be set as empty string.
4. The name of these 2 secrets are not decided yet, thus, after creating the …

Add teacher/judge section to ilab form

---

frontend/src/pages/modelServing/screens/projects/NIMServiceModal/NIMModelListSection.tsx

Related to the following:
https://issues.redhat.com/browse/NVPE-177
(which is a sub-task for https://issues.redhat.com/browse/NVPE-93)
Fixed the duplicated tags issue for models' info and the drop down list like in this model:
1. Enable NIM
2. Go to Data Science Project
3. Click on the existing or create a new project and go over the NVIDIA NIM dropdown
Here is a video where you can see the difference: On the right panel we see the issue of the the multiple tags (1/1.0/1.0.0). On the left panel is the solution.
https://github.com/user-attachments/assets/27665b8d-d082-4a21-b5cd-c87f8c46caf9

fix: duplicated tags issue for models' info and the drop down list

---

frontend/src/__mocks__/mockConnectionType.ts
frontend/src/concepts/connectionTypes/__tests__/utils.spec.ts
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionOciPathField.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionS3FolderPathField.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionExistingField.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionSection.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ConnectionSection.spec.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
frontend/src/pages/modelServing/screens/projects/utils.ts

https://issues.redhat.com/browse/RHOAIENG-19881
Prompt the user for the OCI Model URI when selecting a OCI connection for model deployment.
- If you paste in a URI with `<...>://...` it will remove the prefix
- requires you have a non empty value, other than that the validation is sparse
Existing connection:
New connection: 
- Create an ootb OCI connection deploy it
- deploy and create the connection inline
- test S3 and URI still work fine 
Added jest test for the ConnectionSection.tsx
@simrandhaliw 

feat(serving): add "Model URI" field to deployment modal

---

frontend/package-lock.json
frontend/package.json
frontend/src/utilities/markdown.ts

[RHOAIENG-20371](https://issues.redhat.com/browse/RHOAIENG-20371)
Upgraded the `dompurify` package to version 3.2.4 to address the CVE. Updated the code accordingly to accommodate the package upgrade. Since the package is also used as a sub-package, added an override as well.
Check the npm audit in the frontend, no vulnerabilities should be listed.
Also, review the markdown view in the dashboard, as it is directly affected by this change.
No changes required, just verify that the existing `markdown.spec.ts` tests pass.

DOMPurify CVE fix

---

frontend/src/pages/hardwareProfiles/HardwareProfiles.tsx

https://issues.redhat.com/browse/RHOAIENG-20592
Added the title icon to hardware profile page
Check for the title icon in the hardware profiles
N/A Added icon

add title icon to hardware profiles

---

manifests/rhoai/shared/odhdashboardconfig/odhdashboardconfig.yaml

Reverts opendatahub-io/odh-dashboard#3800
[PM make a call to revert the default state](https://redhat-internal.slack.com/archives/C07J39USZND/p1740759650546239?thread_ts=1740670757.356669&cid=C07J39USZND)

Revert "chore(19957): set rhoai manifest disableModelCatalog flag false"

---

.github/workflows/test.yml
Dockerfile
backend/package-lock.json
backend/package.json
docs/dev-setup.md
frontend/package-lock.json
frontend/package.json
package-lock.json
package.json
scripts/ci/Dockerfile

Upgrade dashboard and CI/CD to Node 22
* Tested locally and everything is working
* Tested in a working cluster with an image built out of the updated Dockerfile: `quay.io/lferrnan/odh-dashboard:rhoaieng-7374`
* There's a follow up PR downstream to upgrade the image: https://github.com/red-hat-data-services/odh-dashboard/pull/569
* Running locally the dashboard with `nvm`
* Installed `quay.io/lferrnan/odh-dashboard:rhoaieng-7374`

Upgrade to Node 20

---

frontend/src/__tests__/cypress/cypress/fixtures/e2e/workloadMetricsResources/testWorkloadMetricsResources.yaml
frontend/src/__tests__/cypress/cypress/fixtures/resources/yaml/kueue_reosources.yaml
frontend/src/__tests__/cypress/cypress/pages/distributedWorkloads.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/distributedWorkloadMetrics/testWorkloadMetricsDefaultPageContents.cy.ts
frontend/src/__tests__/cypress/cypress/types.ts
frontend/src/__tests__/cypress/cypress/utils/oc_commands/distributedWorkloads.ts
frontend/src/__tests__/cypress/cypress/utils/workloadMetricsUtils.ts
frontend/src/__tests__/resources/distributedworkloads/kueue_reosources.yaml

https://issues.redhat.com/browse/RHOAIENG-18124
- Migrated Workload metrics sanity tests from [ods-ci robot framework](https://github.com/red-hat-data-services/ods-ci/blob/master/ods_ci/tests/Tests/0600__distributed_workloads/test-distributed-workloads-metrics-ui.robot#L28) to cypress
- Added Supporting methods for kueue resource creation, deletion and WorkloadMetricsTestData
This change will include workloadmetrics Sanity tests, tested in local against rhoai nightly build
None - this is a test

[RHOAIENG-18124] Add Workload Metrics Sanity tests

---

.github/workflows/test.yml

https://issues.redhat.com/browse/RHOAIENG-21067
Removes the strategy matrix for node versions from the `Tests` job.
Should allow branch protection rules to target a status check for `Tests` instead of `Tests (20.x)`.
PR status checks
N/A

remove node version matrix from Tests job

---

.github/workflows/pull_request.yml

https://issues.redhat.com/browse/RHOAIENG-21067
Removes the strategy matrix for node versions from the Tests job.
Should allow branch protection rules to target a status check for Tests instead of Tests (18.x).
PR checks
N/A

[v2.21.0-fixes] remove node version matrix from Tests job

---

.github/workflows/test.yml

https://issues.redhat.com/browse/RHOAIENG-21067
Removes the strategy matrix for node versions from the Tests job.
Should allow branch protection rules to target a status check for Tests instead of Tests (18.x).
PR checks
N/A

[v2.26.0-fixes] remove node version matrix from Tests job

---

.github/workflows/test.yml

https://issues.redhat.com/browse/RHOAIENG-21067
Removes the strategy matrix for node versions from the Tests job.
Should allow branch protection rules to target a status check for Tests instead of Tests (18.x).
PR checks
N/A

[v2.29.0-fixes] remove node version matrix from Tests job

---

frontend/src/pages/modelServing/screens/projects/kServeModal/EnvironmentVariablesSection.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ServingRuntimeArgsSection.tsx

https://issues.redhat.com/browse/RHOAIENG-17779
made the buttons within `labelInfo` inline. 
this also makes it so that disabled buttons still show up as links instead of buttons. it also adds the underline styling. i imagine these changes are also preferred. @yih-wang @jgiardino 
disabled with this change:
disabled PRIOR TO this change:
enabled with this change:
enabled PRIOR TO this change:
no test impact

fix(17779): misaligned deploy model modal buttons

---

frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunTable.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/restoreModal.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineRuns.cy.ts
frontend/src/concepts/dashboard/DashboardModalFooter.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRowExperiment.tsx
frontend/src/concepts/pipelines/content/useRestoreStatuses.tsx
frontend/src/pages/pipelines/global/runs/RestoreRunWithArchivedExperimentModal.tsx
frontend/src/pages/pipelines/global/runs/RestoreRunsStatusIcon.tsx
frontend/src/pages/pipelines/global/runs/RestoreRunsTableRowExperiment.tsx
frontend/src/pages/pipelines/global/runs/RunsWithArchivedExperimentTable.tsx
frontend/src/pages/pipelines/global/runs/types.ts
frontend/src/pages/pipelines/global/runs/utils.ts
frontend/src/utilities/allSettledPromises.ts

https://issues.redhat.com/browse/RHOAIENG-17134
Allow the archived runs to restore when associated experiments are archived
https://www.figma.com/proto/etbN0ccCcZR1qKCpJXQNAg/Pipeline-phase-2?page-id=12031%3A86470&node-id=14283-127776&viewport=865%2C2037%2C0.08&t=1mf6n88oVojaNlPi-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=14283%3A128060
https://www.figma.com/proto/etbN0ccCcZR1qKCpJXQNAg/Pipeline-phase-2?page-id=12031%3A86470&node-id=14283-128386&viewport=865%2C2037%2C0.08&t=U6y6jJguHHmIlsyk-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=14283%3A128079
https://github.com/user-attachments/assets/302357be-7643-4635-ab66-c52cfd81ec39
https://github.com/user-attachments/assets/4be864bd-e50e-4c5c-b77e-bcc9984d9f97
1. Archive a experiment
2. Try to …

allow to restore archived runs whose associate experiments are archived 

---

frontend/src/__tests__/cypress/cypress/tests/mocked/projects/connections.cy.ts
frontend/src/concepts/modelRegistry/apiHooks/__tests__/usePrefillDeployModalFromModelRegistry.spec.ts
frontend/src/pages/projects/screens/detail/connections/useConnections.ts
frontend/src/utilities/useWatchConnectionTypes.tsx

Enhances https://issues.redhat.com/browse/RHOAIENG-18657 and https://issues.redhat.com/browse/RHOAIENG-18659
Update the OCI feature flag to filter out the ootb connection type. This also removes it from the model serving compatible list check for connections. 
A user could duplicate this and still use OCI though if it's a different name. 
Toggle the feature flag back and forth in the admin page, connections details tab, and model deployment
Most tests are using mocks so no tests have been added

disableKServeOCIModels filters out ootb type

---

frontend/src/concepts/projects/ProjectSelector.tsx
frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
frontend/src/pages/projects/screens/projects/ProjectLink.tsx

1. Closes https://issues.redhat.com/browse/RHOAIENG-12842 Project Selector Overflow onto the next line in the data science pipeline Page in case of a project name with a long name, added a fixed width calculated with calc
**Project Selector Text Overflow** 
2. Resolves Issue related to title overflow onto next line.
**Data Science Pipeline Text Overflow** 
Visually adding screenshots for reference.

FIX : Title and Project Selector Overflow on Data Science Pages 

---

frontend/src/concepts/connectionTypes/__tests__/utils.spec.ts
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/pages/connectionTypes/ConnectionTypesTableRow.tsx
frontend/src/pages/connectionTypes/manage/ManageConnectionTypePage.tsx
frontend/src/pages/modelRegistry/screens/RegisteredModels/usePrefillDeployModalFromModelRegistry.ts
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ConnectionSection.spec.tsx
frontend/src/pages/modelServing/screens/projects/utils.ts
frontend/src/pages/projects/screens/detail/connections/ConnectionsTableRow.tsx
frontend/src/pages/projects/screens/detail/connections/useConnections.ts
frontend/src/utilities/useWatchConnectionTypes.tsx

https://issues.redhat.com/browse/RHOAIENG-20228
Only allow Pull OCI Connections to show up in the Existing Connections part of the ConnectionSection in the deploy kserve model modal. 
* Create a random non-model serving connection type
* Create an instance for S3 connection, URI connection, OCI connection, and the random one you made in a project
* Go to single serving and deploy model
* Existing connections should only show S3, URI, and OCI
* Play around with OCI access type (none selected, pull selected, push & pull selected should show in modal, push only should not show in the modal)
* Make sure other connections deploy properly (S3 and URI)
Edited utils test to check for OCI connections being serving compatible
After …

List only Pull OCI Connections in ConnectionSection

---

frontend/src/concepts/connectionTypes/fields/FileFormField.tsx
frontend/src/concepts/connectionTypes/fields/__tests__/FileFormField.spec.tsx

Closes: [RHOAIENG-20556](https://issues.redhat.com/browse/RHOAIENG-20556)
Allows users to modify the file field contents after upload. Previously the user was only able to view the contents. 
Tested locally on cluster.
- Create a connection that has the option for file upload
- After uploading the file, you should be able to modify and save the contents of the file within the upload box
https://github.com/user-attachments/assets/53de3095-d50f-4889-bb83-9e3588d41eb6

Allow user to edit file field contents

---

frontend/src/concepts/userConfigs/useWatchGroups.tsx

https://issues.redhat.com/browse/RHOAIENG-20458
Notification was returned saying saving would take up to 2 mins.
Reasoning is tied to how we figure out admins (2mins ResourceWatcher cache).
Should be fixed in properly with https://issues.redhat.com/browse/RHOAIENG-16988
Simply use the user management page as any (admin) user. Make a change & save.
Extra verification will need to use impersonate or log in as two different users using the `dev:start:ext` frontend start
N/A

Add back the notification for auth resource updates

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalog.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelDetailsPage.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/registerCatalogModel.cy.ts
frontend/src/pages/modelCatalog/__tests__/utils.spec.ts
frontend/src/pages/modelCatalog/screens/RegisterCatalogModel.tsx
frontend/src/pages/modelCatalog/utils.ts

Closes: [RHOAIENG-21028](https://issues.redhat.com/browse/RHOAIENG-21028) and will fix the modelName prefill, when we register a model from model catalog.
1. Make sure the model name in Register model form prefills names as `modelName-versionNumber` and not just the `modelName`
- To test this:
- Go to Model catalog details page, click on Register model button
- see that the model name prefills as modelName-versionNumber
2. Make sure model details page won't throw error on refresh.
https://github.com/user-attachments/assets/53910268-c054-4f24-9926-670a0b88954f
Tested this on ui-green cluster.
Added, update both unit and cypress tests.

Update encodeParams util and fix modelName prefill in Register model form

---

frontend/src/__mocks__/mockDashboardConfig.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/connections.cy.ts
frontend/src/concepts/areas/const.ts
frontend/src/concepts/areas/types.ts
frontend/src/k8sTypes.ts
frontend/src/pages/projects/screens/detail/connections/useConnections.ts
frontend/src/utilities/useWatchConnectionTypes.tsx

Updates https://issues.redhat.com/browse/RHOAIENG-18657 and https://issues.redhat.com/browse/RHOAIENG-18659 again
based off convo in https://redhat-internal.slack.com/archives/C05SMJ09DD2/p1741194826349979
you can just enable or disable the ootb connection type to toggle this, so this is duplicative and not needed
removed from tests

remove disableKServeOCIModels

---

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineCreateRuns.cy.ts
frontend/src/concepts/pipelines/content/createRun/RunForm.tsx
frontend/src/concepts/pipelines/content/createRun/submitUtils.ts
frontend/src/concepts/pipelines/content/createRun/utils.ts
frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/utils.tsx
frontend/src/concepts/pipelines/kfTypes.ts

https://issues.redhat.com/browse/RHOAIENG-21131
- Update RuntimeConfigParamValue type to allow undefined values
- Modify parameter initialization to use undefined instead of empty string
- Enhance parameter normalization to handle undefined and empty values
- Update validation logic to consider undefined values as valid input
1. Create a new pipeline run
2. Select a pipeline version with numeric parameters
3. Leave numeric parameters empty
4. Submit the form
5. Observe the parameter values in the submitted request
update any broken tests

Fix runtime config parameter handling in pipeline run creation

---

frontend/src/pages/pipelines/global/modelCustomization/startRunModal/MissingConditionAlert.tsx

Closes [RHOAIENG-20675](https://issues.redhat.com/browse/RHOAIENG-20675)
1. Changed the Ilab Pipeline Status message from warning to danger to match the Figma.
2. [Figma Link](https://www.figma.com/design/Pk0BnnzSoaplpGU6jcFX8i/End-to-End---Phase-4?node-id=1362-39785&p=f&t=Wl8L4VKp7GwgzTS6-0)
https://github.com/user-attachments/assets/f38024df-bc62-4f8b-bd33-c476ce6b0e4e
Add the StartRunModal component somewhere in the code and select the projects.
import StartRunModal from '~/pages/pipelines/global/modelCustomization/startRunModal/StartRunModal';
```
<StartRunModal onSubmit={(selectedProject) => {}} onCancel={() => {}} />
```
Visually tested

changed the ilab pipeline status from warning to danger to match Figma

---

.github/workflows/test.yml
frontend/package.json

https://issues.redhat.com/browse/RHOAIENG-20961
Separates the cypress build from each cypress test job and caches the result.
This saves approximately 2mins per cypress test job. 
If we can minimize the time it takes to run the longest running cypress tests, we can benefit more. eg the pipelines cypress tests take over 10 minutes.
An additional 2-3 mins is saved by running unit tests in parallel to cypress tests instead of sequentially.
PR checks
N/A

cache cypress build for improved test execution performance

---

frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDetails.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionDetails.cy.ts
frontend/src/pages/modelRegistry/screens/ModelPropertiesDescriptionListGroup.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/const.ts
frontend/src/pages/modelRegistry/screens/__tests__/utils.spec.ts
frontend/src/pages/modelRegistry/screens/utils.ts

Closes: [RHOAIENG-19017](https://issues.redhat.com/browse/RHOAIENG-19017)
This PR aims to add link to pipeline run from MR version details page.
https://github.com/user-attachments/assets/e9e65a48-5b31-4208-a681-829c1723db7b
- Register a version with a reference to a pipelinerun. You can do this by actually running the InstructLab pipeline, or you can manually add customProperties referencing a pipelinerun. See the issue description for the relevant properties.
- On the version details page, verify that you see the "Registered from" link as shown in the screenshot above and the customProperties referencing a pipelinerun should not present in the properties table, as we filtering them out.
- Click the link to the run and verify that you are taken to the run details page.
- Look at a …

Link pipeline run from MR version details page

---

frontend/src/concepts/projects/ProjectSelectorNavigator.tsx
frontend/src/pages/modelServing/ModelServingContext.tsx

Closes https://issues.redhat.com/browse/RHOAIENG-20051
The `preferredProject` is a thing in the `ProjectsContext` to so a user doesn't always have to reselect their project. It's basically the last project you visited. The global model serving page used `useSyncPreferredProject` and would set the preferred project to the current project you are on (the project name in the url). 
If you tried to set `preferredProject` to something else (like null all projects), it would be overwritten by the current page you are on, never changing. The `preferredProject` logic navigation is used when you nav to the global `/modelServing` without any project, so this is why it was only happening here.
1. go to `/modelServing` (it should be defaulting to "All projects")
2. select a project
3. Select "All …

Fix selecting all projects for global model page

---

frontend/src/concepts/userSSAR/AccessReviewContext.tsx
frontend/src/pages/hardwareProfiles/HardwareProfileEnableToggle.tsx
frontend/src/pages/hardwareProfiles/HardwareProfilesRoutes.tsx
frontend/src/utilities/NavData.tsx

https://issues.redhat.com/browse/RHOAIENG-21069
Shifts the page & navigation to `create` Hardware Profiles to avoid it accidentally listing/visible to basic users.
Add support for the patch toggle (disable the toggle)
UX will need to comment more on the effort for where we will go and proper guidance for read-only values (like the toggle). https://issues.redhat.com/browse/RHOAIENG-21129 will cover the future of those features and come with documentation for the team.
Also spent some time investigating the performance issues -- apparently we didn't cache the values at all fast enough and made a ton of quick "while loading" calls before the state settled. I wrestled with it, tried to also fix the not unloading properly stuff and then ended up in a spot where it's a bit of a mess. I have put …

Improve hardware profiles permission state

---

frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionDeploy.cy.ts
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/concepts/modelRegistry/__tests__/utils.spec.ts
frontend/src/concepts/modelRegistry/utils.ts
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx
frontend/src/pages/modelRegistry/screens/RegisteredModels/useLabeledConnections.ts
frontend/src/pages/modelRegistry/screens/RegisteredModels/usePrefillDeployModalFromModelRegistry.ts
frontend/src/pages/modelRegistry/screens/RegisteredModels/useRegisteredModelDeployInfo.ts
frontend/src/pages/modelRegistry/screens/__tests__/utils.spec.ts
frontend/src/pages/modelRegistry/screens/components/DeployRegisteredModelModal.tsx
frontend/src/pages/modelRegistry/screens/utils.ts
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ProjectSelector.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx

Closes: [RHOAIENG-19258](https://issues.redhat.com/browse/RHOAIENG-19258)
The Deploy model project dropdown should show the info alert and only show projects that have either no model serving platform enabled or single-serving platform enabled(not any modelmesh/multi-serving platform projects). To test this, change any project's model serving platform to multi-model. You should not find this multi-model project in the dropdown.
1. Try deploying any Granite model registered from Model catalog, all have OCI URIs containing `oci://registry.redhat.io`, you will find "Current URI" with the read-only OCI - URI. (You can test this by deploying the version inside "granite-8b-code-base-from-catalog" model on the "mdas" project or any project - a project without any connection and/or project …

Deploy models with OCI from model registry

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts
frontend/src/api/k8s/__tests__/inferenceServices.spec.ts
frontend/src/api/k8s/inferenceServices.ts
frontend/src/k8sTypes.ts
frontend/src/pages/modelServing/screens/projects/utils.ts

Closes https://issues.redhat.com/browse/RHOAIENG-20355
Depends on https://github.com/opendatahub-io/kserve/pull/509 and https://github.com/opendatahub-io/odh-model-controller/pull/382
The backend is moving the auth label to the annotation to align with kserve serverless
Deploy the latest operator image with the latest kserve and model contollers
Deploy kserve raw with public and auth, also check serverless is still normal
Corrected existing tests

fix(serving): change raw label to annotation

---

backend/package-lock.json
frontend/package-lock.json

[RHOAIENG-15596](https://issues.redhat.com/browse/RHOAIENG-15596)
This PR backports two commits, for fixing CVE in cross-spawn in both frontend and backend
Frontend was fixed by dependabot #3490 
Quick check on v2.29.0 shows the vulnerability also exist in frontend so its better to backport it also. 
```
dipgupta@dipgupta-mac frontend % npm audit
cross-spawn  <6.0.6 || >=7.0.0 <7.0.5
Severity: high
Regular Expression Denial of Service (ReDoS) in cross-spawn - https://github.com/advisories/GHSA-3xgq-45jj-v275
Regular Expression Denial of Service (ReDoS) in cross-spawn - https://github.com/advisories/GHSA-3xgq-45jj-v275
fix available via `npm audit fix`
node_modules/cross-spawn
node_modules/npm-run-all/node_modules/cross-spawn
```

[Backport] 2.16 CVE cross-spawn

---

frontend/src/concepts/hardwareProfiles/HardwareProfileSelect.tsx

Closes [RHOAIENG-20551](https://issues.redhat.com/browse/RHOAIENG-20551)
1. On creation of new workbenches for hardware profile dropdown added scrollability.
2. Scrollable prop added to the Hardware Profiles dropdown on notebook creation when there are a lot of hardware profiles available.
https://github.com/user-attachments/assets/d61fd0bb-cee7-49a8-923b-ddbde161fffe
Visually

fix(RHOAIENG-20551):added scrollable prop to the Hardware profiles dropdown

---

frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
frontend/src/pages/projects/screens/detail/connections/ManageConnectionsModal.tsx
frontend/src/pages/projects/screens/detail/connections/usePersistentData.ts

Closes: [RHOAIENG-20546](https://issues.redhat.com/browse/RHOAIENG-20546)
This PR aims to update the prefilled connection type to show respective fields and prefilled connections data to persist, when user changes connection type 
https://github.com/user-attachments/assets/d0d112ce-0b49-4c27-8a03-93497cc88dda
https://github.com/user-attachments/assets/2b2a71ac-8ded-467f-b4bf-e9ecb3bd5f02
1. Navigate to Model Registry
2. Select a registered model
3. Select 'Deploy' via the kebab menu for the version
4. Deploy to a project with no matching connections
5. Switch the connection type and observe that the prefilled data remains from the previous type
6. Also, check that the data will persist if user changes the connection type
Added cypress tests
If you …

Update prefilled connections data to persist correctly

---

frontend/src/__mocks__/mockIlabPipelineVersionParameters.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts
frontend/src/__tests__/cypress/cypress/types.ts
frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/__tests__/validationUtils.spec.ts
frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/validationUtils.ts
frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx
frontend/src/pages/pipelines/global/modelCustomization/ModelCustomizationForm.tsx
frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/PipelineDetailsSection.tsx
frontend/src/pages/pipelines/global/modelCustomization/const.ts

https://issues.redhat.com/browse/RHOAIENG-20529
Added a alert message when the ilab pipeline required parameters are absent
1. Get a pipeline which doesnt contain the required parameters
2. Check for the alert Error message
Added unit test and cypress test

Error handling for incompatible ilab pipeline yaml

---

frontend/src/concepts/connectionTypes/utils.ts
frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/validationUtils.ts
frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx
frontend/src/pages/pipelines/global/modelCustomization/FineTunePageFooter.tsx
frontend/src/pages/pipelines/global/modelCustomization/ModelCustomizationForm.tsx
frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/BaseModelSection.tsx
frontend/src/pages/pipelines/global/modelCustomization/const.ts
frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelConnectionSection.tsx
frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelExistingConnectionField.tsx
frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelNewConnectionContext.tsx
frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelNewConnectionField.tsx
frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelOciPathField.tsx
frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelSection.tsx
frontend/src/pages/pipelines/global/modelCustomization/utils.ts

JIRA: [RHOAIENG-19025](https://issues.redhat.com/browse/RHOAIENG-19025)
Added a section on the ilab form to allow fine-tuned model.
1. It has an existing connection field, which allows users to select all the OCI connections with `PUSH` access type as a field or without any access type
2. It has a new connection field, which allows users to create an OCI connection with all the required fields. It will dry run a secret creation call if the user is creating a new one.
3. It has an optional "Add model to registry" checkbox, to set fields `output_model_name`, `output_model_version`, `output_model_registry_api_url` and `output_model_registry_name` if it's checked.
All the fields are optional expect the secret creation fields, which will be used to create an OCI connection. If a field is not …

Add fine-tuned model section to ilab form

---

frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDetails.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/applications/application.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDetails.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersions.cy.ts
frontend/src/concepts/modelRegistry/context/ModelRegistrySelectorContext.tsx
frontend/src/concepts/modelRegistry/hooks/useModelVersionTuningData.ts
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetails.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsHeaderActions.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionListView.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsTable.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsTableRow.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionsArchive.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionsArchiveListView.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionsArchiveTable.tsx
frontend/src/pages/pipelines/global/modelCustomization/startRunModal/StartRunModal.tsx

Closes [RHOAIENG-19001](https://issues.redhat.com/browse/RHOAIENG-19001) and [RHOAIENG-17782](https://issues.redhat.com/browse/RHOAIENG-17782)
Enabled Fine tune button on the version details page as well as a kebab action
https://github.com/user-attachments/assets/e371bffb-ab53-45bb-8e12-472c4ee6b4e9
https://github.com/user-attachments/assets/9d7c45b2-7e87-47d7-892f-788966738cfc
On shared green cluster. Make sure you have the feature flag on and the configmap.  Go to the version details page and verify that you see the LAB tune button that opens a modal, you can choose juntao as a project option and it will take to to the ilab form.  same on the kebab action for the version 
Will add tests …

Model registry ilab fine tune button on version details, and kebab action on model versions table

---

backend/src/types.ts
frontend/src/__mocks__/mockOdhApplication.ts
frontend/src/pages/exploreApplication/EnableModal.tsx
frontend/src/types.ts
manifests/common/crd/odhapplications.dashboard.opendatahub.io.crd.yaml
manifests/rhoai/shared/apps/nvidia-nim/nvidia-nim-app.yaml

https://issues.redhat.com/browse/NVPE-176
Added NIM-specific API key validation messages during validation in progress.
Tested by enabling the NIM application and verifying that the new message is displayed. Also tested a non-NIM application to ensure the general message 'Validating your entries' is shown correctly.

fix: add NIM specific API key validation messages

---

frontend/src/pages/modelServing/utils.ts
frontend/src/pages/projects/ProjectDetailsContext.tsx

Related to the following:
https://issues.redhat.com/browse/NVPE-154
https://issues.redhat.com/browse/NVPE-156
Fix to ensure tokens consistency after editing and redeploying.
There are 2 main scenarios to be checked:
_Model was initially deployed without any tokens and token authentication was added via edit:_
1. Enable NIM
2. Go to Data Science Project
3. Click on the existing or create a new project
4. Go to models and deploy a model with token authentication unchecked.
5. Edit  the model you created and add token authentication (this will create a token) and redeploy.
6. Make sure the token created is displayed in the dashboard.
_Model was initially deployed with token authentication and another new token was added via edit:_
1. Enable NIM
2. Go to Data Science Project …

fix: ensure tokens consistency after editing and redeploying.

---

frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx

https://issues.redhat.com/browse/NVPE-179
https://issues.redhat.com/browse/NVPE-180
Prevent useEffect from overwriting model server size selection, allowing users to switch options in the dropdown.
- Verified that the **NIM default model server size** is initially set to `'Custom'` with predefined default values that can be modified.  
- Confirmed that users can successfully switch from `'Custom'` to any other available options in the dropdown.  
- Ensured that in **edit mode**, the initial value is retained, and if modified, it correctly displays **NIM Defaults** instead of the generic defaults.  

fix: prevent useEffect from overwriting model server size selection

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersions.cy.ts
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsTableRow.tsx
frontend/src/pages/pipelines/global/modelCustomization/startRunModal/StartRunModal.tsx

Followup to [RHOAIENG-19017](https://issues.redhat.com/browse/RHOAIENG-19017)
cc @YuliaKrimerman 
Prompted by docs comment thread here: https://docs.google.com/document/d/1eHXWp2InljnCW7N3wdWSqc71Gzq_y2vcolxwoCIj6QM/edit?disco=AAABfj1CtpI
cc @ConorOM1 
By preventing the StartRunModal from rendering when `tuningData` isn't defined, we were blocking errors from the artifacts fetch from being rendered anywhere. It is safe to let that modal render even without tuningData because the submit button will be blocked if there is an error.
Force the artifacts fetch to fail (when opening the ilab modal, look in network dev tools for a fetch with a URL ending in `artifacts`, right click it and "block request URL", reload, open the modal again) and see that the modal opens and we get an error rendered …

Show errors when failing to load artifacts for ilab modal

---

frontend/src/pages/hardwareProfiles/HardwareProfiles.tsx

https://issues.redhat.com/browse/RHOAIENG-21526
fixes empty states for when there are no hardware profiles but migrated profiles
get to the state provided in the description and ensure empty state is there
none
@vconzola 

add proper empty state for hardware profile table

---

frontend/src/concepts/pipelines/content/ManageSamplePipelinesModal.tsx
frontend/src/concepts/pipelines/content/configurePipelinesServer/InstructLabPipelineEnablement.tsx
frontend/src/concepts/pipelines/content/configurePipelinesServer/SamplePipelineSettingsSection.tsx
frontend/src/concepts/pipelines/content/import/ImportPipelineSplitButton.tsx

[RHOAIENG-21256](https://issues.redhat.com/browse/RHOAIENG-21256)
Check that area in dashboard and verify the text change
None, just text change
@yannnz @kaedward

InstructLab pipeline upload flow microcopy

---

frontend/src/concepts/pipelines/content/configurePipelinesServer/ObjectStorageSection.tsx
frontend/src/pages/hardwareProfiles/nodeResource/NodeResourceForm.tsx

https://issues.redhat.com/browse/RHOAIENG-20481
• added id to text inputs to remove console errors in the node resource form
• Changed the 'where is my data stored button' to be more user accessible
create a project, go to pipeline server, and press configure pipeline server
simple button change, no tests

converted connection information alert to button

---

backend/src/utils/constants.ts
docs/dashboard-config.md
frontend/src/__mocks__/mockDashboardConfig.ts
frontend/src/concepts/areas/const.ts
manifests/rhoai/shared/odhdashboardconfig/odhdashboardconfig.yaml

Backport NIM flag default value.
Jira: [NVPE-201](https://issues.redhat.com/browse/NVPE-201)
Backported from version 2.18: [NVPE-157](https://issues.redhat.com/browse/NVPE-157), https://github.com/opendatahub-io/odh-dashboard/pull/3747.

fix: set disableNIMModelServing to false as required for GA (#3747)

---

frontend/src/pages/exploreApplication/EnableModal.tsx

JIRA - [https://issues.redhat.com/browse/NVPE-151](https://issues.redhat.com/browse/NVPE-151)
This PR fixes an issue where the `api_key` was being removed when closing the input window before it finished. The key was missing in the resulting Secret. Now, the `api_key` is handled correctly and is not removed unintentionally.
**Before:**
- When the input window was closed before it finished, a Secret was created without any data keys, resulting in a missing `api_key` in the account.
**After:**
- The API key is now properly preserved, even when the input window is closed prematurely.
following these steps:
1. Enabled NVIDIA.
2. Closed the input window before it finished.
3. Verified that the API key is now included in the Secret and no longer missing.
Self checklist (all need …

Fix: Prevent API key from being removed when closing input early

---

frontend/src/__mocks__/mockModelCatalogConfigMap.ts
frontend/src/__tests__/cypress/cypress/pages/modelCatalog/modelCatalog.ts
frontend/src/__tests__/cypress/cypress/pages/modelCatalog/modelDetailsPage.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalog.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelDetailsPage.cy.ts
frontend/src/pages/modelCatalog/__tests__/utils.spec.ts
frontend/src/pages/modelCatalog/components/ModelCatalogCard.tsx
frontend/src/pages/modelCatalog/components/ModelCatalogLabels.tsx
frontend/src/pages/modelCatalog/const.ts
frontend/src/pages/modelCatalog/routeUtils.ts
frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx
frontend/src/pages/modelCatalog/screens/ModelDetailsView.tsx
frontend/src/pages/modelCatalog/screens/RegisterCatalogModel.tsx
frontend/src/pages/modelCatalog/types.ts
frontend/src/pages/modelCatalog/utils.ts
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx
frontend/src/pages/modelRegistry/screens/utils.ts

Closes: https://issues.redhat.com/browse/RHOAIENG-19919
The models in the ModelCatalogSource objects can have special labels on them for InstructLab: `lab-base`, `lab-teacher` and `lab-judge`. We need to detect those labels and give them special treatment wherever they appear in the model catalog (on cards in the overview page and in their section of the details page). These labels:
Should be positioned before other labels
Should be given special colors (see mockups for PF color variables)
Should have their raw value replaced by microcopy
lab-base becomes "LAB starter" with a yellow color
lab-teacher becomes "LAB teacher" with a purple color
lab-judge becomes "LAB judge" with an orangered color.
Also note:
Currently the `tasks` of a model are shown on the card and the `labels` are shown …

Show ilab student/teacher/judge model indicators on models in model catalog

---

frontend/src/__tests__/cypress/cypress/pages/home/home.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/home/home.cy.ts
frontend/src/pages/home/HardwareProfilesHomeHint.tsx
frontend/src/pages/home/Home.tsx
frontend/src/pages/home/HomeHint.tsx
frontend/src/pages/home/LandingPageHomeHint.tsx

https://issues.redhat.com/browse/RHOAIENG-21273
Stashed the home hint banner for hardware profiles for future use. It no longer appears.
set feature flag for hardware profiles and visit the home page. the banner should not appear.
I reverted the cypress tests that enforce their disappearance

stashed home hint banner for hardware profiles

---

frontend/src/components/MarkdownView.tsx
frontend/src/pages/modelCatalog/screens/ModelDetailsView.tsx
frontend/src/utilities/markdown.ts

https://issues.redhat.com/browse/RHOAIENG-21744
downgrading heading levels in model card markdown so that nothing has a higher level than h3. this prevents the a11y issue of having a heading as high or higher than those above it (h2)
locally, green cluster
none, just styling

limit heading level within model card

---

frontend/src/__tests__/cypress/cypress/pages/connections.ts

Fixing the modal title for the page object after we changed the naming during OCI microcopy updates. Ran the e2e test locally and it works.

Fix Connection Create / Delete E2E test

---

.github/workflows/test.yml
backend/package.json
frontend/package.json

Linting was being run twice:
- once as a separate job
- once again alongside unit tests
This PR removes the lint command from the unit test script but also makes it a requirement to pass before starting any test jobs.
PR check
N/A

remove linting from unit test coverage command

---

backend/src/types.ts
backend/src/utils/constants.ts
docs/dashboard-config.md
manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml

closes https://issues.redhat.com/browse/RHOAIENG-21796
The `disableKServeOCIModels` is supposed to be removed, it was removed in the frontend code, but not outside of it. This PR deletes the flag in all the rest
oc apply the crd yaml and check the custom crd in openshift
Misc cleanup so no changes

Remove disableKServeOCIModels in rest of repo

---

frontend/src/__tests__/cypress/cypress/pages/connections.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataSciencePipelines/pipelines.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testMultiModelAdminCreation.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchNegativeTests.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/settings/hardwareProfiles/testWorkbenchTolerations.cy.ts
frontend/src/__tests__/cypress/cypress/utils/models.ts

https://issues.redhat.com/browse/RHOAIENG-20591
- Improve resiliency of Model Serving tests, added a custom Utility that checks multiple times for the Status Tooltip.
- Note that the  testMultiModelAdminCreation is still failing after this resiliency update, but now due to a known bug https://issues.redhat.com/browse/RHOAIENG-20213 and not due to the Status Tooltip issue previously. 
- Remove a number of tests from quarantine that are now passing
- testSingleModelContributorCreation.cy.ts
- pipelines.cy.ts
- Cleaned up test titles and amended titles for tests
- Locally …

Cypress e2e - Model Serving Test Resiliency fix and update Quarantined tests

---

docs/README.md

The previous link was leading to 404

Update architecture docs link

---

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/runs/pipelineRuns.cy.ts

https://issues.redhat.com/browse/RHOAIENG-21797
cypress flake in pipelineRuns.cy.ts, this might be a side effect of mocking the network request only 1 time in the test case
Since this is flaky test this doesnt occurs regularly, run pipelineRuns.cy.ts test file multiple times
Cypress test

cypress flake in pipelineRuns.cy.ts

---

frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts
frontend/src/pages/pipelines/global/modelCustomization/FineTunePageFooter.tsx

Closes [RHOAIENG-21733](https://issues.redhat.com/browse/RHOAIENG-21733)
1. Added refactoring of redirect logic to the Model Registry page in case of state being available from the router state.
2. On state not being available added a fallback usecase of getModelCustomizationPath
https://github.com/user-attachments/assets/3a8ec2af-28ce-4ef6-a90c-7e453d8a78b1
1. Model Registry > select a model version > click on the lab tune button and select the project 
on cancelling the model customization form it would fall back to the model registry page
1. Added intercepts for handling redirection from model registry to model customization form
2. Added test case changes to handle submit form for model customization after redirection from model registry by clicking on labtune button.
3. Added test …

fix(RHOAIENG-21951):added fix for model customization cancel button redirection

---

frontend/src/pages/hardwareProfiles/migration/MigrationModal.tsx

https://issues.redhat.com/browse/RHOAIENG-21735
The text input from the hardware profiles migration modal has been removed.
1. create an accelerator profile
2. go to hardware profiles, click on legacy profiles, and migrate it
3. the modal should show the removed input text box
n/a, small change

removed text input from hardware profile migration modal

---

backend/src/utils/adminUtils.ts

https://issues.redhat.com/browse/RHOAIENG-19355
After updating `getAllowedUserList` to use the Auth CustomResource, the `getUserGroupList` was being passed the `system:authenticated` which is not an actual group on the cluster. In this case we want to filter for any other allowed groups that aren't `system:authenticated`.
Make sure the Admin page loads at Applications > Enabled > Launch Application > Administration
You should see any users that have logged into your cluster in the list
Go to Settings > User management and add a user group to the allowed list
Users in that group should now show up in the Administration tab

Fix page loading error in Jupyter Notebook Admin

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelDetailsPage.cy.ts
frontend/src/pages/modelCatalog/__tests__/utils.spec.ts
frontend/src/pages/modelCatalog/components/ModelCatalogLabels.tsx
frontend/src/pages/modelCatalog/const.ts
frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx
frontend/src/pages/modelCatalog/utils.ts

https://issues.redhat.com/browse/RHOAIENG-21844
lab tune button will only show up on model catalog details page if fineTune is enabled and the model has lab-base label
locally on green cluster
added some tests

fix(21844): only show lab-tune button if lab-base tag

---

frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/connections/testConnectionCreation.cy.ts

Reverts a small change made in [Data Connections clean up](https://github.com/opendatahub-io/odh-dashboard/pull/3846)

Revert a small cypress change from testConnectionCreation

---

frontend/src/pages/modelServing/screens/projects/NIMServiceModal/NIMModelListSection.tsx

JIRA- https://issues.redhat.com/browse/NVPE-218
This PR addresses an issue with selecting models that have versions containing hyphens (e.g., 1.1.0-rtx). The existing logic failed to correctly handle these models, causing errors such as "Model not found" or incorrect image name generation when such models were selected.
This fix ensures that models with hyphenated versions can be selected and processed correctly without errors.
Before-
After-
1. Ensure that NIM is correctly enabled in the environment.
2. Attempt to deploy a model with a version containing -rtx (e.g NeMo Retriever PaddleOCR - 1.1.0-rtx).
3. Verify that no errors related to model name resolution or version parsing appear. …

fix: resolve model selection issues for models with complex version formats

---

frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
frontend/src/pages/modelServing/screens/projects/__tests__/utils.spec.ts
frontend/src/pages/modelServing/screens/projects/utils.ts

Jira: https://issues.redhat.com/browse/NVPE-183
Added an option to select a Storage Class from the NIM deployment UI, with a default option preselected for user convenience.
Tested by selecting a different storage class and verifying that it was correctly applied during deployment. Confirmed successful deployment. Entered edit mode to ensure that the field displays the correct storage class name and remains unchangeable.

Storage class option

---

frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/clusterStorage/testClusterStorageCreation.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/connections/testConnectionCreation.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testMultiModelAdminCreation.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testProjectAdminPermissions.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testProjectContributorPermissions.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchControlSuite.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchEditing.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchNegativeTests.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchStatus.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchVariables.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/workbenches.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/settings/hardwareProfiles/testWorkbenchTolerations.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/storageClasses/clusterStorage.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/topology/pipelinesTopology.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectDetails.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/workbench.cy.ts
frontend/src/pages/projects/components/GenericHorizontalBar.tsx
frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
frontend/src/utilities/useQueryParams.tsx

https://issues.redhat.com/browse/RHOAIENG-21039
Interesting Cypress bug that was based on a product issue that didn't show up as a product bug.
Basically the useEffect in the Horizontal Bar had dual state (one internal and one from the caller). This left the hook triggering twice. Unifying the state and using memoizing aspects it helps it now not trigger the update when the data is not properly set.
Using the Jenkins run job... not possible to see this dev locally or running e2e locally. Tried mocking it but it was heavily inconsistent so I omitted those tests.
https://jenkins-csb-rhods-opendatascience.dno.corp.redhat.com/job/cypress/job/dashboard-tests/926/
Return the old state -- working to satisfy undoing the workaround. …

Fix Cypress Click Issue - Projects Tabs

---

frontend/src/pages/projects/screens/detail/storage/ClusterStorageModal.tsx
frontend/src/pages/projects/screens/detail/storage/ClusterStorageTable.tsx
frontend/src/pages/projects/screens/detail/storage/__tests__/useClusterStorageFormState.spec.ts
frontend/src/pages/projects/screens/detail/storage/submitUtils.ts
frontend/src/pages/projects/screens/detail/storage/useClusterStorageFormState.ts
frontend/src/pages/projects/screens/detail/storage/utils.ts

https://issues.redhat.com/browse/RHOAIENG-21248
Refractor clusterStorageModal
- Check if the functionality remains unchanged
added unit test for custom hooks

refractor clusterStorageModal

---

frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/workbench.cy.ts
frontend/src/components/ExtendedButton.tsx
frontend/src/components/__tests__/ExtendedButton.test.tsx
frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
frontend/src/pages/projects/screens/spawner/connections/ConnectionsFormSection.tsx
frontend/src/pages/projects/screens/spawner/connections/__tests__/ConnectionsFormSection.spec.tsx

See https://issues.redhat.com/browse/RHOAIENG-21536
The proposal is to add an extended button component that, optionally:
- shows a loading skeleton while dependent data is being loaded
- shows an error message in case of errors
- disables the button if a tooltip is provided
With that, standardize the behavior of data-dependent buttons on the spawner page to fix the reported issue.
**No connection/storage available**
https://github.com/user-attachments/assets/169b8ddc-afe7-4db5-bea7-ed6a1d32de8f
**Connection/storage available**
https://github.com/user-attachments/assets/e920eec1-0090-447c-bf17-3e664e4b2dfe
The skeleton is shown while data is being loaded.
Go to Create Workbench page and check the buttons in the Connections and Storage areas
Added unit and mocked Cypress tests to cover the …

Standardize the behavior of data-dependent buttons on the spawner page

---

frontend/src/concepts/__tests__/StartNotebookModal.spec.tsx
frontend/src/concepts/notebooks/StartNotebookModal.tsx
frontend/src/types.ts
frontend/src/utilities/notebookControllerUtils.ts

Closes: [RHOAIENG-21741](https://issues.redhat.com/browse/RHOAIENG-21741) and [RHOAIENG-22056](https://issues.redhat.com/browse/RHOAIENG-22056)
-Removed code that assumed notebook modal events had succeeded based on the most recently successful event.
-Added an additional check for ‘ose-oauth-proxy’ for clarity in differentiating between notebook and oauth events.
-Created a new type that associated events with event milestones -> If the container started, then the image events must have succeeded and so on.
-Added a snippet that loops through the associated events and marks off events based on milestone successes.
-Added optional events and event filtering
-Fixed a typo.
-Tested with npm run test
-Tested locally with successful and broken workbenches.
-If you want to test, open a data …

Adding associated events to workbench status modal

---

frontend/src/app/HeaderTools.tsx

Closes: [RHOAIENG-21393](https://issues.redhat.com/browse/RHOAIENG-21393)
The sun and moon icon colors in the light/dark theme toggle were inconsistent with Patternfly.
**Previously:**
In light mode, both icons were black and in dark mode both icons were white.
**Now:**
The sun is always white and the moon is always black; consistent with Patternfly.
Tested locally:
-Locate the theme toggle switcher
-Toggle the light/dark mode buttons and watch the icon colors

Fixing light/dark toggle icon colors

---

frontend/src/__mocks__/mockDscStatus.ts
frontend/src/__tests__/cypress/cypress/support/e2e.ts
frontend/src/api/useRulesReview.ts
frontend/src/concepts/areas/AreaContext.tsx
frontend/src/concepts/areas/useFetchDscStatus.ts
frontend/src/concepts/modelRegistry/apiHooks/useModelRegistryServices.ts
frontend/src/concepts/modelRegistry/context/ModelRegistrySelectorContext.tsx
frontend/src/concepts/modelRegistry/context/useModelRegistryNamespaceCR.ts
frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx
frontend/src/pages/modelRegistry/ModelRegistryCoreLoader.tsx
frontend/src/pages/modelRegistrySettings/CreateModal.tsx
frontend/src/pages/modelRegistrySettings/ModelRegistriesPermissions.tsx
frontend/src/pages/modelRegistrySettings/ModelRegistrySettings.tsx

Closes https://issues.redhat.com/browse/RHOAIENG-19890
This PR improves error handling when the Model Registry namespace is not configured(Case 1) or when the DSC status returns an empty object(case 2). Previously, we were using fallback empty strings (modelRegistryNamespace || '') which masked the underlying issue and could lead to unexpected behavior.
Key changes:
Removed fallback empty strings - We no longer use modelRegistryNamespace || '' or registriesNamespace || '' in component logic, instead properly handling the undefined case.
Component-specific error handling - Each component that requires the Model Registry namespace now shows a specific error page when the namespace is undefined:
ModelRegistriesPermissions.tsx - Shows an error page when trying to manage permissions …

Fix for when modelRegistryNamespace is undefined and no DSC status in response

---

frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx

https://issues.redhat.com/browse/NVPE-179
Fix to show correct server size instead of defaulting to Custom in Edit mode.
Tested locally. 
- Deployed a model using any option other than "Custom" and verified that, when reopening the form in edit mode, the correct option is displayed instead of defaulting to "Custom".
- Deployed a model using the "Custom" size and confirmed that, upon redeployment, the correct custom values are shown in the form.

fix: show correct server size instead of defaulting to Custom in Edit

---

frontend/src/__tests__/cypress/cypress/pages/hardwareProfile.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/legacyHardwareProfiles.cy.ts
frontend/src/pages/hardwareProfiles/HardwareProfilesTable.tsx
frontend/src/pages/hardwareProfiles/HardwareProfilesTableRow.tsx
frontend/src/pages/hardwareProfiles/const.tsx

https://issues.redhat.com/browse/RHOAIENG-21960
Removed the last modified field from the migrations table, as it doesn't have any functionality.
Go to the hardware profiles page and see the changes.
Removed tests that checked for this field.

removed last modified field in migrations table

---

frontend/src/__tests__/cypress/cypress/pages/components/HardwareProfileSection.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/manageHardwareProfiles.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/workbenchHardwareProfiles.cy.ts
frontend/src/components/ValueUnitField.tsx
frontend/src/concepts/hardwareProfiles/HardwareProfileSelect.tsx
frontend/src/concepts/hardwareProfiles/utils.ts
frontend/src/concepts/hardwareProfiles/validationUtils.ts
frontend/src/pages/hardwareProfiles/__tests__/hardwareProfileWarning.spec.ts
frontend/src/pages/hardwareProfiles/nodeResource/CountFormField.tsx
frontend/src/pages/hardwareProfiles/nodeResource/ManageNodeResourceModal.tsx
frontend/src/pages/hardwareProfiles/nodeResource/NodeResourceForm.tsx
frontend/src/pages/hardwareProfiles/nodeResource/__tests__/utils.spec.ts
frontend/src/pages/hardwareProfiles/nodeResource/utils.ts
frontend/src/pages/hardwareProfiles/utils.ts
frontend/src/utilities/__tests__/valueUnits.spec.ts
frontend/src/utilities/valueUnits.ts

JIRA: https://issues.redhat.com/browse/RHOAIENG-21738
Improve the hardware profile validation error message.
1. When it's not within the range, show the unit
2. Allow users to input empty value, and show a different error message
1. Go to anywhere you can customize a hardware profile size (like workbench spawner page or ilab fine-tune form)
2. Test the CPU and Memory fields, make sure it can show the error message correctly
Added some tests to verify the changes

Improve validation for customized hardware profile size

---

frontend/src/__mocks__/mlmd/mockGetContextsByType.ts
frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/mlmdUtils.ts
frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetArtifactsByRuns.spec.ts
frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useMlmdContextByType.spec.ts
frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useMlmdContextsByType.spec.ts
frontend/src/concepts/pipelines/apiHooks/mlmd/useGetArtifactsByRuns.ts
frontend/src/concepts/pipelines/apiHooks/mlmd/useMlmdContextsByType.ts
frontend/src/concepts/pipelines/content/compareRuns/metricsSection/__tests__/useMlmdPackagesForPipelineRuns.spec.ts
frontend/src/concepts/pipelines/content/compareRuns/metricsSection/useMlmdPackagesForPipelineRuns.ts
frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRun/useMetricColumns.ts
frontend/src/pages/pipelines/global/experiments/compareRuns/CompareRunsMetricsSection.tsx

https://issues.redhat.com/browse/RHOAIENG-21973
Added the `useMlmdContextsByType` hook, which allows for fewer MLMD calls.
Go through the code and see the optimization, where one single call is made instead of many individual ones. Alternatively, you can go to the `Runs` section and inspect network calls. `GetContextsByType` is called only once, but before, `GetContextByTypeAndName` was called many more times, resulting in substantially more MLMD calls.

added optimizations to fetch mlmd contexts in a single call

---

frontend/src/concepts/pipelines/content/import/PipelineFileUpload.tsx

https://issues.redhat.com/browse/RHOAIENG-8111
Updated hardcoded value with Dropzone's ErrorCode enum. 
It's been tested locally.
I created a scenario where the error in question would be thrown (FileTooLarge), and verified that the same error is thrown before and after the change:

Replace hardcoded value with matching ErrorCode enum

---

frontend/src/__tests__/cypress/cypress/tests/e2e/distributedWorkloadMetrics/testWorkloadMetricsDefaultPageContents.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/distributedWorkloads/globalDistributedWorkloads.cy.ts
frontend/src/pages/distributedWorkloads/global/projectMetrics/GlobalDistributedWorkloadsProjectMetricsTab.tsx

Closes https://issues.redhat.com/browse/RHOAIENG-7714 
Added "5" 
On green cluster in comalley-test project
updated the microcopy in the tests as well 

Add "top 5" to DW donut charts

---

frontend/src/__tests__/cypress/cypress/pages/hardwareProfile.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/hardwareProfiles.cy.ts
frontend/src/pages/hardwareProfiles/HardwareProfiles.tsx

closes [RHOAIENG-22649](https://issues.redhat.com/browse/RHOAIENG-22649)
1. Contains mocked cypress test cases for the no hardware profiles case
This PR only adds tests for empty state hardware profile.
This PR only adds tests for empty state hardware profile.

feat(RHOAIENG-22649):added empty state test cases for the hardware profile

---

frontend/src/__mocks__/mockServingRuntimeK8sResource.ts
frontend/src/__mocks__/mockServingRuntimeTemplateK8sResource.ts
frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
frontend/src/__tests__/cypress/cypress/utils/modelServingUtils.ts
frontend/src/api/k8s/servingRuntimes.ts
frontend/src/components/searchSelector/SearchSelector.tsx
frontend/src/concepts/pipelines/content/experiment/ExperimentSelector.tsx
frontend/src/concepts/pipelines/content/pipelineSelector/PipelineSelector.tsx
frontend/src/concepts/pipelines/content/pipelineSelector/PipelineVersionSelector.tsx
frontend/src/concepts/projects/ProjectSelector.tsx
frontend/src/k8sTypes.ts
frontend/src/pages/modelRegistrySettings/CreateMRSecureDBSection.tsx
frontend/src/pages/modelServing/screens/const.ts
frontend/src/pages/modelServing/screens/global/InferenceServiceServingRuntime.tsx
frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
frontend/src/pages/modelServing/screens/projects/utils.ts
frontend/src/pages/modelServing/screens/types.ts

Closes: [RHOAIENG-20300](https://issues.redhat.com/browse/RHOAIENG-20300)
This PR aims to add display project-specific serving runtimes in KServe. Display the project-scoped labels on table and serving runtime dropdown selection.
https://github.com/user-attachments/assets/8d465955-647c-4b0c-ab7c-70905b7b41ef
Note: Needs to add popover, we have that component in this PR: https://github.com/opendatahub-io/odh-dashboard/pull/3955
Make sure that the form is working as expected with/without disableProjectScoped feature flag.
We can check this behavior on:
1. Project details page Models tab
2. Model deployment page
3. Model registry deployment 
Added cypress tests

Display project-specific serving runtimes in dropdown

---

frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionS3FolderPathField.tsx

Closes: [RHOAIENG-2181](https://issues.redhat.com/browse/RHOAIENG-2181)
As per the ticket, the text under the 'path' input was changed from:
'Enter a path to a model or folder. This path cannot point to a root folder.'
to
'Enter a path to your model or the folder containing your model. The path cannot point to a root folder.'
Tested locally
Try it out:
- Open a project and go to the models tab
- If you don't have a model server, configure a model server
- Hit the 'deploy model' button 
- Ensure 'existing connection' is selected (you'll need to have an existing connection)
- Pick an existing connection -> the path input should show up
- Look at the text below the input. It should say "Enter a path to your model or the folder containing your model. The path cannot point to a root folder." …

Update model/folder path helper text

---

frontend/src/pages/modelRegistry/screens/RegisterModel/PrefilledModelRegistryField.tsx
frontend/src/pages/modelRegistry/screens/RegisterModel/RegisterVersion.tsx
frontend/src/pages/modelRegistry/screens/RegisterModel/RegisteredModelSelector.tsx

closes: https://issues.redhat.com/browse/RHOAIENG-13054
make read only fields at the top of create registry and create version just plain text instead of disabled text fields.
create registry:
create version:
create version from model:
local deploy, green cluster
none, mostly a styling change

feat(RegisterModel): 13054 change read only fields to basic text

---

frontend/src/__mocks__/mockModelCatalogConfigMap.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalog.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalogDeploy.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelDetailsPage.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/registerCatalogModel.cy.ts
frontend/src/concepts/modelCatalog/const.ts
frontend/src/concepts/modelCatalog/useModelCatalogSources.ts
manifests/rhoai/shared/apps/model-catalog/kustomization.yaml
manifests/rhoai/shared/apps/model-catalog/model-catalog-rbac.yaml
manifests/rhoai/shared/apps/model-catalog/model-catalog-unmanaged-sources.yaml

closes [RHOAIENG-22483](https://issues.redhat.com/browse/RHOAIENG-22483)
Added a support for additional configmap when the Red Hat source and another one for unmanaged that will have a Third party as a source. We need to make sure we will see both models in 2 different sections on the model Catalog. Make sure 
When testing explore the below scenarios : If it doesn't exist, there's no error rendered, we just see the existing red hat source as expected
If it exists but is malformed, there's an error rendered
If it exists and is empty (sources: [] like in the manifest) we just see the existing red hat source as expected
If it exists and has a source in it, we see two source sections in the UI
Added test cases and fixed failing ones to mitigate working woth 2 configmaps
Self checklist (all …

Support for adding additional unmanaged model catalog sources (second configmap)

---

frontend/src/__mocks__/mockNotebookK8sResource.ts
frontend/src/__tests__/cypress/cypress/pages/workbench.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/workbench.cy.ts
frontend/src/components/ProjectScopedPopover.tsx
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx
frontend/src/pages/projects/screens/detail/notebooks/NotebookImageDisplayName.tsx
frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx
frontend/src/pages/projects/screens/detail/notebooks/useNotebookImage.ts
frontend/src/pages/projects/screens/detail/notebooks/useNotebookImageData.ts
frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
frontend/src/pages/projects/screens/spawner/imageSelector/ImageSelectorField.tsx
frontend/src/pages/projects/screens/spawner/imageSelector/ImageStreamSelector.tsx

Closes: [RHOAIENG-20299](https://issues.redhat.com/browse/RHOAIENG-20299)
Display project scoped workbench images in the dropdown as per [Figma designs](https://www.figma.com/proto/ZvdiudUctzI3HM8W2IHOuT/Project-Enhancements---2025?node-id=6502-12148&p=f&t=nYdiWSDFzrecu3ok-1&scaling=scale-down-width&content-scaling=fixed&page-id=6502%3A12147&starting-point-node-id=6502%3A12148)
Add shared popover component 
Popover:
Dropdown content with selected global and project-scoped labels after selection:
With hardware profile labels on the right(selected and unselected):
While searching a specific image:
Project-scoped label in workbenches table:
Serving runtimes popover if the feature flag is ON and there are project-scoped serving runtimes:
1. Enable the `disableProjectScoped` feature flag and …

Display project scoped workbench images

---

frontend/src/__tests__/cypress/cypress/pages/components/HardwareProfileSection.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/workbenchHardwareProfiles.cy.ts
frontend/src/concepts/hardwareProfiles/HardwareProfileFormSection.tsx
frontend/src/concepts/hardwareProfiles/HardwareProfileSelect.tsx
frontend/src/concepts/hardwareProfiles/useHardwareProfileConfig.ts
frontend/src/concepts/hardwareProfiles/useNotebookHardwareProfileConfig.ts
frontend/src/concepts/hardwareProfiles/useServingHardwareProfileConfig.ts
frontend/src/concepts/hardwareProfiles/utils.ts
frontend/src/pages/hardwareProfiles/migration/useHardwareProfilesByFeatureVisibility.ts
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx
frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingHardwareProfileFormSection.tsx
frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingHardwareSection.tsx
frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx
frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRowHardwareProfile.tsx
frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx

Closes: [RHOAIENG-20301](https://issues.redhat.com/browse/RHOAIENG-20301)
This PR aims to display project-specific Hardware profiles in create workbench form, model serving and ilab form. Display the project-scoped labels on table and hardware profile dropdown selection.
Hardware profile search selector:
https://github.com/user-attachments/assets/211b3411-9551-4e93-b712-e68b6e687d7d
Search hardware profiles:
https://github.com/user-attachments/assets/68043997-860d-46b1-b2eb-4935bda06ee6
Edit form with project-scoped HP:
Displaying project-scoped label for Project-scoped HP and will display custom when the HP is deleted
Edit form, when the HP is deleted:
Deploy model modal:
https://github.com/user-attachments/assets/a3212a20-4d46-455f-bb1c-f6b4c50d3894
ilab form:
Make sure that the form is …

Display project-specific hardware profiles in dropdown

---

frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectDetails.cy.ts
frontend/src/__tests__/cypress/cypress/utils/mockUsers.ts
frontend/src/concepts/projects/accessChecks.tsx
frontend/src/pages/projects/screens/detail/ProjectActions.tsx
frontend/src/pages/projects/screens/projects/useProjectTableRowItems.ts

Closes: [RHOAIENG-18968](https://issues.redhat.com/browse/RHOAIENG-18968)
Corrected a permission bug that always blocked the user from seeing the actions toggle. 
When logged in as a non-admin user, you should now be able to see the Actions dropdown option for projects you’ve created. It should still be hidden for projects created by the Admin.
I’ve also created a new file for this permission check to help with future usage
Tested locally as a non-admin user
Before (Actions dropdown hidden):
After (Actions available):

Permission fix for project users

---

frontend/src/app/App.scss

https://issues.redhat.com/browse/RHOAIENG-23563
Added temporary style override to `App.tsx` until https://github.com/patternfly/patternfly/issues/7452 is resolved.
Before:
After:
N/A, style changes only.
N/A, style changes only.

Fix PF 6.2.0 Style Error with Page Component

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistrySettings/modelRegistrySettings.cy.ts
frontend/src/pages/modelRegistrySettings/CreateMRSecureDBSection.tsx

Closes https://issues.redhat.com/browse/RHOAIENG-17869 
Navigate to Settings > Model registry settings
Create a model registry and select the 'Add CA certificate to secure database connection' option
Select Choose from existing certificates
Search for a Secret or ConfigMap that is only available in one or the other
Verify that now only one of the groups is there for particular values 
Before 👎 
After 👍 
On green cluster as described
No test effect 

Fix Resource certificate group not hidden correctly

---

frontend/src/__tests__/cypress/cypress/pages/modelCatalog/registerCatalogModel.ts
frontend/src/__tests__/cypress/cypress/pages/modelRegistry/registerModelPage.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/registerCatalogModel.cy.ts
frontend/src/pages/modelCatalog/screens/RegisterCatalogModel.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetails.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionsArchive/ArchiveModelVersionDetailsBreadcrumb.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionArchiveDetailsBreadcrumb.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionsArchive.tsx

Closes: [RHOAIENG-21958](https://issues.redhat.com/browse/RHOAIENG-21958)
This PR aims to update the breadcrumb and model name when registering model from catalog
1. Navigate to Model Catalog
2. Select the model granite-3.1-8b-lab-v1
3. Click 'Register Model'
4. Observe the error in the breadcrumb & model name 

Update breadcrumb and model name when registering model from catalog

---

frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionPipelineDescription.tsx

https://issues.redhat.com/browse/RHOAIENG-23666
This PR fixes the dark mode styling issue for the "Registered from" link in the Model Registry's Model Version Details view. The current implementation doesn't properly handle dark mode theming, making the link difficult to read. The fix implements proper PatternFly theme variables to ensure consistent visibility and styling in both light and dark modes.
Changes made:
- Added PatternFly theme variable `--pf-t--global--link--Color` for link color
- Removed default text decoration for cleaner appearance
- Maintained bold font weight using PatternFly theme variable
Testing was performed in the following environments:
- Local development environment
- Browser: Chrome and Firefox
- Both light and dark mode settings
Testing steps:
1. Open Model …

[RHOAIENG-23666] Fix dark mode styling for "Registered from" link in Model Registry

---

frontend/src/concepts/pipelines/content/tables/experiment/ExperimentTableRow.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTableRow.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx
frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx

Closes [RHOAIENG-23406](https://issues.redhat.com/browse/RHOAIENG-23406)
1. Removed the datalabel property for kebab menus in table as on mobile screens it shows up as a label.
1. Visually

Fix(RHOAIENG-23406): Datalabel removal for kebab menus

---

frontend/src/app/useApplicationSettings.tsx

JIRA: [RHOAIENG-22859](https://issues.redhat.com/browse/RHOAIENG-22859)
The problem in the ticket is because the editing page for the legacy hardware profiles keeps resetting to the old value every few seconds. The value could just be reset when the user migrates the hardware profile.
Tracing it back, I found the `existingHardwareProfile` that's passed to the editing page is not reference-stable. Thus it keeps triggering the initial form value setting hook.
Then tracing it back more, I found the `refresh` function in `useApplicationSettings` is not using `React.useCallback`, thus it's not reference stable. However, it's used as the dependency when we create the `migratedHardwareProfiles`.
Make it reference-stable fixes the issue.
1. Go to the hardware profile settings page
2. Edit a …

Fix resetting issue when editing a legacy hardware profile

---

backend/src/utils/proxy.ts

PR https://github.com/opendatahub-io/odh-dashboard/pull/3799 refactored the backend `proxyService` so that setting the `Bearer` token header is factored into a new common util called `setAuthorizationHeader`. In the `doServiceRequest` function within `proxyService`, the old code had an `await` and the new code does not, so it calls `done()` before the header is set and the proxy request proceeds without the Bearer token. This is leading to features that rely on the service proxy like Model Registry not working.
cc @christianvogt 
(TODO - will test with the PR image)
No tests in the backend :(

Await auth helper before completing proxy service request

---

frontend/src/__tests__/cypress/cypress/pages/workbench.ts
frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx
frontend/src/pages/projects/screens/detail/notebooks/data.ts

https://issues.redhat.com/browse/RHOAIENG-24100
Changed the table name to `Workbench Image`
Navigate to `Projects` and then go to the `Workbenches` tab
Fixed existing Cypress tests

Updated workbench terminology in project section

---

frontend/src/__tests__/cypress/cypress/pages/clusterSettings.ts
frontend/src/pages/clusterSettings/CullerSettings.tsx
frontend/src/pages/clusterSettings/PVCSizeSettings.tsx
frontend/src/pages/clusterSettings/TolerationSettings.tsx

https://issues.redhat.com/browse/RHOAIENG-24102
Edited the cluster settings terminology.
Go to the cluster settings page in the sidebar
N/A, simple microcopy change

changed terminology for cluster settings

---

frontend/src/components/ProgressBarWithLabels.tsx
frontend/src/pages/distributedWorkloads/components/WorkloadResourceUsageBar.tsx

https://issues.redhat.com/browse/RHOAIENG-6500
The usage bar is now horizontally aligned in distributed workload resource metrics
- Run the distributed workload having a jobd which has some requested cpu and memory
- Go to the project tab and check if all the usage bar are aligned horizontally 
N/A Just a width change 

Horizontally align usage bar in distributed workload resource metrics

---

frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/RequestedResourcesBulletChart.tsx

https://issues.redhat.com/browse/RHOAIENG-17069
This fixes the distortion of tooltip in memory chart under the `Project Metrics` tab in the distributed workload pages
Before:
After the changes:
- Go to distributed workload page under the `project metrics` tab on the requested resources card, check the tooltip if its not distorted
N/A
cc @kywalker-rh 

the tooltip arrow doesnot look distorted in memory chart

---

frontend/src/pages/pipelines/global/modelCustomization/landingPage/ModelCustomization.tsx

addition to: https://issues.redhat.com/browse/RHOAIENG-22899
adjusting width to be consistent.
before change:
after change:
viewed the page; this is just a style/width/css change. extremely minor
so minor; no tests needed

adjusting width for the top description too

---

frontend/src/api/trustyai/rawTypes.ts
frontend/src/pages/modelServing/screens/metrics/__tests__/utils.spec.ts
frontend/src/pages/modelServing/screens/metrics/bias/BiasConfigurationPage/BiasConfigurationModal/ManageBiasConfigurationModal.tsx
frontend/src/pages/modelServing/screens/metrics/utils.tsx

Issue: https://issues.redhat.com/browse/RHOAIENG-2688
- modified BaseMetricRequestInput property types
- fixed errors from changing BaseMetricRequestInput in trustyai api rawTypes
- Existing tests were ran and showed success.
- addtional tests were added for convertInputType function
Unit test cases were added for convertInputType

Fix types related to TrustyAI service

---

manifests/core-bases/base/cluster-role.yaml
manifests/core-bases/base/role.yaml

Closes [RHOAIENG-16858](https://issues.redhat.com/browse/RHOAIENG-16858)
**Updating service account permissions:
Role updates:**
batch -> GET, UPDATE / cronjobs -> Enabled/Explore tiles
build.openshift.io -> LIST / builds, buildconfigs -> List build statuses of images
**Cluster-Role updates:**
rbac.authorization.k8s.io -> LIST, GET / rolebindings, clusterrolebindings, roles -> Secure admin route general infrastructure -> and standalone workbench
Tested using devFlags for manifest changes on my cluster side by side with another cluster with unchanged SA permissions.
Homepage: same
Projects pages: same (pipeline stuff broken as expected, ignore)
DSP Page: same
Model Registry: ignore
Deploy Models: same
Pipelines: ignore
Experiments: ignore
DW: Not configured on either cluster but showing up …

Updating SA permissions

---

frontend/src/__tests__/cypress/cypress/pages/home/homeModelCatalog.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/home/homeModelCatalog.cy.ts
frontend/src/concepts/modelCatalog/const.ts
frontend/src/concepts/modelCatalog/content/ModelCatalogCard.tsx
frontend/src/pages/home/modelCatalog/ModelCatalogSection.tsx
frontend/src/pages/home/projects/ProjectsLoading.tsx

https://issues.redhat.com/browse/RHOAIENG-22050
Show the featured models in the homepage model catalog section
- Load models with the 'featured' label from the model catalog configmap
- Loading spinner while data's loading
- Error thrown in case of errors
- Hide entire section when no featured models
Featured models (related to https://github.com/opendatahub-io/odh-dashboard/pull/4083)<sup>:star:</sup>: 
- RH Student/starter: Granite 3.1 8B Base - starter
- RH * Teacher: *Mixtral 8x7B Instruct - v0.1
- RH judge: Prometheus 8x7b - v2-0
- RH Starter: Granite 7b starter - 1.4.0
https://github.com/user-attachments/assets/2feaa3f5-76da-4318-bdd8-d9be650600ae
https://github.com/user-attachments/assets/96c47aa4-f8f7-442d-a83f-310aaf6fb8b5
- Manually updated model catalog configmap in the cluster …

Integrate featured models into the model catalog homepage section

---

frontend/.eslintrc
frontend/babel.config.js
frontend/package-lock.json
frontend/package.json
frontend/src/app/App.tsx
frontend/src/plugins/ExtensibilityContext.tsx
frontend/src/plugins/LazyCodeRefComponent.tsx
frontend/src/plugins/__tests__/extensions.spec.ts
frontend/src/plugins/__tests__/pluginStore.spec.ts
frontend/src/plugins/extension-points/index.ts
frontend/src/plugins/extensions.ts
frontend/src/plugins/internal/coderefs.ts
frontend/src/plugins/internal/objects.ts
frontend/src/plugins/plugin-store.ts
frontend/src/plugins/useExtensions.ts
frontend/src/plugins/useResolvedExtensions.ts

https://issues.redhat.com/browse/RHOAIENG-23185
This PR introduces extension points mechanism to ODH.
It re-uses the `@openshift/dynamic-plugin-sdk` where possible. It doesn't utilize it entirely because I did not want to introduce a build aspect to this mechanism. Also by not utilizing the existing library as is, we can benefit from creating code refs in typescript and benefit from the types through dynamic import support for code refs.
There was some code copied and changed from the dynamic-plugin-sdk (eg. `useResolvedExtensions`) because internally it uses a symbol which we cannot reproduce.
How to use:
- Create new extension point files in the `src/plugins/extension-points/` directory. 
- Re-export the extension points from the `src/plugins/extension-points/index.ts` file.
- Add …

introduce extension points to ODH

---

frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalogDeploy.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts
frontend/src/__tests__/cypress/cypress/utils/modelServingUtils.ts
frontend/src/concepts/modelCatalog/content/ModelCatalogLabels.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx

Closes: [RHOAIENG-23292](https://issues.redhat.com/browse/RHOAIENG-23292)
This PR aims to load the data fully before rendering deploy form, when deploying a model from model catalog and model registry.
1. Model catalog
https://github.com/user-attachments/assets/370cd733-5983-492f-9b8f-2403dd4a6817
2. Model Registry with kServe
https://github.com/user-attachments/assets/c6ccd7c6-7c91-4e30-b357-a5059e410e9e
3. Model registry with model mesh
https://github.com/user-attachments/assets/d746b286-fb38-4b55-9ca8-2a3b9a701135
1. deploy a model from model catalog, make sure spinner is displayed and data is loaded before the form renders.
2. Same goes for model registry.(check for both single and multi model platform)
3. Also, check for model deployment page  - this should work as expected.
Added …

Load data before rendering Deploy form, when deploying from model catalog or registry

---

backend/.eslintrc
frontend/.eslintrc
frontend/src/__tests__/cypress/cypress/tests/mocked/applications/application.cy.ts
frontend/src/app/__tests__/AboutDialog.spec.tsx
frontend/src/concepts/topology/PipelineVisualizationSurface.tsx
frontend/src/pages/modelRegistrySettings/CreateModal.tsx
frontend/src/pages/modelServing/screens/projects/DeployPrefilledModelModal.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/EnvironmentVariablesSection.tsx
frontend/src/pages/projects/notebook/NotebookStateStatus.tsx

Issue: https://issues.redhat.com/browse/RHOAIENG-23621
- added no-non-null-assertion to eslint config in both frontend and backend package.json files
- fixed resulting linting errors
Existing tests were ran and all passed.
No additional tests were added.

[Tech debt] Add eslint no-non-null-assertion rule to config

---

frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
frontend/src/pages/modelServing/screens/projects/__tests__/usePrefillModelDeployModal.spec.ts
frontend/src/pages/modelServing/screens/projects/useLabeledConnections.ts
frontend/src/pages/modelServing/screens/projects/usePrefillModelDeployModal.ts
frontend/src/pages/projects/dataConnections/const.ts

closes [RHOAIENG-21303](https://issues.redhat.com/browse/RHOAIENG-21303)
Scenarios Included:
1. When Deploying any model registered using an OCI - URI but not containingoci://registry.redhat.io, you will find "Existing connection" with the fields filled. When you click on the connection name dropdown, you should see the "Recommended" label as shown in the screenshot.(You can test this by deploying the version inside "oci-model" model on the "mdas" project - you should see "Existing connection" preselected and fields filled [ui-green](https://console-openshift-console.apps.ui-green.dev.datahub.redhat.com/) cluster)
The recommended label will now be based on whether the connection includes a Pull request selected in the connection type as seen in the screenshot below even though we have …

fix(RHOAIENG-21303): added default pull access type connection, test cases and recommended connection type 

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts
frontend/src/pages/modelServing/screens/projects/__tests__/usePrefillModelDeployModal.spec.ts
frontend/src/pages/modelServing/screens/projects/usePrefillModelDeployModal.ts

https://issues.redhat.com/browse/RHOAIENG-22645
When we deploy a model (created with uri-connection type) via model registry to a project with no matching connection types, we will prefill the uri field. switching it to OCI - check if the oci field is not prefilled by same uri
https://github.com/user-attachments/assets/fa6ad1ad-b9c4-4feb-90df-c9f89da54d64
- Navigate to Model Registry
- Register a new model using a URI connection type
- Select Deploy for the model version
- Choose a project with no matching connection types
- URI connection will be prefilled, switch to OCI and observe that the uri model location doesnt prefills the OCI storage location
Updated unit test

OCI storage location is not prefilled with URI

---

frontend/.eslintrc
frontend/src/components/NumberInputWrapper.tsx
frontend/src/concepts/pipelines/content/createRun/contentSections/TriggerTypeField.tsx
frontend/src/pages/notebookController/screens/server/AcceleratorProfileSelectField.tsx

Closes: [RHOAIENG-22660](https://issues.redhat.com/browse/RHOAIENG-22660)
Replaces the remaining uses of `NumberInput` with `NumberInputWrapper`. Also adds a eslint rule to flag future imports of `NumberInput`
Tested locally, all functionality remains the same. Also tested with `npm run test` for the eslint rule

Clean up remaining uses of NumberInput

---

manifests/core-bases/base/cluster-role.yaml
manifests/core-bases/base/role.yaml

Quick fix adding 'create' back into rbac.authorization.k8s.io for the cluster role.
After it's removal, attempting to create a standalone jupyter workbench if `opendatahub-image-pullers` didn't exist or was deleted, would result in an error. The SA account needs `create` to create a rolebinding if one doesn't exist.
Tested on my cluster
If you want to try it:
-Point your dsc dashboard devflags at this branch: `https://github.com/katieperry4/odh-dashboard/tarball/SA-Fix`
-Find the opendatahub-image-pullers rolebinding in the opendatahub namespace
-Delete it
-Open ODH
-Try to launch a standalone workbench
If you want to see the broken version (if this hasn't merged yet) point the devFlags at main
-Delete the opendatahub-image-pullers rolebinding in the opendatahub namespace
-Try to launch a …

Update SA Permissions Part Two

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDetails.cy.ts
frontend/src/concepts/modelRegistry/__tests__/utils.spec.ts
frontend/src/concepts/modelRegistry/types.ts
frontend/src/concepts/modelRegistry/utils.ts

Quick followup to #4072 to just use a different value for the `modelSourceKind` when a model is registered from a pipelinerun. [From this slack thread](https://redhat-internal.slack.com/archives/C07J39USZND/p1745865045331399?thread_ts=1744228165.050079&cid=C07J39USZND), instead of `"dsp"` (Data Science Pipelines) we'll use `"kfp"` (KubeFlow Pipelines).
cc @YuliaKrimerman 
Ensured existing tests still pass.
N/A

Followup to #4072: Change 'dsp' to 'kfp' in the ModelSourceKind logic

---

frontend/src/concepts/modelCatalog/__tests__/useModelCatalogSources.spec.ts

closes [RHOAIENG-24224](https://issues.redhat.com/browse/RHOAIENG-24224)
Added unit test to cover that test file
run npm run test and make sure all the tests are passing
Added the unit test, no other test changes happened

Added unit test for useModelCatalogSources.ts

---

frontend/src/__mocks__/mockInferenceServiceK8sResource.ts
frontend/src/concepts/notificationWatcher/NotificationWatcherContext.tsx
frontend/src/concepts/notificationWatcher/__tests__/NotificationWatcherContext.spec.tsx
frontend/src/concepts/pipelines/content/ManageSamplePipelinesModal.tsx
frontend/src/pages/modelServing/screens/global/__tests__/utils.spec.ts
frontend/src/pages/modelServing/screens/global/utils.ts
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ManageInferenceServiceModal.spec.tsx
frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
frontend/src/pages/modelServing/screens/projects/useModelDeploymentNotification.ts
frontend/src/pages/pipelines/global/modelCustomization/FineTunePageFooter.tsx

Closes: [RHOAIENG-553](https://issues.redhat.com/browse/RHOAIENG-553)
-Adds a notification when model deployment fails. The notification pops up in the corner on whatever page the user is on and goes into the notification sidebar. 
-Added an enum to useNotificationWatcherContext for NotificationResponseStatus and updated all usages.
**Popup notification:**
**Notification sidebar:**
**Deployment status:** Where 'View deployment' redirects to (unchanged but I thought I'd show it, there's already a [ticket](https://issues.redhat.com/browse/RHOAIENG-2478) for the status message (which is only applicable to single-model serving)
**If you want to test this:**
- Navigate to or create a data science project. (The fastest way I've found is with multi-model …

Model Deployment Failure Notification

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
frontend/src/pages/modelServing/screens/projects/utils.ts

Closes: [RHOAIENG-22646](https://issues.redhat.com/browse/RHOAIENG-22646)
This update changes the default behavior for the connection radio buttons when deploying a model. Before, it defaults to existing connection, even if there aren’t any connections to choose from. Now, if there are no connections available, the option won’t show at all and you will only have to option the create a new connection. If there are connections available, it will continue to default to existing. 
Tested locally
- Navigate to your data science projects, and to the Models tab. 
- Ensure that you have no existing connections, then click deploy model. 
- The existing radio option shouldn't be visible, and you should only see the option for Connection type.
- If you go back and create a connection and then return …

Update default connections radio

---

frontend/src/pages/modelCatalog/screens/ModelCatalog.tsx
frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx

Closes [RHOAIENG-24514](https://issues.redhat.com/browse/RHOAIENG-24514)
When navigating from the model catalog overview page to a model's details page, the scroll position was being maintained from the previous page. This meant that if a user had scrolled down on the overview page and then clicked on a model, they would land in the middle of the model's readme content instead of seeing the top of the page with the model's title and action buttons. This behavior was confusing users during testing of third-party models.
- Added `ScrollViewOnMount` component to both `ModelCatalog` and `ModelDetailsPage` components
- The component automatically scrolls to the top of the page when mounted, ensuring users always see the top of the page when navigating between model catalog pages
- This …

fixed scrolling issue between Model Catalog and Model Catalog details page 

---

backend/src/routes/api/integrations/nim/index.ts
backend/src/routes/api/integrations/nim/nimUtils.ts
backend/src/types.ts
frontend/src/utilities/useEnableApplication.tsx

https://issues.redhat.com/browse/NVPE-243
Change to check lastAccountCheck and isEnabled status instead of relying on APIKeyValidation, so the 'Enable' button would reflect the account availability. 
Verified that the 'Enable' button does not prematurely disappears as soon as APIKeyValidation status changes while the reconciliation is still in progress.
After entering the API key, once the "Enable" button disappears, the application should now correctly appear on the Enabled page.
Prior to this change, the disappearance of the "Enable" button only indicated that validation was complete, but the application remained disabled on the Enabled page.

fix: check lastAccountCheck

---

frontend/src/pages/modelServing/screens/projects/__tests__/usePrefillModelDeployModal.spec.ts
frontend/src/pages/modelServing/screens/projects/usePrefillModelDeployModal.ts

Issue: https://issues.redhat.com/browse/RHOAIENG-24410
* added `hasPrefilledRef` to make sure prefill happens once.
* fixed up unit test
- tested manually
- also added unit tests
Screen Recording: https://github.com/user-attachments/assets/ac047d22-a5d7-4cb2-89c8-cb8a92adc3dd
Unit test was updated and all are passing.

Connection type switches from create new connections to current uri, when we deploy a model from model catalog

---

frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionOciPathField.tsx

https://issues.redhat.com/browse/RHOAIENG-24886
Fixing a blocker bug that causes the url prefix to be submitted when pasting into the input since the `onChange` is not triggered when you paste and blur the field.
Manually test. See Jira for more details.
1. Go to deploy an oci model (can create the connection first or do it in model)
2. for the oci path paste in your url with a prefix (`http://`, `https://`, `oci://`, etc)
3. Click submit or click away (blur the field) and then submit
Both should submit the proper inference service (check the storageUri field on the ISVC). storageUri should always have an `oci://` prefix

Fix http prefix removal for OCI path

---

frontend/src/__tests__/cypress/cypress/tests/mocked/home/homeModelCatalog.cy.ts
frontend/src/pages/home/modelCatalog/ModelCatalogSection.tsx
frontend/src/pages/home/modelCatalog/ModelCatalogSectionFooter.tsx

https://issues.redhat.com/browse/RHOAIENG-24492
The homepage model catalog section displays models with `featured` labels only, and the count in the footer would display either `Showing all models` if all featured models are showing, or `Showing 3 of all models` if only 3 featured models are showing and some other featured models aren't displayed. 
From a user perspective, all the models shown are the same as  in `/modelCatalog`, so if there are 11 models in `/modelCatalog`, it doesn't make sense to show `Showing all models` in the footer because the user can only see the featured models. Therefore, if there are 11 models in total and only 4 of them are displayed, the footer should show `4 of 11 models` and not `Showing all models`. 
Before:
After:
- Navigate to homepage
- Check the …

Homepage Model Catalog: Include non-featured models in footer total model count

---

frontend/src/pages/home/modelCatalog/ModelCatalogSectionHeader.tsx

https://issues.redhat.com/browse/RHOAIENG-24897
The Model catalog icon background color should be teal to remain consistent with the model catalog page and not orange as currently implemented. This is due to section type being set to `organize` instead of `training`.
On the homepage, check that the model catalog icon has a teal background color instead of orange.
Checked visually in local run. 

Fix Model catalog icon background to teal instead of orange

---

frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx

Closes: [RHOAIENG-22646](https://issues.redhat.com/browse/RHOAIENG-22646)
Fixes small bug found in this PR - https://github.com/opendatahub-io/odh-dashboard/pull/4056
There was an issue where if a connection already existed and was pre-selected, and the user clicked new connection, the new connection name would be auto filled with the name of the existing connection. 
Tested locally
- Navigate to your data science projects, and to the Models tab.
- Ensure that you have one existing connection, then click deploy model.
- In the model window, the existing connection should be pre-selected. Click create connection
- The new connection name field should be blank

Small fix for connections radio

---

frontend/src/__tests__/cypress/cypress/pages/home/homeModelCatalog.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/home/homeModelCatalog.cy.ts
frontend/src/concepts/modelCatalog/content/ModelCatalogCard.tsx

https://issues.redhat.com/browse/RHOAIENG-24491
The `Truncate` component was wrapped in a `Link`, which interfered with the `Tooltip` event listeners inside `Truncate`, which in turn caused the `Tooltip` not to show up. Switching `Link` with `Button` doesn't seem to have that problem. 
https://github.com/user-attachments/assets/f80d6cc9-d6f4-4709-b0e9-fca181b264c3
_Note: After the above changes, there might still be cases when the text is truncated but the tooltip isn't displayed on mouseover. In `Truncate`, the logic for adding truncation to the text and changing the display state of the tooltip are separate, therefore there are cases when the text is truncated but the display state for the tooltip is not switched to 'visible' on mouseover._
Navigate to the homepage:
- In the model …

Model catalog homepage: fix issue of tooltip not showing during mouseover

---

frontend/src/__tests__/cypress/cypress/pages/appChrome.ts
frontend/src/__tests__/cypress/cypress/support/commands/application.ts

Convert `findAppNavItem` to a custom query. This will allow cypress to retry the query until it succeeds. This is necessary because async behavior of nav item loading due to the evaluation of access review checks can fail due to timing issues.
Cypress tests.
https://jenkins-csb-rhods-opendatascience.dno.corp.redhat.com/job/cypress/job/dashboard-tests/1434/
N/A

Fix cypress app nav utility to address failures in e2e tests

---

frontend/src/__tests__/cypress/cypress/support/e2e.ts

https://issues.redhat.com/browse/RHOAIENG-24885
This PR adds a new environment variable, `CY_TEST_TIMEOUT_SECONDS`, to set a global timeout for `it` tests in Cypress. The value is specified in seconds and is converted to milliseconds for compatibility with Cypress's `testTimeout` setting.
Usage example: 
`npm run --prefix frontend cypress:run -- --env CY_TEST_TIMEOUT_SECONDS=30`
Only those tests that exceeded 30 seconds will stop due to the timeout limit:
In addition, this PR fixes a problem when `grepTags` includes tags that do not exist in the actual test files, but e2e.ts was still executing those tests `Before` and `After` steps, instead of skipping those steps.
Tested by running Cypress with various values for `CY_TEST_TIMEOUT_SECONDS` to ensure the timeout is applied correctly to …

Cypress --env option to set tests timeout: CY_TEST_TIMEOUT_SECONDS  

---

frontend/src/__tests__/cypress/cypress/pages/workbench.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/workbench.cy.ts
frontend/src/components/GenericSidebar.tsx
frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx

Closes [RHOAIENG-17334](https://issues.redhat.com/browse/RHOAIENG-17334)
There was a bug where if you clicked the sidebar items when creating/editing a workbench and then hit cancel, you'd have to hit cancel however many times as sidebar items clicked +1 to get back to the workbenches tab.
(there's a video of it in the ticket)
The navigation was fixed and I added some cypress tests for testing the cancel button.
Added cypress tests
**If you want to test:**
- On a branch or cluster without this fix, go make/edit a workbench and click around the sidebar items and then try to hit cancel -> it'll take a few clicks to actually cancel.
- Now go to this branch with the fix, go make/edit a workbench and click around the sidebar items and then try to cancel …

Workbench Cancel Button Bug Fix

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
frontend/src/pages/modelServing/screens/const.ts
frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx
frontend/src/pages/modelServing/screens/projects/__tests__/utils.spec.ts
frontend/src/pages/modelServing/screens/projects/utils.ts

Closes [RHOAIENG-15829](https://issues.redhat.com/browse/RHOAIENG-15829)
The serving platform change button would only appear if there was more than one platform enabled. If you had a project using modelMesh and modelMesh got disabled, you'd be stuck with an error on the models tab saying "Multi-model platform is not installed" and unable to switch to kServe.
I added a util to see if the current platform is enabled, if it's not, show the change button and change the label to say the current platform is disabled.
**Previously:**
**Now:**
If you want to test it: (using kServe in this example but the same can be done for modelMesh)
- Create or open a project with no models.
- Select single-model serving -> don't serve a model.
- Open the openshift …

Serving Platform Change Button Bug Fix

---

frontend/src/__tests__/cypress/cypress/utils/storageClass.ts

https://issues.redhat.com/browse/RHOAIENG-25189
Fix ClusterStorage provision bug found during the nightly exectution.
Command used:
`$ npx cypress run --browser chrome --project src/__tests__/cypress --spec src/__tests__/cypress/cypress/tests/e2e/storageClasses/clusterStorage.cy.ts`
It does not make sense to run a pipeline in this case, as for checking that the error is not happening anymore there's a setup needed
So I've tested both cases: With the setup (green) and a regular execution (green too)
Total impact as it's a fix for a test.
Run the tests locally

fix: clusterStorage bug during provision

---

frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/permissions.cy.ts
frontend/src/__tests__/cypress/cypress/utils/mockUsers.ts
frontend/src/concepts/projects/accessChecks.tsx
frontend/src/pages/projects/projectSettings/ProjectSettingsPage.tsx
frontend/src/pages/projects/screens/detail/ProjectDetails.tsx

Closes: [RHOAIENG-23534](https://issues.redhat.com/browse/RHOAIENG-23534)
Makes updates to improve how some of our project permissions are handled. Moves additional checks into `accessChecks.tsx` to allow them to be reusable for future projects.
Tested locally as a user 
No tested changed

Improvements to project permissions

---

frontend/src/__tests__/cypress/cypress/pages/components/Modal.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/archiveModal.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineImportModal.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineVersionImportModal.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/restoreModal.ts
frontend/src/app/DevFeatureFlagsBanner.tsx
frontend/src/concepts/connectionTypes/ConnectionTypePreviewModal.tsx
frontend/src/concepts/pipelines/content/ArchiveModal.tsx
frontend/src/concepts/pipelines/content/ManageSamplePipelinesModal.tsx
frontend/src/concepts/pipelines/content/RestoreModal.tsx
frontend/src/concepts/pipelines/content/ViewPipelineServerModal.tsx
frontend/src/concepts/pipelines/content/configurePipelinesServer/ConfigurePipelinesServerModal.tsx
frontend/src/concepts/pipelines/content/experiment/CreateExperimentModal.tsx
frontend/src/concepts/pipelines/content/import/PipelineImportBase.tsx
frontend/src/concepts/pipelines/content/tables/pipelineRun/CustomMetricsColumnsModal.tsx
frontend/src/concepts/trustyai/content/InstallTrustyModal.tsx
frontend/src/pages/pipelines/global/runs/RestoreRunWithArchivedExperimentModal.tsx

**JIRA:** https://issues.redhat.com/browse/RHOAIENG-24706
This is the first PR to replace deprecated Modal component with PF6 Modal. Below are the major changes implemented in the PR,
1. Manually tested the UI for the affected areas of the dashboard to make sure that the new Modal loads correctly with all the right content.
I have just made sure that the tests which are already present are passing. I have fixed the cypress mock tests which failed.

RHOAIENG-24706: Part 1: Replace Deprecated Modal Instances with PF6 Modal

---

backend/src/utils/resourceUtils.ts

https://issues.redhat.com/browse/RHOAIENG-25122
In ODH -- no flags are set, the check failed to be hit, no issues.
In RHOAI -- the one flag is set, neither kserve or modelmesh, so it assumes we are still in v1 days and trying to migrate settings for new KServe option. Configures things weirdly & breaks tests.
Remove any kserve & model mesh feature flags in the OdhDashboardConfig
* Delete the contents of `dashboardConfig` item from your OdhDashboardConfig
* Should be set to something like this: `dashboardConfig: {}`
* Navigate to the Cluster Settings page
* Disable the Operator deployment
* (scale the Dashboard replicas to 1)
* Modify the image for the Dashboard pod and set the image tag to `pr-4183`
* Wait 2 mins -- refresh the Cluster Settings page
* Do it again, with the `main` tag …

Remove legacy functionality

---

frontend/src/__tests__/cypress/cypress/pages/userManagement.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/settings/userManagement/testUserGroupRemovedNotification.cy.ts
frontend/src/__tests__/cypress/cypress/utils/oc_commands/groups.ts

https://issues.redhat.com/browse/RHOAIENG-22506
Migrates ODS-1686 Tier 1 to Cypress
Test is now added to the test script 'testUserGroupRemovedNotification.cy.ts'
- Tested against ODH-Nightly & RHOAI nightly
- Tested via Jenkins pipeline https://jenkins-csb-rhods-opendatascience.dno.corp.redhat.com/job/cypress/job/dashboard-tests/1464/Test_20Reports/ 
After exporting the test-variables.yml we have 2 different ways:
Using the UI
Go to odh-dashboard/frontend and run the command npm run cypress:open . This will open the Cypress UI where testUserGroupRemovedNotification.cy.ts …

Cypress e2e Test - Verify a notification is shown when a user group is removed

---

frontend/src/__tests__/cypress/cypress/pages/modelCatalog/modelCatalogDeployModal.ts
frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDeployModal.ts
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ProjectSelector.tsx

https://issues.redhat.com/browse/RHOAIENG-24694
Added project search to deploy model modal
https://github.com/user-attachments/assets/ca9c2222-60df-4072-9056-e35e3d9185cc
- Deploy a model either from model registry or directly from model catalog
- Verify you can now see a project search to search the project by name
Updated the cypress test
cc @yannnz

add project search in model registry deploy model

---

frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDetails.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDetails.cy.ts
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionRegisteredFromLink.tsx

Issue: https://issues.redhat.com/browse/RHOAIENG-23477
Modified cypress test for registered from catalog in modelVersionDetails
N/A
all cypress tests are passing.

Modified cypress test for registered from catalog in modelVersionDetails

---

frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionOciPathField.tsx

Related to [RHOAIENG-2545](https://issues.redhat.com/browse/RHOAIENG-2545)
Fixes [RHOAIENG-25342](https://issues.redhat.com/browse/RHOAIENG-25342)
There was a bug causing problems with deploying an OCI model the new field trimming behavior was not always triggering on this field and was sometimes resulting in the modelUri lacking the `oci://` prefix
Test yourself:
- go to a project with kserve enabled
- deploy a model with oci, use any of the options below typed or pasted into the input field for "Model URI" (the ___ are spaces, github was trimming them)
- Either look for the inference service in the network tab or go look at the inference service yaml in openshift
- `spec: predictor: storageUri:` should have the correct `oci://` prefix
**Tested Scenarios:**
No tests changed for now but …

Trim Whitespace Bug Fix

---

frontend/src/concepts/pipelines/content/configurePipelinesServer/ObjectStorageSection.tsx
frontend/src/concepts/pipelines/content/configurePipelinesServer/PipelineDropdown.tsx

for: https://issues.redhat.com/browse/RHOAIENG-21530 
moved the button/dropdown for autofilling connections to a more prominent location re the [[figma](https://www.figma.com/design/6frHhyugL92eQEZO3oeuBH/My-Storage-credentials---pipeline-server-creation?node-id=1-3723&p=f&m=dev)] 
I tested it on the shared server (https://api.ilab-ui.dev.datahub.redhat.com:6443) as a clusteradmin;
with a project that has a stored connection config:
and one that does not have the config (it should not show)
tested that the component works exactly as it did before; which it does.
this ticket just changes the icon and changes the layout.  there are no functional changes *at all*
@kaedward  since ashley crago is not findable on github easily
tests are not applicable as there are no functional changes at all. …

moved the 'autofill connections' to a more prominent location

---

frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDetails.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalogDeploy.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDetails.cy.ts
frontend/src/pages/modelCatalog/__tests__/utils.spec.ts
frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx
frontend/src/pages/modelCatalog/utils.ts
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsHeaderActions.tsx
frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsTabs.tsx
frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsTableRow.tsx
frontend/src/pages/modelServing/__tests__/utils.spec.ts
frontend/src/pages/modelServing/screens/const.ts
frontend/src/pages/modelServing/screens/projects/DeployPrefilledModelModal.tsx
frontend/src/pages/modelServing/screens/projects/__tests__/useDeployButtonState.spec.ts
frontend/src/pages/modelServing/screens/projects/useDeployButtonState.ts
frontend/src/pages/modelServing/utils.ts

Closes [RHOAIENG-24513](https://issues.redhat.com/browse/RHOAIENG-24513)
Closes [RHOAIENG-25132](https://issues.redhat.com/browse/RHOAIENG-25132)
1. If model serving is entirely disabled (useIsAreaAvailable(SupportedArea.MODEL_SERVING).status), hide the button/action/tab entirely.
https://github.com/user-attachments/assets/ca2221a5-bbb8-42d7-a030-194a876c1af2
2. If model serving is enabled and the model to be deployed is an OCI model (uri?.includes('oci://'), and the kserve platform is not available (!useServingPlatformStatuses().kServe.enabled), disable the button/action with a tooltip.This applies to all models in model catalog, and models in model registry with OCI URIs. For this case, the tooltip should read "To deploy this model, an administrator must first enable single-model …

Rhoaieng 24513 -Model catalog and registry pages don't check if model serving is enabled before rendering deploy buttons and deployments tab

---

frontend/src/pages/modelRegistrySettings/CreateModal.tsx

Issue: https://issues.redhat.com/browse/RHOAIENG-17074
Replaced EmptyState spinner element with PF spinner component
Recording: https://github.com/user-attachments/assets/505ca918-8e32-4be9-809b-e0599557b3cf
Tested manually as shown in the video attached above
Cypress and Unit tests for CreateModal under modelRegistrySettings work as usual.

Spinner makes content of a modal jump when added towards the end of a modal

---

frontend/src/__tests__/cypress/cypress/pages/hardwareProfile.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/manageHardwareProfiles.cy.ts
frontend/src/pages/hardwareProfiles/const.tsx
frontend/src/pages/hardwareProfiles/manage/ManageNodeResourceSection.tsx
frontend/src/pages/hardwareProfiles/nodeResource/DeleteNodeResourceModal.tsx
frontend/src/pages/hardwareProfiles/nodeResource/NodeResourceTable.tsx

for: https://issues.redhat.com/browse/RHOAIENG-22692
show a dialog when deleting the *last* CPU or memory for a hardware profile.
previously, the warning happened on the page *after* the deletion happened.  
Now; the warning is still there; but there is a confirmation dialog that pops up if and only if the user is trying to delete the last CPU or memory resource.
if there are multiple cpu or memory resources; then the deletion just happens without a dialog.
Note:  normally hardware profiles are not visible to the user; the feature flag for hiding the hardware profiles has to be unchecked. see this video: (it has audio)
https://github.com/user-attachments/assets/da2c5440-bbae-459a-9739-58d8be34a06d
tested this manually, see the video up above.  tested while editing and while creating a …

Hardware guard deletion: show a dialog when deleting the *last* CPU or memory for a hardware profile

---

frontend/src/concepts/modelRegistry/apiHooks/__tests__/useModelArtifactsByVersionId.spec.ts
frontend/src/concepts/modelRegistry/apiHooks/useModelArtifactsByVersionId.ts

https://issues.redhat.com/browse/RHOAIENG-24225
added test for useModelArtifactsByVersionId
run the jest test check for coverage and test pass
Added jest test

added unit tests for useModelArtifactsByVersionId.ts

---

frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
frontend/src/pages/modelServing/screens/projects/__tests__/usePrefillModelDeployModal.spec.ts
frontend/src/pages/modelServing/screens/projects/usePrefillModelDeployModal.ts

Follow up #4106 
The ticket `Failed_QA` while verification as it was not handling projects with no connections
Try deploying `mdas-uri-test`(for URI) and `mdas-prefill-model`(for S3) version `v1` to any project(you can try 'mdas-new` project that has no connections in `ui-green` cluster) that has Kserve platform selected to deploy and has no connections, the connection name should still be present in the "Connection name" field
As mentioned in the description
Added Cypress tests for this specific use case

Prefill connection name when project has no connections

---

frontend/src/__tests__/cypress/cypress/pages/storageClasses.ts
frontend/src/pages/BYONImages/BYONImageModal/ManageBYONImageModal.tsx
frontend/src/pages/acceleratorProfiles/screens/list/DisableAcceleratorProfileModal.tsx
frontend/src/pages/acceleratorProfiles/screens/manage/tolerations/ManageTolerationModal.tsx
frontend/src/pages/connectionTypes/manage/ConnectionTypeDataFieldModal.tsx
frontend/src/pages/connectionTypes/manage/ConnectionTypeDataFieldRemoveModal.tsx
frontend/src/pages/connectionTypes/manage/ConnectionTypeFieldMoveModal.tsx
frontend/src/pages/connectionTypes/manage/ConnectionTypeSectionModal.tsx
frontend/src/pages/connectionTypes/manage/ConnectionTypeSectionRemoveModal.tsx
frontend/src/pages/storageClasses/StorageClassEditModal.tsx

**JIRA:** https://issues.redhat.com/browse/RHOAIENG-24707
This is the second PR to replace deprecated Modal component with PF6 Modal. Below are the major changes implemented in the PR,
1. Manually tested the UI for the affected areas of the dashboard to make sure that the new Modal loads correctly with all the right content.

RHOAIENG-24707: Part 2: Replace Deprecated Modal Instances with PF6 Modal

---

docs/admin-dashboard.md
docs/byon.md
docs/dashboard-config.md
docs/dev-setup.md

Typo and broken link fixes found with the help of Cursor

Fix typos in documentation files and broken links in dev-setup.md

---

frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDetails.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDetails.cy.ts
frontend/src/bootstrap.tsx
frontend/src/components/DashboardDescriptionListGroup.tsx
frontend/src/components/NavigationBlockerModal.tsx
frontend/src/components/__tests__/DashboardDescriptionListGroup.spec.tsx
frontend/src/components/__tests__/NavigationBlockerModal.spec.tsx
frontend/src/utilities/__tests__/useBrowserUnloadBlocker.spec.ts
frontend/src/utilities/useBrowserUnloadBlocker.tsx

[RHOAIENG-13914](https://issues.redhat.com/browse/RHOAIENG-13914)
* Added useBrowserUnloadBlocker to simplify navigation blocking to browser unload events
* Users now will get error if they try to navigate during editing in Model registry and model version details page.
Browser warning
https://github.com/user-attachments/assets/dc6ead44-f44a-4c0e-8164-dd286321b3b6
Dashboard navigation warning modal
https://github.com/user-attachments/assets/020e0829-926a-40a2-986d-8bb4f55ba270
1. Navigate to details page of model regisrty or model version.
2. Try edit something and click on refresh or try clicking somewhere on the dashboard.
3. You'll get warning modal.
Added unit test for the hook.
Added cypress test to check discard modal in model version details page. …

User can lose unsaved edits without warning on model registry details pages

---

frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunsGlobal.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesGlobal.ts
frontend/src/pages/exploreApplication/EnableModal.tsx
frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
frontend/src/pages/notebookController/screens/server/StopServerModal.tsx
frontend/src/pages/projects/components/DeleteModal.tsx
frontend/src/pages/projects/notebook/StopNotebookConfirmModal.tsx
frontend/src/pages/projects/screens/detail/connections/ManageConnectionsModal.tsx
frontend/src/pages/projects/screens/detail/connections/__tests__/ManageConnectionsModal.spec.tsx
frontend/src/pages/projects/screens/detail/storage/BaseStorageModal.tsx
frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx
frontend/src/pages/projects/screens/spawner/connections/DetachConnectionModal.tsx
frontend/src/pages/projects/screens/spawner/connections/SelectConnectionsModal.tsx
frontend/src/pages/projects/screens/spawner/connections/__tests__/ConnectionsFormSection.spec.tsx
frontend/src/pages/projects/screens/spawner/storage/AttachExistingStorageModal.tsx
frontend/src/pages/projects/screens/spawner/storage/ClusterStorageDetachModal.tsx

**JIRA:** https://issues.redhat.com/browse/RHOAIENG-24709
This is the second PR to replace deprecated Modal component with PF6 Modal. Below are the major changes implemented in the PR,
1. Manually tested the UI for the affected areas of the dashboard to make sure that the new Modal loads correctly with all the right content.

RHOAIENG-24709: Part 4: Replace Deprecated Modal Instances with PF6 Modal

---

frontend/src/pages/modelRegistry/screens/RegisterModel/ConnectionModal.tsx
frontend/src/pages/modelRegistry/screens/components/ArchiveModelVersionModal.tsx
frontend/src/pages/modelRegistry/screens/components/ArchiveRegisteredModelModal.tsx
frontend/src/pages/modelRegistry/screens/components/ModelLabels.tsx
frontend/src/pages/modelRegistry/screens/components/RestoreModelVersionModal.tsx
frontend/src/pages/modelRegistry/screens/components/RestoreRegisteredModel.tsx
frontend/src/pages/modelRegistrySettings/CreateModal.tsx
frontend/src/pages/modelRegistrySettings/DeleteModelRegistryModal.tsx

**JIRA:** https://issues.redhat.com/browse/RHOAIENG-24710
This is the second PR to replace deprecated Modal component with PF6 Modal. Below are the major changes implemented in the PR,
1. Manually tested the UI for the affected areas of the dashboard to make sure that the new Modal loads correctly with all the right content.

RHOAIENG-24710: Part 5: Replace Deprecated Modal Instances with PF6 Modal 

---

frontend/src/pages/clusterSettings/TelemetrySettings.tsx

Closes: [RHOAIENG-1198](https://issues.redhat.com/browse/RHOAIENG-1198)
Small update to remove the documentation link from usage data collection.
Tested locally. 
- Ensure that the disableTracking feature flag is unchecked.
- Navigate to cluster settings. 
- Towards the bottom, under usage data collection, there should no longer be a documentation link
Before:
After:

Small update to remove documentation link

---

frontend/src/api/k8s/__tests__/pvcs.spec.ts
frontend/src/api/k8s/pvcs.ts
frontend/src/pages/projects/screens/detail/storage/utils.ts
frontend/src/pages/projects/screens/spawner/service.ts

https://issues.redhat.com/browse/RHOAIENG-23113
The PVC update logic has issues handling PVCs created outside the dashboard UI, leading to unnecessary updates and invalid spec modifications.
Steps:
* Create a PVC manually through the console. Make sure to add the following to the yaml to see it in the UI:
```
metadata:
labels:
```
* Edit a preexisting workbench and replace the storage with the manually created storage 
* You’ll see that the description of the storageData update will be undefined
Unit tests

Fix PVC update logic for externally created PVCs

---

frontend/src/concepts/pipelines/content/artifacts/ArtifactUriLink.tsx

Follow-up fix for [RHOAIENG-11412](https://issues.redhat.com/browse/RHOAIENG-11412)
The `system.Artifact` type should also fetch the download URL like `system.Model`, but not the render URL. This PR updated that.
Go to the ilab shared cluster, check the artifacts list. Make sure you can download the file when clicking on the S3 URL of the artifacts that have the `system.Artifact` type.
N/A

Use download URL instead of render URL for system.Artifact type

---

frontend/src/pages/hardwareProfiles/migration/MigrationModal.tsx
frontend/src/pages/hardwareProfiles/nodeResource/ManageNodeResourceModal.tsx
frontend/src/pages/hardwareProfiles/nodeSelector/ManageNodeSelectorModal.tsx
frontend/src/pages/hardwareProfiles/toleration/ManageTolerationModal.tsx
frontend/src/pages/modelServing/screens/metrics/bias/BiasConfigurationPage/BiasConfigurationModal/ManageBiasConfigurationModal.tsx
frontend/src/pages/modelServing/screens/projects/DeployPrefilledModelModal.tsx
frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx

**JIRA:** https://issues.redhat.com/browse/RHOAIENG-24708
This is the second PR to replace deprecated Modal component with PF6 Modal. Below are the major changes implemented in the PR,
Manually tested the UI for the affected areas of the dashboard to make sure that the new Modal loads correctly with all the right content except `ManageNIMServingModal and ManageBiasConfigurationModal` modals.

RHOAIENG-24708: Part 3: Replace Deprecated Modal Instances with PF6 Modal

---

frontend/src/__mocks__/mockNotebookK8sResource.ts
frontend/src/__mocks__/mockServingRuntimeK8sResource.ts
frontend/src/__tests__/cypress/cypress/pages/components/subComponents/AcceleratorProfileSection.ts
frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts
frontend/src/__tests__/cypress/cypress/pages/workbench.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/workbenchHardwareProfiles.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/workbench.cy.ts
frontend/src/api/k8s/notebooks.ts
frontend/src/api/k8s/servingRuntimes.ts
frontend/src/concepts/hardwareProfiles/HardwareProfileSelect.tsx
frontend/src/concepts/hardwareProfiles/useHardwareProfileConfig.ts
frontend/src/concepts/hardwareProfiles/useNotebookHardwareProfileConfig.ts
frontend/src/concepts/hardwareProfiles/useServingHardwareProfileConfig.ts
frontend/src/k8sTypes.ts
frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeDetails.tsx
frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTableExpandedSection.tsx
frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTableRow.tsx
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
frontend/src/pages/notebookController/screens/server/AcceleratorProfileSelectField.tsx
frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingHardwareProfileFormSection.tsx

Closes: [RHOAIENG-24572](https://issues.redhat.com/browse/RHOAIENG-24572)
This PR aims to support project-scoped serving runtime, hardware profile and accelerator profile for model mesh. Also create a re-usable component for acceleratorprofile-section.
1. Add model server with project-scoped Accelerator profile.
https://github.com/user-attachments/assets/5ae3af98-63ac-4af7-acc4-992df566ff77
2. with hardware profile
https://github.com/user-attachments/assets/915def47-3ba3-47f9-a635-d09f9b644de8
Try to add model server with project-scoped items(serving runtime, hardware profile and accelerator profile)
Added cypress tests for the same. will be adding more for few edge cases in follow-up PR. …

Add project-scoped items for model mesh

---

frontend/src/__tests__/cypress/cypress.config.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dashboardNavigation/testManifestLinks.cy.ts
frontend/src/__tests__/cypress/cypress/utils/urlValidator.ts

https://issues.redhat.com/browse/RHOAIENG-9235
Add support for common successful responses (201, 202, 204), redirects (301, 302, 307, 308), and rate limiting (429) in testManifestLinks.cy.ts.
In Jenkins and locally, the test duration is now 15 - 30 seconds, while previously it was 40 - 100 seconds:
E2E test `dashboardNavigation/testManifestLinks.cy.ts`

testManifestLinks: Validate multiple HTTP status code responses

---

frontend/src/k8sTypes.ts
frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx
frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTable.tsx
frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTokensTable.tsx
frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
frontend/src/pages/modelServing/utils.ts
frontend/src/pages/projects/ProjectDetailsContext.tsx

https://issues.redhat.com/browse/RHOAIENG-23800
When you have an ISVC and a SR that have different names, the token created in the kserve modal will not display. I had to revert one change from a recent PR that will need testing from the NIM team.
1. Select single model serving
2. Create an ISVC and a SR with different names
3. Go to edit the model
4. Require token authentication
5. Redeploy
6. Edit the model again
7. The service account input field should be visible
Going to add tests in a separate PR

Fix model serving service account when isvc and sr have different names

---

frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
frontend/src/pages/modelServing/customServingRuntimes/__tests__/utils.spec.ts
frontend/src/pages/modelServing/customServingRuntimes/utils.ts
frontend/src/pages/modelServing/screens/global/InferenceServiceServingRuntime.tsx

Closes [RHOAIENG-25675](https://issues.redhat.com/browse/RHOAIENG-25675)
If the runtime version annotation exists in the serving runtime then it will show in the model deployments table
**Before:**
**After:**
To test this:
- Deploy a model.
- Go to the model serving global page.
- Note that there is no version for the serving runtime.
- Go to openshift console and search in the project for the `ServingRuntime` for the model you deployed.
- Go to the yaml.
- Add this to the annotations -> `opendatahub.io/runtime-version: 'v0.5.1'`.
- Go back to the dashboard and refresh the page.
- If you want to see it with the project scoped label as well you can add `opendatahub.io/serving-runtime-scope: project` to the annotations as well.
- (shows in the …

Add serving runtime version to deployment table

---

frontend/src/pages/modelServing/screens/global/InferenceServiceStatus.tsx
frontend/src/pages/modelServing/screens/global/__tests__/utils.spec.ts
frontend/src/pages/modelServing/screens/global/utils.ts
frontend/src/pages/modelServing/screens/types.ts

Related to the following:
https://issues.redhat.com/browse/NVPE-253
Improved scheduling error message for failed model deployments
This update enhances the clarity of the status tooltip shown when a model fails to schedule due to resource constraints. Previously, users only saw a generic "Insufficient resources" message. Now, the UI extracts and displays the actual reason from the Pod condition (e.g., "0/3 nodes are available: 3 Insufficient nvidia.com/gpu"), making it easier to understand and resolve scheduling issues.
1. Deploy NIM.
2. Try to deploy a NIM model (i used llama-3.1-8b-instruct - 1.8.3)
3. Wait a few moments for the status to get updated and watch the tooltip over it.
Before:
After:
After the …

feat: added info for insufficient resources error when a model is deployed

---

frontend/src/__tests__/cypress/cypress/pages/permissions.ts

https://issues.redhat.com/browse/RHOAIENG-26151
Fix the issues found in last RHOAI nightly (dashboard-tests/1587) regarding the testProjectAdminPermissions tests
Locally:
`$ npx cypress run --browser chrome --project src/__tests__/cypress --spec **/testProjectAdminPermissions.cy.ts`
Fix for testProjectAdminPermissions

fix: testProjectAdminPermissions test

---

frontend/src/__tests__/cypress/cypress/pages/components/NIMDeployModal.ts
frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/modelServingNim.cy.ts
frontend/src/components/ReplicaSection.tsx
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeReplicaSection.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/KServeAutoscalerReplicaSection.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx

Closes [RHOAIENG-24712](https://issues.redhat.com/browse/RHOAIENG-24712)
Changes the Advanced deployment option to require a minimum and maximum number of model servers to deploy. 
The numbers are capped at 99, and the inputs won't allow the min to be higher than the max. 
To test this:
- Go to your project and to models > deploy model
- Scroll to deployment mode and ensure 'Advanced' is selected 
- Modify the min and max numbers and deploy the model. The numbers can be equal, but min can't be higher than max and vice versa 
- Go to your OpenShift console, and select your project
- Under your project, search for 'InferenceServices' and open the yaml
- Under `spec:`, you should see your maxReplicas and minReplicas.
Added additional cypress tests to check the functionality of the advanced …

Add min/max selector to advanced deploy model

---

frontend/src/__tests__/cypress/cypress/tests/e2e/dashboardNavigation/testManifestLinks.cy.ts
frontend/src/__tests__/cypress/cypress/utils/urlExtractor.ts
frontend/src/__tests__/cypress/cypress/utils/urlValidator.ts

The regex in `frontend/src/__tests__/cypress/cypress/utils/urlExtractor.ts` was extracting some manifests URLs with a wrong protocol `httpss`:
This PR is to fix the regex pattern used.
E2E on Jenkins:
dashboardNavigation/testManifestLinks.cy.ts

Fix Cypress URL extraction regex

---

frontend/src/__mocks__/mockInferenceServiceK8sResource.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
frontend/src/concepts/connectionTypes/__tests__/utils.spec.ts
frontend/src/concepts/connectionTypes/utils.ts
frontend/src/pages/modelServing/screens/projects/__tests__/utils.spec.ts
frontend/src/pages/modelServing/screens/projects/kServeModal/EnvironmentVariablesSection.tsx
frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
frontend/src/pages/modelServing/screens/projects/utils.ts

Closes [RHOAIENG-15595](https://issues.redhat.com/browse/RHOAIENG-15595)
If you had an env variable that pointed to a `Secret` or `ConfigMap` using `valueFrom` then the env value shown in the model deployment would be empty. Upon trying to edit that empty value it would add `value` next to  `valueFrom` and break the whole thing.
Per the ticket, the input now shows the `valueFrom` but is disabled to prevent editing; with a tooltip that explains the value can be edited from the OCP.
**Previously:**
**Now:**
**The tooltip:**
**To test this:**
- Go to deploy a kserve model.
- Add a regular env variable. Ex key: `test-variable-key` value: `test-variable-value`.
- Deploy the model.
- Find the deployed inference service in OCP.
- Go to the yaml.
- in …

'valueFrom' env vars bug fix

---

frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/workbench.cy.ts
frontend/src/pages/projects/screens/detail/notebooks/useNotebookImageData.ts
frontend/src/pages/projects/screens/spawner/spawnerUtils.ts

https://issues.redhat.com/browse/RHOAIENG-25679
Added a check, where an image can only be deleted if the build commit is not found AND it is not a BYON image.
1. Create a byon image
2. Go to the notebook list. It should not show as deleted.
Cypress tests

added byon checking

---

frontend/src/__mocks__/mockDashboardConfig.ts
frontend/src/concepts/areas/const.ts
frontend/src/concepts/areas/types.ts
frontend/src/k8sTypes.ts

Add Feature flag for LMEval

---

frontend/.eslintrc.js
frontend/packages/kserve/extensions.ts
frontend/packages/kserve/src/deployments.ts
frontend/packages/modelServing/extension-points/index.ts
frontend/packages/modelServing/extensions.ts
frontend/packages/modelServing/src/components/projectDetails/DeploymentsTable.tsx
frontend/packages/modelServing/src/components/projectDetails/ModelsProjectDetailsView.tsx
frontend/packages/modelServing/src/components/projectDetails/NoModelsView.tsx
frontend/packages/modelServing/src/components/projectDetails/SelectPlatformView.tsx
frontend/packages/modelServing/src/concepts/ModelDeploymentsContext.tsx
frontend/packages/modelServing/src/concepts/ModelServingPlatformContext.tsx
frontend/packages/modelServing/src/concepts/extensionUtils.ts
frontend/packages/modelServing/src/concepts/modelServingPlatforms.ts
frontend/packages/plugin-core/src/extension-points/project-details.ts

Based off https://github.com/opendatahub-io/odh-dashboard/pull/4191
Closes https://issues.redhat.com/browse/RHOAIENG-26246
Removes the `// eslint-disable-next-line import/no-extraneous-dependenc` lines and also fix the path checking to forces type imports for extension specific files
run `npm run test:lint`
No tests needed because it's linting only changes

Update model serving plugin linting

---

frontend/src/__tests__/cypress/cypress/pages/pipelines/createRunPage.ts
frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/runs/pipelineCreateRuns.cy.ts
frontend/src/concepts/pipelines/content/createRun/contentSections/PipelineSection.tsx
frontend/src/concepts/pipelines/content/createRun/contentSections/PipelineVersionRadioGroup.tsx
frontend/src/concepts/pipelines/content/import/ImportPipelineVersionButton.tsx
frontend/src/concepts/pipelines/content/import/PipelineVersionImportModal.tsx

Issue: https://issues.redhat.com/browse/RHOAIENG-24479 
Previously, in the Data science pipelines > Runs > Create run form, if a new pipeline version was created within that form, the user would be redirected to the newly created pipeline's page instead of closing the modal and going back to the create run form. This change makes it so that the user is returned back to the create run form so that the user does not lose their inputted data.
Ran the existing cypress and unit tests which already test the pipeline version creation modal and the create run form. These tests ensured that the change is localized within the create run flow and does not affect flows such as creating a new pipeline version from the Pipelines tab.
To see the changes
1. Go to Data science pipelines > Runs > Create …

Fix pipeline version creation in create run form

---

frontend/src/__mocks__/mockServingRuntimeTemplateK8sResource.ts
frontend/src/__tests__/cypress/cypress/pages/servingRuntimes.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/customServingRuntimes/customServingRuntimes.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/customServingRuntimes/customServingRuntimesUtils.ts
frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeTableRow.tsx
frontend/src/pages/modelServing/customServingRuntimes/__tests__/utils.spec.ts
frontend/src/pages/modelServing/customServingRuntimes/utils.ts
frontend/src/pages/modelServing/screens/ServingRuntimeVersionLabel.tsx
frontend/src/pages/modelServing/screens/global/InferenceServiceServingRuntime.tsx

Closes [RHOAIENG-26114](https://issues.redhat.com/browse/RHOAIENG-26114)
A continuation of [RHOAIENG-25675](https://issues.redhat.com/browse/RHOAIENG-25675) <- where I added the serving runtime version to the model deployment table. 
In this PR I added the runtime version to the runtime templates in the settings > serving runtimes table.
**Before:**
**After:**
To test this:
- Log in as a user thats allowed to see this page
- Go to settings > serving runtimes and notice that there are no version labels
- Duplicate any of the existing serving runtimes
- Now to the OCP search in the `opendatahub` namespace for `template` resources
- You can find the resource name for the templates from the popups in settings > serving runtimes
- It'll be generated, …

Add Serving Runtime Version to Admin Serving Runtime Table

---

frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testDeployOCIModel.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testMultiModelAdminCreation.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/settings/hardwareProfiles/testModelServingTolerations.cy.ts
frontend/src/__tests__/cypress/cypress/utils/oc_commands/modelServing.ts

https://issues.redhat.com/browse/RHOAIENG-26465
Add namespace to modelseving backend calls. 
2.21: dashboard-tests/1690
2.22: dashboard-tests/1691 
Affect to model serving e2e tests

Cypress e2e: add namespace to oc modelserving calls

---

frontend/packages/tsconfig/tsconfig.json

When using `moduleResolution: bundler` in the tsconfig, vscode auto complete import is adding file extensions. While I work on finding a solution to prevent addition of file extensions, this setting will help auto complete file extensions to .ts or .tsx instead of .js.
While file extensions in the import aren't wrong, we prefer to have no file extensions required for .ts / .tsx files. Without this setting, a .js file extension is added which will cause jest tests to fail.
Using cursor / vscode, auto complete an import. Check that the file extension is omitted entirely or set to .ts or .tsx.
- Delete an existing import
- Find the usage of the removed import in the code file where the error indicates that it cannot be found
- Go use quick fix or auto complete after the usage
- Check that …

set tsconfig allowImportingTsExtensions: true

---

manifests/common/apps/jupyter/jupyter-app.yaml

https://issues.redhat.com/browse/RHOAIENG-25601
Sets the provider of the 'Start basic workbench' tile to an empty string. It cannot be fully removed as the CRD requires that value. Our code does a check for a defined value there so it will act as undefined when rendered.
go to explore section and make sure 'by Jupyter' is gone
none - microcopy

Remove provider specification from Jupyter app manifest

---

frontend/.eslintignore
frontend/.eslintrc.goal.js
frontend/.eslintrc.js
frontend/packages/tsconfig/tsconfig.json

The js files in `frontend/` got errors because of issues with them not being ignored from the `.eslintignore` in linux and typescript was seeing this discrepancy. They are now being fully linted and the glob file patterns was fixed

Fix glob pattern linting os discrepancies

---

frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionOciPathField.tsx

For 2.19.1 patch https://issues.redhat.com/browse/RHOAIENG-24967
cherry pick from 2.20 fix https://issues.redhat.com/browse/RHOAIENG-24886
Fix

2.19.1 cherry pick: Fix http prefix removal for OCI path (#4150)

---

frontend/src/__mocks__/mockNotebookK8sResource.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/workbench.cy.ts
frontend/src/api/k8s/notebooks.ts
frontend/src/concepts/hardwareProfiles/HardwareProfileSelect.tsx
frontend/src/k8sTypes.ts
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx
frontend/src/pages/notebookController/screens/server/AcceleratorProfileSelectField.tsx
frontend/src/pages/projects/screens/detail/notebooks/NotebookImageDisplayName.tsx
frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx
frontend/src/pages/projects/screens/detail/notebooks/useNotebookImage.ts
frontend/src/pages/projects/screens/detail/notebooks/useNotebookImageData.ts
frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
frontend/src/pages/projects/screens/spawner/imageSelector/ImageSelectorField.tsx
frontend/src/pages/projects/screens/spawner/imageSelector/ImageStreamSelector.tsx

Closes: [RHOAIENG-25734](https://issues.redhat.com/browse/RHOAIENG-25734)
This PR aims to fix duplicate name issue with workbench images. We have introduced an annotation to identify whether a workbench image is project-scoped or global-scoped. 
Also, minor changes around the dropdown items of search selector.
disbaleProjectScoped feature flag should be on.
1. Create same workbench image in opendatahub and any namespace in which, you are going to create a workbench.
2. Make sure the edit page and the table will show the correct label (Project-scoped/global-scoped).
3. Also, turn off the feature flag after creating a workbench with the project-scoped image, go to edit page - you will see the placeholder text in image selector and update workbench button will be disabled.
Added cypress …

Fix duplicate name issue with workbench images

---

frontend/src/__tests__/cypress/cypress/pages/storageClasses.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/storageClasses/storageClasses.cy.ts
frontend/src/pages/storageClasses/StorageClassEditModal.tsx
frontend/src/pages/storageClasses/constants.ts

https://issues.redhat.com/browse/RHOAIENG-25533
Added a new section in the storage class edit modal to allow admin to enable/disable one or more access modes. 
* Added a popover to show the explanation of the feature
* Displayed all access modes in checkbox form
* RWO is supported by default and cannot be disabled
* If the class doesn't support the mode, the mode checkbox is disabled
* When hovering over a disabled mode, a tooltip is shown with an explanation
* When RWX mode is initially enabled at modal opening, and then checked off, an alert is displayed explaining the consequences.
1. Create a new storage class in the OpenShift console, with `kubernetes.io/quobyte` as provisioner. 
2. Go to the dashboard and navigate to the storage classes page
3. Click on the kebab button, and edit
4. …

Storage class edit modal, access mode configuration

---

frontend/src/api/k8s/__tests__/notebooks.spec.ts
frontend/src/api/k8s/notebooks.ts
frontend/src/concepts/pipelines/elyra/utils.ts
frontend/src/pages/projects/screens/spawner/__tests__/SpawnerFooter.spec.tsx

**JIRA story:** https://issues.redhat.com/browse/RHOAIENG-15191
1. The Dashboard code responsible for creating or managing RoleBindings for notebook Service Accounts (related to DSPA/Elyra) is removed.
2. Specifically, calls to createElyraServiceAccountRoleBinding (or similar functions that manage these RoleBindings) within createNotebook and startNotebook in frontend/src/api/k8s/notebooks.ts are removed.
3. When a new workbench is created or an existing one is started with pipeline capabilities enabled, the Dashboard no longer attempts to create any RoleBinding for the notebook's service account.
4. The createElyraServiceAccountRoleBinding function, if no longer used elsewhere after these changes, is removed from ~/concepts/pipelines/elyra/utils.ts and its import is removed from …

RHOAIENG-15191: Deprecate/Remove the DSPA RBAC setting from Dashboard 

---

frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testDeployOCIModel.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testMultiModelAdminCreation.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelAdminCreation.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts
frontend/src/__tests__/cypress/cypress/tests/e2e/settings/hardwareProfiles/testModelServingTolerations.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts
frontend/src/components/searchSelector/ProjectScopedToggleContent.tsx
frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx

https://issues.redhat.com/browse/RHOAIENG-25676
This adds the Runtime Version Label to the dropdown when selecting your serving runtime in both multi and single serving modals. It replaces the SimpleSelect with the SearchSelector full time (something we only did when there were project specific templates). If there are no project specific templates you'll see the normal ones under global.
Create a Serving Runtime Template and add the annotation under the Serving Runtime 
```
opendatahub.io/runtime-version: 'v0.5.1'
```
Go to deploy single and multi models
In the modal go to select a template and see the version label next to your template item
Once selected it should show the label in the selector's place holder.
Added a couple mock tests
Created a new base ServingModal that is inherited …

Add version for serving runtime dropdown

---

frontend/src/__mocks__/mockPVCK8sResource.ts
frontend/src/__tests__/cypress/cypress/pages/workbench.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/workbench.cy.ts
frontend/src/components/TypeaheadSelect.tsx
frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx
frontend/src/pages/projects/screens/detail/storage/data.ts
frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
frontend/src/pages/projects/screens/spawner/storage/AddExistingStorageField.tsx
frontend/src/pages/projects/utils.ts

https://issues.redhat.com/browse/RHOAIENG-25578
* Added inline plain alert below the storage selection
* In the dropdown menu, grouped the PVCs by the access modes (RWO, RWX, ROX, RWOP)
* Will not show the group if there are no storages in that access mode type
* Added a label next to the storage name to indicate the access mode in the selection toggle
https://github.com/user-attachments/assets/18673304-36e2-422c-99a3-ee9b8b3ddf1b
* Create a PVC in the console with quobyte provisioner storage class in project
* Create various other PVCs with different storage classes 
* Add the following to the yaml file under metadata:
```yaml
labels:
```
* Edit a workbench, and click on Add existing storage
* Click on the Select …

Access mode support for existing PVC attachment modal in workbench

---

frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testDeployOCIModel.cy.ts

The bug here was fixed so we should be okay to enable this. Ideally should have done this with the bug fix. In the future with PR testing we can even run the e2e test when the bug fix PR is up.

Enable the OCI e2e test

---

frontend/src/__mocks__/mockServingRuntimeK8sResource.ts
frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts
frontend/src/api/k8s/notebooks.ts
frontend/src/api/k8s/servingRuntimes.ts
frontend/src/k8sTypes.ts
frontend/src/pages/modelServing/screens/projects/useServingAcceleratorProfileFormState.ts
frontend/src/pages/notebookController/screens/server/AcceleratorProfileSelectField.tsx
frontend/src/pages/projects/screens/detail/notebooks/useNotebookAcceleratorProfileFormState.ts
frontend/src/utilities/useAcceleratorProfileFormState.ts
frontend/src/utilities/useReadAcceleratorState.ts

Closes: [RHOAIENG-25733](https://issues.redhat.com/browse/RHOAIENG-25733)
1. Handle duplicate names in different namespace(namely project and global namespace).
2. Show and select "Existing settings" when a deleted project-scoped and global accelerator profile is being used on Edit page of Workbenches/kserve/model-mesh/training hardware field in Ilab form
1. Create/copy the same `AcceleratorProfile` from `opendatahub` and just change the namespace(not the name) to a project when you want to create this item. Change from the project-scoped to the global-scoped accelerator profile and check whether the label reflects properly.
2. Make sure "Existing settings" is showed and selected when a deleted project-scoped and global accelerator profile is being used on Edit page of …

Handle duplicate names in different namespaces for project-scoped accelerator profiles

---

frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/manageHardwareProfiles.cy.ts
frontend/src/pages/hardwareProfiles/manage/__tests__/validationUtils.spec.ts
frontend/src/pages/hardwareProfiles/manage/validationUtils.ts

**JIRA story:** https://issues.redhat.com/browse/RHOAIENG-25719
We wan't to enable the Update hardware profile button when
1. there is last cpu or memory resource is present.
2. you have deleted all the resources and no resources are present.
We should continue showing the warning for cpu and memory.
1. Go to Hardware profiles page (you might have to enable it using feature flags)
2. Create a new hardware profile with default node resources.
3. Edit it and remove either CPU or Memory resource.
4. The update button should be enabled and not disabled.
Removed the unit tests for failed validation when CPU or Memory node was deleted. Added a check for update button being enabled in the cypress mock test. …

RHOAIENG-25719: Deleting Memory or CPU from a Hardware Profile, disables the Update button

---

frontend/src/k8sTypes.ts
frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx
frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTable.tsx
frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTokensTable.tsx
frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx
frontend/src/pages/modelServing/utils.ts
frontend/src/pages/projects/ProjectDetailsContext.tsx

Fixes https://issues.redhat.com/browse/RHOAIENG-27682
Cherry pick of
https://issues.redhat.com/browse/RHOAIENG-23800
Description
When you have an ISVC and a SR that have different names, the token created in the kserve modal will not display. I had to revert one change from a recent PR that will need testing from the NIM team.
How Has This Been Tested?
Select single model serving
Create an ISVC and a SR with different names
Go to edit the model
Require token authentication
Redeploy
Edit the model again
The service account input field should be visible

Fix token issue when ISVC and SR are different names (#4209)

---

packages/gen-ai/frontend/config/dotenv.js

Since the port in module federation config was updated to `9102`, updating the default port for genai.

Update default port for genai since module federation port was updated

---

packages/gen-ai/bff/internal/api/app.go
packages/gen-ai/bff/internal/api/llamastack_distribution_handler_delete.go
packages/gen-ai/bff/internal/api/llamastack_distribution_handler_test.go
packages/gen-ai/bff/internal/constants/api_constants.go
packages/gen-ai/bff/internal/integrations/kubernetes/client.go
packages/gen-ai/bff/internal/integrations/kubernetes/k8smocks/token_k8s_client_mock.go
packages/gen-ai/bff/internal/integrations/kubernetes/token_k8s_client.go
packages/gen-ai/bff/internal/models/llamastack_distribution.go
packages/gen-ai/bff/internal/repositories/llamastack_distribution.go

This PR implements a new DELETE endpoint for LlamaStack Distribution (LSD) management, allowing users to delete LSD instances by their display name.
New API Endpoint
- DELETE /gen-ai/api/v1/llamastack-distribution/delete
- Deletes LSD by display name with proper validation
- Returns structured success/error responses
Example deletion request:
curl -X DELETE \
-H "Authorization: Bearer <token>" \ -H "Content-Type: application/json" \ -d '{"name": "lsd-genai-playground"}' \ "http://localhost:8080/gen-ai/api/v1/llamastack-distribution/delete?namespace=models"

[feat] Add deletion endpoint for LSD

---

manifests/rhoai/shared/base/federation-configmap.yaml
manifests/rhoai/shared/base/kustomization.yaml

Cherry-picks https://github.com/opendatahub-io/odh-dashboard/pull/4969 to stable-2.x, see that PR for details
Was tested by manually patching the manifests on a RHOAI cluster running the latest 2.x build

[Cherry-pick 2.x] Add override for rhoai for modular architecture

---

frontend/src/pages/hardwareProfiles/HardwareProfiles.tsx

(cherry picked from commit 02cc5317086b2728e7390a8871617175fd60695d)
https://issues.redhat.com/browse/RHOAIENG-34837
Cherry-picked from https://github.com/opendatahub-io/odh-dashboard/pull/4964
Fix re-render loop that blocked navigation out of the hardware profiles page. 
Go to the hardware profiles page, create hardware profiles, change their order around in the table, and navigate to another page. 

Fix hwp hook (#4964)

---

manifests/modular-architecture/kustomization.yaml
manifests/modular-architecture/networkpolicy.yaml
manifests/rhoai/shared/base/kustomization.yaml
manifests/rhoai/shared/base/networkpolicy.yaml

Cherrypicks changes from #4995, see that PR for details
Manifest change only, and this merge results in the same manifests that were already tested for #4995

[Cherrypick 2.x] bugfix: add networking to allow connection in rhoai

---

frontend/src/pages/hardwareProfiles/HardwareProfilesTable.tsx
frontend/src/pages/hardwareProfiles/HardwareProfilesTableRow.tsx

Since legacy hardware profiles will still be available for 2.25, we need to remove the ordering functionality from its table since it will interfere with the hardware profile table ordering. The table ordering was implemented without taking the legacy table into account. 
https://github.com/user-attachments/assets/a2461088-62fc-46af-9d8c-7fdad9165450
- Create legacy hardware profiles by either creating accelerator profiles or adding container sizes in odh-dashboard-config
- Go to Settings > Hardware Profiles
- Check that the legacy profiles table does not support ordering, while the hardware profiles table does

Remove ordering functionality from legacy profiles table
