routes/api/components/available-components.js
ODH Dashboard is unable to detect spark component, since upstream uses a different name for it, see:
- https://github.com/opendatahub-io/odh-manifests/tree/master/radanalyticsio
- https://github.com/opendatahub-io/odh-manifests/blob/master/tests/setup/kfctl_openshift.yaml
/kind bug
=> fix: Spark kfDef component name

routes/api/components/available-components.js
Similar to https://github.com/opendatahub-io/odh-dashboard/pull/31
There's no `grafana-instance` component upstream.
https://github.com/opendatahub-io/odh-manifests/tree/master/grafana
https://github.com/opendatahub-io/odh-manifests/blob/master/tests/setup/kfctl_openshift.yaml
=> fix: Grafana component names

routes/api/components/available-components.js
This reverts commit 4ebc0b90664c2b182478a352ecd219fe5f87c392.
=> Revert "fix: Grafana component names (#33)"

frontend/src/pages/ApplicationsPage.scss, frontend/src/pages/enabledApplications/EnabledApplications.tsx, frontend/src/pages/exploreApplication/ExploreApplications.tsx, frontend/src/pages/learningCenter/CategoryFilters.tsx, frontend/src/pages/learningCenter/LearningCenter.scss, frontend/src/pages/learningCenter/LearningCenter.tsx, frontend/src/pages/learningCenter/LearningCenterDataView.tsx, frontend/src/pages/learningCenter/LearningCenterFilters.tsx, frontend/src/pages/learningCenter/LearningCenterToolbar.scss, frontend/src/pages/learningCenter/LearningCenterToolbar.tsx, frontend/src/pages/learningCenter/const.ts, frontend/src/pages/learningCenter/useDocFilterer.ts, frontend/src/utilities/utils.ts
**Fixes**: 
At low resolution or when the nav is open and a quick start is open, the resources view gets too narrow to show much of the information for each resource.
The addition of the filter panel decreases the width used by the view to show the resources.
When the view width becomes narrow (under 600px) turn the filter panel into a slide out drawer controlled by a filter button in the header panel.
This PR also adds "Favorites" category.
**Browser conformance**: 
/cc @kywalker-rh
=> Collapse filter panel when view gets too narrow

backend/src/types.ts, backend/src/utils/resourceUtils.ts
**Fixes**: 
Build failure messages show the name of the build config when builds fail, this name is not what a user would expect to see.
There was no way to determine which notebook a build config was for.
Now that labels for the notebook name have been added to the notebook build configs (https://github.com/red-hat-data-services/odh-deployer/pull/114) use this notebook name for build status messages shown to the users when builds fail.
=> Use notebook name for build status messages

backend/src/utils/features.ts
**Fixes**: 
Feature flags are not effective
The location of the `data` directory changes and the path to the `features.json` file was not updated
Fix the path to the `features.json` file.
=> Fix for path to feature flags file

frontend/src/pages/learningCenter/LearningCenterFilters.tsx
**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-995
The close button for the filter panel is being shown when the filter panel is not collapsible. Its positioning causes it to show to the far right of the header panel.
Hide the button when the filter panel is not collapsible.
**Browser conformance**:
=> Don't show filter close button unless collapsible

backend/src/routes/api/validate-isv/validateISV.ts, backend/src/utils/resourceWatcher.ts
**Fixes**: 
Fixes https://issues.redhat.com/browse/RHODS-1019
The check for validity was checking the status of the job that runs the validation. That job is returning true regardless of the validation state, the results are put into the validation CM.
When the job complete successfully, check the validation CM for the result status
=> Fix to show accurate validation results on app enablement

backend/src/routes/api/validate-isv/validateISV.ts, frontend/src/pages/exploreApplication/EnableModal.tsx, frontend/src/services/validateIsvService.ts, frontend/src/utilities/useEnableApplication.tsx
**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-1414
Anaconda CE key validation failed in the Dashboard but the tile is Enabled and image available in the spawner. Different failures are not communicated to the user.
Increase the timeout used for watching for the validation job results. Add messaging around each point of failure to communicate what caused the failure.
=> Fix validation response messaging, increase timeout

frontend/src/components/OdhDocListItem.tsx, frontend/src/pages/learningCenter/LearningCenter.scss
**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-1078
The list item for tutorials had incorrect text for the access label. Column widths for the favorite and doc type were taking up too much space.
Fix the text for the tutorials access label to be consistent with the card view. Change the column widths from auto to a reasonable fixed width.
**Screen shots / Gifs for design review**:
=> Fix list view access label for tutorials, column widths.

backend/src/routes/api/components/list.ts, backend/src/types.ts, backend/src/utils/componentUtils.ts, backend/src/utils/resourceUtils.ts
**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-750
Jira: https://issues.redhat.com/browse/RHODS-245
To determine the route for some applications, we need to find the ConsoleLink associated with the application.
Other applications may need to specify an endpoint (full URL) for the route.
Allow the application to specify a ConsoleLink to use to find the URL from (the spec.href field).
Allow the application to specify an endpoint for the route.
Also, allow <CLUSTER_ID/> as a replaceable variable in endpoint routes and for getting started links.
=> Allow use of ConsoleLinks for route determination.

backend/src/types.ts, backend/src/utils/resourceUtils.ts, frontend/src/app/HeaderTools.tsx, frontend/src/types.ts, frontend/src/utilities/useWatchDashboardConfig.tsx
**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-987
There should be no support link for sandbox cluster
Check for a `odh-dashboard-config` config map in the current namespace. If it exists, check the `data.disableSupport` field for `true` to determine if we should prevent including the support link.
=> Add a dashboard config option to hide the support link

frontend/src/__tests__/ExploreApplications.spec.tsx, frontend/src/components/OdhExploreCard.tsx, frontend/src/pages/exploreApplication/EnableModal.tsx, frontend/src/pages/exploreApplication/EnableVariable.tsx, frontend/src/pages/exploreApplication/ExploreApplications.tsx, frontend/src/pages/exploreApplication/GetStartedPanel.tsx
**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-1621
The enable dialog does not show enable results if the dialog is closed and reopened prior to the enable job completion.
Keep the status of the enablement thru the lifecycle and show the current status when opening the enable dialog while the enablement process is still running.
=> Persist enable modal status while in progress

.env.production, frontend/src/app/App.scss, frontend/src/utilities/useWatchDashboardConfig.tsx
**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-1669
The quick start drawer is sized to the height of the application page. If the page gets really long due to lots of tiles or a narrow width, the quick start also gets very long and the action buttons are shown at the very bottom of the drawer requiring the user to scroll to find them.
Size the quick start drawer to the window height so that the action buttons always remain visible w/o scrolling.
**Browser conformance**:
=> Fix to quick start scrolling

backend/src/types.ts, backend/src/utils/resourceUtils.ts, frontend/src/types.ts, frontend/src/utilities/useWatchBuildStatus.tsx
**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-1649
Jira: https://issues.redhat.com/browse/RHODS-997
Build status is not showing correctly. Checks for `pending` should have been for `Pending`. Also checks for most recent build included builds that were cancelled and not necessarily the most recent build. 
Update the status checks to define the real possible values of the status. Ignore cancelled builds when there are other builds already completed or running. Determine the most recent build by examining the build annotation and not the name of the build.
=> Fixes for current image build status determination

frontend/src/app/App.scss
**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-1549
color of the non-selected favorite button does not provide enough contrast making it hard to see
Increase the darkness and double the border width of the button.
**Browser conformance**:
=> Update contrast for the un-favorited favorite icon.

backend/src/types.ts, backend/src/utils/resourceUtils.ts, frontend/src/app/App.scss, frontend/src/app/AppNotificationDrawer.tsx, frontend/src/redux/types.ts, frontend/src/types.ts, frontend/src/utilities/useWatchBuildStatus.tsx, install/odh/base/cluster-role.yaml, install/odh/base/deployment.yaml, install/odh/base/role.yaml
**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-1649
Builds that are not started were flagged as in progress
Track builds that have not yet been started and communicate un-started builds to the user.
Update to not use the base build configs for status.
Upon completion of builds, notify the user of all the failures that occurred.
**Screen shots / Gifs for design review**:
=> Fix to more accurately communicate build statuses

backend/src/routes/api/validate-isv/validateISV.ts
**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-1790
While the validation of the entries succeeded, the attempt to unsuspend the cronjob failed due to it having been updated (the previous suspension) throwing an exception which was then deemed as a validation failure.
Refetch the cronjob in order to unsuspend it properly.
=> Fix for ISV enablement failure due to unsuspend cronjob failure

backend/src/routes/api/validate-isv/index.ts, backend/src/routes/api/validate-isv/validateISV.ts, frontend/src/services/validateIsvService.ts, frontend/src/utilities/useEnableApplication.tsx
**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-1790
The validation job can take longer to run at times causing a timeout response from the server.
Start the validation process, then poll for the results rather than waiting for it to complete.
=> Fix validation timeout, poll for results

frontend/src/pages/exploreApplication/GetStartedPanel.tsx
**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-2164
Applications may want to include links or other controls in the beta text shown in the info side panel in the explore page.
Place the text for the beta notification in a markdown viewer
=> Allow markdown in beta text provided by applications.

.github/workflows/pull_request.yml
Disable integartion test check since it's broken on Node 14, frontend build generates more files than the snapshot.
=> Remove integration broken on node 14

backend/src/routes/api/notebook/index.ts, backend/src/routes/api/notebook/notebooksUtils.ts, backend/src/routes/api/status/index.ts, backend/src/types.ts, frontend/src/types.ts
Updated with REST api BYON notebook image endpoints and new notebook image types.
Here is a link to the BYON REST api:
https://studio-ws.apicur.io/sharing/f34aaaa8-58e0-48fb-b36f-1d91ac5ebf48
Relates to issue #140  and https://github.com/open-services-group/byon/issues/18
=> Added types for notebook image and REST end point stubs.

backend/src/routes/api/notebook/notebooksUtils.ts, backend/src/types.ts
Part of: https://github.com/open-services-group/byon/issues/41
This allows for both full and partial upgrades of the `packages` list. This PR also disables patching of the `software` field.
Example:
```
PUT http://0.0.0.0:4000/api/notebook/{{id}}
Content-Type: application/json
{
"id": "{{id}}",
"packages": [{
"name": "backports.functools-lru-cache",
"version": "1.6.4",
"visible": true
}]
}
```
Changes visibility on the single package with matching name. If the package in the patch payload is not found, the change is simply ignored and request returns 200. Other packages, not mentioned in the patch payload are not affected.
=> feat(byon): Allow python dependency visibility field changes

frontend/src/components/MarkdownView.scss
JIRA issue: https://issues.redhat.com/browse/RHODS-3149
It's because of the version bump of the PF quickstarts, some styles are changed in the quickstarts stylesheet, we need to rewrite the styles for the getting-started panel. And replace those variables with available PF variables.
Results:
=> Rewrite the styles of getting started panel

backend/src/routes/api/status/index.ts, backend/src/types.ts, backend/src/utils/componentUtils.ts, backend/src/utils/resourceUtils.ts, backend/src/utils/resourceWatcher.ts
**Fixes**: 
Fixes [RHODS-3191](https://issues.redhat.com/browse/RHODS-3191)
Fetching all CSVs is extremely expensive. On the cluster noted, there are 90k CSVs. This is the bulk of the issue.
Fetching all Services (2k) is also expensive, we only need a specific service when an ISV is installed and then just one specific service by name.
There is a bug in the build retrievals that can cause an infinite loop fetching builds.
Don't retrieve all CSVs or Services.
Fetch subscriptions and use the matching subscription to then find the specific CSV.
Only retrieve the service by name (across all namespaces) when we need to. 
Return the current inactive timeout interval for builds so that the fetch routine doesn't think it needs to update the …
=> Fix for CPU and Memory issues fetching resources

backend/src/types.ts, frontend/src/pages/notebookImages/NotebookImagesTable.tsx, frontend/src/types.ts
I've noticed error messages are not propagating properly due to invalid schema - there can be more than one error, it's a list.
=> fix(byon): Fix error message propagation

backend/src/types.ts, backend/src/utils/componentUtils.ts
If there's any subscription on a cluster without status, status.installedCSV, or status.installPlanRef, all tiles on the enabled/explore tabs disappear.  To test you can create a bad subscription and restart the dashboard pods.
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
name: bad-sub
namespace: bad-sub
spec:
channel: alpha
installPlanApproval: Manual
name: bad-sub
source: redhat-operators
sourceNamespace: openshift-marketplace
```
=> Fix blank dashboard when a sub without status or installedCSV exists.

.env, Dockerfile, Makefile, README.md, docs/CONTRIBUTING.md, install/build.sh, install/push.sh
The replaces the container s2i build with a Dockerfile.  Going forward we can use this to support CI builds of the Dashboard image
TEST Steps:
1. Run `make build` to build the image using `podman`
1. Run `make push` to push the image to the `IMAGE_REPOSITORY` specified in `.env.local` file
1. Run `make deploy` to deploy the odh-dashboard deployment to your OpenShift cluster
=> Convert to Dockerfile build for dashboard image

.env, backend/src/routes/api/config/configUtils.ts, backend/src/routes/api/config/index.ts, backend/src/types.ts, backend/src/utils/constants.ts, backend/src/utils/resourceUtils.ts, docs/dashboard_config.md, frontend/src/__tests__/ExploreApplications.spec.tsx, frontend/src/app/AppLauncher.tsx, frontend/src/app/HeaderTools.tsx, frontend/src/components/OdhAppCard.tsx, frontend/src/components/OdhExploreCard.tsx, frontend/src/pages/clusterSettings/ClusterSettings.tsx, frontend/src/pages/exploreApplication/ExploreApplications.tsx, frontend/src/pages/exploreApplication/GetStartedPanel.tsx, frontend/src/types.ts, frontend/src/utilities/NavData.ts, frontend/src/utilities/useSegmentTracking.ts, frontend/src/utilities/useWatchDashboardConfig.tsx, manifests/base/kustomization.yaml, manifests/base/odh-dashboard-config.yaml, manifests/base/odh-dashboard-crd.yaml, package.json
The PR adds logic to use the OdhDashboard CR from here: https://github.com/opendatahub-io/odh-manifests/pull/561
The included calls are a GET call which read the CR, if it does not exist a default gets created. The read CR is also merged with the default CR to avoid problems with incomplete configs.
There is also a PATCH call which can later be user by the admin UI to change cluster settings and add notebook sizes to the notebook controller dropdown.
Usage of the CR is documented in the docs folder.
Resolves https://github.com/opendatahub-io/odh-dashboard/issues/159
=> Add logic for dealing with new DashboardConfig CR and add sizes

data/getting-started/jupyterhub.md
JIRA issue: https://issues.redhat.com/browse/RHODS-2739
Just change the title of this getting-started YAML file.
=> show correct getting-started title for jupyterhub

manifests/base/cluster-role.yaml
Pulls in @maroroman https://github.com/opendatahub-io/odh-manifests/pull/590 to allow the dashboard to get secret for the prometheus-k8s service account token
Co-authored-by: maroroman <mroman@redhat.com>
=> Add permissions required for GPU

backend/src/routes/api/config/configUtils.ts, backend/src/routes/api/notebooks/notebookUtils.ts, frontend/src/pages/notebookController/NotebookController.tsx, frontend/src/pages/notebookController/NotebookControllerContext.tsx, frontend/src/pages/notebookController/SpawnerPage.tsx, frontend/src/pages/notebookController/StartServerModal.tsx, frontend/src/pages/notebookController/const.ts, frontend/src/types.ts, frontend/src/utilities/utils.ts
While testing the notebook, I found 2 bugs.
1. There are some logical problems in fetching the secret environment variables, which might cause an infinite loop of fetching or type error. To get rid of this, I removed the `secrets` field from `notebookControllerState`, we don't need that state to indicate the secret name. Also, the `secrets` field will be removed in https://github.com/opendatahub-io/odh-dashboard/issues/282 anyway.
2. After we create the notebook, if we use that 'x' close button to close the modal, it will delete the notebook. I fixed that issue in this PR, too.
=> Remove secret from notebookControllerState, fix modal close bug

README.md, backend/src/types.ts, backend/src/utils/constants.ts, frontend/src/types.ts, frontend/src/utilities/useWatchDashboardConfig.tsx, manifests/base/deployment.yaml, manifests/base/kustomization.yaml, manifests/base/odh-dashboard-config.yaml, manifests/base/odh-dashboard-crd.yaml, manifests/base/role.yaml, manifests/base/service-account.yaml, manifests/kfdef/odh-dashboard-kfnbc-test.yaml, manifests/overlays/authentication/deployment.yaml, manifests/overlays/authentication/kustomization.yaml
* Update dashboard manifest to pull :latest imageTag
* Add ODHDashboardConfig CRD to base manifests
* Add updates for odh-manifests for ODH 1.3 release
This should bring the `manifests` repo current with the latest configs for the dashboard and support deployment via the ODH `kfdef` using the example kfdef in the `manifests/kfdef`
Since this does not include any JH configMaps, you will need to add a groups-config manually
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: groups-config
data:
groups-config: odh-dashboard-groups-config
---
apiVersion: v1
kind: ConfigMap
metadata:
labels:
app: jupyterhub
name: odh-dashboard-groups-config
data:
admin_groups: "odh-jupyterhub-admins"
allowed_groups: "system:authenticated"
```
=> Update manifests for deploying latest dashboard

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yml
Help us track what is new and what is triaged into the set of labels it has.
Added the label to the [repo](https://github.com/opendatahub-io/odh-dashboard/labels) already:
=> Auto add 'untriaged' label to the issue templates

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yml
It is unnecessary to assign people to issues when they are created, we'll filter through them as we look periodically at the labels associated.
=> Removes default bug and feature assignees from new issues

backend/src/routes/api/configmaps/index.ts, backend/src/types.ts
This PR places environment variables and secrets in their own configmaps and secrets respectively. This is the same configuration as jupyterhub singleuser profiles. This is for compatibility purposes and to allow us to reference these resources in the notebook.
Resolves: #282
=> Give environment variables and secrets their own configmaps.

backend/src/routes/api/status/statusUtils.ts, backend/src/types.ts, backend/src/utils/userUtils.ts, manifests/overlays/authentication/deployment.yaml, manifests/overlays/authentication/kustomization.yaml, manifests/overlays/authentication/secret.yaml
* Fixes #179
* Get the User ID from OAuth Proxy instead username.
* Adds the ability to retrieve user.
1. Create a new namespace called `opendatahub`
2. In OpenShift, in the *Operatorhub* section, install the `Open Data Hub Operator` in the `opendatahub` namespace.
3. Once installed, go to *Installed operators*, click the *Open Data Hub* card, and inside that, the `create instance` button.
4. Select YAML view and replace the code with the one below.
```yaml
kind: KfDef
apiVersion: kfdef.apps.kubeflow.org/v1
metadata:
name: opendatahub
namespace: opendatahub
spec:
applications:
- kustomizeConfig:
repoRef:
name: manifests
path: odh-common
name: odh-common
- kustomizeConfig:
parameters:
- name: s3_endpoint_url
value: s3.odh.com
repoRef:
name: manifests
path: jupyterhub/jupyterhub
name: …
```
=> Fix issue with user retrieval

backend/src/routes/api/configmaps/index.ts, backend/src/routes/api/pvc/index.ts, backend/src/routes/api/rolebindings/index.ts, backend/src/routes/api/secrets/index.ts, backend/src/types.ts, docs/dashboard_config.md, frontend/src/pages/notebookController/NotebookController.tsx, frontend/src/pages/notebookController/SpawnerPage.tsx, frontend/src/redux/actions/actions.ts, frontend/src/redux/reducers/appReducer.ts, frontend/src/redux/types.ts, frontend/src/services/configMapService.ts, frontend/src/services/pvcService.ts, frontend/src/services/roleBindingService.ts, frontend/src/services/secretsService.ts, frontend/src/types.ts, frontend/src/utilities/notebookControllerUtils.ts, frontend/src/utilities/useWatchNotebook.tsx, manifests/base/cluster-role.yaml, manifests/base/odh-dashboard-crd.yaml, manifests/base/role.yaml
~~Look only at the last commit. The other commits are based on #331~~
Closes #297 
By setting `notebookNamespace` in the dashboard config, you can create all the notebooks in a different namespace. As well as PVC, config maps and secrets.
Pass `projectName` everywhere so all the functions and API calls has the ability to create K8s resources on the assigned project(namespace).
Create a new project on cluster -> Add/Change the `notebookNamespace` under `notebookController` in the dashboard config -> Try to create a notebook -> You will see the notebook running in your assigned project (namespace).
=> Allow creating notebook in different namespace

manifests/base/cluster-role.yaml
Dashboard SA cannot create `rhods-notebooks-image-pullers` RoleBinding because it grants access itself to get `imagestreams/layers` object.
Needed by https://github.com/opendatahub-io/odh-dashboard/issues/297
=> RBAC: Allow dashboard SA to get IS layers

backend/src/routes/api/nb-events/eventUtils.ts, backend/src/routes/api/nb-events/index.ts, backend/src/types.ts, frontend/src/pages/notebookController/NotebookController.scss, frontend/src/pages/notebookController/NotebookControllerContext.tsx, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx, frontend/src/pages/notebookController/screens/server/StartServerModal.tsx, frontend/src/services/notebookEventsService.ts, frontend/src/types.ts, frontend/src/utilities/notebookControllerUtils.ts, frontend/src/utilities/useNotification.ts, frontend/src/utilities/useWatchNotebookEvents.tsx, manifests/base/cluster-role.yaml
Closes #351 
I use the context to track the last time user clicks on `Start Server`, so I can filter the latest events for a new notebook server.
I moved the process of the events to the frontend, in that case, I can better filter the events.
When spawning the notebook, add the expandable detailed logs to help users track the events.
Start notebook -> Expand the logs -> See the events.
(You could also try to run into some bad situation to see the error status, it will show an alert and stop the spawning process)
=> Add detailed logs for starting server modal

backend/src/routes/api/notebooks/notebookUtils.ts, backend/src/utils/requestUtils.ts, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx, frontend/src/utilities/useWatchNotebooksForUsers.tsx
Resolves #368
We don't show errors to the user when something goes wrong on the server. This will add an alert above the submit button.
When an error happens, it will look something like this (the body of the alert is the kube generated error): 
No easy way to test it, I forced an error on the backend by changing code.
=> Add a SpawnerPage error alert when the server fails

frontend/src/pages/notebookController/screens/admin/NotebookAdmin.tsx, frontend/src/pages/notebookController/screens/admin/NotebookAdminContext.tsx, frontend/src/pages/notebookController/screens/admin/NotebookAdminControl.tsx, frontend/src/pages/notebookController/screens/admin/ServerStatus.tsx, frontend/src/pages/notebookController/screens/admin/StopAllServersButton.tsx, frontend/src/pages/notebookController/screens/server/NotebookServer.tsx, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx, frontend/src/pages/notebookController/screens/server/StopServerModal.tsx, frontend/src/pages/notebookController/useCurrentUser.ts
Closes #293 
1. Create a StopServerModal that works for both the Notebook server page and the Admin page
2. For the Notebook server page, it uses props to set the notebook and handle it (delete)
3. For the Admin page, it uses context to handle it, because it needs to support both Stop server and Stop all servers
4. Add a hook to compare `currentUserState` and username from redux (although I don't need to do this in this PR, I did it)
5. Fix a small issue that is not related to this PR for events. When the node is insufficient, it cannot show the error in the detailed logs, I will now first check whether the event is a warning or not
Try to click `stop server` or `stop all servers` on both Server Control Panel and Admin Panel.
=> Add stop server modal

manifests/overlays/authentication/deployment.yaml
There was a misconfiguration in the --openshift-delegate-urls parameter
for the `authentication` overlay of the dashboard. This caused
authentication/authorization to fail for some use cases, particularly
when attempting to authenticate to the dashboard programmatically using
a bearer token. This change updates the argument to a valid value to fix
this use case.
This has been tested on an openshift 4.11 cluster by performing the following:
* Deploy the ODH operator to your cluster from the operator catalog
* Create a namespace for testing this change:
```
oc new-project auth-fix
```
* Create a kfdef to deploy the current version:
```
cat <<EOF | oc apply -f -
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
name: opendatahub
namespace: auth-fix
spec:
applications:
- …
```
=> Update delegate urls argument for dashboard oauth

backend/src/routes/api/status/statusUtils.ts, backend/src/utils/resourceUtils.ts
Resolves #422 
We didn't allow `system:authenticated` users to get access when we set our groups to it. This was because we tried to fetch a group by that name.
See ticket
=> Allow system:authenicated to work for users

frontend/src/pages/BYONImages/BYONImages.tsx, frontend/src/pages/BYONImages/BYONImagesTable.tsx, frontend/src/pages/BYONImages/DeleteBYONImageModal.tsx, frontend/src/pages/BYONImages/ImportImageModal.tsx, frontend/src/pages/BYONImages/UpdateImageModal.tsx, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
Resolves #352 
Just cleaning up some UI references to BYON. Should be just `Notebook`
Searched for all references and clicked around in the UI to check contextual usages.
=> Cleanup BYON references in the UI

backend/src/types.ts, frontend/src/types.ts, manifests/base/odh-dashboard-crd.yaml
Resolves: #420 
This PR removes the gpuConfig and envvarConfig fields form the CRD as well as adds requirements based on #420
1. Deploy CRD from the manifests of this PR
2. Verify that correct requirements are enforced
=> Add required fields, remove unused fields from CRD

frontend/src/__tests__/notebookControllerUtils.spec.ts, frontend/src/utilities/notebookControllerUtils.ts
Addresses:#410 
Updated the username translation to allow for special character encoding and to conform to the requirement of lower case alphanumeric characters and ```.``` or ```-```.
However, during testing, the following was detected once notebook was created and the user was redirected:
1. Created user with special characters:
iam#foo+bar@odh.io
2. Used this user to log in to ODH Dashboard and spawned a notebook
=> modified username translation to utilize encodeURIComponent

backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts, backend/src/types.ts, frontend/src/pages/clusterSettings/ClusterSettings.tsx, frontend/src/pages/clusterSettings/const.ts, frontend/src/types.ts
Resolves: #354 
Replaced the default ```null``` state of User Data Collection checkbox. Additionally, fixed a potential cause of exceptions due to missing null checks in ```clusterSettingsUtils.ts``` when dashboard config notebook controller spec is not present.
Tested locally
=> Fix User Data Collection checkbox

frontend/src/pages/notebookController/screens/server/EnvironmentVariablesField.tsx, frontend/src/pages/notebookController/screens/server/EnvironmentVariablesRow.tsx, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
Closes #411 
The cause for this issue is the current id is not unique, so when you create 2 env vars fields, they have the same id, and it always finds the first one when you select the checkbox. Now we set every input to a unique id based on their index.
Play around with creating env vars and deleting them, checking the secret checkbox, and so on, make sure there is no warning message in the devTool console.
=> Set unique ID for every env var field and input

frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx, frontend/src/types.ts
Closes #430 
Based on what we did in JupyterHub https://github.com/red-hat-data-services/jupyterhub-singleuser-profiles/blob/master/jupyterhub_singleuser_profiles/ui/src/App/Spawner.tsx#L86-L98, fire the telemetry event when the user creates a notebook.
You may need a segment.io account to test it. Maybe @jgarciao could help to test whether the event is really fired.
=> Add telemetry event for starting server

backend/src/routes/api/components/list.ts, backend/src/routes/api/quickstarts/quickStartUtils.ts, backend/src/types.ts, backend/src/utils/resourceUtils.ts, data/applications/jupyter.yaml, data/getting-started/jupyter.md, frontend/src/components/OdhExploreCard.tsx, frontend/src/pages/enabledApplications/EnabledApplications.tsx, frontend/src/types.ts
Closes #400 
Closes #336 
1. Update backend functions to filter or change the resources that returned to the frontend to make sure it matches the current dashboard config (whether the notebook controller is enabled or not)
2. Add getting-started doc for Jupyter based on https://access.redhat.com/documentation/en-us/red_hat_openshift_data_science/1/html/getting_started_with_red_hat_openshift_data_science/launching-jupyterhub-and-starting-a-notebook-server_get-started
Go to different pages to see the tiles.
=> Update doc on Explore page and Resources page

backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts
Resolves: #443 
During the fetching of the data for the cluster settings page, it starts with defaults and builds up a set of settings. Each step of the way drawing from existing data in the OdhDashboardConfig. However, if your `notebookTolerationSettings` is not in your config, the setting is overriding the default and removing the default from the request.
When the client calls the server to update the data based on a change the user did, the data has an omission and thus runs into an NPE issue.
To reproduce:
1. Remove the `.spec.notebookController.notebookTolerationSettings` key from your OdhDashboardConfig. That causes this issue.
2. Save the page with or without changes once you start up the UI.
=> Allow the Cluster settings page to save with no tolerations settings

frontend/src/app/App.tsx
Resolves: #444 
We don't wait until the user information is fully fetched -- so we get unknown permission problems and can show 404 if they are on a nested route. 
Refreshing the app on the root page and on nested "conditional rendered" pages (based on permissions.
https://user-images.githubusercontent.com/8126518/186885574-039f597f-fe23-4080-97be-465bb15d0460.mov
And a fake error state:
The body of the Alert is the `error.message` -- there is nothing to show if we failed to load the user information.
=> Improve initial Application loading, wait on user info

docs/dashboard_config.md, frontend/src/types.ts, manifests/base/odh-dashboard-crd.yaml
Resolves: #445
Cleanup we didn't do late in ODH Dashboard 2.1 release -- it was requested of RHODS not to impact any migration scripts by modifying the CRD. These values are obsolete now and need to be cleaned up. See the doc update in the PR for more detailed information, but the data was moved to the Notebook.
=> Removing the now unused OdhDashboardConfig status property

backend/src/types.ts, frontend/src/pages/notebookController/screens/server/NotebookServer.tsx
Resolves:#466 
Inverts the buttons for notebook server termination and access.
1. Deploy this PR on a cluster
2. Have a running notebook instance
3. Access Notebook server control panel and test the buttons
=> Invert Access/Stop notebook server buttons on notebook server control panel

frontend/src/pages/notebookController/screens/admin/NotebookActions.tsx, frontend/src/pages/notebookController/screens/admin/NotebookAdminControl.tsx, frontend/src/pages/notebookController/screens/admin/ServerStatus.tsx, frontend/src/pages/notebookController/screens/admin/UserTableCellTransform.tsx, frontend/src/pages/notebookController/screens/admin/const.ts, frontend/src/pages/notebookController/screens/admin/types.ts, frontend/src/pages/notebookController/screens/admin/useAdminUsers.ts
Closes #441 
Based on the design in the issue, I added a new action column that holds a kebab dropdown button, which only shows when the notebook is running. Currently, there is only one option `Stop server` in the dropdown menu but it has a good scalability and could add more actions in the future.
Try to create a notebook, and go back to the admin panel, you can either view the notebook details or stop the notebook by selecting in the dropdown menu.
=> Enable viewing users notebook details from the admin panel

backend/src/routes/api/gpu/gpuUtils.ts, backend/src/types.ts, frontend/src/pages/notebookController/screens/server/GPUSelectField.tsx, frontend/src/services/gpuService.ts
Resolves:#428
Implements handling of the case where no GPUs are configured/present
1. Deploy this PR on a cluster
2. Disable the GPU mock exporter
3. Launch Spawner in ODH
4. No GPU dropdown is rendered nor there is the on-click GPU fetch functionality for this case (refresh is required)
Additionally, the case of available GPUs and existing-but-taken GPUs were tested through modifying the mock GPU exporter, as well as the changes between these three cases.
=> Added handling of the case when no GPUs are configured/present

backend/src/routes/api/notebooks/notebookUtils.ts, frontend/package-lock.json
Resolves: #474 
We (me 😞) failed to properly read the error object. `e.body` is the object behind the call... `e.response.body` is the object behind the error. I effectively hid the errors on createNotebook because of this. Logs didn't even get anything useful.
I have corrected that logging issue and handled the `409` conflict issue if you delete a Notebook -- we also created a Role that needs to be deleted (in the previous implementation) -- now it just ignores when there is a conflict and allows the flow to continue. Which will apply the route to the Notebook & not have an error in the form on the UI.
See ticket for full steps -- just delete your Notebook, keep the Role.
=> Support not having an issue if the Notebook was deleted

backend/src/routes/api/notebooks/index.ts, backend/src/routes/api/notebooks/notebookUtils.ts, backend/src/utils/route-security.ts
Follow up #488 
I'm gonna detail all the tests performed in different sections:
* Ensure notebook creation ✅
* Ensure notebook can read env variables and these variables are created ✅
* Ensure dashboard can read PVC ✅
```bash
❯ oc get configmap kube-root-ca.crt -n odh-notebook
NAME                    DATA   AGE
kube-root-ca.crt   1      17d
```
https://odh-dashboard-opendatahub.apps.lferrnan-odh.dev.datahub.redhat.com/api/configmaps/odh-notebook/kube-root-ca.crt 
**Main branch**
🐞 You can access 
**Bugfix branch**
✅ **You can’t access** —> `{"statusCode":403,"error":"Forbidden","message":"Cannot request a resource that does not belong to you"}`
```bash
❯ oc get configmap jupyterhub-singleuser-profile-lferrnan-envs -n odh-notebook
NAME                                          DATA   AGE …
```
=> Fix issue with requesting kube resources

backend/src/types.ts
Issue was found during testing of the security fix that caused a build issue for images (not finding `server.js`). This is because the backend is importing frontend types.
=> Fix type issues

backend/src/routes/api/notebooks/index.ts, backend/src/routes/api/rolebindings/index.ts, backend/src/routes/api/secrets/index.ts, backend/src/utils/adminUtils.ts, backend/src/utils/route-security.ts, frontend/package-lock.json
Removed dashboard namespace direct allow for gets. We don't make any calls to the dashboard namespace aside from rolebinding and it is already covered in the checks.
Also removed the get all notebooks call, not used by frontend.
Tested as admin, can request resources without issue.
Tested with a basic user and was only able to get my resources and nothing out of dashboard.
=> Don't blanket allow reading of dashboard namespace

backend/src/routes/api/rolebindings/index.ts
Resolves #478 
Adds a case for 409 status code, ignoring the failure.
This solves cases where 2 POST requests are sent to the cluster at the same time causing a conflict for RBs
This one was fun to test
1. Deploy odh-dashboard with current changes
2. Create two browser windows each with the Notebook Spawner
3. Delete whichever image puller RB is used (`opendatahub-image-pullers` in my case)
4. Refresh both windows in quick succession. (I also recommend the F12 debug screen to check success)
5. If network logs show that both windows had a 404 occur (and a POST afterwards) check the pod logs.
6. Expect similar output:
=> Ignore 409 case for RBs

backend/src/routes/api/notebooks/index.ts, backend/src/routes/api/notebooks/notebookUtils.ts, frontend/src/pages/notebookController/screens/server/NotebookServer.tsx
Closes #506 
Instead of waiting for 500ms, now the backend will do a loop fetching every second for 10 sec until it gets the route. Also, if there is no route, it will also fetch it when it detects the notebook is running and no link annotation in it, which makes it more robust.
=> Update the logic of getting and patching the route for notebook

frontend/src/pages/notebookController/SetupCurrentNotebook.tsx, frontend/src/pages/notebookController/notebookControllerContextTypes.ts, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx, frontend/src/pages/notebookController/screens/server/useSpawnerNotebookModalState.ts, frontend/src/utilities/useWatchNotebooksForUsers.tsx
Resolves: #508 
~Contains parts of PR #520~
Immediately after creating a notebook resource (the `PATCH` or `POST` call) we refresh the notebook. It seems when the server is busy with other items, we don't always get back a clean enough version of the Notebook and the modal does not open. It takes up to 30s before we background poll to see if the Notebook changed. This 30s is an eternity. So we will fetch every 3 seconds (or whatever the `FAST_POLL_INTERVAL` env var is) and dial it back to 30s only when the modal opens up.
Spawning a Notebook will speed up the speed we fetch it (can be seen in the network tab). Once the modal is shown, it should dial back down significantly (3s => 30s). 
This is a shot in the dark to fix a RHODS testing issue where sometimes the modal would not show up for …
=> Improve the Start Modal Opening

backend/src/routes/api/health/healthUtils.ts, backend/src/routes/api/health/index.ts, manifests/base/deployment.yaml
Added an insecure API call for general health.  Unauthorized users should still be blocked by oauth-proxy, but readiness probe should be able to get a `{"health": "ok""}` message without any kind of token.  Also changed liveness probe to a tcp check for when the server is up.
Deployed image and tested to make sure crashlooping stopped.
Curled `/api/health`
Dashboard image `quay.io/cfchase/odh-dashboard:pr-543`
=> Update liveness/readiness probe with an endpoint without auth.

frontend/src/components/OdhAppCard.tsx
Resolves: #527 
Using an `onClick` without a `href` on an anchor will prevent the browser from detecting that it is an official link reference. To make it cleanly work with React-Router, I just decided to use `Link`, it supports this functionality for both internal routing and proper a11y on links.
1. Enabled page => Jupyter (KFNBC) enabled
2. Same tab works: normal click
3. New tab works: "CTRL+Click" & "Right Click & Open In new tab"
=> Make Jupyter tile have a proper link

frontend/src/pages/notebookController/screens/server/StartServerModal.tsx, frontend/src/types.ts, frontend/src/utilities/notebookControllerUtils.ts
Resolves: #528 
The modal start time is not an accurate enough time to use. We need the immutable activity time from the Notebook to tell us when it was requested to do something. This way if there are events that are immediate, we can get those. The `FailedScheduling` error that prevents you from spinning up a Notebook when your size is too large happens before the modal opens so we didn't show it (to avoid showing previous attempt events).
Using `x-large` size time from the defaults and not having the space on-cluster for it.
=> Show FailedScheduling issues in the Start Modal

backend/src/utils/userUtils.ts, frontend/src/app/App.tsx, frontend/src/app/HeaderTools.tsx, frontend/src/app/appUtils.ts, frontend/src/app/useApplicationSettings.tsx
Resolves: #551 
Another effort behind the hotfix: #532 
When our OAuth error happens (around the getting/using of the `x-forwarded-access-token` header, we just redirect to an error page.
We should logout instead now. 
Hard to say, the issue doesn't happen often. Current theory is you wait 24h or redeploy to your cluster ... or both?
/cc @lucferbux @dlabaj @DaoDaoNoCode
=> When we get an OAuth Failure, we logout

frontend/src/pages/clusterSettings/ClusterSettings.scss, frontend/src/pages/clusterSettings/ClusterSettings.tsx, frontend/src/types.ts
Resolves: #515 
Added the regexp k8s tells us and a similar error message so the Toleration Key is checked in real time.
https://user-images.githubusercontent.com/8126518/189635127-e9749e3b-e919-48b1-a27e-eb790fa6fb5d.mov
Tested on the Toleration key in the Cluster Settings page.
=> Add name check logic to Toleration in ClusterSettings

backend/src/utils/route-security.ts
Resolves: #553 
When requesting resources with an empty name (aka a GET call `/api/<something>/namespaceName/`) some endpoints would sometimes work if the underly API supported a no-name option. `nb-events` fetches a list of events with a label... if the label is empty, it fetches everything.
Apparently `getNamespacedCustomObject` also does that for Notebooks 🤷 
Fix is to just not allow an empty string name. the security layer will make the name `undefined` if it's actually a route without a name but with a namespace.
=> Secure Routes for Empty Name Property

frontend/src/pages/notebookController/NotebookController.tsx
Resolves: #566 
When an admin user spins up a Notebook for another user, it seems the PVC is hooked in from the Admin to that user's Notebook. Thus anything the user put into their storage, is stored erroneously in with the Admin's storage.
I'm an admin, no tabs in the KFNBC page.
=> Disable the KFNBC Admin Tabs

backend/src/routes/api/configmaps/index.ts
Resolves: #513 
Improved error handling. `toString` on an error (or using the variable in a string template) simply makes the kube library show "HTTP request failed" as that's the basic `.message` on the error. We want to dig into the k8s status object so we can get a meaningful message.
Faking errors on the backend to check different calls. GET => 404 happens when you have not created a notebook before.
=> Support proper errors for configmap requests

frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx, frontend/src/pages/notebookController/screens/server/StartServerModal.tsx, frontend/src/pages/notebookController/screens/server/useSpawnerNotebookModalState.ts, frontend/src/types.ts, frontend/src/utilities/notebookControllerUtils.ts, frontend/src/utilities/useWatchNotebookEvents.tsx
Resolves: #559 
We need to filter the events more so the experience is not jarring and "scary" for users. Having red alerts appear often in the lifecycle of a Notebook starting can make it feel like it does not work.
Filters events for:
- In the first 30s, no `warning` level events are shown -- we only show the normal info events so if there is progress (or a special events like scaling) it can be displayed
- After 30s, the `FailedScheduling` event will become visible and an error -- this is likely because there is a lack of space for your notebook pods
- In the case of auto-scaling... when we get the first event, we suppress all warning events until the failed scaling event (`NotTriggerScaleUp`) is visible
- If the `NotTriggerScaleUp` event happens, we ignore all other events for purpose …
=> Improve event filtering to avoid scary messages

backend/src/types.ts, backend/src/utils/groupsUtils.ts, frontend/src/components/FormGroupSettings.tsx, frontend/src/components/MultiSelection.tsx, frontend/src/pages/groupSettings/GroupSettings.scss, frontend/src/pages/groupSettings/GroupSettings.tsx, frontend/src/pages/groupSettings/groupTypes.ts, frontend/src/services/groupSettingsService.ts, frontend/src/utilities/useWatchGroups.tsx, frontend/src/utilities/utils.ts, manifests/overlays/odhdashboardconfig/kustomization.yaml
-  [X] Avoid constant text --> Done, you're right, changed
-  [ ] Apply to the `GroupSettings` form the `isWidthLimited` property ([docs](https://www.patternfly.org/v4/components/form#form)) ---> **Not applied**, maybe cause we are using an old version of patternfly, but `maxWidth` is missing from `Form`, and when applying `isWidthLimited` is limited to 500px width.
1. Follow the steps in the `CONTRIBUTING` file to `build`, `push` and `deploy` an image of this PR.
2. Navigate to `Settings > User management`
3. Try to add and remove groups
=> Refactor user group settings

backend/src/types.ts, backend/src/utils/route-security.ts
Sanitize notebook resource that tries to inject an envFrom to access secrets or configmaps/
Create a patch.json file that includes `"envFrom": [{"secretRef": {"name": "jupyterhub-singleuser-profile-victim-envs"}}]` and patch a notebook with curl.
```
curl 'http://localhost:4000/api/notebooks/rhods-notebooks/jupyter-nb-cchase-40redhat-2ecom' \
-X 'PATCH' \
-H 'Content-Type: application/json' \
-d @patch.json
```
Sample patch.json:
```
{
"apiVersion": "kubeflow.org/v1",
"kind": "Notebook",
"metadata": {
"name": "jupyter-nb-$USERNAME",
"namespace": "rhods-notebooks"
},
"spec": {
"template": {
"spec": {
"containers": [
{
"image": "image-registry.openshift-image-registry.svc:5000/redhat-ods-applications/s2i-minimal-notebook:py3.8-1.17.0-3",
"imagePullPolicy": "Always",
"workingDir": …
```
=> Delete any envFrom sections from notebook containers.

frontend/src/pages/clusterSettings/ClusterSettings.tsx
Signed-off-by: Luca Giorgi <lgiorgi@redhat.com>
Resolves: #580 
Adds a description to the successful variation of the notification received when saving new settings, as requested in #580 
Ran dashboard locally and confirmed the description appears in the notification
=> Add description to "cluster settings saved" toast

OWNERS
Designate the real @cfchase as a reviewer in this repo
=> Update cfchase in OWNERS

backend/src/routes/api/configmaps/index.ts, backend/src/routes/api/pvc/index.ts, backend/src/routes/api/secrets/index.ts
Resolves: #595
Removed logging of 404 error responses for (yet) non-existing pvcs, configmaps and secrets
1. delete the resources in question, simulating a new user startup
2. open notebook controller spawner
3. verify dashboard logs do not contain error records after completed GET requests on ```api/pvc```, ```api/configmaps``` and ```api/secrets```
=> Remove logging of 404 error responses for pvc, configmaps and secrets

frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
Resolves: #635 
We didn't disable the submit button when env was in error.
Make an env and cause it to be in an error -- button should disable.
=> Disable start server when env is in error

frontend/src/api/network/secrets.ts, frontend/src/k8sTypes.ts, frontend/src/pages/projects/notebook/ConnectedWorkspaces.tsx, frontend/src/pages/projects/notebook/useConnectedNotebooks.ts, frontend/src/pages/projects/screens/detail/ProjectDetails.tsx, frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx, frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTable.tsx, frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTableRow.tsx, frontend/src/pages/projects/screens/detail/data-connections/connectionRenderers.tsx, frontend/src/pages/projects/screens/detail/data-connections/data.ts, frontend/src/pages/projects/screens/detail/data-connections/useDataConnections.ts, frontend/src/pages/projects/screens/detail/data-connections/utils.ts, frontend/src/pages/projects/types.ts, frontend/src/pages/projects/utils.ts
Resolves: #491 
Adds a data connection list that currently only lists a subset of secrets that are AWS secrets.
Eg:
```
apiVersion: v1
kind: Secret
metadata:
annotations:
opendatahub.io/related-notebooks: '["notebook-td8hf5"]' # A notebook I had
labels:
opendatahub.io/managed: 'true' # the key search factor for the fetch all
name: example
namespace: kube-3aadmin-3djwta # my namespace
type: Opaque
stringData: # nonsense data for example
AWS_ACCESS_KEY_ID: something
AWS_SECRET_ACCESS_KEY: password
AWS_S3_ENDPOINT: https://s3.amazonaws.com/
AWS_DEFAULT_REGION: us-east-1
```
Create a Notebook (from the UI), create an AWS Secret (from OpenShift Console -- #670 will cover this on the UI later).
=> Data Connections List

backend/src/types.ts, backend/src/utils/constants.ts, frontend/src/app/AppRoutes.tsx, frontend/src/pages/modelServing/screens/global/EmptyModelServing.tsx, frontend/src/pages/modelServing/screens/global/ModelServingGlobal.tsx, frontend/src/pages/projects/screens/detail/EmptyDetailsList.tsx, frontend/src/pages/projects/screens/detail/ModelServerList.tsx, frontend/src/pages/projects/screens/detail/ProjectDetails.tsx, frontend/src/pages/projects/screens/detail/const.ts, frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx, frontend/src/pages/projects/screens/detail/storage/StorageList.tsx, frontend/src/pages/projects/screens/detail/types.ts, frontend/src/pages/projects/screens/detail/workspaces/WorkspacesList.tsx, frontend/src/types.ts, frontend/src/utilities/NavData.ts, manifests/crd/odh-dashboard-crd.yaml, manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Work for #639 
* Add feature flag for model serving
* Add nav section for global model serving view
* Add dsg section behind the feature flag
1. Deploy the dashboard
2. Check the route and dsg are not available
3. Change the OdhDashboardConfig CRD to turnt to `false` `disableProjects` and `disableModelServing`.
4. Check that both sections are displayed
=> Add empty view and empty dsg section

backend/src/plugins/kube.ts, backend/src/routes/api/gpu/gpuUtils.ts, backend/src/routes/api/status/statusUtils.ts, backend/src/types.ts
Fixes a break in `main`. Introduced by #573
Effectively we need the token for whomever is logged in as far as the k8s library is concerned. The PR above sought that out through the direct path to get the service account token -- but this doesn't work for dev and because of the way the Promise was written, it crashes locally in dev mode because the Promise never finishes.
=> Use the kube config to get the current logged in token

manifests/overlays/authentication/deployment.yaml, manifests/overlays/authentication/secret.yaml
Fix https://github.com/opendatahub-io/odh-dashboard/issues/479
Install the `opendatahub-operator` and patch the CSV image:
``` shell
$ oc edit csv opendatahub-operator.v1.3.0 -n openshift-operator
...
326                 image: quay.io/opendatahub/opendatahub-operator:v1.3.0 -> quay.io/vhire/opendatahub-operator:testoauth
...
```
Edit the `.env` file to use the following image:
```
IMAGE_REPOSITORY=quay.io/samuvl/odh-dashboard:oauth-client
```
Run `make deploy` and wait until the dashboard is deployed and running:
```
$ oc get pods -l app=odh-dashboard -n opendatahub
NAME                             READY   STATUS    RESTARTS   AGE
odh-dashboard-5fbc469d8c-6j7dj   2/2     Running   0          4m9s
odh-dashboard-5fbc469d8c-dbf5w   2/2     Running   0          4m9s …
```
=> Create dedicated OAuthclient

backend/src/utils/route-security.ts, backend/src/utils/userUtils.ts, frontend/src/app/useApplicationSettings.tsx
This PR contains the following:
* Add custom error code when retrieving username
* It will return 401 when the token is deprecated or there is no token
* It will return the default error code of the oc get request in other cases (when there's a cluster problem it will be 500)
* Fixes an issue when the dashboard cannot redirect to oauth proxy and keeps a loop.
In local:
1. Comment [this line](https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/utils/userUtils.ts#L90) to trigger the error.
2. Now the frontend should not reload when displaying the error message.
3. Check that is returning a 401 since the token is not provided.
4. Get a /status call with the cookie session of the cluster.
5. It should return a 200 response.
6. Now disconnect from the VPN to emulate …
=> Fix Oauth Issues when retrieving username

Makefile, install/deploy.sh, install/undeploy.sh, manifests/overlays/authentication/deployment.yaml, manifests/overlays/authentication/secret.yaml
Fix https://github.com/opendatahub-io/odh-dashboard/issues/337
Also improve `deploy.sh` and `undeploy.sh` scripts to not mess up your local kubeconfig file.
Install the `opendatahub-operator` and patch the CSV image:
``` shell
$ oc edit csv opendatahub-operator.v1.3.0 -n openshift-operators
...
326                 image: quay.io/opendatahub/opendatahub-operator:v1.3.0 -> quay.io/vhire/opendatahub-operator:testoauth
...
```
Edit the `.env` file to use the following image:
```
IMAGE_REPOSITORY=quay.io/opendatahub/odh-dashboard:pr-590
```
Run `make deploy` and wait until the dashboard is deployed and running:
```
$ oc get pods -l app=odh-dashboard -n opendatahub
NAME                             READY   STATUS    RESTARTS   AGE
odh-dashboard-59d6fc4455-5mr9c   2/2     Running   0 …
```
=> Generate a random OAuth cookie secret

frontend/src/pages/notebookController/screens/server/NotebookServerDetails.tsx, frontend/src/pages/notebookController/screens/server/SizeSelectField.tsx
Resolves: #690
Changed the "Memory requests" text to "Requests" in launched notebook control panel -> Deployment size details
Added a separator between Limits and Requests in GPU dropdown item descriptions for clarity
Tested locally, examine the edited pages
=> Change wrong "Memory requests" text occurences to "Requests" in notebook controller

frontend/src/k8sTypes.ts, frontend/src/pages/projects/const.ts, frontend/src/pages/projects/notebook/utils.ts, frontend/src/pages/projects/pvc/DeletePVCModal.tsx, frontend/src/pages/projects/screens/spawner/storage/useAvailablePvcSize.ts, frontend/src/pages/projects/screens/spawner/storage/useAvailablePvcs.ts
Some small fixes based on the previous comments, and fix the problem when deleting the PVC with a connected notebook.
=> Add ability to delete attached PVC

.github/ISSUE_TEMPLATE/bug_report.yaml
The bug template is too much -- simplifying it. We almost never care about the state of OpenShift for what happens in our world. If it comes to pass that it is important, the log section is now an "anything" section.
=> Simplify bug report view

frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx
Resolves: #741 
PF still uses IDs for Switches -- workbench name is not unique enough -- combine it with the project name.
Create two projects with one workbench (both named the same thing).
Test the Project view by turning off the 2nd Workbench.
=> Workbenches don't conflict when sharing a name

frontend/src/SDKInitialize.tsx, frontend/src/api/errorUtils.ts, frontend/src/api/index.ts, frontend/src/api/network/projects.ts, frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx
Resolves: #719
Allows us to handle k8s errors more cleanly. This is needed because the SDK swallows errors and we end up in weird .then cases that don't always pan out.
=> Support handling pass-through K8sStatus errors in our network flow

backend/src/routes/api/k8s/pass-through.ts, frontend/src/SDKInitialize.tsx, frontend/src/pages/modelServing/useServingRuntimes.ts, frontend/src/pages/projects/screens/detail/ProjectDetails.tsx, frontend/src/utilities/NavData.ts, frontend/src/utilities/utils.ts
Resolves: #782
Cleans up the feature flag usage and handles the 404 from k8s api that is missing (such as when model serving is not installed on the cluster but enabled in the dashboard)
When Model Serving is enabled, but not installed... this is the state:
=> Handle Model Serving addition cleaner

backend/src/plugins/kube.ts, backend/src/routes/api/gpu/gpuUtils.ts, backend/src/types.ts
Add support for retrieving the oauth token for the `kube.currentUser` via `kube.currentToken`
- Tested with the local application against a dashboard cluster.  (Requires using the public route for the `thanos-querier` service)
- Built the image and deployed in an OCP cluster with GPU nodes
Dashboard works as intended to spawn notebooks with and without GPU nodes
=> Fix kube sa token

frontend/src/api/network/inferenceServices.ts, frontend/src/api/network/projects.ts, frontend/src/api/network/servingRuntimes.ts, frontend/src/pages/modelServing/useInferenceServices.ts, frontend/src/pages/modelServing/useServingRuntimes.ts
Fixes #801 
* Now it will just list objects in namespaces they have access.
* Limits a clusterrole list of InferenceService and ServingRuntime.
1. Create a regular user with no clusterrole permissions
2. With the code added in #806 use the token to fake pass-through API calls
3. Check that you can create new projects, create Model Servers, Models and check the global view
=> Fix bug limiting access to global view to regular users:

backend/src/routes/api/prometheus/index.ts, backend/src/utils/prometheusUtils.ts
Resolves: #832
When the OAuth token expires, it triggers a 500 error from a prometheus call for DS Projects when it tries to get the fill-size of the PVCs that are created.
I tested this by suffixing the Authorization header with extra characters -- thus mimicking an invalid token.
=> Handle Prometheus OAuth Issue

manifests/overlays/authentication/deployment.yaml
Resolves: #838 
When OpenShift expires the token before the dashboard, we get some weird behavior:
As per https://github.com/openshift/oauth-proxy/issues/225#issuecomment-1074908450 we can mitigate this by lowering the cookie expiration time on the dashboard.
Scaled down the operator and set the cookie-expire to low values to make sure it worked.
=> Set oauth cookie expiration to less than OpenShift default

backend/src/routes/api/gpu/gpuUtils.ts
Resolves an issue to ensure that a valid Prometheus query is encoded properly when querying the cluster metrics for running pods with GPUs.
Deployed a dashboard pod in a cluster with enabled GPUs and confirmed that the available number of gpus updates with a gpu notebook pod is started/stopped
No runtime or build errors
Changes to number of available cluster GPUs updates dynamically
=> Fix Prometheus query request encoding when querying for gpu data

frontend/package-lock.json, frontend/src/pages/notebookController/screens/server/NotebookServer.tsx, frontend/src/pages/notebookController/screens/server/StopServerModal.tsx
Resolves: #840 
The issue stemmed from the impersonation value is not used on the admin kebab item -- so it defaulted to wanting to stop the admin's server as their token was in use when it came to the server. 
Using the notebook user annotation to properly target the right user behind the Notebook to stop.
See #840 steps
=> Fix the stop server feature of the administration tab

frontend/src/api/network/pvcs.ts, frontend/src/pages/projects/components/PVSizeField.tsx, frontend/src/pages/projects/components/StorageSizeBars.tsx, frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx, frontend/src/pages/projects/screens/detail/storage/StorageList.tsx, frontend/src/pages/projects/screens/detail/storage/StorageTable.tsx, frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx, frontend/src/pages/projects/screens/detail/storage/StorageWarningStatus.tsx, frontend/src/pages/projects/screens/detail/storage/useStorageStatusAlert.ts, frontend/src/pages/projects/screens/detail/storage/utils.ts, frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx
=> Add status popover when storage is nearly full

frontend/src/api/network/notebooks.ts, frontend/src/pages/notebookController/NotebookLogoutRedirect.tsx, frontend/src/pages/projects/notebook/NotebookRouteLink.tsx, frontend/src/pages/projects/notebook/useRouteForNotebook.ts, frontend/src/pages/projects/screens/detail/ProjectDetails.tsx, frontend/src/pages/projects/screens/detail/useCheckLogoutParams.ts
Closes #808 
There is no way to change the text Hub Control Panel, it's hardcoded in JupyterLab https://github.com/jupyterlab/jupyterlab/blob/master/packages/hub-extension/src/index.ts#L74-L80
The logout success prompt will be triggered twice, have no idea why, left a comment and waiting for reviews.
Create a notebook in DSG, login to the notebook, and try to click the logout and hub control panel button.
=> Modify logout and control panel redirect for project notebooks

backend/src/routes/api/images/imageUtils.ts
Closes #857 
Try to remove the annotations of a custom image stream and go to the notebook controller spawner page. If this change is not applied, you will get errors when accessing the page because the backend is crashed.
After this change even if there is no annotations in the image stream, we can still get it and set it to some default values.
=> Avoid backend crash when there is no annotation in image stream

frontend/src/app/App.scss, frontend/src/app/Header.tsx, frontend/src/components/BrandImage.tsx, frontend/src/components/OdhAppCard.tsx, frontend/src/components/OdhDocCard.tsx, frontend/src/components/OdhExploreCard.tsx
Closes #867 
Add OpenVino CR or any other CRs which doesn't contain `width` and `height` in their SVG definition, use firefox to open the explore page and check whether the icon is shown.
=> render SVG in the card header when height and width are not set

.github/workflows/pr-close-image-delete.yml
Resolves #761 
Replaces #811 
This PR implements a github action that automatically deletes a quay image for a PR that is closed.
1. Create a PR and its image
2. Trigger action by closing a PR 
3. Verify the associated image is deleted
=> Cleanup quay image after PR is closed

frontend/src/api/network/servingRuntimes.ts, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/screens/const.ts, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx, manifests/base/kustomization.yaml, manifests/base/model-serving-role-binding.yaml, manifests/base/model-serving-role.yaml, manifests/modelserving/kustomization.yaml, manifests/modelserving/servingruntimes-config.yaml
Fixes #814 
1. Deploy all the files in the manifest folder
2. Create a new Model Server
3. Check that the ServingRuntime is created with the specification of the `servingruntimes-config` ConfigMap.
4. Now use #806 to fake a regular user.
5. Repeate the same process
6. Ensure regular user with no read options can access the manifest too
=> Add dynamic spec to servingruntime objects

frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx, frontend/src/pages/projects/screens/detail/notebooks/useNotebookDeploymentSize.ts, frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
Closes #826 
When the size cannot be correctly found, we have an error tooltip next to the size which might give you some hint on what's the problem.
For GPUs:
Add GPU to workbench -> Make sure the size is not unknown
For error messages:
Create a workbench -> Change the size in dashboard config CR -> See the error icon and hover to see the tooltip
=> Compare workbench size correctly and add error message

backend/src/routes/api/nb-events/eventUtils.ts, backend/src/routes/api/nb-events/index.ts, backend/src/routes/api/notebooks/utils.ts, frontend/package-lock.json, frontend/src/pages/notebookController/NotebookControllerContext.tsx, frontend/src/pages/notebookController/SetupCurrentNotebook.tsx, frontend/src/pages/notebookController/notebookControllerContextTypes.ts, frontend/src/pages/notebookController/useImpersonationForContext.ts, frontend/src/services/notebookEventsService.ts, frontend/src/services/notebookService.ts, frontend/src/types.ts, frontend/src/utilities/notebookControllerUtils.ts, frontend/src/utilities/useWatchNotebookEvents.tsx
Fixes: #899
We fixed DS Projects to use uid in fetching, but the old Jupyter tile code did not get updated. This updates that -- although due to the frontend/backend separation, this was more convoluted. 
Start a Juptyer Notebook - once the oauth container is in the nb events, cancel. Restarting immediately used to show events from the terminating pod -- now we only see the latest pod events.
=> Fetch Jupyter tile nb-events by pod uid not nb name

frontend/src/pages/projects/notebook/NotebookImagePackageDetails.tsx
This is a follow-up simple fix for #870 to get rid of the warning in the DOM.
=> Follow up fix for the warning in the console due to PF version bump

frontend/src/api/network/servingRuntimes.ts, frontend/src/pages/modelServing/screens/const.ts, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx
As a stopgap until we fully support multiple custom runtimes, we want to allow a backend only configuration to override the default custom Runtime
Fixes bug where UI would die when a custom runtime has not buildInAdapter (which is the case on any custom runtime)
Reads override-config from servingruntimes-config and uses that serving runtime if available
add the following key/value to servingruntimes-config
```yaml
override-config: |
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
name: ''
namespace: ''
labels:
name: ''
annotations: 
openshift.io/display-name: 'Watson NLP Custom'
spec:
supportedModelFormats:
- autoSelect: true
name: chris-watson-nlp-custom
replicas: 1
protocolVersions:
- grpc-v1
multiModel: true
grpcEndpoint: …
```
=> Allow overriding default servingruntime.

.gitignore, backend/src/app.ts, backend/src/routes/api/gpu/index.ts, backend/src/routes/api/k8s/index.ts, backend/src/routes/api/namespaces/index.ts, backend/src/routes/api/prometheus/index.ts, backend/src/utils/constants.ts, backend/src/utils/fileUtils.ts, backend/src/utils/route-security.ts
Closes #717 
Replaces #743
Adds user activity logging in the security layer of the dashboard.
Deployed locally and into a running cluster with ODH Core components.  
- There is no change to existing functionality of any features. 
- Log in to the Dashboard as an admin user
- Navigate to any page that requires Admin permissions
- Check the odh-dashboard pod for logs at `/opt/app-root/src/logs` to confirm that api requests by admin users is properly logged
=> Admin logging

frontend/src/pages/modelServing/screens/const.ts
Fix openvino image reference ir order to be able to pull  it from there.
Fix image pulling in the fallback default template.
#920 
1. Create a cluster with pull secret to allow image fetching
2. Create a malformed `servingruntime-config` configmap
3. Create a new model serving and check the image is being pulled
You can check this too just doing `podman pull registry.redhat.io/rhods/odh-openvino-servingruntime-rhel8@sha256:8af20e48bb480a7ba1ee1268a3cf0a507e05b256c5fcf988f8e4a3de8b87edc6`
=> Fix openvino image reference

frontend/src/api/network/notebooks.ts, frontend/src/api/network/servingRuntimes.ts, frontend/src/api/network/utils.ts, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/screens/projects/ServingRuntimeDetails.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeExpandedField.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx, frontend/src/pages/modelServing/screens/projects/utils.ts, frontend/src/pages/modelServing/screens/types.ts, frontend/src/pages/modelServing/useServingRuntimesConfig.ts, frontend/src/pages/notebookController/screens/server/GPUSelectField.tsx, frontend/src/pages/notebookController/screens/server/useGPUSetting.ts, frontend/src/pages/projects/ProjectDetailsContext.tsx, frontend/src/pages/projects/screens/detail/notebooks/useNotebookGPUNumber.ts, frontend/src/pages/projects/types.ts, frontend/src/types.ts, frontend/src/utilities/imageUtils.ts
Allow ServingRuntimes to specify allowed number of GPUs
Closes: #940 
I've added an annotation to the ServingRuntime specification in the servingruntimes-configmap.yaml
```yaml
data:
override-config: |
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
annotations:
opendatahub.io/gpu-setting: '1' #same as notebook gpuSetting
```
This is meant as a stopgap feature until full support for GPUs is implemented and tested, but hopefully follows the same development flow for servingruntimes-configs without the annotation.
Change redhat-ods-applications servingruntimes-config to add an annotation to the override servingruntime 
`opendatahub.io/gpu-setting: '1'`
`opendatahub.io/gpu-setting: '5'`
`opendatahub.io/gpu-setting: '0'`
`opendatahub.io/gpu-setting: 'hidden'`
no …
=>  GPU serving setting

frontend/src/api/network/notebooks.ts, frontend/src/api/network/utils.ts, frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx, frontend/src/utilities/tolerations.ts
Closes: #903 
DS Projects -- Updates tolerations as the Workbench starts (via the toggle). Edit should be unaffected.
1. Create a Workbench with no toleration setting configured (see Settings => Cluster settings)
2. Enable the toleration settings
3. Turn off/on the Workbench -- see the change (added)
4. Change the toleration setting value
5. Turn off/on the Workbench -- see the change (updated)
6. Disable the toleration settings
7. Turn off/on the Workbench -- see the change (removed)
Note: It should be noted we do not update the config immediately after saving. There is a notification update in #939 that covers this scenario. In dev mode refresh or wait for the config to be returned from the server before testing a turn-on state for the Workbench.
=> Updates tolerations when workbench starts

manifests/base/deployment.yaml
Closes: #942
This PR updates the resource limit to `oauth-proxy` container in dashboard deployment.
This is required to allow large number of concurrent requests during scale testing.
=> Update resources for oauth-proxy container

docs/releases.md
Updating the release process to reflect the following:
- The quay step was no longer needed as we have CI/CD setup to do that effort now
- We needed steps to properly associate the Dashboard with the release tied to the ODH Operator
=> Update the release process with odh-manifest step

backend/src/routes/api/k8s/pass-through.ts, frontend/src/api/apiMergeUtils.ts, frontend/src/api/network/notebooks.ts, frontend/src/api/network/secrets.ts, frontend/src/k8sTypes.ts, frontend/src/pages/projects/screens/detail/data-connections/ManageDataConnectionModal.tsx
fixes: https://github.com/opendatahub-io/odh-dashboard/issues/898
I encapsulated the promise actions into an async function that takes a param `dryRun: boolean`. dryRun adds a queryParam to the k8 api call which calls the api, but does not save results to storage. With this we can run the promise actions in dry mode and if no errors occur, we can rerun the actions normally. This prevents the notebooks from being restarted on error.
Test the same way as described in the issue. However look at the network request going out.
- on successful adds: there should be the following requests (for adding secret and patching notebook (if it was defined in the form))
- one request with ?dryRun:All query param
- one request **after** without dryRun query param
- on failed adds (duplicate names): there …
=> Added dry-run to submit actions

backend/src/utils/prometheusUtils.ts
Resolves: #862 
Using the wrong port for simple metrics the user can get.
- Port 9091 is for users who can see all metrics in the cluster (get namespace permission)
- Port 9092 is for users who can only get metrics in certain namespaces
- Turn down the ODH operator on your cluster
- Replace the ODH Dashboard container's image with the one from the PR
- Log into the Dashboard with your basic user
- Create a project & workbench -- then view the status of the PVC
=> Fix Prometheus PVC Fill Status Call (for basic users)

backend/src/types.ts, backend/src/utils/constants.ts, backend/src/utils/prometheusUtils.ts, frontend/src/pages/modelServing/ModelServingRoutes.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/metrics/utils.ts, frontend/src/pages/modelServing/useModelMetricsEnabled.ts, frontend/src/pages/projects/ProjectViewRoutes.tsx, frontend/src/types.ts, manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml, manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Closes: #946
Follow up of #916 
Enable model serving upstream
Tested both in downstream clusters and upstream clusters.
**For odh**
1. Follow the instructions on https://github.com/opendatahub-io/odh-manifests/pull/732 to deploy latest model and parametrize the deployment
2. Add to the `odhDashboardConfig` the value of the namespace where the model is deployed in `modelMetricsNamespace `
3. Test that you can deploy a model and access the metrics
4. Now remove the value in `modelMetricsNamespace`
5. Check that you cannot access  the model visualization (changes need to propagate due to the watcher)
=> Enable model serving metrics upstream

frontend/src/api/network/servingRuntimes.ts, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx, frontend/src/pages/modelServing/screens/projects/utils.ts
Fix #893 
Add error handling for the dynamic spec of the ServingRuntime object.
1. Delete the `servingruntimes-config` ConfigMap
2. Create a new Model Server
3. Check there's a warning now in the modal
4. Create a new `servingruntimes-config` ConfigMap with a `default-config` key
5. Check that the alert is gone
=> Improve Model Server modal error handling with dynamic spec

docs/releases.md
Update the release doc to include instruction for adding the OWNERS file to the release process for odh-manifests
N/A
N/A
=> Add update of the OWNERS file to the release doc

frontend/src/components/FavoriteButton.tsx, frontend/src/components/OdhDocCard.tsx, frontend/src/components/OdhDocListItem.tsx, frontend/src/pages/learningCenter/LearningCenterDataView.tsx
Closes #966 
Before (Card View):
After (Card View): 
Before (List View):
After (List View):
Before and After Empty State - no violations:
=> Address a11y violations in Resources screen(s)

backend/src/devFlags.ts, backend/src/routes/api/dev-impersonate/index.ts, backend/src/routes/api/status/statusUtils.ts, backend/src/types.ts, backend/src/utils/constants.ts, backend/src/utils/directCallUtils.ts, backend/src/utils/route-security.ts, backend/src/utils/userUtils.ts, docs/SDK.md, frontend/src/app/HeaderTools.tsx, frontend/src/redux/actions/actions.ts, frontend/src/redux/reducers/appReducer.ts, frontend/src/redux/types.ts, frontend/src/services/impersonateService.ts, frontend/src/utilities/const.ts
Closes: #949
This PR adds support for impersonating pass-through API calls with a regular user token.
The main goal here is just to avoid disabling backend functionality in development which needs special admin roles (admin settings, regular jupyter notebooks, dsg project creation...) but enabling pass-through requests with a regular user token.
To enable this:
1. Get a regular user Openshift username and password
2. Add the `DEV_IMPERSONATE_USER` and `DEV_IMPERSONATE_PASSWORD` variables to your env variables file with the regular user's username and password as the values.
3. Click on your username name in the upper right corner of the dashboard
4. Select `Start impersonate`
5. This way you can replicate some bugs like this:
=> Add faker for the pass through api to enable regular user testing

frontend/src/components/FormGroupSettings.tsx, frontend/src/components/MultiSelection.tsx
Closes #967 
User and Group Settings - Before:
User and Group Settings - After:
Cluster Settings - no violations:
=> Address a11y violations in Settings screens

backend/package.json
Cleans up the log file introduced in https://github.com/opendatahub-io/odh-dashboard/pull/914
Every time we start our dev environment is a good time to clean up the logfile. If we don't, it grows indefinitely. I hit over 5mb recently... it likely will grow indefinitely as there is no cleanup mechanism.
This is by design for production, but for development it's unnecessary.
=> [Dev] Clean up logfile for dev starts

frontend/src/api/network/inferenceServices.ts
Closes #968 
1. Create two data science projects
2. In each project, deploy a model with the same name
3. Go to the global model serving page
4. Check if both of the models are shown on the table
=> Allow duplicated model name in different projects on global serving page

frontend/src/components/Table.tsx, frontend/src/pages/notebookController/screens/server/SizeSelectField.tsx, frontend/src/pages/projects/notebook/ConnectedNotebookField.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookTable.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx, frontend/src/pages/projects/screens/detail/storage/StorageTable.tsx, frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx, frontend/src/pages/projects/screens/projects/EmptyProjects.tsx
**Needs rebase** - waiting on #983. Please do not review/merge until #983 is merged! 
Towards #965  
**Note: This PR follows the existing PF a11y convention for unique IDs within expandable table rows.** 
Add storage modal - a11y issue with "Connected workbench" dropdown. 
Before:
After:
Project details view. A11y issue with "Cluster storage" expandable row items not having unique IDs
Before:
After:
Project details view. A11y issue with "Workbenches" expandable row items not having unique IDs
Before:
After:
=> Fix a11y issues related to Cluster Storage

frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionExistingField.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionSection.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenInput.tsx, frontend/src/pages/projects/components/DeleteModal.tsx, frontend/src/pages/projects/screens/projects/EmptyProjects.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/EnvTypeSelectField.tsx
**Do not merge/review, needs rebase**
Towards #965 
Delete data connections modal - before:
Delete data connections modal - after:
Configure model server modal - before:
Configure model server modal - after:
Deploy model modal - before:
Deploy model modal - after:
=> fix a11y issues in data connections modal and deploy models modal

backend/src/routes/api/k8s/pass-through.ts, backend/src/routes/api/namespaces/index.ts, backend/src/routes/api/namespaces/namespaceUtils.ts
Closes #963 
We can use [SelfSubjectReviewAccess](https://kubernetes.io/docs/reference/kubernetes-api/authorization-resources/self-subject-access-review-v1/) to check the permissions of a specific user to some resources. For this issue, we need to check the update permission to the given project, but everything needs to be done at the backend so we need to call `passThrough` and the k8s API endpoint directly before the service account do the labels patching.
Prerequisite: You must have 2 accounts on the cluster, 1 as the cluster admin (ADMIN) and one as the regular user (USER).
1. Deploy the image of this PR `pr-991` to your dashboard pod
2. Create a regular project (non-DSG project) using the OpenShift console or the oc command with the ADMIN account
3. Login to the dashboard with both …
=> Check user permissions before promoting data science projects

frontend/src/pages/notebookController/NotebookLogoutRedirect.tsx, frontend/src/pages/projects/notebook/NotebookRouteLink.tsx, frontend/src/pages/projects/notebook/useRouteForNotebook.ts
Closes #858 
There is no good way to test it because once you delete the route, it will recreate one immediately before re-fetching it. I tested it by changing the `notebookName` to something else, which will give you a 404 error when you are trying to get the route, but the `isRunning` status is always accurate. In this way, I can toggle the switch and see if the error is set or not when based on the notebook status.
=> Suppress 404 error for notebook route when the notebook is not running

frontend/src/pages/modelServing/useModelMetricsEnabled.ts
Closes: #998
Disable model metrics by using the hook to control if it's enabled or not and always set it to false.
- Model Serving Global Page => Model Table (link on the name)
- DS Projects => Model Serving Runtime Models => Model Table (link on the name)
Before
After
Not to be tested at this time.
=> Disable Model Metrics

frontend/src/components/Table.tsx, frontend/src/pages/projects/components/PasswordInput.tsx
Towards #965 , specifically DS Projects page: "1-n Projects added"
```diff
- The only changes in this PR are related to the pagination component within Table.tsx. 
- Please only review the pagination updates in Table.tsx.
```
Data Science Projects List - before:
Data Science Projects List - after:
=> Fix a11y issue with Data Science Projects: Pagination

backend/src/utils/adminUtils.ts
Closes #878 
The reason is when a group is not found, an error will be thrown, which will break the whole check access loop. If we put the try-catch block inside the loop, the problem will be fixed.
See the instructions in the issue, the same way to test it.
=> Make sure nonexistent user group not change the permission of current admin permission

backend/src/routes/api/dev-impersonate/index.ts, backend/src/routes/api/gpu/gpuUtils.ts, backend/src/routes/api/k8s/index.ts, backend/src/routes/api/k8s/pass-through.ts, backend/src/routes/api/proxy/index.ts, backend/src/utils/httpUtils.ts, backend/src/utils/prometheusUtils.ts, frontend/src/api/apiMergeUtils.ts, frontend/src/api/index.ts, frontend/src/api/models/index.ts, frontend/src/api/models/pipelines.ts, frontend/src/api/pipelines/callTypes.ts, frontend/src/api/pipelines/callUtils.ts, frontend/src/api/pipelines/custom.ts, frontend/src/api/pipelines/k8s.ts, frontend/src/app/AppRoutes.tsx, frontend/src/concepts/README.md, frontend/src/concepts/pipelines/TestPipelines.tsx, frontend/src/concepts/pipelines/context/PipelinesContext.tsx, frontend/src/concepts/pipelines/context/index.ts, frontend/src/concepts/pipelines/context/usePipelineNamespaceCR.ts, frontend/src/concepts/pipelines/context/usePipelinesAPIRoute.ts, frontend/src/concepts/pipelines/kfTypes.ts, frontend/src/concepts/pipelines/types.ts, frontend/src/k8sTypes.ts, frontend/src/typeHelpers.ts
Closes: #924
Pipelines API will be a little different than other APIs we have. It will have two layers of being enabled.
At the Dashboard level - A feature flag (not included in this PR) -- this will eventually show/hide UI elements
At the Namespace level - A custom Pipeline CR needs to be present to interact with the 
- (setup) From Client -- when the user "enables" Pipelines
- Create Pipelines CR (namespaced)
- Call node backend (K8s API)
- (in the background) Pipeline stack watching the CRs
- Creates a k8s Route object in namespace<sup>1</sup>
- (setup) From Client
- Fetch KF Route & store the value
- (pipeline functionality) From Client
- Using stored route
- Call node backend (Proxy API<sup>2</sup>)
Notes:
- K8s Route object in namespace<sup>1</sup>: This route will be the target of …
=> Pipeline API Framework

backend/src/routes/api/k8s/index.ts, backend/src/routes/api/k8s/pass-through.ts, frontend/src/api/index.ts, frontend/src/api/models/k8s.ts, frontend/src/api/useAccessReview.ts, frontend/src/k8sTypes.ts, frontend/src/pages/projects/screens/projects/EmptyProjects.tsx, frontend/src/pages/projects/screens/projects/LaunchJupyterButton.tsx, frontend/src/pages/projects/screens/projects/ProjectListView.tsx, frontend/src/pages/projects/screens/projects/ProjectView.tsx
Closes #619 
Add a hook called `useAccessReview` that makes a k8s API call and creates [`SelfSubjectAccessReview`](https://kubernetes.io/docs/reference/kubernetes-api/authorization-resources/self-subject-access-review-v1/), which you can get whether you are allowed to do some specific operations to resources.
Apply that hook to the DSG page and check the permission of creating the `Project` resource. When a user is not permitted to create a new project, we hide the create button for both the empty project page and the project list view page.
Sorry I didn't attach the screenshots of the UX changes, thanks @andrewballantyne for helping add that in the [comment](https://github.com/opendatahub-io/odh-dashboard/pull/1013#discussion_r1136181096). Please review the changes and give feedback. cc …
=> Add useAccessReview hook and apply it to create project button

frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx, frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx, frontend/src/pages/projects/screens/spawner/const.ts, frontend/src/pages/projects/screens/spawner/dataConnection/DataConnectionField.tsx, frontend/src/pages/projects/screens/spawner/dataConnection/ExistingDataConnectionField.tsx, frontend/src/pages/projects/screens/spawner/dataConnection/useNotebookDataConnection.ts, frontend/src/pages/projects/screens/spawner/environmentVariables/EnvConfigMap.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/EnvSecret.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/EnvUploadField.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/utils.ts, frontend/src/pages/projects/screens/spawner/service.ts, frontend/src/pages/projects/screens/spawner/spawnerUtils.ts, frontend/src/pages/projects/screens/spawner/types.ts, frontend/src/pages/projects/types.ts
closes https://github.com/opendatahub-io/odh-dashboard/issues/779
Created a new data connection section
Test that you can:
1. create a new workspace with a new data connection
2. create a new workspace with an existing data connection
3. edit a workspace with a new data connection
4. edit a workspace with an existing data connection
only one data connection per workspace. but multiple workspaces can share a connection
=> added data connection section

frontend/src/api/prometheus/serving.ts, frontend/src/api/prometheus/usePrometheusQueryRange.ts, frontend/src/api/prometheus/useQueryRangeResourceData.ts, frontend/src/pages/modelServing/ModelServingRoutes.tsx, frontend/src/pages/modelServing/screens/const.ts, frontend/src/pages/modelServing/screens/metrics/GlobalInferenceMetricsWrapper.tsx, frontend/src/pages/modelServing/screens/metrics/InferenceGraphs.tsx, frontend/src/pages/modelServing/screens/metrics/MetricsChart.tsx, frontend/src/pages/modelServing/screens/metrics/MetricsPage.tsx, frontend/src/pages/modelServing/screens/metrics/ModelServingMetricsContext.tsx, frontend/src/pages/modelServing/screens/metrics/RuntimeGraphs.tsx, frontend/src/pages/modelServing/screens/metrics/types.ts, frontend/src/pages/modelServing/screens/metrics/utils.ts, frontend/src/pages/modelServing/screens/projects/ProjectInferenceMetricsWrapper.tsx, frontend/src/pages/modelServing/screens/projects/ProjectRuntimeMetricsWrapper.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx, frontend/src/pages/modelServing/screens/types.ts, frontend/src/pages/projects/ProjectViewRoutes.tsx
Work towards: https://github.com/opendatahub-io/odh-dashboard/issues/1022
Added the Runtime Metrics page & reworked the Inference Metrics page. Added a stacked line chart.
Global - Inference Metrics
Project - Metrics kebab item added to Runtime:
Project - Runtime Metrics
Project - Inference Metrics
Scale options
Stacked Line Chart (random data):
Things that still need to be done (post this PR):
```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
name: odh-with-modelmesh
namespace: opendatahub
spec:
applications:
- kustomizeConfig:
repoRef:
name: manifests
path: odh-common
name: odh-common
- kustomizeConfig:
overlays:
- additional
repoRef:
name: manifests
path: notebook-images
name: notebook-images
- kustomizeConfig:
repoRef:
name: manifests
path: odh-notebook-controller
name: …
```
=> Fix Graphs & Configure Infrastructure

frontend/src/pages/projects/components/PVSizeField.tsx
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1030
removed upper limit on create pvc. You can now set it to any cluster and the cluster should limit if it has to.
try setting the pvc size to a large number
@DaoDaoNoCode is creating the story for this page in one of his PRs, so I will wait until that is in to avoid having to merge two implementations of the same story
not really a UI change (just removing a limit)
=> removed upper limit on pvc size

frontend/src/__mocks__/mockDashboardConfig.ts, frontend/src/__mocks__/mockNotebookK8sResource.ts, frontend/src/pages/projects/screens/detail/ProjectDetails.stories.tsx, frontend/src/pages/projects/screens/detail/notebooks/useNotebookDeploymentSize.ts, frontend/src/utilities/valueUnits.ts
Closes #1012 
Creates 2 functions named `isCpuLimitEqual` and `isMemoryLimitEqual` to compare size limit CPU and memory. There were some problems with the regex `/^(\d+)(.*)$/` before. For example, if you use `0.5` to match it, you will get back the match array `['0.5', '0', '.5']`. However, what we want is actually `['0.5', '0.5', '']`, so I made some changes to the regex to make sure it can separate value and unit and not mix unit and float up.
Before: 
After: 
1. Add the size snippet as described in the issue to your dashboard config CR
2. Create a workbench using that size
3. Check if the size is correctly found on the workbench list
Add XSmall size to the mock dashboard config and add a mock notebook using that size but in a different format. Check the text to make sure the size show …
=> Change the way comparing notebook container size to make sure it matches correctly

backend/src/types.ts, backend/src/utils/notebookUtils.ts, docs/dashboard_config.md, manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml
Closes #1029 
Add `storageClassName` field under `notebookController` settings in dashboard config CR, which allows the user to specify the `storageClass` they want to use for the PVC of the Jupyter notebook they spawned with the notebook controller.
1. Edit odhDashboardConfig CR and add `storageClassName` as the storage class you want to set under the `notebookController` field
2. Wait for 2 mins for the dashboard to read the new settings
3. Go to the Jupyter tile to spawner a notebook (If you spawned one before, please delete the PVC of your notebook in the OpenShift console to make sure we can create a new PVC)
4. Go to the OpenShift console to check the new PVC storageClassName, it should change to the one you set just now
5. Remove the `storageClassName` in the dashboard config CR …
=> Add storageClassName field to dashboard config for notebook controller

frontend/src/__mocks__/mockServingRuntimeK8sResource.ts, frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.stories.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1025
The issue was that service accounts and role bindings will only be created when a _new_ model server is created with auth enabled. Because enableTokenAuth() is only run on a new model server, not on edit. So if you create. a new model server without auth, then those accounts never get added.
In edit mode, secrets are only created and added, no service account is added.
The solution I went with is to add those service accounts and role bindings on creation, no mater if auth is enabled. 
2. Add a runtime without any tokens
3. Edit the runtime and add a token & save
WIP, since this is the last PR in this section, im writing the test now
no ui changes
=> service accounts always add

.github/workflows/dispatch_on_crd_change.yaml
Prerequisite for: https://github.com/opendatahub-io/opendatahub-operator/pull/205
This workflow sends a dispatch whenever a pull request is merged that modifies the crd folder of the dashboard repository. The operator has a workflow that then copies these changes automatically.
This PR was tested using https://github.com/nektos/act to locally verify that the workflow is sending the dispatch correctly.
To test this in real conditions, a fork of the operator and dashboard is required:
1. Create a pull request in the odh-dashboard fork that changes a file in /manifests/crd folder 
2. Merge the PR into the main branch of the fork
3. Verify that the action has been triggered
4. Verify dispatch reached opendatahub-operator fork sync workflow and has triggered it.
No tests are done for github …
=> Add github dispatch for operator sync workflow

.github/ISSUE_TEMPLATE/internal_story.yml
Help with creating lots feature tickets for a given tracker ticket (https://github.com/orgs/opendatahub-io/projects/24/views/23).
[Viewing the file](https://github.com/opendatahub-io/odh-dashboard/blob/342ea7175a8addc97c33b3a459698d9602eeb3b4/.github/ISSUE_TEMPLATE/internal_story.yml) directly allows you to see the template in a nicer fashion than the markdown.
=> Make story template

frontend/src/pages/projects/screens/spawner/service.ts
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1071
fixed the spawner form data connection section submit flow. Issue was that there was no check to remove the existing data connection when a new connection was added. It only checked when an existing connection was used.
Now the flow is:
- use new data connection var: only defined when data connections are enabled and new data connection is selected 
- use existing data connection var: only defined when data connections are enabled and existing data connection is selected and that data connection is not equal to the old data connection
So now we remove the old data connection if a new var is defined, existing var is defined or data connection have been disabled
- create a new workbench with a data connection
- edit …
=> fixed data connection flow

frontend/src/k8sTypes.ts, frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
Closes: #1111
When OpenVINO image is used in the Workbench creation, it doesn't possess the property on the tag `from.name` -- we use this to track our segment.io even when it is disabled. This gave us an NPE -- but after the form was done but before we routed... so it caused a successful completion of the form but not the submitting to segment.io (or to our wrapper when it was disabled).
Fixed by simply changing it to `imageStream.metadata.name` + `imageVersion.name` with some fallbacks if the image tag doesn't have the metadata of `from`.
On a RHODS cluster with OpenVINO installed. Create workbench using the image + submit. 
No tests.
=> Fix OpenVINO Workbench Creation

frontend/src/pages/projects/screens/spawner/environmentVariables/EnvSecret.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/EnvUploadField.tsx
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1110
added a prop too pass a function into the env field that applies the function before submitting
1. Have a project
2. Create a Workbench
3. Env Vars => Secret => Upload Secret
4. Drag and drop a secret file (you can grab this from OpenShift Console and save it as a file in it's encoded state)
bug fix -> no new tests
=> decode secret values

frontend/src/api/k8s/templates.ts, frontend/src/components/Table.tsx, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeContext.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeEnabledToggle.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimesListView.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimesTableRow.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimesView.tsx, frontend/src/pages/modelServing/customServingRuntimes/templatedData.tsx, frontend/src/pages/modelServing/customServingRuntimes/utils.ts, frontend/src/utilities/useDebounce.ts, frontend/src/utilities/useDraggableTable.ts, frontend/src/utilities/useTableColumnSort.ts
Closes #1077 
Closes #1079 
Closes #1146 
- Add a table that reads the `Templates` and shows them
- Order the table based on the dashboard config `templateOrder` field
- Add a drag and drop function to the table rows, which could update the order with 5 seconds debounce
- Add the annotation `opendatahub.io/template-enabled` to reflect whether a serving runtime template is enabled. If the annotation doesn't exist, we can think it's enabled. So only when the annotation is `false`, we think it's disabled.
TODO:
~~1. Finish Deployed Models column #1157~~
2. Add dropdown items to the table row #1083 
1. Create 2 or more templates on the cluster, you can use the template [here](https://github.com/opendatahub-io/odh-dashboard/pull/1098#issuecomment-1506006377), just change the name to make them …
=> Add custom serving runtimes table

frontend/src/pages/BYONImages/BYONImagesTable.tsx, frontend/src/pages/BYONImages/ImportImageModal.tsx, frontend/src/pages/BYONImages/UpdateImageModal.tsx
Closes #1100 
Import notebook images modal - before:
Import notebook images modal - after:
Edit notebook images modal - before: 
Edit notebook images modal - after:
Notebook image settings list - before:
Notebook image settings list - after:
=> Fix a11y violations in Settings -> Notebook Images

frontend/src/pages/modelServing/screens/global/InferenceServiceStatus.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx, frontend/src/pages/projects/components/StorageSizeBars.tsx, frontend/src/pages/projects/notebook/NotebookRouteLink.tsx, frontend/src/pages/projects/notebook/NotebookStatusText.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx
Closes #1155 
Add screenreader and tabIndex to error status icons wrapped by tooltips. 
For status icons wrapped by tooltips, added icon to tab order and made icon screenreader accessible.
=> Fix error status icons with tooltips: added screenreader and tabIndex 

frontend/src/pages/modelServing/customServingRuntimes/useCustomServingRuntimesEnabled.ts, frontend/src/pages/modelServing/customServingRuntimes/useTemplateOrder.ts, frontend/src/pages/modelServing/customServingRuntimes/useTemplates.ts, frontend/src/pages/modelServing/screens/projects/useServingRuntimeSecrets.ts, frontend/src/pages/modelServing/useInferenceServices.ts, frontend/src/pages/modelServing/useModelServingEnabled.ts, frontend/src/pages/modelServing/useServingRuntimes.ts
Closes #1089 
Check if model serving and custom serving runtimes are enabled in all the fetch hooks that are related to these features. If it's disabled, return NotReadyError instead of the fetch function.
1. Go to the project details page
2. Go to the network tab of the dev console of your browser (Chrome or Firefox)
3. Check the API calls to see if it's fetch `servingruntimes` and `inferenceservices`
4. Go to the dashboard config to disable the model serving feature
5. Wait for ~2 mins until the dashboard fetch the last config
6. Refresh the page to see the API calls, now the page shouldn't fetch `servingruntimes` and `inferenceservices`
7. Enable the model serving feature again
8. Check if the resources are fetched again
=> Control model serving related fetching based on the feature flags

frontend/src/pages/projects/screens/spawner/dataConnection/DataConnectionField.tsx
Closes #1072 
@kywalker-rh @vconzola Please check the UX changes when you are available.
Put the radio sections for choosing new or existing data connections into the `body` of the checkbox.
Before:
After:
1. Go to project workbench spawner page
2. Check the `Use a data connection` checkbox at the bottom
3. Check if there is an indentation in the body section
Only UX changes, and tests are not applicable.
=> Fix data connections indentation issue on the spawner page

frontend/src/pages/projects/screens/spawner/spawnerUtils.ts, frontend/src/pages/projects/types.ts
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1206
When secret upload was added, the category for the env upload was "upload" for both secrets and config maps. B/c the upload for secret was checked first, uploaded envs would always be created as secrets.
create a workbench with an uploaded config map and make sure it is created as a config map and not a secret
no impact
no ux changes
=> made env upload category more specific

frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.ts
Closes: #1233
Uses the `runAfter` state if any of the nodes have it -- to prevent mixing and matching and potentially causing duplicate lines.
From:
To:
Using a Pipeline that has runAfter usage to view the Pipeline. Let me know if you need to see my example, it's taken from another source and I'm not sure how public that is.
None -- no tests.
=> Fix for when topology has visual runAfters in use

Dockerfile
Addresses #1123 to make sure that when the container is running with a random UID in OpenShift, the `/opt/app-root/src/.npm` folder is writable by any user in the `root` group
I can reproduce this locally with a v2.9.2 image by running the container with a UID different from the `default` user ID (`1001`)
```
podman run --rm --user 65536 quay.io/opendatahub/odh-dashboard:v2.9.2 
````
Deployed into my dev cluster that was experiencing the issue with the quay.io/opendatahub/odh-dashboard:v2.9.2 image and patched in the quay.io/opendatahub/odh-dashboard:pr-1256 image with no issues
No dashboard functionality was modified
Deploy the PR container in OpenShift with `make deploy` to ensure that there are no CrashLoopErrors
=> Make the .npm directory writable by the root group

manifests/modelserving/kustomization.yaml, manifests/modelserving/ovms-gpu-ootb.yaml, manifests/modelserving/ovms-ootb.yaml
Closes: #1257 
1. Deploy the manifest files
2. Check that you can see both Custom Serving Runtimes as pre-installed
Test will be done in the follow up testing section for Custom Serving Runtime
=> Add OVMS OOTB with GPU support

Dockerfile
This is a follow-up to #1256 that replaces the hardcoded reference to `/opt/app-root/src` which is the `$HOME` directory inherited from the `ubi8-nodejs18` base image.  This add portability so that the home directory can be changed without breaking the image since the [npm cache](https://docs.npmjs.com/cli/v9/using-npm/config#cache) location default to `$HOME/.npm`
You can verify the $HOME env var is defined using the [skopeo](https://github.com/containers/skopeo) tool to query the image metadata
```
skopeo inspect docker://registry.access.redhat.com/ubi8/nodejs-18:1 | jq '.Env'
skopeo inspect docker://quay.io/opendatahub/odh-dashboard:v2.10.0 | jq '.Env'
```
Manually built the image using `make build` and deployed in my dev environment
There is no change to functionality
=> Use ${HOME} envvar as root dir for .npm folder in Dockerfile

backend/src/routes/api/images/imageUtils.ts, backend/src/types.ts, backend/src/utils/constants.ts, frontend/src/__tests__/dockerRepositoryURL.spec.ts, frontend/src/k8sTypes.ts, frontend/src/pages/BYONImages/BYONImagesTable.tsx, frontend/src/pages/BYONImages/ImageErrorStatus.tsx, frontend/src/pages/BYONImages/ImportImageModal.tsx, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx, frontend/src/pages/projects/screens/spawner/imageSelector/ImageSelectorField.tsx, frontend/src/pages/projects/screens/spawner/spawnerUtils.ts, frontend/src/types.ts, frontend/src/utilities/NavData.tsx, frontend/src/utilities/const.ts
Closes #1085 
The PR did the following things:
1. Use regex to match the repository URL, which could help correctly parse the hostname and the tag name
2. If the user doesn't input the tag name, we will set the tag name default to `latest`, because it will automatically fetch the latest tag if you create an image stream without specifying the tag name
3. If the user inputs the tag name, we will set the tag name of the BYON image to the same as the tag name user is importing
Because some docker container images might not have the `latest` tag or might not have the tag user specifies, it could throw an error if the tag cannot be found. In this situation, we show the error in the BYON image table to the admin users and hide the image from the spawner page of both the KFNBC and DS projects. …
=> Parse BYON repository URL correctly

manifests/base/deployment.yaml, manifests/overlays/authentication/deployment.yaml
Closes #1045 
Resolve issue with Service Accounts being unable to authenticate to the dashboard without cluster scope permissions
Deployed kfdef manually and followed reproducability instructions in #1045
1. Install ODH with a kfdef in a namespace called `opendatahub` with the following manifests url:
```
repos:
- name: manifests
uri: >-
https://github.com/strangiato/odh-manifests/tarball/dashboard-oauth-delegate-url-fix
```
2. Create a test service account:
```
oc create sa test-connection
```
3. Grant permissions to the service account:
```
oc policy add-role-to-user view system:serviceaccount:opendatahub:test-connection
```
4. Verify SA has permissions to list service:
```
TOKEN=$(oc create token test-connection -n opendatahub)
oc login --token=${TOKEN}
oc get services odh-dashboard -n …
```
=> add dynamic namespace to delegate-url oauth arg

frontend/src/api/k8s/serviceAccounts.ts, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenInput.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenSection.tsx, frontend/src/pages/modelServing/utils.ts
Closes #1259 
Test if an admin user can create a model server
1. Create a new project
2. Create a model server with authentication enabled
3. Create some secrets
4. Check that is working as expected
Test if a user with edit permission can create a model server
1. Create a new project
2. Add a user without cluster permissions with edit role in the project sharing panel
3. Log in as this regular user
4. Create a new model server
5. You should see authentication disabled
6. You should be able to create a model server
Test if a user with edit permission can edit a deployed model server
1. Create a new project
2. Create a new model server with auth
3. Add a user without cluster permissions with edit role in the project sharing panel
4. Log in as this regular user
5. Edit the created model …
=> Fix serving runtime edit creation

frontend/src/concepts/pipelines/content/configurePipelinesServer/ConfigurePipelinesServerModal.tsx, frontend/src/concepts/pipelines/content/configurePipelinesServer/ObjectStorageSection.tsx
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1307
using context data connection instead of using hook as it was always stale. also passing data connection into form section so it always has the same data
2. Create a data connection
3. Attempt to create the Pipeline Server
pipelines tests are in an issue already
=> pipelines modal use up top date data connections

.github/trivy.yaml, .github/workflows/vuln_scan.yml
Add new GitHub Action to do vulnerability scanning on static file in the repo on any PR
Result stored as artifacts in json format can be downloaded from Action runs' Artifacts zip file.
Only record if vuln in high or critical level
Create a PR in forked repo https://github.com/zdtsw/odh-dashboard/actions/runs/4799075808
Action was run and result can be download as artifacts
N.A
=> feat: add GH action to scan files in repo on PR basis

frontend/src/api/trustyai/rawTypes.ts
Closes: #1336
Update to the trusty client to handle the upcoming API changes described here: https://github.com/trustyai-explainability/trustyai-explainability/pull/186
Run locally, made sure existing functionality was not broken.
Small, non visual change, no existing tests to update.
=> Update Trusty AI client to handle API changes (#1336)

frontend/src/api/prometheus/serving.ts, frontend/src/concepts/dashboard/DashboardModalFooter.tsx, frontend/src/concepts/explainability/types.ts, frontend/src/pages/modelServing/ModelServingRoutes.tsx, frontend/src/pages/modelServing/screens/metrics/BiasConfigurationAlertPopover.tsx, frontend/src/pages/modelServing/screens/metrics/BiasConfigurationBreadcrumbPage.tsx, frontend/src/pages/modelServing/screens/metrics/BiasConfigurationButton.tsx, frontend/src/pages/modelServing/screens/metrics/BiasConfigurationPage.tsx, frontend/src/pages/modelServing/screens/metrics/BiasConfigurationTable.tsx, frontend/src/pages/modelServing/screens/metrics/BiasConfigurationTableRow.tsx, frontend/src/pages/modelServing/screens/metrics/BiasTab.tsx, frontend/src/pages/modelServing/screens/metrics/EmptyBiasConfigurationCard.tsx, frontend/src/pages/modelServing/screens/metrics/MetricsPage.tsx, frontend/src/pages/modelServing/screens/metrics/MetricsPageTabs.tsx, frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/DeleteBiasConfigurationModal.tsx, frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/ManageBiasConfigurationModal.tsx, frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/MetricTypeField.tsx, frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/useBiasConfigurationObject.ts, frontend/src/pages/modelServing/screens/metrics/const.ts, frontend/src/pages/modelServing/screens/metrics/tableData.tsx, frontend/src/pages/modelServing/screens/metrics/utils.tsx, frontend/src/pages/modelServing/screens/projects/ProjectInferenceMetricsConfigurationPage.tsx, frontend/src/pages/projects/ProjectViewRoutes.tsx
Closes #1274 #1162 
1. Added a modal that allows you to configure the bias metrics. However, this won't work until https://github.com/trustyai-explainability/trustyai-explainability/pull/186 is merged.
2. Added `Duplicate` and `Delete` for modal metric configuration rows
3. Added popover on the tab when there is no bias metric configured
Go to model -> go to bias tab -> click configure button on the page title -> get into the configuration page -> try to create (not working for now) and delete the configuration
TBD
=> Add bias metrics configuration modal

frontend/src/concepts/pipelines/content/createRun/contentSections/PipelineSection.tsx
Closes: #1300 
#1300 
While the UI to create a new pipeline usually reports Import pipeline as button text, both in DS Project details page and Data Science Pipelines > Pipelines page, the form to create a new Run reports Upload a new pipeline for doing the same operation:
=> Rename 'Upload a new pipeline' to 'Import pipeline' to keep consistency

frontend/src/pages/modelServing/screens/const.ts, frontend/src/pages/modelServing/screens/metrics/BiasTab.tsx, frontend/src/pages/modelServing/screens/metrics/EmptyBiasChartSelectionCard.tsx, frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/DeleteBiasConfigurationModal.tsx, frontend/src/pages/modelServing/screens/metrics/useBiasChartsBrowserStorage.ts, frontend/src/pages/modelServing/screens/types.ts
Closes: #1386 
* When a user navigates to the model bias tab and no charts are selected to display, automatically display the first chart
* Refresh interval dropdown updated with the same values as that of the OpenShift console Observability dashboard
* No charts selected empty state updated to:
*  Show the Search icon instead of the Plus icon
Improvement 1:
* Navigate to bias metrics tab
* Deselect all charts
* Navigate away from the current model (i.e. back to Projects view) - so the context is cleared
* Navigate back to the bias model tab - instead of an empty state one chart should be automatically selected.
Improvement 2:
* Check refresh interval dropdown has options that match openshift console (image provided) 
Improvement 3:
* Visit model bias tab, deselect all charts, verify the …
=> Minor enhancements to bias chart (#1386)

frontend/src/api/prometheus/serving.ts, frontend/src/api/prometheus/useQueryRangeResourceData.ts, frontend/src/utilities/useRefreshInterval.ts, frontend/src/utilities/useRestructureContextResourceData.tsx
* Closes: #1403 
Fixes bug described in ticket #1403 -- please read for detailed description
* Go to the bias metric charts page, select a chart to display
* Set the timeframe to 1 hour and refresh interval to 1 minute, to make testing easier.
* Leave the chart open for a few minutes, check there is no gap in the data as seen in the image below.
No tests for this feature yet, so none to change.
=> Fixes issue with bias charts auto-refreshing with stale data (#1403)

backend/src/types.ts, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/customServingRuntimes/utils.ts, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
Closes #1352 
1. Create a Custom Serving Runtime without builtInAdapter
2. Deploy a model server with that serving runtime
```
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
annotations:
name: ovms-no-builtin
opendatahub.io/disable-gpu: "true"
openshift.io/display-name: OpenVINO Model Server No builtinAdapter
labels:
opendatahub.io/dashboard: "true"
name: ovms
spec:
containers:
- args:
- --port=8001
- --rest_port=8888
- --config_path=/models/model_config_list.json
- --file_system_poll_wait_seconds=0
- --grpc_bind_address=127.0.0.1
- --rest_bind_address=127.0.0.1
image: quay.io/opendatahub/openvino_model_server@sha256:20dbfbaf53d1afbd47c612d953984238cb0e207972ed544a5ea662c2404f276d
name: ovms
resources:
limits:
cpu: "0"
memory: 0Gi
requests:
cpu: "0"
memory: 0Gi …
```
=> Fix serving runtime validation

frontend/src/concepts/pipelines/context/useManageElyraSecret.ts, frontend/src/concepts/pipelines/elyra/utils.ts
Switch to Kubernetes secret instead of users credentials
Closes: https://github.com/opendatahub-io/odh-dashboard/issues/1415
- switch the `cos_auth_type`: KUBERNETES_SECRET
https://elyra.readthedocs.io/en/latest/user_guide/runtime-conf.html#cloud-object-storage-authentication-type-cos-auth-type
- include `cos_secret` which reference the secret in the cluster with details of auth
=> Switch to Kubernetes secret instead of users credentials

backend/src/utils/resourceUtils.ts, frontend/src/pages/dependencies/PipelinesDependencyMissing.tsx
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1379
backend: blank config is merged for all calls to get dashboard config
frontend: updated no pipelines page to use useAccessReview and redirect to a search for the operator instead of direct link to it
- dont have pipelines installed
- go to pipelines page as user with access to install operators (cluster admin)
- press button when no pipelines page pops up
- this should take you to a search for the pipelines operator
- impersonate a regular user
- go to pipelines page
- see "Missing the pipelines operator" and no button
none
=> no pipelines error fix

frontend/src/__mocks__/mockRouteK8sResource.ts, frontend/src/__mocks__/mockServingRuntimeK8sResource.ts, frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.spec.ts, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx, frontend/src/__tests__/integration/pages/projects/ProjectDetails.stories.tsx, frontend/src/pages/modelServing/customServingRuntimes/utils.ts
Closes #1395 
1. In a cluster with a legacy model server (Model server deployed before serving runtime)
2. Check that the label is displaying `OpenVINO Model Server` rather than 'Unknown Serving Runtime'
or
1. Deploy an OVMS serving runtime
2. Remove `opendatahub.io/template-display-name` and `opendatahub.io/template-name`
3. Check that the label is displaying `OpenVINO Model Server` rather than 'Unknown Serving Runtime'
4. Now deploy another model with no ovms spec
5. Remove `opendatahub.io/template-display-name` and `opendatahub.io/template-name`
6. Check that the label is displaying 'Unknown Serving Runtime'
[before]
[after]
[after not ovms]
Added test coverage in the PR
=> Fix legacy model server display name

backend/src/types.ts, backend/src/utils/constants.ts, docs/dashboard_config.md, frontend/src/__mocks__/mockDashboardConfig.ts, frontend/src/api/prometheus/serving.ts, frontend/src/pages/modelServing/screens/metrics/BiasTab.tsx, frontend/src/pages/modelServing/screens/metrics/GlobalInferenceMetricsPage.tsx, frontend/src/pages/modelServing/screens/metrics/MetricsPage.tsx, frontend/src/pages/modelServing/screens/metrics/MetricsPageTabs.scss, frontend/src/pages/modelServing/screens/metrics/MetricsPageTabs.tsx, frontend/src/pages/modelServing/screens/metrics/PerformanceTab.tsx, frontend/src/pages/modelServing/screens/metrics/useMetricsPageEnabledTabs.ts, frontend/src/pages/modelServing/screens/metrics/usePerformanceMetricsEnabled.ts, frontend/src/pages/modelServing/screens/projects/ProjectInferenceMetricsPage.tsx, frontend/src/pages/modelServing/screens/projects/ProjectRuntimeMetricsPathWrapper.tsx, frontend/src/pages/modelServing/screens/projects/ProjectRuntimeMetricsWrapper.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx, frontend/src/pages/modelServing/screens/projects/utils.ts, frontend/src/pages/modelServing/useModelMetricsEnabled.ts, frontend/src/pages/projects/ProjectViewRoutes.tsx, frontend/src/types.ts, manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml, manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Closes #1405 
Create a feature flag `disablePerformanceMetrics` in the dashboard config, when its value is `true`, disable the following:
a. In the project details page, hide the dropdown item named `View metrics` in the model server kebab menu, so users cannot access the server performance metrics
b. In the model metrics page, hide the tab `Endpoint Performance`
c. Disable all the routes related to the performance metrics
d. If both `disablePerformanceMetrics` and `disabledBiasMetrics` are set to `true`, then the whole metrics will be disabled, users will not be able to get to the metrics page and the link will be plain text
1. Set `disablePerformanceMetrics` to `true` in the dashboard config CR
2. Wait for 2 mins until the dashboard UI gets the latest config
3. Go to the project details …
=> Add performance metrics feature flag and refactor runtime server route

frontend/src/pages/projects/components/DeleteModal.tsx
Closes: #1387
When trying to confirm to delete the project the user can press the "Enter" key  to confirm the deletion.
https://github.com/opendatahub-io/odh-dashboard/assets/2117670/7ce3468c-e4eb-4a37-aed3-1f6088c1524d
=> Enhance modal to delete project by pressing enter key

backend/src/routes/api/images/imageUtils.ts
Closes: #1434 
#1434  A quick fix to keep the enabled/disabled status after editing the custom notebook image
=> Keep the enabled/disabled status after editing the custom notebook image

backend/src/routes/api/dashboardConfig/index.ts, backend/src/routes/api/rolebindings/index.ts, backend/src/routes/api/templates/index.ts, backend/src/types.ts, backend/src/utils/constants.ts, backend/src/utils/resourceUtils.ts, docs/dashboard_config.md, frontend/src/__mocks__/mockDashboardConfig.ts, frontend/src/api/k8s/dashboardConfig.ts, frontend/src/api/k8s/templates.ts, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeContext.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeEnabledToggle.tsx, frontend/src/pages/modelServing/customServingRuntimes/DeleteCustomServingRuntimeModal.tsx, frontend/src/pages/modelServing/customServingRuntimes/useTemplateDisablement.ts, frontend/src/pages/modelServing/customServingRuntimes/utils.ts, frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx, frontend/src/pages/projects/ProjectDetailsContext.tsx, frontend/src/services/dashboardService.ts, frontend/src/services/templateService.ts, frontend/src/types.ts, manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml, manifests/modelserving/ovms-gpu-ootb.yaml, manifests/modelserving/ovms-ootb.yaml, manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Closes: #1205 
1. Create several Custom Serving Runtimes
2. Start to enable/disable
3. You should see the serving runtime names added into the `OdhDashboardConfig` attribute `templateDisablement`
1. Enable/Disable Custom Serving Runtimes
2. Go to DS Projects
3. Check that users only list the enables Serving Runtimes
4. Go back to Custom Serving Runtime
5. Check that the state of enablement is correct for every Serving Runtime
1. Add the annotation `opendatahub.io/template-enabled: 'false'` to existing templates
2. Delete the existing `OdhDashboardConfig` object
3. Restart the backend/restart the pods
4. A new OdhDashboardConfig object should be created
5. This object should contain a list in `templateDisablement` with the templates with the `opendatahub.io/template-enabled: 'false'` …
=> Refactor Custom Serving Runtime enablement

backend/src/routes/api/prometheus/index.ts, backend/src/utils/prometheusUtils.ts, frontend/src/api/prometheus/serving.ts, frontend/src/api/prometheus/useQueryRangeResourceData.ts
Closes: #1472 
* Adds backend endpoint for making range queries to thanos
* Updates Bias Prometheus queries to use this new endpoint
* Using a cluster with the latest version of trustyai: verify that model bias graphs correctly show data and that the Endpoint performance graph still works.
Minor change of queries to service that as too many dependencies.
=> Retrieve bias metrics from thanos querier (#1472)

frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.spec.ts, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/concepts/pipelines/content/ViewPipelineServerModal.tsx, frontend/src/concepts/pipelines/content/configurePipelinesServer/utils.ts, frontend/src/pages/projects/dataConnections/const.ts
Fixes #1381 
Changes as suggested in [#1381 comment](https://github.com/opendatahub-io/odh-dashboard/issues/1381#issuecomment-1607711576)
1. Check out the PR branch
2. Try to create a data connection and/or pipeline server using the "Create New data connection" option. Also, look at the modal after clicking on "View Pipeline Configuration" while the pipeline is getting created and while Deploying a model using a "New Data Connection"
Just `visual changes` as described in #1381 and added test for endpoint required field for "Deploy model"
=> Make data connection for S3 model sources AWS-unspecific

manifests/base/kustomization.yaml
Closes #1400 
1. Delete the dashboard `kfdef` from the `Open Data Hub Operator` if you had it deployed.
2. Run `make undeploy` if you already have a dashboard version deployed
3. Run `make deploy`
4. Got to your cluster and in the `opendatahub` namespace, look for the `odh-dashboard` deployment.
5. Check in the specification that the oauth proxy is using `registry.redhat.io/openshift4/ose-oauth-proxy:v4.10`
6. Go to the `odh-dashboard` pods, and check that the oauth-proxy container log is not raising any issue
7. Try to log in into the dashboard in the cluster
No testing coverage for infra update
=> Update oauth proxy to v4.10

backend/src/routes/api/prometheus/index.ts, backend/src/utils/prometheusUtils.ts, frontend/src/api/prometheus/serving.ts, frontend/src/api/prometheus/useQueryRangeResourceData.ts, frontend/src/pages/modelServing/screens/const.ts, frontend/src/pages/modelServing/screens/metrics/GlobalModelMetricsWrapper.tsx, frontend/src/pages/modelServing/screens/metrics/MetricsChart.tsx, frontend/src/pages/modelServing/screens/metrics/ModelGraphs.tsx, frontend/src/pages/modelServing/screens/metrics/ModelServingMetricsContext.tsx, frontend/src/pages/modelServing/screens/metrics/ServerGraphs.tsx, frontend/src/pages/modelServing/screens/metrics/types.ts, frontend/src/pages/modelServing/screens/metrics/useCurrentTimeframeBrowserStorage.ts, frontend/src/pages/modelServing/screens/metrics/utils.tsx, frontend/src/pages/modelServing/screens/projects/ProjectModelMetricsWrapper.tsx, frontend/src/pages/modelServing/screens/projects/ProjectServerMetricsWrapper.tsx, frontend/src/pages/modelServing/screens/types.ts
Closes #1130 
Update the queries that used to fetch the server and model metrics.
Update the chart with multiple legends to change the tooltip type.
TBD
TBD
=> Add queries for server and model performance metrics

frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.spec.ts, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceFrameworkSection.tsx
Closes #1458 
1. Go to DS Project
2. Deploy a model server
3. Go to the `Deploy model` modal
4. Check that the Model framework label now is displayed as `Model framework (name - version)`
Added extra steps in integration of Create model
=> Revamp Model framework label text

frontend/src/pages/projects/screens/projects/EmptyProjects.tsx, frontend/src/pages/projects/screens/projects/ProjectListView.tsx
Closes: #1462 
#1462 
Not to be able to find a route to the notebookController part of the app when it is disabled.
The empty state page
Modifying the OdhDashboardConfig is required to test this.
Enable DS Projects spec.dashboardConfig.disableProjects = false
Disable NotebookController spec.notebookController.enable = false 
You can see in DS project , you cannot find a route to notebookController
=> Notebook Spawner reachable when disabled

.github/ISSUE_TEMPLATE/bug_report.yaml
Slight improvements to our bug template to help with RHODS versions and a cleaner approach to what you'd type for each deploy type.
=> Improve the bug template to have more deploy type flexibility

frontend/src/api/pipelines/custom.ts, frontend/src/concepts/pipelines/apiHooks/usePipelineRunsForPipeline.ts, frontend/src/concepts/pipelines/const.ts, frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTable.tsx, frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableExpandedRow.tsx, frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableRow.tsx, frontend/src/concepts/pipelines/content/tables/pipeline/expandedRowRenderUtils.tsx, frontend/src/concepts/pipelines/content/tables/utils.ts, frontend/src/concepts/pipelines/types.ts, frontend/src/pages/projects/screens/detail/pipelines/PipelinesList.tsx
Closes #1248
Improve performance of showing partial Pipelines / associated Pipeline Runs by enabling pagination and limit the items. Also sort the pipelines and runs by `created_at`.
- Created few sample pipelines and runs 
- Go to DS Project  -> select project -> Pipelines -> expand pipeline which contains the runs
Global Pipelines:
Global Pipeline **scheduled** runs:
Global Pipeline **triggered** runs(zoomed out):
=> Improve performance of showing partial Pipelines and runs

frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabDetails.tsx
Closes: [#1288](https://github.com/opendatahub-io/odh-dashboard/issues/1288)
When you start a Pipeline Run you will be navigated to the Run Details page. As it loads, you see an error among other states of "loading".
=> replace EmptyState to Spinner component in Pipeline runs details tab

frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineNotFound.tsx
Closes: #1324 
#1324 
The page displays the correct error message and a link to navigate to pipeline page
1. Create a Pipeline
2. Create a Run for that Pipeline
3. Delete the Pipeline
4. View the Run on the Global Runs list page
5. Click on the Pipeline link
=> If you delete a Pipeline, the run reference leads to a meaningful message

frontend/src/concepts/pipelines/context/useManageElyraSecret.ts, frontend/src/concepts/pipelines/elyra/const.ts, frontend/src/concepts/pipelines/elyra/utils.ts
Resolves:opendatahub-io/notebooks#130
Complementary PR from notebooks: opendatahub-io/notebooks#137
Change the Elyra public API endpoint URL so that it correctly references to the desired data science pipeline run details.
Not fully tested yet, testing in progress
=> Change Elyra public API endpoint to ensure a correct URL for redirect

backend/src/routes/api/prometheus/index.ts, backend/src/utils/constants.ts, backend/src/utils/prometheusUtils.ts
This reverts the PR allowing changing the port used to query Thanos metrics. The dashboard should only make RBAC queries and not OAuth queries (which the previous PR allowed). This is due to the Thanos OAuth proxy only allowing cluster-admin users to log in. Our dashboard must work for users with lower privileges as in a real world scenario no user will have that level of privilege for day to day work.
=> Revert configurable thanos port

frontend/src/pages/projects/projectSharing/useGroups.ts
Closes: #1317
As part of a normal flow, `/api/k8s/apis/user.openshift.io/v1/groups` is queried from the project details page. There was however a check in place where this call was skipped if `useUser().isAdmin === true`. Instead of using this check, we ought to be checking rbac. If the user has permissions to get a resource, we should let them. By simply removing this check we now have to handle error `403`. Or we could perform a self subject access review prior to making the call. I've opted to handle the `403` request as it provides the same feed back as first performing a self subject access review check. `useAccessReview` is a utility that can be used know if a user has permissions to perform an action. This utility would cache the result such that no further network calls are …
=> when fetching groups, capture error 403 as rbac failure and cache result

backend/src/utils/resourceUtils.ts
Closes: #1508
When the Dashboard starts under the new operator, KfDef CRD is not installed as we use a different component. This simply handles that situation by muting the problem when it cannot find them in K8s.
1. Using a fresh cluster
2. [Installing the new operator](https://github.com/opendatahub-io/opendatahub-operator/blob/feature-rearchitecture/docs/Dev-Preview.md)
3. Deleting their auto installed KfDef CRD (this was a work around I thought we would need, but turned out to be unrelated)
4. Starting the Dashboard locally (and testing restarting the pods)
None
=> Remove the KfDef CRD reliance

frontend/src/concepts/pipelines/content/createRun/RunForm.tsx, frontend/src/concepts/pipelines/content/createRun/contentSections/PipelineSection.tsx, frontend/src/concepts/pipelines/content/createRun/types.ts, frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts, frontend/src/concepts/pipelines/content/createRun/utils.ts
Closes: #1344 
#1344 
close the gap by making sure the form data waits until we are properly selected in all aspects.
The submit button needs to be locked until all required fields are filled.
[Screencast from 2023-07-10 10-48-39.webm](https://github.com/opendatahub-io/odh-dashboard/assets/99238909/9274ce43-7365-4f26-880e-e2cd42233268)
1. Create a Pipeline
2. Create a run for this Pipeline
Slow browser network traffic just before the call is made. Might be hard to test this manually, but programatically this can be seen, so perhaps use console logs and other means to test the flow speed.
No testing coverage
=>  Automation Beats Out Pipeline Auto-Selection

frontend/src/components/ResourceNameTooltip.tsx, frontend/src/concepts/dashboard/DashboardPopupIconButton.tsx, frontend/src/pages/BYONImages/BYONImagesTable.tsx, frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1476
added a copy icon to the resource name tooltip
_design:_
- Add the helper text to the bottom of the tooltip
- copy icon uses <Icon /> still to preserve padding, however this means i had to set the style of the pointer manually
- there is currently no confirmation when copied
- the BYONImages from the backend is not returned as a standard k8 object... so i added a eitherNotBoth to allow for manual input of name and kind or a k8 resource.
_Outdated_
_Outdated_
https://github.com/opendatahub-io/odh-dashboard/assets/12587674/5e896138-bd9b-4395-9bdc-5eaa42ad637b
- go to notebook images in settings
- make sure it is not empty
- see help icon
- hover on help icon and click
- make sure it copied
no impact - all labels are …
=> add copy to clipboard icon to tooltips

frontend/src/__tests__/integration/components/error/ErrorBoundary.stories.tsx, frontend/src/app/App.tsx, frontend/src/components/error/ErrorBoundary.tsx, frontend/src/components/error/ErrorDetails.tsx, frontend/src/index.tsx
Closes: #1554
Whenever an uncaught exception occurs in the UI, an error page will display the error details instead of simply rendering a blank page.
The error boundary is installed at two different locations:
- top level
- main content
Added a storybook story for rendering the ErrorBoundary.
Created a component which throws an exception:
```
const Throw = () => {
throw new SyntaxError('This is only a test.');
};
```
Render this component in various parts of the app; both inside the main content area and outside (eg navigation).
```
<Throw />
```
Impacts, in a positive way, uncaught exceptions thrown by the application to display errors instead of blank page.
cc @kaedward …
=> create error boundaries for app and content

frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.spec.ts, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionFolderPathField.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
Fixes #1423 
1. Renamed "Folder Path" to "Path" 
2. Make "Path" a required field
3. Add helper text to "Path" field
4. Add validation for "Path" field(don't allow `/` or `///////` -> enable "Deploy" button only if "Path" is valid )
GIF(outdated):
Please refer to [this comment](https://github.com/opendatahub-io/odh-dashboard/pull/1512#issuecomment-1650046750) for the latest GIF
https://github.com/opendatahub-io/odh-dashboard/assets/22885912/9754dd01-3955-41fc-a1d5-94fd8dfb39c9
1. Create a Model Server
2. Click on Deploy Modal
3. Fill out the data(Path field in both Existing and New data connection)
Added tests for the required "Path" field
=> Prevent No-Folder or root S3 model access

backend/src/utils/componentUtils.ts, manifests/crd/odhapplications.dashboard.opendatahub.io.crd.yaml
Closes: #1510
Remove the reliance on `kfdefApplications` field in the `OdhApplication` CRs (when there are no KfDefs installed).
When the new Operator is installed, it does not use KfDefs... the CRD does not exist, the items do not exist. In https://github.com/opendatahub-io/odh-dashboard/pull/1537 we removed the error when no KfDef CRD exists. 
This is to adjust us back to working -- `kfdefApplications` is not needed when no KfDefs are found and are completely ignored. Moving forward we'll use the "component model" and each component will offer resources if they wish for Dashboard to render.
Couple screenshots...
Should be noted, I could not actually deprecate the field. [K8s doesn't allow it](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/ …
=> Deprecate kfdefApplication field in OdhApplications

backend/src/utils/notebookUtils.ts, frontend/src/api/k8s/notebooks.ts, frontend/src/concepts/pipelines/elyra/utils.ts
Related-to: https://github.com/opendatahub-io/kubeflow/pull/110
Closes: https://github.com/opendatahub-io/odh-dashboard/issues/1593
This includes a volumeMount onto each Notebook on creation. 
which would allow user to have shard memory based on their node size.
- Deploy ODH or RHODS with odh-deployer switch with this PR image.
`quay.io/opendatahub/odh-dashboard:pr-1594`
- Create a Notebook via jupyter tile or project workbenches
- Check if the notebook is set up with the required volume mount.
Tested this behavior by creating notebook both on jupyter tile and project notebook.
Not sure, how to include test, if some one can provide example. 
the code change would be caught by an end to end test.
After the PR is posted & …
=> Add volume to change shared memory limit on notebook

frontend/src/concepts/pipelines/topology/core/PipelineVisualizationSurface.tsx
Closes: #1522  
#1522 
Error page is being displayed instead of redirecting it to blank page
Import this pipleline yaml file
[TestPipeline01-modified.yaml.txt](https://github.com/opendatahub-io/odh-dashboard/files/12102879/TestPipeline01-modified.yaml.txt)
and check for the error page 
=> Uploading a malformed pipeline yaml results in a blank page

backend/src/routes/api/images/imageUtils.ts
Close #1493 
After a discussion with the UX, we decide to parse the error dependency string as empty, which means when the parse error happens, the backend will return an empty array to the frontend side. So from the user's perspective, it can still normally use the image but see no dependencies in the image.
1. Go to the cluster, and find one image stream that the notebook controller spawner page could fetch
2. Change the `annotation['opendatahub.io/notebook-python-dependencies']` of its tag to an invalid string which could cause the JSON parse error
3. Go to the notebook controller spawner page in the dashboard, see if you could successfully load the page and select the image
4. Check the details of the image by clicking the tooltip next to it, and find if the packages are not visible …
=> Gracefully handle image packages and software JSON parse error

docs/architecture.md, frontend/.eslintrc, frontend/.eslintrc.goal.js, frontend/package.json
Updated the `architecture.md` document with new guidance for guidance on folder structure. The updated guidance includes rules to govern importing across folders.
In order to enforce these fules, I've added a new lint configuration along with a configuration of the `import/no-restricted-paths` rule set with several zone restrictions. The new configuration is run separately from `test:lint` so thatthese rules won't affect builds and interrupt development. See `./.estintrc.goal.js`.
Use `npm run lint:goal` to run the new lint rules:
`✖ 167 problems (0 errors, 167 warnings)`
Eg output:
```
/Users/cvogt/dev/odh-dashboard/frontend/src/concepts/projects/ProjectSelector.tsx
3:39  warning  Unexpected path "~/pages/projects/utils" imported in restricted zone. Modules from `src/pages` may not be …
```
=> update architecture doc folder structure

backend/src/utils/constants.ts
closes: #1333
The PVC Size Default in odh dashboard code is set to 20 in both backend and frontend code.
It should be taken from a default entry in odh dashboard config and not be set to a value explicitely in all sorts of places frontend and backend. There is always an auto-generated odh dashboard config, and pvc size is non-optional.
https://github.com/search?q=repo%3Aopendatahub-io%2Fodh-dashboard%20DEFAULT_PVC_SIZE&type=code
In Jupyter tile, the error with number 20 leads to a PVC being pending forever, with event message saying 
**"20 bytes is not a valid size"**
Default should be set to 20Gi.
This is only happening if no other value is specified in OdhDashboardConfig odh-dashboard-config at notebook controller level. 
set this manually in OdhDashboardConfig to 20Gi and then PVC was …
=> change const DEFAULT_PVC_SIZE from 20 to 20Gi as in frontend notebook const ts

.env, docs/releases.md, install/deploy.sh, install/undeploy.sh, manifests/base/deployment.yaml, manifests/kfdef/odh-dashboard-kfnbc-test.yaml, manifests/overlays/performance/deployment.yaml, manifests/overlays/performance/kustomization.yaml
Closes: #1613 
1. Run `make deploy` in your cluster
2. Check that the odh-dashboard deployment has 2 replicas
3. Add `KUSTOMIZE_DEFAULT_OVERLAY=/overlays/performance` in your `.env.local` file
4. Run `make deploy`
5. Check that the odh-dashboard deployment has 5 replicas now
No test impact so far
=> Add performance overlay and sync deployment to odh-manifest

frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.spec.ts, frontend/src/api/k8s/inferenceServices.ts, frontend/src/api/k8s/notebooks.ts, frontend/src/api/k8s/projects.ts, frontend/src/api/k8s/pvcs.ts, frontend/src/api/k8s/secrets.ts, frontend/src/api/k8s/servingRuntimes.ts, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx, frontend/src/pages/projects/components/DeleteModal.tsx, frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx, frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
Closes: #1587
Creation of a resources accepts any display name and stores it within the annotation `openshift.io/display-name`, we then translate value into a valid resource name. However the display name may contain leading or trailing spaces. This doesn't cause any issues at display time however is an issue when it comes to the delete modal where we expect the user to re-ender the display name. Unfortunately the name value the user sees rendered in the UI does not contain these extra spaces (because HTML). Meanwhile in code the comparison to check if the user entered the correct name has these extra spaces. Therefore there's a disconnect between what we ask the user to enter and what we actually compare against.
Changes made:
- trim display name when setting display name annotation …
=> handle white space in creation and deletion using display names

backend/src/routes/api/images/imageUtils.ts
Closes #1641 
It's because the image regex is returning the full match result as the URL but not the full URL, so the tag is omitted.
Follow the same way in the issue description:
1. Go to Notebook image settings
2. Try to import an image using SHA256-encoded tag like `quay.io/opendatahub/workbench-images@sha256:b6532b34c9bf0710ecbd76407c8909742914bdacd17add3e04ab49e7c81a2800`
3. Make sure the image can be successfully imported and the image location is shown correctly
N/A
=> Make custom image location regex match return correct full URL

backend/src/plugins/kube.ts, backend/src/types.ts, backend/src/utils/resourceUtils.ts
relies on https://github.com/opendatahub-io/odh-dashboard/pull/1628
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1598
Adds GPU migration to accelerator profiles
1. set up cluster using GPUs
2. start dashboard server and have the migration code run
3. A new AcceleratorProfile resource should be created and a ConfigMap created for a successful migration
4. open cluster without GPUs 
5. migration should fail as it is missing AcceleratorProfile CRD - no ConfigMap
6. add AcceleratorProfile CRD
7. migration should create config map but not a accelerator profile resource
is backend, no testing there yet
=> added gpu migration

frontend/src/pages/pipelines/global/pipelines/GlobalPipelines.tsx
Fixes #1606 
This is how the Global Pipelines page look like now.
1. Go to the `Pipelines` page using the left Navbar
2. Check whether you can see the divider between the table and the header
Visual changes.
=> Remove misplaced divider in Global Pipelines Page

frontend/src/pages/dependencies/DependencyMissingPage.tsx
Closes #1547 
This is because after the operator is installed, we are stilling on the `/missing-dependency/pipelines` page, which will only return `<NotFound />` when it detects the operator is available. However, it should redirect to the `/pipelines` route if the operator is installed.
1. Uninstall pipelines operator
2. Launch dashboard go to Data Science Pipelines tab
3. Install pipeline operator
4. Keep the Data Science Pipeline open
5. Check if the page redirects to the pipelines main page, which allows you to create a pipeline server in a specific project
N/A, it's a route issue.
=> Navigate to pipelines page after pipelines operator is installed

frontend/src/api/prometheus/serving.ts, frontend/src/concepts/explainability/useTrustyAIAPIRoute.ts, frontend/src/concepts/explainability/useTrustyAIAPIState.ts, frontend/src/concepts/pipelines/context/usePipelineAPIState.ts, frontend/src/pages/modelServing/screens/metrics/BiasConfigurationTable.tsx, frontend/src/pages/modelServing/screens/metrics/EnsureMetricsAvailable.tsx, frontend/src/pages/modelServing/screens/metrics/MetricsChart.tsx, frontend/src/pages/modelServing/screens/metrics/ModelGraphs.tsx, frontend/src/pages/modelServing/screens/metrics/ModelServingMetricsContext.tsx, frontend/src/pages/modelServing/screens/metrics/ServerGraphs.tsx, frontend/src/pages/modelServing/screens/metrics/TrustyChart.tsx, frontend/src/pages/modelServing/screens/metrics/biasConfigurationModal/MetricTypeField.tsx, frontend/src/pages/modelServing/screens/metrics/utils.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx, frontend/src/pages/projects/screens/projects/ProjectListView.tsx, frontend/src/types.ts
=> Fix types on f/mserving-metrics branch

docs/releases.md
Update release docs to reflect that we are getting manifest files from `incubation`
=> Update release docs

frontend/src/components/ScrollViewOnMount.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTable.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableExpandedSection.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx
Closes #1545 
The div will automatically scroll into view because we added that feature somehow. But I think it's not needed because users can always scroll the screen by themselves, auto-scroll will only destroy some of the layouts and behaviors and cause unexpected results.
@kywalker-rh Could you confirm this?
The context: When you click on `Deployed models` on project details page, it will expand the models table, and the page will scroll to show the whole table. However, this auto scroll could cause problems. So I removed it, no when clicking on `Deployed models`, the page will not auto scroll anymore. Is that acceptable?
Follow the same instructions in the issues, you will find the issue disappeared.
N/A, layout issue. …
=> Remove automatically scrolling into view functionality

manifests/base/routes.yaml
=> Fix tls option in odh-dashboard route

frontend/src/pages/modelServing/screens/metrics/MetricsPageTabs.tsx, frontend/src/pages/modelServing/screens/metrics/const.ts
* This address part of, but does not close:  #1526
Following review by UXD the first round of changes to the copy is implemented here:
* No selected bias metrics empty state copy updated as in screenshot.
* Tab titles changed to sentence case, as in the screenshot.
Run on cluster and ensure features work and updates are reflected. 
None, text only change.
=> Explainability copy updates part 1 (#1526)

frontend/src/pages/projects/notebook/utils.ts, frontend/src/types.ts, frontend/src/utilities/notebookControllerUtils.ts
Closes: #1607
The notebook server is starting but cannot start due to insufficient resources. If the Notebook resource doesn't have a `notebooks.kubeflow.org/last-activity` annotation, the UI doesn't display any errors.
Now the user gets an error:
And events log:
1. create a new project
2. create a new workbench and use a large size. Consider adding a new notebookSizes entry to the OdhDashboardConfig if your notebook server still starts.
3. Observe the pod not starting.
4. Check the dashboard UI by clicking on Starting... and viewing the event log 
5. Expect errors to be displayed if there is insufficient resources to start the server
6. Check the `Notebook` k8s resource for the `notebooks.kubeflow.org/last-activity` annotation. It should not be present.
no new tests added
Self checklist …
=> show event details when starting a new notebook server 

frontend/src/pages/notebookController/screens/server/NotebookServer.tsx
Closes #1591 
Didn't make any visual changes here, only updated the button's behavior to make it a link.
1. Go to notebook controller page (Jupyter card on Enabled page), spawner a notebook
2. After spawning, don't get into the notebook, you will see the control panel
3. Click on the `Access notebook server` button, you will be navigated to the notebook in the same tab
4. `Cmd/Ctrl` + Click on the button, you will be able to access the notebook in a new tab
5. Right click the button, you will see some link options like `Copy link address` or `Open link in new tab`
N/A, just behavior change.
=> Make notebook controller access button to link behavior

frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx, frontend/src/pages/projects/notebook/service.ts, frontend/src/pages/projects/notebook/types.ts, frontend/src/pages/projects/notebook/useRefreshNotebookUntilStartOrStop.ts, frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx
* Closes: #1551 
* When stopping a workbench:  
* the switch now waits for the pods to spin down before showing status "stopped". 
* The edit button in the kebab is disabled until the new stopped status.
* Stop a running workbench
* Wait for the edit button in the kebab to not be disabled
* Make an update to your workbench, e.g. change the notebook image.
* Ensure you do not see the error message reported in the bug.
None.
=> Fixes: Workbench not editable for a little while after it's stopped

frontend/src/app/App.tsx, frontend/src/pages/enabledApplications/EnabledApplications.tsx, frontend/src/pages/learningCenter/LearningCenter.tsx, frontend/src/pages/notebookController/NotebookController.tsx
Closes #1574 
I found `QuickStarts` context was used across some specific pages, which is causing inconsistent user experience when switching them.
The fix is to lift up the `QuickStarts` context and use it to wrap the `App`, in this way, the whole application could share the context and when users switch between the pages, there will be no flickering any more, the quick starts will be fixed there unless closing it.
1. Go to the Resources page
2. Open a quick start and keep it open
3. Switch to any other pages in the dashboard (try as many pages as possible)
4. Make sure the quick start panel is always open
N/A, it's behavior among the whole application.
=> Elevate quick starts context to the whole application layer

frontend/src/pages/projects/components/PVSizeField.tsx
Closes: #1610  
This PR will change the wording (already reviewed by UX) for Cluster Storage Editing. 
1. Create a Workbench with a new storage
2. When the Workbench has started, edit the storage
=> Improve Wording for Cluster Storage Editing

frontend/src/concepts/pipelines/content/pipelinesDetails/PipelineDetailsYAML.tsx
Closes: #1689
It makes the yaml editor for pipeline read only
The command palette in the current editor is the same as in PatternFly's read-only code editor. https://v4-archive.patternfly.org/v4/components/code-editor
1. Import pipeline
2. Move to yaml tab
3. Try editing yaml code
=> pipeline yaml editor should be read only

frontend/src/utilities/imageUtils.ts
Closes: #1690
Removing the `default` designator from notebook image name, when starting a notebook server.
@xianli123 tagging you here.
1. Launch a Jupyter notebook
2. On "Start a notebook server page" click on any notebook image which has more than 1 tags.
3. `(default)` should not be there.
Tests are not required for this.
=> Remove default designator when selecting a notebook

frontend/src/pages/projects/screens/detail/ProjectDetailsComponents.tsx, frontend/src/pages/projects/screens/detail/useCheckLogoutParams.ts
Close #1567 
Easy fix, the `useCheckLogoutParams` hook is used both in the `ProjectDetails` component and the `ProjectDetailsComponents` component, so it's called twice. Removing one can fix this problem.
1. Go to data science project, create a workbench
2. Login to the workbench
3. In the Jupyter notebook GUI, choose `File -> Log out`
4. Check the logout success message, make sure there is only one message in the notification center
N/A
=> Remove duplicated logout message when logging out from workbench

backend/src/routes/api/namespaces/namespaceUtils.ts, frontend/src/api/k8s/projects.ts, frontend/src/concepts/projects/ProjectsContext.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx, frontend/src/pages/projects/screens/projects/ProjectListView.tsx, frontend/src/pages/projects/screens/projects/ProjectScopeSelect.tsx, frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx, frontend/src/pages/projects/screens/projects/ProjectView.tsx, frontend/src/pages/projects/types.ts, frontend/src/typeHelpers.ts
Closes #1417 
Closes #1310 
Add a select field, allowing the user to select the scope of the project table.
When selecting Data science projects:
When selecting All available projects:
Also, only apply the `modelmesh-enabled: 'true'` annotation when first creating a server in a project.
1. Go to the dashboard projects page
2. Toggle the select dropdown to view different scopes
3. Make sure projects starts with `openshift-` or `kube-` or `default` or `system` or `openshift` or the dashboard namespace are not shown in the list
4. Try to create a workbench in a non-DS project
TBD
=> Show non-DS projects in the project table

frontend/src/components/SimpleDropdownSelect.tsx, frontend/src/concepts/dashboard/codeEditor/useCodeEditorAsLogs.tsx, frontend/src/concepts/k8s/pods/useFetchLogs.ts, frontend/src/concepts/k8s/pods/usePod.ts, frontend/src/concepts/k8s/pods/utils.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightContent.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightTabs.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTabStatus.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/const.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/usePodContainerLogState.ts, frontend/src/k8sTypes.ts, frontend/src/utilities/string.ts
Closes: #1247
Collaborated with @manaswinidas to complete this feature.
Adds a Logs tab to the selected node sidebar.
Couple high level notes:
* Issue (A): We could not use the Log Viewer -- it does not handle itself well in the Sidebar. We may be able to hack something together but that won't be first pass. We use the code editor in read only mode
* Issue (B): We can't properly capture scroll with the code editor -- but you can manually pause the refresh, it just won't trigger on scroll up
* List of known issues will be after the screenshots -- these are to be handled in a future PR
* For dev purposes, log tab was selected first, some gifs show this -- this is not the case in the PR
> Note: Issues (A) & (B) will be listed below as well.
> Note: There will be some documented gaps. This …
=> Pipeline run pod logs

frontend/src/components/table/Table.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeTableRow.tsx
Closes: #1394
This PR will truncate the long display name in "serving runtimes" and table will not expand as large as name.
1. Go to serving runtimes page
2. Create a new serving runtime with a long display name
3. After creation of new serving runtime, the long display name will be truncated and table will not expand as before.
=> Truncate long display name in serving runtimes

frontend/src/pages/projects/components/PVSizeField.tsx
Closes #1564 
This issue is because we check the input with the min size when the value changes, which will bring a bad user experience for the users. For example, if the minimum size is `5` and the user tries changing it to `35`, it's a valid value. However, the current `onChange` listener will prevent the user from doing that because as soon as the user inputs `3`, the listener will find this value is less than `5` and reset it back to 5. It won't wait until the user inputs the whole `35`.
The solution is to compare the minimum value and reset it in `onBlur` event instead of `onChange` event, in this way, the user could input any number value he wants, however, if the value is smaller than the min size, it will be reset when the input field loses focus.
Behavior now: …
=> Limit storage min size onBlur instead of onChange

backend/src/routes/api/nb-events/eventUtils.ts, backend/src/routes/api/nb-events/index.ts, frontend/src/api/k8s/events.ts, frontend/src/api/models/k8s.ts, frontend/src/pages/notebookController/screens/server/StartServerModal.tsx, frontend/src/pages/projects/notebook/StartNotebookModal.tsx, frontend/src/pages/projects/notebook/useWatchNotebookEvents.ts, frontend/src/pages/projects/notebook/utils.ts, frontend/src/services/notebookEventsService.ts, frontend/src/utilities/notebookControllerUtils.ts, frontend/src/utilities/useWatchNotebookEvents.tsx
Closes: #793
When `LimitRange` prevents the creation of notebook server pods, no errors are displayed in the UI. The error occurs on the `StatefulSet`. This change reads events from the `StatefulSet` when no pod is present. Once a pod is present, we go back to reading the pod events as was done previously.
Added a new error message `Failed to create pod` to represent this state (see screen shots below).
cc @kywalker-rh
<details>
<summary>Limit Range YAML</summary>
```yaml
kind: LimitRange
apiVersion: v1
metadata:
name: limit-range
namespace: <namespace>
spec:
limits:
- type: Container
max:
cpu: 50m
memory: 50Mi
default:
cpu: 50m
memory: 50Mi
defaultRequest:
cpu: 50m
memory: 50Mi
- type: Pod
max:
cpu: 100m
memory: 50Mi
```
</details>
Workbench:
- Create a data science project
- Create a …
=> display StatefulSet errors when notebook pod fails to create

manifests/base/fetch-accelerators.rbac.yaml, manifests/base/kustomization.yaml
Add rbac roles for authenticated user to allow them to fetch, get, and watch all accelerator profiles
oc apply the yaml and impersonate a regular non cluster admin user. If you have acceleratorprofiles, then you should be able to see the dropdown when creating a workbench
n/a - no tests for manifest
=> add rbac accelerator role

frontend/package-lock.json, frontend/package.json, frontend/src/__tests__/unit/testUtils/hooks.spec.ts, frontend/src/__tests__/unit/testUtils/hooks.ts, frontend/src/__tests__/unit/useFetchState.spec.ts, frontend/src/__tests__/unit/useGroups.spec.ts, frontend/src/pages/TestPage.tsx.bak, frontend/src/utilities/useFetchState.ts
Introduces `@testing-library/react` for unit tests. While RTL does provide a means to render a hook and perform assertions using jest, such tests result in a lot of boilerplate code.
The goal of this PR is to supply testing utilities that make it easier to write tests for hooks and ensure that we test two critical areas of hooks:
- return values are stable unless their values have actually changed
- a hook doesn't unnecessary cause additional re-renders
Example of a small test asserting these two areas:
```
const useSayHello = (who: string) => `Hello ${who}!`;
```
```
it('use hook test utils', () => {
const renderResult = testHook(useSayHello, 'world');
expectHook(renderResult).toBe('Hello world!').toHaveUpdateCount(1);
renderResult.rerender('world');
expectHook(renderResult).toBe('Hello …
```
=> add utility to make it easier and more robust to test hooks

frontend/src/concepts/pipelines/content/tables/renderUtils.tsx
Closes: #1586 
Removed the tooltip
[Screencast from 2023-09-06 19-54-12.webm](https://github.com/opendatahub-io/odh-dashboard/assets/99238909/961c95a9-4996-4b4a-8b09-e9a1566710b4)
1. Create some scheduled runs
2. Go to Run page and in the Scheduled tab check for the status column
No test coverage
=> tooltip on pipeline screen impede clicking of the slider right above

frontend/src/pages/modelServing/screens/projects/ServingRuntimeTable.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx
Closes #1320 
Use `useAccessCheck` hook to check whether the user has access to delete the RoleBinding in the namespace, if not, hide the `Delete model server` dropdown item.
1. Create a project as user A
2. Create a model server as user A
3. Grant edit permission to user B (user B needs to be a regular user, and cannot be a cluster admin or dashboard admin)
4. Impersonate user B, go to the project, see the dropdown of the model server
5. The `Delete model server` button should be invisible
N/A
=> Add access check before deleting model server

frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerBottomTabs.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabParameters.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/utils.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsPrintKeyValues.tsx
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1245
For a pipeline run, there is a new tab between the details and yaml that shows the global params for the pipeline
1. create a pipeline that has global params and one that does not
_global params can be added here_
```yaml
spec:
params:
- name: global-param-1
value: some-value-1
- name: global-param-2
value: some-value-2
```
2. Create a run for the pipeline without params
3. go to run details -> Parameters tab
4. it should show an empty state
5. create a run for the pipeline with params
6. it should show the params on the tab
- pipeline test issue: https://github.com/opendatahub-io/odh-dashboard/issues/1297
cc …
=> Added pipeline run param tab

backend/src/plugins/kube.ts, backend/src/routes/api/accelerators/acceleratorUtils.ts, backend/src/utils/resourceUtils.ts, frontend/src/components/SimpleDropdownSelect.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeDetails.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx, frontend/src/pages/notebookController/screens/server/AcceleratorSelectField.tsx, frontend/src/pages/notebookController/screens/server/NotebookServerDetails.tsx, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx, frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx, frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx, frontend/src/utilities/useAcceleratorState.ts
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1765
Minor UX and bug fixes found by testers
- making naming in the error states of the dropdown dynamic so they can use image or servingruntime
- improved backend logging to be more verbose and not miss any exit points
- remove double array usage in accelerator state hook
- remove usage of unknown when we know that there is not an accelerator for description fields and logging - replaced with None when there is no accelerator, and unknown when we use existing settings
- prevent count from going to 0 -> same logic as other number inputs. The default and limit are now 1.
- removed italics from dropdown None option
1. Migration should always give a logging on error, success, or skipping
2. test that errors display correctly in …
=> Minor accelerator fixes

frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTable.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx
Closes #1756 
Bring the expanded column state back to each row, and make the row manage its own state. When creating a new model, it will trigger a hook in the row to compare and expand the column in that row.
1. Create more than 2 model servers
2. Deploy a new model, it should expand the `Deployed model` tab on that model server
3. Try to expand and collapse the tab on every model server, make sure the original issue not happen
Add some unit tests to make sure the click on one model server will not expand all the rows.
=> Fix model server expand issue on the project details page

frontend/src/utilities/__tests__/valueUnits.spec.ts, frontend/src/utilities/valueUnits.ts
Fixes #1730
Fixes an issue when notebook sizes contain a size with either CPU or memory limit not set. When viewing such noetbook in project details page, size was not recognized.
Before:
After:
1. Add noetbook size with no limits to ODH dashboard configuration
2. Create new DS project
3. Create workbench with new size
4. Go back to project details
Also added unit tests for good measure
@kywalker-rh @xianli123 (for dashboard change) and @Gkrumbach07 (for tests)
=> Fixed isCpuLimitEqual and isMemoryLimitEqual wrongly comparing null/undefined values.

backend/src/types.ts, frontend/src/api/k8s/notebooks.ts, frontend/src/api/k8s/servingRuntimes.ts, frontend/src/api/k8s/utils.ts, frontend/src/k8sTypes.ts
Closes #1685 
Apply shm `volumes` and `volumeMounts` when creating or updating (this is for backward compatibility, let me know if we want only to apply this to the future created serving runtimes @lucferbux ) the serving runtime.
1. Create a model server
2. Check the YAML object of the model server (ServingRuntime), make sure you can see the following in the container
```
volumeMounts:
- mountPath: /dev/shm
name: shm
```
and the following in the spec:
```
volumes:
- emptyDir:
medium: Memory
sizeLimit: 2Gi
name: shm
```
N/A
=> Add shm to ServingRuntime volumes and volumeMounts

frontend/src/pages/BYONImages/BYONImageModal/ImageLocationField.tsx, frontend/src/pages/BYONImages/BYONImageModal/ManageBYONImageModal.tsx, frontend/src/pages/BYONImages/BYONImagesTableRow.tsx, frontend/src/pages/BYONImages/utils.ts
Closes #1769 
Fixes the issues mentioned above.
For the first issue, add some modifiers to the table column:
https://github.com/opendatahub-io/odh-dashboard/assets/37624318/ec6f3185-a8b1-4a1f-8918-131be6d6a50d
For the second issue, filter the blank entry of the packages/software out when users import/update the image.
For the third issue, add the disabled input field for the image location when user edit the image:
cc @vconzola Please check the updates when you get a chance.
1. Try to shrink the window size, and make sure the `Enabled` field is not wrapped
2. Try to create/update a notebook image, give it some blank entries (no name and no version) in the packages/software, and submit. Edit the image, and make sure those empty entries are removed
3. Edit a notebook image, you should be …
=> Minor UX fixes for custom notebook images

frontend/jest.config.js, frontend/src/concepts/pipelines/content/configurePipelinesServer/__tests__/utils.spec.ts, frontend/src/concepts/pipelines/content/configurePipelinesServer/utils.ts
Closes: #1350
Depends on https://github.com/opendatahub-io/odh-dashboard/pull/1773 for unit tests.
When creating a data connect whose endpoint does not include a scheme in the URL, creating of a pipeline server will fail with a javascript error attempting to access a property of an undefined value. This is because the regex used to parse the data connection endpoint URL assumed a scheme would always be present.
This change does not affect the UI / UX.
1. Create a data connection
2. set the endpoint to `s3.amazonaws.com`
3. Create a pipeline server
4. Select pre-existing data connection
5. Click `Configure` button
Added unit test.
=> Fix error creating pipeline server when data connection endpoint omits scheme

frontend/src/components/table/TableRowTitleDescription.tsx, frontend/src/concepts/pipelines/content/DeletePipelineCoreResourceModal.tsx, frontend/src/concepts/pipelines/content/PipelineJobReferenceName.tsx, frontend/src/concepts/pipelines/content/PipelineRunTypeLabel.tsx, frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/PipelineDetailsTitle.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabDetails.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRowTitle.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/usePipelineRunFilter.ts, frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTable.tsx, frontend/src/concepts/pipelines/content/tables/utils.ts, frontend/src/concepts/pipelines/context/PipelinesContext.tsx, frontend/src/concepts/pipelines/context/useJobRelatedInformation.ts, frontend/src/pages/ApplicationsPage.tsx, frontend/src/pages/projects/components/DeleteModal.tsx
Closes: #1242
#1242
It fixes "_When a Pipeline Scheduled Run (aka a Job) creates Triggered Runs it creates it with a rather unpleasant name -- a fully lowercase, concatenated together string of the name of the Job._"
- Create scheduled run
- Go to triggered tab once scheduled run triggered
- Select multiple or single triggered run to delete run(s), on the delete modal the formatted  name(s)  should appear
- Click on the triggered run to go to the run details, see the formatted name on the page title and the bottom drawer
=> Fix Pipeline Job titles are partially handled

backend/.eslintrc, backend/src/plugins/kube.ts, backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts, backend/src/routes/api/dev-impersonate/index.ts, backend/src/routes/api/groups-config/groupsConfigUtil.ts, backend/src/routes/api/images/imageUtils.ts, backend/src/routes/api/segment-key/segmentKeyUtils.ts, backend/src/server.ts, backend/src/utils/adminUtils.ts, backend/src/utils/prometheusUtils.ts
Closes: #1826
Improve logging so we can filter through the full error object as we apply scenarios.
Startup in dev mode as a regular user.
None
=> Improve logging with objects

docs/architecture.md, frontend/src/__tests__/integration/hooks/useFetchState.spec.ts, frontend/src/__tests__/integration/pages/clusterSettings/ClusterSettings.spec.ts, frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.spec.ts, frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.stories.tsx, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/__tests__/integration/pages/projects/ProjectDetails.spec.ts, frontend/src/__tests__/integration/pages/projects/ProjectView.spec.ts, frontend/src/__tests__/integration/utils.ts, frontend/src/pages/modelServing/screens/global/EmptyModelServing.tsx, frontend/tsconfig.json
Revert direct merge to main. #1796
=> Revert "Revamp empty state in Model Serving Global"

frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeTableRow.tsx
Closes #1499 
Simply add a dropdown option.
Now for OOTB custom serving runtimes:
For non-OOTB custom serving runtimes:
1. Import a new custom serving runtime or duplicate an OOTB serving runtime, to make a non-OOTB serving runtime
2. Check the dropdown menu of the new custom serving runtime
3. You should be able to duplicate the non-OOTB serving runtime now
N/A
=> Add duplicate option for non-OOTB custom serving runtimes

.github/ISSUE_TEMPLATE/internal_techdebt.yml
Closes: https://github.com/opendatahub-io/odh-dashboard/issues/1788
I added the tech debt categories we are using internally on the board... might need additional attention as needed. 
Is it worth it? Not sure.
/hold
We can talk about this structure
=> Tech Debt Template

manifests/base/kustomization.yaml
Updates the tag to point at the nightly.
Hopefully this doesn't cause conflicts 🤞 (with each feature branch that merges into `incubation`)
The Why...  talking with @VaishnaviHire this will be needed for our transition to component manifests. The Operator will by default for ODH point at our `incubation` branch (the branch we take to ODH Manifests in the past) — however the current image it pulls will be that of `main`. This is a problem because it seems when we build off the branch the code will be of `main` but the manifests will be that of `incubation`. So let us point everything at the latest of `incubation` by this change.
=> Convert nightly over to the right image

frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetailsActions.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx
Closes #1568
Closes #1282
Action menu of Runs triggered page updated with "Stop run" & "Duplicate run" which is same as in Pipeline Run detail page.
@kywalker-rh tagging you for UX review
1. Create workbench and upload a pipeline.
2. Create run with Run type: Run once immediately after creation
3. Move back to Runs page, on Triggered tab.
4. Click on action menu on any row.
5. New actions added "Stop run", "Duplicate run".
6. "Stop run" is disabled when pipeline not running.
7. Click on both actions to run them.
=> Missing Duplicate Run from Triggered Action Menu

backend/src/routes/api/accelerators/acceleratorUtils.ts
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1863
There is a problem in gpu detection reduce function. When the detection iterates over each accelerator, it determines enablement by this logic `prevConfigured ?? checkConfigured()`. The issue was that we used `??` which would cause the configured var to always be false if it started as false because `false ?? true` is still false. This PR uses `||` instead which would give the correct result `false || true = true`
1. hop on a gpu cluster with non accelerator profiles and the gpu-migration-status config map deleted.
2. start the dashboard
3. a `migrated-gpu` accelerator should be added
no test impact -> hot fix
=> fix accelerator detection logic

frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx, frontend/src/pages/projects/screens/spawner/dataConnection/DataConnectionField.tsx, frontend/src/pages/projects/screens/spawner/dataConnection/useNotebookDataConnection.ts
Closes #1487 
Refactor the data connection object to the generic state object. Also, fixed the problem mentioned in the issue. It's because we have an unstable reference that will trigger the `useEffect` hook in `useNotebookDataConnection` every time the data connections are fetched. Instead of passing the array to the `useEffect` hook, we take the value we want outside of it and pass that stable value to the hook could fix this problem.
1. Create a workbench with data connection
2. Stop the workbench
3. Edit the workbench
4. Go to the data connection section, change it to create a new data connection
5. Make sure the choice will not be reset back to use existing data connection
N/A …
=> use generic object state on data connections and prevent resetting on edit

frontend/src/api/k8s/notebooks.ts, frontend/src/api/k8s/roleBindings.ts, frontend/src/concepts/pipelines/elyra/utils.ts, frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx
Closes #1721 
Check the Elyra service account role binding every time we create/restart a notebook with the enabled pipelines feature. If the role binding is there, check the `ownerReferences` field to see if the notebook is the owner, if not, patch it. If the role binding is not there, create a new one with the `ownerReferences` field and set the notebook as the owner. In this way, every time the user deletes the notebook, it will also delete the role binding.
1. Enable pipelines
2. Create a workbench
3. Check the role binding named `elyra-pipelines-${workbenchName}` is created and has the `ownerReferences` field
4. Try to delete the workbench, make sure the role binding is also deleted along with the deletion of the workbench
5. Create a workbench again, then remove the …
=> Add owner references to Elyra role binding when creating notebooks

frontend/jest.config.js, frontend/src/__tests__/unit/jest.d.ts, frontend/src/__tests__/unit/jest.setup.ts, frontend/src/__tests__/unit/testUtils/hooks.spec.ts, frontend/src/__tests__/unit/testUtils/hooks.ts, frontend/src/pages/projects/projectSharing/__tests__/useGroups.spec.ts, frontend/src/utilities/__tests__/useFetchState.spec.ts, frontend/src/utilities/useFetchState.ts
Test hook utils were previously introduced to help developers test hook state updates and stability.
This PR updates those hook utils to extend jest instead of having standalone utilities.
The old API:
```
const renderResult = testHook(useSayHello, 'world');
expectHook(renderResult)
.toBe(...)
.toStrictEqual(...)
.toHaveUpdateCount(...)
.toBeStable(...)
```
Becomes:
```
const renderResult = testHook(useSayHello)('world');
expect(renderResult).hookToBe(...)
expect(renderResult).hookToStrictEqual(...)
expect(renderResult).hookToHaveUpdateCount(...)
expect(renderResult).hookToBeStable(...)
```
While this change looks to be more verbose, it aligns with how assertions are done with jest. It also allows for the use of `expect.not`.
eg. `expect(renderResult).not.hookToBe(...)`
Another useful …
=> refactor hook test utils to extend jest matchers

frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeListButtonAction.tsx
Closes #1579 
Change the name to `Add model server` and add a tooltip on hover.
1. Go to data science project
2. Check if the button is `Add model server` now, but not `Add server`
3. Hover the button to see the tooltip
N/A
=> Revamp add server button and add tooltip

.github/workflows/auto-add-issues-to-project.yaml
=> adding workflow to auto-add issues to project boards

frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenSection.tsx
Closes #1582 
Closes #1581 
Added the alert as the description in the issue. ~One thing that needs to be noted is that the regular user with edit permission cannot enable the token, so the alert will show as soon as the user enables the external route.~
Found issue #1581 and also updated it here because they are tightly related, the user with edit permission cannot change the external route enablement anymore, and added a popover to explain that.
As the project admin:
As the project user with edit access:
1. Go to the project details page, try to add a model server
2. In the adding modal, check to enable the external route
3. Make sure the alert is shown
4. Check to enable token
5. Make sure the alert is gone
6. Try to impersonate as a user with the edit permission
7. Open the add server …
=> Show alert when external route is set while token is not set for model server

frontend/src/api/index.ts, frontend/src/api/k8s/pvcs.ts, frontend/src/api/k8s/storageClasses.ts, frontend/src/api/models/k8s.ts, frontend/src/app/App.tsx, frontend/src/app/AppContext.ts, frontend/src/concepts/k8s/useStorageClasses.ts, frontend/src/k8sTypes.ts, frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx, frontend/src/pages/projects/screens/spawner/service.ts, frontend/src/pages/projects/screens/spawner/storage/usePreferredStorageClass.ts, frontend/src/types.ts
first try at storageclasses get and promises
early stage ... runs and build without errors
related to https://github.com/opendatahub-io/odh-dashboard/issues/1701
trying to get all storageclasses via api call, working nicely.
never mind any 404 on /notebooks routes in screenshots, for local tests together with remote AWS Rosa cluster, I did not bother to install kubeflow and odh notebook controller, which create the routes from kind: Notebook as well as the CRD for Notebook, as part of ODH on my test Rosa cluster. PVC creation by ODH dashboard can be checked with that setup, too.
Q: @andrewballantyne since storage classes of the cluster are not namespace-specific, would it make sense to put the cluster storage classes into the React JS appContext instead of the ProjectDetailsContext? I …
=> first try at storageclasses get and promises

frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeTableRow.tsx, frontend/src/services/templateService.ts, frontend/src/types.ts, frontend/src/utilities/__tests__/addTypesToK8sListedResources.spec.ts, frontend/src/utilities/addTypesToK8sListedResources.ts
Closes: #1615
This PR aims to update the Custom Serving Runtime tooltip with the openshift resource information. Also, this PR takes care of adding "kind" to  the k8s resource. 
1) Log in to Dashboard with a Dashboard Admin user
2) go to Settings > Serving runtimes
3) find a Custom Serving Runtime if present, otherwise create one
4) go hover the "Question Mark" icon
5) try searching the OpenShift resource by using the information in the tooltip message
Added unit test case for the utilities component.
=> Update Custom Serving Runtime tooltip with Openshift resource information

backend/src/utils/resourceUtils.ts, frontend/src/api/models/openShift.ts, frontend/src/utilities/useAcceleratorState.ts, manifests/crd/acceleratorprofiles.opendatahub.io.crd.yaml
- This is a hot fix to move AcceleratorProfile crd version out of alpha.
- rename Nvidia to NVIDIA to align with proper naming conventions
1. oc apply the new crd using the new version `v1`
2. make sure UI can detect accelerator profiles (check network tab for successful request)
3. make sure migration successfully fetches accelerator profiles
4. check that migrated gpu uses new name
n/a this is naming fix
=> move AcceleratorProfile crd version out of alpha

frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.spec.ts, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionSection.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx, frontend/src/pages/projects/dataConnections/AWSField.tsx, frontend/src/pages/projects/screens/spawner/__tests__/spawnerUtils.spec.ts, frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
Closes #1583 
Simply made the bucket field required.
1. Go to data science project details page
2. Create a model server
3. Try to deploy a model, select `New data connection`, make sure the `Bucket` field is required
4. Try to leave it as blank, make sure you cannot click deploy button
Add some unit tests for `isAWSValid` function
=> Make data connection bucket field mandatory

docs/process-definition/triage.md
Adjusting triage to use the wiki so it's easier to modify and have status changes as we go along.
=> Moving triage to wiki for ease of use

frontend/src/__mocks__/mockServingRuntimeTemplateK8sResource.ts, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAddTemplate.tsx, frontend/src/pages/modelServing/customServingRuntimes/utils.ts, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx
Closes #1353 
1. Check the format of the custom serving runtime at the creation/edit time, and prompt an alert if the requirement is not met
2. If the template is accidentally changed to an invalid format (not through the dashboard UI because the UI will prevent that from happening), filter out the template selection at the serving runtime creation modal, because it makes no sense if you select a serving runtime template which is invalid
1. Go to the custom serving runtimes page
2. Copy an OOTB serving runtime
3. Change the kind to `ServingRuntim` or any value that's not `ServingRuntime`
4. Click submit, you will see the error message
5. Set the valid kind but remove the `container` or `supportedModelFormats` field in the spec
6. Click submit again, the same error message will show
7. …
=> Check serving runtime kind at creation time

backend/src/utils/httpUtils.ts
Closes: https://github.com/opendatahub-io/odh-dashboard/issues/1968
The backend passthrough proxy used string length for the `content-length` header which does not match the byte length of a payload which contains encoded characters. Therefore the payload was cut short when received by the api server resulting in malformed JSON being received.
Any request that uses our pass through proxy can be used for testing.
Easiest to test with projects.
Create a new project named `testł`. 
Expect the project to be created successfully.
No backend tests.
=> fix proxy call content-length header for encoded characters in payload

manifests/modelserving/caikit-ootb.yaml, manifests/modelserving/kustomization.yaml, manifests/modelserving/ovms-gpu-ootb.yaml, manifests/modelserving/ovms-ootb.yaml
Closes: #1940 #1911 
Add support for kserve to OVMS OOTB and add Caikit as an OOTB Custom Serving Runtime
1. Apply `oc apply -k manifests/modelserving -n <namespace>`
2. Check that all the modeles are present in the Custom Serving Runtime page
1. Not applying, it's a manifest change
=> Update ovms and add Caikit Custom Serving Runtime

backend/src/types.ts, backend/src/utils/constants.ts, backend/src/utils/resourceUtils.ts, docs/dashboard-config.md, frontend/src/__mocks__/mockDashboardConfig.ts, frontend/src/types.ts, manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml, manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Closes #1939 #1975
Create dashboard configuration to control kserve and modelmesh enablement as model serving platforms
Work In Progress I need to figure out the upgrade path of existing clusters
There are two main paths to test:
1. Deploy and old dashboardConfig object which doesn't contain `disableKServe` nor `disableModelMesh`
2. Start the dashboard
3. Check that in the `config` response, the dashboard is returning the following: `disableKServe: true` and `disableModelMesh: false`
1. Deploy the latest CRD
2. Either delete the `dashboardConfig` CR object or just add whatever configuration you want with `disableKServe` and `disableModelMesh`
3. Check that in the `config` response, the dashboard is returning the following `disableKServe: false` and `disableModelMesh: true`
1. Set up …
=> Create dashboard configuration to control kserve and modelmesh

backend/src/routes/api/notebooks/utils.ts, backend/src/utils/resourceUtils.ts, frontend/src/pages/projects/notebook/useRouteForNotebook.ts
Closes #1958 
Built and used image `quay.io/maistra-dev/odh-dashboard:gen-improve` for testing.
Changes here are pretty minimal, just tested that when a notebook is created/started from the jupyter tile + from a DS project with `ODHDashboardConfig.spec.disableServiceMesh=false`, the user is routed to the notebook correctly through the mesh. 
Verified the same when ODHDashboardConfig.spec.disableServiceMesh=true`, that the user is routed to the old route using oauth-proxy.
Credited @christianvogt as a co-author on the commit as these 3 changes came directly from Christian's review + suggestions on #1088 so I didn't want that to be lost to the sands of time. 
=> [Service Mesh] General Improvements

backend/src/routes/api/groups-config/groupsConfigUtil.ts, backend/src/routes/api/groups-config/index.ts, backend/src/utils/groupsUtils.ts, frontend/src/services/groupSettingsService.ts, frontend/src/utilities/__tests__/useWatchGroups.spec.ts, frontend/src/utilities/useWatchGroups.tsx
Closes #463 
This PR mainly changes the error handle a little bit, to make the error more clear.
1. When the group is not set, or it's an empty string, show the error `No group is set in the group config, please set one or more group.` (May need wording)
2. When the group does not exist, show the error in the pod log (We only showed it in the dashboard notification center before)
1. Change the group config in the dashboard config CR, change the `adminGroups` to a non-existed group like `fake-group`
2. Wait for 2 minutes (We need to wait until the backend fetches the latest cluster data)
3. Refresh the user management settings page, you should see 2 error messages in both pod logs and dashboard UI
- The group fake-group no longer exists in OpenShift and has been removed from the selected …
=> Log group config errors to the pod and refine logic

backend/src/routes/api/dsc/index.ts, backend/src/types.ts, backend/src/utils/dsc.ts, frontend/src/k8sTypes.ts, manifests/base/cluster-role.yaml
Closes: #1979 
Implements a shim layer to get the DSC Status state. A proxy effort until we have https://github.com/opendatahub-io/opendatahub-operator/issues/588 and we can switch to the pass-through k8s API.
Odd concern here is how we can determine the name of the DSC, so we can get just the status. This solution fetches the list, and gets the first item's `.status`. This won't be able to be done by the k8s pass-through.
Calling `GET <host>/api/dsc/status`.
```
{"conditions":[...statuses],"installedComponents":{"codeflare":false,"data-science-pipelines-operator":false,"kserve":false,"model-mesh":false,"odh-dashboard":true,"ray":false,"workbenches":false},"phase":"Ready"}
```
I imagine most will stick to `installedComponents` on first usage. `phase` of `"Ready"` may be needed to make …
=> Expose the DSC status for the client

frontend/src/__mocks__/mockServingRuntimeTemplateK8sResource.ts, frontend/src/__tests__/integration/pages/customServingRuntimes/CustomServingRuntimes.spec.ts, frontend/src/__tests__/integration/pages/customServingRuntimes/CustomServingRuntimes.stories.tsx, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx, frontend/src/__tests__/integration/pages/projects/ProjectDetails.stories.tsx, frontend/src/api/k8s/templates.ts, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAddTemplate.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeHeaderLabels.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeListView.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimePlatformsLabelGroup.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimePlatformsSelector.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeTableRow.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeView.tsx, frontend/src/pages/modelServing/customServingRuntimes/templatedData.tsx, frontend/src/pages/modelServing/customServingRuntimes/utils.ts, frontend/src/services/dashboardService.ts, frontend/src/services/templateService.ts, frontend/src/types.ts
Closes #1912 
The PR did the following things:
1. Add a required select dropdown when adding/editing custom serving runtimes, you can not click submit without selecting a value
2. Add a column to show the supported platform of the custom serving runtimes, and in the header show the available platforms based on the dashboard config
To test the custom serving runtime template labels:
1. Go to the custom serving runtimes page
2. Make sure the OOTB serving runtimes have both labels shown because they don't have the `opendatahub.io/modelServingSupport` annotation
3. Try to duplicate one of the serving runtimes, make sure you cannot submit without selecting a platform
4. Select a platform and create one
5. Make sure the label is correct
6. Try to edit the serving runtime again, choose a …
=> Adapt custom serving runtimes to KServe

backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts, backend/src/types.ts, frontend/src/__mocks__/mockClusterSettings.ts, frontend/src/__tests__/integration/pages/clusterSettings/ClusterSettings.spec.ts, frontend/src/components/SettingSection.tsx, frontend/src/pages/clusterSettings/ClusterSettings.tsx, frontend/src/pages/clusterSettings/ModelServingPlatformSettings.tsx, frontend/src/pages/clusterSettings/const.ts, frontend/src/types.ts
Closes #1913 
Add a section in the cluster settings to control the feature flags `disableKServe` and `disableModelMesh` in the dashboard config. When both checkboxes are unchecked, show a warning alert. When the multi-model option was initially selected but unchecked, show an info alert.
1. Go to the cluster settings page
2. Try to play around with the serving platform section, change the settings, and submit
3. Go to check the dashboard config YAML on the cluster to see if the feature flags are updated
4. Try to uncheck both checkboxes to see if the alert is shown
5. Try to check both options and save the changes
6. Try to uncheck the multi-model option and see if the info alert is shown
Add some integration tests on the cluster settings page to see if the alert is properly prompted and …
=> Add model serving platform settings

frontend/src/concepts/pipelines/context/PipelinesContextWorkaround.tsx, frontend/src/concepts/pipelines/context/index.ts, frontend/src/k8sTypes.ts, frontend/src/pages/projects/ProjectDetailsContext.tsx, frontend/src/pages/projects/screens/detail/pipelines/PipelinesSection.tsx
Closes: #1870
When DSP is disabled in v2 Operator, the context fails and blocks the rendering of DS Projects details view.
Two users:
1. Cluster Admin - The cluster admin can read 404 normally when an API is not available (404 error)
2. Regular user (eg. admin with no special permissions) - The regular user cannot read API from one that does not exist (403 error)
* This will be done through impersonate, same difference on cluster (the screenshot has a white button in the header)
> Note: There are a lot of screenshots to show each state, so I added collapsible sections. Expand each one to see the screenshots. Two sets will be provided in each section. One for the cluster-admin and one for the "regular user".
<details>
<summary>Screenshots</summary>
</details>
---
<details> …
=> Handle Removed but not Disabled DS Pipelines

frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/global/data.ts, frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTable.tsx, frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeDetails.tsx, frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx
Closes #1947 
WIP: add test cases
=> Implement KServe table on project details page

frontend/src/__mocks__/mockProjectK8sResource.ts, frontend/src/api/__tests__/apiMergeUtils.spec.ts, frontend/src/api/__tests__/k8sUtils.spec.ts, frontend/src/api/apiMergeUtils.ts, frontend/src/api/index.ts, frontend/src/api/k8sUtils.ts, frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx, frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTable.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/DeleteServingRuntimeModal.tsx, frontend/src/pages/modelServing/screens/projects/utils.ts, frontend/src/pages/modelServing/utils.ts
Closes: https://github.com/opendatahub-io/odh-dashboard/issues/1998
When creating a `ServingRuntime`, adds owner references to related resources:
- `RoleBinding`
- `ServiceAccount`
- ~`Secrets`~ _secrets are already associated with the `ServiceAccount` and get removed automatically_
When deleting a `ServingRuntime`, for compatibility in existing areas, we will continue to attempt to delete the service account and role binding.
In support of kserve, when an `InferenceService` is deleted from the global model serving page, the referenced `ServingRuntime` is also deleted (manually, not by use of owner references).
- Create a model server with all form options.
- Deploy a model to the new server.
- Inspect newly added `RoleBinding`, `ServiceAccount`, `Secrets` for `ownerReferences` pointing …
=> apply ownerReference to ServingRuntime related resources

backend/src/types.ts, backend/src/utils/constants.ts, docs/dashboard-config.md, frontend/src/__mocks__/mockAcceleratorProfile.ts, frontend/src/__mocks__/mockDashboardConfig.ts, frontend/src/__tests__/integration/pages/acceleratorProfiles/AcceleratorProfiles.spec.ts, frontend/src/__tests__/integration/pages/acceleratorProfiles/AcceleratorProfiles.stories.tsx, frontend/src/app/AppRoutes.tsx, frontend/src/pages/acceleratorProfiles/AcceleratorProfiles.tsx, frontend/src/types.ts, frontend/src/utilities/NavData.tsx, manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml, manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Closes: #1372
Added new feature flag `disableAccelerators` and new section in the admin panel for accelerators.
1. Add accelerator profile crd to your cluster, from `odh-dasboard/manifests/crd/acceleratorprofiles.opendatahub.io.crd.yaml`
2. Open ODH dashboard with clusteradmin login
3. In the sidebar, under setting section you can find Accelerator Profiles.
Note: This PR only provides empty state of the page, so make sure you don't have any AcceleratorProfile operand in your cluster.
Integration testing: To test Empty State of no Accelerator profile and created storybook too.
cc @yannnz
=> Add Accelerator section in Admin Panel and feature flag

frontend/package-lock.json, frontend/package.json, frontend/src/app/AppLauncher.tsx, frontend/src/redux/selectors/clusterInfo.ts, frontend/src/redux/selectors/project.ts, frontend/src/redux/selectors/user.ts, frontend/src/redux/selectors/utils.ts
Fix various dependency issues in the frontend folder.
Also fixes the redux spam about using the useSelector. We are removing redux in the near future, this just does an isEquals operation to silence the noise in the developer console.
=> Upversion dependencies & fix redux spam

frontend/src/concepts/explainability/useTrustyAINamespaceCR.ts
Closes: #1532 
When uninstalling TrustyAI from the dashboard settings menu , it gets uninstalled 
[Screencast from 2023-10-31 13-42-27.webm](https://github.com/opendatahub-io/odh-dashboard/assets/99238909/f761371f-343c-48f1-a0ef-ccb2bafdb7c3)
1. Use a dashboard build of f/mserving-metrics branch
2. Create a new data science project
3. Go to the settings tab
4. Click 'Enable TrustyAI'
5. Wait ~1 minute for the TrustyAI service to spin up (note due to a separate bug the success banner will show immediately, you still need to wait)
6. Uncheck the "Enable TrustyAI" checkbox
7. Confirm the deletion and click uninstall
NA
=> Could not find TrustyAI service

frontend/src/pages/modelServing/screens/metrics/BiasTab.tsx
Closes:
* #1533 
When the bias page renders, any selected charts in the browser session storage are validated to ensure they still exist i.e. they haven't been deleted by a direct call to a backend API.
Pre-requisites:
* A DSProject with: 
* TrustyAI installed
* a demo model installed
* some demo data sent to the model
* at least one bias metric configured
Instructions are for Chrome, it's possible with any browser but you'll have to figure out manipulating the session storage yourself in any others:
1. Navigate to the bias metrics tab
2. From the selector, select a chart
3. Open the browser console (F12) -> Applications tab
4. From the 'storage' group on the left menu bar, expand 'Session Storage'
5. In the main tab, look for a key that will be of the format: …
=> #1553 Add check for stale data in session storage for selected bias charts

frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/utils.tsx
Closes: #1543 
Removed the `Started at` date from Details tab of pipelineRun
When pipelineRuns are immediately triggerred the `finished at` first has N/A value later after completion of runs it gets it exact value
[Screencast from 2023-09-21 17-12-08.webm](https://github.com/opendatahub-io/odh-dashboard/assets/99238909/093cbcbf-2f4f-46e2-95ef-083a0046975d)
1. Check whether the Started at date is not present in the detail tab of pipelineRun
2. When creating a new piplineRun the `finished at` displays N/A instead of epoch value and later on gets the exact value
N/A
=> Removed Started at date

frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx, frontend/src/components/SimpleDropdownSelect.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx
Closes: #1861 
Added the <Truncate /> component within the Model Serving runtime to enhance text visibility and eliminate surplus content, ensuring a cleaner and more concise display.
1. Open settings < serving runtimes < Add serving runtime with long display-name.
2. Open a project and scroll below to "Models & model serving section"
3. Click on "Add server"
4. In dropdown of model serving, you can see long name being truncated.
5. After adding model serving, model serving name will also be truncated.
Added integration testing in model serving, related "Add server" modal and creating storybook component for it.
@vconzola
=> Support Truncated Model Serving Runtime Text Better

.github/workflows/pull_request.yml
Removes the restriction on running PR jobs only against `main` and `f/**` branches so that all branches are included.
=> run pull_request jobs for all branches

frontend/src/api/k8s/notebooks.ts
Closes #1954 
During review of #1088, it was left as an open comment to consolidate the three notebook annotation/label patch functions into one for code cleanness and to ensure future development doesn't "disable" one of the patches. 
This PR implements this by wrapping the three patches into one function, and calling it the same as before but now flattening the returned array of patches.
Tested by installing operator v2 with service mesh: see https://github.com/opendatahub-io/opendatahub-operator/pull/605. Then, tested creating notebooks from the jupyter tile and from a data science project to ensure that the correct annotations and label are still added to the notebook object when using Service Mesh. 
I would be happy to add tests, but would need some directions on how to add testing …
=> [Service Mesh] include SM notebook patches in one function

docs/process-definition/branches.md
Create a new section called `Merging upstream branches` in the `branches.md` documentation providing the steps necessary for creating an upstream branch merge PR.
cc @andrewballantyne
=> include steps for merging upstream branches

frontend/src/__mocks__/mockInferenceServiceK8sResource.ts, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx, frontend/src/components/ResourceActionsColumn.tsx, frontend/src/components/ResourceTr.scss, frontend/src/components/ResourceTr.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTableRow.tsx
Closes: https://github.com/opendatahub-io/odh-dashboard/issues/2052
When we delete an `InferenceService` it may take some time for the finalizers to complete the deletion. At deletion time, the resource will be marked with a `deletionTimestamp`. We can visually represent the deletion state in the UI when this timestamp is present.
Row items that are marked for deletion take on a 50% opacity and kebab menu is replaced with a `Ban` icon along with a tooltip. The components are made generically and can apply to other tables in the application at a later date.
Project details view:
Global model serving:
- Deploy a model, kserve or model mesh.
- Delete the model from the global serving page or from the project details page
- Observe the row with the new visuals
Added integration test.
Self …
=> visually represent InferenceService resources marked for deletion

frontend/src/pages/projects/projectSettings/ModelBiasSettingsCard.tsx
Closes: #1996 
This PR aims to display error message on enabling TrustyAI via UI.
1) Create a Data Science Project
2) Navigate to DSP page
3) Click Settings
4) Check the Enable TrustyAI checkbox, you will show the error (only if  TrustyAIService CRD not installed on your cluster)
NA
=> Display error message on enabling TrustyAI via UI

frontend/src/pages/clusterSettings/ClusterSettings.tsx, frontend/src/pages/groupSettings/GroupSettings.tsx, frontend/src/pages/modelServing/screens/global/ModelServingGlobal.tsx, frontend/src/pages/projects/screens/detail/ProjectDetails.tsx, frontend/src/pages/projects/screens/detail/pipelines/ProjectPipelineBreadcrumbPage.tsx, frontend/src/pages/projects/screens/projects/ProjectView.tsx, frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
Changed three page titles to match the navigation item casing.  Top level items should be Title Case, all nested items should be Sentence case.  
Cluster settings (was Cluster Settings), User management (instead of User and group settings) and Data Science Projects (instead of Data science projects since it's a top level item) were all changed.
Ran the site locally, loaded all impacted pages and ensured that the page title now matches the navigation item on the left hand side.
Ran storybook and other tests before putting up PR - none needed adjustment.
Closes: #1907
=> Fix page title sentence casing

backend/src/routes/api/namespaces/namespaceUtils.ts
This functionality has been accidentally moved to `MODEL_MESH_PROMOTION` case, breaking service mesh support in newly created data science projects.
Closes #2095 
=> fix: adds service mesh annotations on ns creation

frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeReplicaSection.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx, frontend/src/pages/notebookController/screens/server/AcceleratorSelectField.tsx
Closes: https://github.com/opendatahub-io/odh-dashboard/issues/1580
Add tooltips to Model Server Modal
- Create DS Project
- Scroll down to **Models and model servers** section
- Click **Add model server** button
- under **Add model server** pop up check to verify the popover 
=> Add tooltips to Model Server Modal

frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenSection.tsx
Closes #2049 
In https://github.com/opendatahub-io/odh-dashboard/pull/1862, we automatically check the `token authorization` checkbox when the route is enabled. However, we didn't add the default service account in this action. This PR is to fix that issue.
1. Go to a model-mesh project
2. Add a model server
3. Check the Model Route section
4. Make sure the token authorization is also checked and a default service account is added
Add a check in the integration test to make sure the service account token is added
=> Automatically generate first token when enable route when adding modelmesh server

frontend/src/__mocks__/mockImageStreamK8sResource.ts, frontend/src/__mocks__/mockNotebookK8sResource.ts, frontend/src/__tests__/integration/pages/projects/ProjectDetails.spec.ts, frontend/src/__tests__/integration/pages/projects/ProjectDetails.stories.tsx, frontend/src/api/k8s/imageStreams.ts, frontend/src/api/k8s/notebooks.ts, frontend/src/k8sTypes.ts, frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookImageDisplayName.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx, frontend/src/pages/projects/screens/detail/notebooks/const.ts, frontend/src/pages/projects/screens/detail/notebooks/types.ts, frontend/src/pages/projects/screens/detail/notebooks/useNotebookImage.ts, frontend/src/pages/projects/screens/detail/notebooks/useNotebookImageData.ts, frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx, frontend/src/pages/projects/screens/spawner/imageSelector/ImageSelectorField.tsx, frontend/src/pages/projects/screens/spawner/useImageStreams.ts, frontend/src/typeHelpers.ts
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1370
Added a new annotation to workbenches called `opendatahub.io/image-display-name` which stores the display name of the selected image. this gets used when displaying the image on the notebook table if the image itself could not be found. if it is not found it will also include the wording `(deprecated)`.
When you got to edit this workbench with a deprecated image. the image will be _unselected_ and require you to select a new one
1. create a custom notebook image
2. create a workbench with that custom image
3. delete the custom image
4. verify that deprecated wording is on the workbench table
5. verify that on edit, the image selection is required
6. remove the annotation (`opendatahub.io/image-display-name`) from the …
=> logic for deprecated images

frontend/src/__tests__/integration/pages/clusterSettings/ClusterSettings.spec.ts, frontend/src/pages/clusterSettings/ModelServingPlatformSettings.tsx
Closes #2047 
Previously, we only showed this alert when `Multi-model serving platform` was checked but unchecked later. In this PR, we apply the same behavior to `Single model serving platform` as well. No matter which checkbox was checked before but unchecked later, we show this info alert with the following text.
1. Enable both single and multi model serving platforms
2. Uncheck either of them, but not both, see if the alert is showing
Add an integration test check to see if this alert also shows when single model serving platform was checked but unchecked later.
=> Add info alert to kserve on settings page

frontend/src/__tests__/integration/pages/projects/ProjectDetails.spec.ts, frontend/src/pages/projects/screens/detail/notebooks/NotebookImageDisplayName.tsx
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1370
Updated text to lowercase and bolded text in popover
run storybook and navigate to the unknown story to view what a image looks like when a workbench references an image that does not exists and does not have a past name
updated test to reflect `Unknown` to `unknown`
@xianli123 This is just a fix from the past mocks
=> fixed ux on label text

frontend/src/pages/modelServing/screens/metrics/MetricsChart.tsx, frontend/src/pages/modelServing/screens/metrics/ModelGraphs.tsx, frontend/src/pages/modelServing/screens/metrics/ServerGraphs.tsx, frontend/src/pages/modelServing/screens/metrics/const.ts, frontend/src/pages/modelServing/screens/metrics/utils.tsx
Closes: #2090 
Makes the following changes:
* Model metrics and server metrics HTTP requests charts are now stacks
* Fixes a bug with stack charts where the domain is truncated
* Changes the colour scheme away from red / green to avoid a11y issues
* Check the HTTP charts for server and model metrics ensuring they are now a stack (i.e. successful and failed requests add up to a total value, so if there are 5 failed requests and 5 successful requests at the same time, the total on the graph should be 10 at that point).
Area is not yet tested so no impact.
=> Performance metric chart needs area charts to be in a stack

frontend/src/__tests__/integration/pages/clusterSettings/ClusterSettings.stories.tsx, frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.stories.tsx, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx, frontend/src/__tests__/integration/pages/projects/ProjectDetails.spec.ts, frontend/src/__tests__/integration/pages/projects/ProjectDetails.stories.tsx, frontend/src/concepts/areas/__tests__/utils.spec.ts, frontend/src/concepts/areas/const.ts, frontend/src/concepts/areas/index.ts, frontend/src/pages/clusterSettings/ClusterSettings.tsx, frontend/src/pages/clusterSettings/ModelServingPlatformSettings.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeHeaderLabels.tsx, frontend/src/pages/modelServing/screens/global/ModelServingGlobal.tsx, frontend/src/pages/modelServing/screens/projects/EmptyModelServingPlatform.tsx, frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx, frontend/src/pages/modelServing/screens/projects/ModelServingPlatformSelect.tsx, frontend/src/pages/modelServing/screens/projects/__tests__/getProjectModelServingPlatform.spec.ts, frontend/src/pages/modelServing/screens/projects/utils.ts, frontend/src/pages/modelServing/screens/types.ts, frontend/src/pages/modelServing/useServingPlatformStatuses.ts
Closes #1994 
Closes #1995
There are several checks in this PR:
**When the platforms are installed:**
When we enter an unlabelled project and both `disableKServe` and `disableModelMesh` feature flags are set to `true`, you will get the empty state to tell you to ask for the administrator to enable platform selection.
---
**When either platform is not installed:**
On the cluster settings page:
1. You will see the grey out checkbox which prevents you from enabling it if the platform is not installed on the cluster
2. If you are the cluster admin, you will see the link to bring you to the `DataScienceCluster` resource page on the OpenShift console
3. If you don't have edit access to `DataScienceCluster`, the link button will be a plain text
---
On project details page:
If the project is …
=> Add empty state when no serving platform is enabled

manifests/modelserving/caikit-ootb.yaml, manifests/modelserving/kustomization.yaml
Closes #2058 
Support Caikit with REST
1. Deploy this template
2. Deploy a new kserve model (I used `demo-models/flan-t5-small-caikit/flan-t5-small-caikit` in rhods-public)
3. Do an inference:
```bash
> export KSVC_HOSTNAME=$(oc get ksvc <inference-name>-predictor -n <namespace> -o jsonpath='{.status.url}' | cut -d'/' -f3) 
> curl -kL -H 'Content-Type: application/json' -d '{"model_id": "flan-t5-small-caikit", "inputs": "At what temperature does Nitrogen boil?"}' https://${KSVC_HOSTNAME}/api/v1/task/text-generation
```
No automated testing
=> Support Caikit Serving Runtime with REST

frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.spec.ts, frontend/src/pages/modelServing/screens/global/EmptyModelServing.tsx
Closes #2132 
Change the link button text
1. Go to the global model serving page
2. Select a project, it needs to be a model mesh labelled project with no model server added yet
3. You will see the screenshot above
4. Make sure you see the project name is the display name but not the k8s name
Change the test case a little bit to reflect the change in this PR
=> Change empty global model mesh serving link text to project display name

frontend/src/pages/modelServing/screens/metrics/MetricsChart.tsx, frontend/src/pages/modelServing/screens/metrics/ModelGraphs.tsx, frontend/src/pages/modelServing/screens/metrics/ServerGraphs.tsx, frontend/src/pages/modelServing/screens/metrics/types.ts, frontend/src/pages/modelServing/screens/metrics/utils.tsx
Closes: #2091 
* Removes x100 scale from HTTP requests charts on model and server metrics screens.
Model metrics:
Server metrics:
* Open metrics pages and verify there is no scale applied to the graph data
N/A
=> Removes x100 scale from HTTP request charts

frontend/src/__tests__/integration/pages/projects/ProjectDetails.spec.ts, frontend/src/pages/projects/screens/detail/DetailsSection.tsx, frontend/src/pages/projects/screens/detail/ProjectDetailsComponents.scss, frontend/src/pages/projects/screens/detail/ProjectDetailsComponents.tsx, frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookList.tsx, frontend/src/pages/projects/screens/detail/pipelines/PipelinesSection.tsx, frontend/src/pages/projects/screens/detail/storage/StorageList.tsx
Closes: #2076
Closes: #1860
@andrewballantyne this solution uses custom CSS which is something we try to avoid in this project but it does make the solution simple to handle the various use cases.
There are many use cases to consider that make for a complex scenario:
- section is hidden because component is not installed
- section is hidden because section is controlled by a feature flag that is disabled
- section contains no contents and is considered 'empty' => requires divider
- section manages its own internal state and may request a divider
- section contains data => no divider
- the last section in the list => no divider
- section contains an error => no divider, displays alert box
This solution uses CSS as it requires only 2 touch points:
- Adds a class name to the stack component …
=> improve section divider rendering

backend/src/routes/api/images/imageUtils.ts, backend/src/types.ts, frontend/src/__mocks__/mockByon.ts, frontend/src/__tests__/integration/pages/acceleratorProfiles/ManageAcceleratorProfile.spec.ts, frontend/src/__tests__/integration/pages/acceleratorProfiles/ManageAcceleratorProfile.stories.tsx, frontend/src/__tests__/integration/pages/notebookImageSettings/NotebookImageSettings.spec.ts, frontend/src/__tests__/integration/pages/notebookImageSettings/NotebookImageSettings.stories.tsx, frontend/src/pages/BYONImages/BYONImageAccelerators.tsx, frontend/src/pages/BYONImages/BYONImageModal/AcceleratorIdentifierMultiselect.tsx, frontend/src/pages/BYONImages/BYONImageModal/ManageBYONImageModal.tsx, frontend/src/pages/BYONImages/BYONImagesTable.tsx, frontend/src/pages/BYONImages/BYONImagesTableRow.tsx, frontend/src/pages/BYONImages/tableData.tsx, frontend/src/pages/acceleratorProfiles/screens/manage/IdentifierSelectField.tsx, frontend/src/pages/acceleratorProfiles/screens/manage/ManageAcceleratorProfileDetailsSection.tsx, frontend/src/pages/acceleratorProfiles/screens/manage/tolerations/TolerationFields.tsx, frontend/src/types.ts
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1439
closes: https://github.com/opendatahub-io/odh-dashboard/issues/2056
- Added accelerators column to image admin page
- each row matches to what accelerator profiles exist in the cluster
- pending [UX issue](https://github.com/opendatahub-io/odh-dashboard/issues/2056) for when an image does not have the "recommended accelerators" annotation
- a button that navigates with state of identifier to the create accelerator profile page
- multi select input value for accelerator identifiers
- this uses the identifiers from all accelerator profiles found to populate the dropdown
- navigate to create page when clicking "Create accelerator"
**When clicking on "Create profile"**
_multiple identifiers_
_one identifier_
1. create a …
=> Added accelerator column and field

frontend/src/__tests__/integration/pages/acceleratorProfiles/AcceleratorProfiles.spec.ts, frontend/src/concepts/dashboard/DashboardSearchField.tsx, frontend/src/pages/acceleratorProfiles/screens/list/AcceleratorProfilesTable.tsx
Closes: #1374
Added filter to accelerator profile table.
1. Add accelerator profile CR.
2. Settings < accelerator profiles
3. On accelerator profile table page, try filter some accelerators.
Added some integration test within List accelerator profile tests.
@yannnz
=> Accelerator profile table filter

frontend/src/__tests__/integration/pages/acceleratorProfiles/AcceleratorProfiles.spec.ts, frontend/src/pages/acceleratorProfiles/screens/list/AcceleratorProfiles.tsx, frontend/src/pages/acceleratorProfiles/screens/list/AcceleratorProfilesTable.tsx, frontend/src/pages/acceleratorProfiles/screens/list/AcceleratorProfilesTableRow.tsx, frontend/src/pages/acceleratorProfiles/screens/list/DeleteAcceleratorProfileModal.tsx
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1376
Adds a delete modal to accelerator profiles page and updated some internal text to say acceleratorProfile instead of accelerator
1. create a profile
2. located it on the table
3. action button > delete
4. delete should work and refresh the page automatically
added tests for delete flow
=> add delete accelerator profile modal

frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.stories.tsx, frontend/src/concepts/projects/ProjectSelector.tsx, frontend/src/concepts/projects/ProjectSelectorNavigator.tsx, frontend/src/concepts/projects/ProjectsContext.tsx, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/ModelServingContext.tsx, frontend/src/pages/modelServing/screens/global/ModelServingGlobal.tsx, frontend/src/pages/modelServing/screens/global/ModelServingProjectSelection.tsx, frontend/src/pages/projects/screens/detail/DetailsSection.tsx
Closes #2137 
1. When you switch between the navs (projects, pipelines, model serving), the preferred project is always remembered and synced up
2. When you choose `All projects` on the global model serving page, the preferred project is set to `null` (We don't have that dropdown selection on the pipelines page)
3. Remove the filter label so you could select all the available projects on the global model serving page, but not only the dashboard projects
4. Fix some nits from https://github.com/opendatahub-io/odh-dashboard/pull/2123
1. Go to the projects page
2. Get into any project
3. Click on the model serving on the side nav
4. You should be able to land on the page with the same selection as the project you just entered
5. Go to the pipelines page, you can see the selection is kept
6. …
=> Use sync preferred project when switching to global model serving page

manifests/modelserving/caikit-ootb.yaml
Closes #2143 
1. Deploy the new template with `oc apply -k manifests/modelserving`
2. Create a new Caikit deployment with kserve
3. Check that you can infer the results
No testing involved
=> Cleanup of caikit OOTB

backend/src/routes/api/images/imageUtils.ts, backend/src/utils/constants.ts, frontend/src/__mocks__/mockImageStreamK8sResource.ts, frontend/src/k8sTypes.ts, frontend/src/pages/projects/screens/spawner/__tests__/spawnerUtils.spec.ts, frontend/src/pages/projects/screens/spawner/const.ts, frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
Closes: #2084
Adds filters to both Jupyter tile & DS Projects for version tags that have `opendatahub.io/image-tag-outdated` annotation.
Add the annotation to the ImageStreamTag. If it exists on the tag it will not show up in the Jupyter Tile or DS Projects image-tag selection.
Wrote tests for modified frontend code. Backend remains untested as it is deprecated.
=> Update jupyter & ds projects to hide outdated images

frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.stories.tsx, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/pages/projects/screens/detail/ProjectDetailsComponents.scss
contributes to https://github.com/opendatahub-io/odh-dashboard/pull/2041
this fixes the tests to pass in adding or editing model mesh servers tests and project details empty page tests without regressions in other tests
check tests logs that all test pass for ServingRuntimeList.spec.ts and ProjectDetails.spec.ts
updates selectors and some pf4 styles
=> fix test fails on project details page and serving runtimes

frontend/src/concepts/explainability/ExplainabilityContext.tsx, frontend/src/concepts/explainability/content/DeleteTrustyAIModal.tsx, frontend/src/concepts/explainability/content/InstallTrustyAICheckbox.tsx, frontend/src/concepts/explainability/content/TrustyAIServerTimedOutError.tsx, frontend/src/concepts/explainability/content/TrustyAIServiceControl.tsx, frontend/src/concepts/explainability/content/TrustyAIServiceNotification.tsx, frontend/src/concepts/explainability/useManageTrustyAICR.ts, frontend/src/concepts/explainability/useTrustyAIAPIRoute.ts, frontend/src/concepts/explainability/useTrustyAINamespaceCR.ts, frontend/src/concepts/pipelines/context/usePipelineNamespaceCR.ts, frontend/src/pages/projects/components/GenericHorizontalBar.tsx, frontend/src/pages/projects/projectSettings/ModelBiasSettingsCard.tsx, frontend/src/utilities/const.ts
Closes: #1531
This fixes the UX around installing and uninstalling Trusty AI, this includes:
- Updating the condition by which the dashboard decides Trusty is installed, in order to utilise the fixes provided by the Trusty team.
- General rework of the logic to ensure users receive notifications of success / error robustly at the correct time.
- Adds a spinner whilst the service is installing.
- An update to how the `Project Settings` page tabs are loaded to fix an issue where all tabs are mounted immediately regardless of `mountOnEnter` logic.
**NOTE:** It takes about 90 seconds on average for TrustyAI to install, rather than post a monster GIF, the first shows the transition when the checkbox is clicked, the second shows the transition from the spinner to a success notification.
**NB: …
=> Fixes: "When enabling TrustyAI on a project, the dashboard immediately shows success notification" 

backend/src/utils/notebookUtils.ts
Closes #2208
This change fixes how the service mesh feature flag is read when creating/assembling a notebook from the jupyter tile. Previously, it was negated and set as a string, now we keep it as a boolean when checking the value, and assign it to a string when setting the needed annotation/labels.
NOTE: the two commits marked tmp: will be removed after testing and prior to PR merged. 
Tested using image: `quay.io/maistra-dev/odh-dashboard:fix-flag-read` and will be showing Andrew changes in gmeet. 
=> [service mesh] Fix Service Mesh flag read in Jupyter tile

frontend/src/__mocks__/mockDataConnection.ts, frontend/src/__mocks__/mockSecretK8sResource.ts, frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.stories.tsx, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx, frontend/src/__tests__/integration/pages/projects/ProjectDetails.stories.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionExistingField.tsx, frontend/src/pages/modelServing/screens/projects/__tests__/utils.spec.ts, frontend/src/pages/modelServing/screens/projects/utils.ts
Closes: #1604
This PR filters out data connection without bucket name in the Deploy model Modal
1. Create and open project.
2. Create a data connection without bucket name.
3. Create model server.
4. Click on "Deploy model"
5. In the Deploy model modal you can see list of Data connections.
6. Above that you can see the tooltip. 
7. In the dropdown without bucket connection is removed.
Added unit test to test `filterOutConnectionsWithoutBucket` utility function
@vconzola
=> Filter data connections without bucket name in deploy model modal

docs/dashboard-config.md, frontend/src/__mocks__/mockDashboardConfig.ts, frontend/src/__tests__/integration/pages/edge/EdgeModels.spec.ts, frontend/src/__tests__/integration/pages/edge/EdgeModels.stories.tsx, frontend/src/app/AppRoutes.tsx, frontend/src/concepts/areas/const.ts, frontend/src/concepts/areas/types.ts, frontend/src/k8sTypes.ts, frontend/src/pages/edge/EdgeModels.tsx, frontend/src/pages/edge/EdgeModelsRoutes.tsx, frontend/src/pages/edge/EmptyEdgeModels.tsx, frontend/src/utilities/NavData.tsx, manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml, manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Closes: https://github.com/opendatahub-io/odh-dashboard/issues/2061
As part of new Edge specific initiatives, this PR introduces new section for Edge MVP and an empty state component on the new Model Registry page.
Its just the first step in Edge initiative and there will be more features introduced soon.
Click Edge MVP option on the sidebar and select Model Registry
Integration Testing: Included simple test to check the title of EmptyState has rendered.
=> Edge Model Registry - Sidebar and EmptyState

frontend/src/concepts/pipelines/content/createRun/const.ts, frontend/src/concepts/pipelines/content/createRun/contentSections/RunTypeSectionScheduled.tsx, frontend/src/concepts/pipelines/content/createRun/submitUtils.ts, frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts, frontend/src/utilities/__tests__/string.spec.ts, frontend/src/utilities/__tests__/time.spec.ts, frontend/src/utilities/string.ts, frontend/src/utilities/time.ts
Closes: #1244
Added a feature to include numerical input to create Periodic Scheduled Runs on side of dropdown to select time unit.
After creating run, the output is like (no change to this page)
1. Create a pipeline server and import a pipeline.
2. Click on "Runs" tab on sidebar.
3. Click "Create run".
4. Fill the required information 
* Choose "Schedule recurring run".
5. Choose Trigger type "Periodic" and enter time value in text field below "Run every" and choose time unit.
6. Click on "Create"
7. At "Scheduled" tab, you can see the run created with time mentioned below "Trigger".
Added unit test to test string and time utility functions.
cc @yannnz
=> Add a numerical input to Create Periodic Scheduled Runs

backend/src/utils/constants.ts, docs/dashboard-config.md, frontend/src/__mocks__/mockDashboardConfig.ts, frontend/src/__tests__/integration/pages/customServingRuntimes/CustomServingRuntimes.spec.ts, frontend/src/pages/modelServing/screens/projects/ModelServingPlatformSelect.tsx, manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Closes #2238 
1. Delete the dashboard deployment in DSC
2. Configure DSC with the configuration bellow
3. Check that modelmesh is enabled by default
4. Check that KServe selection has the right wording.
```yaml
dashboard:
devFlags:
manifests:
- contextDir: manifests
sourcePath: ''
uri: 'https://github.com/lucferbux/odh-dashboard/tarball/issue-2238'
managementState: Managed
```
No further testing added, working on the kserve migration coverage on https://github.com/opendatahub-io/odh-dashboard/issues/1980
=> Enable modelmesh on cluster creation

frontend/src/concepts/pipelines/NoPipelineServer.tsx, frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx, frontend/src/pages/projects/screens/detail/EmptyDetailsList.tsx, frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookList.tsx, frontend/src/pages/projects/screens/detail/pipelines/PipelinesList.tsx, frontend/src/pages/projects/screens/detail/storage/StorageList.tsx
Closes: #1857 
This PR aims to cleanup empty state text on each of our sections in the Projects view, that is redundant.
Create a new data science project and check each section in project view.
=> Cleanup Empty State Text

frontend/src/__mocks__/mockPipelineVersionsProxy.ts, frontend/src/__tests__/integration/components/pipelines/PipelineSelector.spec.ts, frontend/src/__tests__/integration/components/pipelines/PipelineSelector.stories.tsx, frontend/src/api/pipelines/custom.ts, frontend/src/concepts/pipelines/apiHooks/usePipelineQuery.ts, frontend/src/concepts/pipelines/apiHooks/usePipelineVersionsForPipeline.ts, frontend/src/concepts/pipelines/apiHooks/usePipelines.ts, frontend/src/concepts/pipelines/content/createRun/RunForm.tsx, frontend/src/concepts/pipelines/content/createRun/const.ts, frontend/src/concepts/pipelines/content/createRun/contentSections/PipelineSection.tsx, frontend/src/concepts/pipelines/content/createRun/contentSections/PipelineVersionSection.tsx, frontend/src/concepts/pipelines/content/createRun/submitUtils.ts, frontend/src/concepts/pipelines/content/createRun/types.ts, frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts, frontend/src/concepts/pipelines/content/createRun/utils.ts, frontend/src/concepts/pipelines/content/pipelineSelector/PipelineSelector.tsx, frontend/src/concepts/pipelines/content/pipelineSelector/PipelineSelectorTableRow.tsx, frontend/src/concepts/pipelines/content/pipelineSelector/columns.ts, frontend/src/concepts/pipelines/kfTypes.ts
JIRA:
[RHOAIENG-266](https://issues.redhat.com/browse/RHOAIENG-266)
[RHOAIENG-268](https://issues.redhat.com/browse/RHOAIENG-268)
This PR creates a selector for both pipeline and pipeline versions that could be used in many places. Here in this PR, we add this selector to the pipeline runs creation form.
When no pipeline is selected, the version selector is disabled
Now you could select the pipeline, if the number is less than 10, we will not show the `View more` button
After the pipeline is selected, the default version will be automatically selected
If the number is more than 10, it will show the badge of the visible options and the total size
Clicking on it will load more options
If the name is truncated, the tooltip will show up. If the version has a description, another tooltip will …
=> Create pipeline and pipeline version selector and change pipeline run creation page

frontend/src/__mocks__/mockPipelinesProxy.ts, frontend/src/__tests__/integration/components/pipelines/PipelineSelector.spec.ts, frontend/src/__tests__/integration/components/pipelines/PipelineSelector.stories.tsx, frontend/src/__tests__/integration/components/pipelines/PipelineVersionImportModal.spec.ts, frontend/src/__tests__/integration/components/pipelines/PipelineVersionImportModal.stories.tsx, frontend/src/api/pipelines/errorUtils.ts, frontend/src/concepts/pipelines/content/createRun/RunForm.tsx, frontend/src/concepts/pipelines/content/createRun/contentSections/PipelineSection.tsx, frontend/src/concepts/pipelines/content/createRun/contentSections/PipelineVersionSection.tsx, frontend/src/concepts/pipelines/content/import/ImportPipelineButton.tsx, frontend/src/concepts/pipelines/content/import/ImportPipelineSplitButton.tsx, frontend/src/concepts/pipelines/content/import/ImportPipelineVersionButton.tsx, frontend/src/concepts/pipelines/content/import/PipelineFileUpload.tsx, frontend/src/concepts/pipelines/content/import/PipelineImportModal.tsx, frontend/src/concepts/pipelines/content/import/PipelineVersionImportModal.tsx, frontend/src/concepts/pipelines/content/import/useImportModalData.ts, frontend/src/concepts/pipelines/content/import/utils.ts, frontend/src/concepts/pipelines/content/pipelineSelector/PipelineSelector.tsx, frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTable.tsx, frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableRow.tsx, frontend/src/pages/pipelines/global/pipelines/GlobalPipelinesTableToolbar.tsx
JIRA: [RHOAIENG-269](https://issues.redhat.com/browse/RHOAIENG-269)
Create a modal which allows user to upload a version for a specific pipeline
Implementation:
When the pipeline is selected, it will automatically generate the name for the version, user can edit it, too
Added a split button on the global pipelines page, which supports both uploading the pipelines and uploading the pipeline versions
Add a dropdown item in the pipeline row action menu, which allows the user to upload new version to a specific
On create run page, add 2 link buttons to support uploading pipelines and pipeline versions on this page
1. Go to the global pipelines page
2. Try to upload a version or upload a pipeline
3. You could verify where the version is successfully uploaded in the create run page, if you …
=> Create pipeline version upload modal

frontend/src/pages/projects/notebook/utils.ts, frontend/src/utilities/notebookControllerUtils.ts
Closes: #1935 
This PR adds displaying the various event states when pulling the istio-proxy container.  Before this PR, the percentage is not updated for the different stages of pulling the istio-proxy container as it was for the oauth-proxy container.
This is implemented by adding a function wrapping around the switch statement previously used for oauth-proxy, and now can be used for either `oauth` or `istio` proxy depending on which is being pulled/started. The helper function `capitalizeFirstLetter` is used to maintain the same messages as before (in terms of capitalizing Oauth vs oauth). 
Note: the 'pulling istio proxy' message *should* not appear - this proxy sidecar will be pulled for the dashboard's sidecars as well so.
Tested by installing operator v2 with service mesh: see …
=> [Service Mesh]: handle istio proxy events

frontend/src/utilities/tolerations.ts
closes: https://issues.redhat.com/browse/RHOAIENG-807
Fixes a bug where tolerations are removed when enabling a workbench.
1. create a workbench with a accelerator profile that has tolerations
2. check that tolerations are on the k8s Notebook resource
3. disable and re enable the workbench
4. check for tolerations again
hot fix
=> Fixes Workbench Tolerations Being Removed on Toggle Start

frontend/jest.config.js, frontend/src/concepts/pipelines/content/__tests__/utils.spec.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTitle.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/utils.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTableRow.tsx, frontend/src/concepts/pipelines/topology/__tests__/pipelineUtils.spec.ts, frontend/src/pages/ApplicationsPage.tsx
Closes: #1182  
This PR will truncate the long pipeline name and solve the pipeline runs scheduled and Triggered table width issue. Also solves the breaking of pipelinerun details page and pipeline details page because of the long name. 
1) Have a project
2) Create a Pipeline with long name, like long pipeline nameeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
3) Create a Run that is scheduled or Triggered
4) View the Global Pipeline Runs page
5) Also check the pipelinerun details page (details tab, title with label, breadcrumb)
Added unit test case.
=> Fix pipeline runs Scheduled & Triggered Table width issue

frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelServingGlobal.cy.ts, frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/pages/modelServing/screens/global/ServeModelButton.tsx
Closes https://issues.redhat.com/browse/RHOAIENG-544
Adds a tooltip that appears on the 'Deploy model' button on the global Model Serving page if the button is disabled because no project is selected.
The tooltip is shown here in the empty state when there are no deployed models, but the ServeModelButton component used there is the same one used above the table in the non-empty state of the page, so the tooltip implementation affects both views.
cc @vconzola
Viewing the Model Serving page with no project selected, and observing that the disabled button has the new tooltip. Added Cypress test, see below.
Added to existing Cypress tests for the Model Serving page. The new test visits the all-projects view of the page, triggers a mouse hover event on the button and checks that the tooltip is …
=> Show tooltip on disabled 'Deploy model' button when no project is selected

frontend/src/pages/modelServing/screens/metrics/utils.tsx
Closes: [RHOAIENG-245](https://issues.redhat.com//browse/RHOAIENG-245)
Updates prometheus queries to round HTTP request metrics to the nearest integer
Observe model and server metrics and verify the charts only show integer values.
N/A bugfix, area is not yet tested.
=> Fixes: HTTP Requests charts should not show floating point values

frontend/.env.cypress.mock, frontend/package-lock.json, frontend/package.json, frontend/src/__tests__/cypress/cypress.config.ts, frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelServingGlobal.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/modelServing/ServingRuntimeList.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/projects/project-list.scy.ts, frontend/src/__tests__/cypress/cypress/pages/clusterSettings.ts, frontend/src/__tests__/cypress/cypress/pages/components/Modal.ts, frontend/src/__tests__/cypress/cypress/pages/projects.ts, frontend/src/__tests__/cypress/cypress/pages/servingRuntimes.ts, frontend/src/__tests__/cypress/cypress/support/commands/axe.ts, frontend/src/__tests__/cypress/cypress/support/commands/index.ts, frontend/src/__tests__/cypress/tsconfig.json
Closes: https://github.com/opendatahub-io/odh-dashboard/issues/2252
Adds `cypress-axe` to cypress integration.
Currently configured to fail on `serious` and `critical` issues. There are `moderate` issues currently in the app. We can revisit this configuration in the future.
Added a new custom command `testA11y` to help with reporting axe related violations.
There isn't a silver bullet to continuously test accessibility violations. It's up to individual tests to make an assertion at various points. But I have update existing tests to make accessibility checks on page load and on modal open.
=> add axe support to cypress for accessibility testing

frontend/src/__mocks__/mockDataSciencePipelinesApplicationK8sResource.ts, frontend/src/__mocks__/mockPipelineKF.ts, frontend/src/app/App.scss, frontend/src/components/OdhExploreCard.tsx, frontend/src/concepts/dashboard/DashboardSearchField.tsx, frontend/src/concepts/pipelines/NoPipelineServer.tsx, frontend/src/concepts/pipelines/content/configurePipelinesServer/ObjectStorageSection.tsx, frontend/src/pages/modelServing/screens/global/ModelServingNoProjects.tsx, frontend/src/pages/modelServing/screens/projects/EmptyModelServingPlatform.tsx, frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx
Towards #2209 
Fixes issue numbers 1, 2, and 4 as listed in #2209 cc @DaoDaoNoCode 
Regarding number 3:
> The filter toggle text on Notebook image settings page and global model serving page is truncated
This is part of the larger component deprecation/cleanup effort and will be addressed with the PR for https://github.com/opendatahub-io/odh-dashboard/issues/1931
Tested in UI
1)
Before:
After:
2)
Before:
After:
4) 
Before:
After:
=> PF5: Follow-up UI fixes

backend/package-lock.json, backend/package.json
[RHOAIENG-538](https://issues.redhat.com/browse/RHOAIENG-538)
Upgrading `nodemon` package to  3.0.2 and `semrev` to fix CVE-2022-25883 
Running odh-dashboard on local
No test, just a package upgrade
=> Upgrade semrev to fix CVE-2022-25883

frontend/src/__tests__/integration/pages/pipelines/PipelineRunJobDetails.spec.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/DownloadDropdown.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTabStatus.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/useWindowResize.ts
JIRA: [RHOAIENG-259](https://issues.redhat.com/browse/RHOAIENG-259)
This PR : 
- Prevents downloading empty log files
- Some changes to align with mocks
- Handles small screen "Download" button for pods with a single step 
- Add functionality to view raw logs (part of https://github.com/opendatahub-io/odh-dashboard/issues/1814)
- Code refactor
GIF for raw logs:
https://github.com/opendatahub-io/odh-dashboard/assets/22885912/3bc7459a-b192-4c8a-9185-7064833f3634
Screenshots for view raw logs and disabled and enabled states of both Raw logs and Download button:
Enabled state: 
Disabled: 
Small screen:
1. Run any pipeline
2. Go to the Logs tab
3. Go to any node that has completed execution but has no logs
4. Check that you see "No logs available" and the "Download" button is disabled
Added …
=> Prevent download of empty files in Pipeline Logs

frontend/src/pages/projects/screens/spawner/__tests__/spawnerUtils.spec.ts, frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
closes: https://issues.redhat.com/browse/RHOAIENG-937
check that `opendatahub.io/workbench-image-recommended: 'false'` does not show the recommended label.
_Note: the jupyter tile already does this in the backend, so no need to do anything there._ 
1. edit any imagestream tag's annotation for `opendatahub.io/workbench-image-recommended: 'false'` and verify that in the UI the recommended label is not shown. You can see this when going to the workbench spawner and selecting a version for the image you changed.
added util test to test how different annotation values are handled
=> support workbench-image-recommended annotation being set to false

frontend/src/__mocks__/mockPodK8sResource.ts, frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.spec.ts, frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.stories.tsx, frontend/src/api/k8s/pods.ts, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/__tests__/modelPod.spec.ts, frontend/src/pages/modelServing/screens/global/InferenceServiceStatus.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/global/useModelStatus.ts, frontend/src/pages/modelServing/screens/global/utils.ts, frontend/src/pages/modelServing/screens/types.ts
Closes: #1548  
The status displays an error with  "insufficient resources" messages instead of just loading infinitely
Even displays in the global model serving
1. Deploy a model via model serving using more resources than currently available
2. Wait for its status in the list of deployed models to become either pass or fail
Added
=> Model status will never update if the runtime pod is unschedulable

frontend/src/concepts/trustyai/content/InstallTrustyAICheckbox.tsx, frontend/src/concepts/trustyai/content/TrustyAIServiceControl.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTableRow.tsx, frontend/src/pages/projects/projectSettings/ModelBiasSettingsCard.tsx, frontend/src/pages/projects/projectSettings/ProjectSettingsPage.tsx, frontend/src/pages/projects/projectSettings/const.ts
Closes: [RHOAIENG-248](https://issues.redhat.com//browse/RHOAIENG-248)
Disables model metrics screen access when project is kserve enabled.
- Global modelserving table will not show links to metrics when inference service is kserve based
- 'Models and model servers' table on Project detail page will not show links to model or server metrics when project is kserve enabled.
- Model bias card on Project detail settings page will be disabled and show message (see screenshot) when project is kserve enabled.
- 
With modelmesh enabled on the project:
- Verify all links to model serving screens work as expected.
- Verify Install TrustyAI chackbox on settings tab works as expected
With kserve enabled on the project:
- Verify links to model serving screens are not available
- Verify Install …
=> Disables model metrics screen access when project is kserve enabled (RHOAIENG-248)

frontend/src/__tests__/cypress/cypress/e2e/customServingRuntimes/CustomServingRuntimes.cy.ts, frontend/src/__tests__/cypress/cypress/pages/servingRuntimes.ts, frontend/src/__tests__/integration/pages/customServingRuntimes/CustomServingRuntimes.spec.ts, frontend/src/pages/clusterSettings/ModelServingPlatformSettings.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeHeaderLabels.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimePlatformsLabelGroup.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimePlatformsSelector.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeView.tsx, frontend/src/pages/modelServing/screens/global/EmptyModelServing.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceProject.tsx, frontend/src/pages/modelServing/screens/global/__tests__/InferenceServiceProject.spec.tsx, frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx, frontend/src/pages/modelServing/screens/projects/ModelServingPlatformSelect.tsx, frontend/src/pages/modelServing/screens/projects/utils.ts, frontend/src/pages/projects/components/DeleteModal.tsx
Closes https://issues.redhat.com/browse/RHOAIENG-543
1. Go to the Custom Serving Runtimes section
2. If you have kserve enable, the tag should display "Single-model"
3. If you create a new model, you'll get "Single-model"
4. Now go to Model Serving Global View
5. All the models deployed with modelmesh should display "Single-model"
1. Go to Custom Serving Runtime
2. Create a new Serving Runtime
3. Check that the third option in the dropdown is "Single-model and multi-model serving platforms"
1. Go to Settings > Cluster settings
2. Check the **Model Serving platforms** section
3. It should say `Select the serving platforms that can be used for deploying models on this cluster.`
1. Go to Custom Serving Runtimes
2. The subheader should say: `Manage your model serving runtimes`
1. Create a new …
=> Fix microcopy issues

CONTRIBUTING.md, Makefile
With this change you can call `CONTAINER_BUILDER=docker make build` or rely on your `.env` file instead of editing `Makefile` by hand.
=> feat(make): allows overwriting CONTAINER_ vars

frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.spec.ts, frontend/src/api/k8s/inferenceServices.ts, frontend/src/api/k8s/servingRuntimes.ts, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceNameSection.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx, frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
Closes: #1550 
Added warning and made Deploy button disable when model name exceeds 253 chars.
1. Create project and add a model server.
2. In the Models and model server section click "Deploy model"
3. Enter model name with more than 253 chars and you can see the error mentioned and deploy button disabled.
Integration testing: Added case in Model Serving Global test to check if the model name is no more than 253 chars.
@vconzola
=> Inconsistent behaviour when model name is too long in Model Serving

frontend/src/__tests__/integration/pages/pipelines/PipelineDetails.spec.ts, frontend/src/concepts/pipelines/apiHooks/useAllPipelineVersions.ts, frontend/src/concepts/pipelines/content/pipelineSelector/CustomPipelineVersionSelect.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetailsActions.tsx, frontend/src/concepts/pipelines/content/tables/__tests__/usePipelineFilter.spec.ts, frontend/src/concepts/pipelines/content/tables/columns.ts, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableToolbar.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTable.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTableToolbar.tsx, frontend/src/concepts/pipelines/content/tables/pipelineVersion/PipelineVersionTableRow.tsx, frontend/src/concepts/pipelines/content/tables/usePipelineFilter.ts, frontend/src/pages/pipelines/global/runs/GlobalPipelineRunsTabs.tsx
Closes: [RHOAIENG-267](https://issues.redhat.com/browse/RHOAIENG-267)
- If the page is navigated from the "View run" button on the pipeline details page or pipeline version table action dropdown, then preset the filter to the pipeline version name and filter the runs
- Change the column Pipeline to Pipeline version
- Add the Pipeline version to the filter dropdown
Only manual tests for now.
When this approach is approved, we can proceed with integration tests.
- [] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
=> RHOAIENG-267: Improve pipeline runs table

frontend/src/concepts/pipelines/content/PipelineRunTypeLabel.tsx, frontend/src/concepts/pipelines/content/PipelineVersionLink.tsx, frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts, frontend/src/concepts/pipelines/content/pipelineSelector/CustomPipelineVersionSelect.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/utils.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTableRow.tsx, frontend/src/concepts/pipelines/content/tables/renderUtils.tsx, frontend/src/concepts/pipelines/content/tables/utils.ts
Closes: [RHOAIENG-1451](https://issues.redhat.com/browse/RHOAIENG-1451)
For the pipeline runs table, fetch the pipeline version associated with the runs, and if no pipeline version is returned, that version no longer exists, and we show the name as disabled with a tooltip indicating that the version "no longer exists."
Only regression tested by simply navigating to the pipeline runs table with runs that have pipeline versions that have been deleted, and seeing that on-hover of any disabled text for pipeline versions that a tooltip is shown stating the version no longer exists.
Tests will be written as a follow-up.
=> RHOAIENG-1451: Detect deleted pipeline versions on pipeline runs table, disable, show tooltip

frontend/src/api/k8s/configMaps.ts, frontend/src/api/k8s/notebooks.ts, frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx, frontend/src/pages/projects/screens/spawner/service.ts
closes: https://issues.redhat.com/browse/RHOAIENG-577
Added dry runs to the secrets, configmaps, pvc, and notebook update. We dry run all of them first and if successful, then we return.
_copied from issue_
1. Start to create a Workbench
2. Add two secrets or configmaps (test both)
3. Submit the Workbench
4. Stop the Workbench (just reduces variables, this is not needed)
5. Edit the Workbench
6. Open a new tab and go to the OpenShift Console & locate the Notebook resource
7. Notice that there are two envFrom entires – these are your configmaps/secrets
8. Edit the resource's template spec... modifying one of the resources values seems to work
9. Save the yaml in OpenShift Console
10. Return to the Dashboard UI still mid-edit of that Workbench
11. Remove one of the configmap/secrets
12. …
=> added dry run to workbench update

frontend/src/utilities/__tests__/markdown.spec.ts
Closes: [RHOAIENG-1875 ](https://issues.redhat.com/browse/RHOAIENG-1875)
Unit Test Case for markdown
`npm run test`
=> Unit Test Case for markdown

frontend/src/concepts/pipelines/content/PipelineRunTypeLabel.tsx, frontend/src/concepts/pipelines/content/createRun/RunPage.tsx, frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts, frontend/src/concepts/pipelines/content/import/useImportModalData.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabDetails.tsx, frontend/src/concepts/pipelines/content/tables/renderUtils.tsx, frontend/src/concepts/pipelines/content/tables/utils.ts, frontend/src/concepts/pipelines/context/useJobRelatedInformation.ts
Closes: [RHOAIENG-1748](https://issues.redhat.com/browse/RHOAIENG-1748)
Clicking "Duplicate" was not populating any pre-existing run/job details, specifically pertaining to the pipeline, its input params, and pipeline version.
Tested by navigating to the pipeline `Runs` page, for any given row with an active pipeline version, click the row actions kebab, then "Duplicate" to navigate to what should now be a pre-populated "create run" form.
https://github.com/opendatahub-io/odh-dashboard/assets/96431149/362b11cb-6d84-4c1a-9297-d67fa4701ddd
Only regression tested for now.
=> RHOAIENG-1748: Duplicating runs doesn't auto-fill the pipeline and version selector

frontend/package-lock.json, frontend/package.json, frontend/src/concepts/dashboard/DashboardLogViewer.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawer.scss, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightContent.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightTabs.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/DownloadDropdown.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx
Closes: [RHOAIENG-258](https://issues.redhat.com/browse/RHOAIENG-258)  and [RHOAIENG-1095](https://issues.redhat.com/browse/RHOAIENG-1095) 
This PR aims to change the existing Log viewer to PF Log viewer. Also this PR includes 
1) scroll up to pause feature.
2) Find/search feature in the log viewer toolbar.
3) Support for a full-screen log viewer (expand functionality).
UX Design: https://www.figma.com/proto/rJjOtl3nxpW6BAcl0MZr4y/Pipeline-log-viewer?page-id=62%3A1895&type=design&node-id=1075-5045&viewport=1226%2C-14994%2C0.33&t=BbsTwCedaJMiJaRo-1&scaling=min-zoom&starting-point-node-id=1075%3A5045&show-proto-sidebar=1&mode=design
**Gifs:**
[Screencast from 2024-01-16 22-27-04.webm](https://github.com/opendatahub-io/odh-dashboard/assets/99261071/e91b4805-4c86-4475-be74-85d038658043) …
=> Convert Log Viewer to PF Log Viewer

frontend/src/utilities/__tests__/imageUtils.spec.ts
Closes: [RHOAIENG-1874](https://issues.redhat.com/browse/RHOAIENG-1874)
Unit Test Case for imageUtils.ts
`npm run test`
=> Unit Test Case for imageUtils

frontend/src/concepts/dashboard/DashboardLogViewer.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightContent.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTabStatus.tsx
JIRA: 
[RHOAIENG-254](https://issues.redhat.com/browse/RHOAIENG-254)
[RHOAIENG-255](https://issues.redhat.com/browse/RHOAIENG-255)
500 Internal Error state will be handled by [RHOAIENG-1067](https://issues.redhat.com/browse/RHOAIENG-1067)
1. Adds error messages for failed and cleaned-up pods for Pipeline logs
2. Adds error message in case there is a network issue
3. Hides the Logs toolbar toolbar for such states
Cleaned-up pods(Error message according to this [Slack message](https://redhat-internal.slack.com/archives/C05SMJ09DD2/p1701364992500169?thread_ts=1701266219.319199&cid=C05SMJ09DD2)):
No internet(Error message according to this [Slack message](https://redhat-internal.slack.com/archives/C05SMJ09DD2/p1701364343573709?thread_ts=1701242954.097309&cid=C05SMJ09DD2)):
Failed pod(Error …
=> Improve Pipeline logs error states

backend/src/routes/api/namespaces/namespaceUtils.ts
Followup to https://github.com/opendatahub-io/odh-dashboard/pull/2319
Fixes a bug in the resolution to https://issues.redhat.com/browse/RHOAIENG-548
There was a misunderstanding when verifying #2319: When a model or model server is deployed, not only should an error in updating the namespace prevent a servingruntime from being created, that error should also not happen in the first place for edit-permission users. @lucferbux pointed out that the `resource` field of the `SelfSubjectAccessReview` in `checkEditNamespacePermission` needs to be lowercase for it to check the permission properly.
* As user1, create a project and assign user2 with "edit" permissions.
* As user2, deploy a model in the project.
* Check that there is no error, the serving platform label on the project is applied, …
=> Followup to PR #2319 - permission check typo

backend/src/types.ts, frontend/src/__mocks__/mockServingRuntimeTemplateK8sResource.ts, frontend/src/api/__tests__/inferenceServices.spec.ts, frontend/src/api/__tests__/servingRuntimes.spec.ts, frontend/src/api/k8s/inferenceServices.ts, frontend/src/api/k8s/servingRuntimes.ts, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx, frontend/src/pages/modelServing/screens/projects/utils.ts
Closes https://issues.redhat.com/browse/RHOAIENG-164
1. Create a new Project
2. Select to deploy a kserve model (single model)
3. Change the replica count
4. Deploy the model
5. Now go to the openshift console, to the acutal deployment
6. Check that the number of replicas match the ones selected
Added unit testing for the assenble function
=> Fix the replica count for kserve

frontend/src/pages/modelServing/screens/metrics/utils.tsx
Closes: [RHOAIENG-1743](https://issues.redhat.com//browse/RHOAIENG-1743)
Updates the prometheus query for the "Average response time" server metrics chart. Previously the chart displayed multiple lines, representing each model running on the server (see before / after pics below). Following the PM signoff it was requested that the chart be one single line representing the whole model server - this PR implements this.
*BEFORE*
*AFTER*
* Run locally against a server with models running and performance data pre-seeded.
* Verify the Average response time chart, shows a single area.
* Does not reduce existing test coverage
- Skipped, the server is required for a customer demo tomorrow, …
=> Improves query for Average Response Time charts, so it is only a single area.

frontend/src/__mocks__/mockAcceleratorProfile.ts, frontend/src/pages/notebookController/screens/server/__tests__/useAcceleratorProfiles.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-1946
unit test for use frontend/src/pages/notebookController/screens/server/useAcceleratorProfiles.ts
npm run test
coverage
=> added test for  useAcceleratorProfiles

frontend/src/concepts/pipelines/content/createRun/RunForm.tsx, frontend/src/concepts/pipelines/content/createRun/contentSections/PipelineVersionSection.tsx, frontend/src/concepts/pipelines/content/import/ImportPipelineVersionButton.tsx, frontend/src/concepts/pipelines/content/import/PipelineVersionImportModal.tsx, frontend/src/concepts/pipelines/content/import/useImportModalData.ts, frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableExpandedRow.tsx
JIRA: https://issues.redhat.com/browse/RHOAIENG-1123
It's just a small fix, expose the selection of the pipeline when uploading a pipeline version, so the pipeline selector can get that value and set it.
1. Go to the create run page with all the fields empty
2. Click `Upload new version` button on that pipeline
3. Select a pipeline and upload a version
4. Verify both pipeline and version selectors are auto-filled
5. Now click on `Upload new version` button again, it should auto-fill the pipeline selector in the modal too
6. Change the selection
7. Upload a new version for that different pipeline
8. Verify both pipeline and version selector are changed to the version you just uploaded
N/A …
=> Fix issue when uploading a version on create pipeline run page

frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelServingGlobal.cy.ts, frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/pages/ApplicationsPage.tsx, frontend/src/pages/modelServing/ModelServingContext.tsx, frontend/src/pages/modelServing/screens/global/ModelServingGlobal.tsx, frontend/src/pages/modelServing/screens/global/ModelServingLoading.tsx, frontend/src/pages/modelServing/useInferenceServices.ts, frontend/src/pages/modelServing/useServingRuntimes.ts
Closes https://issues.redhat.com/browse/RHOAIENG-549
1. Open the network tab on Chrome
2. Go to Model Serving Global
3. Select `"All projects"`
4. Check that it's listing `InferenceServices` and `Servingruntimes` are being listed as cluster wide fetches
1. Open the network tab on Chrome
2. Go to Model Serving Global
3. Select `"All projects"`
4. Check that it first requests all projects and then it does several calls to fecth all `InferenceServices` and `ServingRuntimes` in those projects
1. Go to Model Serving Global
2. Select `"All projects"`
3. Check that you can cancel the request
Added e2e tests
=> Fix performance issues in Model Serving Global

frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelMetrics.cy.ts, frontend/src/api/models/trustyai.ts
[WIP] Testing on a cluster in progress
Closes: [RHOAIENG-346](https://issues.redhat.com//browse/RHOAIENG-346)
Updates the apiVersion of the TrustyAI CRD to  `trustyai.opendatahub.io` to match a last minute update on the backend.
1. Deploy TrustyAI using these devflags:
```
trustyai:
devFlags:
manifests:
- contextDir: config
sourcePath: ''
uri: >-
https://github.com/ruivieira/trustyai-service-operator/tarball/issue-168-apiversion-ui-test
managementState: Managed
```
2. Deploy dashboard image from this PR.
3. Enable TrustyAI on a project through the dashboard, verify the service is correctly installed.
Small change, existing tests updated, no drop in coverage.
=> [RHOAIENG-246] Updated TrustyAIKind apiVersion to trustyai.opendatahub.io

frontend/src/__tests__/cypress/cypress/e2e/applications/explore.cy.ts, frontend/src/components/SupportedAppTitle.tsx
Closes: [RHOAIENG-2041](https://issues.redhat.com/browse/RHOAIENG-2041)
Changed the functionality of how we fetch the displayName of the OdhApplication CR. Card titles are visible now.
Run dashboard with check enabled page, card title should be visible.
Added cypress test to check card title
=> 'Jupyter ' text is missing for Notebook tile in RHOAI Enabled/Explore tab

frontend/src/__mocks__/mockSecretK8sResource.ts, frontend/src/concepts/pipelines/elyra/__tests__/useElyraSecret.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-1967
added test for frontend/src/concepts/pipelines/elyra/useElyraSecret.ts
npm run test
test coverage
=> added test case for useElyraSecret

frontend/src/pages/modelServing/__tests__/useInferenceServices.spec.ts
Closes: [RHOAIENG-1852](https://issues.redhat.com/browse/RHOAIENG-1852)
Unit test case for: frontend/src/pages/modelServing/useInferenceServices.ts
`npm run test`
=> Unit Test Case for useInferenceServices

frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTableRow.tsx
Fixes: https://issues.redhat.com/browse/RHOAIENG-2083
Intermittent failures occur when running cypress tests. It was reported that a button exists with no name. Upon investigation it was found that the expand button of the model serving table will display a PF `Skeleton` inside a button without any text while data is loading. This is an accessibility violation because all buttons must have a name.
The fix is to not render the expand button while data is being loaded (we still render the `Skeleton`). Once data is loaded, the `Skeleton` is no longer rendered and a number is rendered in place. The expand button then becomes active to expand the row.
Ran cypress tests locally several times.
To observe the change:
- Create a project.
- On the project details page, create a model server.
- …
=> fix intermittent a11y cypress tests in PR checks

frontend/src/utilities/__tests__/useDeepCompareMemoize.spec.ts
Closes: [RHOAIENG-2091](https://issues.redhat.com/browse/RHOAIENG-2091)
Unit Test Case for useDeepCompareMemoize
`npm run test`
=> Unit Test Case for useDeepCompareMemoize

frontend/src/utilities/__tests__/clusterUtils.spec.ts
Closes: [RHOAIENG-1897](https://issues.redhat.com/browse/RHOAIENG-1897)
Unit Test Case for clusterUtils
`npm run test`
=> Unit Test Case for clusterUtils

backend/src/routes/api/k8s/pass-through.ts, backend/src/routes/api/proxy/index.ts, backend/src/utils/fileUtils.ts, frontend/.eslintrc, frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsCodeBlock.tsx, frontend/src/utilities/allSettledPromises.ts
Closes: [RHOAIENG-508](https://issues.redhat.com/browse/RHOAIENG-508)
This PR aims to apply no-base-to-string rule to both frontend and backend. 
Run `npm run test`
=> Add no-base-to-string rule to both frontend and backend

frontend/src/api/k8s/__tests__/acceleratorProfiles.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-2004
added unit test case for frontend/src/api/k8s/acceleratorProfiles.ts
npm run test
test coverage: 
=> added test for accelerator Profile api

frontend/src/utilities/__tests__/useEventListener.spec.ts
Closes: [RHOAIENG-2141](https://issues.redhat.com/browse/RHOAIENG-2141)
Unit Test Case for useEventListener
`npm run test`
=> Unit Test Case for useEventListener

frontend/src/pages/modelServing/screens/metrics/utils.tsx
Closes: [RHOAIENG-535](https://issues.redhat.com//browse/RHOAIENG-535)
Fixes an issue where metrics stack charts - specifically the Model performance http requests chart would break when there was no data for a given line. See before and after screenshots for comparison.
Before:
After:
1. Navigate to the endpoint performance metric chart for a model that has no data.
2. Verify the graph does not look like the before screenshot, but instead looks like the after screenshot -- tooltip displays success 0, failed 0 and the plotted line runs along the x axis at 0.
We currently don't have test coverage to validate what the chart looks like therefore it's not being added in this issue.
=> Fixes stack charts broken when no datapoints available for one or more lines (RHOAIENG-535)

frontend/src/utilities/__tests__/useWatchSegmentKey.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-2110
Added test for frontend/src/utilities/useWatchSegmentKey.tsx
npm run test
test coverage :
=> added test for useWatchSegmentKey

frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelinesGlobal.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/index.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineImportModal.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineVersionImportModal.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesGlobal.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesTable.ts, frontend/src/concepts/pipelines/content/import/PipelineImportModal.tsx
Closes: [RHOAIENG-2213](https://issues.redhat.com/browse/RHOAIENG-2213)
Test ability to upload a new pipeline version from the pipelines global page.
Terminal 1: 
`npm run cypress:server:build`
`npm run cypress:server:dev`
Terminal 2:
`npm run cypress:run:mock` or `npm run cypress:open:mock`
=> [RHOAIENG-2213] FT: Pipelines global - upload a new pipeline version

frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineRunsGlobal.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/index.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunJobTable.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunTable.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunsGlobal.ts, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTable.tsx, frontend/src/pages/ApplicationsPage.tsx, frontend/src/pages/pipelines/global/pipelines/GlobalPipelines.tsx, frontend/src/pages/pipelines/global/runs/GlobalPipelineRuns.tsx, frontend/src/pages/pipelines/global/runs/GlobalPipelineRunsTabs.tsx
Initial page objects for the global runs page and supporting tables. Only a placeholder test was written for now. Opening this to avoid too many conflicts with others writing tests for other functionality on the page.
=> [RHOAIENG-1124] Initial pipeline runs global page test setup

frontend/src/__mocks__/mock409Error.ts, frontend/src/__mocks__/mockRoleBindingK8sResource.ts, frontend/src/__mocks__/mockServiceAccountK8sResource.ts, frontend/src/__tests__/cypress/cypress/e2e/modelServing/ServingRuntimeList.cy.ts, frontend/src/pages/modelServing/__tests__/utils.spec.ts, frontend/src/pages/modelServing/screens/projects/utils.ts, frontend/src/pages/modelServing/utils.ts
Resolves https://issues.redhat.com/browse/RHOAIENG-554
When deploying a model, there is a "Require token authentication" checkbox:
If and only if this box is checked (`servingRuntimeData.tokenAuth` is true), a ServiceAccount and RoleBinding should be created. Currently, the ServiceAccount is created even if the box is not checked. Also, the ServiceAccount creation is attempted even if a ServiceAccount of the same name already exists.
This fix ensures that the ServiceAccount and RoleBinding will only be created if the token auth box is checked AND each of them do not already exist.
Reproduced the bug on the kserve-pm cluster by creating a model server with the auth checkbox unchecked and observing that the ServiceAccount still gets created. Then tested on the same cluster with my changes …
=> When creating ServingRuntime, only create ServiceAccount if it's missing and token auth is selected

frontend/package.json, frontend/src/__tests__/cypress/cypress.config.ts, frontend/src/__tests__/cypress/cypress/support/commands/index.ts, frontend/src/__tests__/cypress/cypress/support/commands/k8s.ts, frontend/src/__tests__/cypress/cypress/support/e2e.ts, frontend/src/__tests__/cypress/cypress/support/websockets.ts, frontend/src/__tests__/cypress/cypress/utils/k8s.ts, frontend/src/utilities/const.ts
Fixes: https://issues.redhat.com/browse/RHOAIENG-836
This change adds support to send updates through websockets to the frontend.
Requires a change to the frontend to accept overriding the websocket connection. The cypress scripts in the `package.json` override `WS_HOSTNAME`. By default we continue to use `localhost.host` as a fallback.
Added three new cypress commands:
- `wsSend`: Generic command to send arbitrary data through websockets.
- `wsK8sDeleted`: Send a web socket K8s resource deleted message.
- `wsK8sAdded`: Send a web socket K8s resource add message.
- `wsK8sModified`: Send a web socket K8s resource modified message.
Example usage:
`cy.wsK8sAdded(ProjectModel, {... k8s resource ...);`
Replaced project polling with websockets locally.
Created a sample test case updating the …
=> add support for cypress websockets

frontend/src/__mocks__/mockEdgePipelineRun.ts, frontend/src/concepts/edge/content/models/utils.ts
Changes the Edge Pipelinerun to use a volumeClaimTemplate instead of relying on a pre-existing PVC for mounting persistent storage to the Pipeline workspace
*DEMO* Dev build and deploy of the odh-dashboard container image in a cluster to verify the change
=> [Edge] Use volumeClaimTemplate for PipelineRuns

frontend/src/concepts/secrets/apiHooks/useAWSSecret.ts
https://issues.redhat.com/browse/RHOAIENG-2321
When the DSP Server got a rework, it no longer used Data Connections as a source for the secret name. The elyra secret was crafted using a Data Connection structure, it required the secret to be named the same thing as a data connection. That was not done, so we ended up with a fail to create the `ds-pipeline-config` secret that was attached to Notebooks for Elyra to work.
The fix is basically to change the rules to what is an AWS secret, instead of the name, it's the key and secret values. This still will present a limitation in manually crafted DSPAs, but this is a blocker for 2.6 RHOAI, so the solution is intentionally small.
2. Create a DSP Server
3. See the `ds-pipeline-config` secret was created after
None
Self …
=> [RHOAIENG-2321] Fix Elyra Secret for new DSP Server Modal

frontend/src/api/k8s/__tests__/dashboardConfig.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-2118
Added test case for frontend/api/k8s/dashboardConfig file
npm run test
test coverage : 
=> added test case for dashboardConfig

frontend/src/__mocks__/mockDataSciencePipelinesApplicationK8sResource.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/GlobalPipelines.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineCreateRuns.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineDeleteRuns.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/Pipelines.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelinesTopology.cy.ts, frontend/src/api/pipelines/k8s.ts, frontend/src/concepts/pipelines/const.ts, frontend/src/concepts/pipelines/content/DeletePipelineServerModal.tsx, frontend/src/concepts/pipelines/context/PipelinesContext.tsx, frontend/src/concepts/pipelines/context/usePipelineNamespaceCR.ts, frontend/src/concepts/pipelines/context/usePipelinesAPIRoute.ts, frontend/src/concepts/pipelines/elyra/const.ts, frontend/src/concepts/pipelines/utils.ts
closes: https://issues.redhat.com/browse/RHOAIENG-945
- name  for new dspa is now `dspa-def`
- we now  fetch the list of dspa resources and get the first one. Empty list returns null
- adjusted get cr and delete cr to accept a name and also storing cr name in the pipelines API
create a pipelines server, make sure it uses new name
test that it grabs the dspa correctly
I understand there will possible issues where a user incorrectly has multiple dspas in their project. We will grab the first one so deletion will act funny, and if the add a new one that ends up at the top of the list, then their will be weird issues too. The frontend already prevents users from making multiple, but the backend team needs to also prevent this on their end.
Make sure all old test pass and grab the dspa
Self …
=> dspa is not name specific anymore

frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightTabs.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/DownloadDropdown.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTabStatus.tsx, frontend/src/pages/projects/screens/detail/pipelines/PipelinesList.tsx
Fixes [RHOAIENG-2105](https://issues.redhat.com/browse/RHOAIENG-2105)
Fixing a11y issues with Pipeline logs section flagged by [axe Devtools](https://chromewebstore.google.com/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd)
1. `DownloadDropdown` button lacked an `aria-label`, Logs alert lacked a `component` prop
1. Add [axe Devtools](https://chromewebstore.google.com/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd) Chrome extension to your Chrome browser
2. Once you have Pipeline logs page open(Click on any node on any pipeline run), open Developer Tools and look for the "axe Devtools" tab, and Click on "Scan ALL of my page".
4. Do the same after clicking on the "View raw logs" from the kebab menu on the extreme right of the `LogViewer` toolbar.
Will …
=> Fix a11y issues with Pipeline logs

frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightTabs.tsx
As described in the second point attached in the doc here: https://issues.redhat.com/browse/RHOAIENG-2328
Fix resize issue of LogViewer
https://github.com/opendatahub-io/odh-dashboard/assets/22885912/a28be52e-70f7-486e-8ae5-9f1706000180
1. Try spending the alert with the changes => the LogViewer shouldn't flow out of viewport when you're on the Log tab
To be added in a later PR
=> Fix LogViewer resize issue

frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelServingGlobal.cy.ts, frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionFolderPathField.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx, frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx, frontend/src/pages/modelServing/screens/projects/utils.ts, frontend/src/utilities/__tests__/string.spec.ts, frontend/src/utilities/string.ts
[RHOAIENG-542](https://issues.redhat.com/browse/RHOAIENG-542)
Removes the leading slash `/` single or multiple and throws error msg for invalid path
[Screencast from 2024-01-30 14-49-34.webm](https://github.com/opendatahub-io/odh-dashboard/assets/97534722/32451a96-cf75-407c-a12d-b38f0e85ab80)
Invalid path
Error when only slash `/` in path 
1. Deploy new model KServe or Multi model
2. Enter path name starting with '/'
3. Edit the model created, you can see the '/' removed from path.
Added unit test for utility function.
@vconzola
=> Inconsistent Model Path

frontend/src/api/__tests__/k8sUtils.spec.ts
Closes: [RHOAIENG-2153](https://issues.redhat.com/browse/RHOAIENG-2153)
This PR aims to update unit test case for: frontend/src/api/k8sUtils.ts
`npm run test`
Previous coverage:
updated coverage:
=> Update unit test case for api/k8sUtils file

backend/src/routes/api/k8s/index.ts, backend/src/routes/api/k8s/pass-through.ts
Shifting logic to the proper owner.
/cc @DaoDaoNoCode @christianvogt
=> Fix ownership of parsing proxyCall() for passThroughText

frontend/src/pages/modelServing/screens/metrics/utils.tsx
Closes: [RHOAIENG-2620](https://issues.redhat.com//browse/RHOAIENG-2620)
Fixes a bug where a user could not duplicate a bias metric request unless they cleared and changed certain fields.
Note: this is a minimal fix to a regression. A flaw in the dashboard's type definitions for TrustyAI have been discovered, which are not addressed in this PR.
1. Create a bias metric configuration
2. Attempt to "duplicate" it, leave all the values as they are presented in the form
3. Click Configure
Validate the new configuration is created successfully.
As this is the smallest possible fix to restore functionality, it doesn't make sense to alter the tests at this stage. Fixing our types in the future will ensure the existing test coverage provides us with adequate cover. …
=> Fixes an issue where users are unable to create duplicate bias metric requests

frontend/src/api/k8s/__tests__/servingRuntimes.spec.ts
Closes:  [RHOAIENG-2151](https://issues.redhat.com/browse/RHOAIENG-2151)
This PR aims to update unit test case for: frontend/src/api/servingRuntimes.ts
`npm run test`
Coverage:
before:
After:
=> Update unit test case for servingRuntimes file

frontend/src/api/prometheus/serving.ts, frontend/src/api/prometheus/usePrometheusQueryRange.ts, frontend/src/api/prometheus/useQueryRangeResourceData.ts, frontend/src/utilities/useRestructureContextResourceData.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-2805
FYI @alexcreasy 
Fixes the intermitted "spikes" which occur in the model metrics stacked chart.
Cause:
Two separate queries are issued for `successes` and `failures`. The chart sometimes updates in between query responses which causes the data set for each query to be slightly off in time. When this happens, the data points no longer stack exactly on top of each other. The spikes occur because the `failures` have data points typically of `0` or `1`; much lower than the data points of the `successes`.
Fix:
Sync data return from the context such that new data is only returned when all pending queries have finalized.
Using a demo project setup by @alexcreasy 
Set refresh interval to the lowest number.
Set the range equal to 1 hour.
Prior …
=> sync query data by waiting on all pending queries

frontend/src/__mocks__/mockDataSciencePipelinesApplicationK8sResource.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelinesList.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesSection.ts, frontend/src/concepts/pipelines/content/import/ImportPipelineSplitButton.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineServerActions.tsx, frontend/src/pages/projects/screens/detail/DetailsSection.tsx, frontend/src/pages/projects/screens/detail/pipelines/PipelinesSection.tsx
JIRA: https://issues.redhat.com/browse/RHOAIENG-2570
Replace the import pipeline button with the split button, which allows both importing pipelines and uploading a pipeline version.
It's disabled when no server is configured:
After the server is configured, if there is no pipeline, only the upload version button is disabled with a tooltip:
When you have pipelines, everything is enabled:
1. Create a project and get to the details page
2. Make sure the button is disabled
3. Configure a pipeline server
4. Make sure the button is enabled when there is a default pipeline
5. Delete the default pipeline
6. Make sure the upload version button is disabled
Add some tests to verify the disabled status for the split button
After the …
=> Allow uploading pipeline versions on project details page

frontend/src/app/App.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-2935
As shown in the `Before` screenshot, the call to `/api/dsc/status` comes only after the other calls to `status`, `builds`, `config`. While in the `After` all request are run in parallel
Before:
After:
_Note that the total request time differs in before and after because the before was taken from a prod install while the after was from a local dev environment._
Locally running app and tests.
Test if app continues to load.
=> render AreaContextProvider higher in the tree to run network call in parallel

frontend/src/api/pipelines/__tests__/k8s.spec.ts
Fixes a linting error for the `@typescript-eslint/dot-notation` rule.
`npm run test:lint` in frontend
=> fix lint error requiring dot notation

backend/src/routes/api/namespaces/index.ts, backend/src/routes/api/namespaces/namespaceUtils.ts, frontend/src/__tests__/cypress/cypress/e2e/modelServing/ServingRuntimeList.cy.ts, frontend/src/api/k8s/__tests__/inferenceServices.spec.ts, frontend/src/api/k8s/__tests__/projects.spec.ts, frontend/src/api/k8s/inferenceServices.ts, frontend/src/api/k8s/projects.ts, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx, frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx, frontend/src/pages/modelServing/screens/projects/utils.ts
Closes: [RHOAIENG-556](https://issues.redhat.com/browse/RHOAIENG-556)
In progress to https://github.com/opendatahub-io/odh-dashboard/pull/2319, this PR improves the functionality to dry run ServingRuntime and InferenceService before creating the KServe model.
Create a KServe modal and check the network logs to find dryRun API executed first.
=> Properly dry-run all operations in KServe modal before submitting

manifests/modelserving/caikit-ootb.yaml
Add liveness/readiness probes and env variables
Related to:
- https://github.com/opendatahub-io/caikit-tgis-serving/pull/205
- https://github.com/opendatahub-io/caikit-tgis-serving/pull/186
Manifest has been deployed in a fresh cluster with a fresh kserve install: https://github.com/opendatahub-io/caikit-tgis-serving/pull/220
=> Add Readiness/Liveness probes to caikit-ootb

frontend/package-lock.json, frontend/package.json
Closes: [RHOAIENG-2855](https://issues.redhat.com/browse/RHOAIENG-2855)
Updated the dev dependency `copy-webpack-plugin` to version 12.0.2, thereby ensuring compatibility with `serialize-javascript` version 6.0.2 across the project.
1. cd /frontend
2. npm list serialize-javascript 
and you can observe the utilization of the `serialize-javascript` across all instances.
```
odh-dashboard-frontend@0.1.0 /home/dipanshu/Documents/odh/odh-dashboard/frontend
├─┬ copy-webpack-plugin@12.0.2
│ └── serialize-javascript@6.0.2
├─┬ css-minimizer-webpack-plugin@4.2.2
│ └── serialize-javascript@6.0.2 deduped
└─┬ terser-webpack-plugin@5.3.9
└── serialize-javascript@6.0.2 deduped
```
Just a package update no test required. …
=> Synk severity issue with serialize-javascript

frontend/src/__tests__/cypress/cypress/e2e/notebookImageSettings/NotebookImageSettings.cy.ts, frontend/src/__tests__/cypress/cypress/pages/notebookImageSettings.ts, frontend/src/pages/BYONImages/BYONImages.tsx, frontend/src/pages/clusterSettings/ClusterSettings.tsx, frontend/src/utilities/NavData.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-1194
Closes: https://issues.redhat.com/browse/RHOAIENG-1195
Content updates to Cluster settings subheader and Notebook image settings renamed to "Custom notebook images"
1. As a `clusteradminuser` go to `Settings` in the left navbar, you should see `Custom notebook images` instead of `Notebook image settings` and the same applies to the title of the page.
Fixed tests impacted by this change
=> Content update for cluster settings and notebook image settings

frontend/src/__tests__/cypress/cypress/e2e/pipelines/Pipelines.cy.ts, frontend/src/concepts/pipelines/content/tables/columns.ts, frontend/src/concepts/pipelines/content/tables/pipelineVersion/PipelineVersionTable.tsx, frontend/src/concepts/pipelines/content/tables/pipelineVersion/PipelineVersionTableRow.tsx
JIRA: https://issues.redhat.com/browse/RHOAIENG-2644
Added a kebab toggle to the pipeline version row to replace the previous `View runs` button. In the dropdown menu, user could create a run using the version, view all runs from that version, or delete the single version.
1. Go to global pipelines table
2. Expand the pipeline row, check the version table, make sure the pipeline version row has the kebab toggle
3. Check the buttons in the dropdown menu, make sure they works (e.g. You can delete a single version. You can also click on `Create run`, which can take you to the create run page with pipeline and version prefilled...)
Add a cypress test to delete a single version using the dropdown menu on the version table row. …
=> Add kebab toggle to the pipeline version row

frontend/.eslintrc, frontend/src/concepts/pipelines/content/DeletePipelineRunsModal.tsx, frontend/src/concepts/pipelines/content/DeletePipelinesModal.tsx, frontend/src/concepts/pipelines/utils.ts, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/DeleteServingRuntimeModal.tsx, frontend/src/utilities/allSettledPromises.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-1295
added eslint to restrict using Promise.allSetttled
npm run test
=> added eslint rules for allSettledPromises

frontend/src/__mocks__/mockInferenceServiceK8sResource.ts, frontend/src/__tests__/cypress/cypress/e2e/modelServing/ServingRuntimeList.cy.ts, frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/pages/modelServing/screens/global/InferenceServiceStatus.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx, frontend/src/pages/modelServing/screens/global/utils.ts, frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTable.tsx
Closes: [RHOAIENG-2627](https://issues.redhat.com/browse/RHOAIENG-2627)
Improved the functionality to display model error status. 
Now the user can see error message properly listed under `lastFailureInfo.message` in InferenceService CR.
Deploy a model with wrong AWS credentials and check it's status, error message should be proper and informative. 
Added cypress test to check error message.
=> Model deploy error is not informative

manifests/base/deployment.yaml
Closes https://issues.redhat.com/browse/RHOAIENG-3410
Add support for dashboard self signed cert.
Tested following the instructions on https://github.com/opendatahub-io/odh-model-controller/pull/166.
I had to manually generate the `odh-trusted-ca-bundle` in the default namespace and I used:
```
dashboard:
devFlags:
manifests:
- contextDir: manifests
sourcePath: ''
uri: 'https://github.com/lucferbux/odh-dashboard/tarball/rhoaieng-2380'
managementState: Managed
```
For the dsc to get the changes.
No need for test coverage, infra changes
=> Add support for cluster wide self signed cert

frontend/src/utilities/__tests__/time.spec.ts
Closes: [RHOAIENG-2673](https://issues.redhat.com/browse/RHOAIENG-2673)
Updated unit test case for frontend/src/utilities/time.ts
`npm run test`
Coverage:
Before:
After:
=> Unit Test Update for utilities/time

frontend/src/utilities/__tests__/string.spec.ts
Closes: [RHOAIENG-2677](https://issues.redhat.com/browse/RHOAIENG-2677)
Updated unit test case for frontend/src/utilities/string.ts
`npm run test`
Coverage:
Before:
After:
=> Unit Test Update for utilities/string

frontend/src/__tests__/unit/testUtils/hooks.spec.ts, frontend/src/__tests__/unit/testUtils/hooks.ts
Hook stability comparison utility, `createComparativeValue`, used `expect.arrayContaining()` internally when constructing the array comparators. The issue with using `expect.arrayContaining()` is that it doesn't take into consideration the order of elements. This error becomes apparent when asserting `[true, false]` is comparatively equal to `[false, true]` passed when it would be expected to fail.
The fix here is to not rely on `expect.arrayContaining()` when creating array comparators and instead always create an array equal to the size of the expected array and then fill each value with a custom comparator equal to any value when the value is irrelevant or a nested comparator such as the `expect.isIdentityEqual` comparator.
Also, `expect.anything()` doesn't match `null` or `undefined`. …
=> fix hook array stability comparison

frontend/src/__tests__/cypress/cypress/e2e/modelServing/ServingRuntimeList.cy.ts, frontend/src/pages/modelServing/screens/projects/utils.ts
Closes: [RHOAIENG-3312](https://issues.redhat.com/browse/RHOAIENG-3312)
Dry run Data connection secret when inferenceService is running on dry run
Deploy new model with new data connection. 
Added cypress test to check dry run of Data connection secret.
=> Error when creating new data connection in InferenceService

frontend/src/pages/exploreApplication/DrawerContentBody.scss, frontend/src/pages/exploreApplication/ExploreApplications.scss, frontend/src/pages/exploreApplication/ExploreApplications.tsx
Fixes https://issues.redhat.com/browse/RHOAIENG-3773
PF selectable cards has are not functional in website v122.
PF has introduced a fix and this change applies that fix while waiting to adopt the latest PF release.
_note commits need to be squashed_
Navigate to the explore page and click the Jupiter tile.
Existing cypress tests were failing with chrome v122. This change should see that test pass.
=> make explore card clickable with PF work around

frontend/src/__tests__/cypress/cypress.config.ts, frontend/src/__tests__/cypress/cypress/e2e/applications/explore.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineCreateRuns.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineRuns.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/Pipelines.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/archiveRunModal.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/createRunPage.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/index.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunTable.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunsGlobal.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesGlobal.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesTable.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/restoreRunModal.ts, frontend/src/concepts/pipelines/content/DeletePipelineRunsModal.tsx, frontend/src/concepts/pipelines/content/createRun/CloneRunPage.tsx, frontend/src/concepts/pipelines/content/createRun/CreateRunPage.tsx, frontend/src/concepts/pipelines/content/createRun/RunPageFooter.tsx, frontend/src/concepts/pipelines/content/createRun/types.ts, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTableToolbar.tsx, frontend/src/pages/pipelines/global/runs/ArchiveRunModal.tsx, frontend/src/pages/pipelines/global/runs/BulkArchiveRunModal.tsx, frontend/src/pages/pipelines/global/runs/ScheduledRuns.tsx, frontend/src/pages/projects/components/DeleteModal.tsx
Closes: [RHOAIENG-3886](https://issues.redhat.com/browse/RHOAIENG-3886)
Starts: [RHOAIENG-3887](https://issues.redhat.com/browse/RHOAIENG-3887)
Test scenarios covered from Active & Archived run list pages:
- single Restore
- multiple Restore
- single Archive
- multiple Archive
Also includes:
- Fix for `explore.cy.ts` test that is unrelated and not owned by our scrum team, but is impeding on CI builds.
- A simple name change of `Create Schedule` -> `Schedule run`, which is a part of [RHOAIENG-3887](https://issues.redhat.com//browse/RHOAIENG-3887), but only captures a small amount that still could change more as a part of that ticket which is not yet fully vetted.
Cypress tests, regression tests
=> Cypress tests: Runs - Restore & Archive

frontend/src/api/pipelines/__tests__/errorUtils.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-2166
added unit test for frontend/src/api/pipelines/errorUtils.ts
npm run test
=> added unit test for errorUtils file

frontend/src/__mocks__/mockProjectK8sResource.ts, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ManageInferenceServiceModal.spec.tsx
Closes https://issues.redhat.com/browse/RHOAIENG-2724
Fix an issue regarding states of the model server dropdown being restored on each project polling
1. Go to model serving global
2. Select a modelmesh project
3. Click on deploy new model
4. Select a model server
5. Wait around 15 seconds
6. The selection should not disappear
=> Fix an issue with the model server dropdown state

frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ManageInferenceServiceModal.spec.tsx, manifests/overlays/apps/base/rhoai/kustomization.yaml, manifests/overlays/apps/base/rhoai/rhoai-docs.yaml
Closes https://issues.redhat.com/browse/RHOAIENG-532
Adding a dashboard tile for the "OpenShift AI tutorial - Fraud detection example" guide.
1. Deploy all the rhoai documentation with `oc apply -k manifests/overlays/apps/base/rhoai`
2. Check that there's a new doc in the resources section
No testing required, new resource added, no changes in the codebase
=> Add e2e tutorial for fraud detection

frontend/src/__mocks__/mockServingRuntimeK8sResource.ts, frontend/src/__mocks__/mockServingRuntimeTemplateK8sResource.ts, frontend/src/__tests__/cypress/cypress/e2e/customServingRuntimes/CustomServingRuntimes.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/modelServing/ServingRuntimeList.cy.ts, frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/__tests__/cypress/cypress/pages/servingRuntimes.ts, frontend/src/api/k8s/__tests__/templates.spec.ts, frontend/src/api/k8s/templates.ts, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAPIProtocolLabel.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAPIProtocolSelector.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAddTemplate.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimePlatformsLabelGroup.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimePlatformsSelector.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeTableRow.tsx, frontend/src/pages/modelServing/customServingRuntimes/templatedData.tsx, frontend/src/pages/modelServing/customServingRuntimes/utils.ts, frontend/src/pages/modelServing/screens/global/InferenceServiceAPIProtocol.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/global/data.ts, frontend/src/services/templateService.ts, frontend/src/types.ts, manifests/modelserving/caikit-ootb.yaml, manifests/modelserving/ovms-kserve-ootd.yaml, manifests/modelserving/ovms-ootb.yaml, manifests/modelserving/tgis-ootb.yaml
Closes: [RHOAIENG-560](https://issues.redhat.com/browse/RHOAIENG-560) [RHOAIENG-3875](https://issues.redhat.com/browse/RHOAIENG-3875)
Enable GRPC support for model serving routes
<details>
<summary>
Custom serving runtime list
</summary>
</details>
<details>
<summary>
Add custom serving runtime
</summary>
</details>
<details>
<summary>
Project KServe list
</summary>
</details>
<details>
<summary>
Project Multi-model list
</summary>
</details>
<details>
<summary>
Global model serving
</summary>
</details>
Custom Serving Runtimes Page:
1. Navigate to Settings > Serving Runtimes.
2. Click "Add Serving Runtime."
3. Choose "Multi Model" and observe REST as the default API protocol (disabled).
4. Toggle to "Single Model" or both, enabling the API protocol dropdown.
5. Select either HTTP or …
=> Enable GRPC support for model serving routes

manifests/modelserving/ovms-kserve-ootd.yaml, manifests/overlays/modelserving/kustomization.yaml
Closes: https://issues.redhat.com/browse/RHOAIENG-3469 --> addressed by update SHAs for RHOAI. OVMS ODH images will not be updated for now.
https://issues.redhat.com/browse/RHOAIENG-3355 --> addressed by the `--target_device=AUTO` line in the template
Partially closes: https://issues.redhat.com/browse/RHOAIENG-3052 --> addressed by the `--enable_metrics` line in the template
Partially addresses: https://issues.redhat.com/browse/RHOAIENG-3134 --> updating openvino_ir format to latest and adding now newly supported pytorch format
I tested this manually on a ROSA-hosted cluster. New image is working well. And all additional args are verified. Comments have been added in the relevant JIRAs with details.
After the PR is posted & …
=> Update OVMS images and template

frontend/src/concepts/pipelines/content/configurePipelinesServer/ConfigurePipelinesServerModal.tsx, frontend/src/concepts/pipelines/content/configurePipelinesServer/utils.ts
JIRA: https://issues.redhat.com/browse/RHOAIENG-2317
Trim all the fields of ObjectStorage when configuring a pipeline server to make sure the DSPA and secret creation is correct.
1. Configure a pipeline server, input some spaces before and after all the field inputs
2. Configure the server
3. View the server configuration, make sure all the fields are correct and without the spaces at the beginning and end.
N/A
=> Trim field input when configuring pipeline server

frontend/src/app/AppLauncher.tsx
Closes: [RHOAIENG-4230](https://issues.redhat.com/browse/RHOAIENG-4230)
Clicking the application launcher crashes the UI. Update the code to ensure no null-ish items are in the launcher drop down items.
Click the application launcher
None
=> Fix for application launcher crash

manifests/overlays/apps/base/watson/watson-docs.yaml
Closes: #[RHOAIENG-1150](https://issues.redhat.com//browse/RHOAIENG-1150)
One of the tutorial in the Dashboard > Resources page has a typo in the title: **Buildng** a binary classification model
=> fix(resource): RHOAIENG-1150, fix typo in tutorial

frontend/src/SDKInitialize.tsx, frontend/src/__tests__/cypress/cypress/support/commands/intercept-snapshots.ts, frontend/src/components/error/ErrorDetails.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-2952
Removes the 1second delay that was arbitrarily added to work around an issue in the dynamic plugin SDK. Not the check is run immediately and the delay is reduced to 100ms. In testing, waiting for the effect to run is sufficient but kept the delay because of the async nature of the problem to be safe.
Cypress test execution time locally has also been reduce:
Before: `5m36s`
After: `3m25s`
It seems like the SDK also at one point was holding up rendering much like our app on the setting of config but was removed in this change: https://github.com/openshift/dynamic-plugin-sdk/commit/1b7f29515cbb43c67d5cf6c5010d5ac6adcaa27f
Running the application.
None …
=> remove SDK initialize delay

frontend/src/__tests__/cypress/cypress/e2e/projects/projectDetails.cy.ts, frontend/src/__tests__/cypress/cypress/pages/projects.ts, frontend/src/pages/modelServing/screens/projects/EmptyModelServingPlatform.tsx, frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx, frontend/src/pages/modelServing/screens/projects/ModelServingPlatformButtonAction.tsx, frontend/src/pages/modelServing/screens/projects/ModelServingPlatformCard.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-3817
added additional tests for project details screen
Validate when no servingRuntime template is available
Validate when single serving platform is enabled
Validate when multi serving platorm is enabled
Validate when both platform are enabled
npm run test
=> additional test for project details

frontend/src/concepts/pipelines/content/createRun/RunPage.tsx, frontend/src/concepts/pipelines/content/createRun/const.ts
hides experiment section jump to section on feature flag disable
disable/enable the feature flag and make sure the section is removed
n/a
Not a UX needed UI change. It is quick fix that is already approved via mocks
=> Add useIsAreaAvailable hook to check if experiments are available and hide jump to section

frontend/src/pages/pipelines/global/runs/GlobalPipelineRunsTabs.scss
JIRA: https://issues.redhat.com/browse/RHOAIENG-3426
This is a one-liner fix, simply changes direction to `column` (because the default is `row` which causes the issue)
1. Go to pipelines run page, and see the empty state, make sure your window is not very wide
2. The style should be fixed, and there will be no overflow text anymore
N/A, it's a one-liner CSS fix, needs manual test.
=> Fix tab custom CSS layout issue on pipelines

backend/src/routes/api/proxy/index.ts, backend/src/routes/wss/k8s/index.ts, backend/src/server.ts, backend/src/utils/directCallUtils.ts, backend/src/utils/httpUtils.ts, backend/src/utils/prometheusUtils.ts, manifests/base/deployment.yaml
Closes https://issues.redhat.com/browse/RHOAIENG-2380
Removes the option to allow unsecure connections throught the pass through API and check wethere k8s library should override the CA bundle
1. Add a certificate in the DSCInitialization object in the ODH Operator
2. Deploy `quay.io/lferrnan/odh-dashboard:rhoaieng-2380` in your cluster
3. Enter the pod's terminal in the dashboard container
4. Check that these certificates does exist:
```bash
'/var/run/secrets/kubernetes.io/serviceaccount/ca.crt',
'/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt',
'/etc/pki/tls/certs/odh-ca-bundle.crt',
'/etc/pki/tls/certs/odh-trusted-ca-bundle.crt',
```
5. `odh-ca-bundle.crt` should contain the certificate added  in step 1
6. Log in into the odh dashboard
7. Create a pipeline server and …
=> Force tls and add ca bundle to k8s library

frontend/src/concepts/pipelines/content/configurePipelinesServer/__tests__/utils.spec.ts, frontend/src/concepts/pipelines/content/configurePipelinesServer/utils.ts, frontend/src/pages/projects/dataConnections/const.ts
JIRA: https://issues.redhat.com/browse/RHOAIENG-2283
Add the region field and set it as required when configuring a pipeline server, the default value is `us-east-1`
Also, when the endpoint is `s3.amazonaws.com`, we convert the `host` field in DSPA to add the region information in.
2. Configure a pipeline server
3. Make sure the region field is pre-filled and is required
4. When you submit the creation, go to DSPA to check whether the `spec.objectStorage.externalStorage.host` is converted. If the endpoint is `s3.amazonaws.com`, it should be converted. Otherwise, we keep it unchanged.
Add unit tests to verify the converted host is correct.
=> Add region field when configuring pipeline server

frontend/src/concepts/k8s/pods/__tests__/usePodContainers.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-4051
Adds unit tests for `usePodContainers.ts`
Run `npm run test`
=> Add unit tests for usePodContainers

frontend/src/concepts/k8s/pods/__tests__/usePod.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-4049
Adds unit tests for `usePod.ts`
Run `npm run test` 
=> Add unit tests for usePod

frontend/src/components/error/ErrorBoundary.tsx
Fixes https://issues.redhat.com/browse/RHOAIENG-2650
Adds a close button to the error boundary. Clicking the close button resets the internal error state causing the error boundary to unmount. When this occurs, the app will resume loading as if no error occurred by rendering the contents of the current URL.
Cause an uncaught error to occur. 
Through the web console, add a breakpoint to a react component. Once the break point is hit, edit a variable such that an exception will be thrown attempting to access a property of an undefined variable
None
=> add close button to error boundary

frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineRuns.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/Pipelines.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelinesTopology.cy.ts, frontend/src/concepts/pipelines/content/createRun/RunForm.tsx, frontend/src/concepts/pipelines/content/createRun/RunPage.tsx, frontend/src/concepts/pipelines/content/createRun/const.ts, frontend/src/concepts/pipelines/content/createRun/contentSections/RunTypeSection.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetailsActions.tsx, frontend/src/concepts/pipelines/content/tables/__tests__/useSetVersionFilter.spec.tsx, frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableRow.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTable.tsx, frontend/src/concepts/pipelines/content/tables/pipelineVersion/PipelineVersionTableRow.tsx, frontend/src/concepts/pipelines/content/tables/useSetVersionFilter.ts, frontend/src/pages/pipelines/global/runs/GlobalPipelineRunsTabs.tsx
Closes: [RHOAIENG-3887](https://issues.redhat.com/browse/RHOAIENG-3887)
Added actions to the pipelines list, pipeline version details, wrapped Schedule settings in a form section for the Create/Schedule run page so that it can be jumped to.
**Create run alert**
https://github.com/opendatahub-io/odh-dashboard/assets/96431149/d0404281-a77a-42c3-9d22-7acc680a4181
**Create schedule alert**
https://github.com/opendatahub-io/odh-dashboard/assets/96431149/e07ab74a-9ded-4f93-9cfb-d317a5457f01
**Pipeline version detail actions**
https://github.com/opendatahub-io/odh-dashboard/assets/96431149/5731087e-a970-4070-b133-1522b7404aac
**Pipeline list actions**
https://github.com/opendatahub-io/odh-dashboard/assets/96431149/96fbdca8-b1a8-4e5a-96a5-db76c17ebddf …
=> [RHOAIENG-3887] Run Schedules - UX cleanup

frontend/src/__tests__/cypress/cypress/e2e/pipelines/Pipelines.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineImportModal.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineVersionImportModal.ts, frontend/src/api/pipelines/callTypes.ts, frontend/src/api/pipelines/custom.ts, frontend/src/concepts/pipelines/content/import/PipelineImportModal.tsx, frontend/src/concepts/pipelines/content/import/PipelineUploadRadio.tsx, frontend/src/concepts/pipelines/content/import/PipelineVersionImportModal.tsx, frontend/src/concepts/pipelines/content/import/useImportModalData.ts, frontend/src/concepts/pipelines/content/import/utils.ts, frontend/src/concepts/pipelines/context/usePipelineAPIState.ts, frontend/src/concepts/pipelines/kfTypes.ts, frontend/src/concepts/pipelines/types.ts
closes: https://issues.redhat.com/browse/RHOAIENG-2299
- adds url upload option for both import pipeline and import pipeline version modal
- uses radio button to switch between
- adds two new pipelines api funcs to manage the import
1. open import pipeline modal
2. fill out required fields
3. select url import'
4. use this for example `https://raw.githubusercontent.com/amadhusu/data-science-pipelines/8dfd0c5fc8db1f4b18a8e22d13dacb4c02c50dbf/samples/core/exit_handler/exit_handler.py.yaml`
5. code source should be optional but url is not optional
6. code source should not show up when doing file upload
7. submit form
8. pipeline should be in table
9. do the same thing but for importing a pipeline version
added 2 tests for url import for pipeline and pipeline version
Self checklist (all need …
=> Add pipeline url submit modal

manifests/overlays/apps/base/rhoai/rhoai-docs.yaml
small PR to update the Resources tile for the RHOAI tutorial - edit the description and change the type from "how-to" to "tutorial"
Closes: https://issues.redhat.com/browse/RHOAIENG-4317
=> odh-532-2 update tile for RHOAI fraud detection tutorial

frontend/src/__tests__/cypress/cypress/e2e/modelServing/ServingRuntimeList.cy.ts
Closes: [RHOAIENG-3838](https://issues.redhat.com/browse/RHOAIENG-3838)
This PR aims to update existing cypress tests on ServingRuntimeList.cy.ts to test the delete functionality for model servers
`npm run test`
=> Update Cypress tests to assert delete in ServingRuntimeList

frontend/src/__mocks__/mock-custom-serving-runtime-add.yaml, frontend/src/__mocks__/mock-custom-serving-runtime-edit.yaml, frontend/src/__tests__/cypress/cypress/e2e/customServingRuntimes/CustomServingRuntimes.cy.ts, frontend/src/__tests__/cypress/cypress/pages/components/DashboardCodeEditor.ts, frontend/src/__tests__/cypress/cypress/pages/servingRuntimes.ts
Closes: [RHOAIENG-3835](https://issues.redhat.com/browse/RHOAIENG-3835)
This PR aims to update cypress test for custom serving runtime 
`npm run test`
=> Update cypress test for custom serving runtime 

frontend/src/concepts/dashboard/DashboardLogViewer.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTabStatus.tsx
JIRA: [RHOAIENG-3830](https://issues.redhat.com/browse/RHOAIENG-3830)
There is some problem with the PF log viewer, which is causing the incorrect rendering for the extremely long log lines. In the OpenShift console, the solution is to truncate the line. However, it's limited currently in the dashboard for now because we haven't applied websocket on the logs, so it's hard to truncate a single line of the logs (it's a full string now). After a discussion with the UX, we decided to add an option to allow the users to check whether they want to wrap the text in the log viewer or not. In this way, they can view the incorrectly rendered logs by unchecking the `Wrap text` checkbox in the toolbar.
Also, update the text in the alert because we don't truncate the exceptionally long lines :)
1. …
=> Add wrap text option for pipeline run logs

frontend/src/__mocks__/mockWorkloadK8sResource.ts, frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts, frontend/src/concepts/distributedWorkloads/__tests__/utils.spec.ts, frontend/src/concepts/distributedWorkloads/utils.tsx, frontend/src/k8sTypes.ts, frontend/src/pages/distributedWorkloads/global/workloadStatus/DWWorkloadsTable.tsx
Closes: [RHOAIENG-3583](https://issues.redhat.com//browse/RHOAIENG-3583)
Implement first iteration of workloads table. More information is necessary before including links from the table. After selecting a project with workloads, go to the workload metrics -> workload status tab.
Cypress tests to see that the table is there with a workload name and with the placeholder text if no workload. Unit test on a new utility function
=> feat(DW): add workloads table

frontend/src/__mocks__/mockClusterQueueK8sResource.ts, frontend/src/__mocks__/mockWorkloadK8sResource.ts, frontend/src/api/k8s/__tests__/clusterQueues.spec.ts, frontend/src/api/k8s/__tests__/workloads.spec.ts, frontend/src/api/prometheus/__tests__/usePrometheusNumberValueQuery.spec.ts, frontend/src/api/prometheus/distributedWorkloads.ts, frontend/src/concepts/distributedWorkloads/__tests__/useClusterQueues.spec.ts, frontend/src/concepts/distributedWorkloads/__tests__/useWorkloads.spec.ts, frontend/src/concepts/distributedWorkloads/useClusterQueues.ts, frontend/src/concepts/distributedWorkloads/useDistributedWorkloadsEnabled.ts, frontend/src/concepts/distributedWorkloads/useWorkloads.ts, frontend/src/pages/distributedWorkloads/global/useDistributedWorkloadsTabs.tsx
Closes [RHOAIENG-3578](https://issues.redhat.com/browse/RHOAIENG-3578).
Followup to #2587. Adds remaining unit tests for code introduced in #2469 that were not covered by #2587, with the exception of the hooks related to specific prometheus queries in `frontend/src/api/prometheus/distributedWorkloads.ts`. The code in that file is very likely to change significantly in the short term, and many of those queries will likely no longer be used due to RBAC issues that are still being resolved. As a result, unit testing those now would likely be throwaway work. This code will be unit tested as part of completing the stories for the Project Metrics epic ([RHOAIENG-2533](https://issues.redhat.com/browse/RHOAIENG-2533)) which will include rewriting/replacing the code in this file.
In order to …
=> Add unit tests for utilities added in initial Distributed Workloads changes

frontend/src/api/prometheus/distributedWorkloads.ts, frontend/src/concepts/distributedWorkloads/DistributedWorkloadsContext.tsx, frontend/src/concepts/distributedWorkloads/__tests__/utils.spec.ts, frontend/src/concepts/distributedWorkloads/utils.tsx, frontend/src/pages/distributedWorkloads/global/workloadStatus/DWStatusOverviewDonutChart.tsx, frontend/src/pages/distributedWorkloads/global/workloadStatus/DWStatusTrendsChart.tsx, frontend/src/pages/distributedWorkloads/global/workloadStatus/DWWorkloadsTable.tsx, frontend/src/pages/distributedWorkloads/global/workloadStatus/GlobalDistributedWorkloadsWorkloadStatusTab.tsx
Closes [RHOAIENG-2881](https://issues.redhat.com/browse/RHOAIENG-2881)
* Replaces the old Prometheus-based `workloadCurrentMetrics` with aggregate status counts based on the conditions of Workload CRs. A new `getStatusCounts` helper uses the `getStatusInfo` helper introduced by https://github.com/opendatahub-io/odh-dashboard/pull/2610 for this.
* Temporarily removes the "Status trends" card from the page since it has been descoped from GA due to RBAC issues.
* Leaves the unused `workloadTrendMetrics` fetching code in place for now because it will be reused when the RBAC issues are resolved. A comment to this effect has been added.
cc @xianli123 
Tested that the donut chart and card layout look correct and accurately represent the data.
Unit test added for the new `getStatusCounts` helper. …
=> Implement Status overview donut chart on DW Workload Status page, temporarily remove Status trends chart

frontend/src/__mocks__/mockRegisteredModel.ts, frontend/src/api/index.ts, frontend/src/api/modelRegistry/__tests__/custom.spec.ts, frontend/src/api/modelRegistry/__tests__/errorUtils.spec.ts, frontend/src/api/modelRegistry/custom.ts, frontend/src/api/modelRegistry/errorUtils.ts, frontend/src/api/proxyUtils.ts, frontend/src/concepts/modelRegistry/types.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-2113
Collaborated with @dpanshug to create the model registry API and related tests
Adds model registry API ([Swagger link](https://editor.swagger.io/?url=https://raw.githubusercontent.com/opendatahub-io/model-registry/main/api/openapi/model-registry.yaml))
As for the APIs not included in this PR - their usage has not been determined yet(not in UX - [confirmed by the backend team](https://redhat-internal.slack.com/archives/C05QB0A582E/p1710322379688809?thread_ts=1710314042.265519&cid=C05QB0A582E)).
You can `console.log` the APIs to test 
Added unit tests for the `custom.ts` and `errorUtils.ts`
=> Add Model registry api

frontend/src/utilities/__tests__/useWatchGroups.spec.tsx, frontend/src/utilities/useWatchGroups.tsx
Closes: [RHOAIENG-2674](https://issues.redhat.com/browse/RHOAIENG-2674)
Updated unit test case for frontend/src/utilities/useWatchGroups.tsx
`npm run test`
Coverage:
Before:
After:
=> Unit Test Update for utilities/useWatchGroups

frontend/.eslintrc, frontend/package-lock.json, frontend/package.json
Closes: https://issues.redhat.com/browse/RHOAIENG-4575
utilize a new eslint rule to prevent  committing test code containing `.only`
npm run test:lint
=> Added no-only-tests eslint rule

frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineCreateRuns.cy.ts, frontend/src/concepts/pipelines/content/createRun/RunForm.tsx, frontend/src/concepts/pipelines/content/createRun/contentSections/ParamsSection/ParamsSection.tsx, frontend/src/concepts/pipelines/content/createRun/utils.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/utils.tsx, frontend/src/concepts/pipelines/kfTypes.ts
Closes: [RHOAIENG-4738](https://issues.redhat.com/browse/RHOAIENG-4738)
Updates pipeline run parameter inputs to allow for descriptions to take form in helper text, `isOptional` to toggle isRequired for `FormGroup`s, and `defaultValue` to pre-populate parameter input values of all types without interfering with the pre-population used when cloning (aka, only for net-new creations).
Also, for description lists for post-creation display of input parameters, since values are possibly optional now, `No value` is now displayed next to labels of parameters with empty values. This was discussed with PF design as a solution instead of just showing whitespace next to labels (cc @yannnz).
Added a cypress test which verifies the creation of a run with default values, optional parameters, and some …
=> [RHOAIENG-4738] default & optional create run parameters

frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts, frontend/src/pages/distributedWorkloads/global/projectMetrics/GlobalDistributedWorkloadsProjectMetricsTab.tsx, frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/DWSectionCard.tsx, frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/ResourceUsage.tsx, frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/SharedStates.tsx, frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/TopResourceConsumingWorkloads.tsx, frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/WorkloadResourceMetrics.tsx
Closes: #https://issues.redhat.com/browse/RHOAIENG-4746
Add empty state, error state, loading state, and placeholders where we don't have the data/charts implemented yet
Showing multiple states (manually manipulated code to do so):
With a project that has no workloads:
A project with workloads:
No quota:
no project (already existed, will show selector when merged with the "move project selector" PR)
tested manually loading data with and without workload data
added tests to make sure the various empty states are showing up
- [ x] The developer has manually tested the changes and verified that the changes work
- [ x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have …
=> feat(dw): add empty state and placeholders

frontend/src/pages/distributedWorkloads/GlobalDistributedWorkloadsRoutes.tsx, frontend/src/pages/distributedWorkloads/global/GlobalDistributedWorkloads.tsx, frontend/src/pages/distributedWorkloads/global/GlobalDistributedWorkloadsTabs.tsx, frontend/src/pages/distributedWorkloads/global/useDistributedWorkloadsTabs.tsx
Closes: [RHOAIENG-4623](https://issues.redhat.com/browse/RHOAIENG-4623)
Moved the project selector to the header for workload metrics (was previously at the top of each tab page section)
Before:
After:
Tested changes by checking:
- Project selector exists in header with both tabs selected
- Project selector does not exist in either tab anymore
- Selecting a project updates the data, reflecting the project has changed
- Selecting a project does not change the page/tab we are on
(operates in the same manner as previously, just shows up in a different area)
=> feat(dw): move project selector to page head

frontend/src/__tests__/cypress/cypress/e2e/acceleratorProfiles/AcceleratorProfiles.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/modelServing/ServingRuntimeList.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/notebookImageSettings/NotebookImageSettings.cy.ts, frontend/src/__tests__/cypress/cypress/pages/acceleratorProfile.ts, frontend/src/__tests__/cypress/cypress/pages/components/TableToolbar.ts, frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/__tests__/cypress/cypress/pages/notebookImageSettings.ts, frontend/src/__tests__/cypress/cypress/support/commands/application.ts, frontend/src/concepts/dashboard/DashboardSearchField.tsx, frontend/src/pages/acceleratorProfiles/screens/list/AcceleratorProfileEnableToggle.tsx, frontend/src/pages/acceleratorProfiles/screens/list/DisableAcceleratorProfileModal.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-3818
This PR aims to update the accelerator profile cypress test. Also added a generic component for filter and search functionality, and applied it to the `NotebookImageSetting` file and `ServingRuntimeList` file. 
`npm run test`
=> Update Accelerator profile cypress test 

frontend/src/pages/modelServing/screens/projects/ProjectServerMetricsWrapper.tsx
Closes https://issues.redhat.com/browse/RHOAIENG-5067 (**Critical**)
As identified by @christianvogt, the `ProjectServerMetricsWrapper` was passing the current project's display name into `ModelServingMetricsProvider` instead of the namespace name. This was making its way into the Prometheus query strings in the Model Serving Metrics page, causing 400 Bad Request errors.
Created a model server in a project whose display name is different from its underlying namespace (e.g. it has capital letters or spaces in it). Tried to view the model server metrics (Projects -> [project] -> Models tab -> Kebab menu -> View model server metrics) and saw that before this change I got 400 errors in the dev tools Network tab and the loading spinners on the page never resolved. After this change the queries …
=> RHOAIENG-5067: Model Serving Metrics: Use real namespace name instead of project display name in queries

frontend/src/concepts/design/CollapsibleSection.tsx, frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx, frontend/src/pages/projects/screens/detail/overview/configuration/ConfigurationSection.tsx, frontend/src/pages/projects/screens/detail/overview/serverModels/NoProjectServingEnabledSection.tsx, frontend/src/pages/projects/screens/detail/overview/serverModels/PlatformSelectSection.tsx, frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelsSection.tsx, frontend/src/pages/projects/screens/detail/overview/trainModels/TrainModelsSection.tsx
Closes https://issues.redhat.com/browse/RHOAIENG-4995 and https://issues.redhat.com/browse/RHOAIENG-4882
Based on feedback from Jenn, Sim, and Tal, this PR removes the background and border colors for collapsed sections. This is in line with the future designs for expand/collapse sections and helps minimize logic needed to apply colors to borders. Also fixes a typo in the Data connections tab.
@simrandhaliw
Ran locally and did a visual test.
Since this is just a styling update, other tests may not be necessary.
=> Remove collapsible borders and fix typo

frontend/src/api/prometheus/__tests__/distributedWorkloads.spec.ts, frontend/src/api/prometheus/distributedWorkloads.ts, frontend/src/concepts/distributedWorkloads/DistributedWorkloadsContext.tsx, frontend/src/pages/distributedWorkloads/global/projectMetrics/GlobalDistributedWorkloadsProjectMetricsTab.tsx, frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/SharedStates.tsx, frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/TopResourceConsumingWorkloads.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-2845
implement top consuming distributed workload charts
left some utility type stuff in the consuming chart component, this and the inner pf chart will be moved out once we get this and other chart stuff in and are able to combine/refactor a bit.
No workloads:
No workloads consuming resources (similar message for if all or some have failed, but using <!> icon and noting that some or all have failed):
With data
With narrow screen:
Ran through with various data and lack of data
tests for the empty state of this session are in place, not sure if we are testing charts
empty state works (no workloads, no workloads with usage), if workloads with usage exist, two donut charts should show the details of that usage. …
=> feat(dw): top consumption charts

frontend/src/pages/projects/screens/detail/overview/trainModels/NotebooksCard.tsx
Closes: [RHOAIENG-4847](https://issues.redhat.com/browse/RHOAIENG-4847)
Remove the check for pipeline server compatibility from the notebooks overview card
Tested manually on a server with an incompatible pipeline server version.
None
=> fix(overview): Don't show pipeline compatibility error in notebooks card

frontend/src/pages/projects/screens/projects/ProjectListView.tsx, frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx
Closes: [RHOAIENG-4853](https://issues.redhat.com/browse/RHOAIENG-4853)
Fixes padding on the first column of a striped row. Since it is the first column in the row, PF adds a larger padding which we don't want.
Sets the default sort column to the project name.
Manual testing
None
=> fix(projects list): fix style issue on striped rows, add default sort

frontend/src/__mocks__/mockClusterQueueK8sResource.ts, frontend/src/__mocks__/mockLocalQueueK8sResource.ts, frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts, frontend/src/api/index.ts, frontend/src/api/k8s/__tests__/localQueues.spec.ts, frontend/src/api/k8s/localQueues.ts, frontend/src/api/models/kueue.ts, frontend/src/api/prometheus/distributedWorkloads.ts, frontend/src/concepts/distributedWorkloads/DistributedWorkloadsContext.tsx, frontend/src/concepts/distributedWorkloads/__tests__/useLocalQueues.spec.ts, frontend/src/concepts/distributedWorkloads/useLocalQueues.ts, frontend/src/k8sTypes.ts, frontend/src/pages/distributedWorkloads/global/projectMetrics/GlobalDistributedWorkloadsProjectMetricsTab.tsx
Closes [RHOAIENG-4746](https://issues.redhat.com/browse/RHOAIENG-4746) (followup to #2644, cc @gitdallas)
Needed for [RHOAIENG-2844](https://issues.redhat.com/browse/RHOAIENG-2844)
* Adds types, utilities, hooks and tests for fetching Kueue [LocalQueues](https://kueue.sigs.k8s.io/docs/reference/kueue.v1beta1/#kueue-x-k8s-io-v1beta1-LocalQueue). LocalQueues are the last piece of data the UI needs to fetch to implement features for our initial Distributed Workloads GA. The `LocalQueueKind` type is based on referencing [the CRD here](https://github.com/kubernetes-sigs/kueue/blob/main/config/components/crd/bases/kueue.x-k8s.io_localqueues.yaml) and [the API docs here](https://kueue.sigs.k8s.io/docs/reference/kueue.v1beta1/#kueue-x-k8s-io-v1beta1-LocalQueue).
* Also cleans up some repetition …
=> DW: Fetch LocalQueues, pass them down in context, use them for "quota is not set" empty state

frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelsCard.tsx, frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelsSection.tsx
Closes [RHOAIENG-4859](https://issues.redhat.com/browse/RHOAIENG-4859)
Fixes an issue where models from all projects are being shown in the models section of the overview page. The fix is to pass the project name to the models list rather than incorrectly using the current project namespace field.
Manually tested and verified that models from other projects no longer show in the cards list.
None.
=> [RHOAIENG-4859] Fix for showing correct models in project overview

frontend/src/__tests__/cypress/cypress/e2e/pipelines/Experiments.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineCreateRuns.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineRuns.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/Pipelines.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineFilterBar.ts
Closes: [RHOAIENG-3819](https://issues.redhat.com/browse/RHOAIENG-3819)
This PR validates that the Archived runs table filtering, searching and sorting functionality works properly, and that the Active and Scheduled runs table sorting functionality works. 
`npm run test`
=> Update PipelineRuns Cypress test to account for sorting and filtering

frontend/src/__tests__/cypress/cypress/e2e/pipelines/ManageRuns.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineCreateRuns.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineRuns.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/intercepts.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/manageRuns.ts, frontend/src/app/App.tsx, frontend/src/components/table/TableBase.tsx, frontend/src/components/table/useCheckboxTable.ts, frontend/src/components/table/useCheckboxTableBase.ts, frontend/src/concepts/pipelines/content/tables/PipelineFilterBar.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRowTitle.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableToolbar.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/usePipelineRunTable.ts, frontend/src/concepts/pipelines/content/tables/pipelineVersion/usePipelineVersionsCheckboxTable.ts, frontend/src/concepts/pipelines/content/tables/usePipelineFilter.ts, frontend/src/concepts/pipelines/content/tables/usePipelineTable.ts, frontend/src/pages/pipelines/GlobalPipelineExperimentsRoutes.tsx, frontend/src/pages/pipelines/global/experiments/compareRuns/ManageRunsPage.tsx, frontend/src/pages/pipelines/global/experiments/compareRuns/ManageRunsTable.tsx, frontend/src/pages/pipelines/global/runs/ActiveRuns.tsx, frontend/src/pages/pipelines/global/runs/ArchivedRuns.tsx, frontend/src/routes/pipelines/experiments.ts
Closes: [RHOAIENG-4660](https://issues.redhat.com/browse/RHOAIENG-4660)
Manage runs page uses selected runs from the Compare runs page initially as pre-selected table rows (runs), and the user has the ability to select up to 10 total (and change what was initially selected if they want). Selections are maintained between pages, cancelling uses what was initially selected by the Compare runs page, and "Update" will update the selections and bring the user back to the Compare runs page.
Cypress tests for main interactions
1. Navigate to `http://localhost:4010/experiments/jps-fun-world/85c9d729-bf63-441f-af87-d6898e5db5f0/compareRuns/add`
2. Verify the initial Experiment filter is set to the experiment associated with the ID in your URL path
3. Select up to 10 table rows on a single or …
=> [RHOAIENG-4660] Compare runs - Manage runs page

frontend/src/pages/projects/screens/detail/overview/trainModels/NotebooksCard.tsx, frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCard.tsx
Closes: [RHOAIENG-4996](https://issues.redhat.com/browse/RHOAIENG-4996)
Remove the help popovers for the Project overview, workbench and pipeline empty state cards.
Add the help popovers for the Project overview, workbench and pipeline non-empty state cards.
Tested against projects with and without workbenches and pipelines
None
=> [RHOAIENG-4996] Show popover help for non-empty pipelines/notebooks cards

frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineCreateRuns.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/createRunPage.ts, frontend/src/concepts/pipelines/content/createRun/RunForm.tsx, frontend/src/concepts/pipelines/content/createRun/RunPage.tsx, frontend/src/concepts/pipelines/content/createRun/contentSections/RunTypeSection.tsx
closes: https://issues.redhat.com/browse/RHOAIENG-4739
- switching from triggered run to scheduled run and vise versa now directs to the create form and not the list
- doing this from a clone will direct to a non clone route 
- create a run, switch run to scheduled
- create a schedule, switch run to triggered
- clone a run, switch to non clone route schedule
- clone a schedule, switch to non clone triggered
added tests for the redirects in both directions
=> Fix run type switch link in createRunPage and RunPage

frontend/src/__tests__/cypress/cypress/e2e/projects/ProjectList.cy.ts, frontend/src/__tests__/cypress/cypress/pages/acceleratorProfile.ts, frontend/src/__tests__/cypress/cypress/pages/clusterSettings.ts, frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts, frontend/src/__tests__/cypress/cypress/pages/distributedWorkloads.ts, frontend/src/__tests__/cypress/cypress/pages/enabled.ts, frontend/src/__tests__/cypress/cypress/pages/explore.ts, frontend/src/__tests__/cypress/cypress/pages/modelMetrics.ts, frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts, frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/__tests__/cypress/cypress/pages/notebookImageSettings.ts, frontend/src/__tests__/cypress/cypress/pages/pageNotFound.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/compareRuns.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/experiments.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/manageRuns.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunsGlobal.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesGlobal.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/topology.ts, frontend/src/__tests__/cypress/cypress/pages/projects.ts, frontend/src/__tests__/cypress/cypress/pages/servingRuntimes.ts
https://issues.redhat.com/browse/RHOAIENG-2808
It's still unclear exactly what is causing the initial page load to fail. It's possibly an issue with the HTTP server used hosting our frontend or something internally with cypress. However the check for the invalid status code is performed by the custom command `visitWithLogin`. This command is only useful if running against a live cluster (eg. for snapshot purposes). Therefore this PR replaces the use of `visitWithLogin` with a basic `visit` call. The hope here is that `visit` will reattempt the command if this situation and resolve itself. `visitWithLogin` used `{ failOnStatusCode: false }` which was needed to capture the `403`. An assumption here is that this option aborts any retry attempts.
Test automation.
Updated cypress tests.
Self …
=> use default cy.visit function

frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelServingGlobal.cy.ts, frontend/src/pages/modelServing/screens/global/EmptyModelServing.tsx
Closes: [RHOAIENG-5104](https://issues.redhat.com/browse/RHOAIENG-5104)
Fix to use the correct model serving empty state image. Also, reverted code that removed the ability to deploy a model from the empty state form multi-serving runtime platforms.
Manually and with e2e tests
None
=> [RHOAIENG-5104] Fix empty state image for global model servers

frontend/src/__tests__/cypress/cypress/e2e/projects/projectDetails.cy.ts, frontend/src/__tests__/cypress/cypress/pages/projects.ts, frontend/src/concepts/pipelines/elyra/ElyraInvalidVersionAlerts.tsx, frontend/src/concepts/pipelines/elyra/utils.ts, frontend/src/pages/projects/screens/detail/notebooks/NotebookTable.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx, frontend/src/pages/projects/screens/detail/notebooks/useNotebookImageData.ts, frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx, frontend/src/pages/projects/screens/spawner/imageSelector/ImageVersionSelector.tsx
closes: https://issues.redhat.com/browse/RHOAIENG-4715
Adds two new alerts above workbenches table in the project details section
- Info alert when you are on a v2 pipeline server but have at least one workbench with a notebook image using old version of python package Elyra.
- has a checkbox to hide or show the notebook image info icon
- warning alert when you are on a v1 pipeline server but have at least one workbench with a notebook image using the updated version of python package ODH-Elyra
- an info icon with a popover on images with out of date elyra for when the info alert is shown (same criteria)
- both alerts can be dismissed and that is saved in session storage
- info icon for out of date elyra is added to version in workbench spawner only if the criteria are met (using new v2 …
=> Add Elyra version check functions and ElyraInvalidVersion component

frontend/src/__tests__/cypress/cypress/e2e/pipelines/CompareRuns.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/compareRuns.ts, frontend/src/concepts/pipelines/content/compareRuns/CompareRunTableRow.tsx, frontend/src/concepts/pipelines/content/compareRuns/CompareRunTableToolbar.tsx, frontend/src/concepts/pipelines/content/compareRuns/CompareRunsRunList.tsx, frontend/src/concepts/pipelines/content/compareRuns/columns.ts, frontend/src/concepts/pipelines/content/compareRuns/useCompareRunsCheckboxTable.ts, frontend/src/pages/ApplicationsPage.tsx, frontend/src/pages/pipelines/global/experiments/compareRuns/CompareRunsPage.tsx, frontend/src/pages/pipelines/global/experiments/compareRuns/GlobalComparePipelineRunsLoader.tsx
JIRA: [RHOAIENG-4658](https://issues.redhat.com/browse/RHOAIENG-4658)
Added an expandable list to show the runs that are being compared.
Finish the filter as well.
1. Go to the experiment page
2. Go to experiment details
3. Check some runs and click on `Compare runs` button
4. You will see this page
5. Test the sort and filter functions
Add some check to the cypress e2e test to make sure it can correctly render the list.
=> Add compare runs list

frontend/package-lock.json
Closes: [RHOAIENG-4843](https://issues.redhat.com/browse/RHOAIENG-4843)
Upgrades frontend packages to remove vulnerabilities reported on snyk.
```
odh-dashboard/frontend$ npm audit
found 0 vulnerabilities
```
No test added, just a package upgrade.
=> Frontend synk vulnerabilities

docs/dev-setup.md, frontend/src/components/ExternalLink.tsx, frontend/src/pages/projects/notebook/NotebookRouteLink.tsx, frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx, frontend/src/pages/projects/screens/projects/DeleteProjectModal.tsx, frontend/src/pages/projects/screens/projects/NewProjectButton.tsx, frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx, frontend/src/types.ts, frontend/src/utilities/segmentIOUtils.tsx
This adds additional Segment tracking. No visible UI changes are done.
This is recorded in https://issues.redhat.com/browse/RHOAIENG-4226
Click through projects UI, see events flow into Segment (or in dev-mode, watch browser console)
UI behaviour is not changed.
- [] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)
=> [RHOAIENG-4226] Add additional tracking for projects UI.

frontend/src/api/prometheus/__tests__/useQueryRangeResourceData.spec.ts
Closes: [RHOAIENG-2176](https://issues.redhat.com/browse/RHOAIENG-2176)
Unit test case for useQueryRangeResourceData
`npm run test`
=> Unit test case for useQueryRangeResourceData

frontend/src/concepts/pipelines/content/__tests__/utils.spec.tsx, frontend/src/concepts/pipelines/content/compareRuns/CompareRunsRunList.tsx, frontend/src/concepts/pipelines/content/createRun/RunPage.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabDetails.tsx, frontend/src/concepts/pipelines/content/tables/usePipelineRunVersionInfo.ts, frontend/src/concepts/pipelines/kfTypes.ts
closes: https://issues.redhat.com/browse/RHOAIENG-5245
- handles sdk flow where user creates a run using `kfp.Client.create_run_from_pipeline_package` which produces a run without a reference to a pipeline/pipeline version. This PR adjusts the types to make it the reference optional so we dont run into this type error in the future
- also now will fallback to run.pipeline_spec (is only available when creating a run using `create_run_from_pipeline_package`) instead of fetching the version and getting the spec from there.
1. create a pipeline run using the v2 sdk
- I used this tutorial: https://www.kubeflow.org/docs/components/pipelines/v2/hello-world/
- I had ssl issues, you may not, but to get around it see: https://v1-5-branch.kubeflow.org/docs/components/pipelines/sdk/connect-api/#connec …
=> Fix pipeline version reference in pipeline run details

frontend/src/concepts/pipelines/NoPipelineServer.tsx
closes: https://issues.redhat.com/browse/RHOAIENG-4846
The NoPipelineServer component now handles both no pipeline server and no pipelines since the UI refresh. However this component would only ever open the no pipeline server modal. This PR does the lightest change possible and just adds a condition to render the correct modal. Ideally these should be separated into their own components, but to maintian the most stability i kept it like this.
1. open project pipelines tab from project details page (with no pipeline server installed)
2. empty state button should open configure pipeline server modal
3. configure the server
4. now the empty state should be no pipelines AND the button should open to the import pipeline modal
no tests impacted
If you …
=> Add ImportPipelineButton to NoPipelineServer component

frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts, frontend/src/pages/distributedWorkloads/global/GlobalDistributedWorkloadsTabs.tsx, frontend/src/pages/distributedWorkloads/global/projectMetrics/GlobalDistributedWorkloadsProjectMetricsTab.tsx
moving quota related error/empty/loading states out of the project metrics tab and to the full dw page.
ran through some scenarios on my local
updated some tests that were previously testing the existence of these states at the project metric tab level
quota related states will now show at the page level instead of under the project metric tab
=> feat(dw): move quota level issue states out of tabs

frontend/src/api/prometheus/__tests__/usePrometheusQueryRange.spec.ts
Closes: [RHOAIENG-2163](https://issues.redhat.com/browse/RHOAIENG-2163)
Unit test case for prometheus/usePrometheusQueryRange file
`npm run test`
=> add test case for usePrometheusQueryRange

frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts, frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/TopResourceConsumingWorkloads.tsx, frontend/src/pages/distributedWorkloads/global/workloadStatus/DWStatusOverviewDonutChart.tsx, frontend/src/pages/distributedWorkloads/global/workloadStatus/GlobalDistributedWorkloadsWorkloadStatusTab.tsx
addresses feedback on empty charts in the "top-consuming" section while we have data in other charts (happens when winding down?). also adds empty state for status overview chart
charts with no data will now show a gray donut, with a "No workload is consuming {unit}" tooltip and no legend.
charts with no data will now show a gray donut, with a "No workload is consuming {unit}" tooltip and no legend.
manually modifying data to test with empty data
no test impact, mostly a design change that doesn't impact data
no workloads at all will still show the empty state screen, if there is data a specific chart doesn't have data, it will get the new gray donut
=> feat(DW): gray donuts for empty data top-consuming charts

backend/src/types.ts, backend/src/utils/constants.ts, docs/dashboard-config.md, manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml, manifests/overlays/odhdashboardconfig/odhdashboardconfig.yaml
Enables the Distributed Workloads feature by default for its GA in the upcoming release.
N/A
N/A
=> Enable Distributed Workloads feature flag by default in manifests

frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineCreateRuns.cy.ts, frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts, frontend/src/concepts/pipelines/content/createRun/utils.ts
JIRA: https://issues.redhat.com/browse/RHOAIENG-4258
When switching to a pipeline that contains no versions in it, we always trigger the hook `useUpdatePipelineFormData` and set the version to the incorrect one. The solution is to add a check before setting it to make sure we are only doing this when setting the same pipeline but not switching to another.
Also, fix a small issue that could crash the page.
1. Create 2 pipelines (pipeline 1 and pipeline 2)
2. Delete the version in pipeline 2, make sure there is no version in it
3. Create a run using pipeline 1
4. Duplicate this run, and switch the pipeline selection to pipeline 2
5. Verify the version selector is disabled and showing "no versions available" in it
Add some conditions in the cypress test to verify the change works.
Self …
=> Fix issue when selecting a pipeline without version on the clone run page

frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelServingGlobal.cy.ts, frontend/src/__tests__/cypress/cypress/pages/components/TableToolbar.ts, frontend/src/__tests__/cypress/cypress/pages/modelServing.ts
Closes: [RHOAIENG-3837](https://issues.redhat.com/browse/RHOAIENG-3837)
This PR validates that the Name and Project table filtering, searching, and sorting functionality works properly
`npm run test`
=> Update ModelServingGlobal Cypress test to account for sorting and filtering

frontend/src/concepts/pipelines/EnsureCompatiblePipelineServer.tsx
closes: https://issues.redhat.com/browse/RHOAIENG-5334
adjusts text dependent on admin or not
- log in as admin
- go to project with a v1 pipeline server -> see error message with delete button
- log in as regular user 
- go to project with a v1 pipeline server -> see error message without delete button
none
@kywalker-rh 
=> Add useUser hook to EnsureCompatiblePipelineServer component

frontend/src/__tests__/cypress/cypress/e2e/projects/Workbench.cy.ts, frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/__tests__/cypress/cypress/pages/workbench.ts, frontend/src/__tests__/cypress/cypress/support/commands/application.ts, frontend/src/components/SimpleDropdownSelect.tsx, frontend/src/concepts/dashboard/DashboardSearchField.tsx, frontend/src/concepts/pipelines/content/compareRuns/CompareRunTableToolbar.tsx, frontend/src/concepts/pipelines/content/createRun/contentSections/TriggerTypeField.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableToolbar.tsx, frontend/src/pages/acceleratorProfiles/screens/manage/tolerations/TolerationFields.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAPIProtocolSelector.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimePlatformsSelector.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx, frontend/src/pages/projects/screens/spawner/imageSelector/ImageStreamSelector.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-3412
Fixes the image selection dropdown scroll issue. Upgraded `SimpleDropdownSelect` component to PF5.
https://github.com/opendatahub-io/odh-dashboard/assets/22885912/3d8af954-c3cf-4d6c-8702-b14b5096b359
Try creating a workbench after creating many custom images using the `Notebook images` section in the `Settings` section in the Dashboard. You should see a scroll bar while trying to select images in the `Image selection`, which doesn't break the layout. 
Fixed failing tests due to the PF5 migration. Added new tests for scrollable dropdown selection
=> Fixes Image selection dropdown scroll issue

frontend/src/app/AppRoutes.tsx, frontend/src/concepts/areas/types.ts, frontend/src/concepts/areas/utils.ts, frontend/src/concepts/pipelines/content/InvalidArgoDeploymentAlert.tsx
closes: https://issues.redhat.com/browse/RHOAIENG-5296
Adds a alert to the top of every page that can be dismissed (and stays dismissed) when the following are true:
- pipelines feature flag is enabled
- there exists a condition with the following `c.type === 'CapabilityDSPv2Argo' && c.status === 'False'` in the DSC
You can add this mocked data to `backend/src/utils/dsc.ts`
```diff
diff --git a/backend/src/utils/dsc.ts b/backend/src/utils/dsc.ts
index eae01bc1..a5a7e81d 100644
--- a/backend/src/utils/dsc.ts
+++ b/backend/src/utils/dsc.ts
@@ -12,6 +12,26 @@ export const getClusterStatus = async (
const result: DataScienceClusterKind | null = await fastify.kube.customObjectsApi
.listClusterCustomObject('datasciencecluster.opendatahub.io', 'v1', 'datascienceclusters')
.then((res) => …
```
=> Add InvalidArgoDeploymentAlert component to AppRoutes

frontend/src/api/k8s/__tests__/notebooks.spec.ts
Closes: [RHOAIENG-5447](https://issues.redhat.com//browse/RHOAIENG-5447)
This PR addresses an issue where notebook.spec.ts is failing randomly due to its reliance on date timestamps. The failures occur because the test does not mock out the system date when using the Date object.
`npm run test`
=> notebook.spec.ts unit test flake

frontend/src/utilities/segmentIOUtils.tsx
The previous setting (from #2557 ) was still loading the analytics.js directly from Segment.
The cdn setting in the options did not override this.
This is a followup on [RHOAIENG-3984](https://issues.redhat.com//browse/RHOAIENG-3984).
Manual testing in browser console without dev-mode.
Network calls should look like this:
Should be none, as the tracking itself has not changed.
=> [RHOAIENG-3984] Make sure analytics.js is loaded via proxy

Makefile
Provided support for s390x and ppc64le to create multi-arch image
For creating multi-arch build image, use command ``` make docker-buildx ```.  This will build multi-arch images and will push into your provided image repository
=> Adding support for s390x and ppc64le for multi-arch image build

frontend/src/concepts/pipelines/apiHooks/usePipelines.ts, frontend/src/concepts/pipelines/context/PipelinesContext.tsx, frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCard.tsx, frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCardMetrics.tsx, frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesOverviewCard.tsx
closes: https://issues.redhat.com/browse/RHOAIENG-5429
This fixes two issues:
1. an issue with how api availability is determined changed after security updates, meaning we said it was available bc we knew the route, but the service was not ready
2. pipeline overview card in workbenches overview tab accesses pipeline resources without a check for api availability and correct pipeline version, resulting in errors
What I did
- adds back check for route to be loaded to api is available
- puts pipeline overview card behind checks for api availability and correct version check
- had to split component up to do so
- needed to make a new safe get pipelines hook bc the card title relies on the count of pipelines
1. go to overview tab of project without pipeline server
3. should not see an error …
=> Refactor pipelines context and add useSafePipelines hook

frontend/src/concepts/pipelines/apiHooks/mlmd/types.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/useExecutionsFromMlmdContext.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/useMlmdContext.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/usePipelineRunMlmdContext.ts, frontend/src/concepts/pipelines/apiHooks/usePipelineRunById.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/useExecutionsForPipelineRun.ts, frontend/src/concepts/pipelines/kfTypes.ts, frontend/src/concepts/pipelines/topology/__tests__/parseUtils.spec.ts, frontend/src/concepts/pipelines/topology/parseUtils.ts, frontend/src/concepts/pipelines/topology/pipelineTaskTypes.ts, frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.ts
JIRA: https://issues.redhat.com/browse/RHOAIENG-4544
Read pipeline executions information from the mlmd service instead of parsing it by ourselves so it's more accurate. If the mlmd service is not available, it will fall back to our current logic.
1. Create a pipeline run
2. Click on the nodes
3. Compare it with the KubeFlow Pipeline runs UI, make sure the information is the same with the ones in that UI
N/A, not sure how we should test the mlmd service, I can add it if needed after the PR gets reviewed.
=> Read pipeline run node details from mlmd context

backend/src/types.ts, backend/src/utils/constants.ts, docs/dashboard-config.md, frontend/src/__mocks__/mockDashboardConfig.ts, frontend/src/__tests__/cypress/cypress/e2e/home/home.cy.ts, frontend/src/__tests__/cypress/cypress/pages/enabled.ts, frontend/src/app/AppRoutes.tsx, frontend/src/concepts/areas/const.ts, frontend/src/concepts/areas/types.ts, frontend/src/k8sTypes.ts, frontend/src/pages/home/Home.tsx, frontend/src/utilities/NavData.tsx, manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml, manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml, manifests/overlays/odhdashboardconfig/odhdashboardconfig.yaml
Closes: [RHOAIENG-5487](https://issues.redhat.com/browse/RHOAIENG-5487)
Adds an initial Home page for the dashboard hidden behind a feature flag. The feature flag is set to disable the page and it will not be shown until/unless it is enabled.
Tested manually by turning on/off the disableHome flag.
Added e2e test to verify the feature flag is working correctly.
=> [RHOAIENG-5487] Initial "empty state" of home page

frontend/src/app/AppRoutes.tsx, frontend/src/components/table/TableBase.tsx, frontend/src/pages/ApplicationsPage.tsx, frontend/src/pages/pipelines/GlobalArtifactsRoutes.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactsListTable.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/GlobalArtifactsPage.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/index.ts, frontend/src/pages/pipelines/global/experiments/artifacts/useGetArtifactsList.ts, frontend/src/routes/pipelines/artifacts.ts, frontend/src/routes/pipelines/index.ts, frontend/src/utilities/NavData.tsx
Closes: [RHOAIENG-2986](https://issues.redhat.com/browse/RHOAIENG-2986)
Initial setup for Artifacts that includes the nav item, page with project selector, title, description, data fetching and loading/empty state. The artifact route is behind the experiments feature flag as it is a sub-nav item to the Experiments nav section.
(cc @yannnz)
=> [RHOAIENG-2986] Artifacts - Initial Infrastructure

frontend/src/__mocks__/mockModelVersion.ts, frontend/src/__mocks__/mockModelVersionList.ts, frontend/src/__mocks__/mockRegisteredModel.ts, frontend/src/__mocks__/mockRegisteredModelsList.ts, frontend/src/__tests__/cypress/cypress/e2e/modelRegistry/ModelRegistry.cy.ts, frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts, frontend/src/__tests__/cypress/cypress/support/commands/odh.ts, frontend/src/api/modelRegistry/k8s.ts, frontend/src/api/models/index.ts, frontend/src/api/models/odh.ts, frontend/src/pages/modelRegistry/screens/ModelRegistry.tsx, frontend/src/pages/modelRegistry/screens/RegisteredModelLabels.tsx, frontend/src/pages/modelRegistry/screens/RegisteredModelListView.tsx, frontend/src/pages/modelRegistry/screens/RegisteredModelOwner.tsx, frontend/src/pages/modelRegistry/screens/RegisteredModelTable.tsx, frontend/src/pages/modelRegistry/screens/RegisteredModelTableRow.tsx, frontend/src/pages/modelRegistry/screens/RegisteredModelsTableToolbar.tsx
Closes: [RHOAIENG-2231](https://issues.redhat.com/browse/RHOAIENG-2231) [RHOAIENG-2232](https://issues.redhat.com/browse/RHOAIENG-2232)
Added cypress testing and minor changes
Move to Model registry section
Added cypress test for model registry
=> Registered model table follow-up and cypress testing

frontend/src/utilities/__tests__/useDraggableTable.spec.ts, frontend/src/utilities/useDraggableTable.ts
Closes: [RHOAIENG-2120](https://issues.redhat.com/browse/RHOAIENG-2120)
added unit test for frontend/src/utilities/useDraggableTable.ts 
`npm run test`
=> Unit Test Case for useDraggableTable

frontend/src/pages/distributedWorkloads/components/WorkloadResourceUsageBar.scss, frontend/src/pages/distributedWorkloads/components/WorkloadResourceUsageBar.tsx, frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/WorkloadResourceMetricsTable.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-5294
factored out css from the resourceUsageBar aside from a gap which is a temporary fix until patternfly can fix the progress bar on their side - https://github.com/patternfly/patternfly-react/issues/10278 
moved spacing styling (giving progress bar a better gap on the right to distinguish, necessary as there are gaps between the progress bar and the numbers associated with them) to the table
removed the color swatches in the progress bar tooltip as a result of this convo:  https://redhat-internal.slack.com/archives/C06J77CPB7S/p1713293363066699
ran locally to see changes, tests pass
none
everything still works as expected, color swatches are removed from progress bar tooltip
If you have UI …
=> chore(DW): 5294 refactor resourceUsageBar

frontend/src/__mocks__/mockAllowedUsers.ts, frontend/src/__mocks__/mockNotebookImageInfo.ts, frontend/src/__tests__/cypress/cypress/e2e/applications/Administration.cy.ts, frontend/src/__tests__/cypress/cypress/pages/administration.ts, frontend/src/__tests__/cypress/cypress/support/commands/odh.ts, frontend/src/pages/notebookController/screens/admin/ImpersonateAlert.tsx, frontend/src/pages/notebookController/screens/admin/NotebookAdminControl.tsx, frontend/src/pages/notebookController/screens/admin/NotebookControllerTabs.tsx, frontend/src/pages/notebookController/screens/admin/ServerStatus.tsx, frontend/src/pages/notebookController/screens/admin/StopAllServersButton.tsx, frontend/src/pages/notebookController/screens/admin/types.ts, frontend/src/pages/notebookController/screens/server/ImageSelector.tsx, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
Closes: [RHOAIENG-3919](https://issues.redhat.com/browse/RHOAIENG-3919)
This PR aims to add cypress test for administration tab.
`npm run test`
=> Cypress test for Administration tab

frontend/src/__tests__/cypress/cypress/e2e/home/homeProjects.cy.ts, frontend/src/components/EvenlySpacedGallery.tsx, frontend/src/components/OdhCard.scss, frontend/src/components/OdhDocCard.tsx, frontend/src/components/TruncatedText.tsx, frontend/src/concepts/projects/ProjectsContext.tsx, frontend/src/pages/home/aiFlows/useAIFlows.tsx, frontend/src/pages/home/projects/CreateProjectCard.tsx, frontend/src/pages/home/projects/ProjectCard.tsx, frontend/src/pages/home/projects/ProjectsSection.tsx, frontend/src/pages/home/projects/ProjectsSectionHeader.tsx
Closes: [RHOAIENG-5489](https://issues.redhat.com/browse/RHOAIENG-5489)
Closes: [RHOAIENG-5490](https://issues.redhat.com/browse/RHOAIENG-5490)
Closes: [RHOAIENG-4860](https://issues.redhat.com/browse/RHOAIENG-4860)
Add project tiles to the home page projects section.
Locally tested while turning the home page feature floag on
Added e2e tests
/cc @jgiardino
=> [RHOAIENG-5489] Home page: projects w/ tiles

frontend/src/__mocks__/mockGroupConfig.ts, frontend/src/__tests__/cypress/cypress/e2e/projects/projectDetails.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/userManagement/userManagement.cy.ts, frontend/src/__tests__/cypress/cypress/pages/userManagement.ts, frontend/src/__tests__/cypress/cypress/support/commands/odh.ts, frontend/src/components/MultiSelection.tsx, frontend/src/components/SettingSection.tsx, frontend/src/pages/groupSettings/GroupSettings.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-3813
Closes: https://issues.redhat.com/browse/RHOAIENG-5310
added cypress test for user management
npm run test
=> added user management cypress test

frontend/config/webpack.dev.js, frontend/package.json, frontend/src/app/HeaderTools.tsx, frontend/src/utilities/const.ts
https://issues.redhat.com/browse/RHOAIENG-6353
Removes the requirement for frontend local development requiring also a local running backend server.
Support running the frontend dev server communicating with an external cluster by proxying all `/api` calls to the external cluster.
Requires logging into the cluster using `oc` before starting webpack dev server using `npm run start:dev:ext`.
Action to `Start impersonate` has been removed when using running with an external cluster.
```
▶ oc login -u clusteradmin -p "pasword" https://api.mytestserver.com:443
▶ npm run start:dev:ext
> odh-dashboard-frontend@0.1.0 start:dev:ext
> EXT_CLUSTER=true npm run start:dev
> odh-dashboard-frontend@0.1.0 start:dev
> webpack serve --hot --color --config ./config/webpack.dev.js
Prepping files...
SRC DIR: …
```
=> start webpack dev server with external cluster target

frontend/src/pages/distributedWorkloads/global/projectMetrics/GlobalDistributedWorkloadsProjectMetricsTab.tsx
As part of https://issues.redhat.com/browse/RHOAIENG-5293
removing logic that hides the "you might not have access to all of these projects" for admin, as `isAdmin` is not a cluster admin and doesn't mean they will have access to all projects.
ran locally, ran tests - still pass
none
help tooltip shows up for odh admins
=> chore(dw): requested resources always show tooltip

frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts, frontend/src/__tests__/cypress/cypress/pages/distributedWorkloads.ts, frontend/src/concepts/metrics/MetricsCommonContext.tsx, frontend/src/concepts/metrics/MetricsRefreshIntervalSelect.tsx, frontend/src/concepts/metrics/useRefreshIntervalBrowserStorage.ts
Closes [RHOAIENG-5290](https://issues.redhat.com/browse/RHOAIENG-5290)
* Adds a new `useRefreshIntervalBrowserStorage` hook to match the existing `useCurrentTimeframeBrowserStorage` which was moved from ModelServingMetricsContext in https://github.com/opendatahub-io/odh-dashboard/pull/2609
* Replaces the `useState` for refresh interval in `MetricsCommonContextProvider` with the new hook
* Adds a `toggleId` to the Select for refresh interval to support Cypress tests (the existing `data-testid` gets applied only to the menu that appears on click, we still needed some way to find the toggle button for opening the menu)
Tested by hand, made sure it's working as expected in both places MetricsCommonContext is used (Model Serving Metrics and Distributed Workload Metrics)
Added a Cypress test to …
=> MetricsCommonContext (DW and Model Serving): Persist refresh interval selection in browser sessionStorage

frontend/src/__tests__/cypress/cypress/e2e/home/homeResources.cy.ts, frontend/src/components/OdhDocCard.tsx, frontend/src/concepts/design/CollapsibleSection.tsx, frontend/src/concepts/design/ScrolledGallery.tsx, frontend/src/concepts/docResources/docUtils.ts, frontend/src/concepts/docResources/useDocResources.tsx, frontend/src/pages/home/Home.tsx, frontend/src/pages/home/resources/ResourcesLoading.tsx, frontend/src/pages/home/resources/useResourcesSection.tsx, frontend/src/pages/home/resources/useSpecifiedResources.tsx, frontend/src/pages/learningCenter/LearningCenter.tsx, frontend/src/pages/projects/screens/detail/overview/configuration/ConfigurationSection.tsx, frontend/src/types.ts
Closes: [RHOAIENG-5495](https://issues.redhat.com/browse/RHOAIENG-5495)
Adds a learning resource section to the landing page
Manually tested.
Added e2e tests
- [x ] Included any necessary screenshots or gifs if it was a UI change.
- [x ] Included tags to the UX team if it was a UI/UX change (find relevant UX in the [SMEs](https://github.com/opendatahub-io/odh-dashboard/tree/main/docs/smes.md) section).
/cc @jgiardino
=> [RHOAIENG-5495] Landing page: resources section

frontend/src/__mocks__/mockDWUsageByJobPrometheusResponse.ts, frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts, frontend/src/__tests__/cypress/cypress/pages/distributedWorkloads.ts, frontend/src/pages/distributedWorkloads/global/projectMetrics/GlobalDistributedWorkloadsProjectMetricsTab.tsx, frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/WorkloadResourceMetricsTable.tsx, frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/WorkloadResourceMetricsTableRow.tsx
Closes [RHOAIENG-5289](https://issues.redhat.com/browse/RHOAIENG-5289)
Previously in the workload resource metrics table, the resource usage bars would be shown only if a workload is in an active state (pending, admitted, or running) and otherwise the column would show a dash (-). In reality, when workloads are finished they don't release their resources right away, and there is still usage to show while the pods spin down. We did not have this "active state" condition for showing workloads in the other charts on the page, only in this table. However, we still don't want to show the empty resource bars after workloads are no longer using resources.
This change fixes the issue by adding an additional condition where the CPU or memory usage bar will appear if there is any continued usage of …
=> DW: Consistently show resource usage for finished workloads that are still spinning down

backend/src/routes/api/notebooks/utils.ts, backend/src/utils/notebookUtils.ts
https://issues.redhat.com/browse/RHOAIENG-6455
Merges in the volumeMounts, and the notebook container's volumes & envs to keep the cert information around instead of overriding it with the k8s patch logic.
Manually using the Jupyter tile.
Needs self signed cert stuff setup (cc @harshad16 for details)
1. Go to the Jupyter tile
2. Create a notebook - details do not matter (if you have one before this, delete it & the PVC)
3. Check the yaml on OpenShift Console (look for the `ca-bundle` references)
4. Stop Notebook
5. Create the notebook again
6. Check the yaml still has the `ca-bundle` references
None, backend only change.
/cc @harshad16
=> Jupyter tile, merge cert info from old notebook to avoid loss

frontend/src/__mocks__/mockDWUsageByOwnerPrometheusResponse.ts, frontend/src/__mocks__/mockWorkloadK8sResource.ts, frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts, frontend/src/api/prometheus/__tests__/distributedWorkloads.spec.ts, frontend/src/api/prometheus/distributedWorkloads.ts, frontend/src/concepts/distributedWorkloads/__tests__/utils.spec.ts, frontend/src/concepts/distributedWorkloads/utils.tsx, frontend/src/k8sTypes.ts
Cherry-picks https://github.com/opendatahub-io/odh-dashboard/pull/2754 to `v2.22.0-fixes` to close this blocking bug: https://issues.redhat.com/browse/RHOAIENG-6519
=> [v2.22.0] [RHOAIENG-6519] DW: Support workloads owned by either a RayCluster or a Job when querying CPU and Memory usage

frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelinesTopology.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/topology.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/PipelineDetailsYAML.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineTaskDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/SelectedTaskDrawerContent.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsCodeBlock.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsInputOutput.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsSection.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-3834
added additional test for pipeline detail page
npm run test
=> additional cypress test case for pipeline detail

frontend/src/__tests__/cypress/cypress/e2e/modelServing/ServingRuntimeList.cy.ts, frontend/src/concepts/areas/__tests__/utils.spec.ts, manifests/base/cluster-role.yaml
Closes https://issues.redhat.com/browse/RHOAIENG-6578 
Add permissions to fetch dsci by the dashboard serviceaccount and fixes a flaw in the area enablement util method that returned true if the dsci was missing.
1. Run the changes in a cluster with dsci but no permissions
2. Use `npm run start:dev:ext` to get the deployed dashboard serviceaccount capabilities
3. Check that the kserve auth feature should be disabled
4. Now add the permissions to the cluster (see bellow)
5. Check that the feature should be enabled
**Tested with npm run start:dev:ext which sholud mimic this same behavior**
=> Add dscinitializations resource to cluster-role.yaml and handle missing dsci status in ServingRuntimeList.cy.ts

frontend/src/__tests__/cypress/cypress/pages/pipelines/experiments.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineFilterBar.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunTable.ts, frontend/src/components/table/TableBase.tsx, frontend/src/concepts/pipelines/content/tables/PipelineFilterBar.tsx, frontend/src/concepts/pipelines/context/MlmdListContext.tsx, frontend/src/concepts/pipelines/context/index.ts, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactsList.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactsTable.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/GlobalArtifactsPage.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/constants.ts, frontend/src/pages/pipelines/global/experiments/artifacts/useGetArtifactsList.ts
Closes: [RHOAIENG-2977](https://issues.redhat.com/browse/RHOAIENG-2977)
Artifacts table, filter toolbar, pagination. 
(cc @yannnz)
**Filtering**
https://github.com/opendatahub-io/odh-dashboard/assets/96431149/53a04653-b833-49ec-94ec-70d7bcc666a1
**Pagination**
https://github.com/opendatahub-io/odh-dashboard/assets/96431149/a532700a-2edd-4288-a013-9731fc5eef89
Navigate to the Artifacts page from the left nav. Using a project with multiple artifacts, verify pagination, and toolbar filtering works as expected.
Cypress does not support intercepting `application/grpc-web+proto` content type requests.
=> [RHOAIENG-2977] Artifacts table

frontend/src/app/AppRoutes.tsx, frontend/src/concepts/pipelines/apiHooks/mlmd/useExecutionsFromMlmdContext.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/useGetExecutionsList.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/useExecutionsForPipelineRun.ts, frontend/src/concepts/pipelines/kfTypes.ts, frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.ts, frontend/src/pages/pipelines/GlobalPipelineExecutionsRoutes.tsx, frontend/src/pages/pipelines/global/experiments/executions/ExecutionsList.tsx, frontend/src/pages/pipelines/global/experiments/executions/ExecutionsTable.tsx, frontend/src/pages/pipelines/global/experiments/executions/ExecutionsTableRow.tsx, frontend/src/pages/pipelines/global/experiments/executions/ExecutionsTableRowStatusIcon.tsx, frontend/src/pages/pipelines/global/experiments/executions/ExecutionsTableToolbar.tsx, frontend/src/pages/pipelines/global/experiments/executions/GlobalExecutions.tsx, frontend/src/pages/pipelines/global/experiments/executions/columns.ts, frontend/src/pages/pipelines/global/experiments/executions/const.ts, frontend/src/routes/pipelines/executions.ts, frontend/src/routes/pipelines/index.ts, frontend/src/utilities/NavData.tsx
JIRA:
[RHOAIENG-4776](https://issues.redhat.com/browse/RHOAIENG-4776)
[RHOAIENG-4777](https://issues.redhat.com/browse/RHOAIENG-4777)
Empty state:
Executions table:
1. Go to the executions page under Experiment navigation
2. Check the list
3. Check the paging and filtering
N/A
=> Executions empty state and table

frontend/src/__mocks__/mockDashboardConfig.ts, frontend/src/__tests__/cypress/cypress/e2e/home/home.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/home/homeResources.cy.ts, frontend/src/pages/home/Home.tsx, frontend/src/pages/home/HomeHint.tsx, frontend/src/pages/home/projects/EmptyProjectsCard.tsx, frontend/src/pages/home/resources/useResourcesSection.tsx
Closes: [RHOAIENG-5496](https://issues.redhat.com/browse/RHOAIENG-5496)
Adds a hint to the landing page directing users how to find the previous landing page
Tested locally
Added e2e tests
/cc @jgiardino
=> [RHOAIENG-5496] Landing page: New home page hint

frontend/src/__tests__/cypress/cypress/e2e/applications/enabled.cy.ts, frontend/src/__tests__/cypress/cypress/pages/components/Card.ts, frontend/src/components/OdhAppCard.tsx
Fixes: [RHOAIENG-6606](https://issues.redhat.com/browse/RHOAIENG-6606)
Update the link URL for the Jupyter card Launch application link to not be a relative path.
Tested with the home page disabled and enabled.
Added an e2e test to check the launch application link with and without the home page feature enabled.
=> [RHOAIENG-6606] Correctly nav to application from Jupyter card

frontend/src/__tests__/cypress/cypress/e2e/home/home.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/home/homeAIFlows.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/home/homeAdmin.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/home/homeProjects.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/home/homeResources.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/home/homeUtils.ts, frontend/src/__tests__/cypress/cypress/pages/home.ts, frontend/src/concepts/design/CollapsibleSection.tsx, frontend/src/concepts/design/InfoGalleryItem.tsx, frontend/src/pages/home/aiFlows/CreateAndTrainGallery.tsx, frontend/src/pages/home/aiFlows/DeployAndMonitorGallery.tsx, frontend/src/pages/home/aiFlows/ProjectsGallery.tsx, frontend/src/pages/home/useEnableTeamSection.tsx, frontend/src/pages/projects/screens/detail/overview/configuration/ConfigurationSection.tsx
Closes: [RHOAIENG-6321](https://issues.redhat.com/browse/RHOAIENG-6321)
Content update for the informational section of the landing page
Added e2e test to verify the content is adjusted based on feature availability.
/cc @jgiardino
=> [RHOAIENG-6321] Home Page Microcopy Updates

frontend/src/components/DashboardDescriptionListGroup.scss, frontend/src/components/DashboardDescriptionListGroup.tsx, frontend/src/components/EditableLabelsDescriptionListGroup.tsx, frontend/src/components/EditableTextDescriptionListGroup.tsx, frontend/src/pages/modelRegistry/ModelRegistryRoutes.tsx, frontend/src/pages/modelRegistry/screens/GlobalModelVersionsTabs.tsx, frontend/src/pages/modelRegistry/screens/ModelDetailsView.tsx, frontend/src/pages/modelRegistry/screens/ModelTimestamp.tsx, frontend/src/pages/modelRegistry/screens/ModelVersions.tsx, frontend/src/pages/modelRegistry/screens/ModelVersionsTableRow.tsx, frontend/src/pages/modelRegistry/screens/RegisteredModelLink.tsx, frontend/src/pages/modelRegistry/screens/RegisteredModelTableRow.tsx, frontend/src/pages/modelRegistry/screens/useRegisteredModelUrl.ts
Part of [RHOAIENG-2235](https://issues.redhat.com/browse/RHOAIENG-2235)
Implements most of the "Details" tab of the registered model page. Note that the "Properties" section is not functional and will be implemented in a followup PR. Also note that while the Description and Labels sections have editable functionality implemented, the actual last step of persisting the edits to the API is a stub promise that simply waits 2 seconds in order to show the "saving" state (edits are not allowed while saving). Implementing the real API patch requests will be in a separate PR.
Model details tab:
Description field in edit mode:
Description field disabled while saving (currently a stub 2-second-delay promise):
Labels in edit mode:
Editing an existing label:
Add label modal:
Label editing disabled …
=> Model Registry: Initial content of model details tab with stub editable fields and tab navigation handling

frontend/src/__mocks__/mockNotebookK8sResource.ts, frontend/src/__tests__/cypress/cypress/e2e/applications/NotebookServer.cy.ts, frontend/src/__tests__/cypress/cypress/pages/notebookServer.ts, frontend/src/__tests__/cypress/cypress/support/commands/odh.ts, frontend/src/pages/notebookController/screens/server/NotebookServer.tsx, frontend/src/pages/notebookController/screens/server/StartServerModal.tsx, frontend/src/pages/notebookController/screens/server/StopServerModal.tsx
Closes: [RHOAIENG-3918](https://issues.redhat.com/browse/RHOAIENG-3918)
This PR aims to add cypress test for Notebook server tab.
`npm run test`
=> Create cypress test for Notebook server tab

frontend/package-lock.json, frontend/package.json, frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRunJob/PipelineRunJobDetails.tsx, frontend/src/concepts/pipelines/topology/pipelineTaskTypes.ts, frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.ts, frontend/src/concepts/topology/NodeStatusIcon.tsx, frontend/src/concepts/topology/PipelineDefaultTaskGroup.tsx, frontend/src/concepts/topology/PipelineVisualizationSurface.tsx, frontend/src/concepts/topology/const.ts, frontend/src/concepts/topology/customNodes/ArtifactTaskNode.tsx, frontend/src/concepts/topology/customNodes/StandardTaskNode.tsx, frontend/src/concepts/topology/factories.ts, frontend/src/concepts/topology/types.ts, frontend/src/concepts/topology/useTopologyController.ts, frontend/src/concepts/topology/utils.ts
Closes https://issues.redhat.com/browse/RHOAIENG-3977
Adds support for groups rendering, selectable, and collapsible groups in Pipelines and Runs Topology view. 
Tested groups layout, rendering subtasks, and expandable/collapsible functionality in UI. 
Tests will be added in a PR for https://issues.redhat.com/browse/RHOAIENG-5146
=> Pipelines Topology: Support Groups

frontend/src/__tests__/cypress/cypress/e2e/pipelines/Pipelines.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesGlobal.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesTable.ts, frontend/src/components/PasswordHiddenText.tsx, frontend/src/concepts/pipelines/content/PipelineServerActions.tsx, frontend/src/concepts/pipelines/content/ViewPipelineServerModal.tsx, frontend/src/concepts/pipelines/content/configurePipelinesServer/ObjectStorageSection.tsx, frontend/src/concepts/pipelines/content/configurePipelinesServer/PipelineDropdown.tsx, frontend/src/concepts/pipelines/content/configurePipelinesServer/PipelinesDatabaseSection.tsx
Closes: [RHOAIENG-3820](https://issues.redhat.com/browse/RHOAIENG-3820)
This PR aims to add additional cypress test to global pipeline page. That includes:
- Configure pipeline server
-  delete pipeline server
- view pipeline configuration
- table sorting, filtering.
`npm run test`
=> Update global pipelines cypress test

frontend/src/concepts/pipelines/apiHooks/mlmd/types.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/useGetArtifactTypes.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/useGetEventsByExecutionId.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/useGetExecutionById.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/useGetLinkedArtifactsByEvents.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/useGetMlmdContextByExecution.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/useGetMlmdContextType.ts, frontend/src/pages/pipelines/GlobalPipelineExecutionsRoutes.tsx, frontend/src/pages/pipelines/global/experiments/executions/ExecutionStatus.tsx, frontend/src/pages/pipelines/global/experiments/executions/ExecutionsTableRow.tsx, frontend/src/pages/pipelines/global/experiments/executions/const.ts, frontend/src/pages/pipelines/global/experiments/executions/details/ExecutionDetails.tsx, frontend/src/pages/pipelines/global/experiments/executions/details/ExecutionDetailsCustomPropertiesSection.tsx, frontend/src/pages/pipelines/global/experiments/executions/details/ExecutionDetailsIDSection.tsx, frontend/src/pages/pipelines/global/experiments/executions/details/ExecutionDetailsInputOutputSection.tsx, frontend/src/pages/pipelines/global/experiments/executions/details/ExecutionDetailsPropertiesSection.tsx, frontend/src/pages/pipelines/global/experiments/executions/details/ExecutionDetailsPropertiesValue.tsx, frontend/src/pages/pipelines/global/experiments/executions/details/ExecutionDetailsReferenceSection.tsx, frontend/src/pages/pipelines/global/experiments/executions/utils.ts, frontend/src/routes/pipelines/executions.ts, frontend/src/typeHelpers.ts
JIRA: https://issues.redhat.com/browse/RHOAIENG-4778
Add details page for the executions
1. Go to the executions table
2. Click on the execution name
3. Check the details page, make sure the sections are accurate, you can compare it with the KF UI
N/A
=> Add execution details page

frontend/src/components/MaxHeightCodeEditor.tsx, frontend/src/components/NoValue.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/utils.tsx, frontend/src/concepts/pipelines/context/usePipelinesUiRoute.ts, frontend/src/pages/pipelines/GlobalArtifactsRoutes.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/ArtifactDetails.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/ArtifactOverviewDetails.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/ArtifactPropertyDescriptionList.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/index.ts, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactUriLink.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactsTable.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/__tests__/ArtifactDetails.spec.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/__tests__/ArtifactsTable.spec.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/constants.ts, frontend/src/pages/pipelines/global/experiments/artifacts/useGetArtifactById.ts, frontend/src/pages/pipelines/global/experiments/artifacts/utils.ts, frontend/src/pages/pipelines/global/experiments/executions/details/ExecutionDetailsInputOutputSection.tsx, frontend/src/pages/pipelines/global/experiments/executions/details/ExecutionDetailsPropertiesValue.tsx, frontend/src/routes/pipelines/artifacts.ts
Closes: [RHOAIENG-2987](https://issues.redhat.com/browse/RHOAIENG-2987)
Details page for artifacts accessed by clicking the table, then clicking on the name of the artifact. The page only renders the Overview tab and its data. The JIRA asked for an empty state for Lineage explorer, but since there is no design screen showing what that might look like, I've just disabled the tab for now. 
Added unit tests that verifies data being rendered on the page since Cypress does not support intercepting application/grpc-web+proto content type requests.
I've also added a simple unit test for the artifacts list table which mocks and renders some data.
Navigate to the artifacts table from the left nav, click on an artifact name, verify you're routed to the details page, verify the visual matches the …
=> [RHOAIENG-2987] Artifacts - Details Page

frontend/src/pages/pipelines/global/experiments/artifacts/__tests__/ArtifactsTable.spec.tsx
Relates to: [RHOAIENG-2977](https://issues.redhat.com/browse/RHOAIENG-2977)
Fixing Artifacts table unit test to always the use current date to compare against.
=> Fix unit test date - Artifacts table

manifests/overlays/odhdashboardconfig/odhdashboardconfig.yaml
Closes: [RHOAIENG-6880](https://issues.redhat.com/browse/RHOAIENG-6880)
The `disableHome` flag was inadvertently set to false for the RHOAI `odhDashbardConfig` spec.
On the nightly build of a RHOAI deployment, verify the home page is not show and the initial page is the enabled application page.
=> [RHOAIENG-6880] Disable homePage feature flag for RHOAI deployments

frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelinesTopology.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/topology.ts
Closes: [RHOAIENG-4729](https://issues.redhat.com/browse/RHOAIENG-4729)
This PR validates that pipelineRun details right drawer (Input/output, details) have tabs with data, and that the bottom drawer (run output) has tabs with data. Action drop down tests covered in separate PR [2746](https://github.com/opendatahub-io/odh-dashboard/pull/2746)
`npm run test`
=> Update PipelineRun details test

frontend/config/webpack.dev.js
https://issues.redhat.com/browse/RHOAIENG-6597
When using `npm run start:dev:ext`, it was not possible to target an external cluster running RHOAI.
This change simply adds support for the `ODH_APP` env variable which can be supplied in the `.env.local` file. The default value remains `odh-dashbaord` but can be overridden to `rhods-dashboard`.
Update `.env.local` to include:
```
OC_PROJECT=redhat-ods-applications
ODH_APP=rhods-dashboard
```
`oc login ...` to your cluster running RHOAI (use a cluster admin)
`npm run start:dev:ext`
Visit `http://localhost:4010` to check the UI is running as expected.
=> add env var to support rhods-dashboard for dev:start:ext

frontend/package-lock.json, frontend/package.json, frontend/src/concepts/pipelines/topology/__tests__/mockPipelineSpec.ts, frontend/src/concepts/pipelines/topology/__tests__/usePipelineTaskTopology.spec.ts, frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.tsx, frontend/src/concepts/topology/PipelineDefaultTaskGroup.tsx, frontend/src/concepts/topology/PipelineVisualizationSurface.tsx, frontend/src/concepts/topology/customNodes/ArtifactTaskNode.tsx, frontend/src/concepts/topology/useTopologyController.ts
Closes: [RHOAIENG-6647](https://issues.redhat.com/browse/RHOAIENG-6647)
Artifacts with the same name created by different tasks were being thrown out due to duplicate IDs. Update the generation of the artifact nodes to create a unique ID for the artifact based on its parent task's ID.
Update the version of [@patternfly/react-topology](https://github.com/patternfly/react-topology) to [5.4.0-prerelease.1](https://github.com/patternfly/react-topology/compare/prerelease-v5.4.0-prerelease.0...prerelease-v5.4.0-prerelease.1) to pickup a fix for correct placement of spacer nodes.
Verified locally that the artifact nodes show up correctly with the correct dependencies.
Added a test for `usePipelineTaskTopology` to verify the correct number of nodes are returned.
=> [RHOAIENG-6647] Fix to show all artifacts in pipeline topology view

frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelMetrics.cy.ts, frontend/src/__tests__/cypress/cypress/support/commands/odh.ts, frontend/src/api/trustyai/custom.ts, frontend/src/concepts/trustyai/useTrustyAIAPIState.ts
Closes: [RHOAIENG-6620](https://issues.redhat.com//browse/RHOAIENG-6620)
Updates trusty ai API client to filter only for bias metrics when querying for the list of all Bias Metric Configs.
Prerequisites:
* Deploy on a cluster with the following TrustyAI section in your DSC:
```
trustyai:
devFlags:
manifests:
- contextDir: config
sourcePath: ''
uri: 'https://github.com/ruivieira/trustyai-service-operator/tarball/RHOAIENG-6622-dev'
```
* Create a new project, enable trustyai and deploy demo models.
* Train demo models and hit them with real world data
* Create a few Bias Metric Configs
* Create an Identity metric via the CLI
Testing:
* Visit the bias metrics page, make sure the charts all work
* Goto the configure screen
* Verify in the network tab of your browser that the call to endpoint: …
=> Update TrustyAI APIs to use new endpoint (RHOAINENG-6620)

frontend/config/webpack.dev.js, manifests/base/deployment.yaml, manifests/overlays/rhoai/deployment.yaml
https://issues.redhat.com/browse/RHOAIENG-6479
The oauth-proxy `openshift-delegate-urls` option grants access to the underlying service via `Authorization: Bearer` header. The current access check is restricted to users with access to the namespace in which the dashboard is deployed. This limits access to privileged users and restricts other users, such as self-provisioners.
When running a local frontend dev server, developers want to target external clusters and test with users of varying access. Currently this method of development only works for cluster admin users. The change in this PR will loosen the access check so that any user with the ability to list projects can get through.
Apply the deployment changes for the oauth-proxy configuration.
Create a self-provisioner user on the …
=> update oauth-proxy openshift-delegate-urls

.github/workflows/test.yml
Code coverage results need to be uploaded for `main`. A github workflow is required to upload the coverage results for `main` when code is pushed to the `main` branch. The current workflow is only running for `pull_requests`. As such there is no "base report" uploaded to codecov for PRs to create a comparison to.
=> update coverage on push and pull_request

backend/src/__tests__/objUtils.spec.ts, backend/src/types.ts, backend/src/utils/notebookUtils.ts, backend/src/utils/objUtils.ts
https://issues.redhat.com/browse/RHOAIENG-7070
Improves the merging of env values provided as part of the Jupyter Tile.
1. Don't have a Jupyter Tile Notebook
* delete Notebook, PVC, and configmap under your name
* Find the namespace these are in by checking the OdhDashboardConfig -- if a notebookNamespace is set, go there, if not it's in the Dashboard's namespace
3. Create a Jupyter Tile Notebook
4. Stop the Notebook after it creates (this flow is not part of this fix)
5. Add an env var and start the Notebook again
It failed after the 2nd start (no4 above) with an error in the modal -- if it continues to deploy, the fix is successful.
Wrote tests for the customizer function used in lodash `mergeWith` …
=> Merge smarter jupyter values

frontend/src/__mocks__/mockRegisteredModelsList.ts, frontend/src/components/DashboardDescriptionListGroup.tsx, frontend/src/components/EditableLabelsDescriptionListGroup.tsx, frontend/src/components/EditableTextDescriptionListGroup.tsx, frontend/src/concepts/modelRegistry/types.ts, frontend/src/pages/modelRegistry/screens/GlobalModelVersionsTabs.tsx, frontend/src/pages/modelRegistry/screens/ModelDetailsView.tsx, frontend/src/pages/modelRegistry/screens/ModelPropertiesDescriptionListGroup.tsx, frontend/src/pages/modelRegistry/screens/ModelPropertiesTableRow.tsx, frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetails.tsx, frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsTabs.tsx, frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx, frontend/src/pages/modelRegistry/screens/ModelVersions.tsx, frontend/src/pages/modelRegistry/screens/__tests__/utils.spec.ts, frontend/src/pages/modelRegistry/screens/utils.ts, frontend/src/pages/projects/types.ts, frontend/src/types.ts
Closes [RHOAIENG-2235](https://issues.redhat.com/browse/RHOAIENG-2235) and [RHOAIENG-2238](https://issues.redhat.com/browse/RHOAIENG-2238)
Followup to https://github.com/opendatahub-io/odh-dashboard/pull/2760
* Implements the contents of the Properties section using a new `ModelPropertiesDescriptionListGroup` component which provides view/add/edit/delete controls
* Implements API patch requests when saving edits to Description, Labels and Properties (replacing the stub Promise for the former two)
* Adds input validation to ensure labels and property keys are unique. See **"Input validation screencaps"** below.
* None of these components/utils are specific to `RegisteredModel`, they work with `ModelRegistryCustomProperties` objects and generic `T extends ModelRegistryBase` objects, so it …
=> Model Details and Model Version Details: add editable properties section, set up API patches for description, labels and properties

frontend/src/__mocks__/mockModelVersion.ts, frontend/src/__mocks__/mockModelVersionList.ts, frontend/src/__tests__/cypress/cypress/e2e/modelRegistry/ModelRegistry.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/modelRegistry/ModelVersions.cy.ts, frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts, frontend/src/__tests__/cypress/cypress/support/commands/odh.ts, frontend/src/pages/modelRegistry/screens/EmptyModelRegistryState.tsx, frontend/src/pages/modelRegistry/screens/ModelRegistry.tsx, frontend/src/pages/modelRegistry/screens/ModelVersionListView.tsx, frontend/src/pages/modelRegistry/screens/ModelVersions.tsx, frontend/src/pages/modelRegistry/screens/ModelVersionsHeaderActions.tsx, frontend/src/pages/modelRegistry/screens/ModelVersionsTableRow.tsx
Tests for https://issues.redhat.com/browse/RHOAIENG-2236
https://issues.redhat.com/browse/RHOAIENG-2237
https://issues.redhat.com/browse/RHOAIENG-2234
- Added e2e tests for model versions empty state and model versions table
- Fixed Actions button from Split button to normal dropdown according to mocks 
- The chip key values now reflects owner instead of just keyword
- Fixed the `app-page-title` along with tests for the same.
Run Cypress test -`ModelRegistry.cy.ts`
=> Tests for model versions table and empty state

frontend/src/__tests__/cypress/cypress/e2e/applications/NotebookServer.cy.ts, frontend/src/__tests__/cypress/cypress/pages/notebookServer.ts, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
Closes: [RHOAIENG-7073](https://issues.redhat.com/browse/RHOAIENG-7073)
Cancel on the spawner page sends the user to `/` which, when the home page is enabled, is incorrect. It should send the user to '/enabled' when the home page is enabled.
Tested locally and added an e2e test.
Should test cancel from the spawner page with and without the home page enabled.
=> [RHOAIENG-7073] Fix for cancel on spawn a notebook server page

frontend/src/pages/modelRegistry/ModelRegistryRoutes.tsx, frontend/src/pages/modelRegistry/screens/EmptyModelRegistryState.tsx, frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsTabs.tsx, frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionRegisteredDeploymentsView.tsx
initial progress towards https://issues.redhat.com/browse/RHOAIENG-6636
includes setting up the tab, routes, and the component with the empty state
na, just setting up a skeleton with empty state for now
none
can access tab with route and see empty state
=> feat(mr): routes etc and empty state for registered deployments

.codecov.yml
https://issues.redhat.com/browse/RHOAIENG-5313
Force codecov status checks to be informational only so that they will always succeed.
Turns out that the default behavior of codecov without thresholds is causing PR checks to fail.
=> update codecov status checks to informational

frontend/src/concepts/pipelines/kfTypes.ts, frontend/src/concepts/pipelines/topology/__tests__/parseUtils.spec.ts, frontend/src/concepts/pipelines/topology/__tests__/usePipelineTaskTopology.spec.ts, frontend/src/concepts/pipelines/topology/parseUtils.ts, frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.tsx
Resolves:
[RHOAIENG-6319](https://issues.redhat.com/browse/RHOAIENG-6319)
[RHOAIENG-6572](https://issues.redhat.com/browse/RHOAIENG-6572)
[RHOAIENG-6671](https://issues.redhat.com/browse/RHOAIENG-6671)
This PR is resolving several issues when rendering the pipeline topology. Now it can find all the edges and nodes correctly. More details will be explained in the comments below.
Compare the topology with the KF UI to see if it renders the same, and make sure there are no missing nodes and edges for any pipelines.
Updated some jest test cases.
=> Render pipeline topology correctly, add missing nodes

frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineRuns.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/Pipelines.cy.ts
Closes: [RHOAIENG-5117](https://issues.redhat.com/browse/RHOAIENG-5117)
follow up to https://github.com/opendatahub-io/odh-dashboard/pull/2745
This PR to add pagination to pipeline and pipeline run tables.
`npm run test`
=> Cypress test for pipeline pagination

docs/dashboard-config.md, frontend/src/__tests__/cypress/cypress/e2e/projects/__intercept__/project-list.snap.json, frontend/src/concepts/areas/types.ts
Removes a few orphaned references to the removed `modelMetricsNamespace` flag.
=> Remove last remaining traces of modelMetricsNamespace flag

frontend/src/concepts/pipelines/apiHooks/mlmd/useArtifactsFromMlmdContext.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/useGetArtifactsList.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/useGetEventsByExecutionId.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightContent.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/ArtifactNodeDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/ArtifactNodeDrawerContent.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/index.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/usePipelineRunArtifacts.tsx, frontend/src/concepts/pipelines/topology/pipelineTaskTypes.ts, frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.tsx
Starts: [RHOAIENG-2989](https://issues.redhat.com/browse/RHOAIENG-2989)
Fetches the artifact context for the run, now displaying those MLMD artifact details. Virtualization will be a follow-up PR.
(cc yannnz)
Will include tests in follow-up PR if applicable.
=> [RHOAIENG-2989] artifact node drawer details section

backend/src/routes/api/modelRegistries/index.ts, backend/src/routes/api/service/modelregistry/index.ts, backend/src/types.ts, backend/src/utils/constants.ts, frontend/src/services/modelRegistryService.ts, manifests/base/cluster-role.yaml
Closes https://issues.redhat.com/browse/RHOAIENG-7058
Adds the following admin-only backend API routes:
* `GET /api/modelRegistries` - lists ModelRegistries
* `POST /api/modelRegistries` - creates a ModelRegistry
* `GET /api/modelRegistries/:modelRegistryName` - gets a ModelRegistry
* `PATCH /api/modelRegistries/:modelRegistryName` - updates a ModelRegistry
* `DELETE /api/modelRegistries/:modelRegistryName` - deletes a ModelRegistry 
And adds the new `frontend/src/services/modelRegistryService.ts` with functions to call these routes using axios.
Also adds a new constant `MODEL_REGISTRY_NAMESPACE` to `backend/src/utils/constants.ts` since there are some places where we were hard-coding the use of the `odh-model-registries` namespace.
The admin page where this will be used does not exist …
=> Add backend routes and frontend service for admin CRUD of ModelRegistries

backend/src/types.ts, backend/src/utils/constants.ts, docs/dashboard-config.md, frontend/src/__mocks__/mockDashboardConfig.ts, frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelServingGlobal.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/projects/projectDetails.cy.ts, frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/__tests__/cypress/cypress/pages/projects.ts, frontend/src/concepts/areas/const.ts, frontend/src/concepts/areas/types.ts, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/metrics/GlobalModelMetricsPage.tsx, frontend/src/pages/modelServing/screens/metrics/MetricsPage.tsx, frontend/src/pages/modelServing/screens/metrics/MetricsPageTabs.tsx, frontend/src/pages/modelServing/screens/metrics/performance/PerformanceTab.tsx, frontend/src/pages/modelServing/screens/projects/ProjectModelMetricsPage.tsx, frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelCard.tsx, manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml, manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml, manifests/overlays/odhdashboardconfig/odhdashboardconfig.yaml
Closes: [RHOAIENG-6985](https://issues.redhat.com/browse/RHOAIENG-6985)
Initial creation fo the kserve metric feature, disabled by default. Includes a simple `Coming soon` page.
Tested locally and added e2e tests
Verify that the user can navigate to the kserve metrics page from the model list view by clicking on the model name ONLY if the feature flag is enabled.
=> [RHOAIENG-6985] Create kserve metrics feature flag

frontend/package-lock.json, frontend/package.json, frontend/src/__tests__/unit/jest.setup.ts, frontend/src/concepts/pipelines/content/artifacts/charts/ROCCurve.tsx, frontend/src/concepts/pipelines/content/artifacts/charts/confusionMatrix/ConfusionMatrix.scss, frontend/src/concepts/pipelines/content/artifacts/charts/confusionMatrix/ConfusionMatrix.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/__tests__/PipelineRunDrawerRightContent.spec.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/ArtifactNodeDrawerContent.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/ArtifactVisualization.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/__tests__/ArtifactNodeDrawerContent.spec.tsx, frontend/src/pages/pipelines/global/experiments/MlmdPropertyValue.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/ArtifactPropertyDescriptionList.tsx
Closes: [RHOAIENG-2989](https://issues.redhat.com/browse/RHOAIENG-2989)
Added visualization content (ROC curve, scalar metrics table, confusion matrix) for run artifact node drawers.
NOTE: Since we have yet to setup requests to allow for HTML and Markdown visualization data, those artifact types have placeholder text in the drawer content space for now.
Create and/or navigate to a run that has artifact nodes of type `system.Metrics` and `system.ClassificationMetrics` (confusion matrix and ROC curves fit under this category), click on those respective topology graph nodes, and within the drawer for each, click the "Visualization" tab and verify the content is correct. 
**Scalar metrics:**
**ROC curve:**
**Confusion matrix:**
(@yannnz) …
=> [RHOAIENG-2989] artifact node drawer visualization

frontend/src/__mocks__/mockPipelineVersionsProxy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineCreateRuns.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/Pipelines.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelinesList.cy.ts, frontend/src/__tests__/cypress/cypress/pages/components/table.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesTable.ts, frontend/src/components/table/TableRowTitleDescription.tsx, frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableRow.tsx, frontend/src/concepts/pipelines/content/tables/pipelineVersion/PipelineVersionTable.tsx, frontend/src/concepts/pipelines/content/tables/pipelineVersion/PipelineVersionTableRow.tsx, frontend/src/concepts/pipelines/content/tables/pipelineVersion/usePipelineVersionsCheckboxTable.ts
JIRA: https://issues.redhat.com/browse/RHOAIENG-7077
It's a one-liner fix, we read the wrong property in the object of a pipeline version to select the checkbox.
However, I updated a lot of the pipeline cypress test to make it make more sense. Thanks for the help of @christianvogt 
1. Verify the multi-selection is working on the pipeline versions table
2. Verify the batch deletion of pipeline version works
Updated the cypress test.
=> Fix pipeline version multi-select issue

frontend/src/__mocks__/mockGoogleRpcStatusKF.ts, frontend/src/__tests__/cypress/cypress/e2e/modelRegistry/ModelRegistry.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/modelRegistry/ModelVersionDetails.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/modelRegistry/ModelVersions.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/CompareRuns.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/Experiments.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/ManageRuns.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineCreateRuns.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineDeleteRuns.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineRuns.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/Pipelines.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelinesList.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelinesTopology.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/cloneRunPage.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/createRunPage.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/experiments.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineFilterBar.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineImportModal.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunTable.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineVersionImportModal.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesTable.ts, frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-5329
continuation for updating interceptOdh for pipeline intercepts
npm run test
=> added core interceptor for pipeline

frontend/src/concepts/pipelines/topology/__tests__/parseUtils.spec.ts, frontend/src/concepts/pipelines/topology/parseUtils.ts, frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.tsx
closes: https://issues.redhat.com/browse/RHOAIENG-7079
- run details now uses the task name first to match an execution to a task in the dag
- if no name exists, we fall back to using the key to match the execution
- and if nothing exists at all in terms of matching an execution, we fall back to the pipeline spec
- check that logs are equal from our UI to KF
none, small mlmd fix in for backend
=> add taskName parameter to parseRuntimeInfoFromExecutions function

frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/__tests__/PipelineRunDrawerRightContent.spec.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/ArtifactNodeDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/__tests__/ArtifactNodeDrawerContent.spec.tsx
Closes: [RHOAIENG-7421](https://issues.redhat.com/browse/RHOAIENG-7421)
Just rendering the string of the artifact name instead of the link which takes users to the new artifact details page behind the experiments feature flag.
=> [RHOAIENG-7421] pipeline run artifact detail drawer link to artifact details not behind flag

frontend/src/pages/home/projects/ProjectCard.tsx, frontend/src/pages/home/useEnableTeamSection.tsx, frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx, frontend/src/pages/projects/screens/projects/NewProjectButton.tsx
This adds tracking for the new home page. As part of this, trackign of the new project
button has moved from the NewProjectButton to the ManageProjectsModal.
[RHOAIENG-6314] 
By hand and by watching the browser console.
Functionality of the UI has not changed.
=> [RHOAIENG-6314] Add tracking for new Homepage.

frontend/src/concepts/pipelines/apiHooks/useAllPipelineVersions.ts, frontend/src/concepts/pipelines/apiHooks/usePipelines.ts
Closes: [RHOAIENG-7439](https://issues.redhat.com/browse/RHOAIENG-7439)
Fetch all pages of pipelines whose IDs are used to fetch all versions, used to display versions in the table cells for runs and for the toolbar version filter dropdown.
=> [RHOAIENG-7439] Pipeline version is not visible for some runs in the run table list

frontend/src/pages/home/aiFlows/ProjectsGallery.tsx, frontend/src/pages/home/projects/ProjectsSection.tsx, frontend/src/pages/home/projects/ProjectsSectionHeader.tsx, frontend/src/pages/home/useEnableTeamSection.tsx
Closes: [RHOAIENG-7483](https://issues.redhat.com/browse/RHOAIENG-7483)
Updates the microcopy of the home page:
- Update the text of the `Serving runtimes` card
- Update the text for the `User management` card
- Update the references to the projects section from `Projects` to `Data Science Projects`
Manually
No test impact, textual changes only.
/cc @jgiardino
=> [RHOAIENG-7483] Home page microcopy updates based on PM feedback

frontend/src/concepts/pipelines/content/tables/pipelineRun/usePipelineRunTable.ts, frontend/src/concepts/pipelines/content/tables/pipelineRunJob/usePipelineRunJobTable.ts, frontend/src/concepts/pipelines/content/tables/usePipelineTable.ts, frontend/src/pages/pipelines/global/runs/ScheduledRuns.tsx
Closes: [RHOAIENG-7499](https://issues.redhat.com/browse/RHOAIENG-7499)
Now filtering run schedules by experiment ID when an experiment ID exists in the URL.
=> [RHOAIENG-7499] Scheduled pipeline run tab under an experiment are not filtered by experiment

frontend/src/__mocks__/mockImageStreamK8sResource.ts, frontend/src/__tests__/cypress/cypress/e2e/projects/projectDetails.cy.ts, frontend/src/pages/projects/screens/detail/notebooks/__tests__/useNotebookImageData.spec.ts, frontend/src/pages/projects/screens/detail/notebooks/useNotebookImageData.ts
Closes https://issues.redhat.com/browse/RHOAIENG-5414
Fix an issue with the new implementation of https://issues.redhat.com/browse/RHOAIENG-5264 to make sure we render the correct Image Stream selection
Before:
After:
1. Get the latest version of the notebook controller (see instructions [here](https://issues.redhat.com/browse/RHOAIENG-5264))
2. Deploy a model
3. Check the image selected is correct
Currently no coverage in the fix, will follow up with test coverage of the function.
=> Internal Image Registry Dependency Removal support

frontend/jest.config.js
Closes https://issues.redhat.com/browse/RHOAIENG-5244
Slightly tweaks the Jest configuration to transform all PF packages rather than only react-icons at the top level of node_modules.
The current configuration somewhat recently caused a very difficult to debug issue during PatternFly release testing for our 5.3 release, and this issue is likely to reoccur in the future which could cause significant delays in updating the version of PatternFly used by odh-dashboard in an emergency situation.
This change resolved the issue as discovered during the PF 5.3 release testing and passes your automated tests locally when I ran them.
This change will cause all PF packages to be transformed during test running if needed. The current tests passing verifies that things are still working properly. …
=> [RHOAIENG-5244] Adjust jest config to transform all PatternFly packages

frontend/src/components/error/ErrorBoundary.tsx, frontend/src/components/error/ErrorDetails.tsx, frontend/src/components/error/UpdateState.tsx, frontend/src/components/error/__tests__/ErrorBoundary.spec.tsx
https://issues.redhat.com/browse/RHOAIENG-2690
_@ UX please suggest icon and text_
The times in which this screen may be shown is very very small. A possible way to encounter this issue in production is to have the web app opened while the dashboard updates behind the scene. Then the user attempts to navigate the already opened application.
A `ChunkLoadError` is a special case that indicates a failure to load a build artifact. This generally occurs because the web page was opened on a previous version of the application and the build artifacts have changed on the server. It _may_ also occur as a result of cache not getting the latest version although this case hasn't been proven in our environment where it's expected that we do not cache such files.
Whenever a `ChunkLoadError` is …
=> show special error state for ChunkLoadError

frontend/.eslintrc, frontend/src/__tests__/cypress/cypress.config.ts, frontend/src/__tests__/cypress/cypress/pages/administration.ts, frontend/src/components/OdhExploreCardTypeBadge.tsx, frontend/src/concepts/pipelines/content/InvalidArgoDeploymentAlert.tsx, frontend/src/pages/notebookController/screens/admin/NotebookAdminControl.tsx
[RHOAIENG-7531](https://issues.redhat.com/browse/RHOAIENG-7531)
I added 2 eslint rules to flag hard coded product name (e.g. Red Hat Openshift AI or Open Data Hub) usage instead of variable. These should instead reference variable name `ODH_PRODUCT_NAME` so that it could be replaced by the environment variable that was configured.
I ran `npm run test:lint` to run the rule checker. I also run `npm run test` to see if tests were playing well with the code changes.
Steps to reproduce code changes:
**Notebook Admin Control**
- Go to Applications > Enabled
- Click the default Jupyter application and press `Launch application`
- Navigate to the `Administration` tab. You should see the product name there.
**Odh Explore Card**
- If not done yet, create a Self-managed application.
- Go to …
=> [RHOAIENG-7531] eslint rule to flag hard coded product name usage instead of variable

backend/src/utils/route-security.ts, frontend/src/__tests__/cypress/cypress/e2e/modelRegistrySettings/ModelRegistrySettings.cy.ts, frontend/src/__tests__/cypress/cypress/pages/modelRegistrySettings.ts, frontend/src/api/index.ts, frontend/src/components/FieldList.tsx, frontend/src/components/PasswordInput.tsx, frontend/src/k8sTypes.ts, frontend/src/pages/modelRegistrySettings/CreateModal.scss, frontend/src/pages/modelRegistrySettings/CreateModal.tsx, frontend/src/pages/modelRegistrySettings/ModelRegistrySettings.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/GenericKeyValuePairField.tsx
Closes: [RHOAIENG-2230](https://issues.redhat.com/browse/RHOAIENG-2230)
Create MR form/modal
Created an MR, checked form cannot be submitted if form validations exist.
- added cypress tests for access to MR Settings
- added cypress tests for create MR form validation
Modal opens, form looks right, validation shows up. form can be submitted with good content.
=> feat(mr): create mr modal

frontend/src/__tests__/cypress/cypress/e2e/pipelines/Pipelines.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelinesList.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesTable.ts, frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
[RHOAIENG-3833](https://issues.redhat.com/browse/RHOAIENG-3833)
Updated the pipelineList tests such that its functionality would be tested more rigorously. 
I ran `npm run test`
=> Updated pipelineList tests

frontend/src/__mocks__/mockQuickStarts.ts, manifests/apps/jupyter/deploy-python-model-quickstart.yaml
[RHOAIENG-1138](https://issues.redhat.com/browse/RHOAIENG-1138)
I removed the dot at the end of "Deploying a sample Python application using Flask and OpenShift."
Ran `npm run test:cypress-ci -- --spec "**/Resources.cy.ts"`.
I also did manual testing, by running `oc apply -n opendatahub -f ./manifests/apps/jupyter/deploy-python-model-quickstart.yaml`
I edited the mock corresponding to the manifest.
=> edited manifest to remove dot

frontend/config/webpack.common.js, frontend/config/webpack.prod.js, frontend/package.json
`npm run build:analyze` fails to run because console output was making its way into the `bundle.stats.json` file.
- cd to `frontend` dir
- `npm run build:analyze`
- Wait for analysis webpage to open.
N/A
=> fix build:analyze

frontend/src/concepts/pipelines/EnsureCompatiblePipelineServer.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-5325
The UI page reloads/refreshed  when DSPv1 pipeline server is deleted
[Screencast from 2024-05-30 15-45-06.webm](https://github.com/opendatahub-io/odh-dashboard/assets/99238909/bb046e47-c439-4880-8dca-ac3a7c463e8c)
1. Needed DSPV1 pipeline version 
(to do this In the openshift console ->navigate to DataSciencePipelinesApplication  within your project/namespace, search for `dspVersion: v2`  change v2 to v1 and save
2. Check for the warning in the dashboard UI 
3. click on Delete pipeline server button and delete the version
4. once deleted, check whether the UI is refreshed 
=> Reloads the page after deleting DSPv1 pipeline server

frontend/src/api/pipelines/custom.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/PipelineDetailsTitle.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetailsActions.tsx, frontend/src/concepts/pipelines/content/tables/experiment/ExperimentTableRow.tsx, frontend/src/concepts/pipelines/context/usePipelineAPIState.ts, frontend/src/concepts/pipelines/types.ts
Closes https://issues.redhat.com/browse/RHOAIENG-4999
- Adds a label indicating the run is archived in the run title (see [mocks](https://www.figma.com/design/etbN0ccCcZR1qKCpJXQNAg/Pipeline-phase-2?node-id=7456-75320&t=pnUdepwkzdUli9Ot-0#752615976))
- Adds dropdown actions for an archived run
1. Experiments and Runs
2. Select a run
3. Toggle dropdown in upper right
4. Test that dropdown actions are in parity with the mocks and the methods work as expected. 
Updated PipelinesTopology.cy.ts. 
=> [RHOAIENG-4999] Details page for archived runs

frontend/src/__mocks__/mockImageStreamK8sResource.ts, frontend/src/__mocks__/mockNotebookK8sResource.ts, frontend/src/pages/projects/screens/detail/notebooks/__tests__/useNotebookImageData.spec.ts, frontend/src/pages/projects/screens/detail/notebooks/useNotebookImageData.ts
Closes https://issues.redhat.com/browse/RHOAIENG-7917
Fix issue that fetch the wrong Notebook Image if two Imagestream Version shared the same sha
### In a cluster without Internal Registry
1. Create a workbench with jupyter-minimal-notebook imagestream
2. Notebook image value is shown properly on Dashboard as Minimal Python
3. Then import a custom image (same as is used in this jupyter-minimal-notebook imagestream) and name it as custom-minimal
4. The Notebook image should keep the same image
1. Deploy an image
2. It should display the correct image version
Expanded the testing coverage of the function to account for that edge case
=> Fix issue that fetch the wrong Notebook Image if two Imagestream Version shared the same sha

frontend/src/__mocks__/mockImageStreamK8sResource.ts, frontend/src/__mocks__/mockNotebookK8sResource.ts, frontend/src/__tests__/cypress/cypress/e2e/projects/projectDetails.cy.ts, frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/pages/projects/screens/detail/notebooks/__tests__/useNotebookImageData.spec.ts, frontend/src/pages/projects/screens/detail/notebooks/useNotebookImageData.ts
ODH variant of the 2.8.3 fix.
https://issues.redhat.com/browse/RHOAIENG-7932
=> No internal registry support for 2.8.3

frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesOverviewCard.tsx
https://issues.redhat.com/browse/RHOAIENG-6654
Removed logic that attempted to show the info icon + tooltip under certain conditions. Instead, as per UX guidance, always show the the icon + tooltip.
- Create a project
- add a pipeline server
- go to the project details and observe the info popover is present
- add a pipeline
- go to the project details and observe the info popover is present
cc @jgiardino
=> fix info popover for pipeline overview card

frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeInputOutputTab.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/__tests__/SelectedNodeInputOutputTab.spec.tsx
Closes: [RHOAIENG-7545](https://issues.redhat.com/browse/RHOAIENG-7545)
Added link to execution details page in the right drawer inside Input/Output tab.
https://github.com/opendatahub-io/odh-dashboard/assets/97534722/0c9bb79b-ebbf-48fe-81e1-f7c50da81d1c
Create a run or expirement, and click on one of the node to find the Execution name in the right drawer inside Input/Output tab.
Clicking on the execution name will take you to the node details page.
Added unit test.
@yannnz
=> Pipeline task node details link to execution

frontend/.eslintrc, frontend/src/__tests__/cypress/cypress/support/commands/application.ts, frontend/src/__tests__/cypress/cypress/support/commands/axe.ts, frontend/src/__tests__/cypress/cypress/support/commands/intercept-snapshots.ts, frontend/src/__tests__/cypress/cypress/support/commands/k8s.ts, frontend/src/__tests__/cypress/cypress/support/commands/odh.ts, frontend/src/__tests__/cypress/cypress/support/websockets.ts, frontend/src/__tests__/unit/jest.d.ts, frontend/src/concepts/pipelines/content/createRun/contentSections/ParamsSection/types.ts
Closes: [RHOAIENG-4721](https://issues.redhat.com/browse/RHOAIENG-4721)
Set this eslint rule: `"@typescript-eslint/method-signature-style": "error"` to have consistency for interface functions. The standard we're trying to achieve is `func: (arg: type) => type;`
details: https://issues.redhat.com/browse/RHOAIENG-4721
`npm run test:lint`
=> added method-style rule for eslint

Makefile, backend/src/routes/api/service/mlmd/index.ts
closes: https://issues.redhat.com/browse/RHOAIENG-7526
Updated the pod name prefix for mlmd due to a backend change.
- create a pipeline server
- go to executions table list and verify you dont get a error page `There was an issue loading executions. Unknown Content-type received.`
no tests impacted, backend change
=> update mlmd service prefix

frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useArtifactsFromMlmdContext.spec.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useExecutionsFromMlmdContext.spec.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetArtifactById.spec.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetArtifactTypes.spec.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetArtifactsList.spec.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetEventsByExecutionId.spec.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetExecutionById.spec.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetExecutionsList.spec.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetLinkedArtifactsByEvents.spec.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetMlmdContextByExecution.spec.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useGetMlmdContextType.spec.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/__tests__/useMlmdContext.spec.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/useGetEventsByExecutionId.ts, frontend/src/concepts/pipelines/content/compareRuns/metricsSection/__tests__/useMlmdPackagesForPipelineRuns.spec.ts, frontend/src/concepts/pipelines/context/MlmdListContext.tsx, frontend/src/pages/pipelines/global/experiments/executions/details/ExecutionDetails.tsx
closes: https://issues.redhat.com/browse/RHOAIENG-5510
adds jest tests to all mlmd related hooks
CI passes and make sure all mlmd hooks are covered
Adding coverage to mlmd hooks
=> Added tests for MLMD hooks

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/experiments.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelinesTopology.cy.ts, frontend/src/concepts/pipelines/content/createRun/RunForm.tsx, frontend/src/concepts/pipelines/content/createRun/contentSections/ProjectAndExperimentSection.tsx, frontend/src/concepts/pipelines/content/createRun/submitUtils.ts, frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts, frontend/src/concepts/pipelines/content/experiment/ExperimentSelector.tsx, frontend/src/concepts/pipelines/content/pipelineSelector/useCreateSelectors.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetailsActions.tsx, frontend/src/concepts/pipelines/content/tables/experiment/useExperimentTable.ts, frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableRow.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRowExperiment.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTableToolbar.tsx, frontend/src/concepts/pipelines/content/tables/pipelineVersion/PipelineVersionTableRow.tsx, frontend/src/concepts/pipelines/content/tables/renderUtils.tsx, frontend/src/pages/pipelines/GlobalPipelineExperimentsRoutes.tsx, frontend/src/pages/pipelines/global/GlobalPipelineCoreDetails.tsx, frontend/src/pages/pipelines/global/experiments/ExperimentRunsContext.tsx, frontend/src/pages/pipelines/global/experiments/ExperimentRunsListBreadcrumb.tsx, frontend/src/pages/pipelines/global/experiments/compareRuns/ManageRunsPage.tsx, frontend/src/pages/pipelines/global/experiments/useExperimentByParams.ts, frontend/src/pages/pipelines/global/runs/ActiveRuns.tsx, frontend/src/pages/pipelines/global/runs/CreateScheduleButton.tsx, frontend/src/pages/pipelines/global/runs/ScheduledRuns.tsx
JIRA: https://issues.redhat.com/browse/RHOAIENG-7543
When an experiment is archived, refine the login on the runs page
1. On the active runs tab, show an empty state
2. On the archived runs tab, disable the restore button on both the table toolbar and the row actions
3. On the schedules tab, disable the creation button and the status toggle, so the user cannot enable a schedule
4. The user could duplicate a schedule, but the status will be disabled
5. Refine the logic on the create runs page, the experiment dropdown for a one-time triggered run will only show active experiments (even if you are under the archived experiment context). Duplicating a run with an archived experiment will not auto-fill any experiment now. Create schedules page is working as previously
1. Create an experiment …
=> Refine logic actions for runs on an archived experiment page

frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectDetails.cy.ts, frontend/src/pages/UnknownError.tsx, frontend/src/pages/modelServing/screens/metrics/EnsureMetricsAvailable.tsx, frontend/src/pages/modelServing/screens/metrics/performance/KserveMetrics.tsx, frontend/src/pages/modelServing/screens/metrics/performance/MetricsPlaceHolder.tsx, frontend/src/pages/modelServing/screens/metrics/performance/ModelGraphs.tsx, frontend/src/pages/modelServing/screens/metrics/performance/ModelMeshMetrics.tsx, frontend/src/pages/modelServing/screens/metrics/performance/PerformanceTab.tsx
Closes: [RHOAIENG-6522](https://issues.redhat.com/browse/RHOAIENG-6522)
Implement a page for "kserve model metrics" similar to the way "model metrics" are implemented for modelmesh. The page should however, contain more charts for kserve, which are the following:
- HTTP requests per 5 minutes
- Average response time (ms)
- CPU Utilisation %
- Memory Utilisation %
These queries are TBD so this PR simply creates the page with placeholders for each metric graph.
Updated e2e tests
=> [RHOAIENG-6522] Create model metrics kserve page

frontend/package-lock.json, frontend/package.json, frontend/src/concepts/topology/PipelineVisualizationSurface.tsx
JIRA: https://issues.redhat.com/browse/RHOAIENG-7430
Add "Collapse All" and "Expand All" actions to control bar in topology view.
1. Open a pipeline or run.
2. Click "Collapse All" or "Expand All" action in control bar.
3. Verify that the expand/collapse works as expected.
=> Add "Collapse All" and "Expand All" actions to control bar in topology view

backend/package-lock.json, backend/package.json
Small set of changes to get tough-cookie override fixed: https://issues.redhat.com/browse/RHOAIENG-7540
Ran/built locally - no errors
Shouldn't be any - either this will work or it won't
=> fix(cookie): Bump tough-cookie using override

.codecov.yml
Change the codecov color [range](https://docs.codecov.com/docs/coverage-configuration#range).
> This value is used to customize the visible color range in Codecov. The first number represents the cutover from red to yellow, and the second represents the cutover from yellow to green. You can change the range of colors by adjusting this configuration.
Since our coverage target is 70%, any coverage >= 70% should be green.
The range from 50-70 will become yellow.
The range < 50 will become red.
=> update codecov color range

frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.tsx, frontend/src/concepts/topology/utils.ts
JIRA: https://issues.redhat.com/browse/RHOAIENG-7544
Updated the way we search for the artifact details for a specific node. Also, I removed the status for the artifact node because an artifact node shouldn't have status. (I checked that in KF UI)
1. Import the pipeline listed in the JIRA ticket
2. Create a run using that pipeline
3. Compare the artifact details with the KF UI to make sure the info is correct
N/A, it's topology side panel details change, hard to write test.
=> Show correct artifact run node details on artifact side drawer panel

frontend/src/concepts/pipelines/context/useJobRelatedInformation.ts
JIRA: https://issues.redhat.com/browse/RHOAIENG-7375
Simply set the loading state to `false` when there is an error fetching the recurring run. This could help fix the forever loading state when showing the label of a run.
1. Create a schedule
2. Wait until the schedule create one or more runs
3. Delete the schedule
4. Go to the runs tab, make sure there is no `Loading...` text under the runs
N/A
=> Fix label for runs produces by a deleted recurring run

frontend/src/concepts/pipelines/content/createRun/contentSections/RunTypeSectionScheduled.tsx, frontend/src/concepts/pipelines/content/createRun/submitUtils.ts, frontend/src/concepts/pipelines/content/createRun/utils.ts, frontend/src/utilities/__tests__/time.spec.ts, frontend/src/utilities/time.ts
Closes: [RHOAIENG-1197](https://issues.redhat.com/browse/RHOAIENG-1197)
The issue at hand was that in Firefox, when trying to schedule a pipeline run, returned incoherent values for the end date. This was because of the usage of the Date() constructor, which is inconsistent at runtime if the parameter isn't an `ISO 8601 formatted` string. Here is the [documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#several_ways_to_create_a_date_object) if you are interested.
Unfortunately, it seemed that I could not schedule any pipelines in Firefox, due to this runtime issue, which is a larger issue. Although this is now fixed, I need guidance on whether or not the testing I have done is adequate, or if it needs more.
Reproducible for Firefox on …
=> fixed end date issue and issues scheduling pipelines in Firefox

frontend/src/concepts/pipelines/context/PipelinesContext.tsx
Supports [RHOAIENG-7338](https://issues.redhat.com/browse/RHOAIENG-7338) and [RHOAIENG-7335](https://issues.redhat.com/browse/RHOAIENG-7335), but opening this PR separately since it may be generally useful for ongoing dev on other stories as well
In dev mode, enables support for the [gRPC-Web Developer Tools](https://github.com/SafetyCulture/grpc-web-devtools) browser extension ([Chrome install link](https://chromewebstore.google.com/detail/grpc-web-developer-tools/kanmilmfkjnoladbbamlclhccicldjaj?pli=1)) ([Firefox install link](https://addons.mozilla.org/en-US/firefox/addon/grpc-web-developer-tools/)) when initializing the gRPC client for MLMD in PipelinesContext.
This dev tool allows us to view gRPC responses in deserialized JSON instead of base64 encoded binary format. This should make …
=> Enable gRPC-web dev tools in dev mode for MLMD client

backend/src/routes/api/k8s/pass-through.ts, backend/src/routes/api/storage/index.ts, backend/src/routes/api/storage/storageUtils.ts, backend/src/types.ts
closes: https://issues.redhat.com/browse/RHOAIENG-8473
changes header key to capital A
get image and test on cluster
n/a backend
=> Fix authorization header casing in storageUtils

frontend/src/__mocks__/mockExperimentKF.ts, frontend/src/concepts/pipelines/content/tables/columns.ts, frontend/src/concepts/pipelines/content/tables/experiment/ExperimentTableRow.tsx, frontend/src/concepts/pipelines/content/tables/experiment/renderUtils.tsx, frontend/src/concepts/pipelines/kfTypes.ts
Closes: [RHOAIENG-7715](https://issues.redhat.com/browse/RHOAIENG-7715)
Added new column in Experiments table for last run started.
Go to Experiments page and you can find the new column added.
@yannnz
=> Allow experiments table to sort by last run started

frontend/src/concepts/pipelines/content/pipelinesDetails/PipelineDetailsTitle.tsx, frontend/src/concepts/pipelines/content/utils.tsx
JIRA: https://issues.redhat.com/browse/RHOAIENG-7428
Updates the label colors for the PipelineDetailsTitle header to reflect status of Pipeline Run. 
1. Navigate to a succeeded pipeline run and verify the label in the header is green. 
2. Navigate to a failed pipeline run and verify the label in the header is red. 
=> [RHOAIENG-7428]: update pipelineRunLabel to apply correct colors

frontend/src/concepts/k8s/NameDescriptionField.tsx, frontend/src/concepts/pipelines/content/createRun/RunForm.tsx, frontend/src/concepts/pipelines/content/createRun/const.ts
Closes: [RHOAIENG-2293](https://issues.redhat.com/browse/RHOAIENG-2293)
This PR aims to limit the character for pipeline run name to 255 and added help text under the name input form to explain the limitation.
-  Open a create pipeline run modal.
-  check that name in run details section has an help text.
-  And run name will only take maximum of 255 character, check that it won't allow to add more than 255 character.
=> Add character limit for pipeline run name

frontend/src/concepts/topology/customNodes/ArtifactTaskNode.tsx
JIRA: https://issues.redhat.com/browse/RHOAIENG-7946
Hides status icon on hovered artifact nodes as per UX feedback of artifact node rendering.
Before  - default artifact node: 
Before  - hovered artifact node: 
After  - default artifact node: 
After  - hovered artifact node: 
1. Navigate to a pipeline run with artifacts (e.g. iris pipeline)
2. Verify the artifact nodes render the artifact icon beside the text when hovered
=> [RHOAIENG-7946]: Hide Status Icon on Hovered Artifact Nodes

frontend/src/__tests__/cypress/cypress/pages/pipelines/experiments.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/experiments.cy.ts
[RHOAIENG-8493](https://issues.redhat.com/browse/RHOAIENG-8493)
Added cypress tests for experiments table which was missed in [RHOAIENG-7715](https://issues.redhat.com/browse/RHOAIENG-7715).
Just a cypress test
Added cypress test to check last run time in experiments table.
=> Cypress test for experiments table time

manifests/overlays/odhdashboardconfig/odhdashboardconfig.yaml
Closes: [RHOAIENG-8521](https://issues.redhat.com/browse/RHOAIENG-8521)
Updates the dashboard config manifest file to enable the home page by default.
Needs to be tested on an install
Install and verify the home page is shown.
=> [RHOAIENG-8521] Enable home page in manifest file

frontend/src/concepts/pipelines/content/configurePipelinesServer/ObjectStorageSection.tsx, frontend/src/concepts/pipelines/content/configurePipelinesServer/const.ts
Closes: [RHOAIENG-4385](https://issues.redhat.com/browse/RHOAIENG-4385)
Added info alert with popover for Bucket field in the Configure Pipeline modal
(cc @yannnz)
=> [RHOAIENG-4385] DSPA - Add back the Folder Info

frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts, frontend/src/pages/home/aiFlows/DeployAndMonitorGallery.tsx, frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/AuthServingRuntimeSection.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenSection.tsx, frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
Closes https://issues.redhat.com/browse/RHOAIENG-382
Fix inconsistency in authentication working for model serving.
1. Deploy a model through KServe
2. Select external route
3. Text should match "Token authentication"
=> Fix inconsistency in authentication

manifests/overlays/apps/base/elastic/elastic-app.yaml, manifests/overlays/apps/base/elastic/kustomization.yaml
Adds new manifest for elastic search - vector db solution based on collaboration with them.
Closes: https://issues.redhat.com/browse/RHOAIENG-5150
Applied yaml to running cluster (nightly odh)
27-8b9d-200427768137)
=> RHOAIENG-5150: Initial elastic odh application addition

backend/src/routes/api/servingRuntimes/index.ts, backend/src/types.ts, frontend/src/__mocks__/mockInferenceServiceK8sResource.ts, frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts, frontend/src/api/k8s/__tests__/inferenceServices.spec.ts, frontend/src/api/k8s/inferenceServices.ts, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/screens/global/InferenceServiceEndpoint.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceStatus.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx, frontend/src/pages/modelServing/screens/global/InternalServicePopoverContent.tsx, frontend/src/pages/modelServing/screens/global/utils.ts, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/useModelFramework.ts, frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeDetails.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/DeleteServingRuntimeModal.tsx, frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx, frontend/src/pages/modelServing/screens/projects/useServingAcceleratorProfile.ts, frontend/src/pages/modelServing/screens/projects/utils.ts, frontend/src/pages/modelServing/utils.ts, frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelsGallery.tsx
Closes https://issues.redhat.com/browse/RHOAIENG-6794, https://issues.redhat.com/browse/RHOAIENG-6649
Fixes types for both `InferenceService` and `ServingRuntime` CR objects, fixing an existing bug that made the UI crash by clicking the internal service popup.
1. Create a new modelmesh server
2. Unselect public route
3. Deploy a new model
4. Click the Internal Service section in the row before the model is deployed
=> Fix types for ServingRuntimes and InferenceService

frontend/src/__mocks__/mockConfigMap.ts, frontend/src/__mocks__/mockKserveMetricsConfigMap.ts, frontend/src/__tests__/cypress/cypress/pages/modelMetrics.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelMetrics.cy.ts, frontend/src/api/index.ts, frontend/src/api/k8s/__tests__/configMaps.spec.ts, frontend/src/api/k8s/configMaps.ts, frontend/src/api/prometheus/const.ts, frontend/src/api/prometheus/kservePerformanceMetrics.ts, frontend/src/api/prometheus/useQueryRangeResourceData.ts, frontend/src/concepts/metrics/kserve/KserveMetricsContext.tsx, frontend/src/concepts/metrics/kserve/__tests__/utils.spec.ts, frontend/src/concepts/metrics/kserve/const.ts, frontend/src/concepts/metrics/kserve/content/KserveCpuUsageGraph.tsx, frontend/src/concepts/metrics/kserve/content/KserveMeanLatencyGraph.tsx, frontend/src/concepts/metrics/kserve/content/KserveMemoryUsageGraph.tsx, frontend/src/concepts/metrics/kserve/content/KserveMetricsContent.tsx, frontend/src/concepts/metrics/kserve/content/KservePerformanceGraphs.tsx, frontend/src/concepts/metrics/kserve/content/KserveRequestCountGraph.tsx, frontend/src/concepts/metrics/kserve/types.ts, frontend/src/concepts/metrics/kserve/useKserveMetricsConfigMap.ts, frontend/src/concepts/metrics/kserve/useKserveMetricsGraphDefinitions.ts, frontend/src/concepts/metrics/kserve/utils.ts, frontend/src/pages/modelServing/screens/metrics/MetricsChart.tsx, frontend/src/pages/modelServing/screens/metrics/performance/KserveMetrics.tsx, frontend/src/pages/modelServing/screens/metrics/performance/ModelGraphs.tsx, frontend/src/pages/modelServing/screens/metrics/performance/PerformanceTab.tsx, frontend/src/types.ts, frontend/src/utilities/useRestructureContextResourceData.tsx
Closes: [RHOAIENG-6560](https://issues.redhat.com//browse/RHOAIENG-6560) [RHOAIENG-6561](https://issues.redhat.com//browse/RHOAIENG-6561)
Implements metrics graphs for supported Kserve runtimes. Implements empty state for when a specific serving runtime is not supported.
Graphs and queries are now defined by a config map created by the KServe operator.
NOTE: There are some outstanding bugs in the backend:
- The definition provided for the requests chart is invalid, right now we can only verify the dashboard handles this gracefully
- Graph titles are defined on the backend, these need updating to fix case / match modelmesh charts.
- There is an error in the Memory Usage query that returns an absolute value, instead of a percentage. As such you won't see any data on that chart.
Environment …
=> Support model metrics for KServe (RHOAIENG-6560) (RHOAIENG-6561)

frontend/src/concepts/pipelines/content/configurePipelinesServer/ObjectStorageSection.tsx, frontend/src/concepts/pipelines/content/configurePipelinesServer/const.ts
Closes: [RHOAIENG-8568](https://issues.redhat.com/browse/RHOAIENG-8568)
Removing link for now since the destination doc link is still in question.
=> [RHOAIENG-8568] Remove 'Learn more' link from pipeline server bucket form field popover

frontend/src/concepts/pipelines/content/tables/pipelineRun/useMetricColumnNames.ts
closes: https://issues.redhat.com/browse/RHOAIENG-8585
makes fetching the metrics dependent on if a experiment id is in the params
1. navigate to viewing the runs of a version and verify no custom columns are added
none - covered by existing tests
=>  Refactor useMetricColumnNames to handle empty experimentId

.github/workflows/test.yml
Cypress artifact upload was only done on success but not when test failed.
According to the [github documentation](https://docs.github.com/en/actions/learn-github-actions/expressions#status-check-functions), the default conditional for actions is `success()`. Added the condition of `always()` to the artifact upload step.
=> add always() condition to upload cypress artifacts

docs/dev-setup.md, manifests/overlays/apps/apps-onprem/starburst-enterprise/starburstenterprise-app.yaml
The following files included docs.openshift.com reference to old Openshift versions:
- docs/dev-setup.md
- manifests/overlays/apps/apps-onprem/starburst-enterprise/starburstenterprise-app.yaml
Updated to the latest OCP versions.
The new URLs was verified to lead to docs.openshift.com of latest OCP version. 
=> Update references of docs.openshift.com to the latest OCP version

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts, frontend/src/concepts/pipelines/content/configurePipelinesServer/__tests__/utils.spec.ts, frontend/src/concepts/pipelines/content/configurePipelinesServer/utils.ts
closes: https://issues.redhat.com/browse/RHOAIENG-8836
adds a cleanup step for pipeline server install to remove trailing slash from the host
1. create a pipeline server with a host that has a trailing slash
2. verify that the resulting dspa has the same host but with the trailing slash removed
added test to cover the trailing slash removal
=> Cleanup S3 endpoint host in configurePipelinesServer utils

frontend/src/concepts/pipelines/content/createRun/CloneRunPage.tsx, frontend/src/concepts/pipelines/content/createRun/CreateRunPage.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRunJob/PipelineRunJobDetails.tsx, frontend/src/concepts/pipelines/content/types.ts, frontend/src/pages/pipelines/global/GlobalPipelineCoreDetails.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/ArtifactDetails.tsx, frontend/src/pages/pipelines/global/experiments/compareRuns/CompareRunsPage.tsx, frontend/src/pages/pipelines/global/experiments/executions/details/ExecutionDetails.tsx, frontend/src/pages/pipelines/global/runs/GlobalPipelineVersionRuns.tsx, frontend/src/pages/projects/screens/detail/pipelines/ProjectPipelineBreadcrumbPage.tsx, frontend/src/routes/pipelines/experiments.ts, frontend/src/routes/pipelines/global.ts
JIRA: https://issues.redhat.com/browse/RHOAIENG-7751
When you are on a run details page and navigate back to the pipeline runs page or experiment runs page, it will navigate you back to the correct tab now based on whether the run is archived or is a schedule.
1. Create a run
2. Archive a run
3. Go to the run details page from the pipeline version runs page
4. Click on the breadcrumb to go back to the pipeline version runs page
5. Make sure it lands on the archived tab
6. Go to the experiment runs page
7. Go to the same run details page
8. Click on the breadcrumb to go back to the experiment runs page
9. Make sure it lands on the archived tab
10. Create a schedule
11. Repeat step 3-9, but make sure it lands on the schedules page on each page
N/A, we don't have the breadcrumb test yet. …
=> Fix breadcrumb navigation to correct tabs for pipeline run and jobs details page

frontend/src/concepts/pipelines/content/pipelinesDetails/PipelineDetailsTitle.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx, frontend/src/concepts/pipelines/content/tables/experiment/ExperimentTableRow.tsx, frontend/src/pages/pipelines/global/runs/GlobalPipelineVersionRuns.tsx
Closes: [RHOAIENG-8837](https://issues.redhat.com/browse/RHOAIENG-8837)
Added inline styling for solve truncate min width issue. 
Check page title and breadcrumbs in pipeline pages.
None, just a css change
@yannnz
=> [RHOAIENG-8837] Truncate min width issue

frontend/src/concepts/pipelines/content/artifacts/ArtifactUriLink.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/ArtifactNodeDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsInputOutput.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/ArtifactOverviewDetails.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactsTable.tsx
Closes: [RHOAIENG-7403](https://issues.redhat.com/browse/RHOAIENG-7403)
For system.ClassificationMetrics artifacts the download link is removed.
https://github.com/opendatahub-io/odh-dashboard/assets/97534722/d4b6e22b-b57c-4e8d-a184-a9caf3bb25df
1. Enable S3 feature flag.
2. Create a pipeline run containing a classification metrics artifact, and ensure that the artifact URL is not clickable.
@yannnz
=> [RHOAIENG-7403] Pipeline system.ClassificationMetrics artifacts provide a uri but have no source in storage

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineCreateRuns.cy.ts, frontend/src/concepts/pipelines/content/createRun/contentSections/ParamsSection/NumberInputParam.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeInputOutputTab.tsx
closes: https://issues.redhat.com/browse/RHOAIENG-7678
- makes the doubles render with at least one decimal place even when they have no decimal value
- this is done in the input params and the task detail input params
1. use the provided pipeline which has a default float value of `7.0`: [pipeline-float-input.yaml.zip](https://github.com/user-attachments/files/15891912/pipeline-float-input.yaml.zip)
2. it should show the default as `7.0`
3. the run details input should also show `7.0` instead of `7`
updated test to reflect this case
@yannnz 
=> update double params to be fixed at 1

frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesTable.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts, frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableRow.tsx, frontend/src/concepts/pipelines/content/tables/pipeline/usePipelineTableRowData.ts
Closes: 
Added link for pipeline names in the pipelines list table to navigate to the latest pipeline version's details.
https://github.com/opendatahub-io/odh-dashboard/assets/96431149/64027921-8d14-4230-9e04-dcb21e425a4f
=> [RHOAIENG-7717] Make pipeline table name cell be a clickable link to the latest pipeline version details

frontend/src/pages/projects/projectSharing/utils.ts
Closes: [RHOAIENG-582](https://issues.redhat.com/browse/RHOAIENG-582)
Updates the wording to use 'Contributor' instead of 'Edit'
This has been tested using the Cypress tests in `permissions.cy.ts`
No new tests were added as this is only a label change and there is no functionality change. Screenshots of that change in Cypress are included below. 
=> Rename Edit Permission to Contributor

frontend/package-lock.json, frontend/package.json, frontend/src/concepts/topology/PipelineDefaultTaskGroup.tsx
https://issues.redhat.com/browse/RHOAIENG-7425
Updates expanded group label to pill shape per design feedback. Also updates arrow positioning to keep the group label connected with other nodes so the user understands it is the parent node. 
Before
After
1. Upload [flip_coin_compiled.yml.zip](https://github.com/user-attachments/files/15977589/flip_coin_compiled.yml.zip)
2. Expand group(s)
3. Verify that label renders as pill shape on upper group boundary
N/A
=> [RHOAIENG-7425]: Update Pipeline Group Labels and Positioning

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts, frontend/src/concepts/pipelines/EnsureCompatiblePipelineServer.tsx
closes: https://issues.redhat.com/browse/RHOAIENG-8635
removes the non admin state for incompatible pipeline version view
1. create a pipeline server and change its version to v1 (will need to manually update the DSPA yaml)
2. go to UI and go to this project with the v1 server
3. make sure you are a non odh admin user
4. should see a button to delete in the empty state error view
updated tests for admin user to expect the button
No UI change, just logic
=> remove isAdmin logic for EnsureCompatiblePipelineServer empty state

frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx
closes: https://issues.redhat.com/browse/RHOAIENG-8581
for pages of pipeline runs that have no metrics but the experiment as a whole has saved selected metrics, the icon button does not remain disabled with the tooltip saying it is loading. instead now it allows you to customize the metric columns when on these specific pages
1. create a new experiment
2. create 1 run that has scalar metrics
3. create 10 more runs that dont have a scalar metric output
4. confirm there are selected runs by seeing them in the table columns
5. go to the page that does **not** have the run with the metric output
6. confirm the customize button in the toolbar is enabled
no tests in this area because the the cypress tests for the experiment run page dont yet support mlmd mocks. this work is being done this …
=> remove the length check for the loaded state of customize metric columns

manifests/overlays/apps/base/rhoai/rhoai-docs.yaml
Closes: [RHOAIENG-9175](https://issues.redhat.com/browse/RHOAIENG-9175)
Change the link in manifest file for Fraud Detection tutorial
https://github.com/opendatahub-io/odh-dashboard/assets/97534722/b15b1853-2701-4837-a28c-591d69e4d3e5
1. Deploy the manifest `oc apply -k manifests/overlays/apps/base/rhoai -n opendatahub`
2. Verify that the link redirects to the correct destination.
None, just a URL change.
=> [RHOAIENG-9175] Broken link to Fraud Detection tutorial in Dashboard Home

scripts/ci/Dockerfile
This reduces the cypress job duration in the CI (Jenkins) container runtime, by using preexisting npm packages that were installed during `scripts/ci/Dockerfile` build.
In addition updated to the latest minor release of NPM 20 (v20.15.0).
Running the CI Job that uses an image built from this Dockerfile, takes ~10 minutes instead of ~16 previously:
In the job output we can see that the `npm ci` command did not pull new packages, since all required Node packages were already available:
```
14:03:50  + git clone -b main --single-branch https://github.com/opendatahub-io/odh-dashboard odh-dashboard
14:03:50  Cloning into 'odh-dashboard'...
[Pipeline] dir
14:03:56  Running in /home/jenkins/workspace/cypress/cypress-tests/odh-dashboard
[Pipeline] {
[Pipeline] echo
14:03:56  Installing NodeJS …
```
=> Create NPM Cache directories for CI and run `npm ci` in Dockerfile build

frontend/src/__tests__/cypress/cypress.config.ts
cc @manosnoam 
Set `experimentalMemoryManagement=true` to enable support for improved memory management within Chromium-based browsers.
https://docs.cypress.io/guides/references/experiments#Configuration
> This feature helps prevent out-of-memory errors and improves test stability and performance by:
>  - Actively managing memory usage
>  - Clearing caches and performing garbage collection more aggressively
`npm run test:cypress-ci`
N/A
=> set experimentalMemoryManagement=true for cypress

frontend/src/concepts/pipelines/content/artifacts/charts/ROCCurve.tsx
https://issues.redhat.com/browse/RHOAIENG-7794
Previously in pipelines compare runs we would compare many ROC curves in one graph by using different shades of blue, but per the PF recommendation we should instead be[ corresponding each run with one of the available base colors](https://www.patternfly.org/charts/colors-for-charts/#use-cases).
Before
After
Compare runs that have all metrics. Use the following pipeline
[Pipeline metrics-visualization-pipeline.yaml.zip](https://github.com/opendatahub-io/odh-dashboard/files/15268325/Pipeline.metrics-visualization-pipeline.yaml.zip)
N/A, color change only
=> [RHOAIENG-7794]: Use different colors for the ROC curve legend

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineCreateRuns.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineRuns.cy.ts, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTableRow.tsx
Closes: [RHOAIENG-8566](https://issues.redhat.com/browse/RHOAIENG-8566)
Hiding run/schedule "Duplicate" actions when the associated pipeline version is not found.
**Active run with a deleted pipeline version:**
**Active run with a pipeline version:**
**Schedule with a deleted pipeline version:**
**Schedule with a pipeline version:**
Updated duplicate action related cypress tests to point to the experiment runs page vs the legacy runs page. The rest will eventually need updating as well, but that will require many more line changes and was out of scope.
=> [RHOAIENG-8566] Duplicate run is not useful when its pipeline is disabled

backend/src/utils/proxy.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-8080
When uploading to the Pipeline Service, it does not limit the request on the bytes sent. this issue is been currently addressed on client side  for pipeline in this PR https://github.com/opendatahub-io/odh-dashboard/pull/2874 
To overall limit the upload body limit , changes are been done in backend side
1. Create a file of > 1 mib ( to do this run openssl rand -hex 25000000 > mb-50.yaml)
2.Undo the changes made in this PR https://github.com/opendatahub-io/odh-dashboard/pull/2874 
3. Go to Pipeline Page and click on import pipeline
4. Import the created file
5. See if error is thrown
No test impacted
=> make proxy service have upload byte limit

frontend/src/utilities/segmentIOUtils.tsx
Now that we have the dashboard version in the Frontend, we can send it to Segment as context.app.version
See [RHOAIENG-8414](https://issues.redhat.com/browse/RHOAIENG-8414)
Manual testing by looking at the network tab of the browser.
No functionality change of the UI code.
=> [RHOAIENG-8414] Tracking of dashboard version in Segment.

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/experiments.cy.ts, frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTableToolbar.tsx, frontend/src/pages/pipelines/global/runs/ScheduledRuns.tsx
Closes: [RHOAIENG-8583](https://issues.redhat.com/browse/RHOAIENG-8583)
Removed 2 "Create schedule" buttons when the experiment is archived
**Archived experiment schedules list with data:**
**Archived experiment schedules list empty state:**
Updated cypress test verifying the create button is not present in the schedule list table's toolbar.
=> [RHOAIENG-8583] Remove the disabled 'Create schedule' button when in an archived experiment

frontend/src/concepts/pipelines/content/artifacts/ArtifactUriLink.tsx
https://issues.redhat.com/browse/RHOAIENG-8502
Navigate to the Artifacts page from the left nav. Using a project with multiple artifacts, verify that any truncated artifact URI  truncates in the middle. 
To test URIs within artifact node details, navigate to artifact node details in runs for the following pipelines:
[Pipeline.metrics-visualization-pipeline.yaml.zip](https://github.com/user-attachments/files/16057492/Pipeline.metrics-visualization-pipeline.yaml.zip)
[Pipeline iris-training-pipeline.yaml.zip](https://github.com/user-attachments/files/16057516/Pipeline.iris-training-pipeline.2.1.yaml.zip)
N/A
=> [RHOAIENG-8502]: Change pipeline URI truncate to middle instead of end

frontend/src/__tests__/cypress/cypress/pages/pipelines/compareRuns.ts, frontend/src/__tests__/cypress/cypress/support/commands/odh.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/compareRuns.cy.ts, frontend/src/concepts/pipelines/content/artifacts/charts/ROCCurve.tsx, frontend/src/concepts/pipelines/content/artifacts/charts/confusionMatrix/ConfusionMatrix.tsx, frontend/src/concepts/pipelines/content/compareRuns/metricsSection/PipelineRunArtifactSelect.tsx, frontend/src/concepts/pipelines/content/compareRuns/metricsSection/confusionMatrix/ConfusionMatrixCompare.tsx, frontend/src/concepts/pipelines/content/compareRuns/metricsSection/markdown/MarkdownCompare.tsx, frontend/src/concepts/pipelines/content/compareRuns/metricsSection/roc/RocCurveTable.tsx, frontend/src/pages/pipelines/global/experiments/compareRuns/CompareRunsMetricsSection.tsx
closes: https://issues.redhat.com/browse/RHOAIENG-8500
add cypress tests for compare runs
- markdown
- roc cure
- confusion matrix
tests pass
coverage to metrics section of compare runs
=> add compare runs tests

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/compareRuns.cy.ts, frontend/src/concepts/pipelines/content/compareRuns/metricsSection/markdown/MarkdownCompare.tsx, frontend/src/concepts/pipelines/content/compareRuns/metricsSection/markdown/useFetchMarkdownMaps.ts, frontend/src/pages/pipelines/global/experiments/compareRuns/CompareRunsMetricsSection.tsx
JIRA: https://issues.redhat.com/browse/RHOAIENG-8360
This issue is because we have 2 additional S3 API calls for fetching the markdown content. In that way, we have a delay when selecting/unselecting the compared runs. The solution is to fetch all the markdown data on the first render and record it as a map. Then we only need to filter the map based on the run selection.
1. Turn S3 feature flag on
2. Create 2 runs with the pipeline provided in the ticket
3. Go to compare runs page
4. Select/Unselect the runs to see if the markdown tab is rendering seamlessly and correctly
N/A
=> Fix markdown tab render delay when toggling selected compared runs

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/compareRuns.cy.ts
closes: https://issues.redhat.com/browse/RHOAIENG-9665
remove flaky compare runs test that blocks PRs
tests pass in CI
removed 1 test that was testing a PF graph
=> remove flaky compare runs test

frontend/src/__tests__/cypress/cypress/pages/pipelines/topology.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/experiments.cy.ts, frontend/src/concepts/dashboard/codeEditor/DashboardCodeEditor.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/PipelineDetailsYAML.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/PipelineVersionError.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetailsTabs.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabDetails.tsx, frontend/src/concepts/topology/PipelineTopology.tsx
Closes: [RHOAIENG-6683](https://issues.redhat.com/browse/RHOAIENG-6683)
This PR aims to add error state in pipeline run details page when pipeline version is deleted.
1. create a pipeline
2. create a run for that.
3. delete pipeline version of that run.
4. From Experiments and run page open pipeline run details page.
5. It will show the error state on run graph and pipeline spec tab. Also in details tab, "No pipeline version" will be mentioned for pipeline version property.
=> Add error state when pipeline version is deleted

frontend/src/pages/projects/screens/spawner/__tests__/spawnerUtils.spec.ts, frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
Closes: [RHOAIENG-5531](https://issues.redhat.com/browse/RHOAIENG-5531)
Before, when using a dependency with a number (non-string) dependency, it will crash due to a type error.
Create a custom ImageStream with the Python dependency as 3.9 instead of "3.9". It should work with the fix. More detailed reproduction of the error is nicely laid out in the jira ticket
Added tests to `spawnerUtils.spec.ts`
CC @lucferbux
=> fixed workbench image number dep

frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/SelectedTaskDrawerContent.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRecurringRun/PipelineRecurringRunDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetailsTabs.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightContent.tsx, frontend/src/concepts/topology/PipelineTopology.tsx, frontend/src/concepts/topology/PipelineVisualizationSurface.scss, frontend/src/concepts/topology/PipelineVisualizationSurface.tsx
https://issues.redhat.com/browse/RHOAIENG-7942
Previously if we selected a pipelines node and the side panel opened, the node that toggled the panel was obscured by the panel.
Now when a node is selected, the node that toggled the drawer is panned into view. 
https://github.com/opendatahub-io/odh-dashboard/assets/32821331/e8bd847a-58e9-4958-b5f0-b8b9ce1d6019
1. Navigate to a pipeline, pipeline run, or scheduled run
2. Click + drag the graph to the right of the topology view (such as to be obscured by the side panel opening on the right)
3. Select a node in the pipeline
4. Verify the node/graph pans to the left of the drawer panel and is not obscured by the panel
N/A
=> [RHOAIENG-7942]: Update Side Panel Behavior to Pan Graph on Node Selection

frontend/src/__mocks__/mlmd/mockGetExecutions.ts, frontend/src/__mocks__/mlmd/mockGetExecutionsByID.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/executions.ts, frontend/src/__tests__/cypress/cypress/support/commands/odh.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/executions.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/mlmdUtils.ts
Closes: [RHOAIENG-6986](https://issues.redhat.com/browse/RHOAIENG-6986)
I added pipeline executions tests (focused on table and details) to improve code coverage
`npm run test`
I added tests and mocks.
=> added pipeline execution tests

frontend/src/__tests__/cypress/cypress/pages/pipelines/topology.ts, frontend/src/__tests__/cypress/cypress/support/commands/odh.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelinesTopology.cy.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRecurringRun/PipelineRecurringRunDetailsActions.tsx, frontend/src/concepts/pipelines/content/tables/renderUtils.tsx, frontend/src/concepts/pipelines/kfTypes.ts
Closes: [RHOAIENG-7752](https://issues.redhat.com/browse/RHOAIENG-7752)
Added ability to Enable or Disable the status of schedules from their respective schedule details pages via the top right actions dropdown.
**Enable**
**Disable**
(cc @yannnz)
Manual and cypress tests
Added cypress tests for enabling and disabling from the schedule details page
=> [RHOAIENG-7752] Add disable pipeline schedule in the job detail page

frontend/src/__mocks__/mlmd/mockGetArtifacts.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/artifacts.ts, frontend/src/__tests__/cypress/cypress/support/commands/odh.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/artifacts.cy.ts, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/ArtifactOverviewDetails.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/ArtifactPropertyDescriptionList.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactsTable.tsx
Closes: [RHOAIENG-9048](https://issues.redhat.com/browse/RHOAIENG-9048)
Cypress tests for artifacts table & detail pages
=> [RHOAIENG-9048] Cypress tests for MLMD artifacts

backend/src/utils/adminUtils.ts
Closes: [RHOAIENG-7659](https://issues.redhat.com/browse/RHOAIENG-7659)
Users in the group `cluster-admins` but not in `odh-admins` showed up as `users` in the administration tab. I added this group so that they would instead show as `admin`
This fix will also show `cluster-admin` users with no previous activity in the tab.
1. Comment out the one-liner
2. Add a `cluster-admin` to your cluster, but do not add them to the `odh-admins` group.
3. Create a notebook server (Applications -> Enabled -> Jupyter -> Notebooks Server) logged in with the credentials of the NEW USER you just created.
4. Go to `Applications` -> `Enabled` -> `Jupyter` -> `Administration`. They should show up as a `user` since it just had recent activity.
5. Repeat step 2.
6. Uncomment the one-line fix
7. After reloading, …
=> added cluster-admins to administration tab

frontend/src/pages/projects/screens/projects/useProjectTableRowItems.ts
Closes: [RHOAIENG-8785](https://issues.redhat.com/browse/RHOAIENG-8785)
The `edit permissions` menu item under `Data Science Projects` links to the overview tab rather than the permissions tab. I added the query parameter so that it links to the permissions tab
`npm run test`
I don't think tests are necessary, as it's a minimal change, and any future changes are unlikely to break this behavior.
=> changed link for permissions menu item

manifests/rhoai/shared/apps/pachyderm/pachyderm-docs.yaml
Closes: https://issues.redhat.com/browse/RHOAIENG-9330
Change the link in manifest file for Pachyderm tutorial 
1. Deploy the manifest in your cluster  `oc apply -k manifests/rhoai/shared/apps/pachyderm -n opendatahub`
2. Verify that pachyderm tutorial redirects to correct page
N/A, changed url
=> fixed the broken Pachyderm tutorial link

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelineRuns.cy.ts, frontend/src/concepts/pipelines/content/compareRuns/CompareRunTableToolbar.tsx, frontend/src/concepts/pipelines/content/tables/experiment/ExperimentTableToolbar.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableToolbar.tsx, frontend/src/pages/pipelines/global/experiments/compareRuns/ManageRunsTable.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-2701
Changed the filter text of ExperimentTable, CompareRunTable, ManageRunTable and RunTable toolbar to `Created after`
1. Manually checking  ExperimentTable, CompareRunTable, ManageRunTable and RunTable toolbar in the  the UI
2. Check whether Started/Created is replaced by Created after
Updated the existing cypress test
=> changed the filters to Created after

backend/src/routes/api/status/adminAllowedUsers.ts, frontend/src/__mocks__/mockAllowedUsers.ts, frontend/src/__tests__/cypress/cypress/pages/administration.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/applications/administration.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/applications/notebookServer.cy.ts, frontend/src/pages/notebookController/screens/admin/__tests__/useCheckForAllowedUsers.spec.ts
Closes: [RHOAIENG-7660](https://issues.redhat.com/browse/RHOAIENG-7660)
This PR aims to fix the started notebook disappear problem. 
1. Make sure the notebook culling is disabled. (delete the `notebook-controller-culler-config` ConfigMap)
2. Login as a cluster-admin
3. Navigate to the Jupyter tile & select the admin tab
4. Start another user's notebook
5. Check the Administration tab, make sure the started notebook is still visible with last-activity: 'Just now' and kebab action to stop the server.
Added unit test and cypress test.
=> Fix started notebooks disappear issue
