routes/api/components/available-components.js
Related to: https://github.com/opendatahub-io/odh-manifests/pull/208
Merge together, please
=> feat: Update Argo route to argo-server

frontend/src/components/OdhDocListItem.tsx
List view items did not get updates to type name changes on merge upstream.
=> Fix merge error on list view items

frontend/src/app/App.scss, frontend/src/app/App.tsx, frontend/src/app/AppNotificationDrawer.tsx, frontend/src/app/Header.tsx, frontend/src/app/HeaderTools.tsx, frontend/src/utilities/utils.ts
**Fixes**: 
Jira https://issues.redhat.com/browse/RHODS-885
As a DS user, I want to see a list of all notifications I have received in case I missed any. I need a way to know that there are new notifications, a way to acknowledge notifications, and a way to remove notifications from the list.
Add a notification drawer and an indicator of unread notification on the header bar. Notifications are marked read when clicked on and can be remove via the x button.
**Browser conformance**: 
/cc @kywalker-rh
=> Add notifications drawer

backend/src/routes/api/validate-isv/validateISV.ts, frontend/src/app/AppNotificationDrawer.tsx, frontend/src/app/HeaderTools.tsx, frontend/src/pages/exploreApplication/ExploreApplications.scss, frontend/src/pages/exploreApplication/ExploreApplications.tsx, frontend/src/pages/exploreApplication/GetStartedPanel.scss, frontend/src/pages/learningCenter/LearningCenter.scss, frontend/src/utilities/useEnableApplication.tsx
- Remove extra help dropdown
- Fix log message when validation cron job does not exist
- Fix borders/space for filter drawer and getting started panel
=> Updates per internal reviews

backend/src/routes/api/validate-isv/index.ts, backend/src/routes/api/validate-isv/validateISV.ts, backend/src/types.ts, frontend/src/pages/exploreApplication/EnableModal.scss, frontend/src/pages/exploreApplication/EnableModal.tsx, frontend/src/pages/exploreApplication/ExploreApplications.scss, frontend/src/types.ts
**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-748 (partially)
Some apps do not have a known mechanism for determining enablement.
Add a mechanism whereby the user can specify an application is enabled.
**Browser conformance**: 
/cc @kywalker-rh
=> Add ability to manually flag an app as enabled

backend/src/routes/api/components/list.ts, backend/src/routes/api/validate-isv/validateISV.ts, backend/src/types.ts, backend/src/utils/componentUtils.ts
**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-600 (partially)
To determine enablement of some applications we need to support checking of the existence of a particular custom resource and optionally, a specific setting within that resource.
Add the ability to specify a CR and optionally a field and value to check for.
=> Add enablement via CustomResource

backend/src/routes/api/components/list.ts, backend/src/routes/api/validate-isv/validateISV.ts, frontend/src/app/App.tsx, frontend/src/services/validateIsvService.ts
**Fixes**: 
Jira: https://issues.redhat.com/browse/RHODS-1019
The check for the enable variables is incorrectly checking the length and hence performing manual validation without running the validation job. Fix another discovered issue where applications are not showing as enabled in the Explore section :(
Fix the check to look for keys in the enable object rather than its length. Fix some error messaging and style of the notifications and alerts.
=> Fix to run validation job when enable variables exist

frontend/src/pages/clusterSettings/ClusterSettings.tsx
Fix to allow a user to enter an empty string.
https://user-images.githubusercontent.com/6126356/158695015-14ffe643-580b-40aa-a444-c66692f9fde2.mov
=> Fix for input not allowing blank spaces.:

backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts, backend/src/types.ts, frontend/src/pages/clusterSettings/ClusterSettings.scss, frontend/src/pages/clusterSettings/ClusterSettings.tsx, frontend/src/pages/clusterSettings/const.ts, frontend/src/services/clusterSettingsService.ts, frontend/src/types.ts, frontend/src/utilities/utils.ts
The config map `jupyterhub-cfg` will be changed when users change the culler timeout settings.
=> Add culler timeout settings feature

backend/src/types.ts, frontend/src/types.ts
Updated the REST API based on discussions from PR https://github.com/opendatahub-io/odh-dashboard/pull/147.
=> Updated REST API 

backend/src/routes/api/notebook/notebooksUtils.ts, backend/src/types.ts
Since we're hurrying with this, I've implemented it all at once (commits have slight dependency, so it goes as a single PR) 
Resolves https://github.com/opendatahub-io/odh-dashboard/issues/153
Resolves https://github.com/opendatahub-io/odh-dashboard/issues/142
Resolves https://github.com/opendatahub-io/odh-dashboard/issues/152
Resolves https://github.com/opendatahub-io/odh-dashboard/issues/151
Resolves https://github.com/opendatahub-io/odh-dashboard/issues/143
=> [byon] Implement backend

backend/src/routes/api/notebook/notebooksUtils.ts, backend/src/types.ts
Part of: https://github.com/open-services-group/byon/issues/39
=> feat(byon): Feat add creator annotation

backend/src/routes/api/notebook/notebooksUtils.ts, backend/src/types.ts
Resolves https://github.com/open-services-group/byon/issues/40
=> feat(byon): Allow to patch name and description on notebook

backend/src/routes/api/notebook/notebooksUtils.ts, frontend/package-lock.json, frontend/package.json, frontend/src/app/Routes.tsx, frontend/src/pages/ApplicationsPage.tsx, frontend/src/pages/notebookImages/DeleteImageModal.tsx, frontend/src/pages/notebookImages/ImportImageModal.tsx, frontend/src/pages/notebookImages/NotebookImages.tsx, frontend/src/pages/notebookImages/NotebookImagesTable.scss, frontend/src/pages/notebookImages/NotebookImagesTable.tsx, frontend/src/pages/notebookImages/UpdateImageModal.tsx, frontend/src/services/notebookImageService.ts, frontend/src/types.ts, frontend/src/utilities/NavData.ts, frontend/src/utilities/time.ts, frontend/src/utilities/useWatchNotebookImages.tsx
This PR adds the following functionality to the UI:
=> BYON front end code.

install/odh/base/role.yaml
Support BYON backend when deployed to OCP.
=> fix(byon): Update dashboard Role

backend/src/routes/api/notebook/notebooksUtils.ts, frontend/src/pages/notebookImages/NotebookImagesTable.tsx
Resolves https://github.com/opendatahub-io/odh-dashboard/issues/181
=> fix(byon): Visibility toggle only on Succeeded images

frontend/src/components/DocCardBadges.tsx, frontend/src/utilities/quickStartUtils.ts
Fixes issue where quick start is not completed and doesn't show in progress and where it completed with failed steps.
=> Fixed progress showing incorrectly for Quick Starts.

frontend/src/components/DocCardBadges.tsx, frontend/src/utilities/quickStartUtils.ts
Fixes the issue where a user skips every step and it doesn't show in progress.
=> Quickstart fix for missing the initial step

backend/src/routes/api/status/statusUtils.ts
**Changes proposed in this pull request**
- Add the ability to have `system:authenticated` as a group option
- Refactor log error to add more info
**Test instructions (required)**
- Run a new instance of ODH
- Stop the operator to be able to edit de configmap
- Change the value of `jupyterhub-default-groups-config` Configmap to `admin_groups: 'system:authenticated'`
- Check wether the config options of the dashboard have the settings enable
- Refresh the dashboard and check you can see the settings panel
=> Update error message

docs/apis.md
Added documentation describing the backend api calls.
=> Added api documentation.

backend/src/routes/api/status/statusUtils.ts
Add the ability to have system:authenticated as a group option
Refactor log error to add more info:
``` bash
Error: It is not allowed to set "system:authenticated" or an empty string as admin group.
Error: Failed to retrieve Group fakegroup, might not exist.
Error: Failed to retrieve ConfigMap fake-groups-config-jupyterhub, might be malformed or doesn't exist.
Error: Failed to retrieve ConfigMap groups-config, might be malformed or doesn't exist.
```
```yaml
kind: KfDef
apiVersion: kfdef.apps.kubeflow.org/v1
metadata:
name: opendatahub
namespace: opendatahub
spec:
applications:
- kustomizeConfig:
repoRef:
name: manifests
path: odh-common
name: odh-common
- kustomizeConfig:
parameters:
- name: s3_endpoint_url
value: s3.odh.com
repoRef:
name: manifests
path: jupyterhub/jupyterhub
name: …
```
=> Fix system:authenticated feature

README.md, data/quickstarts/create-jupyter-notebook-quickstart.yaml, data/quickstarts/deploy-python-model-quickstart.yaml, docs/user_interaction.md
The PR replaces references to our downstream offering with Open Data Hub
=> Replace references to downstrem product with ODH

backend/src/routes/api/notebooks/notebookUtils.ts, frontend/src/pages/notebookController/SpawnerPage.tsx, frontend/src/pages/notebookController/const.ts, frontend/src/services/notebookService.ts
=> Update volume mount path to read from correct PVC path

frontend/src/pages/notebookController/NotebookServerDetails.tsx
=> Show correct notebook container size on control panel

frontend/src/pages/notebookController/NotebookController.tsx, frontend/src/pages/notebookController/SpawnerPage.tsx, frontend/src/services/notebookService.ts, frontend/src/utilities/utils.ts
Closes #316 
There is an issue to generate a userState entry with username equals to a `''`, I also fixed that in this PR.
=> Translate username in Notebook label and dashboard config user states

backend/src/routes/api/notebooks/notebookUtils.ts, frontend/src/services/notebookService.ts
=> Update NOTEBOOK_ARGS when creating the notebook

OWNERS
=> Add andrewballantyne as Approver in OWNERS file

backend/package.json, backend/src/routes/api/config/configUtils.ts, backend/src/routes/api/notebooks/index.ts, backend/src/routes/api/secrets/index.ts, backend/src/types.ts, backend/src/utils/resourceUtils.ts, frontend/package.json, frontend/src/pages/BYONImages/BYONImagesTable.tsx, frontend/src/redux/actions/actions.ts, frontend/src/services/dashboardConfigService.ts, frontend/src/services/notebookService.ts, frontend/src/types.ts
Resolves:#289
Replaces #313 due to issues with git
It includes the changes and also implements the feedback provided in the comments of the mentioned PR.
Added requirements for 0 warnings allowed
Backend:
- specified types
- removed unused reply arguments
- removed unused variables
Frontend:
- specified types
- added explicit eslint ignores
=> Fix linter warnings

frontend/src/app/Header.tsx
Resolves #323
Added a link to the ODH logo directed to the main page (Enabled).
=> Add home-page link to the ODH logo

backend/src/routes/api/status/statusUtils.ts, frontend/src/pages/notebookController/NotebookController.tsx
Closes #344 
Simply wrap the `QuickStart` component to notebookController, it will get all the context of the quick starts.
Open the quick start -> Click 'launch application' -> The quick start remains open
=> Enable QuickStart in notebook controller

docs/byon.md
Updated dead link in docs
Resolves #366
=> Fix dead link

backend/src/routes/api/nb-events/eventUtils.ts, backend/src/routes/api/nb-events/index.ts, backend/src/routes/api/status/statusUtils.ts, backend/src/types.ts
Resolves: https://github.com/opendatahub-io/odh-dashboard/issues/315
=> Add notebook status endpoint

.dockerignore
Fix #370 
* Add dockerignore to avoid copying build and dependencies folders.
1. Create a new build (it should be faster than usual).
2. Deploy that build.
=> Add dockerignore to ignore external dependencies and build folders

frontend/src/pages/notebookController/SetupCurrentUserState.tsx
Closes: #389 
Change the logic to initialize the user state and patch it.
=> Fix user state initial patching

backend/src/routes/api/gpu/gpuUtils.ts
=> Make sure the app is not crashed when GPU data is unavailable

frontend/src/pages/notebookController/screens/admin/ImpersonateAlert.tsx, frontend/src/pages/notebookController/screens/admin/NotebookControllerTabs.tsx, frontend/src/pages/notebookController/screens/admin/ServerStatus.tsx, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
Resolves #394 
Speaking with UX -- these are a few misc changes to improve the Admin Spawner experience.
=> Misc Admin Spawner Improvements

frontend/src/pages/notebookController/screens/server/GPUSelectField.tsx, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
Resolves #301
Based on UX & PM input, we will disable the dropdown if there are no options with the provided help text.
=> Disable the SpawnerPage GPU dropdown at zero

frontend/src/services/notebookService.ts
Resolves: #381 
Added soft nodeAffinity when the number of GPUs is zero.
1. Deploy this PR on the cluster
2. Spawn notebook with 0 GPUs
3. Verify that posted notebook has the desired affinity
4. Attempt spawn with at least 1 GPU
5. Verify that the affinity is not present
=> added nodeAffinity during notebook creation with 0 gpus

.github/ISSUE_TEMPLATE/bug_report.yaml
Update the question about what infrastructure OpenShift is running on
=> Update Bug report to clarify question about OCP infra

frontend/src/pages/notebookController/screens/server/SizeSelectField.tsx, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx, frontend/src/pages/notebookController/screens/server/usePreferredNotebookSize.ts
Closes #418 
This is an infrastructure PR to extract Size Form out of the Spawner Page which could reduce spawner page size and make it easier to maintain.
Check the sizes dropdown.
=> Extract size form out of Spawner Page

manifests/base/deployment.yaml
* Change probe endpoint to `/api/config` path.
* Fixes #376 
* Build a new image
* Deploy to the dashboard
* Check that the dashboard doesn't log the `x-forwarded-acccess-token` error
=> Change probe endpoint

frontend/src/app/AppNotificationDrawer.tsx, frontend/src/pages/BYONImages/BYONImagesTable.tsx, frontend/src/pages/notebookController/screens/server/ImageVersions.tsx, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx, frontend/src/utilities/imageUtils.ts, frontend/src/utilities/useWatchImages.tsx
Closes #439 
Follow the same procedures in the issue to reproduce, and you will not see the issue anymore.
=> Stop mutating objects by sort functions

backend/src/routes/api/components/list.ts, backend/src/routes/api/quickstarts/quickStartUtils.ts, backend/src/utils/componentUtils.ts, backend/src/utils/resourceUtils.ts
=> Type check when notebookController is not defined

frontend/src/pages/notebookController/screens/server/NotebookServerRoutes.tsx
Closes #452, add routes to fix the existing known issues and add a fallback to prevent unknown URLs that come from JL.
Please refer to the issue, the test is the same as the way to reproduce the issue. But you will not see the blank page this time.
=> Refine notebook controller routes

backend/src/types.ts, backend/src/utils/constants.ts, frontend/package-lock.json, frontend/src/app/NavSidebar.tsx, frontend/src/app/Routes.tsx, frontend/src/pages/projects/EmptyProjects.tsx, frontend/src/pages/projects/ProjectView.tsx, frontend/src/types.ts, frontend/src/utilities/NavData.ts, frontend/src/utilities/useWatchDashboardConfig.tsx, manifests/base/odh-dashboard-crd.yaml, manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Resolves: #449 
Adds the basic DSG page with empty projects view.
See nav, click nav.
=> Add empty DSG page & nav

CONTRIBUTING.md, README.md
Updates the README to include information about the automated image builds for the main branch and pull requests
N/A
README info is clear and there are no mistakes
=> README: Add automated image build info

backend/src/routes/api/configmaps/index.ts, backend/src/routes/api/groups-config/groupsConfigUtil.ts, backend/src/routes/api/notebooks/notebookUtils.ts, backend/src/routes/api/pvc/index.ts, backend/src/routes/api/secrets/index.ts, backend/src/routes/api/status/adminAllowedUsers.ts, backend/src/routes/api/status/statusUtils.ts, backend/src/types.ts, backend/src/utils/route-security.ts, backend/src/utils/userUtils.ts
Resolves: #487 
Add additional security to routes to make sure they are requesting resources for them in the namespaces they expect to have.
See ticket
=> Add Route Security to some routes

backend/src/routes/api/builds/index.ts, backend/src/routes/api/cluster-settings/index.ts, backend/src/routes/api/components/index.ts, backend/src/routes/api/config/index.ts, backend/src/routes/api/console-links/index.ts, backend/src/routes/api/docs/index.ts, backend/src/routes/api/getting-started/index.ts, backend/src/routes/api/gpu/index.ts, backend/src/routes/api/groups-config/index.ts, backend/src/routes/api/images/index.ts, backend/src/routes/api/nb-events/index.ts, backend/src/routes/api/notebooks/index.ts, backend/src/routes/api/notebooks/notebookUtils.ts, backend/src/routes/api/quickstarts/index.ts, backend/src/routes/api/rolebindings/index.ts, backend/src/routes/api/segment-key/index.ts, backend/src/routes/api/status/index.ts, backend/src/routes/api/validate-isv/index.ts, backend/src/types.ts, backend/src/utils/route-security.ts, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
Adds additional security to all routes.
Main aspects are locking endpoints to admins when applicable & adding a fallback warn for users that access endpoints that are not parameterized.
=> Secure all routes

backend/src/routes/api/builds/index.ts, backend/src/routes/api/cluster-settings/index.ts, backend/src/routes/api/components/index.ts, backend/src/routes/api/config/index.ts, backend/src/routes/api/configmaps/index.ts, backend/src/routes/api/console-links/index.ts, backend/src/routes/api/docs/index.ts, backend/src/routes/api/getting-started/index.ts, backend/src/routes/api/gpu/index.ts, backend/src/routes/api/groups-config/groupsConfigUtil.ts, backend/src/routes/api/groups-config/index.ts, backend/src/routes/api/images/index.ts, backend/src/routes/api/nb-events/index.ts, backend/src/routes/api/notebooks/index.ts, backend/src/routes/api/notebooks/notebookUtils.ts, backend/src/routes/api/pvc/index.ts, backend/src/routes/api/quickstarts/index.ts, backend/src/routes/api/rolebindings/index.ts, backend/src/routes/api/secrets/index.ts, backend/src/routes/api/segment-key/index.ts, backend/src/routes/api/status/adminAllowedUsers.ts, backend/src/routes/api/status/index.ts, backend/src/routes/api/status/statusUtils.ts, backend/src/routes/api/validate-isv/index.ts, backend/src/types.ts, backend/src/utils/route-security.ts, backend/src/utils/userUtils.ts, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
Takes the 3 separate PRs and merges them into a hotfix branch off of ODH 2.1.
- #488 
- #501 
- #502
/cc @lucferbux @cfchase @jkoehler-redhat @LaVLaS
=> 2.1 hotfix security

backend/src/routes/api/nb-events/index.ts
Sync with main for another security fix.
/cc @cfchase @lucferbux
=> Secure nb-events endpoint (#510)

backend/src/routes/api/notebooks/index.ts, backend/src/routes/api/rolebindings/index.ts, backend/src/routes/api/secrets/index.ts, backend/src/utils/adminUtils.ts, backend/src/utils/route-security.ts
Continue improvements to the v2.1-hotfix branch needs to be kept up with in `main`.
- Drop all notebook fetch call, wasn't used
- Drop logic to allow Dashboard ns to be more open
- Prevent Admin from getting extra privs when pulling secrets
/cc @lucferbux @DaoDaoNoCode @dlabaj
=> Add additional route security

backend/src/utils/route-security.ts
- Implement a bit more security for namespaces (no one should make direct requests to a namespace that is not ours).
- Fix admin access, they need to interact with secrets to impersonate and spawn notebooks
=> Improve Admin Access & Disallow Outside Namespaces

backend/src/routes/api/groups-config/index.ts, backend/src/routes/api/status/index.ts, backend/src/utils/route-security.ts, backend/src/utils/userUtils.ts
Fixes #360 
1. Install this image.
2. Deploy in the cluster.
3. Force an oauth proxy error.
4. Check that you reach the error page.
=> Remove logic - kube:admin as default username

backend/src/routes/api/notebooks/notebookUtils.ts
Closes #507 
1. Create a notebook
2. Watch the ready containers on the cluster for the notebook pod
3. See the success of starting only when there are 2/2 containers ready
=> Check notebook status by container statuses instead of pod phase

frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx, frontend/src/pages/notebookController/screens/server/StartServerModal.tsx, frontend/src/utilities/notebookControllerUtils.ts
Part of: #508 
Continuation of #521 
Speed of requests and the modal showing speed have been significantly improved. Hopefully this helps spinning notebooks up better on RHODS.
Testing the time on spawning the Notebook through the usage of the web api calls and how many concurrently happen
=> Improve Spawner Speed by Batching Requests

backend/src/routes/api/health/index.ts, backend/src/utils/requestUtils.ts, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
Resolves: #546
See the issue for what happened. Simple fixes to address them.
Manually -- as noted on the ticket. Not sure how to generate this on a live build.
=> Improved spawner errors

frontend/src/pages/notebookController/screens/server/StartServerModal.tsx, frontend/src/types.ts, frontend/src/utilities/notebookControllerUtils.ts
Closes #525 
This is the repeat PR of #533 because I took over this issue. We can close that PR if the approvers and reviewers think one is OK.
Need to test on a cluster with the auto scale-up feature.
Show an info alert if the current event is `TriggeredScaleUp`.
=> Add TriggeredScaleUp event and info alert

README.md, manifests/base/kustomization.yaml
Updates image references to replace
N/A
Information is clear and concise
=> Update imagetag names documentation to reflect `nightly` image builds

manifests/base/deployment.yaml
=> Increase Deployment replicas to 5

backend/src/routes/api/notebooks/notebookUtils.ts, backend/src/routes/api/route/index.ts, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx, frontend/src/pages/notebookController/screens/server/StartServerModal.tsx, frontend/src/services/routeService.ts, frontend/src/utilities/notebookControllerUtils.ts
Resolves: #549 
Work was coded for the 2.1-hotfix: #532 
Couple gaps we needed to close for ODH in general and the RHODS infra.
Just testing the Notebook creation is all that is needed.
=> Catch up main

backend/src/routes/api/groups-config/index.ts, backend/src/routes/api/health/healthUtils.ts, backend/src/routes/api/health/index.ts, backend/src/routes/api/notebooks/index.ts, backend/src/routes/api/notebooks/notebookUtils.ts, backend/src/routes/api/rolebindings/index.ts, backend/src/routes/api/route/index.ts, backend/src/routes/api/status/index.ts, backend/src/utils/requestUtils.ts, backend/src/utils/route-security.ts, backend/src/utils/userUtils.ts, frontend/src/app/App.tsx, frontend/src/app/HeaderTools.tsx, frontend/src/app/appUtils.ts, frontend/src/pages/notebookController/SetupCurrentNotebook.tsx, frontend/src/pages/notebookController/notebookControllerContextTypes.ts, frontend/src/pages/notebookController/screens/server/NotebookServer.tsx, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx, frontend/src/pages/notebookController/screens/server/StartServerModal.tsx, frontend/src/pages/notebookController/screens/server/useSpawnerNotebookModalState.ts, frontend/src/services/routeService.ts, frontend/src/utilities/notebookControllerUtils.ts, frontend/src/utilities/useWatchDashboardConfig.tsx, frontend/src/utilities/useWatchNotebooksForUsers.tsx, manifests/base/deployment.yaml
Addressing hot fix bugs against our 2.1 version of the ODH Dashboard.
Directly for the RHODS 1.16 rebuild.
=> 2.1 hotfix bugs

frontend/src/pages/clusterSettings/ClusterSettings.tsx
=> Change tolerations text to avoid mislead

data/feature.json
Fixes issue #561  by adding back feature.json
=> Issue 561 - Fix for feature.json.

manifests/base/role.yaml
Follow up #243 
Deploying the actual code will fail, since the serviceaccount cannot list/update/get the new cards created. To test this fix.
1. Deploy latest image: podman pull quay.io/opendatahub/odh-dashboard:nightly
2. Access to the dashboard.
3. There won't be any application
Now build an image with this codebase and update the deployment:
1. Deploy it
2. Access to the dashboard.
3. You should see all the applications.
=> Add permissions for CRD

backend/src/routes/api/notebooks/index.ts, backend/src/utils/route-security.ts
=> Fix sanitization

.github/dependabot.yml
Adjusting the target branch of dependabot, see conversation in #377
=> Adjust dependabot's target branch

frontend/src/pages/notebookController/const.ts, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx
Resolves:#586
Adds validation of Environment variable name input field
1. Access notebook controller spawner and add custom enivorment variables
2. Test names that start with digits or contain characters that are not valid
=> Add regex validation for enviroment variable name

frontend/src/api/index.ts, frontend/src/api/models/openShift.ts, frontend/src/api/network/builds.ts, frontend/src/api/network/imageStreams.ts, frontend/src/api/network/notebooks.ts, frontend/src/app/App.tsx, frontend/src/k8sTypes.ts, frontend/src/pages/projects/ProjectViewRoutes.tsx, frontend/src/pages/projects/components/GenericSidebar.tsx, frontend/src/pages/projects/screens/detail/ProjectDetails.tsx, frontend/src/pages/projects/screens/detail/WorkspacesList.tsx, frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx, frontend/src/pages/projects/screens/spawner/FormFooter.tsx, frontend/src/pages/projects/screens/spawner/NameDescriptionField.tsx, frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx, frontend/src/pages/projects/screens/spawner/const.ts, frontend/src/pages/projects/screens/spawner/deploymentSize/ContainerSizeSelector.tsx, frontend/src/pages/projects/screens/spawner/imageSelector/ImageSelectorField.tsx, frontend/src/pages/projects/screens/spawner/imageSelector/ImageStreamPopover.tsx, frontend/src/pages/projects/screens/spawner/imageSelector/ImageStreamSelector.tsx, frontend/src/pages/projects/screens/spawner/imageSelector/ImageVersionSelector.tsx, frontend/src/pages/projects/screens/spawner/imageSelector/ImageVersionTooltip.tsx, frontend/src/pages/projects/screens/spawner/spawnerUtils.ts, frontend/src/pages/projects/screens/spawner/types.ts, frontend/src/pages/projects/screens/spawner/useBuildStatuses.ts, frontend/src/pages/projects/screens/spawner/useImageStreams.ts, frontend/src/pages/projects/screens/spawner/useNotebookSize.ts, frontend/src/pages/projects/utils.ts, frontend/src/types.ts, frontend/src/utilities/utils.ts
=> Add part of spawner page

backend/src/routes/api/notebooks/utils.ts, backend/src/typeHelpers.ts, backend/src/types.ts, backend/src/utils/notebookUtils.ts, backend/src/utils/route-security.ts, backend/src/utils/userUtils.ts, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx, frontend/src/services/notebookService.ts, frontend/src/types.ts
Follow up of #587 
* Removed URL from the data types in `notebook` endpoint.
* General improvements requested.
1. Create a new deployment.
2. Open the notebook spawner.
3. Create a new notebook.
4. Check all the fields are filled as expected.
=> Improvements to #587

frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx, frontend/src/pages/projects/notebook/StopNotebookConfirmModal.tsx, frontend/src/pages/projects/notebook/useStopNotebookModalAvailability.ts, frontend/src/pages/projects/screens/detail/workspaces/WorkspaceTableRow.tsx
Resolves: #662 
Added a stop modal alongside the toggle button.
=> Stop Notebook Confirmation Modal

frontend/src/api/network/notebooks.ts, frontend/src/pages/projects/notebook/DeleteNotebookModal.tsx, frontend/src/pages/projects/notebook/useProjectNotebooks.ts, frontend/src/pages/projects/screens/detail/workspaces/WorkspaceTable.tsx, frontend/src/pages/projects/screens/detail/workspaces/WorkspaceTableRow.tsx, frontend/src/pages/projects/screens/detail/workspaces/WorkspacesList.tsx
Resolves: #494 
Allows for deleting of the notebook.
=> Delete Notebook Modal

backend/src/routes/api/k8s/index.ts, backend/src/routes/api/k8s/pass-through.ts, backend/src/routes/api/prometheus/index.ts, backend/src/routes/api/status/statusUtils.ts, backend/src/types.ts, backend/src/utils/directCallUtils.ts, backend/src/utils/prometheusUtils.ts, frontend/src/api/index.ts, frontend/src/api/prometheus/pvcs.ts, frontend/src/api/prometheus/usePrometheusQuery.ts, frontend/src/k8sTypes.ts, frontend/src/pages/projects/components/StorageSizeBars.tsx, frontend/src/types.ts, frontend/src/utilities/number.ts
Resolves #668 
Sets up the inUse value of the storages using Prometheus in a pass-through fashion.
Should be easy to extend to future use-cases.
Add a workspace with a PVC.
=> Prometheus connection for inUse storage value

frontend/src/pages/ApplicationsPage.scss, frontend/src/pages/ApplicationsPage.tsx, frontend/src/pages/projects/screens/detail/ProjectDetails.tsx, frontend/src/pages/projects/screens/projects/useUserProjects.ts, frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
Added breadcrumb to project detail and spawner page.  Fixes issue #674 
Verified that bread crumb navigation worked on pages above.
=> Add breadcrumb to project detail and spawner page.

frontend/src/api/index.ts, frontend/src/api/models/k8s.ts, frontend/src/api/network/events.ts, frontend/src/k8sTypes.ts, frontend/src/pages/projects/notebook/NotebookRouteLink.tsx, frontend/src/pages/projects/notebook/NotebookStatusPopover.tsx, frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx, frontend/src/pages/projects/notebook/StartNotebookModal.tsx, frontend/src/pages/projects/notebook/service.ts, frontend/src/pages/projects/notebook/types.ts, frontend/src/pages/projects/notebook/useRefreshNotebookUntilStart.ts, frontend/src/pages/projects/notebook/useWatchNotebookEvents.ts, frontend/src/pages/projects/notebook/utils.ts
=> Add status tooltip and start notebook modal

frontend/src/api/network/notebooks.ts, frontend/src/api/network/pvcs.ts, frontend/src/k8sTypes.ts, frontend/src/pages/projects/ProjectDetailsContext.tsx, frontend/src/pages/projects/components/PVSizeField.tsx, frontend/src/pages/projects/const.ts, frontend/src/pages/projects/notebook/ListNotebookState.tsx, frontend/src/pages/projects/notebook/service.ts, frontend/src/pages/projects/notebook/utils.ts, frontend/src/pages/projects/pvc/AddNotebookStorage.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookList.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookTable.tsx, frontend/src/pages/projects/screens/detail/storage/ConnectExistingNotebook.tsx, frontend/src/pages/projects/screens/detail/storage/ExistingConnectedNotebooks.tsx, frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx, frontend/src/pages/projects/screens/detail/storage/StorageList.tsx, frontend/src/pages/projects/screens/detail/storage/StorageTable.tsx, frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx, frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/EnvironmentVariables.tsx, frontend/src/pages/projects/screens/spawner/storage/AddExistingStorageField.tsx, frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx, frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx, frontend/src/pages/projects/screens/spawner/storage/useAvailablePvcSize.ts, frontend/src/pages/projects/screens/spawner/storage/useAvailablePvcs.ts, frontend/src/pages/projects/screens/spawner/storage/utils.ts, frontend/src/pages/projects/types.ts, frontend/src/utilities/utils.ts
Resolve most of the PVC problems.
TODO: Delete PVC when it's binding with a notebook.
=> Improve storage section features and bug fix

backend/src/routes/api/gpu/index.ts, frontend/src/api/network/pvcs.ts, frontend/src/pages/projects/components/DeleteModal.tsx, frontend/src/pages/projects/notebook/DeleteNotebookModal.tsx, frontend/src/pages/projects/pvc/DeletePVCModal.tsx, frontend/src/pages/projects/pvc/useNotebookPVCItems.ts, frontend/src/pages/projects/screens/detail/ProjectDetails.tsx, frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTableRow.tsx, frontend/src/pages/projects/screens/detail/data-connections/DeleteDataConnectionModal.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx, frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx, frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx, frontend/src/pages/projects/screens/projects/DeleteProjectModal.tsx, frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx, frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx, frontend/src/pages/projects/screens/spawner/deploymentSize/ContainerSizeSelector.tsx, frontend/src/pages/projects/screens/spawner/imageSelector/ImageSelectorField.tsx
See commit messages for every bug fix or feature.
=> Fixes for DSG

backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts, backend/src/routes/api/images/imageUtils.ts, backend/src/routes/api/validate-isv/validateISV.ts, backend/src/utils/constants.ts, backend/src/utils/deployment.ts, backend/src/utils/envUtils.ts, backend/src/utils/notebookUtils.ts, frontend/src/api/network/notebooks.ts, frontend/src/pages/projects/components/DeleteModalConnectedAlert.tsx, frontend/src/pages/projects/notebook/NotebookImagePackageDetails.tsx, frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx, frontend/src/pages/projects/notebook/service.ts, frontend/src/pages/projects/pvc/DeletePVCModal.tsx, frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx, frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTableRow.tsx, frontend/src/pages/projects/screens/detail/data-connections/DeleteDataConnectionModal.tsx, frontend/src/pages/projects/screens/detail/data-connections/data.ts, frontend/src/pages/projects/screens/detail/notebooks/NotebookTable.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx, frontend/src/pages/projects/screens/detail/notebooks/data.ts, frontend/src/pages/projects/screens/detail/storage/StorageTable.tsx, frontend/src/pages/projects/screens/detail/storage/StorageTableRow.tsx, frontend/src/pages/projects/screens/spawner/deploymentSize/ContainerSizeSelector.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/EnvTypeSelectField.tsx, frontend/src/pages/projects/screens/spawner/imageSelector/ImageStreamSelector.tsx, frontend/src/pages/projects/screens/spawner/imageSelector/ImageVersionSelector.tsx, frontend/src/pages/projects/utils.ts
See the commit messages for details.
=> Fixes and features for DSG

OWNERS
Change OWNERS file to match the current working members.
=> Update Root Owners File

frontend/src/api/models/odh.ts, frontend/src/api/network/deployedModel.ts, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/screens/types.ts
Add support to fetch deployed models to avoid blockers in development
=> Enable support to fetch deployed models

backend/src/routes/api/envs/index.ts, backend/src/routes/api/groups-config/index.ts, backend/src/routes/api/notebooks/index.ts, backend/src/routes/api/status/index.ts, backend/src/utils/envUtils.ts, backend/src/utils/notebookUtils.ts, backend/src/utils/userUtils.ts
Follow up on #667 
Fixes some of the messages thrown since they were misformed. 
When fixing #667, I messed up the code and I push the wrong code, this fixes the solution.
=> Fix Oauth Error, now catching the status code

frontend/src/api/index.ts, frontend/src/api/models/odh.ts, frontend/src/api/network/inferenceServices.ts, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/screens/global/InferenceServiceEndpoint.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceListView.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/global/ModelServingGlobal.tsx, frontend/src/pages/modelServing/screens/global/ServeModelButton.tsx, frontend/src/pages/modelServing/screens/global/data.ts, frontend/src/pages/modelServing/screens/global/useInferenceServices.ts, frontend/src/pages/modelServing/screens/global/useRouteForInferenceService.ts, frontend/src/pages/modelServing/screens/global/utils.ts, frontend/src/pages/projects/components/SearchField.tsx
Closes #653 
Hide serving cluster for now.
=> Add Deployed model table and row to the global page

frontend/src/api/network/projects.ts, frontend/src/api/network/roleBindings.ts, frontend/src/api/network/secrets.ts, frontend/src/api/network/serviceAccounts.ts, frontend/src/api/network/servingRuntimes.ts, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeReplicaSection.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeExpandedField.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenInput.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenSection.tsx, frontend/src/pages/modelServing/screens/projects/useServingRuntimes.ts, frontend/src/pages/modelServing/screens/projects/utils.ts, frontend/src/pages/modelServing/utils.ts
Fixes #647 
* Fixed some naming conventions and adapted to dsg
* Display the model server deployed in the namespace
1. Deploy the image
2. Go to DSG section
3. Create new project
4. Create a new model server
5. Check that a new model server is deployed and the modal to deploy a server is enabled
=> Add support to deployed server

frontend/src/api/network/notebooks.ts
Fixes #730 
1. Building a new image
2. Deploying it
3. Create a new notebook in dsg
4. Ensure is protected by Oauth Proxy.
=> Fix authentication to access dsg notebooks

frontend/src/api/network/inferenceServices.ts, frontend/src/pages/modelServing/screens/global/DeleteInferenceServiceModal.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceEndpoint.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceListView.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeDetails.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableExpandedSection.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx, frontend/src/pages/projects/screens/detail/ProjectDetails.tsx
Closes #654 
Add a modal to support deleting deployed model.
Deploy a model, and try to delete it in both the project detail page and the global model serving page.
=> Add delete InferenceService modal

frontend/src/pages/projects/notebook/NotebookRouteLink.tsx, frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx, frontend/src/pages/projects/notebook/StopNotebookConfirmModal.tsx, frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTableRow.tsx, frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx, frontend/src/pages/projects/screens/spawner/imageSelector/ImageStreamSelector.tsx
=> [DSG]: fix ux issues

frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/screens/global/InferenceServiceEndpoint.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceProject.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/global/useConnectedProject.ts, frontend/src/pages/modelServing/screens/projects/DeleteServingRuntimeModal.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeDetails.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTable.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx
=> Add delete model server modal

frontend/src/pages/projects/screens/spawner/environmentVariables/GenericKeyValuePairField.tsx
Resolves: #754 
Minor text change requested by QE to improve the UX flow of envs.
=> Update env text

frontend/src/api/network/configMaps.ts, frontend/src/api/network/secrets.ts, frontend/src/pages/projects/notebook/DeleteNotebookModal.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/EnvConfigMap.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/EnvDataTypeField.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/EnvSecret.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/EnvironmentVariables.tsx, frontend/src/pages/projects/types.ts
Resolves: #756 
Cleans up configmaps and secrets that were created part of the workbench's env flow
=> Delete configmaps & secrets with the notebook

frontend/src/api/network/secrets.ts, frontend/src/pages/projects/dataConnections/const.ts, frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx, frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTable.tsx, frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTableRow.tsx, frontend/src/pages/projects/screens/detail/data-connections/ManageDataConnectionModal.tsx, frontend/src/pages/projects/screens/detail/data-connections/utils.ts, frontend/src/pages/projects/types.ts
Closes #738 
Create a data connection -> Edit -> Update.
=> Support editing data connections

backend/src/plugins/kube.ts, backend/src/utils/resourceUtils.ts
Startup cleanup script for #744 
Follow up on #763
=> Cleanup display names on projects

frontend/src/pages/clusterSettings/ClusterSettings.tsx, frontend/src/pages/projects/components/PVSizeField.tsx, frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx, frontend/src/pages/projects/notebook/utils.ts, frontend/src/pages/projects/pvc/MountPathField.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookStorageBars.tsx, frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx, frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx, frontend/src/pages/projects/screens/spawner/spawnerUtils.ts, frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx, frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx, frontend/src/pages/projects/types.ts
Resolves: #768 
Some misc feedback we got from QE, UX & PM.
- Minor text changes were also made where applicable to help with wording consistency
- Updated the Spawner Page in DSG not to use Ephemeral and assume a like-named resource name for the PVC that is created as part of the flow
- Added note to showcase that PVCs in Create Workbench flow mount to the root
- Support folder mount names in expanded Workbenches
- Added a pointer finger cursor for the "starting..." text that Workbenches show; live status is hidden behind here
Images:
=> Misc Improvements for DSG

frontend/src/pages/projects/notebook/NotebookRouteLink.tsx, frontend/src/pages/projects/notebook/useRouteForNotebook.ts
Closes #767 
If error, re-fetch the notebook route in 1 second until we get the notebook route.
Also, move the error icon outside of the link button, so the user could see the error message when hovering over it.
=> Refetch notebook route if error

frontend/src/api/network/secrets.ts, frontend/src/api/network/servingRuntimes.ts, frontend/src/pages/modelServing/screens/global/InferenceServiceEndpoint.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionSection.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceFrameworkSection.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenInput.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTable.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTokens.tsx, frontend/src/pages/modelServing/screens/projects/utils.ts, frontend/src/pages/modelServing/screens/types.ts, frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsList.tsx, frontend/src/pages/projects/screens/detail/data-connections/useDataConnections.ts
Fixes #663 
1. Create a new dsg project
2. Create a new model server
3. Edit the model server
4. Check that the values are changed
**Edit doesn't support token deletion at the moment**
=> Add support for serving runtime edit

frontend/src/api/network/notebooks.ts, frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx, frontend/src/pages/projects/screens/spawner/EditSpawnerPage.tsx, frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx, frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/useNotebookEnvVariables.tsx, frontend/src/pages/projects/screens/spawner/service.ts, frontend/src/pages/projects/screens/spawner/spawnerUtils.ts, frontend/src/pages/projects/screens/spawner/storage/AddExistingStorageField.tsx, frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx, frontend/src/pages/projects/screens/spawner/storage/useAvailablePvcs.ts, frontend/src/pages/projects/screens/spawner/storage/useNotebookRootStorage.ts, frontend/src/pages/projects/screens/spawner/storage/utils.ts, frontend/src/pages/projects/types.ts
=> Add editing environment variables and storage features for notebook

frontend/src/pages/modelServing/screens/projects/utils.ts
=> Fix dependency array

backend/src/utils/resourceUtils.ts
Resolves: #775 
Resolves a weird situation when OdhDashboard references a csv that changes version.
=> Override and disable applications when we have errors fetching

frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx, frontend/src/pages/modelServing/screens/projects/utils.ts
=> Enable token deletion

manifests/crd/odh-dashboard-crd.yaml, manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
=> Sync crds with downstream

frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/global/utils.ts, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionExistingField.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionSection.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTableRow.tsx, frontend/src/pages/modelServing/screens/types.ts, manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Fix #788 
1. Create a new project
2. Create a new model server, check that there's no reference to metrics
3. Once deployed, check that there's no metrics reference
4. Create a new inference server, check that all the fields are aligned
5. Once created, check that the status icon are updated with the desired icons.
=> UI enhancements for model serving

frontend/src/api/network/secrets.ts
Fixes #799
1. Create a new DSG Project
2. Create a new model server
3. Deploy a new model with a new data connection
4. Check that the `storage-config` secret includes the `type` field
=> Add missing annotation for data connection secret

frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx, frontend/src/types.ts, frontend/src/utilities/segmentIOUtils.tsx
=> Add workbench created and updated telemetry events

frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx, frontend/src/pages/notebookController/screens/server/StopServerModal.tsx, frontend/src/services/notebookService.ts, frontend/src/types.ts
Fix #835 
* Omitted username field in spawner page for regular calls, as it should only be used when impersonating
* Revamped the impersonatedUsername field
1. Log in Dashboard > Enabled as regular user 
2. Launch Jupyter and try to spawn a notebook
3.Now it should be able to create a notebook
=> Fix bug that prevented regular users to spawn notebooks.

frontend/src/pages/projects/notebook/NotebookStatusPopover.tsx, frontend/src/pages/projects/notebook/NotebookStatusText.scss, frontend/src/pages/projects/notebook/NotebookStatusText.tsx, frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx
Closes #749 
Try to create a notebook, check the new style of `starting...` text. If there are some errors, there will be an error icon next to the text, you can also hover it to get the brief problem.
=> Support better starting... status

frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeReplicaSection.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeExpandedField.tsx
Fix #818
1. Create a new DSG Project
2. Open the Model Server Modal
3. Validate the number input of number of replicas
4. Select Size as "Custom"
5. Validate the rest of NumberInputs
=> Improve NumberInput validation logic in ServingRuntime Modal

frontend/src/api/network/servingRuntimes.ts
This fix will allow the installation of the image in disconnected environment.
1. Create a new DSG project
2. Create a new model server
3. Check that the image works
=> Change servingruntime image tag for sha

Dockerfile, frontend/config/webpack.dev.js, frontend/package-lock.json, frontend/package.json
Fix #859
1. Install this image: quay.io/lferrnan/odh-dashboard-test:new-build-deps
2. Check that is currently working
=> fix: remove old sass dependencies

README.md, docs/releases.md, docs/triaging.md
Adding documented steps for us to do a release & how we do triage.
=> Add release notes & triage notes

frontend/src/pages/notebookController/screens/server/StopServerModal.tsx
=> Fix issue when trying to stop notebook with regular user

frontend/src/pages/projects/notebook/useRouteForNotebook.ts
Close #884 
See the issue, using the same way to test.
=> Unload notebook route hook error data when success

frontend/src/pages/modelServing/screens/global/InferenceServiceListView.tsx, frontend/src/pages/projects/screens/projects/ProjectListView.tsx
Closes #887 
Create more than 10 projects on project page, and the try to change the pages.
=> fix pagination issue for projects table and inference service table

frontend/package-lock.json, frontend/package.json, frontend/src/api/network/notebooks.ts, frontend/src/pages/projects/screens/detail/notebooks/useNotebookGPUNumber.ts, frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx, frontend/src/types.ts, frontend/src/utilities/const.ts, frontend/src/utilities/imageUtils.ts
Closes #881 
Since I don't have a GPU cluster, I only did some fake tests and checked the Notebook CR, it works.
1. Go to the dashboard config CR, set `notebookController -> gpuSetting: '3'`
2. Go to the spawner page, you will see the GPU number dropdown
3. Select the GPU number
4. Go to check the Notebook CR
5. Edit the workbench and set the GPU to 0
6. Check the Notebook CR again
=> Allow users to edit workbench GPU to 0

frontend/src/pages/projects/notebook/useRouteForNotebook.ts
Closes #895 
See the issue description, the same way to test.
=> Add fetching notebook route interval and properly unload it

frontend/src/pages/projects/components/NotebookRestartAlert.tsx, frontend/src/pages/projects/notebook/useWillNotebooksRestart.ts, frontend/src/pages/projects/pvc/AddNotebookStorage.tsx, frontend/src/pages/projects/screens/detail/data-connections/ManageDataConnectionModal.tsx, frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx, frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
Closes #847 
Check the following page/modals:
- Editing workbench
- Add/Edit storage modal
- Add/Edit data connections modal
=> Alert user when the action could lead to the restart of the notebooks

frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx, frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx, frontend/src/types.ts
Closes #912 
Go to the dev console in your browser, try to start/stop the workbenches, and see the telemetry events that are fired.
=> Add telemetry events when starting/stopping workbenches

docs/triaging.md
Adds more details to triaging.
cc @lucferbux
=> Add 'visual changes' label to triaging

frontend/package-lock.json, frontend/src/__tests__/ExploreApplications.spec.tsx, frontend/src/app/HeaderTools.tsx, frontend/src/components/OdhAppCard.tsx, frontend/src/components/OdhExploreCard.tsx, frontend/src/components/SupportedAppTitle.tsx, frontend/src/pages/notebookController/screens/admin/NotebookAdminControl.tsx, frontend/src/pages/projects/screens/projects/EmptyProjects.tsx
Resolves: #928 
Commits cover different areas.
=> AXE: Initial pass fixing accessibility

frontend/src/pages/clusterSettings/ClusterSettings.tsx, frontend/src/pages/groupSettings/GroupSettings.tsx, frontend/src/utilities/useNotification.ts, frontend/src/utilities/useWatchGroups.tsx
Closes: #894
Update the save information to help convey that we have multiple pods and settings may not propagate immediately (and may take up to 2 mins).
1. Be an admin ... 
2. Change Cluster settings or Group settings and save
=> Update Settings (Cluster & Group) page notifications

OWNERS
Maros is not on the Dashboard code effort anymore
Gage has joined the team
=> Add Gage and remove Maros as reviewers

frontend/src/app/NavSidebar.tsx
Closes #848 
Click the side nav and go to the project details page, see if the nav link is still highlighted.
=> Add highlight nav to all pages

backend/src/routes/api/cluster-settings/clusterSettingsUtils.ts, backend/src/utils/constants.ts, docs/dashboard_config.md
Closes #285 
Try to get rid of the `disableTracking` field in the dashboard config to see if the telemetry tracking is disabled by default.
=> Set telemetry user tracking default to be disabled

frontend/__mocks__/mockEnabledApplications.ts, frontend/__mocks__/mockExploreApplications.ts, frontend/src/components/OdhAppCard.tsx, frontend/src/components/OdhExploreCard.tsx, frontend/src/components/OdhExploreCardTypeBadge.tsx, frontend/src/types.ts, manifests/crd/odhapplications.dashboard.opendatahub.io.crd.yaml
Closes #863 
Add a tooltip as described in the issue, and updated the CRD as well. At the same time, updated part of the code to make the badge show the correct color that they should be.
Go to the explore page and hover over the type badges.
=> Add tooltip to the explore card types

backend/src/routes/api/gpu/gpuUtils.ts, backend/src/routes/api/prometheus/index.ts, backend/src/types.ts, backend/src/utils/prometheusUtils.ts, frontend/package-lock.json, frontend/package.json, frontend/src/api/prometheus/pvcs.ts, frontend/src/api/prometheus/serving.ts, frontend/src/api/prometheus/usePrometheusQuery.ts, frontend/src/api/prometheus/usePrometheusQueryRange.ts, frontend/src/api/prometheus/useQueryRangeResourceData.ts, frontend/src/pages/ApplicationsPage.tsx, frontend/src/pages/modelServing/ModelServingRoutes.tsx, frontend/src/pages/modelServing/screens/const.ts, frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/metrics/MetricsChart.tsx, frontend/src/pages/modelServing/screens/metrics/MetricsPage.tsx, frontend/src/pages/modelServing/screens/metrics/MetricsPageToolbar.tsx, frontend/src/pages/modelServing/screens/metrics/ModelServingMetricsContext.tsx, frontend/src/pages/modelServing/screens/metrics/ModelServingMetricsWrapper.tsx, frontend/src/pages/modelServing/screens/metrics/utils.ts, frontend/src/pages/modelServing/screens/projects/DetailsPageMetricsWrapper.tsx, frontend/src/pages/modelServing/screens/types.ts, frontend/src/pages/projects/ProjectViewRoutes.tsx, frontend/src/types.ts, frontend/src/utilities/time.ts, frontend/src/utilities/useContextResourceData.tsx, frontend/src/utilities/utils.ts
Closes #656 
Closes #825 
Closes #829 
Did 3 things:
1. Updated the backend API based on the host we called and the way we want to query (`query` or `query_range`)
2. Created a common context for the metrics page to use, and created 2 wrappers for the project details page and the global model serving page
3. Created metrics page, which gets data and renders them.
Go to dashboard -> Click the name of a workable model -> You will see the charts
=> Add inference service metrics page

frontend/src/components/OdhAppCard.tsx, frontend/src/components/OdhCard.scss, frontend/src/components/OdhExploreCard.tsx, frontend/src/components/OdhListItem.scss
Closes #958 
Install some third-party support applications on your cluster and go to the dashboard explore page, to check if all the badges are grey background.
=> Remove warning status from the app card badge

docs/dashboard_config.md
Update documentation with new flags in `odhDashboardConfig` CR
=> Update odh documentation

frontend/src/app/App.tsx, frontend/src/redux/actions/actions.ts, frontend/src/utilities/useDetectUser.ts
Close #964 
Fetch the status endpoint at the regular `POLL_INTERVAL`.
Login to the dashboard -> Go to the developer console and open the Network tab -> Check if the `status` endpoint is called every 30 seconds.
=> Periodically fetch kube status

Dockerfile
Follow up of #1004 
There was an issue that prevented enabled applications to be displayed and error trying to access the log file.
1. Deploy `quay.io/lferrnan/odh-dashboard:test-dockerfile`
2. Check that there are recommended apps
3. Check that there are not log errors
=> Fix issues with log access and enabled applications

OWNERS
Adding Alex as a reviewer so the bot picks him up as an auto reviewer.
=> Add Alex as a reviewer

backend/src/utils/constants.ts, frontend/src/k8sTypes.ts, frontend/src/pages/projects/screens/spawner/const.ts, frontend/src/pages/projects/screens/spawner/spawnerUtils.ts, frontend/src/utilities/imageUtils.ts
Fix #990 
Ensure changes on OOTB images with support of n -1 version is working in the UI.
1. You need a second tag in the notebooks such as this [pr](https://github.com/atheo89/odh-manifests/commit/1046f453f7bbfc5bfd749e7c9af54a181aca3f59)
2. Add the `opendatahub.io/workbench-image-recommended: 'true'` tag to one of the notebook's images such as 's2i-minimal-notebook:py3.8-v1.3.1'
3. Check that the UI is displaying the recommended label
=> Update workbench image recommended tag

.github/workflows/storybook-tests.yml, frontend/.storybook/preview.js, frontend/package-lock.json, frontend/package.json, frontend/src/pages/projects/screens/projects/ProjectView.stories.tsx
closes: https://github.com/opendatahub-io/odh-dashboard/issues/984
This adds storybook ci testing as a github action. The action will build storybook, run the build, run the test-runner, and if all passes, will pass the ci
1. fork the repo
2. make a not breaking pr
3. check that the storybook ci runs asn passes
4. make another pr with a change that breaks the test 
5. check that storybook ci runs and fails
im not going to test the test
=> Add storybook test github action

frontend/config/webpack.dev.js, frontend/config/webpack.prod.js, frontend/package-lock.json, frontend/package.json, frontend/src/concepts/pipelines/TestPipelines.tsx, frontend/src/concepts/pipelines/topology/PipelineTopology.tsx, frontend/src/concepts/pipelines/topology/PipelineVisualizationSurface.tsx, frontend/src/concepts/pipelines/topology/const.ts, frontend/src/concepts/pipelines/topology/factories.ts, frontend/src/concepts/pipelines/topology/types.ts, frontend/src/concepts/pipelines/topology/useTopologyController.ts, frontend/src/concepts/pipelines/topology/utils.ts
Closes: #926 
Adds Topology to the Dashboard and wires up some initial Pipeline Topology infrastructure.
Mounted examples in the `TestPipelines` page.
cc @kywalker-rh
Head on over to `<host>/pipelines/<namespace>`. 
No functionality to change things... 3 examples though (see above for screenshots).
None, no tests at this time.
=> Pipeline Topology Infrastructure

frontend/src/pages/modelServing/screens/projects/utils.ts
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1027
changed `data.replicas || 1` to data.replicas ?? `1`
because replicas is an int, OR operator (`||`) will treat the ints as boolean values, effectively running the boolean `0 || 1` = `1`. 
2. Create a runtime with 0 replicas
3. Edit the runtime
@DaoDaoNoCode has a PR for testing the page. Will wait until that that is in to create this test 
no UI change
=> fixed exisiting replica bug

CONTRIBUTING.md, README.md
=> Update README and CONTRIBUTING formatting

Dockerfile
Fixes #1123 
1. Create a new build
2. Deploy it and check there is no error
=> Fix odh release

frontend/.storybook/preview.js
n/a. comes from internal conversation
color contrast is not a reliable type of violation for axe to identify correctly. It has been giving many false positives in our UI on modals.
run storybook test locally and check ProjectView - Edit Project accessibility test. There should be no incomplete violations.
color contrast will no longer be tested anyehere
=> color-contrast rule disabled axe

frontend/src/app/Header.tsx, frontend/src/pages/notebookController/screens/server/StartServerModal.tsx
Closes #1102 
Start server modal before:
Start server modal after:
Administration screen before:
Administration screen after:
Stop server modal - no violations:
**Note: "Unique Landmarks" issue will be resolved with patternfly v5 release, noted in JIRA ticket**
=> Fix a11y issues in applications

frontend/src/concepts/pipelines/content/pipelinesTable/PipelinesTable.tsx, frontend/src/concepts/pipelines/content/pipelinesTable/PipelinesTableExpandedRow.tsx, frontend/src/concepts/pipelines/content/pipelinesTable/PipelinesTableRow.tsx, frontend/src/concepts/pipelines/content/pipelinesTable/columns.ts, frontend/src/concepts/pipelines/content/pipelinesTable/expandedRowRenderUtils.tsx, frontend/src/concepts/pipelines/content/pipelinesTable/runRenderUtils.tsx, frontend/src/concepts/pipelines/content/pipelinesTable/utils.ts, frontend/src/concepts/pipelines/kfTypes.ts, frontend/src/utilities/time.ts
Closes: #1058
Adds the expanded Pipeline Runs row.
Once you have your Pipeline Server installed, you get a OOTB Pipeline. Using the Pipeline API UI from Kubeflow, you can trigger runs on it.
No tests yet. Will be covered as followup to the feature.
/cc @kywalker-rh @vconzola @Gkrumbach07 @alexcreasy
=> Pipeline runs

frontend/src/api/pipelines/callTypes.ts, frontend/src/api/pipelines/custom.ts, frontend/src/concepts/pipelines/content/DeletePipelineModal.tsx, frontend/src/concepts/pipelines/content/pipelinesTable/PipelinesTable.tsx, frontend/src/concepts/pipelines/content/pipelinesTable/PipelinesTableRow.tsx, frontend/src/concepts/pipelines/context/PipelinesContext.tsx, frontend/src/concepts/pipelines/kfTypes.ts, frontend/src/concepts/pipelines/types.ts, frontend/src/pages/pipelines/global/pipelines/PipelinesView.tsx, frontend/src/pages/projects/screens/detail/pipelines/PipelinesList.tsx
Closes: #1063
Add the Pipeline Kebab (create run doesn't do anything) and the Delete Pipeline modal.
Have a Pipeline => Delete.
No tests on first pass.
/cc @kywalker-rh @vconzola @Gkrumbach07 @lucferbux
=> Pipeline Table Kebab + Delete Pipeline

frontend/src/api/prometheus/serving.ts, frontend/src/api/prometheus/usePrometheusQueryRange.ts, frontend/src/api/prometheus/useQueryRangeResourceData.ts, frontend/src/pages/ApplicationsPage.tsx, frontend/src/pages/modelServing/ModelServingRoutes.tsx, frontend/src/pages/modelServing/screens/const.ts, frontend/src/pages/modelServing/screens/metrics/BiasTab.tsx, frontend/src/pages/modelServing/screens/metrics/DIRChart.tsx, frontend/src/pages/modelServing/screens/metrics/MetricsChart.tsx, frontend/src/pages/modelServing/screens/metrics/MetricsPage.tsx, frontend/src/pages/modelServing/screens/metrics/MetricsPageTabs.scss, frontend/src/pages/modelServing/screens/metrics/MetricsPageTabs.tsx, frontend/src/pages/modelServing/screens/metrics/MetricsPageToolbar.tsx, frontend/src/pages/modelServing/screens/metrics/ModelServingMetricsContext.tsx, frontend/src/pages/modelServing/screens/metrics/PerformanceTab.tsx, frontend/src/pages/modelServing/screens/metrics/SPDChart.tsx, frontend/src/pages/modelServing/screens/metrics/ScheduledMetricSelect.tsx, frontend/src/pages/modelServing/screens/metrics/TrustyChart.tsx, frontend/src/pages/modelServing/screens/metrics/types.ts, frontend/src/pages/modelServing/screens/metrics/utils.ts, frontend/src/pages/modelServing/screens/types.ts, frontend/src/pages/projects/ProjectViewRoutes.tsx, frontend/src/types.ts
Closes #1001 #1006 #1007 #1008
This completes the feature work for phase 0 of Explainability: Fairness and Bias. Features added:
- Tab based nav with deep linking added to modelServing views
- Charts for displaying both Disparate Inference Ratio and Statistical Parity Distance metrics
- Ability to switch between multiple payloads of the above metrics
- Tooltip displaying definitions of the above metrics
* Deploy updated odh-dashboard to cluster
* Deploy main branch of TrustyAI in same namespace
* Through the dashboard, create a data science project, model server and model
* Send data to trustyAI service
1. Open dashboard
2. Click 'Model Serving' in primary nav
3. In the table of available models, click the model name to open the metrics view
4. Click the bias tab
5. Verify SPD and DIR …
=> Trustyai demo phase0

frontend/src/api/k8s/templates.ts, frontend/src/components/Table.tsx, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAddTemplate.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeContext.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeEditTemplate.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeListView.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeRoutes.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeTableRow.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeView.tsx, frontend/src/pages/modelServing/customServingRuntimes/DeleteCustomServingRuntimeModal.tsx, frontend/src/pages/modelServing/customServingRuntimes/EmptyCustomServingRuntime.tsx, frontend/src/pages/modelServing/customServingRuntimes/utils.ts, frontend/src/utilities/useDraggableTable.ts
Closes #1083 
1. Fix some drag-and-drop issues and remove the debounce for it.
2. Add the "delete" dropdown in the kebab toggle. When you click on it, you can open a deleting modal to delete the serving runtimes
3. Add the "edit" dropdown in the kebab toggle. When you click on it, it will take you to the same page as you adding the serving runtimes, but it will read the current information and map them in the code editor so you can update it.
1. Try to drag and drop to see if there are any bugs
2. Try to create a serving runtime and delete it
3. Try to create a serving runtime and edit it, you can add the `openshift.io/display-name` field in the annotation so it will show the display name. Otherwise, it will show the metadata name.
Will add tests after everything is done.
=> Custom serving runtimes: fix drag problems, add deleting and editing features

frontend/src/api/k8s/secrets.ts, frontend/src/api/pipelines/k8s.ts, frontend/src/components/FieldList.tsx, frontend/src/concepts/pipelines/content/DeletePipelineServerModal.tsx, frontend/src/concepts/pipelines/content/configurePipelinesServer/ConfigurePipelinesServerModal.scss, frontend/src/concepts/pipelines/content/configurePipelinesServer/ConfigurePipelinesServerModal.tsx, frontend/src/concepts/pipelines/content/configurePipelinesServer/DatabaseConnectionField.tsx, frontend/src/concepts/pipelines/content/configurePipelinesServer/DatabaseConnectionInputField.tsx, frontend/src/concepts/pipelines/content/configurePipelinesServer/ObjectStorageSection.tsx, frontend/src/concepts/pipelines/content/configurePipelinesServer/PipelinesDatabaseSection.tsx, frontend/src/concepts/pipelines/content/configurePipelinesServer/const.ts, frontend/src/concepts/pipelines/content/configurePipelinesServer/utils.ts, frontend/src/concepts/pipelines/context/PipelinesContext.tsx, frontend/src/concepts/pipelines/context/index.ts, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/screens/global/ModelServingGlobal.stories.tsx, frontend/src/pages/pipelines/global/pipelines/PipelinesPageHeaderActions.tsx, frontend/src/pages/projects/dataConnections/AWSField.tsx, frontend/src/pages/projects/dataConnections/const.ts, frontend/src/pages/projects/screens/detail/data-connections/utils.ts, frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1060
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1062
Added modals for creating and removing a pipeline server
1. create a new project
2. go to `/pipelines`
3. _Configure pipeline server_
4. create new object storage
5. input **real** aws data connection info
6. configure
7. should configure (might start as an error but this is a bug in error handling)
8. go delete it from the dropdown in the right
n/a for pipelines right now
/cc @kywalker-rh @vconzola @andrewballantyne
=> Configure pipelines modal

frontend/src/components/Table.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeListView.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeTableRow.tsx, frontend/src/pages/modelServing/customServingRuntimes/templatedData.tsx, frontend/src/pages/modelServing/customServingRuntimes/utils.ts, frontend/src/utilities/useDraggableTable.ts
Follow up of https://github.com/opendatahub-io/odh-dashboard/pull/1177, and part of the fix covers #1185 
Revert the Table component, use the draggable hook in the custom serving runtime list view component instead.
Mostly check the code, drag and drop the serving runtimes table, add and delete them and make sure nothing is broken. This PR adds no new features, mainly code refactoring and small bug fixes.
N/A
=> Revert Table and refactor implementation, fix drag issues

frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAddTemplate.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeTableRow.tsx, frontend/src/pages/modelServing/customServingRuntimes/utils.ts
Closes #1180 
All the OOTB serving runtimes will have the label `opendatahub.io/ootb: 'true'` in the Template. You can only clone the serving runtime, but not edit or remove it. If you clone it, it will take you to the adding page with the serving runtime YAML cloned so you can change the name and create a new one.
Also, add a tooltip for the custom serving runtimes so the user could find the K8s name for it.
1. Create a custom serving runtime
2. Add the label `opendatahub.io/ootb: 'true'` to the Template
3. Refresh the dashboard
4. Check the dropdown of the custom serving runtime to see if you can only clone it
5. Click on the clone to see if it copy paste the serving runtime
6. Try to create a new one based on the cloned one
7. Go back to the list and hover the tooltip of the serving …
=> Add support for OOTB runtimes and add tooltip to the name

frontend/config/webpack.common.js, frontend/config/webpack.dev.js, frontend/config/webpack.prod.js
Fixes an issue when building due to webpack plugin misconfiguration
=> Fix code editor monaco plugin for builds

frontend/src/api/k8s/secrets.ts
Fix an issue where assembling error token names was misconfigured
1. Create a new Model Server (Serving Runtime)
2. Edit values
3. Check that is working
=> Fix issue while editing model serving model

backend/src/utils/httpUtils.ts, backend/src/utils/prometheusUtils.ts, frontend/src/api/pipelines/custom.ts, frontend/src/api/pipelines/k8s.ts, frontend/src/concepts/pipelines/content/DeletePipelineServerModal.tsx, frontend/src/concepts/pipelines/content/ViewPipelineServerModal.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/useJobRelatedInformation.ts, frontend/src/concepts/pipelines/content/tables/utils.ts, frontend/src/concepts/pipelines/context/PipelinesContext.tsx, frontend/src/concepts/pipelines/context/index.ts, frontend/src/concepts/pipelines/context/usePipelineNamespaceCR.ts, frontend/src/concepts/pipelines/utils.ts, frontend/src/k8sTypes.ts, frontend/src/pages/pipelines/global/PipelineCoreApplicationPage.tsx, frontend/src/pages/projects/screens/detail/pipelines/PipelinesSection.tsx
Closes: #1222
Misc fixes to help smooth out the first release.
Major ones are:
- Support a better Job => Run on the Triggered Runs table by using Job details in rendering of the rows
- Support a "what if the Data Connection is bad" error state (5mins before we drop into it -- should get better next sprint)
None. https://github.com/opendatahub-io/odh-dashboard/issues/1184
=> Pipeline release fixes

frontend/src/pages/pipelines/global/pipelines/GlobalNoPipelines.tsx
We are removing the visual editor, the wording needs to be updated to not direct users to something we do not provide.
=> Update the visual editor wording

frontend/src/utilities/clusterUtils.ts
Closes: #1232
OpenShift Console links were broken because it built it from the api path -- which is not necessarily the same path to the cluster's console.
Hosting the PR image -- see ticket for reproduction steps.
None.
=> OpenShift Console link fixes

frontend/src/pages/projects/projectSharing/ProjectSharingPermissionSelection.tsx
Closes #1241 
It's a one-liner fix, just the text update.
1. Login to the dashboard as an admin user
2. Go to any of the projects
3. Go to the Permissions tab
4. Click on `Add user` and open the dropdown to select the permission, check if the description of the Edit selection is updated
Text update, N/A.
=> Update Edit description in project permission dropdown

backend/src/routes/api/proxy/index.ts
Closes: #1278 
Passing the `rejectUnauthorized` flag as `false` worked for Prometheus calls -- I imagine it will work here too.
Using OSD -- I have not tested this implementation.
None
=> Add the unauth flag to the proxy pass-through

frontend/src/concepts/pipelines/elyra/utils.ts, frontend/src/pages/pipelines/global/pipelines/GlobalNoPipelines.tsx
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1251
added back text and added a new item to the secret config
go to pipelines page when there are no pipelines os you see the empty view
n/a
=> added back text; added new item to secret config

frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx
Closes #1272 
Fixed this while verifying GPU support.
1. Deploy the dashboard in a cluster with GPU enabled
2. Deploy a new model
3. Try to input a big number outside of 0-max GPU
4. Check that the value will revert to the threshold
This test will be covered in the model serving testing section.
=> Add gpu limits

backend/src/utils/constants.ts
Closes: #1315
On fresh creation of the Dashboard Config (install, or if you delete it manually) Pipelines was not turned on. It should be.
* I deleted a config to test that we reset it to disabled.
* Applied my fix.
* Did it again, and it was enabled.
None
=> Adjust the default of Pipelines to enabled

frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTable.tsx, frontend/src/concepts/projects/ProjectsContext.tsx, frontend/src/pages/projects/components/DeleteModal.tsx, frontend/src/pages/projects/screens/projects/DeleteProjectModal.tsx, frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx, frontend/src/pages/projects/screens/projects/NewProjectButton.tsx, frontend/src/pages/projects/screens/projects/ProjectListView.tsx, frontend/src/utilities/useFetchState.ts
Closes: #1239
Closes: #1240
Cleanup the Project modal:
* Create Project is waiting on the project being fetched -- fetches all projects until the project is available
* Update Project shows errors
* Both Project modals refreshes inside the modal
* Delete modals now wait on closure before clearing the content
Manually. Spent most of the time testing Projects List View and creating, deleting, updating modals.
None
=> Fix Project Create/Update/Delete Modals

frontend/src/concepts/pipelines/content/createRun/RunForm.tsx, frontend/src/concepts/pipelines/content/createRun/const.ts
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1283
navigate to the other project when changing the form.
1. Have two projects
2. Create a pipeline named differently in each
3. Head over to one of the projects' Pipeline Run page
4. Create a Run
5. Switch the dropdown to the other project and view the Pipelines visible
issues have been created to address this
=> navigate on new run form

manifests/modelserving/ovms-gpu-ootb.yaml, manifests/modelserving/ovms-ootb.yaml
Closes #1292 
1. Deploy the updated ootb templates
2. Check that you can select tensorflow as supported runtime
Not added testing, we might include this into the model serving testing too
=> Add tensorflow as supported runtime of onnx ootb

backend/src/routes/api/dashboardConfig/index.ts, backend/src/routes/api/servingRuntimes/index.ts, backend/src/routes/api/templates/index.ts, backend/src/types.ts, frontend/src/api/k8s/dashboardConfig.ts, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAddTemplate.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeContext.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeEnabledToggle.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeListView.tsx, frontend/src/pages/modelServing/customServingRuntimes/DeleteCustomServingRuntimeModal.tsx, frontend/src/pages/modelServing/customServingRuntimes/useTemplateOrder.ts, frontend/src/pages/modelServing/customServingRuntimes/useTemplates.ts, frontend/src/services/dashboardService.ts, frontend/src/services/templateService.ts
Closes #1225 
For all testing, the pre-requisite is:
1. Add a regular user to the odh admins group (you should have some groups added in Settings -> User Management)
2. Log in as the regular user
3. You should see now the admin panel
*Note*: In dev mode it takes way more time to do any action compared to pass through
1. Go to **Settings -> Serving Runtime**
2. You should see all the Custom Serving Runtimes
1. Drag and drop the Custom Serving Runtimes
2. Navigate to other screen
4. The order should persist
1. Click on "Add serving runtime"
2. Add a new serving runtime
3. Check that you can create it
1. Go back to the Serving Runtime view
2. Click on the kebab menu of one of the Serving Runtimes
3. Click delete
5. Check that you can delete it
All these tests should be covered in the serving …
=> Refactor Custom Serving Runtime admin

frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx
=> Fixes to update project error message

frontend/src/app/App.scss
Closes #908 
1. [In chrome] Switch to this branch and check that the logo is working fine
2. [In safari] Check that the logo is now full witdh
3. Change `ODH_LOGO` value to test other logos and see if they fit the widht
before
after
=> Fix nav logo in safari

frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeListButtonAction.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx
Fixes #1357 
You can see the changes by going to the "Models and Model Servers" section of a Project
=> Rename configure to add

frontend/src/concepts/pipelines/content/createRun/CloneRunPage.tsx, frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetailsActions.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRunJob/PipelineRunJobTableRow.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeTableRow.tsx
=> Rename kebab actions from 'Clone' to 'Duplicate'

backend/src/server.ts, backend/src/utils/constants.ts
Closes #1401 
1. Runing the backend
2. Check that no longer displays the warn about variadic call signature
=> Migration of listent function for fastify v4

frontend/src/concepts/pipelines/content/createRun/const.ts
Addresses #1301 
Refer to #1301 
Try to create run after going to Data Science Pipelines => Runs
=> Make pipeline input parameters more evident

frontend/src/concepts/pipelines/context/useManageElyraSecret.ts, frontend/src/concepts/pipelines/elyra/const.ts, frontend/src/concepts/pipelines/elyra/utils.ts
Closes: #1418
Updates existing secrets as a follow up to the change in https://github.com/opendatahub-io/odh-dashboard/pull/1416
1. Create a project before testing (or use the cluster dashboard) & add a DSP Server
2. Use the PR code and visit the existing DS Project you have and look in the network tab for a PUT of the `ds-pipelines-confg`
None
=> Update Existing Elyra Secret if incorrect

docs/triaging.md
Change "viusal chnages" to "visual changes"
=> Fix typo in triaging.md

frontend/src/concepts/dashboard/DashboardModalFooter.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
Closes: #993 
#993 
1.Create a DS Project
2.Create a Model Server
3.Deploy a Model
4.Deploy a 2nd Model with the same name as the first
=> chore: resolved the gap issue when Error shows

frontend/src/pages/projects/components/GenericHorizontalBar.tsx, frontend/src/pages/projects/screens/detail/ProjectDetails.tsx, frontend/src/pages/projects/screens/projects/ProjectTableRow.tsx, frontend/src/pages/projects/screens/projects/useProjectTableRowItems.ts
Closes: #1347 
#1347 
Be a admin
Create a DS project
check for the Edit permission in the kebab option which redirect to the permission tab
=> Add 'Edit Permissions' Kebab to Project Row

.github/pull_request_template.md
Updating the template to help with filling it out and catching on-cluster bugs that we won't see in dev mode.
=> Rework the self checklist on the PR Template

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/ISSUE_TEMPLATE/internal_story.yml, .github/ISSUE_TEMPLATE/internal_test.yml
=> Added Internal Test & Updated other templates

frontend/src/pages/projects/screens/spawner/imageSelector/ImageVersionSelector.tsx
Fixes #1444 
Refer to #1444 
1. Under a project, click 'create workbench'.
2. Select an image under 'Image selection'.
3. Note text under 'Version selection' field.
=> Modify help text under for image version selection

CONTRIBUTING.md
Update the CONTRIBUTING section to reflect the latest changes in building and deploying the dashboard into a cluster.
=> Update CONTRIBUTING to reflect latest changes in build and deployment

backend/src/utils/constants.ts
Fixes an incorrect comment added in commit 4038b177432cc9b136f04e8b7ae3d43c5b4b03e8
=> Fixes incorrect comments

frontend/src/concepts/pipelines/content/createRun/const.ts
Fixes #1546 
#1546 
1. Create a pipeline run
2. Select `Schedule recurring run`
3. Select `Cron`
Visual changes
=> Fix default cron string

backend/src/utils/resourceUtils.ts
Closes #1562 
1. Get the annotation opendatahub.io/template-enabled one one of the templates.
2. Reload the dashboard pod
3. Check that the first status object doesn't return status in DashboardConfig
No testing coverage added to backend, no planned efforts for that component
=> Fix issue when doing first migration of Serving Runtime enablement

frontend/src/__mocks__/mock403Error.ts, frontend/src/__tests__/integration/pages/projects/ProjectView.spec.ts, frontend/src/__tests__/integration/pages/projects/ProjectView.stories.tsx, frontend/src/pages/projects/screens/projects/DeleteProjectModal.tsx, frontend/src/pages/projects/screens/projects/ProjectListView.tsx
Closes #1544 
We should not close the modal when the error appears, instead, we should keep the modal open and show the error.
1. Login as an admin user and create a project
2. Give a regular user `edit` permission in project sharing, so he could see the project in the project list
3. Login as this regular user and try to delete the project
4. See if the modal keeps open and the error shows
Add deletion error to storybook test.
=> Show project deletion error correctly

frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/SelectedTaskDrawerContent.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightContent.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeDetailsTab.tsx, frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.ts, frontend/src/k8sTypes.ts
Closes: #1507 
#1507 
The elyra pipeline was lacking the proper task name in data science pipeline 
you can check the changes in pipelines tab :
and also in the triggered run tab
1) Create a workbench with notebook image that contain elyra extension (Standard data science, TensorFlow, TrustyAI, or PyTorch  ) , In the cluster, that are insecured , above env vars are needed to be set in workbenches (PIPELINES_SSL_SA_CERTS=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt)
2) You have created and configured a pipeline server within the data science project that contains your workbench.
3)You have access to S3-compatible storage
4)Launch an Elyra Notebook
5)Build any pipeline of any number of tasks
6)Launch DS Pipelines Dashboard UI and view the Pipeline/Run views
Self …
=> Elyra Pipelines Lack Proper Task Names

frontend/src/app/App.scss, frontend/src/app/App.tsx, frontend/src/components/GenericSidebar.tsx, frontend/src/concepts/pipelines/content/createRun/RunPage.tsx, frontend/src/concepts/pipelines/content/createRun/const.ts, frontend/src/pages/projects/screens/detail/ProjectDetailsComponents.tsx, frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx, frontend/src/utilities/const.ts, frontend/src/utilities/utils.ts
Closes: #1358
Jump links were not working on the project details components tab. The reason is because the page was setup with a different scroll container than what was actually scrolling.
The same component with `jump link` is present in the create workbench form. This page was working correctly however the scroll pane was an inner panel. Updated this page to be consistent with the project details such that the scroll behavior occurs at the main container panel of the page.
I added a small offset to the `jump links` section and the scroll behavior so that as the user scrolls, or jumps to a link, the content doesn't get squished right at the top.
Create Project:
- Create a project (or be an admin on it)
- Visit the project details page `/projects/<myproject>`
- Click on one of the `jump …
=> fix jump links scroll behavior

.env
Fixes #1534 
The `Documentation` and `Community` links were broken, just removed `.html` as described in #1534 
1. Click on the `Documentation` and `Community` links in top navbar (`?` icon)
No tests needed(visual changes)
=> Fix docs and community link

frontend/src/concepts/pipelines/content/createRun/contentSections/PipelineSection.tsx, frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts, frontend/src/concepts/pipelines/kfTypes.ts
Closes: #1516 
#1516 
[Screencast from 2023-08-01 11-31-58.webm](https://github.com/opendatahub-io/odh-dashboard/assets/99238909/1e59aa24-315d-42df-b3bb-551d750f426d)
1. Import a pipeline which contains input parameters
2. Create a run using that pipeline and change the input parameter
3. After the run completes, go to Triggered tab and select the initial run.
Select Actions -> Duplicate run and scroll down to Pipeline input parameters.
Check whether the input parameters are correctly duplicated
=> Parameters from triggered runs not copied when run is duplicated

.github/ISSUE_TEMPLATE/bug_report.yaml
Makes language on our bug template a bit clearer when filing bugs against unreleased feature branches.
N/A text only
None
Read the text changes and give an opinion.
^^^ **Textual change to GitHub templates, above is N/A**
=> Improve bug report issue template language

frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableToolbar.tsx
Closes #1638 
Simple fix, just text replacement.
1. Create a pipeline run
2. Go to the triggered tab, check the placeholder text in the search input
N/A, text fix.
=> Fix placeholder text in triggered run search input

frontend/src/concepts/dashboard/DashboardSearchField.tsx, frontend/src/pages/BYONImages/BYONImagesTable.tsx
=> Fix byon branch type issues

frontend/src/pages/projects/screens/projects/ProjectListView.tsx
=> Fix lint error when solving merge conflict

frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionFolderPathField.tsx
Fixes #1601 
According to the description of #1601 `placeholder` is changed and changing a type variable to PascalCase that I missed in previous PR-https://github.com/opendatahub-io/odh-dashboard/pull/1512#pullrequestreview-1549935352
1. Select `Model Serving` from the left Navbar
2. Click on `Deploy server`(You may have to add a model server if you haven't added one already)
3. Go to the `Path` field towards the end of the `Deploy model` modal.
Visual changes, not tests required
=> Deploy model Path field enhancements

backend/src/routes/api/k8s/index.ts, backend/src/routes/api/k8s/pass-through.ts, backend/src/routes/api/namespaces/namespaceUtils.ts, frontend/src/api/k8s/pods.ts, frontend/src/concepts/k8s/pods/useFetchLogs.ts, frontend/src/concepts/k8s/pods/usePod.ts, frontend/src/concepts/k8s/pods/usePodContainers.ts, frontend/src/k8sTypes.ts, frontend/src/pages/notebookController/screens/server/NotebookServerDetails.tsx, frontend/src/pages/projects/screens/detail/notebooks/useNotebookDeploymentSize.ts, frontend/src/pages/projects/screens/detail/notebooks/useNotebookGPUNumber.ts, frontend/src/pages/projects/screens/detail/notebooks/useNotebookImageData.ts, frontend/src/types.ts, frontend/src/utilities/imageUtils.ts
Help for #1653
Adds Pod Logs Infrastructure
https://github.com/opendatahub-io/odh-dashboard/assets/8126518/5dbc2bb5-0df3-4288-8a7b-b6273fc0f47b
=> Fetch Logs infrastructure

package-lock.json, package.json
Closes: #1696
Removes jest from the root package.json
* remove `node_modules` dir
* run `npm install`
* run `npm test`
None
=> Remove jest from root package.json

frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightContent.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightTabs.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeInputOutputTab.tsx, frontend/src/concepts/pipelines/topology/pipelineUtils.ts, frontend/src/k8sTypes.ts
Closes: #1425 
#1425
1) Create a Pipeline in DSP that contains various references
2) Run the Pipeline
=> pipelineRun reference handling

frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAddTemplate.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeTableRow.tsx
Closes #1500 
When duplicating an OOTB custom serving runtime, change the preset value to:
`metadata.name` -> `${metadata.name}-copy`
`displayName` -> `Copy of ${displayName}`
`description` -> `description` (unchanged)
1. Go to settings -> Serving runtimes page
2. Choose an OOTB serving runtime and click `Duplicate` in the dropdown menu
3. Check the `metadata.name` field and `metadata.annotations['openshift.io/display-name']` field to make sure they are updated as described above
N/A
=> Update resource name, display name and description when duplicating custom serving runtime

frontend/src/concepts/pipelines/topology/core/TaskEdge.tsx, frontend/src/concepts/pipelines/topology/core/factories.ts
Closes: #1346 
#1346
Adding ArrowHead to the topology
1.  Go to the DS pipeline
2. Check whether the arrowhead is present in the pipleline
No test coverage
=> ArrowHead topology

frontend/config/webpack.common.js
Closes: https://github.com/opendatahub-io/odh-dashboard/issues/1691
As per the [patternfly code editor guidelines](https://github.com/patternfly/patternfly-react/tree/main/packages/react-code-editor), we should specify only the languages to bundle. ODH only needs the `yaml` language.
Using the bundle analyzer.
Before:
56 chunks
After:
38 chunks
Pipelines:
- Import a pipeline
- View the pipeline and switch to the YAML tab.
Serving runtimes:
- Login as an admin
- Go to `Settings` => `Serving runtimes` in the left nav
- Click a serving runtime kebab menu and select `Duplicate`
- View / edit the yaml.
none
=> bundle only the yaml language using MonacoWebpackPlugin

.github/pull_request_template.md, OWNERS, docs/smes.md, frontend/package-lock.json, frontend/src/pages/projects/screens/detail/ProjectDetailsComponents.tsx, frontend/src/pages/projects/screens/detail/useCheckLogoutParams.ts
=> Merge main into f/notebook-controller

frontend/src/pages/modelServing/screens/projects/ServingRuntimeList.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeTable.tsx
Closes #1215 
Simply refresh the data connections. Also, cleaned up the code a little because we have context, we don't need to pass all the values to the table. What's more, the table will sort inside it, we only need to pass `defaultSortColumn`.
1. Go to project details page
2. Try to deploy a model with a new data connection
3. See if the data connection appears immediately when the model is deployed
N/A, it's only a network call refreshing thing.
=> Refresh data connections when deploying model on project details page

manifests/apps/jupyter/create-jupyter-notebook-quickstart.yaml, manifests/apps/jupyter/deploy-python-model-quickstart.yaml, manifests/apps/jupyter/jupyter-app.yaml, manifests/apps/jupyter/jupyter-docs.yaml, manifests/apps/jupyter/kustomization.yaml
Closes #1616 
Follow up #1636 to get automation right.
Update the quickstarts to remove JupyterHub
1. Deploy the dashboard
2. Check that the links have been updated
No current testing of ISV or documentation
=> Update Jupyter Quickstart

docs/smes.md
Updates the SMEs markdown with more information on feature areas that are on-going.
=> Added Edge to SME areas

.github/ISSUE_TEMPLATE/internal_tracker.yml, .github/ISSUE_TEMPLATE/internal_ux.yml
Adds additional internal flow templates for creating issues.
=> Add UX and Tracker internal templates

frontend/src/app/App.tsx, frontend/src/components/GenericSidebar.tsx, frontend/src/utilities/const.ts, frontend/src/utilities/utils.ts
Closes: #1795
When quick starts were moved to the top level of the application as part of https://github.com/opendatahub-io/odh-dashboard/pull/1676, it introduced a new scroll container. While this is not a problem, disjointed code that relied on query selectors to retrieve the scroll container broke. As a result, the jump links were no longer working.
There are three parts of the application that make use of this feature: project details, workbench and pipeline run creation forms.
Project details:
- Create a new project
- Navigate to `Data Science Projects` in the left nav.
- Locate your project in the list and click the link.
- Test that the links under the section heading `Jump to section` update as you scroll the page and also navigate to the correct section on click.
Workbench …
=> update scroll container selector for JumpLinks

backend/src/types.ts, frontend/src/components/CPUField.tsx, frontend/src/pages/modelServing/__tests__/utils.spec.ts, frontend/src/pages/modelServing/utils.ts, frontend/src/types.ts, frontend/src/utilities/__tests__/valueUnits.spec.ts, frontend/src/utilities/valueUnits.ts
Closes #1549 
1. Create a DS Project in ODH (either UI or CLI)
2. Either apply for CLI a `ServingRuntime` with request.cpu without commas or edit one you've already created
3. Go to ODH UI > your DS project
4. Find the serving runtime you deployed at step 2
5. Click the 3dots menu on the right > click "Edit model server"
6. Check that you can edit the Model Server
No UI Changes
=> Fix issue with resource types for cpus

manifests/base/cluster-role.yaml
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1875
update service account role to allow accelerator migration the correct permissions to create a new accelerator profile
1. open odh on a cluster (not dev mode) (with gpu nodes)
2. ensure the gpu migration config map is removed, as well as all accelerator profile instances
3. restart the dashboard pod
4. ensure that a new accelerator profile was created
n/a hot fix
=> update cluster role to allow accelerator profile creation

frontend/src/utilities/useAcceleratorState.ts
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1902
If a user calls the reset function on useAcceleratorState, then the hook also refreshed the data because reset removed necessary options
1. open add model server modal
2. close model
3. open again
4. notice accelerator dropdown is still there
tests will come later, hot fixing this before feature freeze
@andrewballantyne do you want tests for this PR now that we are in main?
=> refresh accelerators after reset

frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenInput.tsx, frontend/src/pages/modelServing/screens/projects/utils.ts, frontend/src/pages/modelServing/screens/types.ts, frontend/src/pages/modelServing/utils.ts, frontend/src/utilities/useAcceleratorState.ts, frontend/src/utilities/utils.ts
Closes #1626 
1. Update the title and button label when editing the model server
2. Disable the update button when there is no change in the fields
3. Automatically disable the tokens when the last token is removed
https://github.com/opendatahub-io/odh-dashboard/assets/37624318/a7b28de9-a914-4779-9acc-16110d1ee57f
1. Edit an existing model server
2. Check the title and the button label
3. Try to change all the fields and change them back, see the enabled/disabled status of the update button
Add an integration test for editing the model server to check the enabled/disabled status when changing the inputs fields
=> Improvements to edit model server modal

backend/.eslintrc, backend/src/routes/api/gpu/gpuUtils.ts, frontend/.eslintrc, frontend/src/pages/BYONImages/UpdateImageModal.tsx, frontend/src/pages/learningCenter/CategoryFilters.tsx, frontend/src/utilities/useFetchState.ts
Fixes #1890 
Enforce strict equality operator by including appropriate rules in `.eslintrc` according to [`eqeqeq` documentation](https://eslint.org/docs/latest/rules/eqeqeq) and made changes to accommodate the rule.
Run `npm run test`. Any outstanding `!=` or `==` will be detected.
=> Enforce strict equality operator

manifests/crd/acceleratorprofiles.opendatahub.io.crd.yaml
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1895
added descriptions to accelerator profile CRD
make sure CRD can still be applied in openshift
n/a this is manifests
=> add descriptions to accelerator profile crd

frontend/src/__mocks__/mockByon.ts, frontend/src/__tests__/integration/pages/notebookImageSettings/NotebookImageSettings.spec.ts, frontend/src/__tests__/integration/pages/notebookImageSettings/NotebookImageSettings.stories.tsx, frontend/src/__tests__/unit/testUtils/BYONImagesUtils.spec.ts, frontend/src/components/table/Table.tsx, frontend/src/pages/ApplicationsPage.tsx, frontend/src/pages/BYONImages/BYONImageModal/DisplayedContentTabContent.tsx, frontend/src/pages/BYONImages/EmptyBYONImages.tsx
closes: https://github.com/opendatahub-io/odh-dashboard/issues/1970
add UI tests and util tests. See issue for details on what concepts are tested.
also some small bug fixes found from tests
-  filterBlankPackages had incorrect logic
- a11y fixes
- add type helper
`npm run test`
this PR is tests
=> BYON tests added

frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx
Fixes #1736 
Renamed "Container" to "Steps".
cc @yih-wang 
1. Go to Global Pipelines Run page and select any Triggered run.
2. Click on any node -> A side drawer will appear from the right containing the "Logs" tab.
3. You can see "Steps" instead of "Container" beside the steps-dropdown.
=> Rename Container to Step

manifests/crd/acceleratorprofiles.opendatahub.io.crd.yaml
closes: https://github.com/opendatahub-io/odh-dashboard/issues/2007/
updated crd
Add new CRD and make sure v1alpha versions still show up in the UI
backend no tests
=> add migrate crd from v1alpha to v1 on start

frontend/src/app/App.scss, frontend/src/components/OdhDocCard.tsx, frontend/src/components/SupportedAppTitle.tsx, frontend/src/pages/notebookController/NotebookController.scss, frontend/src/pages/notebookController/screens/server/EnvironmentVariablesField.tsx, frontend/src/pages/projects/projectSharing/ProjectSharingNameInput.tsx, frontend/src/pages/projects/projectSharing/ProjectSharingTableRow.tsx, frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTableRow.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/EnvUploadField.tsx
Follow up to patternfly/patternfly-react#1901 , specifically comments https://github.com/opendatahub-io/odh-dashboard/pull/1901#pullrequestreview-1668709333 and https://github.com/opendatahub-io/odh-dashboard/pull/1901#discussion_r1353210324
Help wanted on Jump Links / sidebar bug as noted in [original ticket](https://github.com/opendatahub-io/odh-dashboard/issues/1694#issue-1862028424) cc @andrewballantyne , would appreciate some extra resourcing to help figure this out since it seems to come from deeper within the dashboard logic rather than PF
=> PF5 upgrade: styling updates

backend/src/routes/api/prometheus/index.ts, backend/src/types.ts, backend/src/utils/constants.ts, backend/src/utils/prometheusUtils.ts, frontend/src/__mocks__/mockDashboardConfig.ts, frontend/src/api/prometheus/serving.ts, frontend/src/api/prometheus/usePrometheusQueryRange.ts, frontend/src/api/prometheus/useQueryRangeResourceData.ts, frontend/src/pages/modelServing/screens/metrics/GlobalModelMetricsWrapper.tsx, frontend/src/pages/modelServing/screens/metrics/ModelServingMetricsContext.tsx, frontend/src/pages/modelServing/screens/metrics/utils.tsx, frontend/src/pages/modelServing/screens/projects/ProjectModelMetricsWrapper.tsx, frontend/src/pages/modelServing/screens/projects/ProjectServerMetricsWrapper.tsx, frontend/src/pages/modelServing/useModelMetricsEnabled.ts, frontend/src/types.ts, manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml, manifests/overlays/odhdashboardconfig/odh-dashboard-config.yaml
Closes: 
* #1855
* #1916
* #1109
* Migrates prometheus metrics queries for explainability and performance to use UWM.
* Modifies model performance queries to use model mesh native prometheus function instead of `haproxy` (haproxy functions don't work with UWM.
Notes: 
* A dashboard build with these changes is available here: quay.io/acreasy/odh-dashboard:uwm
Requires a DS project with a model server installed, TrustyAI service installed and some models to test. You'll also need to fire some data at the model.
Note: this can't be tested locally in dev mode as the queries need to be made via RBAC, which isn't available via external routes, use the image listed above to test.
Run these tests as a cluster admin and also as a user with admin role on the ds project to verify.
For your given …
=> Fetch prometheus metrics from UWM

backend/src/routes/api/namespaces/const.ts, backend/src/routes/api/namespaces/namespaceUtils.ts, frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.spec.ts, frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.stories.tsx, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx, frontend/src/api/k8s/inferenceServices.ts, frontend/src/api/k8s/projects.ts, frontend/src/pages/modelServing/__tests__/utils.spec.ts, frontend/src/pages/modelServing/customServingRuntimes/utils.ts, frontend/src/pages/modelServing/screens/global/DeleteInferenceServiceModal.tsx, frontend/src/pages/modelServing/screens/global/EmptyModelServing.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceEndpoint.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceListView.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/global/useRouteForInferenceService.ts, frontend/src/pages/modelServing/screens/global/utils.ts, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceNameSection.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx, frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTable.tsx, frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeNameSection.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx, frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx, frontend/src/pages/modelServing/screens/projects/utils.ts, frontend/src/pages/projects/types.ts
Closes #1943 #1945 
1. Enabling both platforms first
2. Click the "Single model serving platform"
3. Check that the model cannot be deployed until you fill in all the values
4. Check that you get the correct serving runtimes
5. Deploy the model
6. Check that you get one Model Server and one Model deployed
1. In a project with "Single model platform"
2. Deploy a new model
3. Check that you get one Model Server and one Model deployed
1. Try to edit one model deployed in a `Single model serving enabled` project
2. Edit the project
3. Check that the changes are submitted
TODO
=> Implement kserve modal

frontend/src/__mocks__/mockInferenceServiceK8sResource.ts, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx, frontend/src/api/__tests__/inferenceServices.spec.ts, frontend/src/api/k8s/inferenceServices.ts, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/screens/global/useRouteForInferenceService.ts
Closes #2079 #2053
1. Deploy a kserve model
2. Check that the annotations described in #2079 are present in the `InferenceService` resource
3. Check that until loaded, the route is a skeleton
=> Add annotations for inferenceservice in kserve

frontend/src/pages/projects/projectSettings/ModelBiasSettingsCard.tsx
Change "TrustAI" to "TrustyAI" In `ModelBiasSettingsCard`
Tested while installing and uninstalling `TrustyAI` in `ModelBiasSettingsCard`
=> Fix typo in TrustyAI alerts 

docs/process-definition/branches.md, frontend/src/__mocks__/mockInferenceServiceK8sResource.ts, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx, frontend/src/api/__tests__/inferenceServices.spec.ts, frontend/src/api/k8s/inferenceServices.ts, frontend/src/components/ResourceActionsColumn.tsx, frontend/src/components/ResourceTr.scss, frontend/src/components/ResourceTr.tsx, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/global/useRouteForInferenceService.ts, frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTableRow.tsx
Merge `f/model-serving` into `incubation` and resolve conflicts
=> Merge f/model-serving into incubation

frontend/src/__tests__/integration/pages/customServingRuntimes/CustomServingRuntimes.spec.ts, frontend/src/__tests__/integration/pages/customServingRuntimes/CustomServingRuntimes.stories.tsx, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx, frontend/src/pages/modelServing/__tests__/utils.spec.ts, frontend/src/pages/modelServing/customServingRuntimes/utils.ts, manifests/modelserving/ovms-ootb.yaml
Closes #2059 #2048 
1. Deploy the new OVMS model
2. Clone other template and remove the `opendatahub.io/modelServingSupport` annotation
3. Check that OMVS will only supports multi model
4. Check that the Serving Runtime with no annotation only supports multi model
Adapted tests and added unit testing coverage
=> Adapt logic for Custom Serving Runtime migration and adapt OVMS OOTB

frontend/src/concepts/k8s/pods/utils.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTabStatus.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/useWindowResize.ts
Fixes #1745
Included a dropdown for downloading pod logs from all containers
cc @yih-wang 
https://github.com/opendatahub-io/odh-dashboard/assets/22885912/4f294b8c-feeb-4a9f-ab8b-ff741bb38d9e
1. Trigger a run of any pipeline 
2. Select the run from the Global Runs table and click on any node/task of the pipeline 
3. Go to "Logs" tab and see whether you see a dropdown titled "Download" (only in case you have multiple containers in the pod), the dropdown has 2 list items, one for current container and one for all containers. Try clicking on the dropdown and see whether you can download the pod logs.
=> Download pod logs from all containers

frontend/src/__tests__/integration/pages/projects/ProjectDetails.stories.tsx, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionSection.tsx
=> Fix merging issues

frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.stories.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceEndpoint.tsx
Closes #2053 
1. Deploy a new model in kserve
2. Check that you get the route
Tests already in place, just reopened this issue cause we were fetching the wrong resource
=> Improve route handling

frontend/src/pages/modelServing/screens/global/ModelServingGlobal.tsx
Closes #2134 
Check the error state for the current project selected and the installed status of the platform and show error state if the project is labelled while the platform in not installed.
1. Go to the global model serving page
2. Choose a project which is labelled already but the corresponding platform is not installed
3. Make sure it has an error state
N/A
=> Show error state on global serving page when the platform in not installed

backend/src/types.ts, docs/architecture.md, frontend/src/__tests__/integration/pages/notebookImageSettings/NotebookImageSettings.spec.ts, frontend/src/__tests__/integration/pages/notebookImageSettings/NotebookImageSettings.stories.tsx, frontend/src/components/NumberInputWrapper.tsx, frontend/src/components/ValueUnitField.tsx, frontend/src/concepts/dashboard/DashboardSearchField.tsx, frontend/src/concepts/pipelines/NoPipelineServer.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionFolderPathField.tsx, frontend/src/pages/projects/components/PVSizeField.tsx
Syncing active work with the PF5 branch
Tests will fail as they are on the branch -- we will address that as another effort after the merge.
See "how has this been tested" section.
=> Minor improvements pf5

frontend/src/__tests__/integration/pages/projects/ProjectView.spec.ts, frontend/src/pages/modelServing/screens/global/InferenceServiceListView.tsx, frontend/src/pages/projects/components/SearchField.tsx
Closes #2120 
One liner. Just filter the search types.
1. Go to the data science projects page
2. Check the search filter, make sure there are only `Name` and `User` could be selected
3. Verify they are working
Update the test cases a little bit to verify the filter dropdowns.
=> Remove projects filter on the project view page

frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.spec.ts, frontend/src/__tests__/integration/pages/modelServing/ModelServingGlobal.stories.tsx, frontend/src/pages/clusterSettings/ClusterSettings.tsx, frontend/src/pages/modelServing/ModelServingContext.tsx, frontend/src/pages/modelServing/ModelServingRoutes.tsx, frontend/src/pages/modelServing/screens/global/EmptyModelServing.tsx, frontend/src/pages/modelServing/screens/global/GlobalModelServingCoreLoader.tsx, frontend/src/pages/modelServing/screens/global/ModelServingGlobal.tsx, frontend/src/pages/modelServing/screens/metrics/ModelServingMetricsWrapper.tsx, frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx, frontend/src/pages/modelServing/screens/projects/utils.ts, frontend/src/pages/modelServing/useInferenceServices.ts, frontend/src/pages/modelServing/useServingRuntimes.ts
Closes #2135 
Main purpose is to add spinner when switching between projects on the global model serving page. Also, improve the route and error handling to make it more robust.
1. Go to global model serving page
2. Try to switch between the project, there should be no flickering state change now
Add a new integration test to make sure the global model serving page shows the expected error page when both platforms are not installed.
=> Add spinner, enhance route and error handling for global model serving page

backend/src/routes/api/notebooks/utils.ts, backend/src/utils/notebookUtils.ts, backend/src/utils/resourceUtils.ts, frontend/src/api/k8s/notebooks.ts, frontend/src/pages/projects/notebook/useRouteForNotebook.ts
Updates incubation with the OSSM bugfix for Jupyter Tile (also some cleanup).
=> Merge `f/ossm` into `incubation`

backend/src/routes/api/k8s/index.ts, backend/src/routes/api/k8s/pass-through.ts
Closes: #2219
See ticket, solution was code cleanup
Test by creating a Project.
N/A - backend infra issue
=> Cleanup the PF5 merge for overlapping Logs functionality

frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabDetails.tsx
Closes: https://github.com/opendatahub-io/odh-dashboard/issues/2218
branch: `f/pipelines-enhancement`
During the merge from main into `f/pipelines-enhancement`, some details were duplicated.
Manually
No new tests.
=> Remove duplicate pipeline run details

frontend/src/__mocks__/mockEdgePipelineRun.ts, frontend/src/__tests__/integration/pages/edge/EdgeModels.stories.tsx, frontend/src/api/index.ts, frontend/src/api/k8s/pipelineRuns.ts, frontend/src/api/models/pipelines.ts, frontend/src/concepts/edge/EdgeContext.tsx, frontend/src/concepts/edge/__tests__/getEdgeModelRunContainerImage.spec.ts, frontend/src/concepts/edge/__tests__/isPipelineRunOutputOverridden.spec.ts, frontend/src/concepts/edge/__tests__/organizePipelineRuns.spec.ts, frontend/src/concepts/edge/const.ts, frontend/src/concepts/edge/types.ts, frontend/src/concepts/edge/useEdgeModels.ts, frontend/src/concepts/edge/utils.ts, frontend/src/k8sTypes.ts, frontend/src/pages/edge/EdgeModels.tsx, frontend/src/pages/edge/EdgeModelsRoutes.tsx
closes: https://github.com/opendatahub-io/odh-dashboard/issues/2247
- added context component
- added hook to get all models
- added utils to organize and fetch certain parts of a model
added util tests
=> add starting edge architecture

frontend/src/pages/modelServing/ModelServingRoutes.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/metrics/ModelMetricsPathWrapper.tsx, frontend/src/pages/modelServing/screens/metrics/ModelServingExplainabilityWrapper.tsx, frontend/src/pages/modelServing/screens/metrics/bias/BiasConfigurationPage/BiasConfigurationBreadcrumbPage.tsx
Fixes issues caused by the previous merge which broke the global model serving routes.
=> Fixes global model serving routes

frontend/src/__tests__/integration/pages/modelServing/ServingRuntimeList.spec.ts, frontend/src/components/ResourceActionsColumn.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-423
Brought back a previous change that had gone missing and updated the integration test.
Screenshot from storybook:
- Create an inference service
- Delete the inference service from the model serving page
- The UI should update to display the marked for deletion row before it gets removed on next update. If the row disappears immediately, try again.
Updated integration test.
=> re-instate the ResourceActionsColumn for inference service table rows

frontend/src/__mocks__/mockEdgePipelineRun.ts, frontend/src/__tests__/integration/pages/edge/EdgeModels.stories.tsx, frontend/src/api/index.ts, frontend/src/api/k8s/pipelines.ts, frontend/src/api/models/pipelines.ts, frontend/src/concepts/edge/__tests__/isPipelineRunOutputOverridden.spec.ts, frontend/src/concepts/edge/const.ts, frontend/src/concepts/edge/content/EdgeContext.tsx, frontend/src/concepts/edge/content/edgePipelines/CreateRunModal.tsx, frontend/src/concepts/edge/content/edgePipelines/EdgeModelRunRow.tsx, frontend/src/concepts/edge/content/edgePipelines/EdgePipelineRow.tsx, frontend/src/concepts/edge/content/edgePipelines/EdgePipelineTable.tsx, frontend/src/concepts/edge/content/edgePipelines/EdgeStatus.tsx, frontend/src/concepts/edge/content/edgePipelines/const.ts, frontend/src/concepts/edge/content/edgePipelines/types.ts, frontend/src/concepts/edge/types.ts, frontend/src/concepts/edge/useEdgeModels.ts, frontend/src/concepts/edge/useEdgePipelines.ts, frontend/src/concepts/edge/utils.ts, frontend/src/k8sTypes.ts, frontend/src/pages/edge/EdgeModels.tsx, frontend/src/pages/edge/EdgeModelsRoutes.tsx, frontend/src/pages/edge/screens/edgePipelines/EdgePipelinesPage.tsx, frontend/src/utilities/NavData.tsx
closes: https://issues.redhat.com/browse/RHOAIENG-237
adds pipelines table page for pipelines and pipeline runs with the edge wrapping around it
_note: This PR is missing a re run method which will be done once the add model modal is done_
make sure edge pipeline runs are added to the table
n/a no test for this feature as it will be not merged into main
=> Edge pipelines view

frontend/src/api/k8s/pipelineRuns.ts, frontend/src/api/k8s/secrets.ts, frontend/src/concepts/edge/GITField.tsx, frontend/src/concepts/edge/assemblePipelineRuns.ts, frontend/src/concepts/edge/const.ts, frontend/src/concepts/edge/types.ts, frontend/src/k8sTypes.ts, frontend/src/pages/edge/AddModelButton.tsx, frontend/src/pages/edge/ManageEdgeModels.tsx, frontend/src/pages/edge/screens/models/EmptyEdgeModels.tsx
=> Add Model feature

frontend/tsconfig.json
VScode recently complained to me about typescript having to deal with too many files. To solve this, additional artifact directories have been excluded in the tsconfig.
Ensured app still builds.
None
=> exclude artifact directories from tsconfig

frontend/src/concepts/edge/content/models/ManageEdgeModels.tsx, frontend/src/concepts/edge/content/models/table/EdgeModeVersionRow.tsx, frontend/src/concepts/edge/content/models/table/EdgeModelRow.tsx, frontend/src/concepts/edge/content/models/table/EdgeModelsTable.tsx, frontend/src/concepts/edge/content/models/table/const.ts, frontend/src/concepts/edge/content/models/utils.ts, frontend/src/concepts/edge/content/pipelines/CreateRunModal.tsx, frontend/src/concepts/edge/content/pipelines/table/EdgeModelRunRow.tsx, frontend/src/concepts/edge/content/pipelines/table/EdgePipelineRow.tsx, frontend/src/concepts/edge/content/pipelines/table/EdgeStatus.tsx, frontend/src/concepts/edge/hooks/useEdgeS3Secret.ts, frontend/src/concepts/edge/types.ts, frontend/src/concepts/edge/utils.ts
closes: https://issues.redhat.com/browse/RHOAIENG-181\
- fix links
- overwrite function
- popover ux
- indent table
- add bucket param
- add fix for pipeline issue
n/a just for a demo
=> add UX fixes to edge feature

frontend/src/SDKInitialize.tsx, frontend/src/__mocks__/mock403Error.ts, frontend/src/__mocks__/mock404Error.ts, frontend/src/__mocks__/mockInferenceServiceK8sResource.ts, frontend/src/api/errorUtils.ts, frontend/src/api/k8s/configMaps.ts, frontend/src/api/k8s/inferenceServices.ts, frontend/src/api/k8s/notebooks.ts, frontend/src/api/k8s/pvcs.ts, frontend/src/api/k8s/roleBindings.ts, frontend/src/api/k8s/secrets.ts, frontend/src/api/k8s/serviceAccounts.ts, frontend/src/api/pipelines/k8s.ts, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/DeleteServingRuntimeModal.tsx, frontend/src/pages/modelServing/utils.ts, frontend/src/pages/projects/notebook/DeleteNotebookModal.tsx, frontend/src/pages/projects/screens/detail/data-connections/utils.ts, frontend/src/pages/projects/screens/spawner/service.ts
=> Adding K8sStatus from @openshift/dynamic-plugin-sdk-utils

frontend/.eslintrc, frontend/src/__tests__/integration/hooks/TestHook.tsx, frontend/src/components/OdhAppCard.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetails.tsx, frontend/src/concepts/projects/ProjectSelector.tsx, frontend/src/pages/BYONImages/BYONImageModal/ManageBYONImageModal.tsx, frontend/src/pages/exploreApplication/GetStartedPanel.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionExistingField.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx, frontend/src/pages/notebookController/screens/server/EnvironmentVariablesField.tsx, frontend/src/pages/projects/projectSharing/ProjectSharingTable.tsx, frontend/src/pages/projects/screens/detail/pipelines/ProjectPipelineBreadcrumbPage.tsx
Fixes #1953 
Added eslint rule to remove unnecessary braces in props and children. For more details : https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md
Run `npm run test`, you should see errors if there are unnecessary curly braces
Tech-debt issue. No visual changes.
=> Add react/jsx-curly-brace-presence eslint rule

frontend/.eslintrc, frontend/src/concepts/pipelines/content/configurePipelinesServer/PipelineDropdown.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx, frontend/src/pages/projects/projectSharing/ProjectSharingTableRowAdd.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-513
Added the eslint rule : https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/self-closing-comp.md
npm run test
=> Added react/self-closing-comp

frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineDetails.cy.ts, frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/__tests__/cypress/cypress/pages/notebookImageSettings.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines.ts, frontend/src/__tests__/integration/pages/pipelines/PipelineDetails.stories.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/SelectedTaskDrawerContent.tsx
A new [integration test](https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/__tests__/integration/pages/pipelines/PipelineDetails.spec.ts) was recently added built on playwright.
This PR migrates the test to cypress.
Also fixes a linting error that exists in `PipelineDetails.stories.tsx`.
New cypress test.
New cypress test.
=> migrate pipeline details integration test to cypress

frontend/package-lock.json, frontend/package.json
Upgraded dependencies/sub-dependencies to resolve vulnerabilities.
This will resolve vulnerabilities issues raised on [Synk app](https://app.snyk.io/org/red-hat-openshift-data-science-rhods/project/1d87351a-04b6-4d75-b13b-9187e9f55bc5)
* Pull this branch locally and `npm i`
* Run `cd frontend/ && npm audit`
* You should see `found 0 vulnerabilities`
* Try running odh-dashboard
No test, just upgrading packages.
=> Fixing frontend packages with vulnerabilities

frontend/package-lock.json, frontend/package.json
Closes: [RHOAIENG-1285](https://issues.redhat.com/browse/RHOAIENG-1285)
`follow-redirects` package exists in:
```
odh-dashboard-frontend
└─┬ axios@1.6.2
└── follow-redirects@1.15.3
```
Updated axios to latest to solve this
```
odh-dashboard-frontend
└─┬ http-server@14.1.1
└─┬ http-proxy@1.18.1
└── follow-redirects@1.15.3
```
Only a dev dependency and it's not carried over to our container.
Manually running on local
Only a package upgrade, no tests required
=> Update axios to resolve CVE-2023-26159

frontend/src/__mocks__/mockStatus.ts
Closes: [RHOAIENG-1283](https://issues.redhat.com/browse/RHOAIENG-1283)
Created a function to generate a mock SHA token instead of hardcoding it, addressing the Synk issue.
Running existing integration and e2e tests
Added unit test for `createMockToken` 
=> Resolving Hard coded secret in repository

manifests/modelserving/caikit-ootb.yaml, manifests/modelserving/ovms-ootb.yaml
Closes https://issues.redhat.com/browse/RHODS-12899
Just added this Custom Serving Runtime:
```yaml
kind: Template
apiVersion: template.openshift.io/v1
metadata:
name: ovms-accelerator
labels:
opendatahub.io/ootb: 'true'
annotations:
tags: 'ovms,servingruntime'
description: 'OpenVino Model Serving Definition Accelerator'
opendatahub.io/modelServingSupport: '["multi"]'
objects:
- apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
name: ovms
annotations:
openshift.io/display-name: 'OpenVINO Model Server Accelerator'
opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
labels:
spec:
builtInAdapter:
env:
- name: OVMS_FORCE_TARGET_DEVICE
value: AUTO
memBufferBytes: 134217728
modelLoadingTimeoutMillis: …
```
=> Add accelerator support to Custom Serving Runtimes

frontend/src/concepts/pipelines/content/pipelineSelector/PipelineSelectorTableRow.tsx
JIRA: https://issues.redhat.com/browse/RHOAIENG-522
Remove the auto-generated tooltip for the truncated table cell, and create a custom tooltip for the rows in the selector for pipelines and pipeline versions
Without description:
With description:
On pipeline details page:
1. Go to create run page/pipeline details page/pipeline version upload modal (anywhere contains a pipeline or pipeline version selector)
2. However on the pipeline or the version row
3. Check the content
N/A, it's a tiny UI change.
=> Handle tooltip in pipeline and version selector cleaner

frontend/src/concepts/areas/__tests__/useFetchDscStatus.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-1877
unit test for frontend/src/concepts/areas/useFetchDscStatus.ts
npm run test
test coverage 
=> added test for useFetchDscStatus file 

frontend/src/utilities/__tests__/dataEntryToRecord.spec.ts
Closes: [RHOAIENG-1895](https://issues.redhat.com/browse/RHOAIENG-1895)
Unit Test Case for dataEntryToRecord
`npm run test`
=> Unit Test Case for dataEntryToRecord

manifests/modelserving/caikit-ootb.yaml, manifests/modelserving/kustomization.yaml, manifests/modelserving/tgis-ootb.yaml
Add TGIS runtime to ootb models
Closes https://issues.redhat.com/browse/RHOAIENG-1267
1. Create a new project
2. Deploy a single model server
3. Select TGIS
4. Use the public-rhods bucket to deploy `demo-models/flan-t5-small-caikit/artifacts`
=> Add TGIS servingruntime template and update kustomization.yaml

frontend/src/utilities/__tests__/number.spec.ts
Closes: [RHOAIENG-1885](https://issues.redhat.com/browse/RHOAIENG-1885)
Unit Test Case for number
`npm run test`
=> Unit Test Case for number

frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelMetrics.cy.ts, frontend/src/concepts/dashboard/DashboardEmptyTableView.tsx, frontend/src/concepts/trustyai/content/DeleteTrustyAIModal.tsx, frontend/src/concepts/trustyai/content/InstallTrustyAICheckbox.tsx, frontend/src/concepts/trustyai/content/TrustyAIServerTimedOutError.tsx, frontend/src/concepts/trustyai/content/TrustyAIServiceNotification.tsx, frontend/src/pages/modelServing/screens/metrics/bias/BiasConfigurationPage/BiasConfigurationModal/ManageBiasConfigurationModal.tsx, frontend/src/pages/modelServing/screens/metrics/const.ts, frontend/src/pages/projects/projectSettings/ModelBiasSettingsCard.tsx, frontend/src/pages/projects/projectSettings/const.ts
Closes:
* [RHOAIENG-252](https://issues.redhat.com//browse/RHOAIENG-252)
* [RHOAIENG-1847](https://issues.redhat.com//browse/RHOAIENG-1847)
Implements suggestions from microcopy review described here: https://docs.google.com/document/d/1Jgzo9ZoNYeYmyAtTV1v-JzDWHnotM5aVwnL1NRZPjOA/edit#heading=h.bz4zmg8x9xcy
Updated screens:
* Verify string changes described in linked doc have been made.
N/A changes strings only
=> Update microcopy for Bias & Performance metrics

frontend/src/pages/projects/screens/spawner/__tests__/useImageStreams.spec.ts
Closes: [RHOAIENG-1942](https://issues.redhat.com/browse/RHOAIENG-1942)
Unit test case for: frontend/src/pages/projects/screens/spawner/useImageStreams.ts
`npm run test:unit`
code coverage:
=> Unit test case for useImageStreams

frontend/src/concepts/k8s/pods/utils.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/usePodStepsStates.ts, frontend/src/types.ts
JIRA: [RHOAIENG-1095](https://issues.redhat.com/browse/RHOAIENG-1095)
Add step logs icons to individual steps in Pipeline logs dropdown as per the [latest design](https://www.figma.com/proto/rJjOtl3nxpW6BAcl0MZr4y/Pipeline-log-viewer?page-id=62%3A1895&type=design&node-id=1075-5045&viewport=1756%2C-20118%2C0.46&t=KtJufeUCZWMruc21-1&scaling=min-zoom&starting-point-node-id=1175%3A7502&show-proto-sidebar=1)
cc @yih-wang 
1. Click on any Pipeline run from the Pipeline runs table
2. Click on any node of the run
3. Select the `Logs` tab and wait till it loads.
4. Click on the step dropdown
Tests to be added in a later PR
=> Add step logs icons to individual steps in Pipeline logs dropdown items

frontend/src/utilities/__tests__/useDetectUser.spec.ts
Closes: [RHOAIENG-1973](https://issues.redhat.com/browse/RHOAIENG-1973)
Unit Test Case for useDetectUser
`npm run test`
=> Unit Test Case for useDetectUser

frontend/.eslintrc, frontend/src/api/__tests__/apiMergeUtils.spec.ts, frontend/src/api/k8s/notebooks.ts, frontend/src/api/k8s/pvcs.ts, frontend/src/app/AppLauncher.tsx, frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts, frontend/src/concepts/pipelines/elyra/utils.ts, frontend/src/concepts/projects/apiHooks/useNamespaceSecret.ts, frontend/src/pages/exploreApplication/ExploreApplications.tsx, frontend/src/pages/exploreApplication/GetStartedPanel.tsx, frontend/src/pages/learningCenter/ApplicationFilters.tsx, frontend/src/pages/learningCenter/ProviderTypeFilters.tsx, frontend/src/pages/modelServing/screens/metrics/utils.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx, frontend/src/pages/modelServing/utils.ts, frontend/src/pages/notebookController/screens/server/SizeSelectField.tsx, frontend/src/pages/notebookController/screens/server/usePreferredNotebookSize.ts, frontend/src/pages/projects/notebook/DeleteNotebookModal.tsx, frontend/src/pages/projects/notebook/useWatchNotebookEvents.ts, frontend/src/pages/projects/screens/spawner/deploymentSize/ContainerSizeSelector.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/useNotebookEnvVariables.tsx, frontend/src/pages/projects/screens/spawner/imageSelector/ImageSelectorField.tsx, frontend/src/pages/projects/screens/spawner/imageSelector/ImageVersionSelector.tsx, frontend/src/pages/projects/screens/spawner/useNotebookSize.ts, frontend/src/services/templateService.ts, frontend/src/utilities/const.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-1734
added prefer-destructuring eslint rule 
npm run test
=> added prefer-destructing eslint rule

frontend/src/__mocks__/mockPipelinesProxy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelinesList.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines.ts, frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTable.tsx, frontend/src/concepts/projects/ProjectSelector.tsx, frontend/src/pages/pipelines/global/pipelines/GlobalPipelines.tsx
Initial test for the PipelinesList page which simply loads the page and renders the PipelinesTable with mock data.
Running `cypress:run` or `cypress:open` and selecting `PipelinesList.cy.ts`
=> RHOAIENG-1124: Initial pipelines list page test

backend/src/types.ts, backend/src/utils/componentUtils.ts, backend/src/utils/resourceUtils.ts
Cherry Pick to prep for the inclusion of https://issues.redhat.com/browse/RHOAIENG-2040 as a post release fix.
=> made getSubscriptions into an iterator to reduce memory usage

frontend/src/pages/projects/screens/detail/storage/__tests__/useProjectPvcs.spec.ts
Closes: [RHOAIENG-2067](https://issues.redhat.com/browse/RHOAIENG-2067)
Unit test case for: frontend/src/pages/projects/screens/detail/storage/useProjectPvcs.ts
`npm run test`
coverage:
=> Unit test case for useProjectPvcs

frontend/src/pages/modelServing/__tests__/useModelServingProjects.spec.ts
Closes: [RHOAIENG-2080](https://issues.redhat.com/browse/RHOAIENG-2080)
Unit test case for: frontend/src/pages/modelServing/useModelServingProjects.ts
`npm run test`
coverage:
=> Unit test case for useModelServingProjects

frontend/src/api/__tests__/builds.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-2114
added test for api/k8s/builds file
npm run test
test coverage :
=> Added test for api/k8s/builds

manifests/modelserving/kustomization.yaml
Closes https://issues.redhat.com/browse/RHOAIENG-2057
1. No testing available, update images from manifest files
=> Update model serving images

frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineRuns.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRuns.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesGlobal.ts, frontend/src/concepts/pipelines/EnsureAPIAvailability.tsx, frontend/src/pages/ApplicationsPage.tsx, frontend/src/pages/pipelines/global/pipelines/GlobalPipelines.tsx, frontend/src/pages/pipelines/global/runs/GlobalPipelineRuns.tsx, frontend/src/pages/pipelines/global/runs/GlobalPipelineRunsTabs.tsx
quick layout fix for https://redhat-internal.slack.com/archives/C05SMJ09DD2/p1706551047256789
layout issue was introduced when we needed to add test ids to certain elements. this meant change from a react fragments to a div, which broke some part of pipelines layout ux
Switched back to use the `<></>` and put the test ids elsewhere to keep the same test coverage
1. make sure pipelines topology and application pages extend the full screen
updated how we look for pipelines availability
=> fix layout issues by in pipelines

frontend/src/api/k8s/__tests__/secrets.spec.ts
Closes:  [RHOAIENG-2106](https://issues.redhat.com/browse/RHOAIENG-2106)
Unit test case for: frontend/src/api/k8s/secrets.ts
`npm run test`
coverage:
=> Unit test case for k8s/secrets file

frontend/src/concepts/secrets/apiHooks/useAWSSecret.ts
Cherry pick of https://github.com/opendatahub-io/odh-dashboard/pull/2412 for v2.19 additional fixes.
=> Fix Elyra Secret for new DSP Server Modal

frontend/src/concepts/pipelines/content/createRun/contentSections/ParamsSection.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerBottomTabs.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabParameters.tsx
Fixes [RHOAIENG-1750](https://issues.redhat.com/browse/RHOAIENG-1750)
Fixes all a11y issues flagged by axe Devtools in Pipelines Table page, Runs Table rows, Create/Duplicate page
Before: 
After: 
1. Go to Pipelines page, Runs page, Create Run pages and try running an axe Devtools SCAN 
2. Pull this PR and run an axe Devtools SCAN
Tests being covered in other Pipeline logs/versions tests PR
=> Fix A11y issues with Pipelines page, runs page and Create/Duplicate Run

backend/package-lock.json, backend/package.json, backend/src/app.ts, backend/src/routes/api/k8s/index.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx
JIRA: https://issues.redhat.com/browse/RHOAIENG-2252
Add `@fastify/accepts` to help detect the accept header field in the request. If the first match is `json`, it will parse the data, if not, it will not parse it for the pass through API.
Change the endpoint of fetching the raw logs.
1. Create a pipeline run
2. See the logs
3. Click on `view raw logs` and make sure you can open a new window and see the raw logs there
N/A
=> Refactor the way of fetching raw logs

backend/src/routes/api/k8s/index.ts
JIRA: https://issues.redhat.com/browse/RHOAIENG-2445
A quick fix for the pipeline logs
raw:
in the dashboard
Create a pipeline run and view logs
N/A
=> fix pipeline run logs parsing issue

frontend/src/api/k8s/__tests__/imageStreams.spec.ts
Closes [RHOAIENG-2146](https://issues.redhat.com/browse/RHOAIENG-2146)
Unit Test for k8s/imageStream
`npm run test`
=> Unit Test Case for imageStream

frontend/src/utilities/__tests__/router.spec.ts
Closes  [RHOAIENG-2164](https://issues.redhat.com/browse/RHOAIENG-2164)
Unit Test Case for **router.ts**
`npm run test`
=> Unit Test Case for router

frontend/src/pages/pipelines/global/pipelines/GlobalPipelinesTableToolbar.tsx
Address one small feedback on UX sign off ticket: https://issues.redhat.com/browse/RHOAIENG-1770
1. Go to global pipelines page
2. Check the filters
N/A
=> Change filter name pipeline

manifests/base/kustomization.yaml
Updates the image to include the latest main.
=> Update the incubation image with a more up to date main image

frontend/src/__mocks__/mockInferenceServiceK8sResource.ts, frontend/src/__tests__/cypress/cypress/e2e/modelServing/ServingRuntimeList.cy.ts, frontend/src/api/k8s/inferenceServices.ts, frontend/src/pages/modelServing/screens/projects/utils.ts
Closes:  https://issues.redhat.com/browse/RHOAIENG-2270
Fix edit in kserve modal
1. Create a new Single model server
2. Try to edit it
3. It should work
Before:
After:
=> Fix edit project in kserve modal

frontend/src/api/__tests__/apiMergeUtils.spec.ts, frontend/src/api/apiMergeUtils.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-2152
A small ix to increase the coverage of file 
npm run test
test coverage:
Before:
After:
=> updated the apiMerge Util files.

frontend/src/api/k8s/__tests__/pvcs.spec.ts
Closes: [RHOAIENG-2160](https://issues.redhat.com/browse/RHOAIENG-2160)
Unit test case for: frontend/src/api/k8s/pvcs.ts
`npm run test`
coverage:
=> Unit test case for k8s/pvcs file

frontend/src/api/k8s/__tests__/pods.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-2156
Added unit test case for frontend/src/api/k8s/pods.ts
npm run test
coverage:
=> added tes cases for pod

frontend/src/__mocks__/mockAxiosError.ts, frontend/src/api/k8s/__tests__/projects.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-2157
added test for frontend/src/api/k8s/projects.ts
npm run test
jest coverage:
=> added unit test for project

frontend/src/api/k8s/__tests__/roleBindings.spec.ts
Closes: [RHOAIENG-2161](https://issues.redhat.com/browse/RHOAIENG-2161)
Unit test case for: frontend/src/api/k8s/roleBindings.ts
`npm run test`
Coverage:
=> Unit test case for k8s/roleBindings file

manifests/base/kustomization.yaml
https://issues.redhat.com/browse/RHOAIENG-2543
Adds the merge PR image into the manifests so this branch can be referenced by DevFlags
Manually with the PR image from https://github.com/opendatahub-io/odh-dashboard/pull/2448
After this PR:
```
dashboard:
devFlags:
manifests:
- contextDir: manifests
sourcePath: ''
uri: >-
https://github.com/opendatahub-io/odh-dashboard/tarball/f/pipelines-v2
```
N/A
=> [RHOAIENG-2543] Add manifest image

frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightContent.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeDetailsTab.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeInputOutputTab.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeVolumeMountsTab.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx, frontend/src/concepts/pipelines/topology/__tests__/pipelineUtils.spec.ts, frontend/src/concepts/pipelines/topology/pipelineUtils.ts, frontend/src/k8sTypes.ts, frontend/src/pages/projects/notebook/service.ts
JIRA: https://issues.redhat.com/browse/RHOAIENG-2669
Temp blind fix for the types of pipeline run tasks status and conditions.
=> Fix type issues on pipeline logs

frontend/src/__mocks__/mockPipelineVersionsProxy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/Pipelines.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesGlobal.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesTable.ts, frontend/src/concepts/pipelines/content/DeletePipelinesModal.tsx, frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableExpandedRow.tsx, frontend/src/pages/pipelines/global/pipelines/GlobalNoPipelines.tsx, frontend/src/pages/pipelines/global/pipelines/GlobalPipelinesTableToolbar.tsx, frontend/src/pages/projects/components/DeleteModal.tsx
JIRA: https://issues.redhat.com/browse/RHOAIENG-2212
Add tests for bulk deletion on global pipelines page
In frontend folder, run `npm run cypress:server:build && npm run cypress:server` then in another terminal run `npm run cypress:run:mock`
=> Add tests for deleting pipelines and versions

frontend/src/api/k8s/__tests__/routes.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-2170
added test cases for frontend/src/api/k8s/routes.ts
npm run test
test coverage:
=> added test cases for routes

frontend/src/api/k8s/__tests__/inferenceServices.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-2149
added extra test cases for frontend/src/api/k8s/inferenceServices.ts
npm run test
test coverage:
Before:
After:
=> added extra test cases for inference service

frontend/src/api/k8s/__tests__/serviceAccounts.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-2172
added test cases for frontend/src/api/k8s/serviceAccounts.ts
npm run test
test coverage:
=> added test case for service account

frontend/src/api/__tests__/proxyUtils.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-2159
added test cases for frontend/src/api/proxyUtils.ts
npm run test
test coverage:
=> added test cases for proxyUtils

manifests/modelserving/kustomization.yaml
Addresses: https://issues.redhat.com/browse/RHOAIENG-2664
Updating two image SHAs: Caikit-TGIS and TGIS to latest stable tag for ODH.
=> Update shas for Caikit-TGIS and TGIS

frontend/src/components/table/CheckboxTd.tsx, frontend/src/components/table/TableBase.tsx, frontend/src/components/table/useCheckboxTable.ts, frontend/src/components/table/useCheckboxTableBase.ts, frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTable.tsx, frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTableRow.tsx, frontend/src/concepts/pipelines/content/tables/pipelineVersion/PipelineVersionTable.tsx
closes: https://issues.redhat.com/browse/RHOAIENG-2574
- added a new function to checkbox hook to manage the state of checkboxes that are disabled
- disable checkboxes  when versions is > 0
- only select all from non disabled checkboxes
1. create a DSPA with some pipelines with and without versions
2. test that you cannot select pipelines unless they have no versions
3. test that you can select pipelines with no versions
4. test that select all selects from the subset of "selectable pipelines" and the select all checkbox is selected
5. tests that when deleting multiple after pressing select all, only valid selectable pipelines get deleted
covered by versions
=> added disable delete

frontend/src/components/table/index.ts, frontend/src/components/table/useCheckboxTableBase.ts, frontend/src/concepts/pipelines/content/tables/pipeline/PipelinesTable.tsx, frontend/src/concepts/pipelines/content/tables/pipeline/usePipelinesCheckboxTable.ts, frontend/src/concepts/pipelines/content/tables/pipelineVersion/PipelineVersionTable.tsx, frontend/src/concepts/pipelines/content/tables/pipelineVersion/usePipelineVersionsCheckboxTable.ts
JIRA: https://issues.redhat.com/browse/RHOAIENG-2734
Created 2 hooks `usePipelinesCheckboxTable` and `usePipelineVersionsCheckboxTable` to better organize the code.
Make sure the bulk selection is not broken by this change.
N/A, it's a tech debt.
=> Improve the code to use checkbox table for pipelines and versions

frontend/src/api/pipelines/__tests__/k8s.spec.ts
Closes: [RHOAIENG-2177](https://issues.redhat.com/browse/RHOAIENG-2177)
Unit test case for: frontend/src/api/pipelines/k8s.ts
`npm run test`
Coverage:
=> Add unit test case for pipelines/k8s file

frontend/src/api/k8s/__tests__/users.spec.ts
Closes: [RHOAIENG-2175](https://issues.redhat.com/browse/RHOAIENG-2175)
Unit test case for: frontend/src/api/k8s/users.ts
'npm run test'
Coverage:
=> Unit Test for k8s/Users

frontend/src/__mocks__/mockInferenceServiceK8sResource.ts, frontend/src/__mocks__/mockInferenceServiceModalData.ts, frontend/src/__tests__/cypress/cypress/e2e/modelServing/ServingRuntimeList.cy.ts, frontend/src/api/k8s/__tests__/inferenceServices.spec.ts, frontend/src/api/k8s/inferenceServices.ts, frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeDetails.tsx, frontend/src/pages/modelServing/screens/projects/kServeModal/KServeAutoscalerReplicaSection.tsx, frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx, frontend/src/pages/modelServing/screens/projects/utils.ts, frontend/src/pages/modelServing/screens/types.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-2269
1. Create a New KServe Model
2. Edit it and change the replica count
3. Check that the replica count has changed in the expanded board
4. Check that the edit panel has reflected the changes
=> Fix issue with replica count display

frontend/src/api/k8s/__tests__/groups.spec.ts
Closes: [RHOAIENG-2155](https://issues.redhat.com/browse/RHOAIENG-2155)
Unit test case for: frontend/src/api/k8s/groups.ts
'npm run test'
Coverage:
=> Unit Test for k8s/groups

frontend/src/api/__tests__/errorUtils.spec.ts
=> added test case for errorUtils

backend/src/routes/api/validate-isv/validateISV.ts, backend/src/types.ts, frontend/src/pages/exploreApplication/EnableModal.scss, frontend/src/pages/exploreApplication/EnableVariable.tsx
JIRA: https://issues.redhat.com/browse/RHOAIENG-1899
Our backend is reading the `CronJob` of the `batch/v1beta1` group while that's deprecated and replaced by the `batch/v1` group. Changed the backend to read from the correct group to fetch the resources.
Fixed a small layout issue with the upgrading of PF5 in the enable modal:
1. Find a cluster installed OpenShift AI
2. Enable anaconda
3. Check it works
N/A
=> Fix anaconda validation issue

frontend/src/api/k8s/__tests__/acceleratorProfiles.spec.ts, frontend/src/api/k8s/__tests__/builds.spec.ts, frontend/src/api/k8s/__tests__/dashboardConfig.spec.ts, frontend/src/api/k8s/__tests__/imageStreams.spec.ts, frontend/src/api/k8s/__tests__/projects.spec.ts, frontend/src/api/k8s/__tests__/secrets.spec.ts, frontend/src/concepts/areas/__tests__/useFetchDscStatus.spec.ts, frontend/src/concepts/pipelines/elyra/__tests__/useElyraSecret.spec.ts, frontend/src/pages/modelServing/__tests__/useInferenceServices.spec.ts, frontend/src/pages/notebookController/screens/server/__tests__/useAcceleratorProfiles.spec.ts, frontend/src/pages/projects/projectSharing/__tests__/useGroups.spec.ts, frontend/src/pages/projects/screens/detail/data-connections/__tests__/utils.spec.ts, frontend/src/pages/projects/screens/detail/storage/__tests__/useProjectPvcs.spec.ts, frontend/src/pages/projects/screens/spawner/__tests__/useImageStreams.spec.ts, frontend/src/utilities/__tests__/clusterUtils.spec.ts, frontend/src/utilities/__tests__/markdown.spec.ts, frontend/src/utilities/__tests__/useDetectUser.spec.ts, frontend/src/utilities/__tests__/useWatchGroups.spec.tsx, frontend/src/utilities/__tests__/useWatchSegmentKey.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-2470
Convert all usage of casting to `as jest.Mock` to use `jest.mocked`.
Convert `.mockReturnValue(Promise.resolve` to `.mockResolvedValue`
Convert `.mockReturnValue(Promise.reject` to `.mockRejectedValue`
Simplified `markdown.spec.ts` test to avoid all the mocking and just assert the expected conversion.
unit tests
=> use jest.mocked for type safe mocks

frontend/src/api/k8s/__tests__/events.spec.ts
Closes: [RHOAIENG-2154](https://issues.redhat.com/browse/RHOAIENG-2154)
Unit test case for: frontend/src/api/k8s/events.ts
'npm run test'
Coverage:
=> Unit Test for k8s/events

frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelineCreateRuns.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/createRunPage.ts, frontend/src/__tests__/cypress/cypress/support/commands/application.ts, frontend/src/components/NumberInputWrapper.tsx, frontend/src/concepts/dashboard/DashboardHelpTooltip.tsx, frontend/src/concepts/dashboard/split/DashboardSplitItemLabel.tsx, frontend/src/concepts/dashboard/split/DashboardSplitReserveSpace.tsx, frontend/src/concepts/pipelines/content/createRun/const.ts, frontend/src/concepts/pipelines/content/createRun/contentSections/CatchUp.tsx, frontend/src/concepts/pipelines/content/createRun/contentSections/MaxConcurrencyField.tsx, frontend/src/concepts/pipelines/content/createRun/contentSections/RunTypeSection.tsx, frontend/src/concepts/pipelines/content/createRun/contentSections/RunTypeSectionDateTime.tsx, frontend/src/concepts/pipelines/content/createRun/contentSections/RunTypeSectionScheduled.tsx, frontend/src/concepts/pipelines/content/createRun/contentSections/TriggerTypeField.tsx, frontend/src/concepts/pipelines/content/createRun/submitUtils.ts, frontend/src/concepts/pipelines/content/createRun/types.ts, frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts
https://issues.redhat.com/browse/RHOAIENG-2948
Improved the create job flow to include a couple fields that we were missing (catch up & max concurrency). Reworked the start/end to be more aligned with the mocks and converted the radio buttons into a dropdown.
cc @yannnz / @xianli123 / @kywalker-rh 
https://github.com/opendatahub-io/odh-dashboard/assets/8126518/64471d85-a554-4dbe-bb4e-2ff47d7f7f0d
Create / Duplicate Runs & Jobs
Added Tests for the scheduled section
=> [RHOAIENG-2948] Improve create job

frontend/src/api/k8s/__tests__/utils.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-2169
added test for frontend/src/api/k8s/utils.ts
npm run test
test coverage:
=> added test case for k8s/utils file

frontend/src/pages/projects/screens/detail/data-connections/DataConnectionsTableRow.tsx, frontend/src/pages/projects/screens/detail/data-connections/__tests__/utils.spec.ts, frontend/src/pages/projects/screens/detail/data-connections/data.ts, frontend/src/pages/projects/screens/detail/data-connections/utils.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-1162
Removes Provider column from Data Connection section on Projects page
1. Go to any Project and check the Data connection section. You should not see the "Provider" column
Removed all test related to the "Provider" column
=> Remove provider column from Data connection section

frontend/src/api/k8s/__tests__/templates.spec.ts, frontend/src/api/k8s/templates.ts
Closes: [RHOAIENG-2173](https://issues.redhat.com/browse/RHOAIENG-2173)
unit test case for: frontend/src/api/k8s/templates.ts
`npm run test`
coverage:
=> Unit test case for k8s/templates file

frontend/.eslintrc, frontend/src/concepts/k8s/pods/utils.ts, frontend/src/concepts/pipelines/apiHooks/useAllPipelineVersions.ts, frontend/src/concepts/pipelines/apiHooks/usePipelineQuery.ts, frontend/src/concepts/pipelines/content/PipelineAndVersionContext.tsx, frontend/src/concepts/pipelines/content/PipelineJobReferenceName.tsx, frontend/src/concepts/pipelines/content/createRun/RunPage.tsx, frontend/src/concepts/pipelines/content/createRun/contentSections/ParamsSection.tsx, frontend/src/concepts/pipelines/content/createRun/useRunFormData.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeInputOutputTab.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTabStatus.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/usePodContainerLogState.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/usePodStepsStates.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/utils.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRunJob/PipelineRunJobDetails.tsx, frontend/src/concepts/pipelines/content/tables/utils.ts, frontend/src/concepts/pipelines/content/types.ts, frontend/src/concepts/pipelines/content/utils.tsx, frontend/src/k8sTypes.ts, frontend/src/pages/modelServing/screens/global/utils.ts, frontend/src/pages/pipelines/global/runs/GlobalPipelineRunsTabs.tsx, frontend/src/utilities/__tests__/utils.spec.ts, frontend/src/utilities/utils.ts
Fixes https://issues.redhat.com/browse/RHOAIENG-2413
Turns on the `@typescript-eslint/no-unnecessary-condition` as an `error`.
`npm run test:lint`
Added new unit test for enum utils.
=> re-instate no-unnecessary-condition eslint rule

frontend/src/api/prometheus/__tests__/usePrometheusQuery.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-2162
added test cases for frontend/src/api/prometheus/__tests__/usePrometheusQuery.spec.ts
npm run test
=> added test cases for prometheusQuery

frontend/src/api/pipelines/__tests__/custom.spec.ts
Closes: [RHOAIENG-2165](https://issues.redhat.com/browse/RHOAIENG-2165)
Unit test case for: frontend/src/api/pipelines/custom.ts
`npm run test`
Coverage:
=> Add unit test case for pipeline/custom file

backend/src/utils/componentUtils.ts
Closes https://issues.redhat.com/browse/RHOAIENG-3962
Fix an issue that wasn't properly handling a type in the backend for subscriptions.
1. Create a subscription without `status.installedCSV`
2. Go to the enable page
3. Check that you don't have the following error
No testing coverage since there's no backend testing infra to cover this change
=> Fix error handling for subscriptions in the backend

backend/src/utils/constants.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/experiments.ts, frontend/src/app/AppRoutes.tsx, frontend/src/pages/pipelines/GlobalPipelineExperimentsRoutes.tsx, frontend/src/pages/pipelines/GlobalPipelinesRoutes.tsx, frontend/src/pages/pipelines/global/experiments/GlobalExperiments.tsx, frontend/src/pages/pipelines/global/experiments/GlobalExperimentsTabs.tsx, frontend/src/utilities/NavData.tsx
https://issues.redhat.com/browse/RHOAIENG-3912
Disables experiments nav by default. Supporting both navs while we migrate over. 
* Add the CRD value (`oc apply -f manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml`)
* Add the value to the OdhDashboardConfig (`oc patch -n opendatahub OdhDashboardConfig/odh-dashboard-config -p "{\"spec\":{\"dashboardConfig\":{\"disablePipelineExperiments\": false}}}" --type='merge'`)
* change the `false` to a `true` to disable it
* View the UI Nav
None
/cc @Gkrumbach07
=> Support Experiment sub-feature flag concurrently

frontend/src/__tests__/cypress/cypress/e2e/acceleratorProfiles/AcceleratorProfiles.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/acceleratorProfiles/ManageAcceleratorProfiles.cy.ts, frontend/src/__tests__/cypress/cypress/pages/acceleratorProfile.ts, frontend/src/__tests__/cypress/cypress/pages/components/table.ts, frontend/src/pages/acceleratorProfiles/screens/list/AcceleratorProfiles.tsx, frontend/src/pages/acceleratorProfiles/screens/list/AcceleratorProfilesTable.tsx, frontend/src/pages/acceleratorProfiles/screens/list/AcceleratorProfilesTableRow.tsx, frontend/src/pages/acceleratorProfiles/screens/manage/EditAcceleratorProfile.tsx, frontend/src/pages/acceleratorProfiles/screens/manage/IdentifierSelectField.tsx, frontend/src/pages/acceleratorProfiles/screens/manage/tolerations/TolerationFields.tsx, frontend/src/pages/acceleratorProfiles/screens/manage/tolerations/TolerationsTable.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-1924
Added test cases for acceleratorProfile file 
Migrated acceleratorProfile test from playwright to cypress
npm run test
=> added accelerator profile cypress test

frontend/src/__tests__/cypress/cypress/e2e/projects/projectDetails.cy.ts, frontend/src/__tests__/cypress/cypress/pages/projects.ts, frontend/src/__tests__/integration/pages/projects/ProjectDetails.spec.ts, frontend/src/pages/projects/screens/detail/DetailsSection.tsx, frontend/src/pages/projects/screens/detail/EmptyDetailsList.tsx, frontend/src/pages/projects/screens/detail/ProjectDetailsComponents.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookImageDisplayName.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookTable.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-1925
migrated playwright test frontend/src/__tests__/integration/pages/projects/ProjectDetails.spec.ts 
npm run test
=> Migrated project details tests

manifests/modelserving/kustomization.yaml, manifests/overlays/modelserving/kustomization.yaml
Closes: https://issues.redhat.com/browse/RHOAIENG-3470
and https://issues.redhat.com/browse/RHOAIENG-3468
There will be a separate PR for OVMS later today.
Updated the Caikit-TGIS and TGIS images. One minor update to ODH OVMS image too, it points now to ODH repo (instead of RHOAI one previously)
@heyselbi has informed me the testing has happened on their side
N/A
=> Update TGIS and Caikit-TGIS images for 2.8

frontend/src/utilities/__tests__/valueUnits.spec.ts, frontend/src/utilities/valueUnits.ts
Closes: [RHOAIENG-2679](https://issues.redhat.com/browse/RHOAIENG-2679)
Updated unit test case for frontend/src/utilities/valueUnits.ts
I've changed the IF statement on line 34 of valueUnits.ts so that it's no longer accepting every entry
`npm run test`
Coverage:
Before:
After:
Edit to add completed screen shot:
=> Unit Test Update for utilities/valueUnits

frontend/src/__tests__/cypress/cypress/e2e/projects/ProjectList.cy.ts, frontend/src/__tests__/cypress/cypress/pages/projects.ts
Jira link [Jira](https://issues.redhat.com/browse/RHOAIENG-2043)
Add tests for project list page and verify the basic elements in project list page
In frontend folder, run npm run cypress:server:build && npm run cypress:server then in another terminal run npm run cypress:run:mock
=> RHOAIENG-2043:Add tests for project list page

docs/release-steps.md
Cleanup the release steps to meet the current change to sync incubation and main branches.
=> Update release steps

frontend/src/__tests__/cypress/cypress/e2e/modelServing/ServingRuntimeList.cy.ts, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionFolderPathField.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx, frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx, frontend/src/pages/modelServing/screens/projects/utils.ts, frontend/src/utilities/__tests__/string.spec.ts, frontend/src/utilities/string.ts
Closes: [RHOAIENG-3314](https://issues.redhat.com/browse/RHOAIENG-3314)
Added condition to throw error with path is invalid, also reduced the field debounce timeout to 500ms
<details><summary>Valid path</summary>
</details>
<details><summary>Path with special chars</summary>
</details>
<details><summary>Path with only slash</summary>
</details>
<details><summary>Path with multiple slashes in between</summary>
</details>
<details><summary>Path starting with multiple slashes are invalid</summary>
</details>
1. Open deploy model
2. Enter path with different special chars and check the error.
Added cypress test to check path with different values
Added unit test for string util function …
=> Need proper validation in model path

frontend/src/api/pipelines/k8s.ts, frontend/src/concepts/pipelines/content/configurePipelinesServer/__tests__/utils.spec.ts, frontend/src/concepts/pipelines/content/configurePipelinesServer/utils.ts, manifests/base/kustomization.yaml
https://issues.redhat.com/browse/RHOAIENG-2340
https://issues.redhat.com/browse/RHOAIENG-2579
Minor cleanup to not bring any dev work into `main`.
N/A
Cleaned up tests
=> Merge clean up for DSPv2 API Parity

docs/testing.md, frontend/src/__tests__/cypress/cypress/pages/explore.ts, frontend/src/__tests__/cypress/cypress/support/commands/application.ts, frontend/src/components/OdhExploreCard.tsx
Fixes: https://issues.redhat.com/browse/RHOAIENG-2760
Augment the `ByTestId` cypress commands to support an array of selector values. When an array is present, this informs the API to use the `~=` approach to CSS selectors. The following commands can then be used:
- find all cards
- `cy.findAllByTestId(['card'])`
- find a specific card
- `cy.findByTestId('card data-key')`
- `cy.findByTestId(['card', 'data-key'])`
Modified a cypress test to make use of new api.
None.
=> enhance ByTestId cypress command to support multiple values

frontend/src/__mocks__/mockServingRuntimeK8sResource.ts, frontend/src/__tests__/cypress/cypress/e2e/clusterSettings/ClusterSettings.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/modelServing/ServingRuntimeList.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/notebookImageSettings/NotebookImageSettings.cy.ts
Closes: [RHOAIENG-834](https://issues.redhat.com/browse/RHOAIENG-834)
followup to: https://github.com/opendatahub-io/odh-dashboard/pull/2561
This PR aims to update existing cypress tests to assert network requests for existing cypress test. 
npm run test
=> Update existing cypress tests to assert network requests

frontend/src/__tests__/cypress/cypress/e2e/customServingRuntimes/CustomServingRuntimes.cy.ts, frontend/src/__tests__/cypress/cypress/pages/clusterSettings.ts, frontend/src/__tests__/cypress/cypress/pages/components/DashboardCodeEditor.ts, frontend/src/__tests__/cypress/cypress/pages/servingRuntimes.ts, frontend/src/concepts/dashboard/codeEditor/DashboardCodeEditor.tsx, frontend/src/pages/clusterSettings/ClusterSettings.tsx, frontend/src/pages/clusterSettings/CullerSettings.tsx, frontend/src/pages/clusterSettings/ModelServingPlatformSettings.tsx, frontend/src/pages/clusterSettings/PVCSizeSettings.tsx, frontend/src/pages/clusterSettings/TelemetrySettings.tsx, frontend/src/pages/clusterSettings/TolerationSettings.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAddTemplate.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeHeaderLabels.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeListView.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimePlatformsLabelGroup.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeTableRow.tsx, frontend/src/pages/modelServing/customServingRuntimes/EmptyCustomServingRuntime.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-833
Updated existing test to use testids
1. frontend/src/__tests__/cypress/cypress/e2e/customServingRuntimes/CustomServingRuntimes.cy.ts
2. frontend/src/__tests__/cypress/cypress/e2e/clusterSettings/ClusterSettings.cy.ts
npm run test
=> Added data-testid

frontend/src/__tests__/unit/testUtils/hooks.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-3050
Increased the timeout to address the flake
npm run test
=> unit test flake

frontend/src/concepts/pipelines/elyra/utils.ts
https://issues.redhat.com/browse/RHOAIENG-4529
Switch the elyra engine to Argo for DSPv2 support
This keep the automated runtime-configuration to point elyra engine towards Argo, 
which is default engine supported by DSP v2
Related-to: https://issues.redhat.com/browse/RHOAIENG-1866
Tested manually by including a secret to workbench.
NA
=> Switch the elyra engine to Argo for DSPv2 support

frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelinesTopology.cy.ts
Just a temp fix for some flaky tests causing CI issues on the pipeline details page that will soon be handled by a JIRA ticket; https://issues.redhat.com/browse/RHOAIENG-4562
=> Temp fix for flaky pipeline details page nav cypress tests

frontend/src/__tests__/cypress/cypress/e2e/applications/enabled.cy.ts, frontend/src/__tests__/cypress/cypress/pages/components/Card.ts, frontend/src/__tests__/cypress/cypress/pages/components/JupyterCard.ts, frontend/src/__tests__/cypress/cypress/pages/enabled.ts, frontend/src/components/OdhAppCard.tsx, frontend/src/components/SupportedAppTitle.tsx, frontend/src/pages/enabledApplications/EnabledApplications.tsx
Jira [Link](https://issues.redhat.com/browse/RHOAIENG-2760)
Cypress tests for enabled page
In frontend folder, run npm run cypress:server 
then in another terminal  run npm run cypress:run:mock
=> RHOAIENG-2760:Add cypress tests for enabled page

frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelServingGlobal.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/modelServing/ServingRuntimeList.cy.ts, frontend/src/__tests__/cypress/cypress/pages/distributedWorkloads.ts, frontend/src/__tests__/cypress/cypress/pages/modelMetrics.ts, frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/__tests__/cypress/cypress/pages/projects.ts, frontend/src/components/FieldList.tsx, frontend/src/pages/NotFound.tsx, frontend/src/pages/modelServing/screens/global/EmptyModelServing.tsx, frontend/src/pages/modelServing/screens/global/ModelServingLoading.tsx, frontend/src/pages/modelServing/screens/global/ServeModelButton.tsx, frontend/src/pages/modelServing/screens/metrics/bias/BiasConfigurationPage/BiasConfigurationModal/ManageBiasConfigurationModal.tsx, frontend/src/pages/modelServing/screens/metrics/bias/BiasTab.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionFolderPathField.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionSection.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceNameSection.tsx, frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTable.tsx, frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeTableRow.tsx, frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx, frontend/src/pages/modelServing/screens/projects/ModelServingPlatformButtonAction.tsx, frontend/src/pages/modelServing/screens/projects/ModelServingPlatformSelect.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ManageServingRuntimeModal.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeNameSection.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeReplicaSection.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenInput.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenSection.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-833
Updating following file existing tests to use test ids
1. frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts
2. frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelServingGlobal.cy.ts
3. frontend/src/__tests__/cypress/cypress/e2e/modelServing/ServingRuntimeList.cy.ts
=> added testid

frontend/src/__mocks__/mockPipelineVersionsProxy.ts, frontend/src/concepts/pipelines/kfTypes.ts, frontend/src/concepts/pipelines/topology/__tests__/parseUtils.spec.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-4543
Unit test for already written parseUtils for pipelines topology.
`test:unit`
=> [RHOAIENG-4543] pipelines topology parseUtils unit tests

backend/src/types.ts, backend/src/utils/constants.ts, docs/dashboard-config.md, frontend/src/__mocks__/mockDashboardConfig.ts, frontend/src/__tests__/cypress/cypress/e2e/modelRegistry.cy.ts/ModelRegistry.cy.ts, frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts, frontend/src/app/AppRoutes.tsx, frontend/src/concepts/areas/const.ts, frontend/src/concepts/areas/types.ts, frontend/src/k8sTypes.ts, frontend/src/pages/modelRegistry/ModelRegistryEmpty.tsx, frontend/src/pages/modelRegistry/ModelRegistryRoutes.tsx, frontend/src/pages/modelRegistry/useModelRegistryEnabled.ts, frontend/src/utilities/NavData.tsx, manifests/crd/odhdashboardconfigs.opendatahub.io.crd.yaml, manifests/overlays/odhdashboardconfig/odhdashboardconfig.yaml
Closes https://issues.redhat.com/browse/RHOAIENG-2112
Add Model Registry setup configuration.
1. In a new cluster, deploy the new OdhDashboardConfig crds and crs
2. Open the dashboard, model registry should be disabled
3. Change `disableModelRegistry` attribute in `OdhDashboardConfig` to `false`
4. Check that the section is now enabled
Added first tests to check area
=> Add Model Registry scaffolding

frontend/src/__mocks__/mockRegisteredModel.ts, frontend/src/__mocks__/mockRegisteredModelsList.ts, frontend/src/api/index.ts, frontend/src/api/modelRegistry/k8s.ts, frontend/src/api/models/modelRegistry.ts, frontend/src/concepts/modelRegistry/apiHooks/useModelArtifactById.ts, frontend/src/concepts/modelRegistry/apiHooks/useModelArtifacts.ts, frontend/src/concepts/modelRegistry/apiHooks/useModelRegistries.ts, frontend/src/concepts/modelRegistry/apiHooks/useModelVersionById.ts, frontend/src/concepts/modelRegistry/apiHooks/useModelVersions.ts, frontend/src/concepts/modelRegistry/apiHooks/useRegisteredModelById.ts, frontend/src/concepts/modelRegistry/apiHooks/useRegisteredModels.ts, frontend/src/concepts/modelRegistry/const.ts, frontend/src/concepts/modelRegistry/context/ModelRegistryContext.tsx, frontend/src/concepts/modelRegistry/context/useModelRegistryAPIRoute.ts, frontend/src/concepts/modelRegistry/context/useModelRegistryAPIState.tsx, frontend/src/concepts/modelRegistry/context/useModelRegistryNamespaceCR.ts, frontend/src/concepts/modelRegistry/types.ts, frontend/src/k8sTypes.ts, frontend/src/pages/modelRegistry/ModelRegistryCoreLoader.tsx, frontend/src/pages/modelRegistry/ModelRegistryRoutes.tsx
Closes: [RHOAIENG-2116](https://issues.redhat.com/browse/RHOAIENG-2116)
Collaborated with @manaswinidas and @lucferbux 
Created concept page Model Registry with context and apiHooks
=> Model registry concept

backend/src/server.ts
Closes https://issues.redhat.com/browse/RHOAIENG-4572
Fixes an issue that the dashboard is not getting the clobal cluster certificates when the ODH Operator Certificates functionality is not enabled.
1. Deploy this branch to a cluster
2. Test that you can create a pipeline server connection
No testing converage added.
=> Add ca-bundle.crt to add cluster bundles into the dashboard

manifests/modelserving/caikit-ootb.yaml, manifests/modelserving/ovms-kserve-ootd.yaml, manifests/modelserving/tgis-ootb.yaml
Small nit noticed in https://issues.redhat.com/browse/RHOAIENG-4547
=> Fix indentation for labels in serving manifests

frontend/src/__mocks__/mockPipelineVersionsProxy.ts, frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelinesTopology.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/topology.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDrawerRightTabs.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeVolumeMountsTab.tsx, frontend/src/concepts/pipelines/kfTypes.ts, frontend/src/concepts/pipelines/topology/parseUtils.ts, frontend/src/concepts/pipelines/topology/pipelineTaskTypes.ts, frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.ts
JIRA: https://issues.redhat.com/browse/RHOAIENG-4545
Get the volume mounts based on the `platform_spec` executors and map them on the side panel `Volumes` tab.
If there is no volume mount for the task, show `No content`
1. Upload https://github.com/opendatahub-io/data-science-pipelines/blob/c9916af07f171a586504959a88d73f36dc5a83ef/frontend/src/data/test/create_mount_delete_dynamic_pvc.yaml as a pipeline version
2. Create a run using this pipeline
3. Check the run side panel volumes tab, make sure the volume mounts are the same as is shown in the KubeFlow UI
Add some cypress test cases for the volumes tab
=> Add volumes tab to pipeline run details side panel

frontend/src/__tests__/cypress/cypress/e2e/pipelines/CompareRuns.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/compareRuns.ts, frontend/src/concepts/pipelines/apiHooks/usePipelineRunById.ts, frontend/src/concepts/pipelines/content/compareRuns/CompareRunInvalidRunCount.tsx, frontend/src/concepts/pipelines/content/compareRuns/CompareRunsContext.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetailsActions.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableToolbar.tsx, frontend/src/concepts/pipelines/content/types.ts, frontend/src/pages/pipelines/GlobalPipelineExperimentsRoutes.tsx, frontend/src/pages/pipelines/global/GlobalPipelineCoreDetails.tsx, frontend/src/pages/pipelines/global/experiments/compareRuns/CompareRunsPage.tsx, frontend/src/pages/pipelines/global/experiments/compareRuns/GlobalComparePipelineRunsLoader.tsx, frontend/src/routes/pipelines/experiments.ts
closes: https://issues.redhat.com/browse/RHOAIENG-4657
- adds a context for compare runs page that handles selections and runs in the array
- added routing to extend the context into both the index and /add pages
- added data fetching from url and handling error states
1. navigate to `/experiments/{namespace}/{experimentId}/compareRuns`
2. should show an error state
3. navigate to `/experiments/{namespace}/{experimentId}/compareRuns?runs={run_id}`
4. should not show and error state
5. navigate to `/experiments/{namespace}/{experimentId}/compareRuns?runs=not a run id`
6. should remove the run from the url
7. should show error state
tests added for error states
@yannnz @xianli123 
=> Add compare runs functionality

OWNERS
=> Add Gage to Approvers

frontend/src/__tests__/cypress/cypress/e2e/applications/explore.cy.ts, frontend/src/__tests__/cypress/cypress/pages/components/Card.ts, frontend/src/__tests__/cypress/cypress/pages/components/JupyterCard.ts, frontend/src/__tests__/cypress/cypress/pages/explore.ts, frontend/src/components/OdhExploreCard.tsx, frontend/src/components/SupportedAppTitle.tsx
Closes: #[RHOAIENG-4834](https://issues.redhat.com/browse/RHOAIENG-4834)
This PR aims to update cypress test for explore page
npm run test
=> RHOAIENG-4834:Modify explore page cypress test

frontend/src/__tests__/cypress/cypress/e2e/distributedWorkloads/GlobalDistributedWorkloads.cy.ts, frontend/src/__tests__/cypress/cypress/pages/distributedWorkloads.ts, frontend/src/concepts/distributedWorkloads/DistributedWorkloadsContext.tsx, frontend/src/concepts/distributedWorkloads/__tests__/utils.spec.ts, frontend/src/pages/distributedWorkloads/global/DistributedWorkloadsNoProjects.tsx, frontend/src/pages/distributedWorkloads/global/GlobalDistributedWorkloads.tsx, frontend/src/pages/distributedWorkloads/global/GlobalDistributedWorkloadsTabs.tsx, frontend/src/pages/distributedWorkloads/global/projectMetrics/GlobalDistributedWorkloadsProjectMetricsTab.tsx, frontend/src/pages/distributedWorkloads/global/useDistributedWorkloadsTabs.tsx, frontend/src/pages/distributedWorkloads/global/workloadStatus/DWStatusOverviewDonutChart.tsx, frontend/src/pages/distributedWorkloads/global/workloadStatus/DWWorkloadsTable.tsx, frontend/src/utilities/NavData.tsx
Closes: #[RHOAIENG-4748](https://issues.redhat.com//browse/RHOAIENG-4748)
renamed several instances of "workload" to "distributed workload"
tests updated where necessary, visually ran through UI
tests update to match ui changes
- [ x] The developer has manually tested the changes and verified that the changes work
- [ x] Commits have been squashed into descriptive, self-contained units of work (e.g. 'WIP' and 'Implements feedback' style messages have been removed)
- [ x] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ x] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)
- [ x] Included any …
=> feat(dw): renaming instances of workload to dw

frontend/src/__mocks__/mockPVCK8sResource.ts, frontend/src/__tests__/cypress/cypress/e2e/projects/ClusterStorage.cy.ts, frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts, frontend/src/components/ValueUnitField.tsx, frontend/src/pages/projects/components/PVSizeField.tsx, frontend/src/pages/projects/pvc/MountPathField.tsx, frontend/src/pages/projects/screens/detail/storage/StorageList.tsx, frontend/src/pages/projects/screens/detail/storage/StorageTable.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-3809
added cypress test for cluster storage page
npm run test
=> added cluster storage cypress test

frontend/src/concepts/pipelines/content/PipelineServerActions.tsx
Closes: [RHOAIENG-4829](https://issues.redhat.com/browse/RHOAIENG-4848)
Fixes the position of the dropdown menu for pipeline actions in the pipelines section of project details so that the actions are fully visible.
None
=> [RHOAIENG-4848] Fix positioning of pipeline actions menu

frontend/src/pages/projects/screens/detail/ProjectDetails.tsx, frontend/src/pages/projects/screens/detail/overview/configuration/ConfigurationSection.tsx
Closes: [RHOAIENG-5080](https://issues.redhat.com/browse/RHOAIENG-5080)
Updates the order of the tabs in the project page and the card order in the project configuration section.
Manually
None
=> [RHOAIENG-5080] Update order of tabs on project page

frontend/src/utilities/segmentIOUtils.tsx
https://issues.redhat.com/browse/RHOAIENG-3984
Make segment connections go through the proxy at console.redhat.com
Look at Browsers network tab
Should be none, as the tracking itself has not changed.
=> RHOAIENG-3984 Use the proxy at Red Hat.

frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCard.tsx
Closes: [RHOAIENG-4845](https://issues.redhat.com/browse/RHOAIENG-4845)
Fix action when user selects import pipeline
None
=> [RHOAIENG-4845] Fix for import pipeline button action in overview card

frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
Closes: [RHOAIENG-4994](https://issues.redhat.com/browse/RHOAIENG-4994)
Navigate to the workbenches tab after creating a new workbench
Manually
None
=> [RHOAIENG-4994] Navigate to workbenches section after create

frontend/src/pages/projects/screens/detail/overview/serverModels/SelectMultiModelCard.tsx, frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCard.tsx, frontend/src/pages/projects/screens/detail/overview/trainModels/TrainModelsSection.tsx
Closes: [RHOAIENG-4856](https://issues.redhat.com/browse/RHOAIENG-4856)
Update the warning and move it into the pipelines card.
Fix a typo.
Manually
=> [RHOAIENG-4856] update warning in the project overview page

frontend/package-lock.json, frontend/package.json, frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.ts, frontend/src/concepts/topology/PipelineTaskEdge.tsx, frontend/src/concepts/topology/PipelineVisualizationSurface.tsx, frontend/src/concepts/topology/TaskEdge.tsx, frontend/src/concepts/topology/const.ts, frontend/src/concepts/topology/customNodes/ArtifactTaskNode.tsx, frontend/src/concepts/topology/customNodes/StandardTaskNode.tsx, frontend/src/concepts/topology/factories.ts, frontend/src/concepts/topology/types.ts, frontend/src/concepts/topology/useTopologyController.ts, frontend/src/concepts/topology/utils.ts
https://issues.redhat.com/browse/RHOAIENG-3977
Tested locally using demo pipelines from backend team.
As discussed cc @Gkrumbach07 , tests will be part of a standalone task: https://issues.redhat.com/browse/RHOAIENG-5146
=> Feat(pipelines): Adds support for artifact nodes and vertical layout

frontend/src/__mocks__/mock-upload-configmap.yaml, frontend/src/__mocks__/mockNotebookK8sResource.ts, frontend/src/__mocks__/mockPodK8sResource.ts, frontend/src/__tests__/cypress/cypress/e2e/projects/Workbench.cy.ts, frontend/src/__tests__/cypress/cypress/pages/workbench.ts, frontend/src/pages/projects/components/ExistingPVCField.tsx, frontend/src/pages/projects/notebook/NotebookRouteLink.tsx, frontend/src/pages/projects/notebook/NotebookStatusText.tsx, frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx, frontend/src/pages/projects/notebook/StopNotebookConfirmModal.tsx, frontend/src/pages/projects/pvc/AddNotebookStorage.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookList.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookStorageBars.tsx, frontend/src/pages/projects/screens/spawner/EditSpawnerPage.tsx, frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx, frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx, frontend/src/pages/projects/screens/spawner/dataConnection/DataConnectionField.tsx, frontend/src/pages/projects/screens/spawner/dataConnection/ExistingDataConnectionField.tsx, frontend/src/pages/projects/screens/spawner/deploymentSize/ContainerSizeSelector.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/EnvDataTypeField.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/EnvTypeSelectField.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/EnvUploadField.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/EnvironmentVariables.tsx, frontend/src/pages/projects/screens/spawner/environmentVariables/GenericKeyValuePairField.tsx, frontend/src/pages/projects/screens/spawner/imageSelector/ImageStreamSelector.tsx, frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-3808
added cypress test for workbench Page
npm run test
=> added workbench cypress test

frontend/src/__mocks__/mockRoleBindingK8sResource.ts, frontend/src/__tests__/cypress/cypress/e2e/projects/Permissions.cy.ts, frontend/src/__tests__/cypress/cypress/pages/permissions.ts, frontend/src/pages/projects/projectSharing/ProjectSharingNameInput.tsx, frontend/src/pages/projects/projectSharing/ProjectSharingTable.tsx, frontend/src/pages/projects/projectSharing/ProjectSharingTableRow.tsx, frontend/src/pages/projects/projectSharing/ProjectSharingTableRowAdd.tsx, frontend/src/pages/projects/projectSharing/ProjectSharingTableSection.tsx
Closes:  [RHOAIENG-3807](https://issues.redhat.com/browse/RHOAIENG-3807)
This PR aims to add cypress test for Permissions tab.
`npm run test`
=> Cypress test for permissions tab

frontend/src/__tests__/cypress/cypress/e2e/appLauncher/AppLauncher.cy.ts, frontend/src/__tests__/cypress/cypress/pages/appChrome.ts, frontend/src/__tests__/cypress/cypress/pages/appLauncher.ts, frontend/src/app/AppLauncher.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-4511
added test for application Launcher
npm run test
=> added test for application launcher

frontend/src/__mocks__/mockRegisteredModel.ts, frontend/src/api/modelRegistry/__tests__/custom.spec.ts, frontend/src/components/SimpleDropdownSelect.tsx, frontend/src/concepts/dashboard/DashboardSearchField.tsx, frontend/src/concepts/design/utils.ts, frontend/src/concepts/modelRegistry/apiHooks/useModelVersionsByRegisteredModel.ts, frontend/src/concepts/modelRegistry/context/ModelRegistryContext.tsx, frontend/src/concepts/modelRegistry/types.ts, frontend/src/pages/modelRegistry/ModelRegistryRoutes.tsx, frontend/src/pages/modelRegistry/screens/ModelRegistry.tsx, frontend/src/pages/modelRegistry/screens/ModelRegistrySelector.tsx, frontend/src/pages/modelRegistry/screens/RegisteredModelLabels.tsx, frontend/src/pages/modelRegistry/screens/RegisteredModelLastModified.tsx, frontend/src/pages/modelRegistry/screens/RegisteredModelListView.tsx, frontend/src/pages/modelRegistry/screens/RegisteredModelOwner.tsx, frontend/src/pages/modelRegistry/screens/RegisteredModelTable.tsx, frontend/src/pages/modelRegistry/screens/RegisteredModelTableRow.tsx, frontend/src/pages/modelRegistry/screens/__tests__/utils.spec.ts, frontend/src/pages/modelRegistry/screens/const.ts, frontend/src/pages/modelRegistry/screens/utils.ts
Closes: [RHOAIENG-2231](https://issues.redhat.com/browse/RHOAIENG-2231) [RHOAIENG-2232](https://issues.redhat.com/browse/RHOAIENG-2232)
Created Registered model table page
<details><summary>Registered model page</summary>
</details>
<details><summary>Model registry selector with favorite selection</summary>
</details>
<details><summary>Table searching with keyword</summary>
</details>
<details><summary>Register new version disable for now</summary>
</details>
<details><summary>View archived models disable for now</summary>
</details>
<details><summary>Label popover when less than 8</summary>
</details>
<details><summary>Label modal when greater than or equal to 8</summary>
</details>
<details><summary>Label modal search</summary>
</details>
Open Model registry section from sidebar
Added …
=> Registered model table

frontend/src/__mocks__/mockNotebookK8sResource.ts, frontend/src/__mocks__/mockRoleBindingK8sResource.ts, frontend/src/__mocks__/mockStartNotebookData.ts, frontend/src/api/k8s/__tests__/notebooks.spec.ts, frontend/src/api/k8s/notebooks.ts
Closes: [RHOAIENG-2150](https://issues.redhat.com/browse/RHOAIENG-2150)
Unit Test Case for k8s/notebooks
`npm run test`
=> Unit Test Case for k8s/notebooks

frontend/src/api/prometheus/distributedWorkloads.ts, frontend/src/concepts/distributedWorkloads/DistributedWorkloadsContext.tsx
part of https://issues.redhat.com/browse/RHOAIENG-5293
fixes the nits addressed in pr2645
ran through the app and made sure nothing broke, reran tests
everything still works as it should
=> chore(dw): fix nits related to pr2645

manifests/overlays/modelserving/kustomization.yaml
Closes: https://issues.redhat.com/browse/RHOAIENG-4174 --> main issues
Closes bugs included in the update:
https://issues.redhat.com/browse/RHOAIENG-2937
https://issues.redhat.com/browse/RHOAIENG-2502
https://issues.redhat.com/browse/RHOAIENG-4362
https://issues.redhat.com/browse/RHOAIENG-4936
Updating TGIS and Caikit-TGIS images to latest versions
=> Update SHAs of caikit-tgis and tgis

frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.ts
JIRA: https://issues.redhat.com/browse/RHOAIENG-5349
Refine the logic to recursively render all the tasks on the pipeline details page before we have a solution for the stacked topology node.
1. Import the flip coin pipeline (the file is in the JIRA ticket)
2. View the pipeline version details
3. Check whether all the nodes/tasks are rendered on the topology graph and you can view their details
N/A
=> Show all the nodes in pipeline details topology

frontend/src/concepts/pipelines/apiHooks/usePipelines.ts, frontend/src/concepts/pipelines/context/PipelinesContext.tsx, frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCard.tsx, frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCardMetrics.tsx, frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesOverviewCard.tsx
=> Refactor pipelines context and add useSafePipelines hook

frontend/.eslintignore
Cypress code coverage creates directories inside the `src` dir that contain JS files. These files are picked up by eslint and contain linting errors.
This change simply adds the cypress code coverage folders to the eslint ignore list of files.
Run cypress code coverage:
- Build and run cypress server in one terminal: `npm run cypress:server:build:coverage && npm run cypress:server`
- Run cypress coverage in another terminal: `npm run cypress:run:mock:coverage`
- Now run eslint: `npm run test:lint`
- Before the change 3 errors were present in the `src/__tests__/cypress/coverage/` directory.
- No errors after the change.
N/A
=> eslint ignore cypress coverage

frontend/src/api/prometheus/__tests__/distributedWorkloads.spec.ts, frontend/src/api/prometheus/distributedWorkloads.ts, frontend/src/concepts/distributedWorkloads/utils.tsx, frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/TopResourceConsumingWorkloads.tsx, frontend/src/pages/distributedWorkloads/global/projectMetrics/sections/WorkloadResourceMetricsTable.tsx, frontend/src/pages/distributedWorkloads/global/workloadStatus/DWWorkloadsTable.tsx
As part of https://issues.redhat.com/browse/RHOAIENG-5293
addressing a couple PR nits, it was already mostly taken care of throughout some other PRs that went in (moving things to utility classes/etc)
ran tests, ran app, made sure it still works
updated tests with new data structure
=> chore(dw): refactor otherUsage and getWorkloadName

backend/src/routes/api/notebooks/utils.ts, backend/src/utils/notebookUtils.ts
Cherry pick of https://issues.redhat.com/browse/RHOAIENG-6455
=> Jupyter tile, merge cert info from old notebook to avoid loss

frontend/src/pages/modelRegistry/ModelRegistryRoutes.tsx, frontend/src/pages/modelRegistry/screens/EmptyModelVersions.tsx, frontend/src/pages/modelRegistry/screens/GlobalModelVersionsTabs.tsx, frontend/src/pages/modelRegistry/screens/ModelLabels.tsx, frontend/src/pages/modelRegistry/screens/ModelLastModified.tsx, frontend/src/pages/modelRegistry/screens/ModelVersionListView.tsx, frontend/src/pages/modelRegistry/screens/ModelVersions.tsx, frontend/src/pages/modelRegistry/screens/ModelVersionsHeaderActions.tsx, frontend/src/pages/modelRegistry/screens/ModelVersionsTable.tsx, frontend/src/pages/modelRegistry/screens/ModelVersionsTableColumns.ts, frontend/src/pages/modelRegistry/screens/ModelVersionsTableRow.tsx, frontend/src/pages/modelRegistry/screens/RegisteredModelLink.tsx, frontend/src/pages/modelRegistry/screens/RegisteredModelTable.tsx, frontend/src/pages/modelRegistry/screens/RegisteredModelTableRow.tsx, frontend/src/pages/modelRegistry/screens/RegisteredModelsTableColumns.ts, frontend/src/pages/modelRegistry/screens/__tests__/utils.spec.ts, frontend/src/pages/modelRegistry/screens/const.ts, frontend/src/pages/modelRegistry/screens/utils.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-2236
Closes: https://issues.redhat.com/browse/RHOAIENG-2237
Closes: https://issues.redhat.com/browse/RHOAIENG-2234
Model version table:
Model version table empty state:
1. Go to `Model Registry` tab
2. Click on any registered model in the `Registered Models` table
3. You will be taken to the model versions table corresponding to that specific model 
4. When the model versions table is empty, you will see the empty state in the screenshot provided.
Will be added shortly.
=> Model versions table and empty state

frontend/src/__tests__/cypress/cypress/e2e/acceleratorProfiles/AcceleratorProfiles.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/applications/Administration.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/modelServing/ModelServingGlobal.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/notebookImageSettings/NotebookImageSettings.cy.ts, frontend/src/__tests__/cypress/cypress/e2e/projects/ProjectList.cy.ts, frontend/src/__tests__/cypress/cypress/pages/components/Pagination.ts, frontend/src/__tests__/cypress/cypress/utils/pagination.ts
Closes: [RHOAIENG-5117](https://issues.redhat.com/browse/RHOAIENG-5117)
This PR aims to create a utility to test pagination. Follow up PR will have pagination for pipelines.
`npm run test`
=> Cypress test for pagination

frontend/src/__tests__/cypress/cypress/e2e/projects/ProjectList.cy.ts, frontend/src/__tests__/cypress/cypress/pages/projects.ts
Closes: [RHOAIENG-3836](https://issues.redhat.com//browse/RHOAIENG-3836)
This PR validates when workbench is in running state, that clicking on switch toggle will open modal to stop workbench. The Name and User table filtering, searching, and sorting functionality works properly, and that an Invalid Project name will open error page.
`npm run test`
=> Update ProjectList Cypress test

frontend/src/__tests__/cypress/cypress/e2e/pipelines/PipelinesTopology.cy.ts, frontend/src/__tests__/cypress/cypress/support/commands/odh.ts
Closes: [RHOAIENG-4730](https://issues.redhat.com/browse/RHOAIENG-4730)
added additional test for pipeline job detail page
`npm run test`
=> Test for PipelineJob details action and  drawer

frontend/src/concepts/pipelines/apiHooks/mlmd/types.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/useExecutionsFromMlmdContext.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/useMlmdContext.ts, frontend/src/concepts/pipelines/apiHooks/mlmd/usePipelineRunMlmdContext.ts, frontend/src/concepts/pipelines/apiHooks/usePipelineRunById.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/useExecutionsForPipelineRun.ts, frontend/src/concepts/pipelines/kfTypes.ts, frontend/src/concepts/pipelines/topology/__tests__/parseUtils.spec.ts, frontend/src/concepts/pipelines/topology/parseUtils.ts, frontend/src/concepts/pipelines/topology/pipelineTaskTypes.ts, frontend/src/concepts/pipelines/topology/usePipelineTaskTopology.ts
https://issues.redhat.com/browse/RHOAIENG-6317
=> Read pipeline run node details from mlmd context

backend/src/__tests__/objUtils.spec.ts, backend/src/types.ts, backend/src/utils/notebookUtils.ts, backend/src/utils/objUtils.ts
https://issues.redhat.com/browse/RHOAIENG-6709
=> Merge smarter jupyter values

CONTRIBUTING.md
Add documentation for using frontend script `npm run start:dev:ext`.
Add documentation for port forwarding services when running a local backend.
=> Update CONTIRBUTING.md for port forwarding and frontend start:dev:ext

frontend/src/pages/home/aiFlows/InfoGallery.tsx
[RHOAIENG-7212](https://issues.redhat.com/browse/RHOAIENG-7212)
The spread operator was not needed in this case (nor is it syntactically supported), thus I removed it.
UI stays the same:
I testing by running `npm run test:cypress-ci -- --spec "**/homeAIFlows.cy.ts"`
=> fixed spread error

docs/release-steps.md, frontend/.env, frontend/src/utilities/const.ts, frontend/src/utilities/segmentIOUtils.tsx
Add the internal dashboard version and demonstrate usage in the track events helper utilities (only while in dev mode).
Closes https://issues.redhat.com/browse/RHOAIENG-4219
ran dashboard locally and ensured track events show correct version in the console
None really - just adds new env variable and allows access through const.
=> [RHOAIENG-4219] Add internal dashboard version

OWNERS
=> Add Mike Turley to reviewers & approver

frontend/OWNERS
FYI @manosnoam
Added to frontend approvers only to help avoid accidental backend approvals.
=> Add Noam to the Approvers

frontend/src/concepts/pipelines/content/DeletePipelineServerModal.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-356
Updated delete button text with "Delete pipeline server" of Delete pipeline server modal
1. Create a pipeline server
2. Open Data Science Pipelines -> Pipelines
3. Top right -> Pipeline server actions -> Delete pipeline server
check whether the text of the delete button in the modal is "Delete pipeline server"
Updated the pipeline.cy.ts cypress test
=> Updated delete button for Delete Pipeline Server modal

frontend/src/__tests__/cypress/cypress/e2e/pipelines/Pipelines.cy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesGlobal.ts, frontend/src/concepts/pipelines/content/ViewPipelineServerModal.tsx
[RHOAIENG-2254](https://issues.redhat.com/browse/RHOAIENG-2254)
I deleted the done button from the View Pipeline Configuration Server modal.
Manual testing
I edited tests to not reference this button.
^ Already UX approved
=> deleted done button in view pipeline configuration

docs/testing.md
Fix cypress `npm run cypress:open:mock` example command line.
Update description of dir structure for cypress tests to include `e2e` and `mocked` test dirs.
=> update cypress docs

frontend/src/concepts/pipelines/content/tables/experiment/ExperimentTableBase.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-7125
Active and archived Pipeline experiment table compact
Before changes:
After changes:
1. Enable experiment flag from odhDashboardConfig 
2. Go to the Experiment Page 
3. Check whether the acyive and archived experiment table is compact
=> Changed active and archived pipeline experiment table to compact

frontend/.env
=> Upversion Dashboard to v2.23.0

frontend/src/__tests__/cypress/cypress/pages/pipelines/argoAlert.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/argoAlert.cy.ts, frontend/src/concepts/pipelines/content/InvalidArgoDeploymentAlert.tsx
https://issues.redhat.com/browse/RHOAIENG-6286
Fixed the links by swapping to their correct location.
Manually tested using method outlined [here](https://github.com/opendatahub-io/odh-dashboard/pull/2701) to mock the backend response.
Once mocked, startup the local dev env and load any page to view the banner.
Click the individual links.
N/A
@yannnz
=> fix links for invalid argo deployment alert

frontend/src/utilities/__tests__/utils.spec.ts, frontend/src/utilities/utils.ts
Updated the enum utilities to work for string or mixed enum types. Expanded the unit tests to include various enum definitions.
`npm run test:jest`
New unit tests.
@rsun19
=> update enum utils for string and mixed enums

backend/package-lock.json, frontend/package-lock.json, frontend/package.json
Updated package and lock files for frontend/backend for some version updates related to security
Closes issues:
https://issues.redhat.com/browse/RHOAIENG-8283
https://issues.redhat.com/browse/RHOAIENG-8284
https://issues.redhat.com/browse/RHOAIENG-8285
https://issues.redhat.com/browse/RHOAIENG-8286
Built and ran code locally
None - minor version bumps only
Build should succeed - running locally is also helpful but behavior will not be changed.
=> chore(version): Bump versions for several vulnerable packages

frontend/src/__mocks__/mockPodK8sResource.ts, frontend/src/concepts/k8s/pods/utils.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/LogsTab.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/runLogs/usePodContainerLogState.ts, frontend/src/k8sTypes.ts, frontend/src/types.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-6516
Set the default container to "main" , everytime you switch to the logs, it falls on the main/default  container of the pod
1. Import the pipeline yaml
2. Create a run using the pipeline
3. Check the pod logs, the "main" container is set as default
=> set default container and add groups in the dropdown

backend/src/utils/resourceUtils.ts
https://issues.redhat.com/browse/RHOAIENG-7811
Disable Trusty Bias when the app starts.
Manually, connecting to a RHOAI cluster (and an ODH as sanity nothing happens).
None, we don't have a framework for testing on the backend.
/cc @alexcreasy
=> Added migration for disabling trusty bias for RHOAI

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts, frontend/src/concepts/pipelines/content/configurePipelinesServer/__tests__/utils.spec.ts, frontend/src/concepts/pipelines/content/configurePipelinesServer/utils.ts
JIRA: https://issues.redhat.com/browse/RHOAIENG-3782
Remove the hack implemented in https://github.com/opendatahub-io/odh-dashboard/pull/2592 to insert the region to an AWS S3 endpoint.
2. Configure a pipeline server
3. Check the DSPA of that pipeline server, make sure the `spec.objectStorage.externalStorage.host` doesn't contain the region
4. Make sure the pipeline server is running
N/A, remove or update some tests.
=> Remove DS pipeline endpoint hack

manifests/overlays/odhdashboardconfig/odhdashboardconfig.yaml
Cherry pick of https://github.com/opendatahub-io/odh-dashboard/pull/2907
=> [RHOAIENG-8521] Enable home page in manifest file

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/experiments.cy.ts
Closes:[RHOAIENG-8678](https://issues.redhat.com/browse/RHOAIENG-8678)
I made the last run created at date more dynamic so that it wouldn't break after a set number of months.
`npm run test:cypress-ci -- --spec "**/experiments.cy.ts"`
This is the test
=> fixed test for experiments

frontend/.env
Upversioning the Dashboard for a release.
=> Upversion to v2.24.0

frontend/.env, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/experiments.cy.ts
Late release needs to cherry pick over the upversion env.
=> Cherry-pick "Upversion to v2.24.0"

frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunTable.ts, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx, frontend/src/pages/pipelines/global/experiments/ExperimentRunsListBreadcrumb.tsx
JIRA: https://issues.redhat.com/browse/RHOAIENG-8525
Fix UX issues:
1. Label spacing on breadcrumb
2. Kebab action menu overflow issue
Archive an experiment and go to the experiment runs table to check the UX fixes
N/A
=> Fix UX issues on archived experiment runs table

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts, frontend/src/concepts/pipelines/content/configurePipelinesServer/__tests__/utils.spec.ts, frontend/src/concepts/pipelines/content/configurePipelinesServer/utils.ts
related: https://issues.redhat.com/browse/RHOAIENG-8836
the related jira is a blocker so moving this to fixes branch
=>  Cleanup S3 endpoint host in configurePipelinesServer utils

frontend/package-lock.json, frontend/package.json, frontend/src/concepts/topology/PipelineDefaultTaskGroup.tsx
Before
After
Before
After
Updates pipelines group to show label when hovered to provide access to expand/collapse actions.
To test label updates:
1. Navigate/upload pipelines example with groups: 
[flip_coin_compiled.yml.zip](https://github.com/user-attachments/files/15917833/flip_coin_compiled.yml.zip)
2. Expand a group
3. Zoom out to low scale
4. Verify that the label is shown when hovered and expand/collapse actions can be accessed in this UI state 
To test group boundary fix:
1. Upload [Pipeline time-series-dense-encoder-forecasting.yaml.zip](https://github.com/user-attachments/files/15917849/Pipeline.time-series-dense-encoder-forecasting.yaml.zip)
2. Verify that group boundaries persist when zooming in / out. 
N/A …
=> [RHOAIENG-8124] Show Pipeline Group Label on Hover at Low Scale

frontend/src/api/k8s/__tests__/clusterQueues.spec.ts, frontend/src/api/k8s/__tests__/configMaps.spec.ts, frontend/src/api/k8s/__tests__/inferenceServices.spec.ts, frontend/src/api/k8s/__tests__/localQueues.spec.ts, frontend/src/api/k8s/__tests__/projects.spec.ts, frontend/src/api/k8s/__tests__/pvcs.spec.ts, frontend/src/api/k8s/__tests__/roleBindings.spec.ts, frontend/src/api/k8s/__tests__/secrets.spec.ts, frontend/src/api/k8s/__tests__/servingRuntimes.spec.ts, frontend/src/api/k8s/__tests__/workloads.spec.ts, frontend/src/api/pipelines/__tests__/k8s.spec.ts, frontend/src/pages/projects/screens/detail/storage/__tests__/useProjectPvcs.spec.ts
Closes: [RHOAIENG-2733](https://issues.redhat.com/browse/RHOAIENG-2733)
Refactored k8 resources to reference exported members.
`npm run test:unit`
I ran the unit tests. New tests are not needed because only unit test files were changed.
=> refactored k8 resources

frontend/.eslintrc, frontend/src/__tests__/cypress/cypress/pages/components/JupyterCard.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/application.cy.ts
Closes:  [RHOAIENG-5298](https://issues.redhat.com/browse/RHOAIENG-5298)
Need consistency within test files on how `ODH_PRODUCT_NAME` is used. Added an eslint rule to enforce that it is used in Cypress testing to avoid test failures.
`npm run test`
Alternatively, you can run the test files that were changed. Run them, then change the `.env` var for `ODH_PRODUCT_NAME`, then run again, and see the name change.
I implemented the tests.
=> configured default environment for cypress

manifests/overlays/apps/base/rhoai/rhoai-docs.yaml
Cherry pick of https://github.com/opendatahub-io/odh-dashboard/pull/2964, Closes [RHOAIENG-9175](https://issues.redhat.com/browse/RHOAIENG-9175)
=> Broken link to Fraud Detection tutorial in Dashboard Home (RHOAI 2.11.0)

frontend/src/__tests__/cypress/cypress/tests/mocked/projects/workbench.cy.ts, frontend/src/api/k8s/notebooks.ts, frontend/src/concepts/k8s/__tests__/utils.spec.ts, frontend/src/concepts/k8s/utils.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-824
Workbenches start fine with names containing only numbers. This PR adds a prefix wb- for names starting with only numbers.
1. Try creating a workbench that contains only numbers and check whether it starts fine
Added both unit and e2e tests
=> Handle only numbers workbench names

frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/experiments.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesSection.ts, frontend/src/app/App.scss, frontend/src/app/AppLauncher.scss, frontend/src/app/AppLauncher.tsx, frontend/src/app/HeaderTools.tsx, frontend/src/components/OdhAppCard.tsx, frontend/src/components/SimpleMenuActions.tsx, frontend/src/components/ValueUnitField.tsx, frontend/src/concepts/pipelines/content/PipelineServerActions.tsx, frontend/src/concepts/pipelines/content/configurePipelinesServer/PipelineDropdown.tsx, frontend/src/concepts/pipelines/content/tables/experiment/ExperimentTableToolbar.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTable.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx, frontend/src/pages/pipelines/global/pipelines/GlobalPipelinesTableToolbar.tsx, frontend/src/pages/projects/components/PVSizeField.tsx, frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx, frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx
Closes: https://issues.redhat.com/browse/RHOAIENG-2404
Upgraded some of the patternfly deprecated component to use patternfly v5 component
1. check the functionality of application launcher
2. check the pipeline dropdown of configure pipeline server modal
3. check the toolbar dropdown of pipeline table, experiment table and pipeline run table
4. check the Value Unit field dropdown of workbenches and model server modal
Updated some of the cypress test 
=> first group for removing deprecated patternfly component

.gitignore, backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json
Closes: [RHOAIENG-9094](https://issues.redhat.com//browse/RHOAIENG-9094) [RHOAIENG-9095](https://issues.redhat.com//browse/RHOAIENG-9095)
Override version of 'ws' to remove vulnerability (frontend and backend)
Deploy and verify nothing is broken
N/A - no code changes.
=> Override version of transitive dependency 'ws' (RHOAIENG-9094)

frontend/src/components/ExternalLink.tsx, frontend/src/components/OdhDocCard.tsx, frontend/src/concepts/analyticsTracking/segmentIOUtils.tsx, frontend/src/concepts/analyticsTracking/trackingProperties.ts, frontend/src/concepts/analyticsTracking/useSegmentTracking.ts, frontend/src/concepts/analyticsTracking/useTrackHistory.ts, frontend/src/pages/enabledApplications/EnabledApplications.tsx, frontend/src/pages/exploreApplication/ExploreApplications.tsx, frontend/src/pages/exploreApplication/GetStartedPanel.tsx, frontend/src/pages/home/projects/ProjectCard.tsx, frontend/src/pages/home/useEnableTeamSection.tsx, frontend/src/pages/learningCenter/LearningCenterToolbar.tsx, frontend/src/pages/notebookController/screens/server/SpawnerPage.tsx, frontend/src/pages/projects/notebook/NotebookRouteLink.tsx, frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx, frontend/src/pages/projects/screens/projects/DeleteProjectModal.tsx, frontend/src/pages/projects/screens/projects/ManageProjectModal.tsx, frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
Closes https://issues.redhat.com/browse/RHOAIENG-9476
Break out the various types of segment interaction from the one function into specialised ones.
Have typed methods for custom-event tracking (i.e. events other than page-view).
Get rid of the free-form fireTrackingEventRaw function.
Manual testing and watching the developer console
@andrewballantyne does this go into the direction you thought of?
Note this builds on top of #2989
=> [RHOAIENG-9476] Create base firing event

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/executions.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/mlmdUtils.ts
Closes: [RHOAIENG-9745](https://issues.redhat.com/browse/RHOAIENG-9745)
Allow interception of mlmd requests on Cypress to verify that they are doing the right thing
`npm run test`
Tests already included in `executions.cy.ts`
=> added ability to intercept mlmd requests

frontend/src/concepts/pipelines/content/configurePipelinesServer/utils.ts
JIRA: [RHOAIENG-4850](https://issues.redhat.com/browse/RHOAIENG-4850)
Catch the conflict error before creating the `dashboard-dspa-secret` and delete it so it won't block the new secret and server creation.
1. Configure a pipeline server in a project
2. Go to the dashboard console and delete DataSciencePipelinesApplication CR in that project
3. Verify the secret named `dashboard-dspa-secret` is not deleted
4. Go back to the dashboard, you should see the black page to ask you to configure the pipeline server again (because DSPA CR is deleted)
5. Configure a new server (it doesn't matter if it's valid or not, use different inputs in the fields)
6. There should be an error saying "dashboard-dspa-secret already exists", and if you go to check `dashboard-dspa-secret` in the console, the field …
=> Delete conflict dspa secret when creating pipeline server

backend/src/types.ts, backend/src/utils/constants.ts, docs/dashboard-config.md, frontend/src/__mocks__/mockDashboardConfig.ts, frontend/src/api/pipelines/__tests__/custom.spec.ts, frontend/src/api/pipelines/callTypes.ts, frontend/src/api/pipelines/custom.ts, frontend/src/concepts/areas/const.ts, frontend/src/concepts/areas/types.ts, frontend/src/concepts/pipelines/apiHooks/__tests__/useArtifactStorage.spec.ts, frontend/src/concepts/pipelines/apiHooks/useArtifactStorage.ts, frontend/src/concepts/pipelines/context/usePipelineAPIState.ts, frontend/src/concepts/pipelines/types.ts, frontend/src/k8sTypes.ts
Closes: https://issues.redhat.com/browse/RHOAIENG-9677
Added feature flag `disableArtifactsAPI`
Added proxy call
added hook to return different  object based on API call 
manually console logging the useArtifactStorage function
added jest tests for hooks
=> infrastructure proxy call for artifacts API

frontend/.env, manifests/odh/params.env
=> Update image & version

frontend/src/concepts/pipelines/content/pipelineSelector/PipelineSelector.tsx
https://issues.redhat.com/browse/RHOAIENG-9752
When pipeline name is too long, clicking on the `upload new version` dropdown action button opens a modal and check the functionality
Import a pipeline with long pipeline name
Click on the kebab action for the long pipeline name in the pipeline table
Click on the upload new version modal 
Check the modal
Just truncating the text, no test 
=> truncated pipeline selector

frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx, frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
https://issues.redhat.com/browse/RHOAIENG-9911
Updating the Title and the Button in the Model Serving Modal - the titles are conditioned by if it's an edit or not. 
Tested Locally
Updated Unit tests
- [V] The developer has manually tested the changes and verified that the changes work
- [V ] The developer has added tests or explained why testing cannot be added (unit or cypress tests for related changes)
=> Model Serving edit modal should change the title

frontend/src/__mocks__/mlmd/mockGetArtifacts.ts, frontend/src/__mocks__/mlmd/mockGetArtifactsByContext.ts, frontend/src/__mocks__/mlmd/mockGetEventsByExecutionIDs.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/topology.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/artifacts.cy.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/ArtifactVisualization.tsx
https://issues.redhat.com/browse/RHOAIENG-9738
Added cypress test for visualization tab
npm run test
=> added cypress test for visualization tab

frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/__tests__/cypress/cypress/support/commands/application.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionDeploy.cy.ts, frontend/src/pages/modelRegistry/screens/RegisteredModels/useProjectErrorForRegisteredModel.ts, frontend/src/pages/modelRegistry/screens/__tests__/useProjectErrorForRegisteredModel.spec.ts, frontend/src/pages/modelRegistry/screens/components/DeployRegisteredModelModal.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionExistingField.tsx
Part of https://issues.redhat.com/browse/RHOAIENG-2404
1. Added back the `Recommended` data connection label that was accidentally removed due to resolving conflicts.
2. Fixed a small issue: there is a flickering when choosing a multi-model platform project with no model servers in it because we didn't check the loading status of fetching the model servers. Now it's fixed.
1. Choose a multi-model platform project with no model servers, make sure there is no flickering
2. Make sure the recommended label appears when the data connection matches the model artifact
Updated the unit tests due to the function changes.
=> Follow-up fixes for model registry deployment modal

backend/src/routes/api/groups-config/groupsConfigUtil.ts, backend/src/routes/api/notebooks/utils.ts, backend/src/routes/api/status/adminAllowedUsers.ts, backend/src/routes/api/status/statusUtils.ts, backend/src/types.ts, backend/src/utils/fileUtils.ts, backend/src/utils/notebookUtils.ts, backend/src/utils/route-security.ts, backend/src/utils/userUtils.ts, frontend/src/concepts/analyticsTracking/segmentIOUtils.tsx, frontend/src/concepts/analyticsTracking/trackingProperties.ts, frontend/src/concepts/analyticsTracking/useSegmentTracking.ts, frontend/src/concepts/analyticsTracking/useTrackUser.ts, frontend/src/redux/types.ts
Clean version of #3093, closes #3093
Closes https://issues.redhat.com/browse/RHOAIENG-9480
In cases where we have a sso-user-id , supply this to segment tracking instead of the anonymous one.
So far.. manual inspection only.
Manual testing via inspection of browser console
cc @christianvogt
=> RHOAIENG-9480 Update useTrackUser for Developer Sandbox

frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/pages/modelRegistry/screens/components/DeployRegisteredModelModal.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionExistingField.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionFolderPathField.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceFrameworkSection.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceNameSection.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceServingRuntimeSection.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ProjectSelector.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/AuthServingRuntimeSection.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTokenSection.tsx, frontend/src/pages/modelServing/screens/projects/kServeModal/KServeAutoscalerReplicaSection.tsx, frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx, frontend/src/pages/notebookController/screens/server/AcceleratorProfileSelectField.tsx
JIRA: [RHOAIENG-10134](https://issues.redhat.com/browse/RHOAIENG-10134)
Change the layout and some texting based on the mockup here https://www.figma.com/design/oWUToVG5TikXyDGFHNIK87/Model-Serving-post-Summit-2024?node-id=2115-20976&t=A5cSaE6FTIX2bRjx-0
1. Make the project name bold in the alert if there is an error with the project when deploying the model version
2. Multi-model platform
3. Single-model platform
1. Check the deployment modal for both multi-model platform projects and single-model-platform projects
2. Make sure the layout is aligned with the mockup and the function is working as expected
N/A, UX updates, I only updated the cypress test a little bit due to the text and layout changes …
=> Adapt model deployment modals to the latest design

backend/src/utils/resourceUtils.ts
closes: https://issues.redhat.com/browse/RHOAIENG-8499
Removed deprecated migrateTemplateDisablement
ran tests, ran app locally, no issues
none
=> chore: 8499 remove deprecated migrateTemplateDisablement

frontend/src/concepts/pipelines/content/configurePipelinesServer/ObjectStorageSection.tsx
https://issues.redhat.com/browse/RHOAIENG-11962
Removed the warning shown up in the console when open up the configure pipeline server modal
1. Navigate to a project (create one if needed)
2. Click on the Pipeline tab
3. Click on the primary button to create a pipeline server
N/A
=> React error- pipeline server creation modal

frontend/src/concepts/pipelines/content/pipelinesDetails/pipeline/PipelineTaskDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeInputOutputTab.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsInputOutput.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/taskDetails/TaskDetailsPrintKeyValues.tsx
JIRA: https://issues.redhat.com/browse/RHOAIENG-7944
Update the layout in the side panel to make it align with the design. Mainly made the following changes:
1. Use Flex layout instead of Stack to better set the space between sections
2. Based on the mockup, we wrap the text of the long parameter names instead of truncating them. Here I removed the `Truncate` component and use `DescriptionList` for the layout, and set a width for the terms.
1. Import some pipelines
2. Check the pipeline node on pipeline version details page, make sure the definitions text are correctly wrapped
3. Create some runs
4. Check the executions node and make sure the space between sections are similar to the mockups
N/A, layout changes only, we need UX approvals.
If you …
=> Update layout in the pipelines and runs node side panel

frontend/src/pages/projects/notebook/NotebookStatusToggle.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx, frontend/src/pages/projects/screens/projects/NotebookStateStatus.tsx
https://issues.redhat.com/browse/RHOAIENG-9988
https://issues.redhat.com/browse/RHOAIENG-6485
If a Workbench is stopped/started using toggle via the Workbench tab inside Data science Projects, the state is updated in the projects view. Likewise, if a workbench is stopped/started via the projects view toggle, it will be updated
1. Create a Data Science Project
2.  Create a new workbench
3.  Open your project in a new browser tab
4. Navigate to the Workbenches tab and verify your workbench is in 'Running' state.
5. In Projects browser tab, observe its in running state
6. Use both browsers to change the toggle states and observe correct behaviours
N/A
=> Workbench toggle changing state

backend/src/routes/api/images/__tests__/imageUtils.spec.ts, backend/src/routes/api/images/imageUtils.ts, backend/src/utils/constants.ts, frontend/src/concepts/areas/__tests__/utils.spec.ts
https://issues.redhat.com/browse/RHOAIENG-12579
Returned concepts/areas test for the utility
Fix the location of the RegExp test for image path -- was in frontend (deleted) and needed to be against backend usage (moved out of the function to use in a test)
--
FYI, this was found using `git bisect` after I noticed one of the tests were gone (went looking for them). A simple "`cat <file-path>`" check was done on each location of bisect. Starting with when I added the test file originally and "now". Was a pretty smooth process.
`npm run test:jest -- <file>` in the frontend and backend folders.
Tests added.
=> Return tests & fix imageUtils test for the RegExp

backend/package-lock.json, backend/package.json
JIRA: https://issues.redhat.com/browse/RHOAIENG-12691
This CVE is from `fast-xml-parser` package, which is a sub-dependency of `minio` package. We don't use the package anymore because we removed it in https://github.com/opendatahub-io/odh-dashboard/pull/3086 and use DSP Artifacts API to fetch the storage object instead of connecting to the minio.
So remove the dependency here to fix the CVE.
Make sure there is no `fast-xml-parser` in package-lock.json and the dashboard is running with no problem.
N/A
=> CVE-2024-41818 odh-dashboard-container: ReDOS at currency parsing in currency.js [main]

manifests/rhoai/shared/base/nvidia-nim-validator-cron.yaml
Create a Template for NIM ServingRuntime when NIM app is enabled.
The Template should not be shown in the `Serving Runtime` list of `Settings`.
Check KServe installation in the status of DataScienceCluster before validating ngc api key, when enabling NIM app.
Negative scenario 1:
1. Enter an invalid ngc api key to enable NIM
2. Check if the Job for validating the api key fails
3. Check if the NIM application is not enabled
4. Check if the Template `nvidia-nim-serving-template` doesn't exist
Negative scenario 2:
1. Not enable KServe for Openshift AI installation.
2. Enter a valid ngc api key to enable NIM
3. Check if the Job for validating the api key fails
4. Check if the NIM application is not enabled
Positive scenario:
1. Enable KServe for Openshift AI installation.
2. Enter a valid ngc …
=> Create Template for NIM deployment & Check KServe Installation before enabling NIM

frontend/src/concepts/pipelines/content/InvalidArgoDeploymentAlert.tsx
Closes: [RHOAIENG-9505](https://issues.redhat.com/browse/RHOAIENG-9505)
Fixes small type error of a missing space in the Argo workflow warning
Tested using the Cypress file `argoAlert.cy.ts` 
Before:
After:
=> Typo fix in Argo Workflow warning

frontend/.env, frontend/src/__tests__/cypress/cypress/tests/mocked/projects/clusterStorage.cy.ts, frontend/src/pages/projects/notebook/ConnectedNotebookNames.tsx, frontend/src/pages/projects/notebook/StorageNotebookConnections.tsx, frontend/src/pages/projects/screens/detail/storage/ManageStorageModal.tsx, frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx, frontend/src/pages/projects/screens/spawner/spawnerUtils.ts, frontend/src/pages/projects/screens/spawner/storage/AddExistingStorageField.tsx, frontend/src/pages/projects/screens/spawner/storage/StorageClassSelect.tsx, frontend/src/pages/projects/screens/spawner/storage/StorageField.tsx, frontend/src/pages/projects/screens/spawner/storage/utils.ts, manifests/core-bases/base/cluster-role.yaml, manifests/core-bases/base/role.yaml, manifests/odh/params.env
[18b67eb](https://github.com/opendatahub-io/odh-dashboard/pull/3241/commits/18b67eb97e3d62bf5117a7c486395d31d81aa8ae) includes changes from the [release instructions](https://spaces.redhat.com/pages/viewpage.action?spaceKey=RHODS&title=Dashboard+ODH+Release).
Also includes [84628b2](https://github.com/opendatahub-io/odh-dashboard/pull/3241/commits/84628b28ea751dc64377b303150b6edcc2d15123) which was merged to main after this release branch was created but we want to include.
=> v2.26.2-odh-release

frontend/src/api/k8s/templates.ts, frontend/src/pages/modelServing/screens/global/DeleteInferenceServiceModal.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/global/ServeModelButton.tsx, frontend/src/pages/modelServing/screens/projects/EmptyNIMModelServingCard.tsx, frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx, frontend/src/pages/modelServing/screens/projects/NIMServiceModal/DeployNIMServiceModal.tsx, frontend/src/pages/modelServing/screens/projects/NIMServiceModal/NIMModelListSection.tsx, frontend/src/pages/modelServing/screens/projects/nimUtils.ts, frontend/src/pages/modelServing/screens/projects/useIsNIMAvailable.ts, frontend/src/pages/projects/screens/detail/overview/serverModels/AddModelFooter.tsx, frontend/src/pages/projects/screens/detail/overview/serverModels/PlatformSelectSection.tsx, frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelCard.tsx
https://issues.redhat.com/browse/APPENG-2711
https://issues.redhat.com/browse/APPENG-2713
Fixed NIM flow based on NIM enablement and UI feature flag.
Hiding 'Deploy' button and 'Edit' on models tab and Model Serving navigation
Fixed the list on NIM Models to display all the versions not just the latest.
1. disableNIMModelServing: true,  validation_result false -  NIM model card does not show up [Correct]
2. disableNIMModelServing: false,  validation_result true -  NIM model card show up in overview and models tab on selection of data science project [correct]
3. disableNIMModelServing: false, validation_result false -  NIM model card does not show up [Correct]
=> fix: NIM flow based on NIM enablement and UI feature flag

backend/src/routes/api/images/imageUtils.ts
JIRA: https://issues.redhat.com/browse/RHOAIENG-389
Simply update the error message returned by the backend.
Before:
After:
1. Import a custom notebook image
2. Import another custom notebook image with the same name
3. Check the error message
N/A, backend change.
=> Update error message when importing custom notebook image

backend/src/routes/api/nim-serving/index.ts, frontend/src/api/k8s/servingRuntimes.ts, frontend/src/pages/modelServing/screens/projects/NIMServiceModal/DeployNIMServiceModal.tsx, frontend/src/pages/modelServing/screens/projects/NIMServiceModal/NIMModelListSection.tsx, frontend/src/pages/modelServing/screens/projects/__tests__/utils.spec.ts, frontend/src/pages/modelServing/screens/projects/nimUtils.ts, frontend/src/pages/modelServing/screens/projects/utils.ts
https://issues.redhat.com/browse/RHOAIENG-13874
=> Config map nim model name fetch (#3276)

frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeDetails.tsx, frontend/src/pages/modelServing/screens/projects/NIMServiceModal/DeployNIMServiceModal.tsx
https://issues.redhat.com/browse/RHOAIENG-14039
The fix to display the correct Model server sizes on the expanded section.
Tested locally
Tested with setting the sizes of the Model to Medium, Large and Custom. 
=> NIM Model size propagated to the expanded section

frontend/src/concepts/pipelines/EnsureCompatiblePipelineServer.tsx
JIRA: [RHOAIENG-6755](https://issues.redhat.com/browse/RHOAIENG-6755)
Update the doc link as mentioned in the JIRA.
1. Create a project and configure a pipeline server
2. Go to the OpenShift console and edit the DSPA in the project, change `spec.dspVersion` from `v2` to `v1`
3. Go to the pipelines page, check the error message
4. Click on the link and make sure it opens https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/2.13/html/release_notes/support-removals_relnotes
N/A
=> Update doc link for deprecated pipeline version removals

frontend/src/pages/notebookController/screens/server/AcceleratorProfileSelectField.tsx
https://issues.redhat.com/browse/RHOAIENG-13937
Setting the max number of accelerators to 999 to avoid NaN.
Tested by trying to put in the numbers higher than 999. 
=> Max number of accelerators

backend/package-lock.json, backend/package.json
JIRA: https://issues.redhat.com/browse/RHOAIENG-12612
Cherry-pick the fix in https://github.com/opendatahub-io/odh-dashboard/pull/3193.
=> CVE-2024-41818 odh-dashboard-container: ReDOS at currency parsing in currency.js [RHOAI 2.13]

backend/package-lock.json, frontend/package-lock.json
This is not associated with any JIRA. This PR will address the CVEs reported by npm audit.
This is a fix for vulnerabiliites reported by npm audit.
<b>Frontend</b>:
before
after
<b>Backend</b>:
before
after: (The remaining ones are the CVEs related to kubernetes/client-node)
`npm install`
`npm audit` in both frontend and backend folder.
N/A
=> Upgrade packages to fix npm audit vulnerabilities

frontend/src/__tests__/cypress/cypress/tests/mocked/projects/workbench.cy.ts, frontend/src/pages/modelServing/screens/projects/ModelMeshSection/ServingRuntimeDetails.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx, frontend/src/pages/notebookController/screens/server/SizeSelectField.tsx, frontend/src/pages/projects/screens/spawner/spawnerUtils.ts
Per testing feedback on https://issues.redhat.com/browse/RHOAIENG-291 cc @antowaddle 
<details><summary>Before</summary>
</details>
<details><summary>After</summary>
</details>
1. Notebook Server -> Start a Notebook Server -> Container Size dropdown
2. DSPs -> Workbenches -> Create Workbench -  Container Size dropdown
3.  DSPs -> Models -> Deploy Model -  Model server size dropdown
4. DSPs -> Models -> Deployed Models table -> Expand model -> Verify "Model Server Size"  units are correct
N/A, tests have been added and updated in https://github.com/opendatahub-io/odh-dashboard/pull/3338
=> [RHOAIENG-291]: Update Remaining Mi/Gi Instances

frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
https://issues.redhat.com/browse/RHOAIENG-14848
- create a project
- from the project details, go to the `Models` tab
- add a model server
- deploy a model
- edit the modal
- Expect the `Model server` and the `existing data connection` to be populated
cc @mturley
=> fix editing modelmesh prefill

frontend/src/components/MultiSelection.tsx, frontend/src/pages/modelServing/screens/metrics/bias/BiasMetricConfigSelector.tsx, frontend/src/pages/projects/screens/spawner/deploymentSize/ContainerSizeSelector.tsx
Remnant of [RHOAIENG-2404](https://issues.redhat.com/browse/RHOAIENG-2404)
Removes debugging code that was left in.
Verified the debug text is not shown in the UI.
No impact on tests
=> Remove extraneous developer debugging code

frontend/.eslintrc, frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDeployModal.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/acceleratorProfiles/manageAcceleratorProfiles.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts, frontend/src/components/MultiSelection.tsx, frontend/src/components/SimpleSelect.tsx, frontend/src/components/TruncatedText.tsx, frontend/src/components/TypeaheadSelect.tsx, frontend/src/concepts/connectionTypes/fields/DropdownFormField.tsx, frontend/src/concepts/pipelines/content/compareRuns/metricsSection/PipelineRunArtifactSelect.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableToolbarBase.tsx, frontend/src/concepts/roleBinding/RoleBindingPermissionsPermissionSelection.tsx, frontend/src/pages/BYONImages/BYONImageModal/AcceleratorIdentifierMultiselect.tsx, frontend/src/pages/acceleratorProfiles/screens/manage/IdentifierSelectField.tsx, frontend/src/pages/connectionTypes/manage/ConnectionTypeDataFieldModal.tsx, frontend/src/pages/connectionTypes/manage/ConnectionTypeFieldMoveModal.tsx, frontend/src/pages/modelRegistry/screens/ModelRegistrySelector.tsx, frontend/src/pages/modelRegistry/screens/components/DeployRegisteredModelModal.tsx, frontend/src/pages/modelServing/customServingRuntimes/CustomServingRuntimeAPIProtocolSelector.tsx, frontend/src/pages/modelServing/screens/metrics/bias/BiasConfigurationPage/BiasConfigurationModal/MetricTypeField.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/DataConnectionExistingField.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceFrameworkSection.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceServingRuntimeSection.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ProjectSelector.tsx, frontend/src/pages/modelServing/screens/projects/NIMServiceModal/NIMModelListSection.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeSizeSection.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx, frontend/src/pages/projects/screens/spawner/storage/StorageClassSelect.tsx
JIRA: [RHOAIENG-10833](https://issues.redhat.com/browse/RHOAIENG-10833)
Update one-option dropdown UX as mentioned in the JIRA ticket.
I created a [doc](https://docs.google.com/document/d/1tHpzrmqDCEuEdmkqoPscCCm-oYFtUDCV8QwcvebwhA0/edit) to track the effort in case I missed anything, please refer to it.
There will be several commits in this PR to make it easier for the reviewers:
- commit 1: Update the `SimpleSelect` component to make it default to be disabled when there is only one or fewer options in the dropdown and auto-select that option. Also, make the description to be previewed under the dropdown toggle and truncate it to 2 lines if it's too long. Also, updated some usages in the code, please refer to the doc
- commit 2: Replace some use cases of using `Select` component directly …
=> Update one-option Select UX

frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelinesGlobal.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts, frontend/src/concepts/pipelines/EnsureAPIAvailability.tsx, frontend/src/concepts/pipelines/EnsureCompatiblePipelineServer.tsx, frontend/src/concepts/pipelines/content/PipelineServerActions.tsx, frontend/src/pages/pipelines/global/PipelineCoreApplicationPage.tsx
https://issues.redhat.com/browse/RHOAIENG-13936
update the wording for EnsureCompatiblePipelineServer page
Global pipeline page:
Project Pipeline page:
Experiment page:
Artifact Page:
Execution Page:
1. Change  dspVersion from v2 to v1
2. Check for the wording mentioned in this [mock](https://www.figma.com/proto/etbN0ccCcZR1qKCpJXQNAg/Pipeline-phase-2?page-id=12031%3A86470&node-id=13079-97404&node-type=frame&viewport=551%2C1546%2C0.1&t=wZMxvecIe0ss3sgC-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=13079%3A97404)
3. Check whether delete pipeline server is not present
Updated the existing cypress test
=> update wording for ensureCompatiblePipelineServer page

frontend/src/app/App.scss, frontend/src/pages/modelServing/screens/global/InferenceServiceStatus.tsx
Closes: [RHOAIENG-10993](https://issues.redhat.com/browse/RHOAIENG-10993)
Fixes popover overflow when the messages is too long. Adds a scrollable option
Tested locally using mock data for the popover. Edit the `bodyContent` to include more text, and test the scroll bar functionality 
Before:
After: (With scroll option)
=> Fix popover overflow

frontend/src/api/k8s/inferenceServices.ts, frontend/src/concepts/connectionTypes/ConnectionDetailsHelperText.tsx, frontend/src/concepts/connectionTypes/utils.ts, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ConnectionSection.spec.tsx, frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx, frontend/src/pages/modelServing/screens/projects/utils.ts, frontend/src/pages/modelServing/screens/types.ts
https://issues.redhat.com/browse/RHOAIENG-13662
[figma](https://www.figma.com/proto/97akqulXiGIGtvxkdPLjMm/Data-connections-enhancement?node-id=2095-320117&t=oqClZqYkjDh3Yp5q-0&scaling=scale-down&content-scaling=fixed&page-id=1135%3A199632&starting-point-node-id=2095%3A320117)
Add URI model deployments using connection types.
1. Either go to the "Models" details section of a project or open a project via the "Model Serving" on the left nav bar
2. Select single-model serving or multi-model serving (if not set already). Both should be tested.
3. Have a "s3" and a "URI" connection type created
4. Create a new deployment
Example config:
OpenVINO Model Server / onnx - 1
if single serving use URI - https://github.com/emilys314/odh-uri-model/raw/refs/heads/main/fraud.zip
if multi use URI - …
=> Add URI connection support for model serving

frontend/src/components/SimpleSelect.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceFrameworkSection.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceServingRuntimeSection.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/useModelFramework.ts, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeTemplateSection.tsx, frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
JIRA: Follow-up of [RHOAIENG-10833](https://issues.redhat.com/browse/RHOAIENG-10833)
Fix issues as discussed in https://redhat-internal.slack.com/archives/C05SMJ09DD2/p1730402472208489
Make sure the serving runtime/model framework selections are working well on both KServe/ModelMesh modals when deploying/editing a model.
N/A
=> Follow-up fixes in Model Deployment modals for Select component

frontend/src/pages/projects/notebook/StopNotebookConfirmModal.tsx, frontend/src/pages/projects/screens/projects/LaunchJupyterButton.tsx, frontend/src/pages/projects/screens/projects/tableData.tsx
JIRA: https://issues.redhat.com/browse/RHOAIENG-15150
Updated the wording as described in the [doc](https://docs.google.com/document/d/1BvHzGlFomuR9sUo7hMgdfC5ypkxBpEDpRTxcNk_tYG8).
Compare the UI with the doc, and make sure all the changes are made.
N/A, update wording.
=> Microcopy updates for project list view

frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingNim.cy.ts, frontend/src/api/k8s/pvcs.ts, frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTableRow.tsx, frontend/src/pages/modelServing/screens/global/ServeModelButton.tsx, frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTable.tsx, frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx, frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx, frontend/src/pages/modelServing/screens/projects/NIMServiceModal/NIMModelListSection.tsx, frontend/src/pages/modelServing/screens/projects/NIMServiceModal/useNIMPVC.ts, frontend/src/pages/modelServing/screens/projects/utils.ts, frontend/src/pages/projects/screens/detail/overview/serverModels/AddModelFooter.tsx
https://issues.redhat.com/browse/NVPE-16
https://issues.redhat.com/browse/NVPE-20
Adding 'Edit' capability to the NIM model. Unit test was added and well as cypress test for 'Edit' button was modified.
Tested the following scenarios for editing: 
- Modify Model deployment name
- PVC Size
- Replicas count
- Model size
- Number of accelerators
=> feat: adding 'Edit' capability

frontend/src/concepts/pipelines/EnsureCompatiblePipelineServer.tsx
https://issues.redhat.com/browse/RHOAIENG-15510
update pipelines ensure compatibility screen docs link to a non versioned link: https://docs.redhat.com/en/documentation/red_hat_openshift_ai_self-managed/2-latest/html/release_notes/support-removals_relnotes
make sure the link changed goes to a place
nada
=> update docs link

frontend/src/__mocks__/mockInferenceServiceK8sResource.ts, frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts, frontend/src/pages/modelServing/screens/projects/kServeModal/EnvironmentVariablesSection.tsx, frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx, frontend/src/pages/modelServing/screens/projects/kServeModal/ServingRuntimeArgsSection.tsx
Closes: [RHOAIENG-14700](https://issues.redhat.com/browse/RHOAIENG-14700) and [RHOAIENG-14701](https://issues.redhat.com/browse/RHOAIENG-14701)
Adds Cypress tests for [RHOAIENG-14700](https://issues.redhat.com/browse/RHOAIENG-14700) and [RHOAIENG-14701](https://issues.redhat.com/browse/RHOAIENG-14701)
Run `servingRuntimeList.cy.ts` and make sure that all tests run successfully.
Adds Cypress tests for create,edit and submit serving runtime configuration parameters for Kserve modal
=> Serving runtime params cypress tests

backend/src/routes/api/integrations/nim/index.ts, manifests/core-bases/base/cluster-role.yaml
Grants the Dashboard Service Account permission over the new NIM resource.
=> Fix the NIM Tile issue on prod

backend/src/routes/api/integrations/nim/index.ts, manifests/core-bases/base/cluster-role.yaml
Paralleling this with https://github.com/opendatahub-io/odh-dashboard/pull/3485 because it's a Friday and the CI takes 45mins a pop.
/cc @Gkrumbach07
=> Another nim fix

frontend/src/components/SimpleSelect.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/InferenceServiceFrameworkSection.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx, frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx
Cherry-pick https://github.com/opendatahub-io/odh-dashboard/pull/3488/commits/b6dacc7edc191a0f41fd2cadfa6a0370868479a3 to fix a blocker in RHOAI 2.16
=> [v2.29.0-fixes] Make SimpleSelect one-option hook triggered on key instead of the options

frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx, frontend/src/pages/projects/screens/detail/overview/serverModels/PlatformSelectSection.tsx
https://issues.redhat.com/browse/RHOAIENG-15594
In the Overview and Models tabs of the Project Details page, when a model serving platform is not selected yet, there is a blue info message reading that is now changed to : "You can change the model serving type before the first model is deployed from this project. After deployment, switching types requires deleting all models and servers."
In the Overview and Models tabs of the Project Details page, look that the text is now matching what is requested 
No test impact
=> Clarify microcopy of info message about changing serving platforms in a project

manifests/rhoai/shared/apps/elastic/elastic-app.yaml
Closes: [RHOAIENG-14172](https://issues.redhat.com/browse/RHOAIENG-14172)
Quick fix to add a title header to the elasticsearch app
After installing elasticsearch, use the Openshift YAML editor and copy/paste the changes from this PR to see the updated header.
No changes needed
Before: 
After:
=> Quick fix to add header to elasticsearch app

manifests/rhoai/shared/apps/anaconda-ce/anaconda-ce-docs.yaml
https://issues.redhat.com/browse/RHOAIENG-10874
Before:
<details>
<summary>Scikit-learn</summary>
</details>
<details>
<summary>Anaconda for Data Science</summary>
</details>
After:
<details>
<summary>Scikit-learn</summary>
</details>
<details>
<summary>Anaconda for data science</summary>
</details>
1. In Openshift Console, open YAML editor, select opendatahub as project, and copy/paste https://github.com/opendatahub-io/odh-dashboard/blob/0ba281c70ee6dbb02b55a420db82691e37485221/manifests/rhoai/shared/apps/anaconda-ce/anaconda-ce-app.yaml
2. In Openshift Console, open YAML editor, select opendatahub as project, and copy/paste the updated [anaconda-ce-docs.yaml](https://github.com/opendatahub-io/odh-dashboard/compare/main...jenny-s51:odh-dashboard:[RHOAIENG-10874](https://issues.redhat.com/ …
=> Update Jupyter / Anaconda resource links

backend/package-lock.json
[RHOAIENG-17793](https://issues.redhat.com/browse/RHOAIENG-17793)
* CVE-2024-21538 odh-dashboard-container: regular expression denial of service [main]
`npm audit` in backend folder and check for cross-spawn package vulnerability to not exist.
None
=> Backend Vulnerabilities fixed

frontend/.env, manifests/odh/params.env
=> Upversion Dashboard

frontend/src/__tests__/OWNERS
We need to have approval ownership for the Cypress frontend tests
N/A
A new OWNERS file under frontend/src/__tests__/
=> Add Cypress test folder owners

frontend/src/components/SimpleSelect.tsx, frontend/src/pages/modelServing/screens/metrics/bias/BiasConfigurationPage/BiasConfigurationEmptyState.tsx, frontend/src/pages/modelServing/screens/metrics/bias/BiasConfigurationPage/BiasConfigurationModal/MetricTypeField.tsx, frontend/src/pages/modelServing/screens/metrics/bias/BiasTab.tsx, frontend/src/pages/modelServing/screens/metrics/const.ts
Closes : [RHOAIENG-15396](https://issues.redhat.com/browse/RHOAIENG-15396) and [RHOAIENG-15456](https://issues.redhat.com/browse/RHOAIENG-15456)
Use this cluster to test https://console-openshift-console.apps.ods-qe-psi-07.osp.rh-ods.com/dashboards
1. Go to Data science projects
2. Choose comalley-test
3. Open the deployed model
4. Go to the Model Bias Tab and verify the below. 
1. When No metrics are set up we don't see the metrics dropdown on the left. The text for configuration is updated with the design, and the Icon is changed from wrench(per discussion with Vince)
2. When Opening the configuration Tab the Metrics type dropdown has a normal width, and when selecting a value, the full name is displayed once the dropdown is closed, Instead of only the value inside the parentheses 
3. …
=> TrustyAI issues 

backend/src/routes/api/integrations/nim/index.ts, backend/src/routes/api/integrations/nim/nimUtils.ts, frontend/src/components/OdhAppCard.tsx, frontend/src/services/integrationAppService.ts
https://issues.redhat.com/browse/NVPE-97
Removing the NIM tile from Enabled page by removing the Account CR. 
- Tested by entering an incorrect API key, which disabled the tile on the Enabled Page.
- Clicked to remove the tile from the page and verified that the Account CR was deleted.
- Confirmed that no tile was displayed on the Enabled Page afterward.
=> feat: remove the NIM tile from Enabled page

frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingNim.cy.ts, frontend/src/pages/modelServing/screens/global/InferenceServiceProject.tsx, frontend/src/pages/modelServing/screens/projects/ModelServingPlatform.tsx, frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelsCard.tsx, frontend/src/pages/projects/screens/detail/overview/serverModels/deployedModels/DeployedModelsSection.tsx
https://issues.redhat.com/browse/NVPE-120
Changed the "Single-model serving enabled" to "NVIDIA NIM serving enabled" when NIM project is selected on Models Tab, Deployed Card and Deployed Section.
Tested all the 3 places to ensure the correct label is displayed for the corresponding project.
=> fix: label update for nim project from single serving to NVIDIA NIM Serving Enabled

backend/package-lock.json
[RHOAIENG-18494](https://issues.redhat.com/browse/RHOAIENG-18494)
Upgrade `undici` package to resolve CVE
cd backend
npm audit 
In the vulnerability list, `undici` package should not exist.
=> CVE-2025-22150 odh-dashboard-container: Undici Uses Insufficiently Random Values [main]

backend/package-lock.json, backend/package.json
[RHOAIENG-18914](https://issues.redhat.com/browse/RHOAIENG-18914)
jsonpath-plus version upgrade to `10.0.1` 
Will resolve CVE-2024-21534 https://bugzilla.redhat.com/show_bug.cgi?id=2317968
https://app.snyk.io/org/red-hat-openshift-data-science-rhods/project/3173893f-2c45-4a3e-8de3-3b82e3b6ed9c#issue-SNYK-JS-JSONPATHPLUS-7945884
cd backend 
npm audit
jsonpath-plus package should not be in vulnerability list.
=> Synk - jsonpath-plus package version override to solve vulnerability

frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts, frontend/src/concepts/connectionTypes/utils.ts, frontend/src/pages/modelServing/screens/projects/kServeModal/EnvironmentVariablesSection.tsx, frontend/src/pages/modelServing/screens/projects/kServeModal/ManageKServeModal.tsx, frontend/src/pages/modelServing/screens/types.ts
Closes [RHOAIENG-15501](https://issues.redhat.com/browse/RHOAIENG-15501)
Added a live field validation for the Additional environment variables in deploy model form. 
Use a cluster that has Model Serving enabled for example [psi-08](https://issues.redhat.com//browse/psi-08)
When deploying a Model in model serving, there is a field for additional environment variables, that now go through validation based on this [design](https://www.figma.com/proto/ahospciKiNxVeqOUZcMPlb/Dynamic-Parameters-for-Serving-Runtime?page-id=2239%3A3105&node-id=2722-1353&node-type=frame&viewport=1229%2C270%2C0.15&t=csWbXFe1uZpyzwmT-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=2722%3A1353) 
Added tests to cover the validation functionality
If you …
=> No input validation on "Additional environment variables" in deploy model form

.github/workflows/create-tag-release.yml
=> [GitHub action] Add tag to Quay image URL and fix link

frontend/.env
=> Dashboard upversion release

frontend/src/pages/modelServing/screens/projects/ProjectModelMetricsPage.tsx
JIRA - https://issues.redhat.com/browse/NVPE-133
This PR addresses a **navigation issue bug** where users are unable to return to the models list after clicking on a specific model to view its metrics. 
The change adds a direct back link to the models list from the model’s metrics page, improving the navigation flow and overall user experience.
**Before fixing the bug-**
This screenshot demonstrates the issue where, on the model metrics page, there is no option to return directly to the models list.
when clicking on the project name, it leads to the Overview page but does not provide access back to the Models page.
**After fixing the bug-**
This screenshot illustrates the fix: after selecting a specific model and being on the metrics page, a breadcrumb link to the model's list is now …
=> Fix navigation bug: Add direct back link to models list from model metrics page

frontend/src/__mocks__/mockCatalogModel.ts, frontend/src/__mocks__/mockModelCatalogSource.ts, frontend/src/app/App.tsx, frontend/src/concepts/modelCatalog/context/ModelCatalogContext.tsx, frontend/src/concepts/modelCatalog/mockData/catalogModelMock.ts, frontend/src/concepts/modelCatalog/mockData/modelCatalogSourceMock.ts, frontend/src/concepts/modelCatalog/types.ts, frontend/src/pages/modelCatalog/ModelCatalogCoreLoader.tsx
Closes:  [RHOAIENG-18954](https://issues.redhat.com/browse/RHOAIENG-18954)
This PR aims to add types, mock data and context provider for model catalog
NA
=> Add types, mock data and context provider for model catalog

frontend/src/pages/modelCatalog/ModelCatalogCoreLoader.tsx, frontend/src/pages/modelCatalog/ModelCatalogRoutes.tsx, frontend/src/pages/modelCatalog/screens/ModelCatalog.tsx
Follow up #3712 
This PR aims to update child routing for model catalog.
https://github.com/user-attachments/assets/e54a11f4-ca75-49e6-b917-7f54853193ed
Check that the details page is rendered when we navigate to `/tempDetails`.  
tests are already added as part of #3712
=> Update Model catalog route

frontend/src/utilities/useEnableApplication.tsx
https://issues.redhat.com/browse/NVPE-145
Changed to show backend error message for API key validation instead of hardcoded message on the Explore and Enable pages.
Tested locally by entering an incorrect API key and verifying that the error message is returned from the backend.
Tested locally by entering an incorrect API key.
=> fix: show backend error message for API key validation

backend/src/utils/constants.ts, docs/dashboard-config.md, frontend/src/__mocks__/mockDashboardConfig.ts, frontend/src/__mocks__/mockNimResource.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/projects/modelServingNim.cy.ts, frontend/src/components/OdhAppCard.tsx, frontend/src/concepts/areas/const.ts, frontend/src/pages/modelServing/screens/projects/NIMServiceModal/ManageNIMServingModal.tsx, frontend/src/pages/modelServing/screens/projects/ProjectModelMetricsPage.tsx, frontend/src/utilities/useEnableApplication.tsx, manifests/rhoai/shared/odhdashboardconfig/odhdashboardconfig.yaml
https://github.com/opendatahub-io/odh-dashboard/pull/3747
https://github.com/opendatahub-io/odh-dashboard/pull/3748
https://github.com/opendatahub-io/odh-dashboard/pull/3727
https://github.com/opendatahub-io/odh-dashboard/pull/3720
https://github.com/opendatahub-io/odh-dashboard/pull/3717
=> V2.31.0 fixes more nim stuff

frontend/src/__tests__/cypress/cypress/pages/modelCatalog.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalog.cy.ts, frontend/src/pages/modelCatalog/__tests__/utils.spec.ts, frontend/src/pages/modelCatalog/components/ModelCatalogCard.tsx, frontend/src/pages/modelCatalog/routeUtils.ts, frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx, frontend/src/pages/modelCatalog/utils.ts
closes: https://issues.redhat.com/browse/RHOAIENG-18958
the model name (in model catalog cards) will now link to the model details page for that model
tested locally on green cluster
added a test and unit test
=> feat(ModelCatalog): link to details page

frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts, frontend/src/pages/modelServing/screens/projects/KServeSection/KServeInferenceServiceTableRow.tsx
https://issues.redhat.com/browse/RHOAIENG-20122
If authorino is disabled on your cluster, you can't see the token auth for a raw deployment.
Before:
After:
1. have a cluster without authorino
2. Deploy a model with raw and enable authorization
3. It should show in the table row the auth token or that auth isn't enabled for the token
4. Also make sure serverless deployments still behave correctly
=> Check if deployment is raw for showing token

frontend/src/__tests__/cypress/cypress/tests/mocked/projects/connections.cy.ts, frontend/src/concepts/connectionTypes/__tests__/utils.spec.ts, frontend/src/concepts/connectionTypes/utils.ts, manifests/common/connection-types/oci-v1.yaml
https://issues.redhat.com/browse/RHOAIENG-18659
Adds the ootb yaml file and marks it model serving compatible for the admin pages. 
1. run `oc project opendatahub`
2. run `oc apply -f manifests/common/connection-types/oci-v1.yaml`
3. Also you need to manually add the label `platform.opendatahub.io/part-of: dashboard` to show up as "Pre-installed"
- make sure "OCI compliant registry - v1" shows up in the admin connectionTypes page
- Go to a project and try creating a connection from the type
Test updated to mimic the ootb one, and testing for the "Model serving compatible" tag to appear
Other than that, i don't believe there is a good way in the mocks to actually test the yaml is applied properly
@simrandhaliw 
After the PR …
=> Add oci-v1.yaml ootb connection type

frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/validationUtils.ts, frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx, frontend/src/pages/pipelines/global/modelCustomization/ModelCustomizationForm.tsx, frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/BaseModelSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/InlineEditText.tsx, frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/__tests__/InlineEditText.spec.tsx, frontend/src/pages/pipelines/global/modelCustomization/const.ts
See https://issues.redhat.com/browse/RHOAIENG-20117
Note: All values are hardcoded except `inputStorageLocationUri`, which is read from query arg `baseModelInputStorageLocationUri`. Let me know if this is ok for now.
https://github.com/user-attachments/assets/910eb23d-1904-40e5-846f-91eee141b6fa
See the video above.
Added unit tests for the new component.
=> Add base model section to ilab form

frontend/src/__tests__/cypress/cypress/pages/home/home.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/home/home.cy.ts, frontend/src/pages/home/HomeHint.tsx
https://issues.redhat.com/browse/RHOAIENG-17842
Add a hardware profile banner 
Remove the jupyter notebook banner
- Check if the banner is visible in the home page when hardwareprofile is enabled
- check if the banner is visible for both admin and non user
- when the banner is closed, check if its not displayed again even after loading
=> Hardware profile introduction alert banner

frontend/src/components/SimpleSelect.tsx
Closes: [RHOAIENG-18592](https://issues.redhat.com/browse/RHOAIENG-18592)
Adds missing key for SimpleSelect for model registry dropdown 
This change is already [addressed upstream](https://github.com/kubeflow/model-registry/pull/729), I'm porting it downstream.
Make sure model registry dropdown loads fine.
You should not see the below error in the console when you load the model registry page.
Not a UI change, just fixing some errors in the console.
=> feat(MR): Add missing key for SimpleSelect

frontend/src/__tests__/cypress/cypress/pages/distributedWorkloads.ts, frontend/src/__tests__/cypress/cypress/pages/modelCatalog.ts, frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts, frontend/src/__tests__/cypress/cypress/pages/modelRegistrySettings.ts, frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/__tests__/cypress/cypress/pages/projects.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalog.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelRegistry.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomization.cy.ts, frontend/src/concepts/distributedWorkloads/DistributedWorkloadsContext.tsx, frontend/src/pages/distributedWorkloads/global/DistributedWorkloadsNoProjects.tsx, frontend/src/pages/distributedWorkloads/global/GlobalDistributedWorkloads.tsx, frontend/src/pages/distributedWorkloads/global/GlobalDistributedWorkloadsTabs.tsx, frontend/src/pages/modelCatalog/screens/ModelCatalog.tsx, frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx, frontend/src/pages/modelRegistry/ModelRegistryCoreLoader.tsx, frontend/src/pages/modelRegistry/screens/ModelRegistry.tsx, frontend/src/pages/modelRegistrySettings/ModelRegistrySettings.tsx, frontend/src/pages/modelServing/screens/global/GlobalModelServingCoreLoader.tsx, frontend/src/pages/modelServing/screens/global/ModelServingGlobal.tsx, frontend/src/pages/pipelines/global/experiments/const.ts, frontend/src/pages/projects/screens/projects/ProjectView.tsx, frontend/src/utilities/NavData.tsx
Closes [RHOAIENG-19611](https://issues.redhat.com/browse/RHOAIENG-19611)
Updated the Nav bar, changed the names of Model Serving to -> Model deployments. After discussion with UX, the decision was to change only on the page itself but not at any helper texts/popovers etc'. This will probably done in the future. Also changed Distributed Workload Metrics--> Distributed workloads. This was changed everywhere in the code as it only had 8 placed to change. 
This was tested on the green cluster. In order to see Model Customization please use disableFineTuning in the dev flags
Updated all the tests that were failing due to name changes and nesting of the Nav pages
=> Reorganize main nav to create Models section and update page titles

frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testMultiModelAdminCreation.cy.ts
https://issues.redhat.com/browse/RHOAIENG-20591
- Quarantine test due to https://issues.redhat.com/browse/RHOAIENG-20591
- N/A
- None
=> Quarantine multiModelAdminCreation Test

frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts, frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/__tests__/validationUtils.spec.ts, frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/types.ts, frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/validationUtils.ts, frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx, frontend/src/pages/pipelines/global/modelCustomization/FineTunePageFooter.tsx, frontend/src/pages/pipelines/global/modelCustomization/FineTuneTaxonomySection.tsx, frontend/src/pages/pipelines/global/modelCustomization/ModelCustomizationForm.tsx, frontend/src/pages/pipelines/global/modelCustomization/const.ts, frontend/src/pages/pipelines/global/modelCustomization/utils.ts
https://issues.redhat.com/browse/RHOAIENG-19173
Added taxonomy section
Test whether the submit button is disabled/enabled between sshkey type and username and token type 
Test whether submitting it will create secrets
added unit test and cypress test
=> Fine tune taxonomy

backend/package-lock.json, backend/package.json
[RHOAIENG-20372](https://issues.redhat.com/browse/RHOAIENG-20372)
Package upgraded to 10.3.0 to fix CVE reported by snyk.
Check the npm audit in the backend, this vulnerabilities should be listed.
=> SNYK CVE jsonpathplus fix

frontend/src/__mocks__/mockDscStatus.ts, frontend/src/__tests__/cypress/cypress/pages/aboutDialog.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/application.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/clusterSettings/clusterSettings.cy.ts, frontend/src/app/AboutDialog.tsx, frontend/src/app/App.scss, frontend/src/app/__tests__/AboutDialog.spec.tsx, frontend/src/concepts/areas/const.ts, frontend/src/concepts/areas/types.ts, frontend/src/k8sTypes.ts
https://issues.redhat.com/browse/RHOAIENG-13920
This PR updates the Dashboard UI to display the available component versions for each RHOAI release in the "About" modal. Previously, users had to manually check component repositories or ask owners for version details. This update automates the process by fetching component version data from the DSC (Data Science Cluster) status and displaying it in the modal.
Changes
- Fetch component version data from the DSC status.
- Updated the Dashboard UI to read and display this information in the "About" modal.
- Deployed the ODH operator (from the main branch) in the cluster to make component release data available.
- Verified that the "About" modal in the Dashboard UI correctly displays the component version information. …
=> Map component versions to RHOAI releases

frontend/src/pages/modelRegistry/screens/ModelPropertiesTableRow.tsx, frontend/src/pages/modelRegistry/screens/__tests__/utils.spec.ts, frontend/src/pages/modelRegistry/screens/utils.ts
Closes: [RHOAIENG-20080](https://issues.redhat.com/browse/RHOAIENG-20080)
In Model version details page and Model details page, external URls will be seen as below and if clicked, wil l lead to the external anchor link. Long links are truncated.
On the details pages for both a registered model and a registered version, create some properties in the Properties table and check the behavior of different kinds of values:
- Valid http:// and https:// URLs: verify that these render as clickable links with an external icon and clicking the link works.
- Also try a very long URL and make sure it truncates properly and doesn't break the page layout. Make sure you are able to see the full URL in the tooltip before clicking.
- URLs of another protocol like s3:// or [ftp://:](ftp:///) verify that …
=> Render URLs as external links in MR customProperties

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts, frontend/src/concepts/pipelines/content/modelCustomizationForm/useIlabPipeline.ts
See https://issues.redhat.com/browse/RHOAIENG-20647 and https://github.com/opendatahub-io/odh-dashboard/pull/3809#issuecomment-2690502153
https://github.com/user-attachments/assets/08a26055-749c-47f3-957e-54269e2eedc2
Add the `StartRunModal` component somewhere in the code and select the projects.
```ts
import StartRunModal from '~/pages/pipelines/global/modelCustomization/startRunModal/StartRunModal';
...
<StartRunModal onSubmit={(selectedProject) => {}} onCancel={() => {}} />
...
```
Fixes to the affected tests have been included in this PR.
=> Fix flashing error message during iLab Pipeline project selection

frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts, frontend/src/concepts/hardwareProfiles/HardwareProfileCustomize.tsx, frontend/src/concepts/hardwareProfiles/HardwareProfileFormSection.tsx, frontend/src/concepts/hardwareProfiles/HardwareProfileSelect.tsx, frontend/src/concepts/hardwareProfiles/validationUtils.ts, frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/validationUtils.ts, frontend/src/pages/notebookController/screens/server/AcceleratorProfileSelectField.tsx, frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx, frontend/src/pages/pipelines/global/modelCustomization/FineTunePageFooter.tsx, frontend/src/pages/pipelines/global/modelCustomization/FineTuneTaxonomySection.tsx, frontend/src/pages/pipelines/global/modelCustomization/ModelCustomizationForm.tsx, frontend/src/pages/pipelines/global/modelCustomization/const.ts, frontend/src/pages/pipelines/global/modelCustomization/teacherJudgeSection/TeacherJudgeInputComponents.tsx, frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/ContainerCustomSize.tsx, frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingAcceleratorFormSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingHardwareProfileFormSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingHardwareSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/type.ts, frontend/src/pages/pipelines/global/modelCustomization/useIlabPodSpecOptionsState.ts, frontend/src/pages/pipelines/global/modelCustomization/utils.ts, frontend/src/pages/projects/screens/spawner/storage/CreateNewStorageSection.tsx, frontend/src/pages/projects/screens/spawner/storage/StorageClassSelect.tsx, frontend/src/utilities/useAcceleratorProfileFormState.ts
https://issues.redhat.com/browse/RHOAIENG-19109
added hardware section to ilab page
=> add ilab hardware sections

frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/servingRuntimeList.cy.ts, frontend/src/pages/modelServing/screens/global/data.ts
Closes: [RHOAIENG-20227](https://issues.redhat.com/browse/RHOAIENG-20227)
Changed "Model name" -> "Model deployment name"
1. Go to a project with model deployments and check the Models tab. The table header is "Model deployment name"
2. Go to Model Serving Global page. The table header should be changed.
3. Go to Model registry and to a version that is deployed or deploy a model from a registered model version. Go to Deployments tab of a version that is deployed. You should see the changed header.
Fixed related Cypress tests
=> Change Model deployments column header

frontend/src/concepts/analyticsTracking/segmentIOUtils.tsx, frontend/src/concepts/pipelines/content/ArchiveModal.tsx, frontend/src/concepts/pipelines/content/DeletePipelineServerModal.tsx, frontend/src/concepts/pipelines/content/DeletePipelinesModal.tsx, frontend/src/concepts/pipelines/content/PipelineServerActions.tsx, frontend/src/concepts/pipelines/content/RestoreModal.tsx, frontend/src/concepts/pipelines/content/configurePipelinesServer/ConfigurePipelinesServerModal.tsx, frontend/src/concepts/pipelines/content/createRun/RunPageFooter.tsx, frontend/src/concepts/pipelines/content/experiment/CreateExperimentModal.tsx, frontend/src/concepts/pipelines/content/import/PipelineImportModal.tsx, frontend/src/concepts/pipelines/content/import/PipelineVersionImportModal.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRecurringRun/PipelineRecurringRunDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRecurringRun/PipelineRecurringRunTable.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTable.tsx, frontend/src/pages/modelRegistry/screens/RegisterModel/RegisterModel.tsx, frontend/src/pages/modelRegistry/screens/components/ArchiveModelVersionModal.tsx, frontend/src/pages/modelRegistry/screens/components/ArchiveRegisteredModelModal.tsx, frontend/src/pages/modelRegistry/screens/components/RestoreModelVersionModal.tsx, frontend/src/pages/modelRegistry/screens/components/RestoreRegisteredModel.tsx, frontend/src/pages/modelRegistrySettings/CreateModal.tsx, frontend/src/pages/modelRegistrySettings/DeleteModelRegistryModal.tsx, frontend/src/pages/modelServing/screens/global/InferenceServiceTable.tsx, frontend/src/pages/pipelines/global/experiments/ArchiveExperimentModal.tsx, frontend/src/pages/pipelines/global/experiments/DeleteExperimentModal.tsx, frontend/src/pages/pipelines/global/experiments/RestoreExperimentModal.tsx, frontend/src/pages/pipelines/global/runs/ArchiveRunModal.tsx, frontend/src/pages/pipelines/global/runs/RestoreRunModal.tsx
https://issues.redhat.com/browse/RHOAIENG-20641
This PR adds more analytics tracking  in the areas of Pipelines and Model registry.
Manual click-through
Automated tests are not needed, as missing analytics does not impact the UI appearance or flow.
=> RHOAIENG-20641 Add more Analytics for Registry and Pipelines

frontend/package-lock.json, frontend/package.json, frontend/src/utilities/markdown.ts
[RHOAIENG-19948](https://issues.redhat.com/browse/RHOAIENG-19948)
=> [Backport] 2.16.2 CVE dompurify

frontend/src/__mocks__/mockNotebookK8sResource.ts, frontend/src/__tests__/cypress/cypress/pages/notebookServer.ts, frontend/src/__tests__/cypress/cypress/support/commands/odh.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/applications/notebookServer.cy.ts, frontend/src/pages/notebookController/screens/server/EnvironmentVariablesField.tsx, frontend/src/pages/notebookController/screens/server/EnvironmentVariablesRow.tsx
[RHOAIENG-18214](https://issues.redhat.com/browse/RHOAIENG-18214)
Backport of PR #3610 
Differential changes are due to merge conflicts
=> [Backport] Fix Jupyter Tile env var readback

frontend/src/__mocks__/mockPipelineVersionsProxy.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts, frontend/src/__tests__/cypress/cypress/types.ts, frontend/src/components/ParamsDefaultFields.tsx, frontend/src/concepts/pipelines/content/createRun/contentSections/ParamsSection/ParamsSection.tsx, frontend/src/concepts/pipelines/content/modelCustomizationForm/hyperparameterFields/HyperparameterEvaluationField.tsx, frontend/src/concepts/pipelines/content/modelCustomizationForm/hyperparameterFields/HyperparameterLongNumberField.tsx, frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/__tests__/validationUtils.spec.ts, frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/hyperparameterValidationUtils.ts, frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/types.ts, frontend/src/concepts/pipelines/content/modelCustomizationForm/modelCustomizationFormSchema/validationUtils.ts, frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx, frontend/src/pages/pipelines/global/modelCustomization/FineTunePageFooter.tsx, frontend/src/pages/pipelines/global/modelCustomization/HyperparameterSection/HyperparameterFields.tsx, frontend/src/pages/pipelines/global/modelCustomization/HyperparameterSection/HyperparameterFieldsUtils.tsx, frontend/src/pages/pipelines/global/modelCustomization/HyperparameterSection/HyperparameterPageSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/ModelCustomizationForm.tsx, frontend/src/pages/pipelines/global/modelCustomization/RunTypeSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/const.ts, frontend/src/pages/pipelines/global/modelCustomization/utils.ts
https://issues.redhat.com/browse/RHOAIENG-19022
Added run type and hyperparameter fields
Visually. Some testing in cypress and unit test files
Some testing in cypress and unit test files
=> add ilab basic params

frontend/src/concepts/areas/const.ts
Closes: [RHOAIENG-21244](https://issues.redhat.com/browse/RHOAIENG-21244)
When both pipelines and model registry feature flags are turned OFF("Model catalog" is absent coz it is reliant on "Model registry")
When both model registry and pipelines feature flags are turned ON
When model registry is turned OFF but pipelines feature flag is ON
Try editing the feature flags as stated in the Description
N/A only reliant area changes
=> Update reliantAreas of Fine tuning feature

frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunTabDetails.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/SelectedNodeDetailsTab.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/useFetchRunArtifact.tsx, frontend/src/concepts/pipelines/content/tables/pipelineRun/PipelineRunTableRow.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/ArtifactDetails.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/ArtifactOverviewDetails.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactsTableRow.tsx
[RHOAIENG-21246](https://issues.redhat.com/browse/RHOAIENG-21246)
Model registry feature flag is checked wherever we have label "Model registered" which was introduced in #3842 
Enable/Disable model registry feature flag and check for "Model registered" / "Registered" label in Pipeline runs list/details and Artifacts list/details 
None
=> Add feature flag for registered model links in Pipelines UI

frontend/src/__mocks__/mockConnectionType.ts, frontend/src/concepts/connectionTypes/ConnectionTypeForm.tsx, frontend/src/concepts/connectionTypes/fields/ConnectionTypeFormFields.tsx, frontend/src/concepts/connectionTypes/fields/DropdownFormField.tsx, frontend/src/concepts/connectionTypes/fields/FileFormField.tsx, frontend/src/concepts/connectionTypes/fields/NumericFormField.tsx, frontend/src/concepts/connectionTypes/fields/UriFormField.tsx, frontend/src/concepts/connectionTypes/fields/types.d.ts, frontend/src/pages/connectionTypes/manage/DataFieldPropertiesForm.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/__tests__/ConnectionSection.spec.tsx, frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelNewConnectionContext.tsx, frontend/src/pages/projects/screens/detail/connections/ManageConnectionsModal.tsx, frontend/src/pages/projects/screens/detail/connections/usePersistentData.ts
Closes https://issues.redhat.com/browse/RHOAIENG-20982
This changes a lot of the connection form validation from valid to error state. I then made it a `boolean | string` for allowing messages. Then in the validation callback being passed to the form, i added a custom one that can be added by the parent of the connection form. 
File padding alignment fix
Create an oci connection and select only the push type, it should error
test added
@simrandhaliw 
=> Show error if only Push access

manifests/rhoai/shared/apps/model-catalog/model-catalog-configmap.yaml
Updates model catalog sources in ConfigMap
=> Updates model catalog sources in ConfigMap

frontend/src/concepts/hardwareProfiles/HardwareProfileCustomize.tsx, frontend/src/pages/hardwareProfiles/manage/HardwareProfileVisibilitySection.tsx, frontend/src/pages/modelServing/screens/global/EmptyModelServing.tsx, frontend/src/pages/projects/screens/detail/ProjectDetails.tsx, frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx
1. Closes [RHOAIENG-21376](https://issues.redhat.com/browse/RHOAIENG-21376)
2. Closes [RHOAIENG-12842](https://issues.redhat.com/browse/RHOAIENG-12842)
3. [Hardware Profiles Content Review Doc](https://docs.google.com/document/d/1NGI5fIlVfpNf9nidTA0NdkPtr9-5Yiyp5fuCXjiI8V8/edit?tab=t.0)
1. Added rewording changes for the hardware profile requests and limits
**Textual rewording for  requests and limits in the hardware profile customize section** 
2. Hardware Profile Description on the settings page updated
**Hardware Profile settings page description** 
4. Truncate fixes
**Breadcrumb truncate on the data science pipeline page** 
**Truncation of redirection text for the link to the data science pipeline section** 
1. When you create a new workbench from the Data Science Pipeline page under …
=> (feat RHOAIENG-21376) : Rewording for the hardware profile customization section

frontend/src/__tests__/cypress/cypress/pages/modelCatalog/registerCatalogModel.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelDetailsPage.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersions.cy.ts, frontend/src/concepts/roleBinding/RoleBindingPermissionsTableRow.tsx, frontend/src/pages/modelCatalog/screens/ModelCatalog.tsx, frontend/src/pages/modelCatalog/screens/ModelDetailsPage.tsx, frontend/src/pages/modelCatalog/screens/ModelDetailsView.tsx, frontend/src/pages/modelCatalog/screens/RegisterCatalogModel.tsx, frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsHeaderActions.tsx, frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx, frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionListView.tsx, frontend/src/pages/modelRegistry/screens/ModelVersions/ModelVersionsTableRow.tsx, frontend/src/pages/modelRegistry/screens/RegisterModel/RegisterVersion.tsx, frontend/src/pages/modelRegistry/screens/RegisteredModels/usePrefillDeployModalFromModelRegistry.ts, frontend/src/pages/modelRegistry/screens/RegisteredModels/useProjectErrorForRegisteredModel.ts, frontend/src/pages/modelRegistry/screens/__tests__/useProjectErrorForRegisteredModel.spec.ts, frontend/src/pages/modelRegistrySettings/CreateModal.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ProjectSelector.tsx
Closes: [RHOAIENG-21418](https://issues.redhat.com/browse/RHOAIENG-21418)
Microcopy updates for Model registry/Model catalog 
The remaining microcopy is already covered and/or obsolete.
View database configuration model/kebab action- We removed this some time ago coz I don't see this anymore.
Model catalog main page:
Model catalog details page: InstructLab fine-tune action
Model catalog details page: No registry access tooltip
Model catalog details page: Sidebar of the body
Registration form (from model catalog)
Model registry details page
Model Registry > Model > Versions list - empty state
Model Registry > register new version
Model Registry > model > version > deploy model
Model registry settings > Create model registry modal 
Model Registry > model > version > deploy model(when the …
=> Model catalog/Model registry microcopy

frontend/src/__mocks__/mockModelCatalogConfigMap.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalog.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelDetailsPage.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/registerCatalogModel.cy.ts, frontend/src/concepts/modelCatalog/const.ts, frontend/src/concepts/modelCatalog/types.ts, frontend/src/concepts/modelCatalog/useModelCatalogSources.ts, manifests/rhoai/shared/apps/model-catalog/model-catalog-configmap.yaml, manifests/rhoai/shared/apps/model-catalog/model-catalog-rbac.yaml
From discussion with @andrewballantyne and @alexcreasy - in anticipation of perhaps being asked to backport future additional model catalog sources, it would be less risky to have our configmap contain an array of sources (currently with one source) so that we can add more sources without changing how we fetch data or how we handle RBAC.
This PR:
* Renames our `model-catalog-source-redhat` configmap to `model-catalog-sources` in the manifest
* Renames the role and rolebinding in the manifest accordingly
* Changes its data property from `modelCatalogSource` to `modelCatalogSources`
* Changes the JSON in that property to have a wrapping object `{ sources: [...] }` and adds a new type `ModelCatalogSourcesObject` for this wrapping object
* Updates the `useModelCatalogSources` hook to use this …
=> Refactor to support multiple model catalog sources in one configmap

frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDetails.ts, frontend/src/pages/pipelines/global/modelCustomization/startRunModal/MissingConditionAlert.tsx, frontend/src/pages/pipelines/global/modelCustomization/startRunModal/StartRunModal.tsx
Closes [RHOAIENG-21255](https://issues.redhat.com/browse/RHOAIENG-21255)
1. Modal States Rewording changes for Content,Alerts.
2. [Modal Content Changes Doc](https://docs.google.com/document/d/1LVNsOJLXipRDJxddIaKYZ3R-fejqjSptiGzZaFzPV-8/edit?tab=t.0)
3. [Figma Link](https://www.figma.com/design/Pk0BnnzSoaplpGU6jcFX8i/End-to-End---Phase-4?node-id=1362-39785)
**Initial State with placeholder** 
**Textual Changes when Server pipeline is not available** 
**Textual Changes when server pipeline is not configured** 
https://github.com/user-attachments/assets/e14f33c8-efd3-4179-8325-0dff4691d8c9
Add the StartRunModal component somewhere in the code and select the projects.
```javascript
import StartRunModal from '~/pages/pipelines/global/modelCustomization/startRunModal/StartRunModal';
... …
```
=> Feat(Rhoaieng 21255) ilab mircocopy ux rewording modal content

frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testSingleModelContributorCreation.cy.ts, frontend/src/__tests__/cypress/cypress/tests/e2e/nim/testEnableNIM.cy.ts
- Quarantine Model Serving test due to new blocking issue https://issues.redhat.com/browse/RHOAIENG-21662
- NIM was quarantined yesterday, however the 'after' method was not respected due to a missing !wasSetupPerformed method
=> Quarantine Model Serving and resolve NIM quarantine issue

frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationLandingPage.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationLandingPage.cy.ts, frontend/src/components/GenericSidebar.tsx, frontend/src/components/MarkdownView.scss, frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx, frontend/src/pages/pipelines/global/modelCustomization/FineTuneTaxonomySection.tsx, frontend/src/pages/pipelines/global/modelCustomization/HyperparameterSection/HyperparameterPageSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/ModelCustomizationForm.tsx, frontend/src/pages/pipelines/global/modelCustomization/RunTypeSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/BaseModelSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/InlineEditText.tsx, frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/PipelineDetailsSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/const.ts, frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/landingPage/ModelCustomization.tsx, frontend/src/pages/pipelines/global/modelCustomization/landingPage/ModelCustomizationDrawerContent.tsx, frontend/src/pages/pipelines/global/modelCustomization/landingPage/PrerequisitesSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/teacherJudgeSection/JudgeModelSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/teacherJudgeSection/TeacherJudgeInputComponents.tsx, frontend/src/pages/pipelines/global/modelCustomization/teacherJudgeSection/TeacherModelSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingHardwareProfileFormSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingHardwareSection.tsx, frontend/src/routes/pipelines/modelCustomizationForm.ts
JIRA: https://issues.redhat.com/browse/RHOAIENG-21254
Figma: https://www.figma.com/design/Pk0BnnzSoaplpGU6jcFX8i/End-to-End---Phase-4?node-id=511-22474
Doc: https://docs.google.com/document/d/1mUVbZ1eUilJK83jXnKqs6eEmCKOSB88qDP1omlAlhgo/edit?tab=t.0
Make sure the content and the design on the fine-tune page match the mockup and the doc
Go to the fine tune form and make sure everything is up to date with the doc and mockup, and all the links are working
N/A
=> Ilab fine tune page microcopy

frontend/package-lock.json
[RHOAIENG-21734](https://issues.redhat.com/browse/RHOAIENG-21734)
Fixed the latest vulnerabilities in frontend reported by [snyk](https://app.snyk.io/org/red-hat-openshift-data-science-rhods/project/1d87351a-04b6-4d75-b13b-9187e9f55bc5)
cd frontend
check `npm audit` - no vulnerabilities should be found
=> Frontend vulnerabilities fixed

backend/package-lock.json
[RHOAIENG-21737](https://issues.redhat.com/browse/RHOAIENG-21737)
Fixed the latest vulnerabilities in frontend reported by [Snyk](https://app.snyk.io/org/red-hat-openshift-data-science-rhods/project/3173893f-2c45-4a3e-8de3-3b82e3b6ed9c) 
Only `@babel/helpers` is fixed, as others don't have any fix.
cd backend
check `npm audit` - `@babel/helpers` should not be in the list
=> Backend Snyk vulnerabilities

frontend/src/__mocks__/mockConnectionType.ts, frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
Closes https://issues.redhat.com/browse/RHOAIENG-21893
Kyle also mentioned we shouldn't have it show up in model mesh. OCI isn't compatible with model mesh / we don't want to support it
Create a connection in a project, try to deploy a model mesh server, it shouldn't show up. Same with the connection type
Updated the modelmesh cypress test to assert the correct connection types are showing
=> Filter out OCI connections for model mesh

frontend/src/__mocks__/mockConnectionType.ts, frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDeploy.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/runtime/servingRuntimeList.cy.ts, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ManageInferenceServiceModal.tsx
* Filter out OCI connections
* Add OCI modelmesh cypress test
Closes 
https://issues.redhat.com/browse/RHOAIENG-21893
Kyle also mentioned we shouldn't have it show up in model mesh. OCI isn't compatible with model mesh / we don't want to support it
Create a connection in a project, try to deploy a model mesh server, it shouldn't show up. Same with the connection type
Updated the modelmesh cypress test to assert the correct connection types are showing
=> Filter out OCI connections for model mesh 2.32 cherry pick

frontend/src/__tests__/cypress/cypress/fixtures/e2e/connectionTypes/testOOTBConnectionType.yaml, frontend/src/__tests__/cypress/cypress/fixtures/e2e/dataScienceProjects/testDeployOCIModel.yaml, frontend/src/__tests__/cypress/cypress/pages/connections.ts, frontend/src/__tests__/cypress/cypress/pages/modelServing.ts, frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testDeployOCIModel.cy.ts, frontend/src/__tests__/cypress/cypress/tests/e2e/settings/connectionTypes/connectionTypes.cy.ts, frontend/src/__tests__/cypress/cypress/types.ts, frontend/src/__tests__/cypress/cypress/utils/dataLoader.ts, frontend/src/__tests__/cypress/cypress/utils/testConfig.ts, frontend/src/__tests__/cypress/test-variables.yml.example
https://issues.redhat.com/browse/RHOAIENG-18663
Added a new test for deploying a model with an OCI connection.
Updated the OOTB Connection Types test to include OCI.
Run this branch locally with `npm run start:dev:ext`
setup testing config
Run `npm run cypress:open` and run the tests in the PR.
Ran on Jenkins
Yes...
Run the tests yourself. I might need to add disabling the OCI feature flag :thinking: or do we instead hold this until OCI is enabled?
=> Add OCI Deployment E2E Test

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/pipelines.cy.ts, frontend/src/concepts/pipelines/content/import/PipelineVersionImportModal.tsx
https://issues.redhat.com/browse/RHOAIENG-21115
The aim of the Ticket is changed a bit
- Check whether the uploading the new pipeline version redirects to the pipeline version detail page
1. Import a pipeline version 
2. Check if after importing the pipeline version it redirects to the pipeline version detail page
Updated the existing cypress test to verify correct redirection using the version from import response
=> Redirect the pipelineversion after import

manifests/common/connection-types/kustomization.yaml
Closes https://issues.redhat.com/browse/RHOAIENG-22043
The OCI ootb yaml isn't being applied in the latest odh dashboard manifests. Without this, OCI will not be enabled / available
run `kustomize build common/connection-types` to check the process
=> Add oci to connection types Kustomization

manifests/common/connection-types/kustomization.yaml
Cherry pick for https://github.com/opendatahub-io/odh-dashboard/pull/3963 (commit sha is from my repo not odh-dashboard)
Closes https://issues.redhat.com/browse/RHOAIENG-22043
The OCI ootb yaml isn't being applied in the latest odh dashboard manifests. Without this, OCI will not be enabled / available
run `kustomize build common/connection-types` to check the process
=> Add oci to connection types Kustomization 2.32.0-fixes cherry pick

frontend/src/__tests__/cypress/cypress/pages/components/MigrationModal.ts, frontend/src/__tests__/cypress/cypress/pages/hardwareProfile.ts, frontend/src/__tests__/cypress/cypress/pages/notebookImageSettings.ts, frontend/src/__tests__/cypress/cypress/pages/notebookServer.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/applications/notebookServer.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/legacyHardwareProfiles.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/notebookImageSettings/notebookImageSettings.cy.ts, frontend/src/pages/BYONImages/BYONImageModal/HardwareProfileIdentifierMultiselect.tsx, frontend/src/pages/hardwareProfiles/HardwareProfiles.tsx, frontend/src/pages/hardwareProfiles/HardwareProfilesTableRow.tsx, frontend/src/pages/hardwareProfiles/manage/ManageHardwareProfileFooter.tsx
See https://issues.redhat.com/browse/RHOAIENG-21522
This PR only adds tests.
This PR only adds tests.
=> Create mocked cypress tests migration cases for hardware profiles

frontend/src/__tests__/cypress/cypress/tests/mocked/applications/notebookServer.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/hardwareProfiles/workbenchHardwareProfiles.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts, frontend/src/concepts/hardwareProfiles/HardwareProfileDetailsPopover.tsx, frontend/src/concepts/hardwareProfiles/HardwareProfileSelect.tsx
See https://issues.redhat.com/browse/RHOAIENG-21959
Using the same formatting strategy of the Hardware Profiles table, which formats CPU and Memory units.
**Before**
**After**
Go to any place where the Hardware Profile Select is present (e.g. create workbench page) and check the resource units.
Adapted existing tests.
=> Cleanup additional references to `Gi` on Hardware Profiles

frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts, frontend/src/concepts/pipelines/content/const.ts, frontend/src/concepts/pipelines/content/import/PipelineFileUpload.tsx, frontend/src/pages/pipelines/global/modelCustomization/FineTuneTaxonomySection.tsx, frontend/src/pages/pipelines/global/modelCustomization/SshKeyFileUpload.tsx
Closes [RHOAIENG-21951](https://issues.redhat.com/browse/RHOAIENG-21951)
https://github.com/user-attachments/assets/36ce3d5b-b5ad-4dd4-8082-4d5a5976c6cf
1. Go to the model customization form from the model registry page. 
1. Added test cases for the file upload for the ssh upload input
=> feat(RHOAIENG-21951):added ssh file upload for taxonomy

frontend/src/__mocks__/mlmd/mockGetArtifacts.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/artifacts.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/modelCustomizationForm.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/pipelineRunTable.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/artifacts.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/modelCustomizationForm.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/runs/pipelineRuns.cy.ts, frontend/src/concepts/pipelines/content/PipelineRunTypeLabel.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunRegisteredModelDetails.tsx, frontend/src/pages/ApplicationsPage.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactsTableRow.tsx, frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx, frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/BaseModelSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/InlineEditText.tsx, frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/PipelineDetailsSection.tsx
[RHOAIENG-22105](https://issues.redhat.com/browse/RHOAIENG-22105)
Cypress tests for ilab
Just added mock tests
* Added test for sections in ilab form
* Added test for testing errors
* Added test for Registered model label in pipeline run tables
* Added test for Artifacts to check registered model label and URL in details page.
=> Cypress Mock tests for InstructLab

frontend/src/__tests__/cypress/cypress/pages/pipelines/artifacts.ts, frontend/src/__tests__/cypress/cypress/pages/pipelines/executions.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/artifacts.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/executions.cy.ts, frontend/src/pages/pipelines/global/experiments/ExperimentPipelineRunLink.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/ArtifactDetails/ArtifactOverviewDetails.tsx, frontend/src/pages/pipelines/global/experiments/executions/details/ExecutionDetailsReferenceSection.tsx
https://issues.redhat.com/browse/RHOAIENG-16338
Fix the infinite loading state when Pipeline run fails to fetch
1. Check the execution detail page of which the pipeline run is deleted
2. Do same for artifact detail page
Updated and added cypress test
=> fix the infinitely loading state on execution and artifact page

frontend/src/components/pf-overrides/FormSection.scss, frontend/src/pages/pipelines/global/modelCustomization/FineTunePage.tsx, frontend/src/pages/pipelines/global/modelCustomization/FineTuneTaxonomySection.tsx, frontend/src/pages/pipelines/global/modelCustomization/HyperparameterSection/HyperparameterPageSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/BaseModelSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/baseModelSection/PipelineDetailsSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelConnectionSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelExistingConnectionField.tsx, frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelOciPathField.tsx, frontend/src/pages/pipelines/global/modelCustomization/fineTunedModelSection/FineTunedModelSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/landingPage/BaseSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/landingPage/LabMethodDescriptionSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/landingPage/ModelCustomization.tsx, frontend/src/pages/pipelines/global/modelCustomization/landingPage/NextStepsSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/landingPage/PrerequisitesSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/landingPage/ProjectSetupSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/teacherJudgeSection/JudgeModelSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/teacherJudgeSection/TeacherModelSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingHardwareProfileFormSection.tsx, frontend/src/pages/pipelines/global/modelCustomization/trainingHardwareSection/TrainingHardwareSection.tsx
JIRA: [RHOAIENG-21978](https://issues.redhat.com/browse/RHOAIENG-21978)
Updated everything mentioned in the doc https://docs.google.com/document/d/14J7WPk_GbTNfj621D0Y0dyp55nMqk4k3VTX2Gg9fh-U/edit?tab=t.0
Some highlights:
1. Update all the wording as mentioned
2. Change all the link style buttons that will open up a drawer from `inline` to the default one to remove the underscore of the button because they are action link buttons but not external links. Added a custom style `padding: 0` to these buttons.
3. Set model customization landing page max width to `470px` as requested by UX
4. Change all the `FormSection` to our override `FormSection` component to get a better spacing between section title and description. Also, changed the description font size from 12px to 14px. Confirmed with …
=> Model customization microcopy updates

backend/src/routes/api/integrations/nim/nimUtils.ts, frontend/src/components/OdhAppCard.tsx, frontend/src/components/OdhExploreCard.tsx, frontend/src/pages/exploreApplication/EnableModal.tsx, frontend/src/utilities/useEnableApplication.tsx
https://issues.redhat.com/browse/NVPE-237
https://issues.redhat.com/browse/NVPE-242
This PR fixes an infinite loop that occurred during the enablement process by annotating the API key secret with a timestamp. It also corrects the logic used to compare timestamps, ensuring the flow proceeds as expected.
Manually tested by entering the same incorrect API key twice to verify that the backend error message is displayed correctly without triggering an infinite loop.
Also tested with a valid API key to ensure the enablement process works as expected.
=> fix: infinite loop

backend/src/types.ts, docs/dashboard-config.md, frontend/src/__tests__/cypress/cypress/pages/workbench.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/projects/tabs/workbench.cy.ts, frontend/src/api/k8s/__tests__/notebooks.spec.ts, frontend/src/api/k8s/notebooks.ts, frontend/src/concepts/pipelines/elyra/ElyraInvalidVersionAlerts.tsx, frontend/src/k8sTypes.ts, frontend/src/pages/projects/notebook/NotebookImagePackageDetails.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookImageDisplayName.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookTableRow.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookUpdateImageCard.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookUpdateImageModal.tsx, frontend/src/pages/projects/screens/detail/notebooks/NotebookUpdateImageModalFooter.tsx, frontend/src/pages/projects/screens/detail/notebooks/__tests__/useNotebookImageData.spec.ts, frontend/src/pages/projects/screens/detail/notebooks/const.ts, frontend/src/pages/projects/screens/detail/notebooks/types.ts, frontend/src/pages/projects/screens/detail/notebooks/useNotebookImage.ts, frontend/src/pages/projects/screens/detail/notebooks/useNotebookImageData.ts, frontend/src/pages/projects/screens/spawner/SpawnerPage.tsx, frontend/src/pages/projects/screens/spawner/imageSelector/ImageStreamPopover.tsx, frontend/src/pages/projects/screens/spawner/imageSelector/ImageVersionTooltip.tsx, frontend/src/types.ts
https://issues.redhat.com/browse/RHOAIENG-348
Added the update and latest image labels, plus the update image modal
Create an outdated image version by adding this annotation: `'opendatahub.io/image-tag-outdated': 'true',`. There should be a label that appears and lets you update it through a modal.
Added cypress tests
=> Outdated image workbench alerts

frontend/src/__tests__/cypress/cypress/pages/modelRegistry/modelVersionDetails.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersion/modelVersionDetails.cy.ts, frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx, frontend/src/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionPipelineDescription.tsx
https://issues.redhat.com/browse/RHOAIENG-21130
Before enabling the pipeline run link in the model registry version details page checks whether user can have access to the project
1. Login as a user with no project access 
2. Go to model registry version detail page and look for the pipeline run link converted into text and a popover stating the reason
=> Access check before enabling link from MR to pipelinerun

frontend/src/__tests__/cypress/cypress/pages/components/NIMDeployModal.ts, frontend/src/components/ReplicaSection.tsx, frontend/src/pages/modelServing/screens/projects/ServingRuntimeModal/ServingRuntimeReplicaSection.tsx, frontend/src/pages/modelServing/screens/projects/kServeModal/KServeAutoscalerReplicaSection.tsx
Closes: [RHOAIENG-14567](https://issues.redhat.com/browse/RHOAIENG-14567)
Limits the amount of model server replicas to 3 numbers. Limits the user typing past 3, or using the + button to increase past 3. 
Tested locally
- Navigate to the Models tab under your Data Science Projects
- Either create or edit a model
- Scroll to "Number of model server replicas to deploy"
You should now be limited to 3 numbers for your input
Before:
After:
=> Set model server replica limit

frontend/src/app/__tests__/AboutDialog.spec.tsx
Closes https://issues.redhat.com/browse/RHOAIENG-23712
Fixed tests in frontend/src/app/__tests__/AboutDialog.spec.tsx
Now all  unit tests are passing (see below):
Run unit tests in frontend
=> Fix for AboutDialog unit tests

backend/package-lock.json, backend/package.json, frontend/package-lock.json, frontend/package.json, package-lock.json, package.json
JIRA: [RHOAIENG-2539](https://issues.redhat.com/browse/RHOAIENG-2539)
Update package.json file, changed/removed some outdated fields.
Deploy the built image on the cluster, make sure it didn't break anything.
N/A
=> Update package.json fields in root, frontend and backend folders

frontend/src/__tests__/cypress/cypress/pages/notebookImageSettings.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/home/homeAdmin.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/notebookImageSettings/notebookImageSettings.cy.ts, frontend/src/app/AppRoutes.tsx, frontend/src/pages/BYONImages/BYONImageAccelerators.tsx, frontend/src/pages/BYONImages/BYONImageHardwareProfiles.tsx, frontend/src/pages/BYONImages/BYONImageRoutes.tsx, frontend/src/pages/BYONImages/BYONImages.tsx, frontend/src/pages/BYONImages/EmptyBYONImages.tsx, frontend/src/pages/home/useEnableTeamSection.tsx, frontend/src/utilities/NavData.tsx
https://issues.redhat.com/browse/RHOAIENG-24098
Changed all occurrences of notebook to workbench in the settings page as described in the microcopy. I also changed the link to `/workbenchImages`
Manually. Try to replicate the changes.
N/A. Simple microcopy changes
=> Change path and occurrences of notebook to workbench in settings and nav

frontend/src/pages/projects/screens/detail/notebooks/NotebookImageDisplayName.tsx, frontend/src/pages/projects/screens/detail/notebooks/const.ts, frontend/src/pages/projects/screens/detail/notebooks/useNotebookImageData.ts
JIRA: [RHOAIENG-23619](https://issues.redhat.com/browse/RHOAIENG-23619)
Update wording for the latest image popover description as discussed.
1. Create a workbench with any latest notebook image
2. Go to the workbench list and click on the workbench with the `Latest` popover
3. Check the description is changed as mentioned in the ticket
N/A, one-liner microcopy update.
=> Update wording for the latest notebook image

CONTRIBUTING.md
Fixes:  https://issues.redhat.com/browse/RHOAIENG-19842
This pull request includes a small change to the `CONTRIBUTING.md` file. The change updates the `OC_PROJECT` environment variable and provides additional notes for setting it correctly.
* [`CONTRIBUTING.md`](diffhunk://#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055L76-R82): Changed `OC_PROJECT` from `my-project` to `opendatahub` and added a note explaining the options for setting this variable.
* 
=> Document OC_PROJECT environment variable in CONTRIBUTING

frontend/src/__mocks__/mockNimResource.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelServing/modelServingGlobal.cy.ts, frontend/src/__tests__/cypress/cypress/utils/nimUtils.ts, frontend/src/__tests__/cypress/cypress/utils/servingUtils.ts
https://issues.redhat.com/browse/RHOAIENG-22512
As part of the model serving refactor planning, we decided to audit our test coverage and fill in gaps. One major area we are lacking is in the Global Model Serving page when filtering by All Projects. This test adds a row for this table for each serving type we support and makes sure the page works correctly.
Ran locally
=> Add Model Serving Global mock test for all projects

frontend/src/__tests__/cypress/cypress/tests/e2e/applications/enabled/testNotebookAdministration.cy.ts, frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/testLaunchStandaloneNotebook.cy.ts
- Quarantine Notebook tests due to blocking bug https://issues.redhat.com/browse/RHOAIENG-24546
=> Quarantine Notebook Tests -  RHOAIENG-24546

frontend/src/__tests__/cypress/cypress/tests/mocked/navSidebar/navSidebar.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/navSidebar/navSidebar.ts, frontend/src/utilities/NavData.tsx
https://issues.redhat.com/browse/RHOAIENG-24578
If model related flags are disabled, then the models nav bar will disappear
Disable model catalog, model registry, model serving, and fine tuning. The models nav bar should disappear
added cypress tests
=> fixed models nav

frontend/src/pages/modelServing/screens/projects/kServeModal/KServeDeploymentModeDropdown.tsx
Related to the following:
https://issues.redhat.com/browse/NVPE-250
Updated the deployment mode tooltip with a detailed explanation of the differences between Advanced and Standard modes. 
Added a link to official documentation for additional context.
Tested Locally.
1. Deploy NIM
2. Read tooltip in NIM deploy modal 
Before:
After:
=> Improve deployment mode tooltip

.github/workflows/create-tag-release.yml
https://issues.redhat.com/browse/RHOAIENG-19838
Updated the GHA for tagging releases to do all the rest of the work detailed in our Confluence page for ODH Dashboard releases. The action will now create the release branch, tag the image in quay, create a draft PR with .env and params.env files updated, and create the release notes and tag in GitHub
I tested this on my own fork by changing the `QUAY_ODH_DASHBOARD_IMAGE_REPO` to my fork and adding the necessary secrets for my own quay repo. Please note I picked an arbitrary release number for my testing v5.1.3.
You can see this successful build for the output (might have to switch between 1st and 2nd run in the top right since the 1st run hit a 503 from GitHub on the Release-Notes): …
=> Edit GHA to automate ODH Dashboard releases

frontend/src/__tests__/cypress/cypress/tests/e2e/nim/testEnableNIM.cy.ts
=> Add the reference to Product bug and disable NIM enable TC

docs/external-redirects.md
https://issues.redhat.com/browse/RHOAIENG-24571
Added an explanation to the usage of `/external`.
Go to `external-redirects.md`
N/A, readme change
=> updated external redirect readme

frontend/src/concepts/connectionTypes/ExistingConnectionField.tsx, frontend/src/concepts/connectionTypes/NewConnectionField.tsx, frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionSection.tsx
Towards https://issues.redhat.com/browse/RHOAIENG-21535
The connections section is pretty large so I've decided to break down the changes into smaller bits. This is internal to the ConnectionsSection file so doesn't affect the consumers. 
The next 2 main steps would seperating out the ExistingModelConnection and also removing the 'data' object that is specific to model serving there.
Ran existing tests, testing manually by checking the model serving page
No changings since no new functionality is introduced
=> Connections section refactor part 1

frontend/src/concepts/modelRegistry/apiHooks/__tests__/useModelVersionsByRegisteredModel.spec.ts
Issue: https://issues.redhat.com/browse/RHOAIENG-24227
added unit test for useModelVersionsByRegisteredModel.ts
Ran unit test and passed
=> added unit tests for useModelVersionsByRegisteredModel

frontend/src/pages/modelServing/screens/projects/InferenceServiceModal/ConnectionOciPathField.tsx
https://issues.redhat.com/browse/RHOAIENG-24886
=> Fix http prefix removal for OCI path

frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/topology/pipelinesTopology.cy.ts
Fixes a lint error in cypress test case.
CI
N/A
=> fix lint error in cypress test case

frontend/config/webpack.common.js, frontend/package-lock.json, frontend/package.json, frontend/packages/modelServing/package.json, frontend/packages/modelServing/src/components/ModelsProjectDetailsTab.tsx, frontend/packages/modelServing/src/extension-points/index.ts, frontend/packages/modelServing/src/extensions.ts, frontend/packages/modelServing/tsconfig.json, frontend/packages/plugin-core/src/extension-points/index.ts, frontend/packages/plugin-core/src/extension-points/project-details.tsx, frontend/src/__mocks__/mockDashboardConfig.ts, frontend/src/concepts/areas/const.ts, frontend/src/concepts/areas/types.ts, frontend/src/concepts/projects/projectDetails/useModelServingTab.tsx, frontend/src/k8sTypes.ts, frontend/src/pages/projects/screens/detail/ProjectDetails.tsx, frontend/src/plugins/extensions.ts
Depends on https://github.com/opendatahub-io/odh-dashboard/pull/4138
Closes https://issues.redhat.com/browse/RHOAIENG-24577
Set's up the `frontend/packages/modelServing` with a simple obj for the project details tab, and is toggled with the `disableModelServingPlugin` flag. 
Turn on `disableModelServingPlugin` to `false`, navigate to the models projecte details tab and see some boilerplate text
none yet, it's dev only boilerplate and is defaulted to disabled
=> Base model serving package extension

backend/src/types.ts, backend/src/utils/constants.ts, backend/src/utils/resourceUtils.ts, frontend/src/k8sTypes.ts, manifests/README.md, manifests/common/crd/odhdashboardconfigs.opendatahub.io.crd.yaml, manifests/rhoai/addon/kustomization.yaml, manifests/rhoai/addon/params.env, manifests/rhoai/onprem/kustomization.yaml, manifests/rhoai/onprem/params.env, manifests/rhoai/shared/odhdashboardconfig/README.md, manifests/rhoai/shared/odhdashboardconfig/odhdashboardconfig.yaml
https://issues.redhat.com/browse/RHOAIENG-23172
Bringing a lot of clarity to how the OdhDashboardConfig works as it's a common confusion point. Added some varying changes around this concept to help explain the world better.
No visual changes
Hosting a new cluster and testing with a devflag on first install
N/A we don't have code around this effort.
https://jenkins-csb-rhods-opendatascience.dno.corp.redhat.com/job/cypress/job/dashboard-tests/1359/Test_20Reports/
=> Add, remove, update content around OdhDashboardConfig

.github/workflows/test.yml
Fix our PR test action to properly check for uncommitted changes. The check was run out of order.
CI
N/A
=> fix order of uncommitted changes check

frontend/src/__mocks__/mockDashboardConfig.ts, frontend/src/concepts/areas/const.ts, frontend/src/concepts/areas/types.ts, frontend/src/k8sTypes.ts
Closes: [RHOAIENG-25060](https://issues.redhat.com//browse/RHOAIENG-25060)
Adds a basic feature flag for llama stack chatbot.
Locally with ?devFeatureFlags using a temporary bit of code that inserts `<p>CHATBOT ENABLED!!!!</p>` onto the front-page when the feature flag is enabled, see screenshots below:
With no changes to the default feature flags:
With feature flag flipped using devFeatureFlags:
N/A 
=> Add feature flag for Llama Stack Chat Bot

backend/tsconfig.json, frontend/packages/tsconfig/tsconfig.json
Updates the tsconfig target for both backend and frontend to es2021
`npm run build`
CI
[e2e successful ](https://jenkins-csb-rhods-opendatascience.dno.corp.redhat.com/job/cypress/job/dashboard-tests/1458/)
N/A
=> update tsconfig target to es2021

frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/models/testDeployOCIModel.cy.ts
Add @bug tag to OCI test while we are working on the fix of 
https://issues.redhat.com/browse/RHOAIENG-25342#
N/A
Skips OCI test
=> test: quarantine OCI test

backend/tsconfig.json, frontend/packages/tsconfig/tsconfig.json, frontend/src/__mocks__/mockAxiosError.ts, frontend/src/__mocks__/mockK8sStatus.ts, frontend/src/__tests__/cypress/cypress/pages/projects.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/projects/projectDetails.cy.ts, frontend/src/__tests__/cypress/cypress/utils/mockUsers.ts, frontend/src/api/__tests__/errorUtils.spec.ts, frontend/src/api/errorUtils.ts, frontend/src/concepts/pipelines/context/PipelinesContext.tsx, frontend/src/pages/UnauthorizedError.tsx, frontend/src/pages/projects/ProjectDetailsContext.tsx, frontend/src/pages/projects/screens/detail/DetailsSection.tsx
https://issues.redhat.com/browse/RHOAIENG-13776
All 403 requests lead to the 403 page, which is updated to include the `Return to Home` button.
Open two windows. One with odh with clusteradminuser logged in and another with a regular user (it would be beneficial to have one with the odh launched from the openshift dashboard and another launched with localhost). 
To reproduce:
1. Give permissions to regular user in the permissions tab in projects.
2. Go to project details page logged in as regular user. 
3. Revoke said permissions using the cluster admin account.
4. Reload the page logged in as regular user. There should now be a 403 message. 
5. To see the error when the context is preserved, disable pipelines using the feature flag.
Updated and added cypress tests
Self checklist (all …
=> Added 403 pages for the project details page

backend/src/__tests__/resourceUtils.spec.ts, backend/src/types.ts, backend/src/utils/resourceUtils.ts, frontend/src/__mocks__/mockDscStatus.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/applications/application.cy.ts, frontend/src/app/App.tsx, frontend/src/types.ts
https://issues.redhat.com/browse/RHOAIENG-16249
The isRHOAI check does a namespace check against the static naming of `redhat-ods-applications`. This will not work if the customer changes this in the DSCI.
We should check against the DSC and check the product name. 
_Note: I checked the release name definition in rhods-operator: https://github.com/red-hat-data-services/rhods-operator/blob/main/pkg/cluster/const.go_ 
It's been tested locally for both opendatahub and self-managed rhoai platform types. 
From the homepage, opened the About Modal and verified the release name on the modal, and the value in backend in debug mode.
Added unit tests as well.
Unit tests.
=> Update isRHOAI to check product name in DSC

frontend/src/__mocks__/mlmd/mockGetArtifacts.ts, frontend/src/__mocks__/mockArtifactStorage.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/artifacts.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/pipelines/runs/compareRuns.cy.ts, frontend/src/concepts/pipelines/apiHooks/__tests__/useArtifactStorage.spec.ts, frontend/src/concepts/pipelines/apiHooks/useArtifactStorage.ts, frontend/src/concepts/pipelines/content/artifacts/ArtifactUriLink.tsx, frontend/src/concepts/pipelines/content/compareRuns/metricsSection/markdown/useFetchMarkdownMaps.ts, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/__tests__/PipelineRunDrawerRightContent.spec.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/ArtifactVisualization.tsx, frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/artifacts/__tests__/ArtifactNodeDrawerContent.spec.tsx, frontend/src/concepts/pipelines/types.ts, frontend/src/pages/pipelines/global/experiments/artifacts/__tests__/ArtifactDetails.spec.tsx, frontend/src/pages/pipelines/global/experiments/artifacts/__tests__/ArtifactsTable.spec.tsx
JIRA: [RHOAIENG-11412](https://issues.redhat.com/browse/RHOAIENG-11412)
I made some changes to the Artifact URI links behavior.
For metrics type, including `system.Metrics`, `system.ClassificationMetrics`, and `system.SlicedClassificationMetrics`, we don't show the URI anymore because it doesn't link to any S3 storage, so it's not a link, and it makes no sense to show them. I made a dash for that field.
For model type, which is 'system.Model', it shows only a downloadable link, which will trigger a download when clicked on.
For all the other types, we show both icons for previewing and downloading. Clicking on the first icon will open a new tab to preview the content that's returned by the S3 storage, and clicking on the second icon will download the resource.
1. Create some pipeline runs …
=> Add preview URI links to the specific artifact types

frontend/package-lock.json, manifests/common/apps/jupyter/create-jupyter-notebook-quickstart.yaml, manifests/common/apps/jupyter/jupyter-app.yaml, manifests/common/apps/jupyter/jupyter-docs.yaml, manifests/rhoai/addon/apps/nvidia/gpu-enabled-notebook-quickstart.yaml, manifests/rhoai/addon/apps/nvidia/gpu-quickstart.yaml, manifests/rhoai/addon/apps/starburst/starburst-galaxy-quickstart.yaml, manifests/rhoai/onprem/apps/starburst-enterprise/query-starburstenterprise-quickstart.yaml, manifests/rhoai/shared/apps/aikit/oneapi-aikit-notebook-quickstart.yaml, manifests/rhoai/shared/apps/openvino/openvino-inference-notebook.yaml, manifests/rhoai/shared/apps/pachyderm/pachyderm-beginner-tutorial-notebook.yaml
https://issues.redhat.com/browse/RHOAIENG-24795
Update usages of server and notebook server to workbench.
It is incredibly hard to organically show the tiles, so just code changes.
Manifest changes, no testing.
=> Update rhoai manifests

frontend/src/concepts/pipelines/NoPipelineServer.tsx, frontend/src/pages/projects/screens/detail/overview/trainModels/PipelinesCard.tsx
**JIRA:** https://issues.redhat.com/browse/RHOAIENG-21527
Altering the text / information when a user is in an empty pipeline page.
1. Content changes have been manually tested on `Pipelines, Runs, Executions, Artifacts,the pipelines tab of the project detail pages and Pipelines card` when pipeline server is not configured.
2. When the pipeline server is configured then there should not be any changes to the content.
Textual changes so no unit tests required.
=> RHOAIENG-21527: Provide clearer user understanding why a pipeline server is necessary

frontend/src/pages/home/modelCatalog/ModelCatalogHint.tsx
https://issues.redhat.com/browse/RHOAIENG-25600
Change the text in model catalog homepage hint to:
> Discover models that you can register, deploy, and customize.
Go to the homepage and check the text in the model catalog section. Delete `odh.dashboard.homepage.model.catalog.hint` key in local storage if hint is hidden.
Tested changes locally.
=> Model Catalog homepage hint: update text

frontend/src/__tests__/cypress/cypress/tests/e2e/dashboardNavigation/testManifestLinks.cy.ts, frontend/src/__tests__/cypress/cypress/utils/urlValidator.ts
https://issues.redhat.com/browse/RHOAIENG-9235
testManifestLinks.cy.ts should only accept successful responses (201, 202, 204), and for redirects (301, 302, 307, 308), and rate limiting (429) it should retry the request.
In Jenkins and locally.
E2E test `dashboardNavigation/testManifestLinks.cy.ts`
=> Make urlValidator.ts Retry if network errors occur

OWNERS
DevOps suggested solution for the Konflux CI issues.
Impacted PR: https://github.com/opendatahub-io/odh-dashboard/pull/4160
[Slack Conversation with DevOps](https://redhat-internal.slack.com/archives/C05NXTEHLGY/p1747424787712009)
=> DevOps solution to Konflux CI issues

frontend/src/pages/projects/screens/projects/LaunchJupyterButton.tsx
https://issues.redhat.com/browse/RHOAIENG-25585
Changed text from "Create standalone workbench" to "Start basic workbench"
Go to the projects page
N/A, microcopy update 
=> changed projects button text

frontend/src/concepts/pipelines/content/pipelinesDetails/pipelineRun/PipelineRunDetails.tsx
JIRA: https://issues.redhat.com/browse/RHOAIENG-18467
If there is no version for the pipeline run, we should get the pipeline spec from the `run.pipeline_spec`. The `pipelineSpec` in the changes is already defined as `version?.pipeline_spec ?? run?.pipeline_spec`, which meets our need. Simply replacing it with the current `version?.pipeline_spec` could fix this issue.
1. Follow the JIRA ticket description to create a run from a KfP instead of creating it from the dashboard UI
2. Go to the run details page, check the `Pipeline spec` tab
3. Make sure it's correctly rendered
N/A
=> Render correct pipeline spec when run is created from KfP

.github/workflows/release-odh-dashboard.yml
This should fix 2 of the issue found in our latest run of the GHA for ODH Dashboard release https://github.com/opendatahub-io/odh-dashboard/actions/runs/15111158536/job/42470785906
Fixed the quay repo name and set the short SHA to limit to 7 characters since that what we do in quay.
=> Fix GHA for ODH Dashboard releases

frontend/src/__mocks__/mockModelRegistry.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/registerModel.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/registerVersion.cy.ts, frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistrySettings/modelRegistrySettings.cy.ts, frontend/src/concepts/areas/__tests__/utils.spec.ts, frontend/src/concepts/areas/const.ts, frontend/src/k8sTypes.ts, frontend/src/pages/modelRegistrySettings/CreateModal.tsx
closes [RHOAIENG-26064](https://issues.redhat.com/browse/RHOAIENG-26064) 
Removed the use of Istio and switched to  oauthProxy. Also removed the use of Service Mesh in all the MR related areas. 
Create a new model registry from the dashboard and make sure it still becomes Available and its API connections still work (you can still see and interact with models on the model registry page). Also check that you can access MR if the ServiceMesh operator is not installed.
Make sure all tests pass
=> Istio and service mesh removal for MR 

frontend/src/components/markdown/MarkdownComponent.scss
closes [RHOAIENG-25648](https://issues.redhat.com/browse/RHOAIENG-25648)
**Earlier Issue**
**Fixed View**
https://github.com/user-attachments/assets/9d6190a0-6fd4-4ea6-8b00-9246b1a7acce
1. Visual Change
1. NA
=> fix(RHOAIENG-25648): added fix for overflow markdown catalog issue

frontend/src/__tests__/cypress/cypress/tests/e2e/dashboardNavigation/testManifestLinks.cy.ts
Quarantine of testManifestLinks test
locally
Test quarantine
=> Quarantine testManifestLinks tests

frontend/src/__tests__/cypress/cypress/tests/e2e/settings/clusterSettings/testAdminClusterSettings.cy.ts
https://issues.redhat.com/browse/RHOAIENG-26330
Quarantine test. 
Automation bug found during nightlies run (latest: dashboard-tests/1700)
Locally
Test Quarantine
=> Quarantine test in testAdminClusterSettings

frontend/src/__tests__/cypress/cypress/pages/clusterStorage.ts, frontend/src/__tests__/cypress/cypress/tests/e2e/storageClasses/clusterStorage.cy.ts
https://issues.redhat.com/browse/RHOAIENG-26876
Fix cluster storage error found during e2e testing.
Locally:
Jenkins:
dashboard-tests/1729/
Fix a test
Run it locally or using jenkins.
=> fix: cluster storage testing issue

manifests/common/crd/acceleratorprofiles.opendatahub.io.crd.yaml
Issue: https://issues.redhat.com/browse/RHOAIENG-26733
Changed the accelerator profiles CRD manifest file to make the v1 API show as deprecated as well as add a deprecation message.
Update the `acceleratorprofiles.dashboard.opendatahub.io` CRD YAML with the manifest file specified in `manifests/common/crd/acceleratorprofiles.opendatahub.io.crd.yaml` using either kubectl/oc apply or setting the DSC devflags.
No changes since just adding a deprecation warning text for backend.
=> Deprecate v1 version of AcceleratorProfile CRD

frontend/src/pages/projects/screens/spawner/storage/AccessModeRadio.tsx, frontend/src/pages/projects/screens/spawner/storage/getAccessModePopover.tsx, frontend/src/pages/storageClasses/constants.tsx
https://issues.redhat.com/browse/RHOAIENG-25975
Micro copy changes as shown in the doc
Go to the storage classes page, cluster storage list, and creation modal for cluster storage.
N/A, micro copy changes
=> made microcopy changes to storage classes

.github/workflows/authorized-tag-creators.txt
No code changes, just adding new enablers for Dashboard ODH release
=> Add new authorized tag creators

frontend/src/api/k8s/__tests__/notebooks.spec.ts, frontend/src/api/k8s/notebooks.ts, frontend/src/pages/projects/screens/spawner/SpawnerFooter.tsx
=> [v2.32.0-fixes]Update k8sMergePatchResource, replace undefined value with null to make it removable

frontend/src/pages/projects/screens/spawner/imageSelector/ImageSelectorField.tsx
(cherry picked from commit 0909a548e60dd4a2cb89c274466828f9df8ffae7)
https://issues.redhat.com/browse/RHOAIENG-30321
=> Add fix to image streams notebook enabling label (#4522)

frontend/src/__tests__/cypress/cypress/utils/models.ts
Cherry-pick fixes from https://github.com/opendatahub-io/odh-dashboard/pull/4682
=> Cherry pick E2E Test Fix

frontend/src/__tests__/cypress/cypress/tests/e2e/dataScienceProjects/workbenches/testWorkbenchCreation.cy.ts, frontend/src/__tests__/cypress/cypress/tests/e2e/distributedWorkloadMetrics/testWorkloadMetricsDefaultPageContents.cy.ts
https://issues.redhat.com/browse/RHOAIENG-32615
=> Quarantine/Unquarantine workbench/distributed workload metrics test- cherry-pick

.tekton/odh-mod-arch-modular-architecture-push.yaml
=> use correct SA for builds

frontend/src/utilities/const.ts
Closes: [RHOAIENG-29353](https://issues.redhat.com/browse/RHOAIENG-29353)
Cherry-pick from #4510 
Ran with `npm run start:dev:ext` and checked for documentation and community links in ODH
=> Cherry-pick: Avoid destructuring from process.env

packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/components/ModelCatalogCard.tsx, packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/components/ModelCatalogLabels.tsx, packages/model-registry/upstream/frontend/src/app/pages/modelCatalog/screens/ModelDetailsView.tsx
This PR cherry-picks onto `stable-2.x` two commits from the https://github.com/opendatahub-io/odh-dashboard/pull/4966 sync from kubeflow upstream to ODH main. These commits synced the changes from these two upstream PRs: https://github.com/kubeflow/model-registry/pull/1657 (to fix [RHOAIENG-34835](https://issues.redhat.com/browse/RHOAIENG-34835)) and https://github.com/kubeflow/model-registry/pull/1654 (to fix [RHOAIENG-34810](https://issues.redhat.com/browse/RHOAIENG-34810)). **We cannot cherry-pick the entire squashed sync commit from #4966 because it includes 3.0-specific layout changes.**
Tested by running backend, frontend and the federated MR package separately [as described in this doc](https://docs.google.com/document/d/1vP0B2KeF_XL6PSPN4h-LsBzoTES_Y3YlosFl_pN6rkw/edit?tab=t.0), …
=> Cherry-pick model catalog fixes: label rendering issue and a11y issue

package-lock.json, packages/gen-ai/frontend/package-lock.json
A continuation of https://github.com/opendatahub-io/odh-dashboard/pull/4871. We are upgrading the axios packages for the CVE. I will upgrade the package for model-registry in the upstream rather than in here.
Run `npm run build` in root, and in `/packages/gen-ai/frontend`. Also, run `npm audit` in all directories where the axios package is present. Note that in the model-registry folder, this will be fixed upstream.
N/A
=> fixed axios cve

frontend/src/__tests__/cypress/cypress/tests/mocked/featureStore/featureDataSources.cy.ts, frontend/src/components/lineage/Lineage.tsx, packages/feature-store/src/FeatureStore.tsx, packages/feature-store/src/components/FeatureStoreLineageToolbar.tsx, packages/feature-store/src/screens/dataSources/dataSourceDetails/DataSourceDetailsPage.tsx, packages/feature-store/src/screens/dataSources/dataSourceDetails/DataSourceDetailsView.tsx, packages/feature-store/src/screens/dataSources/dataSourceDetails/DataSourceTabs.tsx
This PR contains cherry-pick changes from https://github.com/opendatahub-io/odh-dashboard/pull/4975 and https://github.com/opendatahub-io/odh-dashboard/pull/4992 to stable-2.x, see those PR's for complete details
(Minor data source badge and lineage toolbar fixes)
NA
NA
NA
=> Cherry-pick - Featurestore(Review changes -2)

frontend/src/concepts/distributedWorkloads/DistributedWorkloadsContext.tsx, frontend/src/concepts/distributedWorkloads/PermissionsNotSet.tsx
See main PR for details: https://github.com/opendatahub-io/odh-dashboard/pull/5047
https://issues.redhat.com/browse/RHOAIENG-35106
=> Fix UX issue with DW permissions
